(define (problem prb-426_d49_p-VAL3-n48-r1w25o9c8-2) (:domain Rover)
(:objects
	general - Lander
	colour high_res low_res - Mode
	rover0 - Rover
	rover0store - Store
	waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 waypoint7 waypoint8 waypoint9 waypoint10 waypoint11 waypoint12 waypoint13 waypoint14 waypoint15 waypoint16 waypoint17 waypoint18 waypoint19 waypoint20 waypoint21 waypoint22 waypoint23 waypoint24 - Waypoint
	camera0 camera1 camera2 camera3 camera4 camera5 camera6 camera7 - Camera
	objective0 objective1 objective2 objective3 objective4 objective5 objective6 objective7 objective8 - Objective
	)
(:init
(visible waypoint0 waypoint10)
(visible waypoint10 waypoint0)
(visible waypoint0 waypoint13)
(visible waypoint13 waypoint0)
(visible waypoint0 waypoint19)
(visible waypoint19 waypoint0)
(visible waypoint0 waypoint21)
(visible waypoint21 waypoint0)
(visible waypoint2 waypoint1)
(visible waypoint1 waypoint2)
(visible waypoint2 waypoint3)
(visible waypoint3 waypoint2)
(visible waypoint2 waypoint13)
(visible waypoint13 waypoint2)
(visible waypoint2 waypoint16)
(visible waypoint16 waypoint2)
(visible waypoint2 waypoint20)
(visible waypoint20 waypoint2)
(visible waypoint3 waypoint6)
(visible waypoint6 waypoint3)
(visible waypoint3 waypoint8)
(visible waypoint8 waypoint3)
(visible waypoint3 waypoint15)
(visible waypoint15 waypoint3)
(visible waypoint3 waypoint16)
(visible waypoint16 waypoint3)
(visible waypoint3 waypoint19)
(visible waypoint19 waypoint3)
(visible waypoint3 waypoint24)
(visible waypoint24 waypoint3)
(visible waypoint4 waypoint14)
(visible waypoint14 waypoint4)
(visible waypoint4 waypoint19)
(visible waypoint19 waypoint4)
(visible waypoint5 waypoint7)
(visible waypoint7 waypoint5)
(visible waypoint5 waypoint24)
(visible waypoint24 waypoint5)
(visible waypoint6 waypoint1)
(visible waypoint1 waypoint6)
(visible waypoint6 waypoint2)
(visible waypoint2 waypoint6)
(visible waypoint6 waypoint5)
(visible waypoint5 waypoint6)
(visible waypoint6 waypoint8)
(visible waypoint8 waypoint6)
(visible waypoint6 waypoint17)
(visible waypoint17 waypoint6)
(visible waypoint6 waypoint18)
(visible waypoint18 waypoint6)
(visible waypoint7 waypoint9)
(visible waypoint9 waypoint7)
(visible waypoint7 waypoint11)
(visible waypoint11 waypoint7)
(visible waypoint7 waypoint14)
(visible waypoint14 waypoint7)
(visible waypoint7 waypoint23)
(visible waypoint23 waypoint7)
(visible waypoint8 waypoint0)
(visible waypoint0 waypoint8)
(visible waypoint8 waypoint2)
(visible waypoint2 waypoint8)
(visible waypoint8 waypoint10)
(visible waypoint10 waypoint8)
(visible waypoint8 waypoint13)
(visible waypoint13 waypoint8)
(visible waypoint8 waypoint14)
(visible waypoint14 waypoint8)
(visible waypoint8 waypoint19)
(visible waypoint19 waypoint8)
(visible waypoint8 waypoint21)
(visible waypoint21 waypoint8)
(visible waypoint8 waypoint22)
(visible waypoint22 waypoint8)
(visible waypoint8 waypoint24)
(visible waypoint24 waypoint8)
(visible waypoint9 waypoint8)
(visible waypoint8 waypoint9)
(visible waypoint9 waypoint13)
(visible waypoint13 waypoint9)
(visible waypoint9 waypoint14)
(visible waypoint14 waypoint9)
(visible waypoint9 waypoint22)
(visible waypoint22 waypoint9)
(visible waypoint9 waypoint24)
(visible waypoint24 waypoint9)
(visible waypoint10 waypoint1)
(visible waypoint1 waypoint10)
(visible waypoint10 waypoint3)
(visible waypoint3 waypoint10)
(visible waypoint10 waypoint5)
(visible waypoint5 waypoint10)
(visible waypoint10 waypoint12)
(visible waypoint12 waypoint10)
(visible waypoint10 waypoint19)
(visible waypoint19 waypoint10)
(visible waypoint10 waypoint20)
(visible waypoint20 waypoint10)
(visible waypoint11 waypoint5)
(visible waypoint5 waypoint11)
(visible waypoint11 waypoint21)
(visible waypoint21 waypoint11)
(visible waypoint13 waypoint17)
(visible waypoint17 waypoint13)
(visible waypoint14 waypoint12)
(visible waypoint12 waypoint14)
(visible waypoint14 waypoint13)
(visible waypoint13 waypoint14)
(visible waypoint14 waypoint16)
(visible waypoint16 waypoint14)
(visible waypoint15 waypoint4)
(visible waypoint4 waypoint15)
(visible waypoint15 waypoint19)
(visible waypoint19 waypoint15)
(visible waypoint15 waypoint21)
(visible waypoint21 waypoint15)
(visible waypoint16 waypoint5)
(visible waypoint5 waypoint16)
(visible waypoint16 waypoint8)
(visible waypoint8 waypoint16)
(visible waypoint16 waypoint15)
(visible waypoint15 waypoint16)
(visible waypoint16 waypoint17)
(visible waypoint17 waypoint16)
(visible waypoint16 waypoint19)
(visible waypoint19 waypoint16)
(visible waypoint16 waypoint20)
(visible waypoint20 waypoint16)
(visible waypoint17 waypoint1)
(visible waypoint1 waypoint17)
(visible waypoint17 waypoint7)
(visible waypoint7 waypoint17)
(visible waypoint17 waypoint8)
(visible waypoint8 waypoint17)
(visible waypoint17 waypoint14)
(visible waypoint14 waypoint17)
(visible waypoint17 waypoint20)
(visible waypoint20 waypoint17)
(visible waypoint18 waypoint3)
(visible waypoint3 waypoint18)
(visible waypoint18 waypoint17)
(visible waypoint17 waypoint18)
(visible waypoint19 waypoint1)
(visible waypoint1 waypoint19)
(visible waypoint19 waypoint13)
(visible waypoint13 waypoint19)
(visible waypoint19 waypoint17)
(visible waypoint17 waypoint19)
(visible waypoint20 waypoint0)
(visible waypoint0 waypoint20)
(visible waypoint20 waypoint6)
(visible waypoint6 waypoint20)
(visible waypoint20 waypoint12)
(visible waypoint12 waypoint20)
(visible waypoint21 waypoint4)
(visible waypoint4 waypoint21)
(visible waypoint21 waypoint6)
(visible waypoint6 waypoint21)
(visible waypoint21 waypoint7)
(visible waypoint7 waypoint21)
(visible waypoint21 waypoint16)
(visible waypoint16 waypoint21)
(visible waypoint21 waypoint18)
(visible waypoint18 waypoint21)
(visible waypoint22 waypoint14)
(visible waypoint14 waypoint22)
(visible waypoint22 waypoint23)
(visible waypoint23 waypoint22)
(visible waypoint23 waypoint1)
(visible waypoint1 waypoint23)
(visible waypoint23 waypoint3)
(visible waypoint3 waypoint23)
(visible waypoint23 waypoint5)
(visible waypoint5 waypoint23)
(visible waypoint23 waypoint8)
(visible waypoint8 waypoint23)
(visible waypoint23 waypoint9)
(visible waypoint9 waypoint23)
(visible waypoint23 waypoint14)
(visible waypoint14 waypoint23)
(visible waypoint23 waypoint16)
(visible waypoint16 waypoint23)
(visible waypoint23 waypoint19)
(visible waypoint19 waypoint23)
(visible waypoint24 waypoint0)
(visible waypoint0 waypoint24)
(visible waypoint24 waypoint4)
(visible waypoint4 waypoint24)
(visible waypoint24 waypoint7)
(visible waypoint7 waypoint24)
(visible waypoint24 waypoint13)
(visible waypoint13 waypoint24)
(visible waypoint24 waypoint16)
(visible waypoint16 waypoint24)
(visible waypoint24 waypoint19)
(visible waypoint19 waypoint24)
(at_lander general waypoint14)
(store_of rover0store rover0)
(equipped_for_soil_analysis rover0)
(equipped_for_rock_analysis rover0)
(equipped_for_imaging rover0)
(can_traverse rover0 waypoint9 waypoint7)
(can_traverse rover0 waypoint7 waypoint9)
(can_traverse rover0 waypoint9 waypoint8)
(can_traverse rover0 waypoint8 waypoint9)
(can_traverse rover0 waypoint9 waypoint13)
(can_traverse rover0 waypoint13 waypoint9)
(can_traverse rover0 waypoint9 waypoint14)
(can_traverse rover0 waypoint14 waypoint9)
(can_traverse rover0 waypoint9 waypoint22)
(can_traverse rover0 waypoint22 waypoint9)
(can_traverse rover0 waypoint9 waypoint23)
(can_traverse rover0 waypoint23 waypoint9)
(can_traverse rover0 waypoint7 waypoint11)
(can_traverse rover0 waypoint11 waypoint7)
(can_traverse rover0 waypoint7 waypoint17)
(can_traverse rover0 waypoint17 waypoint7)
(can_traverse rover0 waypoint7 waypoint21)
(can_traverse rover0 waypoint21 waypoint7)
(can_traverse rover0 waypoint7 waypoint24)
(can_traverse rover0 waypoint24 waypoint7)
(can_traverse rover0 waypoint8 waypoint0)
(can_traverse rover0 waypoint0 waypoint8)
(can_traverse rover0 waypoint8 waypoint2)
(can_traverse rover0 waypoint2 waypoint8)
(can_traverse rover0 waypoint8 waypoint3)
(can_traverse rover0 waypoint3 waypoint8)
(can_traverse rover0 waypoint8 waypoint10)
(can_traverse rover0 waypoint10 waypoint8)
(can_traverse rover0 waypoint8 waypoint16)
(can_traverse rover0 waypoint16 waypoint8)
(can_traverse rover0 waypoint13 waypoint19)
(can_traverse rover0 waypoint19 waypoint13)
(can_traverse rover0 waypoint14 waypoint4)
(can_traverse rover0 waypoint4 waypoint14)
(can_traverse rover0 waypoint14 waypoint12)
(can_traverse rover0 waypoint12 waypoint14)
(can_traverse rover0 waypoint23 waypoint1)
(can_traverse rover0 waypoint1 waypoint23)
(can_traverse rover0 waypoint23 waypoint5)
(can_traverse rover0 waypoint5 waypoint23)
(on_board camera0 rover0)
(calibration_target camera0 objective7)
(supports camera0 colour)
(supports camera0 high_res)
(supports camera0 low_res)
(on_board camera1 rover0)
(calibration_target camera1 objective1)
(supports camera1 high_res)
(on_board camera2 rover0)
(calibration_target camera2 objective2)
(supports camera2 low_res)
(on_board camera3 rover0)
(calibration_target camera3 objective0)
(supports camera3 colour)
(supports camera3 high_res)
(supports camera3 low_res)
(on_board camera4 rover0)
(calibration_target camera4 objective8)
(supports camera4 high_res)
(supports camera4 low_res)
(on_board camera5 rover0)
(calibration_target camera5 objective5)
(supports camera5 colour)
(on_board camera6 rover0)
(calibration_target camera6 objective2)
(supports camera6 colour)
(supports camera6 high_res)
(on_board camera7 rover0)
(calibration_target camera7 objective5)
(supports camera7 colour)
(supports camera7 high_res)
(supports camera7 low_res)
(visible_from objective0 waypoint9)
(visible_from objective0 waypoint16)
(visible_from objective0 waypoint17)
(visible_from objective0 waypoint21)
(visible_from objective0 waypoint24)
(visible_from objective1 waypoint6)
(visible_from objective1 waypoint11)
(visible_from objective1 waypoint13)
(visible_from objective1 waypoint16)
(visible_from objective1 waypoint23)
(visible_from objective2 waypoint4)
(visible_from objective2 waypoint6)
(visible_from objective2 waypoint7)
(visible_from objective2 waypoint9)
(visible_from objective2 waypoint10)
(visible_from objective2 waypoint11)
(visible_from objective2 waypoint12)
(visible_from objective2 waypoint13)
(visible_from objective2 waypoint14)
(visible_from objective2 waypoint18)
(visible_from objective2 waypoint19)
(visible_from objective2 waypoint20)
(visible_from objective2 waypoint21)
(visible_from objective2 waypoint22)
(visible_from objective2 waypoint23)
(visible_from objective3 waypoint4)
(visible_from objective3 waypoint7)
(visible_from objective3 waypoint12)
(visible_from objective3 waypoint16)
(visible_from objective3 waypoint17)
(visible_from objective3 waypoint18)
(visible_from objective3 waypoint21)
(visible_from objective3 waypoint23)
(visible_from objective4 waypoint1)
(visible_from objective4 waypoint3)
(visible_from objective4 waypoint4)
(visible_from objective4 waypoint8)
(visible_from objective4 waypoint9)
(visible_from objective4 waypoint10)
(visible_from objective4 waypoint14)
(visible_from objective4 waypoint15)
(visible_from objective4 waypoint16)
(visible_from objective4 waypoint18)
(visible_from objective4 waypoint20)
(visible_from objective4 waypoint21)
(visible_from objective4 waypoint23)
(visible_from objective4 waypoint24)
(visible_from objective5 waypoint0)
(visible_from objective5 waypoint2)
(visible_from objective5 waypoint4)
(visible_from objective5 waypoint6)
(visible_from objective5 waypoint7)
(visible_from objective5 waypoint11)
(visible_from objective5 waypoint12)
(visible_from objective5 waypoint15)
(visible_from objective5 waypoint16)
(visible_from objective5 waypoint18)
(visible_from objective5 waypoint19)
(visible_from objective5 waypoint23)
(visible_from objective6 waypoint0)
(visible_from objective6 waypoint2)
(visible_from objective6 waypoint3)
(visible_from objective6 waypoint5)
(visible_from objective6 waypoint6)
(visible_from objective6 waypoint7)
(visible_from objective6 waypoint8)
(visible_from objective6 waypoint9)
(visible_from objective6 waypoint13)
(visible_from objective6 waypoint15)
(visible_from objective6 waypoint18)
(visible_from objective6 waypoint19)
(visible_from objective6 waypoint21)
(visible_from objective6 waypoint22)
(visible_from objective6 waypoint24)
(visible_from objective7 waypoint1)
(visible_from objective7 waypoint2)
(visible_from objective7 waypoint4)
(visible_from objective7 waypoint5)
(visible_from objective7 waypoint8)
(visible_from objective7 waypoint12)
(visible_from objective7 waypoint14)
(visible_from objective7 waypoint16)
(visible_from objective7 waypoint18)
(visible_from objective7 waypoint20)
(visible_from objective7 waypoint21)
(visible_from objective7 waypoint22)
(visible_from objective7 waypoint23)
(visible_from objective7 waypoint24)
(visible_from objective8 waypoint1)
(visible_from objective8 waypoint2)
(visible_from objective8 waypoint4)
(visible_from objective8 waypoint6)
(visible_from objective8 waypoint7)
(visible_from objective8 waypoint9)
(visible_from objective8 waypoint10)
(visible_from objective8 waypoint11)
(visible_from objective8 waypoint12)
(visible_from objective8 waypoint13)
(visible_from objective8 waypoint14)
(visible_from objective8 waypoint17)
(visible_from objective8 waypoint19)
(visible_from objective8 waypoint21)
(visible_from objective8 waypoint22)
(visible_from objective8 waypoint23)
(visible_from objective8 waypoint24)
(at_soil_sample waypoint0)
(at_rock_sample waypoint0)
(at_soil_sample waypoint1)
(at_soil_sample waypoint4)
(at_soil_sample waypoint5)
(at_rock_sample waypoint5)
(at_rock_sample waypoint9)
(at_soil_sample waypoint10)
(at_rock_sample waypoint10)
(at_soil_sample waypoint11)
(at_rock_sample waypoint11)
(at_soil_sample waypoint12)
(at_soil_sample waypoint13)
(at_rock_sample waypoint13)
(at_soil_sample waypoint14)
(at_rock_sample waypoint14)
(at_rock_sample waypoint15)
(at_rock_sample waypoint17)
(at_rock_sample waypoint18)
(at_soil_sample waypoint20)
(at_rock_sample waypoint20)
(at_soil_sample waypoint21)
(at_rock_sample waypoint21)
(at_soil_sample waypoint22)
(at_rock_sample waypoint22)
(at_rock_sample waypoint23)
(channel_free general)
(at rover0 waypoint9)
(available rover0)
(empty rover0store)
(communicated_image_data objective6 low_res)
(calibrated camera6 rover0)
(have_image rover0 objective6 low_res)
(have_image rover0 objective4 colour)
)

(:goal (and
(communicated_soil_data waypoint0)
(communicated_soil_data waypoint4)
(communicated_soil_data waypoint1)
(communicated_soil_data waypoint11)
(communicated_rock_data waypoint17)
(communicated_rock_data waypoint9)
(communicated_rock_data waypoint21)
(communicated_rock_data waypoint5)
(communicated_image_data objective8 high_res)
(communicated_image_data objective6 low_res)
(communicated_image_data objective7 colour)
(communicated_image_data objective4 colour)
	)
)
)
