(define (problem prb-206_d07_p-TST3-n66-r1w35o10c15-2) (:domain Rover)
(:objects
	general - Lander
	colour high_res low_res - Mode
	rover0 - Rover
	rover0store - Store
	waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 waypoint7 waypoint8 waypoint9 waypoint10 waypoint11 waypoint12 waypoint13 waypoint14 waypoint15 waypoint16 waypoint17 waypoint18 waypoint19 waypoint20 waypoint21 waypoint22 waypoint23 waypoint24 waypoint25 waypoint26 waypoint27 waypoint28 waypoint29 waypoint30 waypoint31 waypoint32 waypoint33 waypoint34 - Waypoint
	camera0 camera1 camera2 camera3 camera4 camera5 camera6 camera7 camera8 camera9 camera10 camera11 camera12 camera13 camera14 - Camera
	objective0 objective1 objective2 objective3 objective4 objective5 objective6 objective7 objective8 objective9 - Objective
	)
(:init
(visible waypoint0 waypoint15)
(visible waypoint15 waypoint0)
(visible waypoint0 waypoint27)
(visible waypoint27 waypoint0)
(visible waypoint0 waypoint30)
(visible waypoint30 waypoint0)
(visible waypoint1 waypoint6)
(visible waypoint6 waypoint1)
(visible waypoint1 waypoint18)
(visible waypoint18 waypoint1)
(visible waypoint1 waypoint26)
(visible waypoint26 waypoint1)
(visible waypoint1 waypoint29)
(visible waypoint29 waypoint1)
(visible waypoint2 waypoint6)
(visible waypoint6 waypoint2)
(visible waypoint2 waypoint34)
(visible waypoint34 waypoint2)
(visible waypoint3 waypoint1)
(visible waypoint1 waypoint3)
(visible waypoint3 waypoint4)
(visible waypoint4 waypoint3)
(visible waypoint3 waypoint12)
(visible waypoint12 waypoint3)
(visible waypoint3 waypoint23)
(visible waypoint23 waypoint3)
(visible waypoint3 waypoint28)
(visible waypoint28 waypoint3)
(visible waypoint4 waypoint19)
(visible waypoint19 waypoint4)
(visible waypoint4 waypoint25)
(visible waypoint25 waypoint4)
(visible waypoint4 waypoint27)
(visible waypoint27 waypoint4)
(visible waypoint4 waypoint34)
(visible waypoint34 waypoint4)
(visible waypoint5 waypoint11)
(visible waypoint11 waypoint5)
(visible waypoint5 waypoint21)
(visible waypoint21 waypoint5)
(visible waypoint5 waypoint22)
(visible waypoint22 waypoint5)
(visible waypoint5 waypoint27)
(visible waypoint27 waypoint5)
(visible waypoint5 waypoint28)
(visible waypoint28 waypoint5)
(visible waypoint5 waypoint30)
(visible waypoint30 waypoint5)
(visible waypoint6 waypoint16)
(visible waypoint16 waypoint6)
(visible waypoint6 waypoint17)
(visible waypoint17 waypoint6)
(visible waypoint6 waypoint20)
(visible waypoint20 waypoint6)
(visible waypoint6 waypoint21)
(visible waypoint21 waypoint6)
(visible waypoint7 waypoint11)
(visible waypoint11 waypoint7)
(visible waypoint8 waypoint12)
(visible waypoint12 waypoint8)
(visible waypoint8 waypoint28)
(visible waypoint28 waypoint8)
(visible waypoint8 waypoint34)
(visible waypoint34 waypoint8)
(visible waypoint9 waypoint2)
(visible waypoint2 waypoint9)
(visible waypoint9 waypoint3)
(visible waypoint3 waypoint9)
(visible waypoint9 waypoint4)
(visible waypoint4 waypoint9)
(visible waypoint9 waypoint7)
(visible waypoint7 waypoint9)
(visible waypoint9 waypoint20)
(visible waypoint20 waypoint9)
(visible waypoint9 waypoint24)
(visible waypoint24 waypoint9)
(visible waypoint9 waypoint26)
(visible waypoint26 waypoint9)
(visible waypoint10 waypoint4)
(visible waypoint4 waypoint10)
(visible waypoint10 waypoint13)
(visible waypoint13 waypoint10)
(visible waypoint10 waypoint20)
(visible waypoint20 waypoint10)
(visible waypoint10 waypoint23)
(visible waypoint23 waypoint10)
(visible waypoint10 waypoint26)
(visible waypoint26 waypoint10)
(visible waypoint11 waypoint3)
(visible waypoint3 waypoint11)
(visible waypoint11 waypoint22)
(visible waypoint22 waypoint11)
(visible waypoint11 waypoint27)
(visible waypoint27 waypoint11)
(visible waypoint11 waypoint32)
(visible waypoint32 waypoint11)
(visible waypoint11 waypoint34)
(visible waypoint34 waypoint11)
(visible waypoint12 waypoint0)
(visible waypoint0 waypoint12)
(visible waypoint12 waypoint10)
(visible waypoint10 waypoint12)
(visible waypoint12 waypoint14)
(visible waypoint14 waypoint12)
(visible waypoint12 waypoint19)
(visible waypoint19 waypoint12)
(visible waypoint12 waypoint24)
(visible waypoint24 waypoint12)
(visible waypoint12 waypoint31)
(visible waypoint31 waypoint12)
(visible waypoint13 waypoint11)
(visible waypoint11 waypoint13)
(visible waypoint13 waypoint18)
(visible waypoint18 waypoint13)
(visible waypoint13 waypoint31)
(visible waypoint31 waypoint13)
(visible waypoint13 waypoint32)
(visible waypoint32 waypoint13)
(visible waypoint13 waypoint34)
(visible waypoint34 waypoint13)
(visible waypoint14 waypoint2)
(visible waypoint2 waypoint14)
(visible waypoint14 waypoint4)
(visible waypoint4 waypoint14)
(visible waypoint14 waypoint17)
(visible waypoint17 waypoint14)
(visible waypoint14 waypoint27)
(visible waypoint27 waypoint14)
(visible waypoint14 waypoint29)
(visible waypoint29 waypoint14)
(visible waypoint14 waypoint30)
(visible waypoint30 waypoint14)
(visible waypoint15 waypoint4)
(visible waypoint4 waypoint15)
(visible waypoint15 waypoint7)
(visible waypoint7 waypoint15)
(visible waypoint15 waypoint8)
(visible waypoint8 waypoint15)
(visible waypoint16 waypoint18)
(visible waypoint18 waypoint16)
(visible waypoint16 waypoint30)
(visible waypoint30 waypoint16)
(visible waypoint18 waypoint15)
(visible waypoint15 waypoint18)
(visible waypoint18 waypoint24)
(visible waypoint24 waypoint18)
(visible waypoint18 waypoint26)
(visible waypoint26 waypoint18)
(visible waypoint19 waypoint18)
(visible waypoint18 waypoint19)
(visible waypoint19 waypoint27)
(visible waypoint27 waypoint19)
(visible waypoint19 waypoint29)
(visible waypoint29 waypoint19)
(visible waypoint20 waypoint11)
(visible waypoint11 waypoint20)
(visible waypoint20 waypoint17)
(visible waypoint17 waypoint20)
(visible waypoint20 waypoint19)
(visible waypoint19 waypoint20)
(visible waypoint20 waypoint21)
(visible waypoint21 waypoint20)
(visible waypoint20 waypoint22)
(visible waypoint22 waypoint20)
(visible waypoint20 waypoint29)
(visible waypoint29 waypoint20)
(visible waypoint21 waypoint25)
(visible waypoint25 waypoint21)
(visible waypoint21 waypoint27)
(visible waypoint27 waypoint21)
(visible waypoint21 waypoint29)
(visible waypoint29 waypoint21)
(visible waypoint22 waypoint1)
(visible waypoint1 waypoint22)
(visible waypoint22 waypoint8)
(visible waypoint8 waypoint22)
(visible waypoint22 waypoint16)
(visible waypoint16 waypoint22)
(visible waypoint22 waypoint23)
(visible waypoint23 waypoint22)
(visible waypoint22 waypoint28)
(visible waypoint28 waypoint22)
(visible waypoint22 waypoint34)
(visible waypoint34 waypoint22)
(visible waypoint23 waypoint9)
(visible waypoint9 waypoint23)
(visible waypoint23 waypoint11)
(visible waypoint11 waypoint23)
(visible waypoint23 waypoint19)
(visible waypoint19 waypoint23)
(visible waypoint23 waypoint21)
(visible waypoint21 waypoint23)
(visible waypoint23 waypoint27)
(visible waypoint27 waypoint23)
(visible waypoint24 waypoint2)
(visible waypoint2 waypoint24)
(visible waypoint24 waypoint19)
(visible waypoint19 waypoint24)
(visible waypoint24 waypoint23)
(visible waypoint23 waypoint24)
(visible waypoint24 waypoint25)
(visible waypoint25 waypoint24)
(visible waypoint24 waypoint28)
(visible waypoint28 waypoint24)
(visible waypoint24 waypoint33)
(visible waypoint33 waypoint24)
(visible waypoint25 waypoint5)
(visible waypoint5 waypoint25)
(visible waypoint26 waypoint24)
(visible waypoint24 waypoint26)
(visible waypoint26 waypoint25)
(visible waypoint25 waypoint26)
(visible waypoint27 waypoint2)
(visible waypoint2 waypoint27)
(visible waypoint27 waypoint18)
(visible waypoint18 waypoint27)
(visible waypoint27 waypoint29)
(visible waypoint29 waypoint27)
(visible waypoint28 waypoint0)
(visible waypoint0 waypoint28)
(visible waypoint28 waypoint9)
(visible waypoint9 waypoint28)
(visible waypoint28 waypoint15)
(visible waypoint15 waypoint28)
(visible waypoint28 waypoint16)
(visible waypoint16 waypoint28)
(visible waypoint28 waypoint21)
(visible waypoint21 waypoint28)
(visible waypoint28 waypoint32)
(visible waypoint32 waypoint28)
(visible waypoint29 waypoint6)
(visible waypoint6 waypoint29)
(visible waypoint29 waypoint9)
(visible waypoint9 waypoint29)
(visible waypoint29 waypoint11)
(visible waypoint11 waypoint29)
(visible waypoint29 waypoint25)
(visible waypoint25 waypoint29)
(visible waypoint29 waypoint26)
(visible waypoint26 waypoint29)
(visible waypoint30 waypoint23)
(visible waypoint23 waypoint30)
(visible waypoint31 waypoint11)
(visible waypoint11 waypoint31)
(visible waypoint31 waypoint19)
(visible waypoint19 waypoint31)
(visible waypoint31 waypoint32)
(visible waypoint32 waypoint31)
(visible waypoint32 waypoint1)
(visible waypoint1 waypoint32)
(visible waypoint32 waypoint2)
(visible waypoint2 waypoint32)
(visible waypoint32 waypoint7)
(visible waypoint7 waypoint32)
(visible waypoint32 waypoint8)
(visible waypoint8 waypoint32)
(visible waypoint32 waypoint12)
(visible waypoint12 waypoint32)
(visible waypoint32 waypoint19)
(visible waypoint19 waypoint32)
(visible waypoint32 waypoint20)
(visible waypoint20 waypoint32)
(visible waypoint32 waypoint22)
(visible waypoint22 waypoint32)
(visible waypoint33 waypoint0)
(visible waypoint0 waypoint33)
(visible waypoint33 waypoint4)
(visible waypoint4 waypoint33)
(visible waypoint33 waypoint6)
(visible waypoint6 waypoint33)
(visible waypoint33 waypoint13)
(visible waypoint13 waypoint33)
(visible waypoint33 waypoint16)
(visible waypoint16 waypoint33)
(visible waypoint33 waypoint19)
(visible waypoint19 waypoint33)
(visible waypoint33 waypoint26)
(visible waypoint26 waypoint33)
(visible waypoint34 waypoint10)
(visible waypoint10 waypoint34)
(visible waypoint34 waypoint23)
(visible waypoint23 waypoint34)
(visible waypoint34 waypoint26)
(visible waypoint26 waypoint34)
(visible waypoint34 waypoint31)
(visible waypoint31 waypoint34)
(at_lander general waypoint28)
(store_of rover0store rover0)
(equipped_for_soil_analysis rover0)
(equipped_for_rock_analysis rover0)
(equipped_for_imaging rover0)
(can_traverse rover0 waypoint33 waypoint0)
(can_traverse rover0 waypoint0 waypoint33)
(can_traverse rover0 waypoint33 waypoint6)
(can_traverse rover0 waypoint6 waypoint33)
(can_traverse rover0 waypoint33 waypoint13)
(can_traverse rover0 waypoint13 waypoint33)
(can_traverse rover0 waypoint33 waypoint16)
(can_traverse rover0 waypoint16 waypoint33)
(can_traverse rover0 waypoint33 waypoint24)
(can_traverse rover0 waypoint24 waypoint33)
(can_traverse rover0 waypoint0 waypoint12)
(can_traverse rover0 waypoint12 waypoint0)
(can_traverse rover0 waypoint0 waypoint15)
(can_traverse rover0 waypoint15 waypoint0)
(can_traverse rover0 waypoint0 waypoint27)
(can_traverse rover0 waypoint27 waypoint0)
(can_traverse rover0 waypoint0 waypoint28)
(can_traverse rover0 waypoint28 waypoint0)
(can_traverse rover0 waypoint6 waypoint1)
(can_traverse rover0 waypoint1 waypoint6)
(can_traverse rover0 waypoint6 waypoint2)
(can_traverse rover0 waypoint2 waypoint6)
(can_traverse rover0 waypoint6 waypoint17)
(can_traverse rover0 waypoint17 waypoint6)
(can_traverse rover0 waypoint6 waypoint20)
(can_traverse rover0 waypoint20 waypoint6)
(can_traverse rover0 waypoint6 waypoint21)
(can_traverse rover0 waypoint21 waypoint6)
(can_traverse rover0 waypoint6 waypoint29)
(can_traverse rover0 waypoint29 waypoint6)
(can_traverse rover0 waypoint13 waypoint11)
(can_traverse rover0 waypoint11 waypoint13)
(can_traverse rover0 waypoint13 waypoint31)
(can_traverse rover0 waypoint31 waypoint13)
(can_traverse rover0 waypoint13 waypoint32)
(can_traverse rover0 waypoint32 waypoint13)
(can_traverse rover0 waypoint13 waypoint34)
(can_traverse rover0 waypoint34 waypoint13)
(can_traverse rover0 waypoint16 waypoint18)
(can_traverse rover0 waypoint18 waypoint16)
(can_traverse rover0 waypoint16 waypoint30)
(can_traverse rover0 waypoint30 waypoint16)
(can_traverse rover0 waypoint24 waypoint9)
(can_traverse rover0 waypoint9 waypoint24)
(can_traverse rover0 waypoint24 waypoint19)
(can_traverse rover0 waypoint19 waypoint24)
(can_traverse rover0 waypoint12 waypoint3)
(can_traverse rover0 waypoint3 waypoint12)
(can_traverse rover0 waypoint12 waypoint8)
(can_traverse rover0 waypoint8 waypoint12)
(can_traverse rover0 waypoint12 waypoint10)
(can_traverse rover0 waypoint10 waypoint12)
(can_traverse rover0 waypoint12 waypoint14)
(can_traverse rover0 waypoint14 waypoint12)
(can_traverse rover0 waypoint15 waypoint4)
(can_traverse rover0 waypoint4 waypoint15)
(can_traverse rover0 waypoint27 waypoint5)
(can_traverse rover0 waypoint5 waypoint27)
(can_traverse rover0 waypoint27 waypoint23)
(can_traverse rover0 waypoint23 waypoint27)
(can_traverse rover0 waypoint28 waypoint22)
(can_traverse rover0 waypoint22 waypoint28)
(can_traverse rover0 waypoint1 waypoint26)
(can_traverse rover0 waypoint26 waypoint1)
(can_traverse rover0 waypoint29 waypoint25)
(can_traverse rover0 waypoint25 waypoint29)
(on_board camera0 rover0)
(calibration_target camera0 objective9)
(supports camera0 high_res)
(supports camera0 low_res)
(on_board camera1 rover0)
(calibration_target camera1 objective6)
(supports camera1 colour)
(on_board camera2 rover0)
(calibration_target camera2 objective0)
(supports camera2 colour)
(on_board camera3 rover0)
(calibration_target camera3 objective3)
(supports camera3 colour)
(supports camera3 high_res)
(on_board camera4 rover0)
(calibration_target camera4 objective3)
(supports camera4 high_res)
(on_board camera5 rover0)
(calibration_target camera5 objective3)
(supports camera5 low_res)
(on_board camera6 rover0)
(calibration_target camera6 objective1)
(supports camera6 colour)
(supports camera6 high_res)
(supports camera6 low_res)
(on_board camera7 rover0)
(calibration_target camera7 objective2)
(supports camera7 colour)
(on_board camera8 rover0)
(calibration_target camera8 objective9)
(supports camera8 colour)
(on_board camera9 rover0)
(calibration_target camera9 objective7)
(supports camera9 colour)
(on_board camera10 rover0)
(calibration_target camera10 objective8)
(supports camera10 colour)
(supports camera10 high_res)
(on_board camera11 rover0)
(calibration_target camera11 objective0)
(supports camera11 low_res)
(on_board camera12 rover0)
(calibration_target camera12 objective0)
(supports camera12 colour)
(supports camera12 high_res)
(on_board camera13 rover0)
(calibration_target camera13 objective9)
(supports camera13 colour)
(supports camera13 low_res)
(on_board camera14 rover0)
(calibration_target camera14 objective5)
(supports camera14 high_res)
(supports camera14 low_res)
(visible_from objective0 waypoint2)
(visible_from objective0 waypoint8)
(visible_from objective0 waypoint9)
(visible_from objective0 waypoint10)
(visible_from objective0 waypoint12)
(visible_from objective0 waypoint15)
(visible_from objective0 waypoint18)
(visible_from objective0 waypoint29)
(visible_from objective0 waypoint30)
(visible_from objective0 waypoint31)
(visible_from objective0 waypoint32)
(visible_from objective0 waypoint33)
(visible_from objective0 waypoint34)
(visible_from objective1 waypoint0)
(visible_from objective1 waypoint2)
(visible_from objective1 waypoint3)
(visible_from objective1 waypoint4)
(visible_from objective1 waypoint8)
(visible_from objective1 waypoint9)
(visible_from objective1 waypoint11)
(visible_from objective1 waypoint15)
(visible_from objective1 waypoint16)
(visible_from objective1 waypoint17)
(visible_from objective1 waypoint18)
(visible_from objective1 waypoint19)
(visible_from objective1 waypoint21)
(visible_from objective1 waypoint23)
(visible_from objective1 waypoint27)
(visible_from objective1 waypoint28)
(visible_from objective1 waypoint29)
(visible_from objective1 waypoint32)
(visible_from objective1 waypoint33)
(visible_from objective1 waypoint34)
(visible_from objective2 waypoint1)
(visible_from objective2 waypoint2)
(visible_from objective2 waypoint4)
(visible_from objective2 waypoint5)
(visible_from objective2 waypoint8)
(visible_from objective2 waypoint10)
(visible_from objective2 waypoint11)
(visible_from objective2 waypoint12)
(visible_from objective2 waypoint14)
(visible_from objective2 waypoint15)
(visible_from objective2 waypoint16)
(visible_from objective2 waypoint18)
(visible_from objective2 waypoint22)
(visible_from objective2 waypoint25)
(visible_from objective2 waypoint28)
(visible_from objective2 waypoint29)
(visible_from objective2 waypoint30)
(visible_from objective2 waypoint31)
(visible_from objective2 waypoint32)
(visible_from objective2 waypoint34)
(visible_from objective3 waypoint0)
(visible_from objective3 waypoint1)
(visible_from objective3 waypoint2)
(visible_from objective3 waypoint4)
(visible_from objective3 waypoint7)
(visible_from objective3 waypoint8)
(visible_from objective3 waypoint14)
(visible_from objective3 waypoint18)
(visible_from objective3 waypoint19)
(visible_from objective3 waypoint20)
(visible_from objective3 waypoint22)
(visible_from objective3 waypoint23)
(visible_from objective3 waypoint27)
(visible_from objective3 waypoint31)
(visible_from objective4 waypoint5)
(visible_from objective4 waypoint11)
(visible_from objective4 waypoint19)
(visible_from objective4 waypoint20)
(visible_from objective4 waypoint21)
(visible_from objective4 waypoint25)
(visible_from objective4 waypoint27)
(visible_from objective4 waypoint29)
(visible_from objective5 waypoint1)
(visible_from objective5 waypoint2)
(visible_from objective5 waypoint3)
(visible_from objective5 waypoint5)
(visible_from objective5 waypoint6)
(visible_from objective5 waypoint7)
(visible_from objective5 waypoint8)
(visible_from objective5 waypoint10)
(visible_from objective5 waypoint11)
(visible_from objective5 waypoint12)
(visible_from objective5 waypoint15)
(visible_from objective5 waypoint16)
(visible_from objective5 waypoint17)
(visible_from objective5 waypoint19)
(visible_from objective5 waypoint20)
(visible_from objective5 waypoint21)
(visible_from objective5 waypoint23)
(visible_from objective5 waypoint24)
(visible_from objective5 waypoint27)
(visible_from objective5 waypoint28)
(visible_from objective5 waypoint30)
(visible_from objective5 waypoint31)
(visible_from objective5 waypoint32)
(visible_from objective5 waypoint34)
(visible_from objective6 waypoint5)
(visible_from objective6 waypoint9)
(visible_from objective6 waypoint29)
(visible_from objective7 waypoint0)
(visible_from objective7 waypoint1)
(visible_from objective7 waypoint3)
(visible_from objective7 waypoint4)
(visible_from objective7 waypoint5)
(visible_from objective7 waypoint6)
(visible_from objective7 waypoint10)
(visible_from objective7 waypoint12)
(visible_from objective7 waypoint13)
(visible_from objective7 waypoint15)
(visible_from objective7 waypoint16)
(visible_from objective7 waypoint17)
(visible_from objective7 waypoint18)
(visible_from objective7 waypoint22)
(visible_from objective7 waypoint23)
(visible_from objective7 waypoint26)
(visible_from objective7 waypoint28)
(visible_from objective7 waypoint29)
(visible_from objective7 waypoint30)
(visible_from objective7 waypoint32)
(visible_from objective7 waypoint33)
(visible_from objective7 waypoint34)
(visible_from objective8 waypoint0)
(visible_from objective8 waypoint2)
(visible_from objective8 waypoint5)
(visible_from objective8 waypoint7)
(visible_from objective8 waypoint9)
(visible_from objective8 waypoint10)
(visible_from objective8 waypoint11)
(visible_from objective8 waypoint13)
(visible_from objective8 waypoint21)
(visible_from objective8 waypoint22)
(visible_from objective8 waypoint25)
(visible_from objective8 waypoint28)
(visible_from objective8 waypoint29)
(visible_from objective8 waypoint31)
(visible_from objective8 waypoint32)
(visible_from objective9 waypoint0)
(visible_from objective9 waypoint2)
(visible_from objective9 waypoint4)
(visible_from objective9 waypoint5)
(visible_from objective9 waypoint6)
(visible_from objective9 waypoint7)
(visible_from objective9 waypoint10)
(visible_from objective9 waypoint12)
(visible_from objective9 waypoint15)
(visible_from objective9 waypoint20)
(visible_from objective9 waypoint22)
(visible_from objective9 waypoint24)
(visible_from objective9 waypoint26)
(visible_from objective9 waypoint30)
(visible_from objective9 waypoint31)
(visible_from objective9 waypoint32)
(visible_from objective9 waypoint33)
(visible_from objective9 waypoint34)
(at_rock_sample waypoint1)
(at_soil_sample waypoint2)
(at_rock_sample waypoint4)
(at_soil_sample waypoint8)
(at_rock_sample waypoint8)
(at_soil_sample waypoint9)
(at_rock_sample waypoint10)
(at_soil_sample waypoint11)
(at_rock_sample waypoint14)
(at_rock_sample waypoint18)
(at_rock_sample waypoint20)
(at_rock_sample waypoint21)
(at_rock_sample waypoint22)
(at_soil_sample waypoint25)
(at_soil_sample waypoint26)
(at_rock_sample waypoint27)
(at_rock_sample waypoint28)
(at_rock_sample waypoint29)
(at_soil_sample waypoint30)
(at_rock_sample waypoint31)
(at_rock_sample waypoint33)
(at_rock_sample waypoint34)
(channel_free general)
(available rover0)
(empty rover0store)
(communicated_soil_data waypoint3)
(communicated_soil_data waypoint19)
(communicated_soil_data waypoint28)
(communicated_soil_data waypoint13)
(communicated_rock_data waypoint12)
(communicated_rock_data waypoint2)
(communicated_image_data objective2 colour)
(communicated_image_data objective9 colour)
(communicated_image_data objective8 low_res)
(at rover0 waypoint6)
(have_image rover0 objective9 colour)
(have_image rover0 objective8 low_res)
(have_rock_analysis rover0 waypoint12)
(have_image rover0 objective2 colour)
(have_soil_analysis rover0 waypoint3)
(have_soil_analysis rover0 waypoint19)
(have_soil_analysis rover0 waypoint13)
(have_soil_analysis rover0 waypoint28)
(have_rock_analysis rover0 waypoint2)
)

(:goal (and
(communicated_soil_data waypoint3)
(communicated_soil_data waypoint25)
(communicated_soil_data waypoint19)
(communicated_soil_data waypoint28)
(communicated_soil_data waypoint13)
(communicated_rock_data waypoint12)
(communicated_rock_data waypoint2)
(communicated_image_data objective2 colour)
(communicated_image_data objective9 colour)
(communicated_image_data objective8 low_res)
	)
)
)
