(define (problem prb-231_d16_p-TST3-n67-r1w35o12c14-5) (:domain Rover)
(:objects
	general - Lander
	colour high_res low_res - Mode
	rover0 - Rover
	rover0store - Store
	waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 waypoint7 waypoint8 waypoint9 waypoint10 waypoint11 waypoint12 waypoint13 waypoint14 waypoint15 waypoint16 waypoint17 waypoint18 waypoint19 waypoint20 waypoint21 waypoint22 waypoint23 waypoint24 waypoint25 waypoint26 waypoint27 waypoint28 waypoint29 waypoint30 waypoint31 waypoint32 waypoint33 waypoint34 - Waypoint
	camera0 camera1 camera2 camera3 camera4 camera5 camera6 camera7 camera8 camera9 camera10 camera11 camera12 camera13 - Camera
	objective0 objective1 objective2 objective3 objective4 objective5 objective6 objective7 objective8 objective9 objective10 objective11 - Objective
	)
(:init
(visible waypoint0 waypoint3)
(visible waypoint3 waypoint0)
(visible waypoint0 waypoint9)
(visible waypoint9 waypoint0)
(visible waypoint0 waypoint11)
(visible waypoint11 waypoint0)
(visible waypoint0 waypoint14)
(visible waypoint14 waypoint0)
(visible waypoint0 waypoint16)
(visible waypoint16 waypoint0)
(visible waypoint0 waypoint20)
(visible waypoint20 waypoint0)
(visible waypoint0 waypoint32)
(visible waypoint32 waypoint0)
(visible waypoint1 waypoint5)
(visible waypoint5 waypoint1)
(visible waypoint1 waypoint6)
(visible waypoint6 waypoint1)
(visible waypoint1 waypoint12)
(visible waypoint12 waypoint1)
(visible waypoint1 waypoint16)
(visible waypoint16 waypoint1)
(visible waypoint1 waypoint27)
(visible waypoint27 waypoint1)
(visible waypoint2 waypoint14)
(visible waypoint14 waypoint2)
(visible waypoint2 waypoint22)
(visible waypoint22 waypoint2)
(visible waypoint2 waypoint28)
(visible waypoint28 waypoint2)
(visible waypoint3 waypoint6)
(visible waypoint6 waypoint3)
(visible waypoint3 waypoint12)
(visible waypoint12 waypoint3)
(visible waypoint3 waypoint16)
(visible waypoint16 waypoint3)
(visible waypoint4 waypoint2)
(visible waypoint2 waypoint4)
(visible waypoint4 waypoint7)
(visible waypoint7 waypoint4)
(visible waypoint4 waypoint12)
(visible waypoint12 waypoint4)
(visible waypoint4 waypoint17)
(visible waypoint17 waypoint4)
(visible waypoint5 waypoint2)
(visible waypoint2 waypoint5)
(visible waypoint5 waypoint24)
(visible waypoint24 waypoint5)
(visible waypoint5 waypoint31)
(visible waypoint31 waypoint5)
(visible waypoint6 waypoint12)
(visible waypoint12 waypoint6)
(visible waypoint6 waypoint25)
(visible waypoint25 waypoint6)
(visible waypoint6 waypoint30)
(visible waypoint30 waypoint6)
(visible waypoint7 waypoint0)
(visible waypoint0 waypoint7)
(visible waypoint7 waypoint1)
(visible waypoint1 waypoint7)
(visible waypoint7 waypoint8)
(visible waypoint8 waypoint7)
(visible waypoint7 waypoint14)
(visible waypoint14 waypoint7)
(visible waypoint7 waypoint16)
(visible waypoint16 waypoint7)
(visible waypoint7 waypoint28)
(visible waypoint28 waypoint7)
(visible waypoint8 waypoint17)
(visible waypoint17 waypoint8)
(visible waypoint8 waypoint24)
(visible waypoint24 waypoint8)
(visible waypoint9 waypoint1)
(visible waypoint1 waypoint9)
(visible waypoint9 waypoint3)
(visible waypoint3 waypoint9)
(visible waypoint9 waypoint15)
(visible waypoint15 waypoint9)
(visible waypoint9 waypoint28)
(visible waypoint28 waypoint9)
(visible waypoint9 waypoint30)
(visible waypoint30 waypoint9)
(visible waypoint9 waypoint34)
(visible waypoint34 waypoint9)
(visible waypoint10 waypoint16)
(visible waypoint16 waypoint10)
(visible waypoint10 waypoint20)
(visible waypoint20 waypoint10)
(visible waypoint10 waypoint27)
(visible waypoint27 waypoint10)
(visible waypoint11 waypoint8)
(visible waypoint8 waypoint11)
(visible waypoint11 waypoint30)
(visible waypoint30 waypoint11)
(visible waypoint11 waypoint31)
(visible waypoint31 waypoint11)
(visible waypoint12 waypoint2)
(visible waypoint2 waypoint12)
(visible waypoint12 waypoint9)
(visible waypoint9 waypoint12)
(visible waypoint12 waypoint17)
(visible waypoint17 waypoint12)
(visible waypoint12 waypoint31)
(visible waypoint31 waypoint12)
(visible waypoint13 waypoint6)
(visible waypoint6 waypoint13)
(visible waypoint13 waypoint14)
(visible waypoint14 waypoint13)
(visible waypoint13 waypoint24)
(visible waypoint24 waypoint13)
(visible waypoint13 waypoint26)
(visible waypoint26 waypoint13)
(visible waypoint13 waypoint34)
(visible waypoint34 waypoint13)
(visible waypoint14 waypoint8)
(visible waypoint8 waypoint14)
(visible waypoint14 waypoint9)
(visible waypoint9 waypoint14)
(visible waypoint14 waypoint10)
(visible waypoint10 waypoint14)
(visible waypoint14 waypoint17)
(visible waypoint17 waypoint14)
(visible waypoint14 waypoint22)
(visible waypoint22 waypoint14)
(visible waypoint14 waypoint25)
(visible waypoint25 waypoint14)
(visible waypoint14 waypoint33)
(visible waypoint33 waypoint14)
(visible waypoint15 waypoint7)
(visible waypoint7 waypoint15)
(visible waypoint15 waypoint11)
(visible waypoint11 waypoint15)
(visible waypoint15 waypoint12)
(visible waypoint12 waypoint15)
(visible waypoint15 waypoint14)
(visible waypoint14 waypoint15)
(visible waypoint15 waypoint17)
(visible waypoint17 waypoint15)
(visible waypoint16 waypoint4)
(visible waypoint4 waypoint16)
(visible waypoint16 waypoint6)
(visible waypoint6 waypoint16)
(visible waypoint16 waypoint11)
(visible waypoint11 waypoint16)
(visible waypoint16 waypoint22)
(visible waypoint22 waypoint16)
(visible waypoint16 waypoint24)
(visible waypoint24 waypoint16)
(visible waypoint16 waypoint34)
(visible waypoint34 waypoint16)
(visible waypoint17 waypoint2)
(visible waypoint2 waypoint17)
(visible waypoint17 waypoint3)
(visible waypoint3 waypoint17)
(visible waypoint17 waypoint11)
(visible waypoint11 waypoint17)
(visible waypoint17 waypoint21)
(visible waypoint21 waypoint17)
(visible waypoint17 waypoint31)
(visible waypoint31 waypoint17)
(visible waypoint18 waypoint7)
(visible waypoint7 waypoint18)
(visible waypoint18 waypoint12)
(visible waypoint12 waypoint18)
(visible waypoint18 waypoint14)
(visible waypoint14 waypoint18)
(visible waypoint18 waypoint23)
(visible waypoint23 waypoint18)
(visible waypoint18 waypoint29)
(visible waypoint29 waypoint18)
(visible waypoint18 waypoint33)
(visible waypoint33 waypoint18)
(visible waypoint18 waypoint34)
(visible waypoint34 waypoint18)
(visible waypoint19 waypoint0)
(visible waypoint0 waypoint19)
(visible waypoint19 waypoint15)
(visible waypoint15 waypoint19)
(visible waypoint20 waypoint2)
(visible waypoint2 waypoint20)
(visible waypoint20 waypoint3)
(visible waypoint3 waypoint20)
(visible waypoint20 waypoint6)
(visible waypoint6 waypoint20)
(visible waypoint20 waypoint18)
(visible waypoint18 waypoint20)
(visible waypoint20 waypoint23)
(visible waypoint23 waypoint20)
(visible waypoint21 waypoint1)
(visible waypoint1 waypoint21)
(visible waypoint21 waypoint3)
(visible waypoint3 waypoint21)
(visible waypoint21 waypoint7)
(visible waypoint7 waypoint21)
(visible waypoint21 waypoint27)
(visible waypoint27 waypoint21)
(visible waypoint22 waypoint26)
(visible waypoint26 waypoint22)
(visible waypoint22 waypoint31)
(visible waypoint31 waypoint22)
(visible waypoint23 waypoint6)
(visible waypoint6 waypoint23)
(visible waypoint23 waypoint8)
(visible waypoint8 waypoint23)
(visible waypoint23 waypoint11)
(visible waypoint11 waypoint23)
(visible waypoint23 waypoint32)
(visible waypoint32 waypoint23)
(visible waypoint24 waypoint4)
(visible waypoint4 waypoint24)
(visible waypoint24 waypoint10)
(visible waypoint10 waypoint24)
(visible waypoint24 waypoint15)
(visible waypoint15 waypoint24)
(visible waypoint24 waypoint31)
(visible waypoint31 waypoint24)
(visible waypoint24 waypoint34)
(visible waypoint34 waypoint24)
(visible waypoint25 waypoint5)
(visible waypoint5 waypoint25)
(visible waypoint25 waypoint18)
(visible waypoint18 waypoint25)
(visible waypoint25 waypoint19)
(visible waypoint19 waypoint25)
(visible waypoint26 waypoint19)
(visible waypoint19 waypoint26)
(visible waypoint26 waypoint24)
(visible waypoint24 waypoint26)
(visible waypoint27 waypoint5)
(visible waypoint5 waypoint27)
(visible waypoint27 waypoint12)
(visible waypoint12 waypoint27)
(visible waypoint27 waypoint17)
(visible waypoint17 waypoint27)
(visible waypoint27 waypoint18)
(visible waypoint18 waypoint27)
(visible waypoint27 waypoint20)
(visible waypoint20 waypoint27)
(visible waypoint28 waypoint25)
(visible waypoint25 waypoint28)
(visible waypoint29 waypoint2)
(visible waypoint2 waypoint29)
(visible waypoint29 waypoint22)
(visible waypoint22 waypoint29)
(visible waypoint29 waypoint24)
(visible waypoint24 waypoint29)
(visible waypoint29 waypoint25)
(visible waypoint25 waypoint29)
(visible waypoint29 waypoint27)
(visible waypoint27 waypoint29)
(visible waypoint29 waypoint30)
(visible waypoint30 waypoint29)
(visible waypoint29 waypoint31)
(visible waypoint31 waypoint29)
(visible waypoint30 waypoint0)
(visible waypoint0 waypoint30)
(visible waypoint30 waypoint12)
(visible waypoint12 waypoint30)
(visible waypoint30 waypoint18)
(visible waypoint18 waypoint30)
(visible waypoint30 waypoint34)
(visible waypoint34 waypoint30)
(visible waypoint31 waypoint2)
(visible waypoint2 waypoint31)
(visible waypoint31 waypoint21)
(visible waypoint21 waypoint31)
(visible waypoint31 waypoint25)
(visible waypoint25 waypoint31)
(visible waypoint32 waypoint9)
(visible waypoint9 waypoint32)
(visible waypoint32 waypoint17)
(visible waypoint17 waypoint32)
(visible waypoint32 waypoint25)
(visible waypoint25 waypoint32)
(visible waypoint32 waypoint26)
(visible waypoint26 waypoint32)
(visible waypoint32 waypoint31)
(visible waypoint31 waypoint32)
(visible waypoint33 waypoint7)
(visible waypoint7 waypoint33)
(visible waypoint33 waypoint12)
(visible waypoint12 waypoint33)
(visible waypoint33 waypoint13)
(visible waypoint13 waypoint33)
(visible waypoint33 waypoint16)
(visible waypoint16 waypoint33)
(visible waypoint33 waypoint28)
(visible waypoint28 waypoint33)
(visible waypoint34 waypoint0)
(visible waypoint0 waypoint34)
(visible waypoint34 waypoint2)
(visible waypoint2 waypoint34)
(visible waypoint34 waypoint3)
(visible waypoint3 waypoint34)
(visible waypoint34 waypoint4)
(visible waypoint4 waypoint34)
(visible waypoint34 waypoint11)
(visible waypoint11 waypoint34)
(visible waypoint34 waypoint17)
(visible waypoint17 waypoint34)
(visible waypoint34 waypoint19)
(visible waypoint19 waypoint34)
(visible waypoint34 waypoint32)
(visible waypoint32 waypoint34)
(at_lander general waypoint4)
(store_of rover0store rover0)
(equipped_for_soil_analysis rover0)
(equipped_for_rock_analysis rover0)
(equipped_for_imaging rover0)
(can_traverse rover0 waypoint25 waypoint5)
(can_traverse rover0 waypoint5 waypoint25)
(can_traverse rover0 waypoint25 waypoint6)
(can_traverse rover0 waypoint6 waypoint25)
(can_traverse rover0 waypoint25 waypoint14)
(can_traverse rover0 waypoint14 waypoint25)
(can_traverse rover0 waypoint25 waypoint18)
(can_traverse rover0 waypoint18 waypoint25)
(can_traverse rover0 waypoint25 waypoint19)
(can_traverse rover0 waypoint19 waypoint25)
(can_traverse rover0 waypoint25 waypoint28)
(can_traverse rover0 waypoint28 waypoint25)
(can_traverse rover0 waypoint25 waypoint32)
(can_traverse rover0 waypoint32 waypoint25)
(can_traverse rover0 waypoint5 waypoint1)
(can_traverse rover0 waypoint1 waypoint5)
(can_traverse rover0 waypoint5 waypoint2)
(can_traverse rover0 waypoint2 waypoint5)
(can_traverse rover0 waypoint5 waypoint24)
(can_traverse rover0 waypoint24 waypoint5)
(can_traverse rover0 waypoint5 waypoint31)
(can_traverse rover0 waypoint31 waypoint5)
(can_traverse rover0 waypoint6 waypoint13)
(can_traverse rover0 waypoint13 waypoint6)
(can_traverse rover0 waypoint6 waypoint16)
(can_traverse rover0 waypoint16 waypoint6)
(can_traverse rover0 waypoint6 waypoint23)
(can_traverse rover0 waypoint23 waypoint6)
(can_traverse rover0 waypoint6 waypoint30)
(can_traverse rover0 waypoint30 waypoint6)
(can_traverse rover0 waypoint14 waypoint0)
(can_traverse rover0 waypoint0 waypoint14)
(can_traverse rover0 waypoint14 waypoint7)
(can_traverse rover0 waypoint7 waypoint14)
(can_traverse rover0 waypoint14 waypoint9)
(can_traverse rover0 waypoint9 waypoint14)
(can_traverse rover0 waypoint14 waypoint15)
(can_traverse rover0 waypoint15 waypoint14)
(can_traverse rover0 waypoint14 waypoint33)
(can_traverse rover0 waypoint33 waypoint14)
(can_traverse rover0 waypoint18 waypoint20)
(can_traverse rover0 waypoint20 waypoint18)
(can_traverse rover0 waypoint18 waypoint27)
(can_traverse rover0 waypoint27 waypoint18)
(can_traverse rover0 waypoint18 waypoint29)
(can_traverse rover0 waypoint29 waypoint18)
(can_traverse rover0 waypoint32 waypoint34)
(can_traverse rover0 waypoint34 waypoint32)
(can_traverse rover0 waypoint1 waypoint12)
(can_traverse rover0 waypoint12 waypoint1)
(can_traverse rover0 waypoint1 waypoint21)
(can_traverse rover0 waypoint21 waypoint1)
(can_traverse rover0 waypoint2 waypoint4)
(can_traverse rover0 waypoint4 waypoint2)
(can_traverse rover0 waypoint2 waypoint22)
(can_traverse rover0 waypoint22 waypoint2)
(can_traverse rover0 waypoint24 waypoint8)
(can_traverse rover0 waypoint8 waypoint24)
(can_traverse rover0 waypoint31 waypoint11)
(can_traverse rover0 waypoint11 waypoint31)
(on_board camera0 rover0)
(calibration_target camera0 objective11)
(supports camera0 high_res)
(on_board camera1 rover0)
(calibration_target camera1 objective9)
(supports camera1 colour)
(supports camera1 low_res)
(on_board camera2 rover0)
(calibration_target camera2 objective0)
(supports camera2 low_res)
(on_board camera3 rover0)
(calibration_target camera3 objective2)
(supports camera3 high_res)
(on_board camera4 rover0)
(calibration_target camera4 objective11)
(supports camera4 low_res)
(on_board camera5 rover0)
(calibration_target camera5 objective1)
(supports camera5 low_res)
(on_board camera6 rover0)
(calibration_target camera6 objective4)
(supports camera6 low_res)
(on_board camera7 rover0)
(calibration_target camera7 objective3)
(supports camera7 high_res)
(supports camera7 low_res)
(on_board camera8 rover0)
(calibration_target camera8 objective3)
(supports camera8 colour)
(supports camera8 high_res)
(supports camera8 low_res)
(on_board camera9 rover0)
(calibration_target camera9 objective4)
(supports camera9 low_res)
(on_board camera10 rover0)
(calibration_target camera10 objective6)
(supports camera10 colour)
(supports camera10 low_res)
(on_board camera11 rover0)
(calibration_target camera11 objective4)
(supports camera11 low_res)
(on_board camera12 rover0)
(calibration_target camera12 objective7)
(supports camera12 colour)
(supports camera12 high_res)
(supports camera12 low_res)
(on_board camera13 rover0)
(calibration_target camera13 objective2)
(supports camera13 colour)
(supports camera13 high_res)
(supports camera13 low_res)
(visible_from objective0 waypoint12)
(visible_from objective0 waypoint17)
(visible_from objective1 waypoint1)
(visible_from objective1 waypoint4)
(visible_from objective1 waypoint11)
(visible_from objective1 waypoint12)
(visible_from objective1 waypoint15)
(visible_from objective1 waypoint16)
(visible_from objective1 waypoint19)
(visible_from objective1 waypoint20)
(visible_from objective1 waypoint23)
(visible_from objective1 waypoint28)
(visible_from objective1 waypoint29)
(visible_from objective1 waypoint31)
(visible_from objective1 waypoint32)
(visible_from objective1 waypoint33)
(visible_from objective2 waypoint1)
(visible_from objective2 waypoint3)
(visible_from objective2 waypoint4)
(visible_from objective2 waypoint5)
(visible_from objective2 waypoint6)
(visible_from objective2 waypoint8)
(visible_from objective2 waypoint12)
(visible_from objective2 waypoint13)
(visible_from objective2 waypoint14)
(visible_from objective2 waypoint18)
(visible_from objective2 waypoint19)
(visible_from objective2 waypoint20)
(visible_from objective2 waypoint22)
(visible_from objective2 waypoint23)
(visible_from objective2 waypoint25)
(visible_from objective2 waypoint26)
(visible_from objective2 waypoint27)
(visible_from objective2 waypoint34)
(visible_from objective3 waypoint0)
(visible_from objective3 waypoint1)
(visible_from objective3 waypoint3)
(visible_from objective3 waypoint5)
(visible_from objective3 waypoint6)
(visible_from objective3 waypoint8)
(visible_from objective3 waypoint11)
(visible_from objective3 waypoint13)
(visible_from objective3 waypoint15)
(visible_from objective3 waypoint16)
(visible_from objective3 waypoint18)
(visible_from objective3 waypoint19)
(visible_from objective3 waypoint20)
(visible_from objective3 waypoint21)
(visible_from objective3 waypoint23)
(visible_from objective3 waypoint24)
(visible_from objective3 waypoint25)
(visible_from objective3 waypoint27)
(visible_from objective3 waypoint28)
(visible_from objective3 waypoint30)
(visible_from objective3 waypoint32)
(visible_from objective4 waypoint2)
(visible_from objective4 waypoint3)
(visible_from objective4 waypoint4)
(visible_from objective4 waypoint5)
(visible_from objective4 waypoint7)
(visible_from objective4 waypoint11)
(visible_from objective4 waypoint12)
(visible_from objective4 waypoint13)
(visible_from objective4 waypoint16)
(visible_from objective4 waypoint17)
(visible_from objective4 waypoint20)
(visible_from objective4 waypoint25)
(visible_from objective4 waypoint27)
(visible_from objective4 waypoint29)
(visible_from objective4 waypoint34)
(visible_from objective5 waypoint4)
(visible_from objective5 waypoint6)
(visible_from objective5 waypoint7)
(visible_from objective5 waypoint9)
(visible_from objective5 waypoint12)
(visible_from objective5 waypoint15)
(visible_from objective5 waypoint24)
(visible_from objective5 waypoint25)
(visible_from objective5 waypoint26)
(visible_from objective5 waypoint28)
(visible_from objective5 waypoint30)
(visible_from objective6 waypoint0)
(visible_from objective6 waypoint1)
(visible_from objective6 waypoint2)
(visible_from objective6 waypoint3)
(visible_from objective6 waypoint6)
(visible_from objective6 waypoint7)
(visible_from objective6 waypoint8)
(visible_from objective6 waypoint9)
(visible_from objective6 waypoint10)
(visible_from objective6 waypoint13)
(visible_from objective6 waypoint16)
(visible_from objective6 waypoint19)
(visible_from objective6 waypoint20)
(visible_from objective6 waypoint21)
(visible_from objective6 waypoint27)
(visible_from objective6 waypoint28)
(visible_from objective6 waypoint30)
(visible_from objective6 waypoint31)
(visible_from objective6 waypoint32)
(visible_from objective6 waypoint33)
(visible_from objective7 waypoint0)
(visible_from objective7 waypoint1)
(visible_from objective7 waypoint4)
(visible_from objective7 waypoint5)
(visible_from objective7 waypoint6)
(visible_from objective7 waypoint7)
(visible_from objective7 waypoint11)
(visible_from objective7 waypoint12)
(visible_from objective7 waypoint14)
(visible_from objective7 waypoint16)
(visible_from objective7 waypoint18)
(visible_from objective7 waypoint19)
(visible_from objective7 waypoint20)
(visible_from objective7 waypoint21)
(visible_from objective7 waypoint22)
(visible_from objective7 waypoint28)
(visible_from objective7 waypoint32)
(visible_from objective7 waypoint33)
(visible_from objective8 waypoint0)
(visible_from objective8 waypoint1)
(visible_from objective8 waypoint2)
(visible_from objective8 waypoint3)
(visible_from objective8 waypoint4)
(visible_from objective8 waypoint5)
(visible_from objective8 waypoint6)
(visible_from objective8 waypoint7)
(visible_from objective8 waypoint9)
(visible_from objective8 waypoint10)
(visible_from objective8 waypoint11)
(visible_from objective8 waypoint12)
(visible_from objective8 waypoint13)
(visible_from objective8 waypoint15)
(visible_from objective8 waypoint17)
(visible_from objective8 waypoint19)
(visible_from objective8 waypoint22)
(visible_from objective8 waypoint23)
(visible_from objective8 waypoint24)
(visible_from objective8 waypoint27)
(visible_from objective8 waypoint28)
(visible_from objective8 waypoint34)
(visible_from objective9 waypoint2)
(visible_from objective9 waypoint5)
(visible_from objective9 waypoint7)
(visible_from objective9 waypoint17)
(visible_from objective9 waypoint18)
(visible_from objective9 waypoint19)
(visible_from objective9 waypoint20)
(visible_from objective9 waypoint26)
(visible_from objective9 waypoint31)
(visible_from objective10 waypoint2)
(visible_from objective10 waypoint4)
(visible_from objective10 waypoint7)
(visible_from objective10 waypoint10)
(visible_from objective10 waypoint11)
(visible_from objective10 waypoint13)
(visible_from objective10 waypoint16)
(visible_from objective10 waypoint17)
(visible_from objective10 waypoint18)
(visible_from objective10 waypoint19)
(visible_from objective10 waypoint20)
(visible_from objective10 waypoint21)
(visible_from objective10 waypoint23)
(visible_from objective10 waypoint25)
(visible_from objective10 waypoint26)
(visible_from objective10 waypoint27)
(visible_from objective10 waypoint28)
(visible_from objective10 waypoint29)
(visible_from objective10 waypoint31)
(visible_from objective10 waypoint32)
(visible_from objective10 waypoint33)
(visible_from objective11 waypoint6)
(visible_from objective11 waypoint7)
(visible_from objective11 waypoint9)
(visible_from objective11 waypoint10)
(visible_from objective11 waypoint11)
(visible_from objective11 waypoint13)
(visible_from objective11 waypoint15)
(visible_from objective11 waypoint18)
(visible_from objective11 waypoint19)
(visible_from objective11 waypoint21)
(visible_from objective11 waypoint24)
(visible_from objective11 waypoint26)
(visible_from objective11 waypoint27)
(visible_from objective11 waypoint31)
(visible_from objective11 waypoint33)
(visible_from objective11 waypoint34)
(at_soil_sample waypoint0)
(at_rock_sample waypoint0)
(at_soil_sample waypoint1)
(at_rock_sample waypoint1)
(at_soil_sample waypoint2)
(at_rock_sample waypoint3)
(at_rock_sample waypoint4)
(at_soil_sample waypoint5)
(at_rock_sample waypoint5)
(at_rock_sample waypoint6)
(at_soil_sample waypoint7)
(at_soil_sample waypoint8)
(at_rock_sample waypoint8)
(at_soil_sample waypoint9)
(at_soil_sample waypoint10)
(at_rock_sample waypoint10)
(at_soil_sample waypoint15)
(at_soil_sample waypoint16)
(at_rock_sample waypoint17)
(at_soil_sample waypoint20)
(at_rock_sample waypoint21)
(at_soil_sample waypoint22)
(at_soil_sample waypoint24)
(at_soil_sample waypoint25)
(at_rock_sample waypoint26)
(at_soil_sample waypoint29)
(at_rock_sample waypoint29)
(at_soil_sample waypoint32)
(at_rock_sample waypoint32)
(at_rock_sample waypoint33)
(channel_free general)
(available rover0)
(communicated_soil_data waypoint6)
(communicated_soil_data waypoint30)
(communicated_rock_data waypoint12)
(communicated_rock_data waypoint31)
(communicated_rock_data waypoint15)
(communicated_image_data objective7 high_res)
(communicated_image_data objective1 colour)
(communicated_image_data objective4 low_res)
(communicated_image_data objective2 high_res)
(at rover0 waypoint5)
(full rover0store)
(have_image rover0 objective4 low_res)
(have_image rover0 objective2 high_res)
(have_image rover0 objective7 high_res)
(have_rock_analysis rover0 waypoint15)
(have_image rover0 objective1 colour)
(have_rock_analysis rover0 waypoint12)
(have_soil_analysis rover0 waypoint6)
(have_soil_analysis rover0 waypoint30)
(have_rock_analysis rover0 waypoint31)
(have_rock_analysis rover0 waypoint11)
)

(:goal (and
(communicated_soil_data waypoint29)
(communicated_soil_data waypoint6)
(communicated_soil_data waypoint30)
(communicated_rock_data waypoint11)
(communicated_rock_data waypoint12)
(communicated_rock_data waypoint31)
(communicated_rock_data waypoint15)
(communicated_rock_data waypoint29)
(communicated_image_data objective7 high_res)
(communicated_image_data objective1 colour)
(communicated_image_data objective4 low_res)
(communicated_image_data objective2 high_res)
	)
)
)
