(define (problem prb-246_d15_p-TST3-n68-r1w35o13c14-4) (:domain Rover)
(:objects
	general - Lander
	colour high_res low_res - Mode
	rover0 - Rover
	rover0store - Store
	waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 waypoint7 waypoint8 waypoint9 waypoint10 waypoint11 waypoint12 waypoint13 waypoint14 waypoint15 waypoint16 waypoint17 waypoint18 waypoint19 waypoint20 waypoint21 waypoint22 waypoint23 waypoint24 waypoint25 waypoint26 waypoint27 waypoint28 waypoint29 waypoint30 waypoint31 waypoint32 waypoint33 waypoint34 - Waypoint
	camera0 camera1 camera2 camera3 camera4 camera5 camera6 camera7 camera8 camera9 camera10 camera11 camera12 camera13 - Camera
	objective0 objective1 objective2 objective3 objective4 objective5 objective6 objective7 objective8 objective9 objective10 objective11 objective12 - Objective
	)
(:init
(visible waypoint0 waypoint9)
(visible waypoint9 waypoint0)
(visible waypoint0 waypoint15)
(visible waypoint15 waypoint0)
(visible waypoint0 waypoint17)
(visible waypoint17 waypoint0)
(visible waypoint1 waypoint0)
(visible waypoint0 waypoint1)
(visible waypoint1 waypoint4)
(visible waypoint4 waypoint1)
(visible waypoint1 waypoint14)
(visible waypoint14 waypoint1)
(visible waypoint1 waypoint18)
(visible waypoint18 waypoint1)
(visible waypoint1 waypoint20)
(visible waypoint20 waypoint1)
(visible waypoint2 waypoint3)
(visible waypoint3 waypoint2)
(visible waypoint2 waypoint9)
(visible waypoint9 waypoint2)
(visible waypoint2 waypoint31)
(visible waypoint31 waypoint2)
(visible waypoint3 waypoint4)
(visible waypoint4 waypoint3)
(visible waypoint3 waypoint7)
(visible waypoint7 waypoint3)
(visible waypoint3 waypoint10)
(visible waypoint10 waypoint3)
(visible waypoint3 waypoint11)
(visible waypoint11 waypoint3)
(visible waypoint3 waypoint16)
(visible waypoint16 waypoint3)
(visible waypoint3 waypoint21)
(visible waypoint21 waypoint3)
(visible waypoint3 waypoint34)
(visible waypoint34 waypoint3)
(visible waypoint4 waypoint10)
(visible waypoint10 waypoint4)
(visible waypoint4 waypoint15)
(visible waypoint15 waypoint4)
(visible waypoint4 waypoint16)
(visible waypoint16 waypoint4)
(visible waypoint5 waypoint2)
(visible waypoint2 waypoint5)
(visible waypoint5 waypoint23)
(visible waypoint23 waypoint5)
(visible waypoint5 waypoint24)
(visible waypoint24 waypoint5)
(visible waypoint6 waypoint5)
(visible waypoint5 waypoint6)
(visible waypoint6 waypoint9)
(visible waypoint9 waypoint6)
(visible waypoint6 waypoint10)
(visible waypoint10 waypoint6)
(visible waypoint6 waypoint18)
(visible waypoint18 waypoint6)
(visible waypoint6 waypoint28)
(visible waypoint28 waypoint6)
(visible waypoint6 waypoint33)
(visible waypoint33 waypoint6)
(visible waypoint7 waypoint12)
(visible waypoint12 waypoint7)
(visible waypoint8 waypoint5)
(visible waypoint5 waypoint8)
(visible waypoint8 waypoint7)
(visible waypoint7 waypoint8)
(visible waypoint8 waypoint19)
(visible waypoint19 waypoint8)
(visible waypoint9 waypoint3)
(visible waypoint3 waypoint9)
(visible waypoint9 waypoint17)
(visible waypoint17 waypoint9)
(visible waypoint9 waypoint19)
(visible waypoint19 waypoint9)
(visible waypoint9 waypoint23)
(visible waypoint23 waypoint9)
(visible waypoint9 waypoint24)
(visible waypoint24 waypoint9)
(visible waypoint9 waypoint27)
(visible waypoint27 waypoint9)
(visible waypoint10 waypoint1)
(visible waypoint1 waypoint10)
(visible waypoint10 waypoint11)
(visible waypoint11 waypoint10)
(visible waypoint10 waypoint12)
(visible waypoint12 waypoint10)
(visible waypoint10 waypoint14)
(visible waypoint14 waypoint10)
(visible waypoint10 waypoint16)
(visible waypoint16 waypoint10)
(visible waypoint10 waypoint18)
(visible waypoint18 waypoint10)
(visible waypoint11 waypoint9)
(visible waypoint9 waypoint11)
(visible waypoint11 waypoint17)
(visible waypoint17 waypoint11)
(visible waypoint12 waypoint1)
(visible waypoint1 waypoint12)
(visible waypoint12 waypoint20)
(visible waypoint20 waypoint12)
(visible waypoint12 waypoint21)
(visible waypoint21 waypoint12)
(visible waypoint12 waypoint22)
(visible waypoint22 waypoint12)
(visible waypoint12 waypoint23)
(visible waypoint23 waypoint12)
(visible waypoint12 waypoint27)
(visible waypoint27 waypoint12)
(visible waypoint13 waypoint4)
(visible waypoint4 waypoint13)
(visible waypoint13 waypoint19)
(visible waypoint19 waypoint13)
(visible waypoint14 waypoint12)
(visible waypoint12 waypoint14)
(visible waypoint14 waypoint13)
(visible waypoint13 waypoint14)
(visible waypoint14 waypoint15)
(visible waypoint15 waypoint14)
(visible waypoint14 waypoint17)
(visible waypoint17 waypoint14)
(visible waypoint14 waypoint22)
(visible waypoint22 waypoint14)
(visible waypoint14 waypoint29)
(visible waypoint29 waypoint14)
(visible waypoint14 waypoint30)
(visible waypoint30 waypoint14)
(visible waypoint15 waypoint19)
(visible waypoint19 waypoint15)
(visible waypoint15 waypoint20)
(visible waypoint20 waypoint15)
(visible waypoint15 waypoint28)
(visible waypoint28 waypoint15)
(visible waypoint15 waypoint33)
(visible waypoint33 waypoint15)
(visible waypoint16 waypoint0)
(visible waypoint0 waypoint16)
(visible waypoint16 waypoint7)
(visible waypoint7 waypoint16)
(visible waypoint16 waypoint14)
(visible waypoint14 waypoint16)
(visible waypoint16 waypoint28)
(visible waypoint28 waypoint16)
(visible waypoint17 waypoint1)
(visible waypoint1 waypoint17)
(visible waypoint17 waypoint2)
(visible waypoint2 waypoint17)
(visible waypoint17 waypoint3)
(visible waypoint3 waypoint17)
(visible waypoint17 waypoint4)
(visible waypoint4 waypoint17)
(visible waypoint17 waypoint7)
(visible waypoint7 waypoint17)
(visible waypoint17 waypoint12)
(visible waypoint12 waypoint17)
(visible waypoint17 waypoint15)
(visible waypoint15 waypoint17)
(visible waypoint18 waypoint7)
(visible waypoint7 waypoint18)
(visible waypoint18 waypoint11)
(visible waypoint11 waypoint18)
(visible waypoint18 waypoint14)
(visible waypoint14 waypoint18)
(visible waypoint19 waypoint23)
(visible waypoint23 waypoint19)
(visible waypoint19 waypoint27)
(visible waypoint27 waypoint19)
(visible waypoint19 waypoint28)
(visible waypoint28 waypoint19)
(visible waypoint19 waypoint29)
(visible waypoint29 waypoint19)
(visible waypoint20 waypoint5)
(visible waypoint5 waypoint20)
(visible waypoint20 waypoint10)
(visible waypoint10 waypoint20)
(visible waypoint20 waypoint16)
(visible waypoint16 waypoint20)
(visible waypoint20 waypoint17)
(visible waypoint17 waypoint20)
(visible waypoint20 waypoint19)
(visible waypoint19 waypoint20)
(visible waypoint20 waypoint32)
(visible waypoint32 waypoint20)
(visible waypoint21 waypoint22)
(visible waypoint22 waypoint21)
(visible waypoint21 waypoint27)
(visible waypoint27 waypoint21)
(visible waypoint21 waypoint31)
(visible waypoint31 waypoint21)
(visible waypoint22 waypoint4)
(visible waypoint4 waypoint22)
(visible waypoint22 waypoint11)
(visible waypoint11 waypoint22)
(visible waypoint22 waypoint16)
(visible waypoint16 waypoint22)
(visible waypoint23 waypoint0)
(visible waypoint0 waypoint23)
(visible waypoint23 waypoint10)
(visible waypoint10 waypoint23)
(visible waypoint23 waypoint21)
(visible waypoint21 waypoint23)
(visible waypoint23 waypoint22)
(visible waypoint22 waypoint23)
(visible waypoint23 waypoint26)
(visible waypoint26 waypoint23)
(visible waypoint23 waypoint27)
(visible waypoint27 waypoint23)
(visible waypoint24 waypoint2)
(visible waypoint2 waypoint24)
(visible waypoint24 waypoint16)
(visible waypoint16 waypoint24)
(visible waypoint25 waypoint3)
(visible waypoint3 waypoint25)
(visible waypoint25 waypoint8)
(visible waypoint8 waypoint25)
(visible waypoint25 waypoint16)
(visible waypoint16 waypoint25)
(visible waypoint25 waypoint21)
(visible waypoint21 waypoint25)
(visible waypoint25 waypoint23)
(visible waypoint23 waypoint25)
(visible waypoint25 waypoint26)
(visible waypoint26 waypoint25)
(visible waypoint25 waypoint29)
(visible waypoint29 waypoint25)
(visible waypoint25 waypoint34)
(visible waypoint34 waypoint25)
(visible waypoint26 waypoint2)
(visible waypoint2 waypoint26)
(visible waypoint26 waypoint13)
(visible waypoint13 waypoint26)
(visible waypoint26 waypoint14)
(visible waypoint14 waypoint26)
(visible waypoint26 waypoint18)
(visible waypoint18 waypoint26)
(visible waypoint26 waypoint29)
(visible waypoint29 waypoint26)
(visible waypoint26 waypoint31)
(visible waypoint31 waypoint26)
(visible waypoint26 waypoint32)
(visible waypoint32 waypoint26)
(visible waypoint27 waypoint1)
(visible waypoint1 waypoint27)
(visible waypoint27 waypoint6)
(visible waypoint6 waypoint27)
(visible waypoint27 waypoint26)
(visible waypoint26 waypoint27)
(visible waypoint27 waypoint29)
(visible waypoint29 waypoint27)
(visible waypoint28 waypoint10)
(visible waypoint10 waypoint28)
(visible waypoint28 waypoint24)
(visible waypoint24 waypoint28)
(visible waypoint29 waypoint0)
(visible waypoint0 waypoint29)
(visible waypoint29 waypoint4)
(visible waypoint4 waypoint29)
(visible waypoint29 waypoint6)
(visible waypoint6 waypoint29)
(visible waypoint29 waypoint13)
(visible waypoint13 waypoint29)
(visible waypoint29 waypoint22)
(visible waypoint22 waypoint29)
(visible waypoint30 waypoint4)
(visible waypoint4 waypoint30)
(visible waypoint30 waypoint6)
(visible waypoint6 waypoint30)
(visible waypoint30 waypoint8)
(visible waypoint8 waypoint30)
(visible waypoint30 waypoint11)
(visible waypoint11 waypoint30)
(visible waypoint30 waypoint12)
(visible waypoint12 waypoint30)
(visible waypoint30 waypoint33)
(visible waypoint33 waypoint30)
(visible waypoint31 waypoint3)
(visible waypoint3 waypoint31)
(visible waypoint31 waypoint22)
(visible waypoint22 waypoint31)
(visible waypoint31 waypoint25)
(visible waypoint25 waypoint31)
(visible waypoint32 waypoint4)
(visible waypoint4 waypoint32)
(visible waypoint32 waypoint6)
(visible waypoint6 waypoint32)
(visible waypoint32 waypoint8)
(visible waypoint8 waypoint32)
(visible waypoint32 waypoint10)
(visible waypoint10 waypoint32)
(visible waypoint32 waypoint12)
(visible waypoint12 waypoint32)
(visible waypoint32 waypoint13)
(visible waypoint13 waypoint32)
(visible waypoint32 waypoint24)
(visible waypoint24 waypoint32)
(visible waypoint33 waypoint14)
(visible waypoint14 waypoint33)
(visible waypoint33 waypoint16)
(visible waypoint16 waypoint33)
(visible waypoint34 waypoint9)
(visible waypoint9 waypoint34)
(visible waypoint34 waypoint16)
(visible waypoint16 waypoint34)
(visible waypoint34 waypoint18)
(visible waypoint18 waypoint34)
(at_lander general waypoint12)
(store_of rover0store rover0)
(equipped_for_rock_analysis rover0)
(equipped_for_imaging rover0)
(can_traverse rover0 waypoint4 waypoint1)
(can_traverse rover0 waypoint1 waypoint4)
(can_traverse rover0 waypoint4 waypoint13)
(can_traverse rover0 waypoint13 waypoint4)
(can_traverse rover0 waypoint4 waypoint16)
(can_traverse rover0 waypoint16 waypoint4)
(can_traverse rover0 waypoint4 waypoint22)
(can_traverse rover0 waypoint22 waypoint4)
(can_traverse rover0 waypoint4 waypoint29)
(can_traverse rover0 waypoint29 waypoint4)
(can_traverse rover0 waypoint4 waypoint30)
(can_traverse rover0 waypoint30 waypoint4)
(can_traverse rover0 waypoint1 waypoint0)
(can_traverse rover0 waypoint0 waypoint1)
(can_traverse rover0 waypoint1 waypoint10)
(can_traverse rover0 waypoint10 waypoint1)
(can_traverse rover0 waypoint1 waypoint12)
(can_traverse rover0 waypoint12 waypoint1)
(can_traverse rover0 waypoint1 waypoint14)
(can_traverse rover0 waypoint14 waypoint1)
(can_traverse rover0 waypoint1 waypoint18)
(can_traverse rover0 waypoint18 waypoint1)
(can_traverse rover0 waypoint1 waypoint27)
(can_traverse rover0 waypoint27 waypoint1)
(can_traverse rover0 waypoint13 waypoint19)
(can_traverse rover0 waypoint19 waypoint13)
(can_traverse rover0 waypoint13 waypoint26)
(can_traverse rover0 waypoint26 waypoint13)
(can_traverse rover0 waypoint16 waypoint3)
(can_traverse rover0 waypoint3 waypoint16)
(can_traverse rover0 waypoint16 waypoint7)
(can_traverse rover0 waypoint7 waypoint16)
(can_traverse rover0 waypoint16 waypoint24)
(can_traverse rover0 waypoint24 waypoint16)
(can_traverse rover0 waypoint16 waypoint28)
(can_traverse rover0 waypoint28 waypoint16)
(can_traverse rover0 waypoint16 waypoint33)
(can_traverse rover0 waypoint33 waypoint16)
(can_traverse rover0 waypoint16 waypoint34)
(can_traverse rover0 waypoint34 waypoint16)
(can_traverse rover0 waypoint22 waypoint11)
(can_traverse rover0 waypoint11 waypoint22)
(can_traverse rover0 waypoint22 waypoint21)
(can_traverse rover0 waypoint21 waypoint22)
(can_traverse rover0 waypoint22 waypoint23)
(can_traverse rover0 waypoint23 waypoint22)
(can_traverse rover0 waypoint22 waypoint31)
(can_traverse rover0 waypoint31 waypoint22)
(can_traverse rover0 waypoint29 waypoint6)
(can_traverse rover0 waypoint6 waypoint29)
(can_traverse rover0 waypoint0 waypoint9)
(can_traverse rover0 waypoint9 waypoint0)
(can_traverse rover0 waypoint0 waypoint15)
(can_traverse rover0 waypoint15 waypoint0)
(can_traverse rover0 waypoint0 waypoint17)
(can_traverse rover0 waypoint17 waypoint0)
(can_traverse rover0 waypoint10 waypoint20)
(can_traverse rover0 waypoint20 waypoint10)
(can_traverse rover0 waypoint10 waypoint32)
(can_traverse rover0 waypoint32 waypoint10)
(can_traverse rover0 waypoint19 waypoint8)
(can_traverse rover0 waypoint8 waypoint19)
(can_traverse rover0 waypoint26 waypoint25)
(can_traverse rover0 waypoint25 waypoint26)
(can_traverse rover0 waypoint3 waypoint2)
(can_traverse rover0 waypoint2 waypoint3)
(can_traverse rover0 waypoint23 waypoint5)
(can_traverse rover0 waypoint5 waypoint23)
(on_board camera0 rover0)
(calibration_target camera0 objective0)
(supports camera0 colour)
(on_board camera1 rover0)
(calibration_target camera1 objective8)
(supports camera1 colour)
(on_board camera2 rover0)
(calibration_target camera2 objective3)
(supports camera2 high_res)
(on_board camera3 rover0)
(calibration_target camera3 objective4)
(supports camera3 colour)
(supports camera3 low_res)
(on_board camera4 rover0)
(calibration_target camera4 objective1)
(supports camera4 high_res)
(supports camera4 low_res)
(on_board camera5 rover0)
(calibration_target camera5 objective1)
(supports camera5 colour)
(supports camera5 high_res)
(supports camera5 low_res)
(on_board camera6 rover0)
(calibration_target camera6 objective2)
(supports camera6 colour)
(on_board camera7 rover0)
(calibration_target camera7 objective0)
(supports camera7 low_res)
(on_board camera8 rover0)
(calibration_target camera8 objective12)
(supports camera8 low_res)
(on_board camera9 rover0)
(calibration_target camera9 objective10)
(supports camera9 colour)
(supports camera9 high_res)
(on_board camera10 rover0)
(calibration_target camera10 objective2)
(supports camera10 high_res)
(supports camera10 low_res)
(on_board camera11 rover0)
(calibration_target camera11 objective1)
(supports camera11 high_res)
(on_board camera12 rover0)
(calibration_target camera12 objective0)
(supports camera12 colour)
(supports camera12 high_res)
(on_board camera13 rover0)
(calibration_target camera13 objective10)
(supports camera13 high_res)
(visible_from objective0 waypoint0)
(visible_from objective0 waypoint15)
(visible_from objective0 waypoint24)
(visible_from objective0 waypoint26)
(visible_from objective0 waypoint27)
(visible_from objective0 waypoint33)
(visible_from objective1 waypoint0)
(visible_from objective1 waypoint1)
(visible_from objective1 waypoint2)
(visible_from objective1 waypoint7)
(visible_from objective1 waypoint8)
(visible_from objective1 waypoint17)
(visible_from objective1 waypoint26)
(visible_from objective1 waypoint29)
(visible_from objective1 waypoint32)
(visible_from objective1 waypoint33)
(visible_from objective1 waypoint34)
(visible_from objective2 waypoint1)
(visible_from objective2 waypoint2)
(visible_from objective2 waypoint4)
(visible_from objective2 waypoint8)
(visible_from objective2 waypoint11)
(visible_from objective2 waypoint13)
(visible_from objective2 waypoint15)
(visible_from objective2 waypoint17)
(visible_from objective2 waypoint21)
(visible_from objective2 waypoint22)
(visible_from objective2 waypoint23)
(visible_from objective2 waypoint24)
(visible_from objective2 waypoint28)
(visible_from objective2 waypoint30)
(visible_from objective2 waypoint33)
(visible_from objective2 waypoint34)
(visible_from objective3 waypoint5)
(visible_from objective3 waypoint7)
(visible_from objective3 waypoint8)
(visible_from objective3 waypoint9)
(visible_from objective3 waypoint10)
(visible_from objective3 waypoint11)
(visible_from objective3 waypoint12)
(visible_from objective3 waypoint13)
(visible_from objective3 waypoint14)
(visible_from objective3 waypoint20)
(visible_from objective3 waypoint21)
(visible_from objective3 waypoint28)
(visible_from objective3 waypoint29)
(visible_from objective3 waypoint31)
(visible_from objective3 waypoint32)
(visible_from objective4 waypoint4)
(visible_from objective4 waypoint5)
(visible_from objective4 waypoint6)
(visible_from objective4 waypoint8)
(visible_from objective4 waypoint9)
(visible_from objective4 waypoint11)
(visible_from objective4 waypoint14)
(visible_from objective4 waypoint16)
(visible_from objective4 waypoint17)
(visible_from objective4 waypoint18)
(visible_from objective4 waypoint19)
(visible_from objective4 waypoint20)
(visible_from objective4 waypoint21)
(visible_from objective4 waypoint22)
(visible_from objective4 waypoint23)
(visible_from objective4 waypoint24)
(visible_from objective4 waypoint26)
(visible_from objective4 waypoint27)
(visible_from objective4 waypoint30)
(visible_from objective4 waypoint31)
(visible_from objective4 waypoint32)
(visible_from objective5 waypoint8)
(visible_from objective5 waypoint13)
(visible_from objective5 waypoint16)
(visible_from objective5 waypoint22)
(visible_from objective5 waypoint24)
(visible_from objective6 waypoint2)
(visible_from objective6 waypoint5)
(visible_from objective6 waypoint6)
(visible_from objective6 waypoint13)
(visible_from objective6 waypoint14)
(visible_from objective6 waypoint17)
(visible_from objective6 waypoint26)
(visible_from objective6 waypoint31)
(visible_from objective6 waypoint32)
(visible_from objective7 waypoint0)
(visible_from objective7 waypoint3)
(visible_from objective7 waypoint7)
(visible_from objective7 waypoint9)
(visible_from objective7 waypoint11)
(visible_from objective7 waypoint12)
(visible_from objective7 waypoint13)
(visible_from objective7 waypoint14)
(visible_from objective7 waypoint18)
(visible_from objective7 waypoint19)
(visible_from objective7 waypoint21)
(visible_from objective7 waypoint27)
(visible_from objective7 waypoint28)
(visible_from objective7 waypoint30)
(visible_from objective7 waypoint31)
(visible_from objective7 waypoint32)
(visible_from objective7 waypoint34)
(visible_from objective8 waypoint0)
(visible_from objective8 waypoint6)
(visible_from objective8 waypoint7)
(visible_from objective8 waypoint8)
(visible_from objective8 waypoint11)
(visible_from objective8 waypoint12)
(visible_from objective8 waypoint14)
(visible_from objective8 waypoint15)
(visible_from objective8 waypoint19)
(visible_from objective8 waypoint20)
(visible_from objective8 waypoint21)
(visible_from objective8 waypoint26)
(visible_from objective8 waypoint27)
(visible_from objective8 waypoint28)
(visible_from objective8 waypoint32)
(visible_from objective8 waypoint33)
(visible_from objective8 waypoint34)
(visible_from objective9 waypoint0)
(visible_from objective9 waypoint1)
(visible_from objective9 waypoint2)
(visible_from objective9 waypoint12)
(visible_from objective9 waypoint15)
(visible_from objective9 waypoint23)
(visible_from objective9 waypoint26)
(visible_from objective9 waypoint29)
(visible_from objective10 waypoint7)
(visible_from objective10 waypoint13)
(visible_from objective10 waypoint18)
(visible_from objective10 waypoint23)
(visible_from objective11 waypoint9)
(visible_from objective11 waypoint10)
(visible_from objective11 waypoint15)
(visible_from objective11 waypoint16)
(visible_from objective11 waypoint17)
(visible_from objective11 waypoint22)
(visible_from objective11 waypoint23)
(visible_from objective11 waypoint29)
(visible_from objective11 waypoint31)
(visible_from objective11 waypoint34)
(visible_from objective12 waypoint0)
(visible_from objective12 waypoint3)
(visible_from objective12 waypoint4)
(visible_from objective12 waypoint6)
(visible_from objective12 waypoint7)
(visible_from objective12 waypoint8)
(visible_from objective12 waypoint9)
(visible_from objective12 waypoint12)
(visible_from objective12 waypoint15)
(visible_from objective12 waypoint16)
(visible_from objective12 waypoint19)
(visible_from objective12 waypoint20)
(visible_from objective12 waypoint22)
(visible_from objective12 waypoint30)
(at_soil_sample waypoint0)
(at_rock_sample waypoint1)
(at_soil_sample waypoint2)
(at_soil_sample waypoint3)
(at_rock_sample waypoint3)
(at_soil_sample waypoint4)
(at_rock_sample waypoint4)
(at_soil_sample waypoint5)
(at_rock_sample waypoint5)
(at_soil_sample waypoint6)
(at_rock_sample waypoint6)
(at_soil_sample waypoint9)
(at_rock_sample waypoint9)
(at_rock_sample waypoint10)
(at_soil_sample waypoint12)
(at_rock_sample waypoint13)
(at_soil_sample waypoint15)
(at_rock_sample waypoint15)
(at_soil_sample waypoint17)
(at_soil_sample waypoint19)
(at_soil_sample waypoint20)
(at_rock_sample waypoint22)
(at_soil_sample waypoint23)
(at_soil_sample waypoint24)
(at_rock_sample waypoint24)
(at_soil_sample waypoint25)
(at_rock_sample waypoint25)
(at_rock_sample waypoint27)
(at_soil_sample waypoint28)
(at_rock_sample waypoint29)
(at_rock_sample waypoint30)
(at_soil_sample waypoint31)
(at_soil_sample waypoint32)
(at_rock_sample waypoint32)
(at_soil_sample waypoint33)
(at_rock_sample waypoint33)
(at_soil_sample waypoint34)
(at_rock_sample waypoint34)
(channel_free general)
(available rover0)
(communicated_rock_data waypoint14)
(communicated_image_data objective2 colour)
(communicated_image_data objective4 colour)
(full rover0store)
(have_image rover0 objective2 colour)
(have_image rover0 objective4 colour)
(have_rock_analysis rover0 waypoint14)
(at rover0 waypoint31)
(have_rock_analysis rover0 waypoint31)
)

(:goal (and
(communicated_rock_data waypoint14)
(communicated_rock_data waypoint24)
(communicated_rock_data waypoint31)
(communicated_rock_data waypoint30)
(communicated_image_data objective2 colour)
(communicated_image_data objective4 colour)
	)
)
)
