(define (problem prb-289_d13_p-TST3-n72-r1w40o11c15-2) (:domain Rover)
(:objects
	general - Lander
	colour high_res low_res - Mode
	rover0 - Rover
	rover0store - Store
	waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 waypoint7 waypoint8 waypoint9 waypoint10 waypoint11 waypoint12 waypoint13 waypoint14 waypoint15 waypoint16 waypoint17 waypoint18 waypoint19 waypoint20 waypoint21 waypoint22 waypoint23 waypoint24 waypoint25 waypoint26 waypoint27 waypoint28 waypoint29 waypoint30 waypoint31 waypoint32 waypoint33 waypoint34 waypoint35 waypoint36 waypoint37 waypoint38 waypoint39 - Waypoint
	camera0 camera1 camera2 camera3 camera4 camera5 camera6 camera7 camera8 camera9 camera10 camera11 camera12 camera13 camera14 - Camera
	objective0 objective1 objective2 objective3 objective4 objective5 objective6 objective7 objective8 objective9 objective10 - Objective
	)
(:init
(visible waypoint0 waypoint17)
(visible waypoint17 waypoint0)
(visible waypoint0 waypoint31)
(visible waypoint31 waypoint0)
(visible waypoint0 waypoint34)
(visible waypoint34 waypoint0)
(visible waypoint1 waypoint13)
(visible waypoint13 waypoint1)
(visible waypoint1 waypoint21)
(visible waypoint21 waypoint1)
(visible waypoint1 waypoint30)
(visible waypoint30 waypoint1)
(visible waypoint1 waypoint33)
(visible waypoint33 waypoint1)
(visible waypoint2 waypoint6)
(visible waypoint6 waypoint2)
(visible waypoint2 waypoint7)
(visible waypoint7 waypoint2)
(visible waypoint2 waypoint39)
(visible waypoint39 waypoint2)
(visible waypoint3 waypoint2)
(visible waypoint2 waypoint3)
(visible waypoint3 waypoint4)
(visible waypoint4 waypoint3)
(visible waypoint3 waypoint14)
(visible waypoint14 waypoint3)
(visible waypoint3 waypoint32)
(visible waypoint32 waypoint3)
(visible waypoint4 waypoint1)
(visible waypoint1 waypoint4)
(visible waypoint4 waypoint22)
(visible waypoint22 waypoint4)
(visible waypoint4 waypoint26)
(visible waypoint26 waypoint4)
(visible waypoint4 waypoint39)
(visible waypoint39 waypoint4)
(visible waypoint5 waypoint13)
(visible waypoint13 waypoint5)
(visible waypoint5 waypoint31)
(visible waypoint31 waypoint5)
(visible waypoint6 waypoint25)
(visible waypoint25 waypoint6)
(visible waypoint6 waypoint31)
(visible waypoint31 waypoint6)
(visible waypoint6 waypoint32)
(visible waypoint32 waypoint6)
(visible waypoint6 waypoint34)
(visible waypoint34 waypoint6)
(visible waypoint6 waypoint38)
(visible waypoint38 waypoint6)
(visible waypoint7 waypoint10)
(visible waypoint10 waypoint7)
(visible waypoint7 waypoint19)
(visible waypoint19 waypoint7)
(visible waypoint7 waypoint23)
(visible waypoint23 waypoint7)
(visible waypoint7 waypoint24)
(visible waypoint24 waypoint7)
(visible waypoint8 waypoint12)
(visible waypoint12 waypoint8)
(visible waypoint9 waypoint14)
(visible waypoint14 waypoint9)
(visible waypoint9 waypoint32)
(visible waypoint32 waypoint9)
(visible waypoint9 waypoint38)
(visible waypoint38 waypoint9)
(visible waypoint10 waypoint2)
(visible waypoint2 waypoint10)
(visible waypoint10 waypoint3)
(visible waypoint3 waypoint10)
(visible waypoint10 waypoint23)
(visible waypoint23 waypoint10)
(visible waypoint10 waypoint27)
(visible waypoint27 waypoint10)
(visible waypoint10 waypoint29)
(visible waypoint29 waypoint10)
(visible waypoint11 waypoint4)
(visible waypoint4 waypoint11)
(visible waypoint11 waypoint8)
(visible waypoint8 waypoint11)
(visible waypoint11 waypoint17)
(visible waypoint17 waypoint11)
(visible waypoint11 waypoint22)
(visible waypoint22 waypoint11)
(visible waypoint11 waypoint23)
(visible waypoint23 waypoint11)
(visible waypoint11 waypoint26)
(visible waypoint26 waypoint11)
(visible waypoint11 waypoint29)
(visible waypoint29 waypoint11)
(visible waypoint12 waypoint4)
(visible waypoint4 waypoint12)
(visible waypoint12 waypoint15)
(visible waypoint15 waypoint12)
(visible waypoint12 waypoint31)
(visible waypoint31 waypoint12)
(visible waypoint12 waypoint36)
(visible waypoint36 waypoint12)
(visible waypoint12 waypoint39)
(visible waypoint39 waypoint12)
(visible waypoint13 waypoint3)
(visible waypoint3 waypoint13)
(visible waypoint13 waypoint16)
(visible waypoint16 waypoint13)
(visible waypoint13 waypoint34)
(visible waypoint34 waypoint13)
(visible waypoint13 waypoint39)
(visible waypoint39 waypoint13)
(visible waypoint14 waypoint0)
(visible waypoint0 waypoint14)
(visible waypoint14 waypoint11)
(visible waypoint11 waypoint14)
(visible waypoint14 waypoint13)
(visible waypoint13 waypoint14)
(visible waypoint14 waypoint20)
(visible waypoint20 waypoint14)
(visible waypoint14 waypoint22)
(visible waypoint22 waypoint14)
(visible waypoint14 waypoint27)
(visible waypoint27 waypoint14)
(visible waypoint14 waypoint28)
(visible waypoint28 waypoint14)
(visible waypoint14 waypoint35)
(visible waypoint35 waypoint14)
(visible waypoint14 waypoint36)
(visible waypoint36 waypoint14)
(visible waypoint14 waypoint37)
(visible waypoint37 waypoint14)
(visible waypoint15 waypoint13)
(visible waypoint13 waypoint15)
(visible waypoint15 waypoint21)
(visible waypoint21 waypoint15)
(visible waypoint15 waypoint35)
(visible waypoint35 waypoint15)
(visible waypoint15 waypoint39)
(visible waypoint39 waypoint15)
(visible waypoint16 waypoint2)
(visible waypoint2 waypoint16)
(visible waypoint16 waypoint19)
(visible waypoint19 waypoint16)
(visible waypoint16 waypoint26)
(visible waypoint26 waypoint16)
(visible waypoint16 waypoint31)
(visible waypoint31 waypoint16)
(visible waypoint16 waypoint33)
(visible waypoint33 waypoint16)
(visible waypoint17 waypoint5)
(visible waypoint5 waypoint17)
(visible waypoint17 waypoint8)
(visible waypoint8 waypoint17)
(visible waypoint17 waypoint34)
(visible waypoint34 waypoint17)
(visible waypoint18 waypoint9)
(visible waypoint9 waypoint18)
(visible waypoint18 waypoint21)
(visible waypoint21 waypoint18)
(visible waypoint18 waypoint35)
(visible waypoint35 waypoint18)
(visible waypoint19 waypoint36)
(visible waypoint36 waypoint19)
(visible waypoint20 waypoint1)
(visible waypoint1 waypoint20)
(visible waypoint20 waypoint18)
(visible waypoint18 waypoint20)
(visible waypoint21 waypoint28)
(visible waypoint28 waypoint21)
(visible waypoint21 waypoint30)
(visible waypoint30 waypoint21)
(visible waypoint22 waypoint20)
(visible waypoint20 waypoint22)
(visible waypoint22 waypoint21)
(visible waypoint21 waypoint22)
(visible waypoint22 waypoint33)
(visible waypoint33 waypoint22)
(visible waypoint23 waypoint2)
(visible waypoint2 waypoint23)
(visible waypoint23 waypoint12)
(visible waypoint12 waypoint23)
(visible waypoint23 waypoint22)
(visible waypoint22 waypoint23)
(visible waypoint23 waypoint25)
(visible waypoint25 waypoint23)
(visible waypoint23 waypoint33)
(visible waypoint33 waypoint23)
(visible waypoint24 waypoint5)
(visible waypoint5 waypoint24)
(visible waypoint24 waypoint6)
(visible waypoint6 waypoint24)
(visible waypoint24 waypoint16)
(visible waypoint16 waypoint24)
(visible waypoint24 waypoint28)
(visible waypoint28 waypoint24)
(visible waypoint24 waypoint31)
(visible waypoint31 waypoint24)
(visible waypoint24 waypoint34)
(visible waypoint34 waypoint24)
(visible waypoint25 waypoint0)
(visible waypoint0 waypoint25)
(visible waypoint25 waypoint9)
(visible waypoint9 waypoint25)
(visible waypoint25 waypoint19)
(visible waypoint19 waypoint25)
(visible waypoint25 waypoint29)
(visible waypoint29 waypoint25)
(visible waypoint25 waypoint32)
(visible waypoint32 waypoint25)
(visible waypoint25 waypoint39)
(visible waypoint39 waypoint25)
(visible waypoint26 waypoint1)
(visible waypoint1 waypoint26)
(visible waypoint26 waypoint12)
(visible waypoint12 waypoint26)
(visible waypoint26 waypoint13)
(visible waypoint13 waypoint26)
(visible waypoint26 waypoint21)
(visible waypoint21 waypoint26)
(visible waypoint26 waypoint23)
(visible waypoint23 waypoint26)
(visible waypoint26 waypoint24)
(visible waypoint24 waypoint26)
(visible waypoint26 waypoint27)
(visible waypoint27 waypoint26)
(visible waypoint26 waypoint33)
(visible waypoint33 waypoint26)
(visible waypoint26 waypoint37)
(visible waypoint37 waypoint26)
(visible waypoint27 waypoint2)
(visible waypoint2 waypoint27)
(visible waypoint27 waypoint11)
(visible waypoint11 waypoint27)
(visible waypoint27 waypoint13)
(visible waypoint13 waypoint27)
(visible waypoint27 waypoint22)
(visible waypoint22 waypoint27)
(visible waypoint27 waypoint29)
(visible waypoint29 waypoint27)
(visible waypoint27 waypoint31)
(visible waypoint31 waypoint27)
(visible waypoint27 waypoint38)
(visible waypoint38 waypoint27)
(visible waypoint28 waypoint3)
(visible waypoint3 waypoint28)
(visible waypoint28 waypoint5)
(visible waypoint5 waypoint28)
(visible waypoint28 waypoint22)
(visible waypoint22 waypoint28)
(visible waypoint28 waypoint26)
(visible waypoint26 waypoint28)
(visible waypoint28 waypoint32)
(visible waypoint32 waypoint28)
(visible waypoint29 waypoint23)
(visible waypoint23 waypoint29)
(visible waypoint30 waypoint0)
(visible waypoint0 waypoint30)
(visible waypoint30 waypoint19)
(visible waypoint19 waypoint30)
(visible waypoint30 waypoint28)
(visible waypoint28 waypoint30)
(visible waypoint31 waypoint2)
(visible waypoint2 waypoint31)
(visible waypoint31 waypoint21)
(visible waypoint21 waypoint31)
(visible waypoint31 waypoint33)
(visible waypoint33 waypoint31)
(visible waypoint32 waypoint0)
(visible waypoint0 waypoint32)
(visible waypoint32 waypoint4)
(visible waypoint4 waypoint32)
(visible waypoint32 waypoint17)
(visible waypoint17 waypoint32)
(visible waypoint32 waypoint19)
(visible waypoint19 waypoint32)
(visible waypoint33 waypoint7)
(visible waypoint7 waypoint33)
(visible waypoint33 waypoint10)
(visible waypoint10 waypoint33)
(visible waypoint33 waypoint11)
(visible waypoint11 waypoint33)
(visible waypoint33 waypoint29)
(visible waypoint29 waypoint33)
(visible waypoint33 waypoint32)
(visible waypoint32 waypoint33)
(visible waypoint33 waypoint37)
(visible waypoint37 waypoint33)
(visible waypoint34 waypoint7)
(visible waypoint7 waypoint34)
(visible waypoint34 waypoint12)
(visible waypoint12 waypoint34)
(visible waypoint34 waypoint19)
(visible waypoint19 waypoint34)
(visible waypoint34 waypoint26)
(visible waypoint26 waypoint34)
(visible waypoint34 waypoint29)
(visible waypoint29 waypoint34)
(visible waypoint35 waypoint13)
(visible waypoint13 waypoint35)
(visible waypoint35 waypoint22)
(visible waypoint22 waypoint35)
(visible waypoint35 waypoint30)
(visible waypoint30 waypoint35)
(visible waypoint35 waypoint37)
(visible waypoint37 waypoint35)
(visible waypoint36 waypoint1)
(visible waypoint1 waypoint36)
(visible waypoint36 waypoint2)
(visible waypoint2 waypoint36)
(visible waypoint36 waypoint10)
(visible waypoint10 waypoint36)
(visible waypoint36 waypoint21)
(visible waypoint21 waypoint36)
(visible waypoint36 waypoint25)
(visible waypoint25 waypoint36)
(visible waypoint36 waypoint26)
(visible waypoint26 waypoint36)
(visible waypoint37 waypoint1)
(visible waypoint1 waypoint37)
(visible waypoint37 waypoint5)
(visible waypoint5 waypoint37)
(visible waypoint37 waypoint8)
(visible waypoint8 waypoint37)
(visible waypoint37 waypoint15)
(visible waypoint15 waypoint37)
(visible waypoint37 waypoint18)
(visible waypoint18 waypoint37)
(visible waypoint37 waypoint22)
(visible waypoint22 waypoint37)
(visible waypoint37 waypoint29)
(visible waypoint29 waypoint37)
(visible waypoint38 waypoint0)
(visible waypoint0 waypoint38)
(visible waypoint38 waypoint7)
(visible waypoint7 waypoint38)
(visible waypoint38 waypoint15)
(visible waypoint15 waypoint38)
(visible waypoint38 waypoint22)
(visible waypoint22 waypoint38)
(visible waypoint38 waypoint30)
(visible waypoint30 waypoint38)
(visible waypoint39 waypoint11)
(visible waypoint11 waypoint39)
(visible waypoint39 waypoint27)
(visible waypoint27 waypoint39)
(visible waypoint39 waypoint30)
(visible waypoint30 waypoint39)
(visible waypoint39 waypoint36)
(visible waypoint36 waypoint39)
(at_lander general waypoint11)
(store_of rover0store rover0)
(equipped_for_soil_analysis rover0)
(equipped_for_imaging rover0)
(can_traverse rover0 waypoint0 waypoint14)
(can_traverse rover0 waypoint14 waypoint0)
(can_traverse rover0 waypoint0 waypoint17)
(can_traverse rover0 waypoint17 waypoint0)
(can_traverse rover0 waypoint0 waypoint25)
(can_traverse rover0 waypoint25 waypoint0)
(can_traverse rover0 waypoint0 waypoint30)
(can_traverse rover0 waypoint30 waypoint0)
(can_traverse rover0 waypoint0 waypoint34)
(can_traverse rover0 waypoint34 waypoint0)
(can_traverse rover0 waypoint0 waypoint38)
(can_traverse rover0 waypoint38 waypoint0)
(can_traverse rover0 waypoint14 waypoint3)
(can_traverse rover0 waypoint3 waypoint14)
(can_traverse rover0 waypoint14 waypoint9)
(can_traverse rover0 waypoint9 waypoint14)
(can_traverse rover0 waypoint14 waypoint11)
(can_traverse rover0 waypoint11 waypoint14)
(can_traverse rover0 waypoint14 waypoint13)
(can_traverse rover0 waypoint13 waypoint14)
(can_traverse rover0 waypoint14 waypoint20)
(can_traverse rover0 waypoint20 waypoint14)
(can_traverse rover0 waypoint14 waypoint22)
(can_traverse rover0 waypoint22 waypoint14)
(can_traverse rover0 waypoint14 waypoint27)
(can_traverse rover0 waypoint27 waypoint14)
(can_traverse rover0 waypoint14 waypoint28)
(can_traverse rover0 waypoint28 waypoint14)
(can_traverse rover0 waypoint14 waypoint36)
(can_traverse rover0 waypoint36 waypoint14)
(can_traverse rover0 waypoint17 waypoint8)
(can_traverse rover0 waypoint8 waypoint17)
(can_traverse rover0 waypoint17 waypoint32)
(can_traverse rover0 waypoint32 waypoint17)
(can_traverse rover0 waypoint25 waypoint6)
(can_traverse rover0 waypoint6 waypoint25)
(can_traverse rover0 waypoint25 waypoint19)
(can_traverse rover0 waypoint19 waypoint25)
(can_traverse rover0 waypoint25 waypoint23)
(can_traverse rover0 waypoint23 waypoint25)
(can_traverse rover0 waypoint25 waypoint29)
(can_traverse rover0 waypoint29 waypoint25)
(can_traverse rover0 waypoint30 waypoint1)
(can_traverse rover0 waypoint1 waypoint30)
(can_traverse rover0 waypoint30 waypoint21)
(can_traverse rover0 waypoint21 waypoint30)
(can_traverse rover0 waypoint30 waypoint39)
(can_traverse rover0 waypoint39 waypoint30)
(can_traverse rover0 waypoint34 waypoint12)
(can_traverse rover0 waypoint12 waypoint34)
(can_traverse rover0 waypoint34 waypoint24)
(can_traverse rover0 waypoint24 waypoint34)
(can_traverse rover0 waypoint38 waypoint7)
(can_traverse rover0 waypoint7 waypoint38)
(can_traverse rover0 waypoint38 waypoint15)
(can_traverse rover0 waypoint15 waypoint38)
(can_traverse rover0 waypoint3 waypoint2)
(can_traverse rover0 waypoint2 waypoint3)
(can_traverse rover0 waypoint3 waypoint10)
(can_traverse rover0 waypoint10 waypoint3)
(can_traverse rover0 waypoint9 waypoint18)
(can_traverse rover0 waypoint18 waypoint9)
(can_traverse rover0 waypoint11 waypoint4)
(can_traverse rover0 waypoint4 waypoint11)
(can_traverse rover0 waypoint11 waypoint33)
(can_traverse rover0 waypoint33 waypoint11)
(can_traverse rover0 waypoint13 waypoint5)
(can_traverse rover0 waypoint5 waypoint13)
(can_traverse rover0 waypoint13 waypoint16)
(can_traverse rover0 waypoint16 waypoint13)
(can_traverse rover0 waypoint13 waypoint26)
(can_traverse rover0 waypoint26 waypoint13)
(can_traverse rover0 waypoint22 waypoint35)
(can_traverse rover0 waypoint35 waypoint22)
(can_traverse rover0 waypoint22 waypoint37)
(can_traverse rover0 waypoint37 waypoint22)
(can_traverse rover0 waypoint6 waypoint31)
(can_traverse rover0 waypoint31 waypoint6)
(on_board camera0 rover0)
(calibration_target camera0 objective9)
(supports camera0 high_res)
(supports camera0 low_res)
(on_board camera1 rover0)
(calibration_target camera1 objective9)
(supports camera1 colour)
(supports camera1 low_res)
(on_board camera2 rover0)
(calibration_target camera2 objective8)
(supports camera2 low_res)
(on_board camera3 rover0)
(calibration_target camera3 objective5)
(supports camera3 colour)
(supports camera3 high_res)
(supports camera3 low_res)
(on_board camera4 rover0)
(calibration_target camera4 objective10)
(supports camera4 colour)
(on_board camera5 rover0)
(calibration_target camera5 objective7)
(supports camera5 colour)
(supports camera5 high_res)
(supports camera5 low_res)
(on_board camera6 rover0)
(calibration_target camera6 objective0)
(supports camera6 colour)
(supports camera6 high_res)
(on_board camera7 rover0)
(calibration_target camera7 objective3)
(supports camera7 low_res)
(on_board camera8 rover0)
(calibration_target camera8 objective3)
(supports camera8 low_res)
(on_board camera9 rover0)
(calibration_target camera9 objective8)
(supports camera9 high_res)
(on_board camera10 rover0)
(calibration_target camera10 objective2)
(supports camera10 colour)
(supports camera10 high_res)
(supports camera10 low_res)
(on_board camera11 rover0)
(calibration_target camera11 objective5)
(supports camera11 colour)
(supports camera11 high_res)
(supports camera11 low_res)
(on_board camera12 rover0)
(calibration_target camera12 objective9)
(supports camera12 colour)
(on_board camera13 rover0)
(calibration_target camera13 objective3)
(supports camera13 colour)
(on_board camera14 rover0)
(calibration_target camera14 objective4)
(supports camera14 colour)
(visible_from objective0 waypoint1)
(visible_from objective0 waypoint2)
(visible_from objective0 waypoint5)
(visible_from objective0 waypoint10)
(visible_from objective0 waypoint16)
(visible_from objective0 waypoint18)
(visible_from objective0 waypoint21)
(visible_from objective0 waypoint34)
(visible_from objective0 waypoint35)
(visible_from objective0 waypoint37)
(visible_from objective1 waypoint2)
(visible_from objective1 waypoint9)
(visible_from objective1 waypoint19)
(visible_from objective1 waypoint22)
(visible_from objective1 waypoint25)
(visible_from objective1 waypoint29)
(visible_from objective1 waypoint39)
(visible_from objective2 waypoint31)
(visible_from objective3 waypoint1)
(visible_from objective3 waypoint2)
(visible_from objective3 waypoint4)
(visible_from objective3 waypoint5)
(visible_from objective3 waypoint8)
(visible_from objective3 waypoint9)
(visible_from objective3 waypoint21)
(visible_from objective3 waypoint23)
(visible_from objective3 waypoint26)
(visible_from objective3 waypoint27)
(visible_from objective3 waypoint29)
(visible_from objective3 waypoint31)
(visible_from objective3 waypoint35)
(visible_from objective4 waypoint12)
(visible_from objective4 waypoint22)
(visible_from objective4 waypoint23)
(visible_from objective4 waypoint24)
(visible_from objective4 waypoint33)
(visible_from objective4 waypoint38)
(visible_from objective5 waypoint1)
(visible_from objective5 waypoint2)
(visible_from objective5 waypoint4)
(visible_from objective5 waypoint6)
(visible_from objective5 waypoint8)
(visible_from objective5 waypoint9)
(visible_from objective5 waypoint12)
(visible_from objective5 waypoint13)
(visible_from objective5 waypoint14)
(visible_from objective5 waypoint18)
(visible_from objective5 waypoint19)
(visible_from objective5 waypoint22)
(visible_from objective5 waypoint23)
(visible_from objective5 waypoint24)
(visible_from objective5 waypoint26)
(visible_from objective5 waypoint27)
(visible_from objective5 waypoint28)
(visible_from objective5 waypoint31)
(visible_from objective5 waypoint32)
(visible_from objective5 waypoint34)
(visible_from objective5 waypoint35)
(visible_from objective5 waypoint36)
(visible_from objective5 waypoint37)
(visible_from objective5 waypoint39)
(visible_from objective6 waypoint6)
(visible_from objective6 waypoint10)
(visible_from objective6 waypoint29)
(visible_from objective6 waypoint34)
(visible_from objective7 waypoint0)
(visible_from objective7 waypoint1)
(visible_from objective7 waypoint2)
(visible_from objective7 waypoint3)
(visible_from objective7 waypoint5)
(visible_from objective7 waypoint6)
(visible_from objective7 waypoint10)
(visible_from objective7 waypoint12)
(visible_from objective7 waypoint13)
(visible_from objective7 waypoint14)
(visible_from objective7 waypoint15)
(visible_from objective7 waypoint18)
(visible_from objective7 waypoint19)
(visible_from objective7 waypoint20)
(visible_from objective7 waypoint21)
(visible_from objective7 waypoint25)
(visible_from objective7 waypoint27)
(visible_from objective7 waypoint30)
(visible_from objective7 waypoint32)
(visible_from objective7 waypoint33)
(visible_from objective7 waypoint34)
(visible_from objective7 waypoint36)
(visible_from objective7 waypoint38)
(visible_from objective7 waypoint39)
(visible_from objective8 waypoint8)
(visible_from objective9 waypoint3)
(visible_from objective9 waypoint12)
(visible_from objective9 waypoint24)
(visible_from objective9 waypoint28)
(visible_from objective9 waypoint29)
(visible_from objective9 waypoint32)
(visible_from objective9 waypoint35)
(visible_from objective10 waypoint0)
(visible_from objective10 waypoint4)
(visible_from objective10 waypoint5)
(visible_from objective10 waypoint8)
(visible_from objective10 waypoint11)
(visible_from objective10 waypoint17)
(visible_from objective10 waypoint22)
(visible_from objective10 waypoint23)
(visible_from objective10 waypoint25)
(visible_from objective10 waypoint29)
(visible_from objective10 waypoint30)
(visible_from objective10 waypoint33)
(visible_from objective10 waypoint36)
(visible_from objective10 waypoint37)
(visible_from objective10 waypoint38)
(at_rock_sample waypoint0)
(at_soil_sample waypoint1)
(at_rock_sample waypoint1)
(at_rock_sample waypoint3)
(at_rock_sample waypoint4)
(at_rock_sample waypoint6)
(at_rock_sample waypoint7)
(at_soil_sample waypoint9)
(at_rock_sample waypoint9)
(at_rock_sample waypoint10)
(at_rock_sample waypoint11)
(at_soil_sample waypoint13)
(at_rock_sample waypoint13)
(at_rock_sample waypoint14)
(at_soil_sample waypoint15)
(at_rock_sample waypoint15)
(at_rock_sample waypoint17)
(at_rock_sample waypoint18)
(at_rock_sample waypoint19)
(at_rock_sample waypoint20)
(at_soil_sample waypoint21)
(at_soil_sample waypoint23)
(at_soil_sample waypoint24)
(at_rock_sample waypoint25)
(at_soil_sample waypoint26)
(at_rock_sample waypoint27)
(at_rock_sample waypoint28)
(at_soil_sample waypoint30)
(at_rock_sample waypoint30)
(at_rock_sample waypoint31)
(at_soil_sample waypoint33)
(at_rock_sample waypoint33)
(at_soil_sample waypoint34)
(at_rock_sample waypoint34)
(at_rock_sample waypoint35)
(at_soil_sample waypoint36)
(at_rock_sample waypoint36)
(at_rock_sample waypoint37)
(at_rock_sample waypoint38)
(at_rock_sample waypoint39)
(channel_free general)
(available rover0)
(empty rover0store)
(communicated_soil_data waypoint28)
(communicated_soil_data waypoint22)
(communicated_soil_data waypoint20)
(communicated_image_data objective7 colour)
(calibrated camera4 rover0)
(have_image rover0 objective7 colour)
(have_soil_analysis rover0 waypoint22)
(have_soil_analysis rover0 waypoint28)
(have_image rover0 objective9 low_res)
(have_soil_analysis rover0 waypoint20)
(at rover0 waypoint29)
)

(:goal (and
(communicated_soil_data waypoint34)
(communicated_soil_data waypoint28)
(communicated_soil_data waypoint22)
(communicated_soil_data waypoint20)
(communicated_image_data objective1 colour)
(communicated_image_data objective9 colour)
(communicated_image_data objective7 colour)
(communicated_image_data objective9 low_res)
	)
)
)
