(define (problem prb-305_d13_p-TST3-n74-r1w40o13c15-3) (:domain Rover)
(:objects
	general - Lander
	colour high_res low_res - Mode
	rover0 - Rover
	rover0store - Store
	waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 waypoint7 waypoint8 waypoint9 waypoint10 waypoint11 waypoint12 waypoint13 waypoint14 waypoint15 waypoint16 waypoint17 waypoint18 waypoint19 waypoint20 waypoint21 waypoint22 waypoint23 waypoint24 waypoint25 waypoint26 waypoint27 waypoint28 waypoint29 waypoint30 waypoint31 waypoint32 waypoint33 waypoint34 waypoint35 waypoint36 waypoint37 waypoint38 waypoint39 - Waypoint
	camera0 camera1 camera2 camera3 camera4 camera5 camera6 camera7 camera8 camera9 camera10 camera11 camera12 camera13 camera14 - Camera
	objective0 objective1 objective2 objective3 objective4 objective5 objective6 objective7 objective8 objective9 objective10 objective11 objective12 - Objective
	)
(:init
(visible waypoint0 waypoint3)
(visible waypoint3 waypoint0)
(visible waypoint0 waypoint8)
(visible waypoint8 waypoint0)
(visible waypoint0 waypoint9)
(visible waypoint9 waypoint0)
(visible waypoint0 waypoint10)
(visible waypoint10 waypoint0)
(visible waypoint0 waypoint18)
(visible waypoint18 waypoint0)
(visible waypoint0 waypoint20)
(visible waypoint20 waypoint0)
(visible waypoint0 waypoint38)
(visible waypoint38 waypoint0)
(visible waypoint1 waypoint8)
(visible waypoint8 waypoint1)
(visible waypoint1 waypoint17)
(visible waypoint17 waypoint1)
(visible waypoint1 waypoint18)
(visible waypoint18 waypoint1)
(visible waypoint1 waypoint26)
(visible waypoint26 waypoint1)
(visible waypoint1 waypoint30)
(visible waypoint30 waypoint1)
(visible waypoint1 waypoint34)
(visible waypoint34 waypoint1)
(visible waypoint1 waypoint35)
(visible waypoint35 waypoint1)
(visible waypoint2 waypoint8)
(visible waypoint8 waypoint2)
(visible waypoint2 waypoint22)
(visible waypoint22 waypoint2)
(visible waypoint2 waypoint23)
(visible waypoint23 waypoint2)
(visible waypoint2 waypoint29)
(visible waypoint29 waypoint2)
(visible waypoint2 waypoint37)
(visible waypoint37 waypoint2)
(visible waypoint3 waypoint2)
(visible waypoint2 waypoint3)
(visible waypoint3 waypoint6)
(visible waypoint6 waypoint3)
(visible waypoint3 waypoint18)
(visible waypoint18 waypoint3)
(visible waypoint4 waypoint8)
(visible waypoint8 waypoint4)
(visible waypoint4 waypoint17)
(visible waypoint17 waypoint4)
(visible waypoint4 waypoint24)
(visible waypoint24 waypoint4)
(visible waypoint4 waypoint25)
(visible waypoint25 waypoint4)
(visible waypoint5 waypoint12)
(visible waypoint12 waypoint5)
(visible waypoint5 waypoint35)
(visible waypoint35 waypoint5)
(visible waypoint6 waypoint14)
(visible waypoint14 waypoint6)
(visible waypoint7 waypoint1)
(visible waypoint1 waypoint7)
(visible waypoint7 waypoint18)
(visible waypoint18 waypoint7)
(visible waypoint7 waypoint20)
(visible waypoint20 waypoint7)
(visible waypoint7 waypoint25)
(visible waypoint25 waypoint7)
(visible waypoint8 waypoint6)
(visible waypoint6 waypoint8)
(visible waypoint8 waypoint15)
(visible waypoint15 waypoint8)
(visible waypoint8 waypoint21)
(visible waypoint21 waypoint8)
(visible waypoint8 waypoint31)
(visible waypoint31 waypoint8)
(visible waypoint8 waypoint34)
(visible waypoint34 waypoint8)
(visible waypoint9 waypoint5)
(visible waypoint5 waypoint9)
(visible waypoint9 waypoint8)
(visible waypoint8 waypoint9)
(visible waypoint9 waypoint12)
(visible waypoint12 waypoint9)
(visible waypoint9 waypoint19)
(visible waypoint19 waypoint9)
(visible waypoint9 waypoint23)
(visible waypoint23 waypoint9)
(visible waypoint9 waypoint30)
(visible waypoint30 waypoint9)
(visible waypoint10 waypoint1)
(visible waypoint1 waypoint10)
(visible waypoint10 waypoint6)
(visible waypoint6 waypoint10)
(visible waypoint10 waypoint8)
(visible waypoint8 waypoint10)
(visible waypoint10 waypoint25)
(visible waypoint25 waypoint10)
(visible waypoint11 waypoint4)
(visible waypoint4 waypoint11)
(visible waypoint11 waypoint5)
(visible waypoint5 waypoint11)
(visible waypoint11 waypoint16)
(visible waypoint16 waypoint11)
(visible waypoint11 waypoint22)
(visible waypoint22 waypoint11)
(visible waypoint12 waypoint7)
(visible waypoint7 waypoint12)
(visible waypoint12 waypoint21)
(visible waypoint21 waypoint12)
(visible waypoint12 waypoint31)
(visible waypoint31 waypoint12)
(visible waypoint13 waypoint1)
(visible waypoint1 waypoint13)
(visible waypoint13 waypoint11)
(visible waypoint11 waypoint13)
(visible waypoint13 waypoint34)
(visible waypoint34 waypoint13)
(visible waypoint14 waypoint3)
(visible waypoint3 waypoint14)
(visible waypoint14 waypoint30)
(visible waypoint30 waypoint14)
(visible waypoint15 waypoint0)
(visible waypoint0 waypoint15)
(visible waypoint15 waypoint10)
(visible waypoint10 waypoint15)
(visible waypoint15 waypoint17)
(visible waypoint17 waypoint15)
(visible waypoint15 waypoint18)
(visible waypoint18 waypoint15)
(visible waypoint16 waypoint5)
(visible waypoint5 waypoint16)
(visible waypoint16 waypoint25)
(visible waypoint25 waypoint16)
(visible waypoint16 waypoint35)
(visible waypoint35 waypoint16)
(visible waypoint17 waypoint3)
(visible waypoint3 waypoint17)
(visible waypoint17 waypoint12)
(visible waypoint12 waypoint17)
(visible waypoint17 waypoint26)
(visible waypoint26 waypoint17)
(visible waypoint17 waypoint29)
(visible waypoint29 waypoint17)
(visible waypoint17 waypoint35)
(visible waypoint35 waypoint17)
(visible waypoint17 waypoint39)
(visible waypoint39 waypoint17)
(visible waypoint18 waypoint10)
(visible waypoint10 waypoint18)
(visible waypoint18 waypoint24)
(visible waypoint24 waypoint18)
(visible waypoint19 waypoint12)
(visible waypoint12 waypoint19)
(visible waypoint19 waypoint15)
(visible waypoint15 waypoint19)
(visible waypoint19 waypoint18)
(visible waypoint18 waypoint19)
(visible waypoint19 waypoint24)
(visible waypoint24 waypoint19)
(visible waypoint19 waypoint36)
(visible waypoint36 waypoint19)
(visible waypoint19 waypoint39)
(visible waypoint39 waypoint19)
(visible waypoint20 waypoint3)
(visible waypoint3 waypoint20)
(visible waypoint20 waypoint13)
(visible waypoint13 waypoint20)
(visible waypoint20 waypoint25)
(visible waypoint25 waypoint20)
(visible waypoint20 waypoint29)
(visible waypoint29 waypoint20)
(visible waypoint21 waypoint9)
(visible waypoint9 waypoint21)
(visible waypoint21 waypoint16)
(visible waypoint16 waypoint21)
(visible waypoint21 waypoint19)
(visible waypoint19 waypoint21)
(visible waypoint21 waypoint25)
(visible waypoint25 waypoint21)
(visible waypoint21 waypoint29)
(visible waypoint29 waypoint21)
(visible waypoint21 waypoint31)
(visible waypoint31 waypoint21)
(visible waypoint21 waypoint37)
(visible waypoint37 waypoint21)
(visible waypoint22 waypoint3)
(visible waypoint3 waypoint22)
(visible waypoint22 waypoint8)
(visible waypoint8 waypoint22)
(visible waypoint22 waypoint20)
(visible waypoint20 waypoint22)
(visible waypoint22 waypoint31)
(visible waypoint31 waypoint22)
(visible waypoint22 waypoint34)
(visible waypoint34 waypoint22)
(visible waypoint22 waypoint36)
(visible waypoint36 waypoint22)
(visible waypoint23 waypoint7)
(visible waypoint7 waypoint23)
(visible waypoint23 waypoint12)
(visible waypoint12 waypoint23)
(visible waypoint23 waypoint25)
(visible waypoint25 waypoint23)
(visible waypoint23 waypoint36)
(visible waypoint36 waypoint23)
(visible waypoint23 waypoint39)
(visible waypoint39 waypoint23)
(visible waypoint24 waypoint20)
(visible waypoint20 waypoint24)
(visible waypoint24 waypoint22)
(visible waypoint22 waypoint24)
(visible waypoint25 waypoint37)
(visible waypoint37 waypoint25)
(visible waypoint26 waypoint7)
(visible waypoint7 waypoint26)
(visible waypoint26 waypoint11)
(visible waypoint11 waypoint26)
(visible waypoint26 waypoint14)
(visible waypoint14 waypoint26)
(visible waypoint26 waypoint20)
(visible waypoint20 waypoint26)
(visible waypoint26 waypoint31)
(visible waypoint31 waypoint26)
(visible waypoint27 waypoint3)
(visible waypoint3 waypoint27)
(visible waypoint27 waypoint12)
(visible waypoint12 waypoint27)
(visible waypoint27 waypoint16)
(visible waypoint16 waypoint27)
(visible waypoint27 waypoint23)
(visible waypoint23 waypoint27)
(visible waypoint28 waypoint3)
(visible waypoint3 waypoint28)
(visible waypoint28 waypoint5)
(visible waypoint5 waypoint28)
(visible waypoint28 waypoint26)
(visible waypoint26 waypoint28)
(visible waypoint28 waypoint36)
(visible waypoint36 waypoint28)
(visible waypoint28 waypoint38)
(visible waypoint38 waypoint28)
(visible waypoint29 waypoint5)
(visible waypoint5 waypoint29)
(visible waypoint29 waypoint8)
(visible waypoint8 waypoint29)
(visible waypoint29 waypoint9)
(visible waypoint9 waypoint29)
(visible waypoint29 waypoint12)
(visible waypoint12 waypoint29)
(visible waypoint29 waypoint25)
(visible waypoint25 waypoint29)
(visible waypoint29 waypoint26)
(visible waypoint26 waypoint29)
(visible waypoint30 waypoint27)
(visible waypoint27 waypoint30)
(visible waypoint31 waypoint7)
(visible waypoint7 waypoint31)
(visible waypoint31 waypoint23)
(visible waypoint23 waypoint31)
(visible waypoint31 waypoint32)
(visible waypoint32 waypoint31)
(visible waypoint32 waypoint6)
(visible waypoint6 waypoint32)
(visible waypoint32 waypoint15)
(visible waypoint15 waypoint32)
(visible waypoint32 waypoint17)
(visible waypoint17 waypoint32)
(visible waypoint32 waypoint18)
(visible waypoint18 waypoint32)
(visible waypoint32 waypoint21)
(visible waypoint21 waypoint32)
(visible waypoint32 waypoint29)
(visible waypoint29 waypoint32)
(visible waypoint33 waypoint3)
(visible waypoint3 waypoint33)
(visible waypoint33 waypoint5)
(visible waypoint5 waypoint33)
(visible waypoint33 waypoint16)
(visible waypoint16 waypoint33)
(visible waypoint33 waypoint17)
(visible waypoint17 waypoint33)
(visible waypoint33 waypoint18)
(visible waypoint18 waypoint33)
(visible waypoint33 waypoint20)
(visible waypoint20 waypoint33)
(visible waypoint33 waypoint34)
(visible waypoint34 waypoint33)
(visible waypoint34 waypoint2)
(visible waypoint2 waypoint34)
(visible waypoint34 waypoint14)
(visible waypoint14 waypoint34)
(visible waypoint34 waypoint23)
(visible waypoint23 waypoint34)
(visible waypoint34 waypoint24)
(visible waypoint24 waypoint34)
(visible waypoint34 waypoint27)
(visible waypoint27 waypoint34)
(visible waypoint34 waypoint30)
(visible waypoint30 waypoint34)
(visible waypoint35 waypoint9)
(visible waypoint9 waypoint35)
(visible waypoint35 waypoint13)
(visible waypoint13 waypoint35)
(visible waypoint35 waypoint23)
(visible waypoint23 waypoint35)
(visible waypoint35 waypoint28)
(visible waypoint28 waypoint35)
(visible waypoint35 waypoint32)
(visible waypoint32 waypoint35)
(visible waypoint36 waypoint0)
(visible waypoint0 waypoint36)
(visible waypoint36 waypoint7)
(visible waypoint7 waypoint36)
(visible waypoint36 waypoint8)
(visible waypoint8 waypoint36)
(visible waypoint36 waypoint15)
(visible waypoint15 waypoint36)
(visible waypoint36 waypoint32)
(visible waypoint32 waypoint36)
(visible waypoint37 waypoint14)
(visible waypoint14 waypoint37)
(visible waypoint37 waypoint20)
(visible waypoint20 waypoint37)
(visible waypoint37 waypoint31)
(visible waypoint31 waypoint37)
(visible waypoint37 waypoint33)
(visible waypoint33 waypoint37)
(visible waypoint38 waypoint31)
(visible waypoint31 waypoint38)
(visible waypoint39 waypoint6)
(visible waypoint6 waypoint39)
(visible waypoint39 waypoint7)
(visible waypoint7 waypoint39)
(visible waypoint39 waypoint26)
(visible waypoint26 waypoint39)
(visible waypoint39 waypoint28)
(visible waypoint28 waypoint39)
(visible waypoint39 waypoint29)
(visible waypoint29 waypoint39)
(visible waypoint39 waypoint38)
(visible waypoint38 waypoint39)
(at_lander general waypoint38)
(store_of rover0store rover0)
(equipped_for_imaging rover0)
(can_traverse rover0 waypoint35 waypoint1)
(can_traverse rover0 waypoint1 waypoint35)
(can_traverse rover0 waypoint35 waypoint5)
(can_traverse rover0 waypoint5 waypoint35)
(can_traverse rover0 waypoint35 waypoint16)
(can_traverse rover0 waypoint16 waypoint35)
(can_traverse rover0 waypoint35 waypoint17)
(can_traverse rover0 waypoint17 waypoint35)
(can_traverse rover0 waypoint35 waypoint23)
(can_traverse rover0 waypoint23 waypoint35)
(can_traverse rover0 waypoint35 waypoint28)
(can_traverse rover0 waypoint28 waypoint35)
(can_traverse rover0 waypoint35 waypoint32)
(can_traverse rover0 waypoint32 waypoint35)
(can_traverse rover0 waypoint1 waypoint8)
(can_traverse rover0 waypoint8 waypoint1)
(can_traverse rover0 waypoint1 waypoint10)
(can_traverse rover0 waypoint10 waypoint1)
(can_traverse rover0 waypoint1 waypoint13)
(can_traverse rover0 waypoint13 waypoint1)
(can_traverse rover0 waypoint1 waypoint18)
(can_traverse rover0 waypoint18 waypoint1)
(can_traverse rover0 waypoint1 waypoint26)
(can_traverse rover0 waypoint26 waypoint1)
(can_traverse rover0 waypoint1 waypoint30)
(can_traverse rover0 waypoint30 waypoint1)
(can_traverse rover0 waypoint1 waypoint34)
(can_traverse rover0 waypoint34 waypoint1)
(can_traverse rover0 waypoint5 waypoint11)
(can_traverse rover0 waypoint11 waypoint5)
(can_traverse rover0 waypoint5 waypoint12)
(can_traverse rover0 waypoint12 waypoint5)
(can_traverse rover0 waypoint5 waypoint29)
(can_traverse rover0 waypoint29 waypoint5)
(can_traverse rover0 waypoint16 waypoint21)
(can_traverse rover0 waypoint21 waypoint16)
(can_traverse rover0 waypoint16 waypoint25)
(can_traverse rover0 waypoint25 waypoint16)
(can_traverse rover0 waypoint16 waypoint27)
(can_traverse rover0 waypoint27 waypoint16)
(can_traverse rover0 waypoint16 waypoint33)
(can_traverse rover0 waypoint33 waypoint16)
(can_traverse rover0 waypoint17 waypoint3)
(can_traverse rover0 waypoint3 waypoint17)
(can_traverse rover0 waypoint17 waypoint4)
(can_traverse rover0 waypoint4 waypoint17)
(can_traverse rover0 waypoint17 waypoint39)
(can_traverse rover0 waypoint39 waypoint17)
(can_traverse rover0 waypoint23 waypoint9)
(can_traverse rover0 waypoint9 waypoint23)
(can_traverse rover0 waypoint28 waypoint36)
(can_traverse rover0 waypoint36 waypoint28)
(can_traverse rover0 waypoint28 waypoint38)
(can_traverse rover0 waypoint38 waypoint28)
(can_traverse rover0 waypoint32 waypoint6)
(can_traverse rover0 waypoint6 waypoint32)
(can_traverse rover0 waypoint32 waypoint31)
(can_traverse rover0 waypoint31 waypoint32)
(can_traverse rover0 waypoint8 waypoint0)
(can_traverse rover0 waypoint0 waypoint8)
(can_traverse rover0 waypoint8 waypoint22)
(can_traverse rover0 waypoint22 waypoint8)
(can_traverse rover0 waypoint10 waypoint15)
(can_traverse rover0 waypoint15 waypoint10)
(can_traverse rover0 waypoint26 waypoint7)
(can_traverse rover0 waypoint7 waypoint26)
(can_traverse rover0 waypoint26 waypoint14)
(can_traverse rover0 waypoint14 waypoint26)
(can_traverse rover0 waypoint26 waypoint20)
(can_traverse rover0 waypoint20 waypoint26)
(can_traverse rover0 waypoint34 waypoint2)
(can_traverse rover0 waypoint2 waypoint34)
(can_traverse rover0 waypoint34 waypoint24)
(can_traverse rover0 waypoint24 waypoint34)
(can_traverse rover0 waypoint12 waypoint19)
(can_traverse rover0 waypoint19 waypoint12)
(can_traverse rover0 waypoint21 waypoint37)
(can_traverse rover0 waypoint37 waypoint21)
(on_board camera0 rover0)
(calibration_target camera0 objective8)
(supports camera0 colour)
(supports camera0 low_res)
(on_board camera1 rover0)
(calibration_target camera1 objective10)
(supports camera1 low_res)
(on_board camera2 rover0)
(calibration_target camera2 objective10)
(supports camera2 low_res)
(on_board camera3 rover0)
(calibration_target camera3 objective11)
(supports camera3 colour)
(supports camera3 low_res)
(on_board camera4 rover0)
(calibration_target camera4 objective6)
(supports camera4 colour)
(on_board camera5 rover0)
(calibration_target camera5 objective2)
(supports camera5 high_res)
(supports camera5 low_res)
(on_board camera6 rover0)
(calibration_target camera6 objective7)
(supports camera6 high_res)
(supports camera6 low_res)
(on_board camera7 rover0)
(calibration_target camera7 objective7)
(supports camera7 high_res)
(supports camera7 low_res)
(on_board camera8 rover0)
(calibration_target camera8 objective12)
(supports camera8 high_res)
(on_board camera9 rover0)
(calibration_target camera9 objective6)
(supports camera9 colour)
(supports camera9 high_res)
(on_board camera10 rover0)
(calibration_target camera10 objective12)
(supports camera10 high_res)
(on_board camera11 rover0)
(calibration_target camera11 objective4)
(supports camera11 high_res)
(on_board camera12 rover0)
(calibration_target camera12 objective9)
(supports camera12 high_res)
(on_board camera13 rover0)
(calibration_target camera13 objective4)
(supports camera13 colour)
(on_board camera14 rover0)
(calibration_target camera14 objective8)
(supports camera14 colour)
(supports camera14 low_res)
(visible_from objective0 waypoint1)
(visible_from objective0 waypoint2)
(visible_from objective0 waypoint5)
(visible_from objective0 waypoint10)
(visible_from objective0 waypoint12)
(visible_from objective0 waypoint15)
(visible_from objective0 waypoint16)
(visible_from objective0 waypoint18)
(visible_from objective0 waypoint21)
(visible_from objective0 waypoint25)
(visible_from objective0 waypoint28)
(visible_from objective0 waypoint31)
(visible_from objective0 waypoint32)
(visible_from objective0 waypoint33)
(visible_from objective0 waypoint36)
(visible_from objective0 waypoint37)
(visible_from objective0 waypoint39)
(visible_from objective1 waypoint0)
(visible_from objective1 waypoint1)
(visible_from objective1 waypoint2)
(visible_from objective1 waypoint3)
(visible_from objective1 waypoint8)
(visible_from objective1 waypoint9)
(visible_from objective1 waypoint10)
(visible_from objective1 waypoint16)
(visible_from objective1 waypoint26)
(visible_from objective1 waypoint28)
(visible_from objective1 waypoint29)
(visible_from objective1 waypoint31)
(visible_from objective1 waypoint32)
(visible_from objective1 waypoint33)
(visible_from objective1 waypoint34)
(visible_from objective1 waypoint35)
(visible_from objective1 waypoint37)
(visible_from objective1 waypoint38)
(visible_from objective2 waypoint2)
(visible_from objective2 waypoint4)
(visible_from objective2 waypoint7)
(visible_from objective2 waypoint9)
(visible_from objective2 waypoint10)
(visible_from objective2 waypoint11)
(visible_from objective2 waypoint12)
(visible_from objective2 waypoint15)
(visible_from objective2 waypoint16)
(visible_from objective2 waypoint17)
(visible_from objective2 waypoint18)
(visible_from objective2 waypoint19)
(visible_from objective2 waypoint20)
(visible_from objective2 waypoint21)
(visible_from objective2 waypoint24)
(visible_from objective2 waypoint25)
(visible_from objective2 waypoint28)
(visible_from objective2 waypoint29)
(visible_from objective2 waypoint31)
(visible_from objective2 waypoint32)
(visible_from objective2 waypoint33)
(visible_from objective2 waypoint34)
(visible_from objective2 waypoint35)
(visible_from objective2 waypoint37)
(visible_from objective2 waypoint38)
(visible_from objective2 waypoint39)
(visible_from objective3 waypoint0)
(visible_from objective3 waypoint2)
(visible_from objective3 waypoint5)
(visible_from objective3 waypoint13)
(visible_from objective3 waypoint23)
(visible_from objective3 waypoint27)
(visible_from objective3 waypoint31)
(visible_from objective3 waypoint33)
(visible_from objective3 waypoint34)
(visible_from objective4 waypoint1)
(visible_from objective4 waypoint2)
(visible_from objective4 waypoint3)
(visible_from objective4 waypoint5)
(visible_from objective4 waypoint6)
(visible_from objective4 waypoint7)
(visible_from objective4 waypoint8)
(visible_from objective4 waypoint12)
(visible_from objective4 waypoint13)
(visible_from objective4 waypoint16)
(visible_from objective4 waypoint17)
(visible_from objective4 waypoint18)
(visible_from objective4 waypoint19)
(visible_from objective4 waypoint22)
(visible_from objective4 waypoint23)
(visible_from objective4 waypoint32)
(visible_from objective4 waypoint33)
(visible_from objective4 waypoint34)
(visible_from objective4 waypoint35)
(visible_from objective4 waypoint38)
(visible_from objective4 waypoint39)
(visible_from objective5 waypoint0)
(visible_from objective5 waypoint1)
(visible_from objective5 waypoint2)
(visible_from objective5 waypoint4)
(visible_from objective5 waypoint5)
(visible_from objective5 waypoint6)
(visible_from objective5 waypoint8)
(visible_from objective5 waypoint12)
(visible_from objective5 waypoint13)
(visible_from objective5 waypoint15)
(visible_from objective5 waypoint16)
(visible_from objective5 waypoint19)
(visible_from objective5 waypoint20)
(visible_from objective5 waypoint24)
(visible_from objective5 waypoint27)
(visible_from objective5 waypoint29)
(visible_from objective5 waypoint31)
(visible_from objective5 waypoint32)
(visible_from objective5 waypoint34)
(visible_from objective5 waypoint35)
(visible_from objective5 waypoint37)
(visible_from objective5 waypoint38)
(visible_from objective5 waypoint39)
(visible_from objective6 waypoint0)
(visible_from objective6 waypoint1)
(visible_from objective6 waypoint4)
(visible_from objective6 waypoint5)
(visible_from objective6 waypoint6)
(visible_from objective6 waypoint7)
(visible_from objective6 waypoint8)
(visible_from objective6 waypoint9)
(visible_from objective6 waypoint10)
(visible_from objective6 waypoint11)
(visible_from objective6 waypoint12)
(visible_from objective6 waypoint14)
(visible_from objective6 waypoint15)
(visible_from objective6 waypoint17)
(visible_from objective6 waypoint18)
(visible_from objective6 waypoint19)
(visible_from objective6 waypoint22)
(visible_from objective6 waypoint24)
(visible_from objective6 waypoint32)
(visible_from objective6 waypoint33)
(visible_from objective6 waypoint34)
(visible_from objective6 waypoint35)
(visible_from objective6 waypoint36)
(visible_from objective6 waypoint37)
(visible_from objective6 waypoint38)
(visible_from objective6 waypoint39)
(visible_from objective7 waypoint1)
(visible_from objective7 waypoint13)
(visible_from objective7 waypoint16)
(visible_from objective7 waypoint22)
(visible_from objective7 waypoint31)
(visible_from objective7 waypoint35)
(visible_from objective7 waypoint37)
(visible_from objective8 waypoint8)
(visible_from objective8 waypoint10)
(visible_from objective8 waypoint14)
(visible_from objective8 waypoint17)
(visible_from objective8 waypoint19)
(visible_from objective8 waypoint20)
(visible_from objective8 waypoint23)
(visible_from objective8 waypoint34)
(visible_from objective8 waypoint38)
(visible_from objective8 waypoint39)
(visible_from objective9 waypoint0)
(visible_from objective9 waypoint1)
(visible_from objective9 waypoint2)
(visible_from objective9 waypoint3)
(visible_from objective9 waypoint8)
(visible_from objective9 waypoint9)
(visible_from objective9 waypoint11)
(visible_from objective9 waypoint13)
(visible_from objective9 waypoint14)
(visible_from objective9 waypoint19)
(visible_from objective9 waypoint21)
(visible_from objective9 waypoint22)
(visible_from objective9 waypoint30)
(visible_from objective9 waypoint39)
(visible_from objective10 waypoint2)
(visible_from objective10 waypoint4)
(visible_from objective10 waypoint6)
(visible_from objective10 waypoint12)
(visible_from objective10 waypoint13)
(visible_from objective10 waypoint14)
(visible_from objective10 waypoint15)
(visible_from objective10 waypoint16)
(visible_from objective10 waypoint18)
(visible_from objective10 waypoint21)
(visible_from objective10 waypoint25)
(visible_from objective10 waypoint26)
(visible_from objective10 waypoint27)
(visible_from objective10 waypoint32)
(visible_from objective10 waypoint35)
(visible_from objective10 waypoint36)
(visible_from objective10 waypoint37)
(visible_from objective10 waypoint38)
(visible_from objective11 waypoint0)
(visible_from objective11 waypoint1)
(visible_from objective11 waypoint2)
(visible_from objective11 waypoint4)
(visible_from objective11 waypoint5)
(visible_from objective11 waypoint6)
(visible_from objective11 waypoint7)
(visible_from objective11 waypoint10)
(visible_from objective11 waypoint11)
(visible_from objective11 waypoint12)
(visible_from objective11 waypoint13)
(visible_from objective11 waypoint18)
(visible_from objective11 waypoint19)
(visible_from objective11 waypoint21)
(visible_from objective11 waypoint23)
(visible_from objective11 waypoint24)
(visible_from objective11 waypoint25)
(visible_from objective11 waypoint27)
(visible_from objective11 waypoint29)
(visible_from objective11 waypoint30)
(visible_from objective11 waypoint35)
(visible_from objective11 waypoint37)
(visible_from objective11 waypoint38)
(visible_from objective12 waypoint0)
(visible_from objective12 waypoint1)
(visible_from objective12 waypoint2)
(visible_from objective12 waypoint4)
(visible_from objective12 waypoint5)
(visible_from objective12 waypoint6)
(visible_from objective12 waypoint7)
(visible_from objective12 waypoint8)
(visible_from objective12 waypoint9)
(visible_from objective12 waypoint11)
(visible_from objective12 waypoint13)
(visible_from objective12 waypoint16)
(visible_from objective12 waypoint17)
(visible_from objective12 waypoint19)
(visible_from objective12 waypoint20)
(visible_from objective12 waypoint21)
(visible_from objective12 waypoint23)
(visible_from objective12 waypoint25)
(visible_from objective12 waypoint28)
(visible_from objective12 waypoint29)
(visible_from objective12 waypoint30)
(visible_from objective12 waypoint31)
(visible_from objective12 waypoint32)
(visible_from objective12 waypoint35)
(visible_from objective12 waypoint37)
(at_soil_sample waypoint0)
(at_rock_sample waypoint0)
(at_soil_sample waypoint1)
(at_rock_sample waypoint1)
(at_soil_sample waypoint2)
(at_rock_sample waypoint2)
(at_rock_sample waypoint4)
(at_soil_sample waypoint5)
(at_rock_sample waypoint5)
(at_rock_sample waypoint6)
(at_soil_sample waypoint7)
(at_rock_sample waypoint7)
(at_rock_sample waypoint8)
(at_rock_sample waypoint9)
(at_soil_sample waypoint10)
(at_soil_sample waypoint12)
(at_rock_sample waypoint12)
(at_soil_sample waypoint13)
(at_rock_sample waypoint13)
(at_rock_sample waypoint15)
(at_soil_sample waypoint19)
(at_soil_sample waypoint20)
(at_soil_sample waypoint21)
(at_soil_sample waypoint22)
(at_soil_sample waypoint24)
(at_rock_sample waypoint24)
(at_soil_sample waypoint25)
(at_soil_sample waypoint26)
(at_soil_sample waypoint27)
(at_rock_sample waypoint27)
(at_soil_sample waypoint28)
(at_rock_sample waypoint29)
(at_rock_sample waypoint32)
(at_soil_sample waypoint33)
(at_rock_sample waypoint33)
(at_soil_sample waypoint36)
(at_rock_sample waypoint36)
(at_soil_sample waypoint38)
(channel_free general)
(at rover0 waypoint35)
(available rover0)
(empty rover0store)
(calibrated camera1 rover0)
)

(:goal (and
(communicated_image_data objective10 high_res)
(communicated_image_data objective8 low_res)
(communicated_image_data objective2 high_res)
	)
)
)
