(define (problem roverprob3) (:domain Rover)
(:objects
	general - Lander
	colour high_res low_res - Mode
	rover0 rover1 rover2 - Rover
	rover0store rover1store rover2store - Store
	waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 waypoint7 waypoint8 waypoint9 waypoint10 waypoint11 waypoint12 waypoint13 waypoint14 waypoint15 waypoint16 waypoint17 waypoint18 waypoint19 waypoint20 waypoint21 waypoint22 waypoint23 waypoint24 waypoint25 waypoint26 waypoint27 waypoint28 waypoint29 waypoint30 waypoint31 waypoint32 waypoint33 waypoint34 waypoint35 waypoint36 waypoint37 waypoint38 waypoint39 - Waypoint
	camera0 camera1 camera2 camera3 camera4 camera5 - Camera
	objective0 objective1 objective2 objective3 objective4 objective5 - Objective
	)
(:init
	(visible waypoint0 waypoint3)
	(visible waypoint3 waypoint0)
	(visible waypoint0 waypoint8)
	(visible waypoint8 waypoint0)
	(visible waypoint0 waypoint9)
	(visible waypoint9 waypoint0)
	(visible waypoint0 waypoint10)
	(visible waypoint10 waypoint0)
	(visible waypoint0 waypoint18)
	(visible waypoint18 waypoint0)
	(visible waypoint0 waypoint20)
	(visible waypoint20 waypoint0)
	(visible waypoint0 waypoint38)
	(visible waypoint38 waypoint0)
	(visible waypoint1 waypoint8)
	(visible waypoint8 waypoint1)
	(visible waypoint1 waypoint17)
	(visible waypoint17 waypoint1)
	(visible waypoint1 waypoint18)
	(visible waypoint18 waypoint1)
	(visible waypoint1 waypoint26)
	(visible waypoint26 waypoint1)
	(visible waypoint1 waypoint30)
	(visible waypoint30 waypoint1)
	(visible waypoint1 waypoint34)
	(visible waypoint34 waypoint1)
	(visible waypoint1 waypoint35)
	(visible waypoint35 waypoint1)
	(visible waypoint2 waypoint8)
	(visible waypoint8 waypoint2)
	(visible waypoint2 waypoint22)
	(visible waypoint22 waypoint2)
	(visible waypoint2 waypoint23)
	(visible waypoint23 waypoint2)
	(visible waypoint2 waypoint29)
	(visible waypoint29 waypoint2)
	(visible waypoint2 waypoint37)
	(visible waypoint37 waypoint2)
	(visible waypoint3 waypoint2)
	(visible waypoint2 waypoint3)
	(visible waypoint3 waypoint6)
	(visible waypoint6 waypoint3)
	(visible waypoint3 waypoint18)
	(visible waypoint18 waypoint3)
	(visible waypoint4 waypoint8)
	(visible waypoint8 waypoint4)
	(visible waypoint4 waypoint17)
	(visible waypoint17 waypoint4)
	(visible waypoint4 waypoint24)
	(visible waypoint24 waypoint4)
	(visible waypoint4 waypoint25)
	(visible waypoint25 waypoint4)
	(visible waypoint5 waypoint12)
	(visible waypoint12 waypoint5)
	(visible waypoint5 waypoint35)
	(visible waypoint35 waypoint5)
	(visible waypoint6 waypoint14)
	(visible waypoint14 waypoint6)
	(visible waypoint7 waypoint1)
	(visible waypoint1 waypoint7)
	(visible waypoint7 waypoint18)
	(visible waypoint18 waypoint7)
	(visible waypoint7 waypoint20)
	(visible waypoint20 waypoint7)
	(visible waypoint7 waypoint25)
	(visible waypoint25 waypoint7)
	(visible waypoint8 waypoint6)
	(visible waypoint6 waypoint8)
	(visible waypoint8 waypoint15)
	(visible waypoint15 waypoint8)
	(visible waypoint8 waypoint21)
	(visible waypoint21 waypoint8)
	(visible waypoint8 waypoint31)
	(visible waypoint31 waypoint8)
	(visible waypoint8 waypoint34)
	(visible waypoint34 waypoint8)
	(visible waypoint9 waypoint5)
	(visible waypoint5 waypoint9)
	(visible waypoint9 waypoint8)
	(visible waypoint8 waypoint9)
	(visible waypoint9 waypoint12)
	(visible waypoint12 waypoint9)
	(visible waypoint9 waypoint19)
	(visible waypoint19 waypoint9)
	(visible waypoint9 waypoint23)
	(visible waypoint23 waypoint9)
	(visible waypoint9 waypoint30)
	(visible waypoint30 waypoint9)
	(visible waypoint10 waypoint1)
	(visible waypoint1 waypoint10)
	(visible waypoint10 waypoint6)
	(visible waypoint6 waypoint10)
	(visible waypoint10 waypoint8)
	(visible waypoint8 waypoint10)
	(visible waypoint10 waypoint25)
	(visible waypoint25 waypoint10)
	(visible waypoint11 waypoint4)
	(visible waypoint4 waypoint11)
	(visible waypoint11 waypoint5)
	(visible waypoint5 waypoint11)
	(visible waypoint11 waypoint16)
	(visible waypoint16 waypoint11)
	(visible waypoint11 waypoint22)
	(visible waypoint22 waypoint11)
	(visible waypoint12 waypoint7)
	(visible waypoint7 waypoint12)
	(visible waypoint12 waypoint21)
	(visible waypoint21 waypoint12)
	(visible waypoint12 waypoint31)
	(visible waypoint31 waypoint12)
	(visible waypoint13 waypoint1)
	(visible waypoint1 waypoint13)
	(visible waypoint13 waypoint11)
	(visible waypoint11 waypoint13)
	(visible waypoint13 waypoint34)
	(visible waypoint34 waypoint13)
	(visible waypoint14 waypoint3)
	(visible waypoint3 waypoint14)
	(visible waypoint14 waypoint30)
	(visible waypoint30 waypoint14)
	(visible waypoint15 waypoint0)
	(visible waypoint0 waypoint15)
	(visible waypoint15 waypoint10)
	(visible waypoint10 waypoint15)
	(visible waypoint15 waypoint17)
	(visible waypoint17 waypoint15)
	(visible waypoint15 waypoint18)
	(visible waypoint18 waypoint15)
	(visible waypoint16 waypoint5)
	(visible waypoint5 waypoint16)
	(visible waypoint16 waypoint25)
	(visible waypoint25 waypoint16)
	(visible waypoint16 waypoint35)
	(visible waypoint35 waypoint16)
	(visible waypoint17 waypoint3)
	(visible waypoint3 waypoint17)
	(visible waypoint17 waypoint12)
	(visible waypoint12 waypoint17)
	(visible waypoint17 waypoint26)
	(visible waypoint26 waypoint17)
	(visible waypoint17 waypoint29)
	(visible waypoint29 waypoint17)
	(visible waypoint17 waypoint35)
	(visible waypoint35 waypoint17)
	(visible waypoint17 waypoint39)
	(visible waypoint39 waypoint17)
	(visible waypoint18 waypoint10)
	(visible waypoint10 waypoint18)
	(visible waypoint18 waypoint24)
	(visible waypoint24 waypoint18)
	(visible waypoint19 waypoint12)
	(visible waypoint12 waypoint19)
	(visible waypoint19 waypoint15)
	(visible waypoint15 waypoint19)
	(visible waypoint19 waypoint18)
	(visible waypoint18 waypoint19)
	(visible waypoint19 waypoint24)
	(visible waypoint24 waypoint19)
	(visible waypoint19 waypoint36)
	(visible waypoint36 waypoint19)
	(visible waypoint19 waypoint39)
	(visible waypoint39 waypoint19)
	(visible waypoint20 waypoint3)
	(visible waypoint3 waypoint20)
	(visible waypoint20 waypoint13)
	(visible waypoint13 waypoint20)
	(visible waypoint20 waypoint25)
	(visible waypoint25 waypoint20)
	(visible waypoint20 waypoint29)
	(visible waypoint29 waypoint20)
	(visible waypoint21 waypoint9)
	(visible waypoint9 waypoint21)
	(visible waypoint21 waypoint16)
	(visible waypoint16 waypoint21)
	(visible waypoint21 waypoint19)
	(visible waypoint19 waypoint21)
	(visible waypoint21 waypoint25)
	(visible waypoint25 waypoint21)
	(visible waypoint21 waypoint29)
	(visible waypoint29 waypoint21)
	(visible waypoint21 waypoint31)
	(visible waypoint31 waypoint21)
	(visible waypoint21 waypoint37)
	(visible waypoint37 waypoint21)
	(visible waypoint22 waypoint3)
	(visible waypoint3 waypoint22)
	(visible waypoint22 waypoint8)
	(visible waypoint8 waypoint22)
	(visible waypoint22 waypoint20)
	(visible waypoint20 waypoint22)
	(visible waypoint22 waypoint31)
	(visible waypoint31 waypoint22)
	(visible waypoint22 waypoint34)
	(visible waypoint34 waypoint22)
	(visible waypoint22 waypoint36)
	(visible waypoint36 waypoint22)
	(visible waypoint23 waypoint7)
	(visible waypoint7 waypoint23)
	(visible waypoint23 waypoint12)
	(visible waypoint12 waypoint23)
	(visible waypoint23 waypoint25)
	(visible waypoint25 waypoint23)
	(visible waypoint23 waypoint36)
	(visible waypoint36 waypoint23)
	(visible waypoint23 waypoint39)
	(visible waypoint39 waypoint23)
	(visible waypoint24 waypoint20)
	(visible waypoint20 waypoint24)
	(visible waypoint24 waypoint22)
	(visible waypoint22 waypoint24)
	(visible waypoint25 waypoint37)
	(visible waypoint37 waypoint25)
	(visible waypoint26 waypoint7)
	(visible waypoint7 waypoint26)
	(visible waypoint26 waypoint11)
	(visible waypoint11 waypoint26)
	(visible waypoint26 waypoint14)
	(visible waypoint14 waypoint26)
	(visible waypoint26 waypoint20)
	(visible waypoint20 waypoint26)
	(visible waypoint26 waypoint31)
	(visible waypoint31 waypoint26)
	(visible waypoint27 waypoint3)
	(visible waypoint3 waypoint27)
	(visible waypoint27 waypoint12)
	(visible waypoint12 waypoint27)
	(visible waypoint27 waypoint16)
	(visible waypoint16 waypoint27)
	(visible waypoint27 waypoint23)
	(visible waypoint23 waypoint27)
	(visible waypoint28 waypoint3)
	(visible waypoint3 waypoint28)
	(visible waypoint28 waypoint5)
	(visible waypoint5 waypoint28)
	(visible waypoint28 waypoint26)
	(visible waypoint26 waypoint28)
	(visible waypoint28 waypoint36)
	(visible waypoint36 waypoint28)
	(visible waypoint28 waypoint38)
	(visible waypoint38 waypoint28)
	(visible waypoint29 waypoint5)
	(visible waypoint5 waypoint29)
	(visible waypoint29 waypoint8)
	(visible waypoint8 waypoint29)
	(visible waypoint29 waypoint9)
	(visible waypoint9 waypoint29)
	(visible waypoint29 waypoint12)
	(visible waypoint12 waypoint29)
	(visible waypoint29 waypoint25)
	(visible waypoint25 waypoint29)
	(visible waypoint29 waypoint26)
	(visible waypoint26 waypoint29)
	(visible waypoint30 waypoint27)
	(visible waypoint27 waypoint30)
	(visible waypoint31 waypoint7)
	(visible waypoint7 waypoint31)
	(visible waypoint31 waypoint23)
	(visible waypoint23 waypoint31)
	(visible waypoint31 waypoint32)
	(visible waypoint32 waypoint31)
	(visible waypoint32 waypoint6)
	(visible waypoint6 waypoint32)
	(visible waypoint32 waypoint15)
	(visible waypoint15 waypoint32)
	(visible waypoint32 waypoint17)
	(visible waypoint17 waypoint32)
	(visible waypoint32 waypoint18)
	(visible waypoint18 waypoint32)
	(visible waypoint32 waypoint21)
	(visible waypoint21 waypoint32)
	(visible waypoint32 waypoint29)
	(visible waypoint29 waypoint32)
	(visible waypoint33 waypoint3)
	(visible waypoint3 waypoint33)
	(visible waypoint33 waypoint5)
	(visible waypoint5 waypoint33)
	(visible waypoint33 waypoint16)
	(visible waypoint16 waypoint33)
	(visible waypoint33 waypoint17)
	(visible waypoint17 waypoint33)
	(visible waypoint33 waypoint18)
	(visible waypoint18 waypoint33)
	(visible waypoint33 waypoint20)
	(visible waypoint20 waypoint33)
	(visible waypoint33 waypoint34)
	(visible waypoint34 waypoint33)
	(visible waypoint34 waypoint2)
	(visible waypoint2 waypoint34)
	(visible waypoint34 waypoint14)
	(visible waypoint14 waypoint34)
	(visible waypoint34 waypoint23)
	(visible waypoint23 waypoint34)
	(visible waypoint34 waypoint24)
	(visible waypoint24 waypoint34)
	(visible waypoint34 waypoint27)
	(visible waypoint27 waypoint34)
	(visible waypoint34 waypoint30)
	(visible waypoint30 waypoint34)
	(visible waypoint35 waypoint9)
	(visible waypoint9 waypoint35)
	(visible waypoint35 waypoint13)
	(visible waypoint13 waypoint35)
	(visible waypoint35 waypoint23)
	(visible waypoint23 waypoint35)
	(visible waypoint35 waypoint28)
	(visible waypoint28 waypoint35)
	(visible waypoint35 waypoint32)
	(visible waypoint32 waypoint35)
	(visible waypoint36 waypoint0)
	(visible waypoint0 waypoint36)
	(visible waypoint36 waypoint7)
	(visible waypoint7 waypoint36)
	(visible waypoint36 waypoint8)
	(visible waypoint8 waypoint36)
	(visible waypoint36 waypoint15)
	(visible waypoint15 waypoint36)
	(visible waypoint36 waypoint32)
	(visible waypoint32 waypoint36)
	(visible waypoint37 waypoint14)
	(visible waypoint14 waypoint37)
	(visible waypoint37 waypoint20)
	(visible waypoint20 waypoint37)
	(visible waypoint37 waypoint31)
	(visible waypoint31 waypoint37)
	(visible waypoint37 waypoint33)
	(visible waypoint33 waypoint37)
	(visible waypoint38 waypoint31)
	(visible waypoint31 waypoint38)
	(visible waypoint39 waypoint6)
	(visible waypoint6 waypoint39)
	(visible waypoint39 waypoint7)
	(visible waypoint7 waypoint39)
	(visible waypoint39 waypoint26)
	(visible waypoint26 waypoint39)
	(visible waypoint39 waypoint28)
	(visible waypoint28 waypoint39)
	(visible waypoint39 waypoint29)
	(visible waypoint29 waypoint39)
	(visible waypoint39 waypoint38)
	(visible waypoint38 waypoint39)
	(at_rock_sample waypoint2)
	(at_soil_sample waypoint3)
	(at_rock_sample waypoint3)
	(at_soil_sample waypoint5)
	(at_rock_sample waypoint5)
	(at_soil_sample waypoint6)
	(at_rock_sample waypoint7)
	(at_soil_sample waypoint9)
	(at_soil_sample waypoint10)
	(at_rock_sample waypoint11)
	(at_soil_sample waypoint12)
	(at_soil_sample waypoint13)
	(at_rock_sample waypoint13)
	(at_soil_sample waypoint15)
	(at_rock_sample waypoint16)
	(at_soil_sample waypoint17)
	(at_rock_sample waypoint17)
	(at_soil_sample waypoint18)
	(at_rock_sample waypoint18)
	(at_soil_sample waypoint19)
	(at_rock_sample waypoint19)
	(at_soil_sample waypoint20)
	(at_rock_sample waypoint21)
	(at_soil_sample waypoint22)
	(at_rock_sample waypoint22)
	(at_soil_sample waypoint23)
	(at_rock_sample waypoint24)
	(at_soil_sample waypoint25)
	(at_rock_sample waypoint26)
	(at_rock_sample waypoint28)
	(at_soil_sample waypoint29)
	(at_rock_sample waypoint29)
	(at_rock_sample waypoint30)
	(at_soil_sample waypoint31)
	(at_rock_sample waypoint31)
	(at_soil_sample waypoint33)
	(at_rock_sample waypoint34)
	(at_soil_sample waypoint38)
	(at_lander general waypoint38)
	(channel_free general)
	(at rover0 waypoint35)
	(available rover0)
	(store_of rover0store rover0)
	(empty rover0store)
	(equipped_for_imaging rover0)
	(can_traverse rover0 waypoint35 waypoint1)
	(can_traverse rover0 waypoint1 waypoint35)
	(can_traverse rover0 waypoint35 waypoint5)
	(can_traverse rover0 waypoint5 waypoint35)
	(can_traverse rover0 waypoint35 waypoint16)
	(can_traverse rover0 waypoint16 waypoint35)
	(can_traverse rover0 waypoint35 waypoint17)
	(can_traverse rover0 waypoint17 waypoint35)
	(can_traverse rover0 waypoint35 waypoint23)
	(can_traverse rover0 waypoint23 waypoint35)
	(can_traverse rover0 waypoint35 waypoint28)
	(can_traverse rover0 waypoint28 waypoint35)
	(can_traverse rover0 waypoint35 waypoint32)
	(can_traverse rover0 waypoint32 waypoint35)
	(can_traverse rover0 waypoint1 waypoint8)
	(can_traverse rover0 waypoint8 waypoint1)
	(can_traverse rover0 waypoint1 waypoint10)
	(can_traverse rover0 waypoint10 waypoint1)
	(can_traverse rover0 waypoint1 waypoint13)
	(can_traverse rover0 waypoint13 waypoint1)
	(can_traverse rover0 waypoint1 waypoint18)
	(can_traverse rover0 waypoint18 waypoint1)
	(can_traverse rover0 waypoint1 waypoint26)
	(can_traverse rover0 waypoint26 waypoint1)
	(can_traverse rover0 waypoint1 waypoint30)
	(can_traverse rover0 waypoint30 waypoint1)
	(can_traverse rover0 waypoint1 waypoint34)
	(can_traverse rover0 waypoint34 waypoint1)
	(can_traverse rover0 waypoint5 waypoint11)
	(can_traverse rover0 waypoint11 waypoint5)
	(can_traverse rover0 waypoint5 waypoint12)
	(can_traverse rover0 waypoint12 waypoint5)
	(can_traverse rover0 waypoint5 waypoint29)
	(can_traverse rover0 waypoint29 waypoint5)
	(can_traverse rover0 waypoint16 waypoint21)
	(can_traverse rover0 waypoint21 waypoint16)
	(can_traverse rover0 waypoint16 waypoint25)
	(can_traverse rover0 waypoint25 waypoint16)
	(can_traverse rover0 waypoint16 waypoint27)
	(can_traverse rover0 waypoint27 waypoint16)
	(can_traverse rover0 waypoint16 waypoint33)
	(can_traverse rover0 waypoint33 waypoint16)
	(can_traverse rover0 waypoint17 waypoint3)
	(can_traverse rover0 waypoint3 waypoint17)
	(can_traverse rover0 waypoint17 waypoint4)
	(can_traverse rover0 waypoint4 waypoint17)
	(can_traverse rover0 waypoint17 waypoint39)
	(can_traverse rover0 waypoint39 waypoint17)
	(can_traverse rover0 waypoint23 waypoint9)
	(can_traverse rover0 waypoint9 waypoint23)
	(can_traverse rover0 waypoint28 waypoint36)
	(can_traverse rover0 waypoint36 waypoint28)
	(can_traverse rover0 waypoint28 waypoint38)
	(can_traverse rover0 waypoint38 waypoint28)
	(can_traverse rover0 waypoint32 waypoint6)
	(can_traverse rover0 waypoint6 waypoint32)
	(can_traverse rover0 waypoint32 waypoint31)
	(can_traverse rover0 waypoint31 waypoint32)
	(can_traverse rover0 waypoint8 waypoint0)
	(can_traverse rover0 waypoint0 waypoint8)
	(can_traverse rover0 waypoint8 waypoint22)
	(can_traverse rover0 waypoint22 waypoint8)
	(can_traverse rover0 waypoint10 waypoint15)
	(can_traverse rover0 waypoint15 waypoint10)
	(can_traverse rover0 waypoint26 waypoint7)
	(can_traverse rover0 waypoint7 waypoint26)
	(can_traverse rover0 waypoint26 waypoint14)
	(can_traverse rover0 waypoint14 waypoint26)
	(can_traverse rover0 waypoint26 waypoint20)
	(can_traverse rover0 waypoint20 waypoint26)
	(can_traverse rover0 waypoint34 waypoint2)
	(can_traverse rover0 waypoint2 waypoint34)
	(can_traverse rover0 waypoint34 waypoint24)
	(can_traverse rover0 waypoint24 waypoint34)
	(can_traverse rover0 waypoint12 waypoint19)
	(can_traverse rover0 waypoint19 waypoint12)
	(can_traverse rover0 waypoint21 waypoint37)
	(can_traverse rover0 waypoint37 waypoint21)
	(at rover1 waypoint27)
	(available rover1)
	(store_of rover1store rover1)
	(empty rover1store)
	(equipped_for_soil_analysis rover1)
	(equipped_for_imaging rover1)
	(can_traverse rover1 waypoint27 waypoint3)
	(can_traverse rover1 waypoint3 waypoint27)
	(can_traverse rover1 waypoint27 waypoint12)
	(can_traverse rover1 waypoint12 waypoint27)
	(can_traverse rover1 waypoint27 waypoint16)
	(can_traverse rover1 waypoint16 waypoint27)
	(can_traverse rover1 waypoint27 waypoint23)
	(can_traverse rover1 waypoint23 waypoint27)
	(can_traverse rover1 waypoint27 waypoint30)
	(can_traverse rover1 waypoint30 waypoint27)
	(can_traverse rover1 waypoint27 waypoint34)
	(can_traverse rover1 waypoint34 waypoint27)
	(can_traverse rover1 waypoint3 waypoint2)
	(can_traverse rover1 waypoint2 waypoint3)
	(can_traverse rover1 waypoint3 waypoint6)
	(can_traverse rover1 waypoint6 waypoint3)
	(can_traverse rover1 waypoint3 waypoint14)
	(can_traverse rover1 waypoint14 waypoint3)
	(can_traverse rover1 waypoint3 waypoint17)
	(can_traverse rover1 waypoint17 waypoint3)
	(can_traverse rover1 waypoint3 waypoint20)
	(can_traverse rover1 waypoint20 waypoint3)
	(can_traverse rover1 waypoint3 waypoint28)
	(can_traverse rover1 waypoint28 waypoint3)
	(can_traverse rover1 waypoint12 waypoint7)
	(can_traverse rover1 waypoint7 waypoint12)
	(can_traverse rover1 waypoint12 waypoint9)
	(can_traverse rover1 waypoint9 waypoint12)
	(can_traverse rover1 waypoint12 waypoint21)
	(can_traverse rover1 waypoint21 waypoint12)
	(can_traverse rover1 waypoint12 waypoint29)
	(can_traverse rover1 waypoint29 waypoint12)
	(can_traverse rover1 waypoint12 waypoint31)
	(can_traverse rover1 waypoint31 waypoint12)
	(can_traverse rover1 waypoint16 waypoint5)
	(can_traverse rover1 waypoint5 waypoint16)
	(can_traverse rover1 waypoint16 waypoint11)
	(can_traverse rover1 waypoint11 waypoint16)
	(can_traverse rover1 waypoint16 waypoint25)
	(can_traverse rover1 waypoint25 waypoint16)
	(can_traverse rover1 waypoint16 waypoint33)
	(can_traverse rover1 waypoint33 waypoint16)
	(can_traverse rover1 waypoint16 waypoint35)
	(can_traverse rover1 waypoint35 waypoint16)
	(can_traverse rover1 waypoint23 waypoint36)
	(can_traverse rover1 waypoint36 waypoint23)
	(can_traverse rover1 waypoint23 waypoint39)
	(can_traverse rover1 waypoint39 waypoint23)
	(can_traverse rover1 waypoint34 waypoint1)
	(can_traverse rover1 waypoint1 waypoint34)
	(can_traverse rover1 waypoint34 waypoint8)
	(can_traverse rover1 waypoint8 waypoint34)
	(can_traverse rover1 waypoint34 waypoint22)
	(can_traverse rover1 waypoint22 waypoint34)
	(can_traverse rover1 waypoint34 waypoint24)
	(can_traverse rover1 waypoint24 waypoint34)
	(can_traverse rover1 waypoint2 waypoint37)
	(can_traverse rover1 waypoint37 waypoint2)
	(can_traverse rover1 waypoint6 waypoint10)
	(can_traverse rover1 waypoint10 waypoint6)
	(can_traverse rover1 waypoint6 waypoint32)
	(can_traverse rover1 waypoint32 waypoint6)
	(can_traverse rover1 waypoint14 waypoint26)
	(can_traverse rover1 waypoint26 waypoint14)
	(can_traverse rover1 waypoint17 waypoint4)
	(can_traverse rover1 waypoint4 waypoint17)
	(can_traverse rover1 waypoint17 waypoint15)
	(can_traverse rover1 waypoint15 waypoint17)
	(can_traverse rover1 waypoint20 waypoint0)
	(can_traverse rover1 waypoint0 waypoint20)
	(can_traverse rover1 waypoint20 waypoint13)
	(can_traverse rover1 waypoint13 waypoint20)
	(can_traverse rover1 waypoint28 waypoint38)
	(can_traverse rover1 waypoint38 waypoint28)
	(can_traverse rover1 waypoint7 waypoint18)
	(can_traverse rover1 waypoint18 waypoint7)
	(can_traverse rover1 waypoint21 waypoint19)
	(can_traverse rover1 waypoint19 waypoint21)
	(at rover2 waypoint37)
	(available rover2)
	(store_of rover2store rover2)
	(empty rover2store)
	(equipped_for_rock_analysis rover2)
	(equipped_for_imaging rover2)
	(can_traverse rover2 waypoint37 waypoint2)
	(can_traverse rover2 waypoint2 waypoint37)
	(can_traverse rover2 waypoint37 waypoint20)
	(can_traverse rover2 waypoint20 waypoint37)
	(can_traverse rover2 waypoint37 waypoint21)
	(can_traverse rover2 waypoint21 waypoint37)
	(can_traverse rover2 waypoint37 waypoint25)
	(can_traverse rover2 waypoint25 waypoint37)
	(can_traverse rover2 waypoint37 waypoint31)
	(can_traverse rover2 waypoint31 waypoint37)
	(can_traverse rover2 waypoint2 waypoint3)
	(can_traverse rover2 waypoint3 waypoint2)
	(can_traverse rover2 waypoint2 waypoint8)
	(can_traverse rover2 waypoint8 waypoint2)
	(can_traverse rover2 waypoint2 waypoint22)
	(can_traverse rover2 waypoint22 waypoint2)
	(can_traverse rover2 waypoint2 waypoint23)
	(can_traverse rover2 waypoint23 waypoint2)
	(can_traverse rover2 waypoint2 waypoint29)
	(can_traverse rover2 waypoint29 waypoint2)
	(can_traverse rover2 waypoint2 waypoint34)
	(can_traverse rover2 waypoint34 waypoint2)
	(can_traverse rover2 waypoint20 waypoint7)
	(can_traverse rover2 waypoint7 waypoint20)
	(can_traverse rover2 waypoint20 waypoint13)
	(can_traverse rover2 waypoint13 waypoint20)
	(can_traverse rover2 waypoint20 waypoint24)
	(can_traverse rover2 waypoint24 waypoint20)
	(can_traverse rover2 waypoint20 waypoint26)
	(can_traverse rover2 waypoint26 waypoint20)
	(can_traverse rover2 waypoint21 waypoint16)
	(can_traverse rover2 waypoint16 waypoint21)
	(can_traverse rover2 waypoint21 waypoint32)
	(can_traverse rover2 waypoint32 waypoint21)
	(can_traverse rover2 waypoint31 waypoint12)
	(can_traverse rover2 waypoint12 waypoint31)
	(can_traverse rover2 waypoint31 waypoint38)
	(can_traverse rover2 waypoint38 waypoint31)
	(can_traverse rover2 waypoint3 waypoint0)
	(can_traverse rover2 waypoint0 waypoint3)
	(can_traverse rover2 waypoint3 waypoint14)
	(can_traverse rover2 waypoint14 waypoint3)
	(can_traverse rover2 waypoint3 waypoint17)
	(can_traverse rover2 waypoint17 waypoint3)
	(can_traverse rover2 waypoint3 waypoint28)
	(can_traverse rover2 waypoint28 waypoint3)
	(can_traverse rover2 waypoint3 waypoint33)
	(can_traverse rover2 waypoint33 waypoint3)
	(can_traverse rover2 waypoint8 waypoint1)
	(can_traverse rover2 waypoint1 waypoint8)
	(can_traverse rover2 waypoint8 waypoint4)
	(can_traverse rover2 waypoint4 waypoint8)
	(can_traverse rover2 waypoint8 waypoint9)
	(can_traverse rover2 waypoint9 waypoint8)
	(can_traverse rover2 waypoint8 waypoint10)
	(can_traverse rover2 waypoint10 waypoint8)
	(can_traverse rover2 waypoint8 waypoint15)
	(can_traverse rover2 waypoint15 waypoint8)
	(can_traverse rover2 waypoint8 waypoint36)
	(can_traverse rover2 waypoint36 waypoint8)
	(can_traverse rover2 waypoint22 waypoint11)
	(can_traverse rover2 waypoint11 waypoint22)
	(can_traverse rover2 waypoint23 waypoint27)
	(can_traverse rover2 waypoint27 waypoint23)
	(can_traverse rover2 waypoint23 waypoint35)
	(can_traverse rover2 waypoint35 waypoint23)
	(can_traverse rover2 waypoint23 waypoint39)
	(can_traverse rover2 waypoint39 waypoint23)
	(can_traverse rover2 waypoint29 waypoint5)
	(can_traverse rover2 waypoint5 waypoint29)
	(can_traverse rover2 waypoint7 waypoint18)
	(can_traverse rover2 waypoint18 waypoint7)
	(can_traverse rover2 waypoint24 waypoint19)
	(can_traverse rover2 waypoint19 waypoint24)
	(can_traverse rover2 waypoint14 waypoint30)
	(can_traverse rover2 waypoint30 waypoint14)
	(can_traverse rover2 waypoint10 waypoint6)
	(can_traverse rover2 waypoint6 waypoint10)
	(on_board camera0 rover2)
	(calibration_target camera0 objective1)
	(supports camera0 high_res)
	(on_board camera1 rover2)
	(calibration_target camera1 objective1)
	(supports camera1 high_res)
	(on_board camera2 rover2)
	(calibration_target camera2 objective0)
	(supports camera2 colour)
	(on_board camera3 rover1)
	(calibration_target camera3 objective2)
	(supports camera3 colour)
	(supports camera3 high_res)
	(on_board camera4 rover1)
	(calibration_target camera4 objective0)
	(supports camera4 high_res)
	(on_board camera5 rover0)
	(calibration_target camera5 objective2)
	(supports camera5 colour)
	(visible_from objective0 waypoint0)
	(visible_from objective0 waypoint2)
	(visible_from objective0 waypoint5)
	(visible_from objective0 waypoint11)
	(visible_from objective0 waypoint13)
	(visible_from objective0 waypoint33)
	(visible_from objective0 waypoint34)
	(visible_from objective0 waypoint37)
	(visible_from objective1 waypoint3)
	(visible_from objective1 waypoint5)
	(visible_from objective1 waypoint12)
	(visible_from objective1 waypoint17)
	(visible_from objective1 waypoint18)
	(visible_from objective1 waypoint23)
	(visible_from objective1 waypoint27)
	(visible_from objective1 waypoint31)
	(visible_from objective1 waypoint34)
	(visible_from objective1 waypoint35)
	(visible_from objective2 waypoint1)
	(visible_from objective2 waypoint2)
	(visible_from objective2 waypoint5)
	(visible_from objective2 waypoint6)
	(visible_from objective2 waypoint7)
	(visible_from objective2 waypoint8)
	(visible_from objective2 waypoint12)
	(visible_from objective2 waypoint13)
	(visible_from objective2 waypoint15)
	(visible_from objective2 waypoint16)
	(visible_from objective2 waypoint19)
	(visible_from objective2 waypoint22)
	(visible_from objective2 waypoint32)
	(visible_from objective2 waypoint33)
	(visible_from objective2 waypoint34)
	(visible_from objective2 waypoint35)
	(visible_from objective2 waypoint38)
	(visible_from objective2 waypoint39)
	(visible_from objective3 waypoint0)
	(visible_from objective3 waypoint1)
	(visible_from objective3 waypoint2)
	(visible_from objective3 waypoint4)
	(visible_from objective3 waypoint5)
	(visible_from objective3 waypoint6)
	(visible_from objective3 waypoint8)
	(visible_from objective3 waypoint12)
	(visible_from objective3 waypoint13)
	(visible_from objective3 waypoint15)
	(visible_from objective3 waypoint16)
	(visible_from objective3 waypoint18)
	(visible_from objective3 waypoint19)
	(visible_from objective3 waypoint20)
	(visible_from objective3 waypoint24)
	(visible_from objective3 waypoint27)
	(visible_from objective3 waypoint29)
	(visible_from objective3 waypoint31)
	(visible_from objective3 waypoint32)
	(visible_from objective3 waypoint35)
	(visible_from objective3 waypoint37)
	(visible_from objective3 waypoint38)
	(visible_from objective3 waypoint39)
	(visible_from objective4 waypoint0)
	(visible_from objective4 waypoint4)
	(visible_from objective4 waypoint6)
	(visible_from objective4 waypoint8)
	(visible_from objective4 waypoint12)
	(visible_from objective4 waypoint14)
	(visible_from objective4 waypoint15)
	(visible_from objective4 waypoint18)
	(visible_from objective4 waypoint19)
	(visible_from objective4 waypoint22)
	(visible_from objective4 waypoint24)
	(visible_from objective4 waypoint33)
	(visible_from objective4 waypoint36)
	(visible_from objective4 waypoint37)
	(visible_from objective4 waypoint39)
	(visible_from objective5 waypoint1)
	(visible_from objective5 waypoint5)
	(visible_from objective5 waypoint7)
	(visible_from objective5 waypoint8)
	(visible_from objective5 waypoint9)
	(visible_from objective5 waypoint10)
	(visible_from objective5 waypoint11)
	(visible_from objective5 waypoint22)
	(visible_from objective5 waypoint24)
	(visible_from objective5 waypoint34)
	(visible_from objective5 waypoint35)
	(visible_from objective5 waypoint36)
)

(:goal (and
(communicated_soil_data waypoint12)
(communicated_soil_data waypoint3)
(communicated_soil_data waypoint15)
(communicated_soil_data waypoint33)
(communicated_soil_data waypoint19)
(communicated_rock_data waypoint13)
(communicated_rock_data waypoint26)
(communicated_rock_data waypoint2)
(communicated_rock_data waypoint16)
(communicated_rock_data waypoint22)
(communicated_rock_data waypoint28)
(communicated_rock_data waypoint3)
(communicated_rock_data waypoint19)
(communicated_rock_data waypoint29)
(communicated_rock_data waypoint5)
(communicated_image_data objective1 high_res)
(communicated_image_data objective4 high_res)
(communicated_image_data objective0 high_res)
(communicated_image_data objective3 high_res)
(communicated_image_data objective1 colour)
(communicated_image_data objective2 high_res)
(communicated_image_data objective2 colour)
(communicated_image_data objective3 colour)
(communicated_image_data objective5 colour)
	)
)
)
