(define (problem roverprob7) (:domain Rover)
(:objects
	general - Lander
	colour high_res low_res - Mode
	rover0 rover1 rover2 - Rover
	rover0store rover1store rover2store - Store
	waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 waypoint7 waypoint8 waypoint9 waypoint10 waypoint11 waypoint12 waypoint13 waypoint14 waypoint15 waypoint16 waypoint17 waypoint18 waypoint19 waypoint20 waypoint21 waypoint22 waypoint23 waypoint24 waypoint25 waypoint26 waypoint27 waypoint28 waypoint29 waypoint30 waypoint31 waypoint32 waypoint33 waypoint34 waypoint35 waypoint36 waypoint37 waypoint38 waypoint39 - Waypoint
	camera0 camera1 camera2 camera3 camera4 - Camera
	objective0 objective1 objective2 objective3 objective4 objective5 - Objective
	)
(:init
	(visible waypoint0 waypoint10)
	(visible waypoint10 waypoint0)
	(visible waypoint0 waypoint15)
	(visible waypoint15 waypoint0)
	(visible waypoint0 waypoint20)
	(visible waypoint20 waypoint0)
	(visible waypoint0 waypoint22)
	(visible waypoint22 waypoint0)
	(visible waypoint0 waypoint37)
	(visible waypoint37 waypoint0)
	(visible waypoint1 waypoint0)
	(visible waypoint0 waypoint1)
	(visible waypoint1 waypoint2)
	(visible waypoint2 waypoint1)
	(visible waypoint1 waypoint9)
	(visible waypoint9 waypoint1)
	(visible waypoint1 waypoint20)
	(visible waypoint20 waypoint1)
	(visible waypoint1 waypoint30)
	(visible waypoint30 waypoint1)
	(visible waypoint1 waypoint32)
	(visible waypoint32 waypoint1)
	(visible waypoint1 waypoint33)
	(visible waypoint33 waypoint1)
	(visible waypoint2 waypoint4)
	(visible waypoint4 waypoint2)
	(visible waypoint2 waypoint9)
	(visible waypoint9 waypoint2)
	(visible waypoint2 waypoint14)
	(visible waypoint14 waypoint2)
	(visible waypoint3 waypoint19)
	(visible waypoint19 waypoint3)
	(visible waypoint3 waypoint39)
	(visible waypoint39 waypoint3)
	(visible waypoint4 waypoint13)
	(visible waypoint13 waypoint4)
	(visible waypoint4 waypoint26)
	(visible waypoint26 waypoint4)
	(visible waypoint4 waypoint30)
	(visible waypoint30 waypoint4)
	(visible waypoint5 waypoint0)
	(visible waypoint0 waypoint5)
	(visible waypoint5 waypoint1)
	(visible waypoint1 waypoint5)
	(visible waypoint5 waypoint7)
	(visible waypoint7 waypoint5)
	(visible waypoint5 waypoint8)
	(visible waypoint8 waypoint5)
	(visible waypoint6 waypoint17)
	(visible waypoint17 waypoint6)
	(visible waypoint6 waypoint28)
	(visible waypoint28 waypoint6)
	(visible waypoint6 waypoint30)
	(visible waypoint30 waypoint6)
	(visible waypoint6 waypoint38)
	(visible waypoint38 waypoint6)
	(visible waypoint7 waypoint15)
	(visible waypoint15 waypoint7)
	(visible waypoint7 waypoint19)
	(visible waypoint19 waypoint7)
	(visible waypoint7 waypoint20)
	(visible waypoint20 waypoint7)
	(visible waypoint8 waypoint3)
	(visible waypoint3 waypoint8)
	(visible waypoint8 waypoint27)
	(visible waypoint27 waypoint8)
	(visible waypoint8 waypoint31)
	(visible waypoint31 waypoint8)
	(visible waypoint8 waypoint38)
	(visible waypoint38 waypoint8)
	(visible waypoint9 waypoint14)
	(visible waypoint14 waypoint9)
	(visible waypoint9 waypoint15)
	(visible waypoint15 waypoint9)
	(visible waypoint9 waypoint18)
	(visible waypoint18 waypoint9)
	(visible waypoint9 waypoint23)
	(visible waypoint23 waypoint9)
	(visible waypoint9 waypoint36)
	(visible waypoint36 waypoint9)
	(visible waypoint10 waypoint2)
	(visible waypoint2 waypoint10)
	(visible waypoint10 waypoint14)
	(visible waypoint14 waypoint10)
	(visible waypoint10 waypoint19)
	(visible waypoint19 waypoint10)
	(visible waypoint10 waypoint20)
	(visible waypoint20 waypoint10)
	(visible waypoint10 waypoint36)
	(visible waypoint36 waypoint10)
	(visible waypoint11 waypoint3)
	(visible waypoint3 waypoint11)
	(visible waypoint11 waypoint20)
	(visible waypoint20 waypoint11)
	(visible waypoint11 waypoint26)
	(visible waypoint26 waypoint11)
	(visible waypoint11 waypoint29)
	(visible waypoint29 waypoint11)
	(visible waypoint11 waypoint39)
	(visible waypoint39 waypoint11)
	(visible waypoint12 waypoint0)
	(visible waypoint0 waypoint12)
	(visible waypoint12 waypoint11)
	(visible waypoint11 waypoint12)
	(visible waypoint12 waypoint16)
	(visible waypoint16 waypoint12)
	(visible waypoint12 waypoint34)
	(visible waypoint34 waypoint12)
	(visible waypoint13 waypoint9)
	(visible waypoint9 waypoint13)
	(visible waypoint13 waypoint12)
	(visible waypoint12 waypoint13)
	(visible waypoint13 waypoint20)
	(visible waypoint20 waypoint13)
	(visible waypoint13 waypoint25)
	(visible waypoint25 waypoint13)
	(visible waypoint13 waypoint39)
	(visible waypoint39 waypoint13)
	(visible waypoint14 waypoint6)
	(visible waypoint6 waypoint14)
	(visible waypoint14 waypoint12)
	(visible waypoint12 waypoint14)
	(visible waypoint14 waypoint17)
	(visible waypoint17 waypoint14)
	(visible waypoint14 waypoint19)
	(visible waypoint19 waypoint14)
	(visible waypoint14 waypoint24)
	(visible waypoint24 waypoint14)
	(visible waypoint14 waypoint30)
	(visible waypoint30 waypoint14)
	(visible waypoint14 waypoint39)
	(visible waypoint39 waypoint14)
	(visible waypoint15 waypoint35)
	(visible waypoint35 waypoint15)
	(visible waypoint15 waypoint36)
	(visible waypoint36 waypoint15)
	(visible waypoint16 waypoint14)
	(visible waypoint14 waypoint16)
	(visible waypoint16 waypoint17)
	(visible waypoint17 waypoint16)
	(visible waypoint16 waypoint22)
	(visible waypoint22 waypoint16)
	(visible waypoint16 waypoint32)
	(visible waypoint32 waypoint16)
	(visible waypoint17 waypoint0)
	(visible waypoint0 waypoint17)
	(visible waypoint17 waypoint2)
	(visible waypoint2 waypoint17)
	(visible waypoint17 waypoint12)
	(visible waypoint12 waypoint17)
	(visible waypoint17 waypoint13)
	(visible waypoint13 waypoint17)
	(visible waypoint17 waypoint25)
	(visible waypoint25 waypoint17)
	(visible waypoint17 waypoint34)
	(visible waypoint34 waypoint17)
	(visible waypoint18 waypoint1)
	(visible waypoint1 waypoint18)
	(visible waypoint18 waypoint5)
	(visible waypoint5 waypoint18)
	(visible waypoint18 waypoint17)
	(visible waypoint17 waypoint18)
	(visible waypoint18 waypoint24)
	(visible waypoint24 waypoint18)
	(visible waypoint18 waypoint32)
	(visible waypoint32 waypoint18)
	(visible waypoint18 waypoint33)
	(visible waypoint33 waypoint18)
	(visible waypoint19 waypoint2)
	(visible waypoint2 waypoint19)
	(visible waypoint19 waypoint16)
	(visible waypoint16 waypoint19)
	(visible waypoint19 waypoint34)
	(visible waypoint34 waypoint19)
	(visible waypoint20 waypoint5)
	(visible waypoint5 waypoint20)
	(visible waypoint20 waypoint16)
	(visible waypoint16 waypoint20)
	(visible waypoint20 waypoint32)
	(visible waypoint32 waypoint20)
	(visible waypoint21 waypoint3)
	(visible waypoint3 waypoint21)
	(visible waypoint21 waypoint13)
	(visible waypoint13 waypoint21)
	(visible waypoint22 waypoint1)
	(visible waypoint1 waypoint22)
	(visible waypoint22 waypoint6)
	(visible waypoint6 waypoint22)
	(visible waypoint22 waypoint7)
	(visible waypoint7 waypoint22)
	(visible waypoint22 waypoint35)
	(visible waypoint35 waypoint22)
	(visible waypoint22 waypoint37)
	(visible waypoint37 waypoint22)
	(visible waypoint23 waypoint5)
	(visible waypoint5 waypoint23)
	(visible waypoint23 waypoint8)
	(visible waypoint8 waypoint23)
	(visible waypoint23 waypoint16)
	(visible waypoint16 waypoint23)
	(visible waypoint23 waypoint25)
	(visible waypoint25 waypoint23)
	(visible waypoint23 waypoint29)
	(visible waypoint29 waypoint23)
	(visible waypoint24 waypoint2)
	(visible waypoint2 waypoint24)
	(visible waypoint24 waypoint3)
	(visible waypoint3 waypoint24)
	(visible waypoint24 waypoint13)
	(visible waypoint13 waypoint24)
	(visible waypoint24 waypoint19)
	(visible waypoint19 waypoint24)
	(visible waypoint24 waypoint32)
	(visible waypoint32 waypoint24)
	(visible waypoint24 waypoint37)
	(visible waypoint37 waypoint24)
	(visible waypoint25 waypoint3)
	(visible waypoint3 waypoint25)
	(visible waypoint25 waypoint10)
	(visible waypoint10 waypoint25)
	(visible waypoint25 waypoint28)
	(visible waypoint28 waypoint25)
	(visible waypoint25 waypoint35)
	(visible waypoint35 waypoint25)
	(visible waypoint26 waypoint0)
	(visible waypoint0 waypoint26)
	(visible waypoint26 waypoint3)
	(visible waypoint3 waypoint26)
	(visible waypoint26 waypoint7)
	(visible waypoint7 waypoint26)
	(visible waypoint26 waypoint20)
	(visible waypoint20 waypoint26)
	(visible waypoint26 waypoint31)
	(visible waypoint31 waypoint26)
	(visible waypoint26 waypoint32)
	(visible waypoint32 waypoint26)
	(visible waypoint27 waypoint9)
	(visible waypoint9 waypoint27)
	(visible waypoint27 waypoint23)
	(visible waypoint23 waypoint27)
	(visible waypoint28 waypoint2)
	(visible waypoint2 waypoint28)
	(visible waypoint28 waypoint10)
	(visible waypoint10 waypoint28)
	(visible waypoint28 waypoint17)
	(visible waypoint17 waypoint28)
	(visible waypoint28 waypoint21)
	(visible waypoint21 waypoint28)
	(visible waypoint28 waypoint36)
	(visible waypoint36 waypoint28)
	(visible waypoint29 waypoint2)
	(visible waypoint2 waypoint29)
	(visible waypoint29 waypoint36)
	(visible waypoint36 waypoint29)
	(visible waypoint29 waypoint38)
	(visible waypoint38 waypoint29)
	(visible waypoint30 waypoint8)
	(visible waypoint8 waypoint30)
	(visible waypoint30 waypoint9)
	(visible waypoint9 waypoint30)
	(visible waypoint30 waypoint16)
	(visible waypoint16 waypoint30)
	(visible waypoint30 waypoint28)
	(visible waypoint28 waypoint30)
	(visible waypoint30 waypoint32)
	(visible waypoint32 waypoint30)
	(visible waypoint30 waypoint39)
	(visible waypoint39 waypoint30)
	(visible waypoint31 waypoint2)
	(visible waypoint2 waypoint31)
	(visible waypoint31 waypoint3)
	(visible waypoint3 waypoint31)
	(visible waypoint31 waypoint20)
	(visible waypoint20 waypoint31)
	(visible waypoint32 waypoint13)
	(visible waypoint13 waypoint32)
	(visible waypoint32 waypoint35)
	(visible waypoint35 waypoint32)
	(visible waypoint32 waypoint37)
	(visible waypoint37 waypoint32)
	(visible waypoint33 waypoint9)
	(visible waypoint9 waypoint33)
	(visible waypoint33 waypoint11)
	(visible waypoint11 waypoint33)
	(visible waypoint33 waypoint22)
	(visible waypoint22 waypoint33)
	(visible waypoint33 waypoint26)
	(visible waypoint26 waypoint33)
	(visible waypoint33 waypoint35)
	(visible waypoint35 waypoint33)
	(visible waypoint33 waypoint37)
	(visible waypoint37 waypoint33)
	(visible waypoint34 waypoint4)
	(visible waypoint4 waypoint34)
	(visible waypoint34 waypoint20)
	(visible waypoint20 waypoint34)
	(visible waypoint34 waypoint23)
	(visible waypoint23 waypoint34)
	(visible waypoint34 waypoint27)
	(visible waypoint27 waypoint34)
	(visible waypoint35 waypoint6)
	(visible waypoint6 waypoint35)
	(visible waypoint35 waypoint31)
	(visible waypoint31 waypoint35)
	(visible waypoint36 waypoint24)
	(visible waypoint24 waypoint36)
	(visible waypoint36 waypoint30)
	(visible waypoint30 waypoint36)
	(visible waypoint36 waypoint35)
	(visible waypoint35 waypoint36)
	(visible waypoint37 waypoint1)
	(visible waypoint1 waypoint37)
	(visible waypoint37 waypoint23)
	(visible waypoint23 waypoint37)
	(visible waypoint37 waypoint30)
	(visible waypoint30 waypoint37)
	(visible waypoint38 waypoint1)
	(visible waypoint1 waypoint38)
	(visible waypoint38 waypoint16)
	(visible waypoint16 waypoint38)
	(visible waypoint38 waypoint17)
	(visible waypoint17 waypoint38)
	(visible waypoint38 waypoint24)
	(visible waypoint24 waypoint38)
	(visible waypoint39 waypoint1)
	(visible waypoint1 waypoint39)
	(visible waypoint39 waypoint8)
	(visible waypoint8 waypoint39)
	(visible waypoint39 waypoint22)
	(visible waypoint22 waypoint39)
	(visible waypoint39 waypoint35)
	(visible waypoint35 waypoint39)
	(at_soil_sample waypoint0)
	(at_rock_sample waypoint0)
	(at_rock_sample waypoint2)
	(at_soil_sample waypoint3)
	(at_rock_sample waypoint3)
	(at_rock_sample waypoint4)
	(at_soil_sample waypoint5)
	(at_soil_sample waypoint6)
	(at_soil_sample waypoint7)
	(at_soil_sample waypoint8)
	(at_soil_sample waypoint9)
	(at_rock_sample waypoint9)
	(at_soil_sample waypoint10)
	(at_soil_sample waypoint11)
	(at_rock_sample waypoint11)
	(at_soil_sample waypoint12)
	(at_soil_sample waypoint13)
	(at_rock_sample waypoint13)
	(at_soil_sample waypoint14)
	(at_rock_sample waypoint14)
	(at_rock_sample waypoint15)
	(at_soil_sample waypoint17)
	(at_rock_sample waypoint17)
	(at_rock_sample waypoint18)
	(at_soil_sample waypoint19)
	(at_soil_sample waypoint20)
	(at_rock_sample waypoint20)
	(at_rock_sample waypoint21)
	(at_rock_sample waypoint22)
	(at_rock_sample waypoint23)
	(at_soil_sample waypoint24)
	(at_rock_sample waypoint24)
	(at_rock_sample waypoint25)
	(at_soil_sample waypoint26)
	(at_rock_sample waypoint27)
	(at_rock_sample waypoint29)
	(at_rock_sample waypoint30)
	(at_rock_sample waypoint31)
	(at_soil_sample waypoint33)
	(at_soil_sample waypoint35)
	(at_rock_sample waypoint35)
	(at_soil_sample waypoint36)
	(at_rock_sample waypoint38)
	(at_rock_sample waypoint39)
	(at_lander general waypoint10)
	(channel_free general)
	(at rover0 waypoint15)
	(available rover0)
	(store_of rover0store rover0)
	(empty rover0store)
	(equipped_for_rock_analysis rover0)
	(equipped_for_imaging rover0)
	(can_traverse rover0 waypoint15 waypoint0)
	(can_traverse rover0 waypoint0 waypoint15)
	(can_traverse rover0 waypoint15 waypoint7)
	(can_traverse rover0 waypoint7 waypoint15)
	(can_traverse rover0 waypoint15 waypoint9)
	(can_traverse rover0 waypoint9 waypoint15)
	(can_traverse rover0 waypoint15 waypoint35)
	(can_traverse rover0 waypoint35 waypoint15)
	(can_traverse rover0 waypoint0 waypoint10)
	(can_traverse rover0 waypoint10 waypoint0)
	(can_traverse rover0 waypoint0 waypoint12)
	(can_traverse rover0 waypoint12 waypoint0)
	(can_traverse rover0 waypoint0 waypoint17)
	(can_traverse rover0 waypoint17 waypoint0)
	(can_traverse rover0 waypoint0 waypoint26)
	(can_traverse rover0 waypoint26 waypoint0)
	(can_traverse rover0 waypoint0 waypoint37)
	(can_traverse rover0 waypoint37 waypoint0)
	(can_traverse rover0 waypoint7 waypoint5)
	(can_traverse rover0 waypoint5 waypoint7)
	(can_traverse rover0 waypoint7 waypoint20)
	(can_traverse rover0 waypoint20 waypoint7)
	(can_traverse rover0 waypoint7 waypoint22)
	(can_traverse rover0 waypoint22 waypoint7)
	(can_traverse rover0 waypoint9 waypoint1)
	(can_traverse rover0 waypoint1 waypoint9)
	(can_traverse rover0 waypoint9 waypoint2)
	(can_traverse rover0 waypoint2 waypoint9)
	(can_traverse rover0 waypoint9 waypoint13)
	(can_traverse rover0 waypoint13 waypoint9)
	(can_traverse rover0 waypoint9 waypoint14)
	(can_traverse rover0 waypoint14 waypoint9)
	(can_traverse rover0 waypoint9 waypoint18)
	(can_traverse rover0 waypoint18 waypoint9)
	(can_traverse rover0 waypoint9 waypoint23)
	(can_traverse rover0 waypoint23 waypoint9)
	(can_traverse rover0 waypoint9 waypoint27)
	(can_traverse rover0 waypoint27 waypoint9)
	(can_traverse rover0 waypoint35 waypoint6)
	(can_traverse rover0 waypoint6 waypoint35)
	(can_traverse rover0 waypoint35 waypoint31)
	(can_traverse rover0 waypoint31 waypoint35)
	(can_traverse rover0 waypoint35 waypoint36)
	(can_traverse rover0 waypoint36 waypoint35)
	(can_traverse rover0 waypoint35 waypoint39)
	(can_traverse rover0 waypoint39 waypoint35)
	(can_traverse rover0 waypoint10 waypoint19)
	(can_traverse rover0 waypoint19 waypoint10)
	(can_traverse rover0 waypoint10 waypoint25)
	(can_traverse rover0 waypoint25 waypoint10)
	(can_traverse rover0 waypoint10 waypoint28)
	(can_traverse rover0 waypoint28 waypoint10)
	(can_traverse rover0 waypoint12 waypoint11)
	(can_traverse rover0 waypoint11 waypoint12)
	(can_traverse rover0 waypoint12 waypoint16)
	(can_traverse rover0 waypoint16 waypoint12)
	(can_traverse rover0 waypoint12 waypoint34)
	(can_traverse rover0 waypoint34 waypoint12)
	(can_traverse rover0 waypoint17 waypoint38)
	(can_traverse rover0 waypoint38 waypoint17)
	(can_traverse rover0 waypoint26 waypoint3)
	(can_traverse rover0 waypoint3 waypoint26)
	(can_traverse rover0 waypoint26 waypoint4)
	(can_traverse rover0 waypoint4 waypoint26)
	(can_traverse rover0 waypoint37 waypoint24)
	(can_traverse rover0 waypoint24 waypoint37)
	(can_traverse rover0 waypoint37 waypoint30)
	(can_traverse rover0 waypoint30 waypoint37)
	(can_traverse rover0 waypoint20 waypoint32)
	(can_traverse rover0 waypoint32 waypoint20)
	(can_traverse rover0 waypoint22 waypoint33)
	(can_traverse rover0 waypoint33 waypoint22)
	(can_traverse rover0 waypoint2 waypoint29)
	(can_traverse rover0 waypoint29 waypoint2)
	(can_traverse rover0 waypoint13 waypoint21)
	(can_traverse rover0 waypoint21 waypoint13)
	(can_traverse rover0 waypoint23 waypoint8)
	(can_traverse rover0 waypoint8 waypoint23)
	(at rover1 waypoint32)
	(available rover1)
	(store_of rover1store rover1)
	(empty rover1store)
	(equipped_for_soil_analysis rover1)
	(equipped_for_rock_analysis rover1)
	(equipped_for_imaging rover1)
	(can_traverse rover1 waypoint32 waypoint1)
	(can_traverse rover1 waypoint1 waypoint32)
	(can_traverse rover1 waypoint32 waypoint13)
	(can_traverse rover1 waypoint13 waypoint32)
	(can_traverse rover1 waypoint32 waypoint16)
	(can_traverse rover1 waypoint16 waypoint32)
	(can_traverse rover1 waypoint32 waypoint18)
	(can_traverse rover1 waypoint18 waypoint32)
	(can_traverse rover1 waypoint32 waypoint20)
	(can_traverse rover1 waypoint20 waypoint32)
	(can_traverse rover1 waypoint32 waypoint24)
	(can_traverse rover1 waypoint24 waypoint32)
	(can_traverse rover1 waypoint32 waypoint26)
	(can_traverse rover1 waypoint26 waypoint32)
	(can_traverse rover1 waypoint32 waypoint30)
	(can_traverse rover1 waypoint30 waypoint32)
	(can_traverse rover1 waypoint32 waypoint35)
	(can_traverse rover1 waypoint35 waypoint32)
	(can_traverse rover1 waypoint32 waypoint37)
	(can_traverse rover1 waypoint37 waypoint32)
	(can_traverse rover1 waypoint1 waypoint2)
	(can_traverse rover1 waypoint2 waypoint1)
	(can_traverse rover1 waypoint1 waypoint9)
	(can_traverse rover1 waypoint9 waypoint1)
	(can_traverse rover1 waypoint1 waypoint33)
	(can_traverse rover1 waypoint33 waypoint1)
	(can_traverse rover1 waypoint1 waypoint39)
	(can_traverse rover1 waypoint39 waypoint1)
	(can_traverse rover1 waypoint13 waypoint12)
	(can_traverse rover1 waypoint12 waypoint13)
	(can_traverse rover1 waypoint13 waypoint17)
	(can_traverse rover1 waypoint17 waypoint13)
	(can_traverse rover1 waypoint13 waypoint25)
	(can_traverse rover1 waypoint25 waypoint13)
	(can_traverse rover1 waypoint16 waypoint14)
	(can_traverse rover1 waypoint14 waypoint16)
	(can_traverse rover1 waypoint16 waypoint19)
	(can_traverse rover1 waypoint19 waypoint16)
	(can_traverse rover1 waypoint16 waypoint23)
	(can_traverse rover1 waypoint23 waypoint16)
	(can_traverse rover1 waypoint16 waypoint38)
	(can_traverse rover1 waypoint38 waypoint16)
	(can_traverse rover1 waypoint20 waypoint0)
	(can_traverse rover1 waypoint0 waypoint20)
	(can_traverse rover1 waypoint20 waypoint10)
	(can_traverse rover1 waypoint10 waypoint20)
	(can_traverse rover1 waypoint20 waypoint11)
	(can_traverse rover1 waypoint11 waypoint20)
	(can_traverse rover1 waypoint20 waypoint31)
	(can_traverse rover1 waypoint31 waypoint20)
	(can_traverse rover1 waypoint24 waypoint3)
	(can_traverse rover1 waypoint3 waypoint24)
	(can_traverse rover1 waypoint26 waypoint4)
	(can_traverse rover1 waypoint4 waypoint26)
	(can_traverse rover1 waypoint26 waypoint7)
	(can_traverse rover1 waypoint7 waypoint26)
	(can_traverse rover1 waypoint30 waypoint8)
	(can_traverse rover1 waypoint8 waypoint30)
	(can_traverse rover1 waypoint30 waypoint28)
	(can_traverse rover1 waypoint28 waypoint30)
	(can_traverse rover1 waypoint30 waypoint36)
	(can_traverse rover1 waypoint36 waypoint30)
	(can_traverse rover1 waypoint35 waypoint6)
	(can_traverse rover1 waypoint6 waypoint35)
	(can_traverse rover1 waypoint35 waypoint15)
	(can_traverse rover1 waypoint15 waypoint35)
	(can_traverse rover1 waypoint35 waypoint22)
	(can_traverse rover1 waypoint22 waypoint35)
	(can_traverse rover1 waypoint2 waypoint29)
	(can_traverse rover1 waypoint29 waypoint2)
	(can_traverse rover1 waypoint9 waypoint27)
	(can_traverse rover1 waypoint27 waypoint9)
	(can_traverse rover1 waypoint19 waypoint34)
	(can_traverse rover1 waypoint34 waypoint19)
	(can_traverse rover1 waypoint0 waypoint5)
	(can_traverse rover1 waypoint5 waypoint0)
	(can_traverse rover1 waypoint3 waypoint21)
	(can_traverse rover1 waypoint21 waypoint3)
	(at rover2 waypoint37)
	(available rover2)
	(store_of rover2store rover2)
	(empty rover2store)
	(equipped_for_soil_analysis rover2)
	(equipped_for_rock_analysis rover2)
	(equipped_for_imaging rover2)
	(can_traverse rover2 waypoint37 waypoint0)
	(can_traverse rover2 waypoint0 waypoint37)
	(can_traverse rover2 waypoint37 waypoint1)
	(can_traverse rover2 waypoint1 waypoint37)
	(can_traverse rover2 waypoint37 waypoint22)
	(can_traverse rover2 waypoint22 waypoint37)
	(can_traverse rover2 waypoint37 waypoint23)
	(can_traverse rover2 waypoint23 waypoint37)
	(can_traverse rover2 waypoint37 waypoint24)
	(can_traverse rover2 waypoint24 waypoint37)
	(can_traverse rover2 waypoint37 waypoint30)
	(can_traverse rover2 waypoint30 waypoint37)
	(can_traverse rover2 waypoint37 waypoint32)
	(can_traverse rover2 waypoint32 waypoint37)
	(can_traverse rover2 waypoint37 waypoint33)
	(can_traverse rover2 waypoint33 waypoint37)
	(can_traverse rover2 waypoint0 waypoint10)
	(can_traverse rover2 waypoint10 waypoint0)
	(can_traverse rover2 waypoint0 waypoint12)
	(can_traverse rover2 waypoint12 waypoint0)
	(can_traverse rover2 waypoint0 waypoint15)
	(can_traverse rover2 waypoint15 waypoint0)
	(can_traverse rover2 waypoint0 waypoint17)
	(can_traverse rover2 waypoint17 waypoint0)
	(can_traverse rover2 waypoint0 waypoint20)
	(can_traverse rover2 waypoint20 waypoint0)
	(can_traverse rover2 waypoint0 waypoint26)
	(can_traverse rover2 waypoint26 waypoint0)
	(can_traverse rover2 waypoint1 waypoint2)
	(can_traverse rover2 waypoint2 waypoint1)
	(can_traverse rover2 waypoint1 waypoint18)
	(can_traverse rover2 waypoint18 waypoint1)
	(can_traverse rover2 waypoint1 waypoint38)
	(can_traverse rover2 waypoint38 waypoint1)
	(can_traverse rover2 waypoint1 waypoint39)
	(can_traverse rover2 waypoint39 waypoint1)
	(can_traverse rover2 waypoint22 waypoint6)
	(can_traverse rover2 waypoint6 waypoint22)
	(can_traverse rover2 waypoint22 waypoint7)
	(can_traverse rover2 waypoint7 waypoint22)
	(can_traverse rover2 waypoint22 waypoint16)
	(can_traverse rover2 waypoint16 waypoint22)
	(can_traverse rover2 waypoint22 waypoint35)
	(can_traverse rover2 waypoint35 waypoint22)
	(can_traverse rover2 waypoint23 waypoint8)
	(can_traverse rover2 waypoint8 waypoint23)
	(can_traverse rover2 waypoint23 waypoint9)
	(can_traverse rover2 waypoint9 waypoint23)
	(can_traverse rover2 waypoint23 waypoint25)
	(can_traverse rover2 waypoint25 waypoint23)
	(can_traverse rover2 waypoint23 waypoint34)
	(can_traverse rover2 waypoint34 waypoint23)
	(can_traverse rover2 waypoint24 waypoint3)
	(can_traverse rover2 waypoint3 waypoint24)
	(can_traverse rover2 waypoint24 waypoint13)
	(can_traverse rover2 waypoint13 waypoint24)
	(can_traverse rover2 waypoint24 waypoint14)
	(can_traverse rover2 waypoint14 waypoint24)
	(can_traverse rover2 waypoint24 waypoint19)
	(can_traverse rover2 waypoint19 waypoint24)
	(can_traverse rover2 waypoint24 waypoint36)
	(can_traverse rover2 waypoint36 waypoint24)
	(can_traverse rover2 waypoint30 waypoint4)
	(can_traverse rover2 waypoint4 waypoint30)
	(can_traverse rover2 waypoint30 waypoint28)
	(can_traverse rover2 waypoint28 waypoint30)
	(can_traverse rover2 waypoint33 waypoint11)
	(can_traverse rover2 waypoint11 waypoint33)
	(can_traverse rover2 waypoint20 waypoint5)
	(can_traverse rover2 waypoint5 waypoint20)
	(can_traverse rover2 waypoint20 waypoint31)
	(can_traverse rover2 waypoint31 waypoint20)
	(can_traverse rover2 waypoint38 waypoint29)
	(can_traverse rover2 waypoint29 waypoint38)
	(can_traverse rover2 waypoint8 waypoint27)
	(can_traverse rover2 waypoint27 waypoint8)
	(can_traverse rover2 waypoint3 waypoint21)
	(can_traverse rover2 waypoint21 waypoint3)
	(on_board camera0 rover1)
	(calibration_target camera0 objective0)
	(supports camera0 high_res)
	(on_board camera1 rover0)
	(calibration_target camera1 objective2)
	(supports camera1 high_res)
	(on_board camera2 rover2)
	(calibration_target camera2 objective5)
	(supports camera2 high_res)
	(supports camera2 low_res)
	(on_board camera3 rover0)
	(calibration_target camera3 objective2)
	(supports camera3 colour)
	(supports camera3 high_res)
	(supports camera3 low_res)
	(on_board camera4 rover2)
	(calibration_target camera4 objective5)
	(supports camera4 high_res)
	(supports camera4 low_res)
	(visible_from objective0 waypoint1)
	(visible_from objective0 waypoint2)
	(visible_from objective0 waypoint3)
	(visible_from objective0 waypoint5)
	(visible_from objective0 waypoint7)
	(visible_from objective0 waypoint8)
	(visible_from objective0 waypoint9)
	(visible_from objective0 waypoint10)
	(visible_from objective0 waypoint11)
	(visible_from objective0 waypoint13)
	(visible_from objective0 waypoint15)
	(visible_from objective0 waypoint16)
	(visible_from objective0 waypoint18)
	(visible_from objective0 waypoint19)
	(visible_from objective0 waypoint20)
	(visible_from objective0 waypoint21)
	(visible_from objective0 waypoint22)
	(visible_from objective0 waypoint25)
	(visible_from objective0 waypoint26)
	(visible_from objective0 waypoint29)
	(visible_from objective0 waypoint31)
	(visible_from objective0 waypoint32)
	(visible_from objective0 waypoint33)
	(visible_from objective0 waypoint34)
	(visible_from objective0 waypoint35)
	(visible_from objective0 waypoint36)
	(visible_from objective0 waypoint37)
	(visible_from objective1 waypoint2)
	(visible_from objective1 waypoint4)
	(visible_from objective1 waypoint5)
	(visible_from objective1 waypoint7)
	(visible_from objective1 waypoint9)
	(visible_from objective1 waypoint10)
	(visible_from objective1 waypoint12)
	(visible_from objective1 waypoint15)
	(visible_from objective1 waypoint17)
	(visible_from objective1 waypoint18)
	(visible_from objective1 waypoint20)
	(visible_from objective1 waypoint22)
	(visible_from objective1 waypoint23)
	(visible_from objective1 waypoint28)
	(visible_from objective1 waypoint29)
	(visible_from objective1 waypoint30)
	(visible_from objective1 waypoint31)
	(visible_from objective1 waypoint34)
	(visible_from objective1 waypoint36)
	(visible_from objective1 waypoint38)
	(visible_from objective1 waypoint39)
	(visible_from objective2 waypoint0)
	(visible_from objective2 waypoint3)
	(visible_from objective2 waypoint6)
	(visible_from objective2 waypoint9)
	(visible_from objective2 waypoint11)
	(visible_from objective2 waypoint14)
	(visible_from objective2 waypoint16)
	(visible_from objective2 waypoint20)
	(visible_from objective2 waypoint22)
	(visible_from objective2 waypoint24)
	(visible_from objective2 waypoint25)
	(visible_from objective2 waypoint27)
	(visible_from objective2 waypoint28)
	(visible_from objective2 waypoint32)
	(visible_from objective2 waypoint35)
	(visible_from objective2 waypoint36)
	(visible_from objective2 waypoint37)
	(visible_from objective3 waypoint0)
	(visible_from objective3 waypoint2)
	(visible_from objective3 waypoint6)
	(visible_from objective3 waypoint9)
	(visible_from objective3 waypoint10)
	(visible_from objective3 waypoint11)
	(visible_from objective3 waypoint13)
	(visible_from objective3 waypoint14)
	(visible_from objective3 waypoint15)
	(visible_from objective3 waypoint17)
	(visible_from objective3 waypoint22)
	(visible_from objective3 waypoint23)
	(visible_from objective3 waypoint25)
	(visible_from objective3 waypoint29)
	(visible_from objective3 waypoint34)
	(visible_from objective3 waypoint38)
	(visible_from objective4 waypoint0)
	(visible_from objective4 waypoint2)
	(visible_from objective4 waypoint3)
	(visible_from objective4 waypoint4)
	(visible_from objective4 waypoint8)
	(visible_from objective4 waypoint11)
	(visible_from objective4 waypoint12)
	(visible_from objective4 waypoint15)
	(visible_from objective4 waypoint17)
	(visible_from objective4 waypoint18)
	(visible_from objective4 waypoint19)
	(visible_from objective4 waypoint20)
	(visible_from objective4 waypoint21)
	(visible_from objective4 waypoint23)
	(visible_from objective4 waypoint26)
	(visible_from objective4 waypoint27)
	(visible_from objective4 waypoint29)
	(visible_from objective4 waypoint30)
	(visible_from objective4 waypoint31)
	(visible_from objective4 waypoint33)
	(visible_from objective4 waypoint35)
	(visible_from objective4 waypoint39)
	(visible_from objective5 waypoint0)
	(visible_from objective5 waypoint1)
	(visible_from objective5 waypoint5)
	(visible_from objective5 waypoint7)
	(visible_from objective5 waypoint9)
	(visible_from objective5 waypoint13)
	(visible_from objective5 waypoint14)
	(visible_from objective5 waypoint19)
	(visible_from objective5 waypoint21)
	(visible_from objective5 waypoint22)
	(visible_from objective5 waypoint25)
	(visible_from objective5 waypoint26)
	(visible_from objective5 waypoint29)
	(visible_from objective5 waypoint30)
	(visible_from objective5 waypoint32)
	(visible_from objective5 waypoint34)
	(visible_from objective5 waypoint37)
	(visible_from objective5 waypoint38)
	(visible_from objective5 waypoint39)
)

(:goal (and
(communicated_soil_data waypoint7)
(communicated_soil_data waypoint14)
(communicated_soil_data waypoint3)
(communicated_soil_data waypoint11)
(communicated_soil_data waypoint12)
(communicated_soil_data waypoint20)
(communicated_soil_data waypoint8)
(communicated_soil_data waypoint33)
(communicated_soil_data waypoint26)
(communicated_soil_data waypoint5)
(communicated_soil_data waypoint9)
(communicated_soil_data waypoint19)
(communicated_soil_data waypoint6)
(communicated_soil_data waypoint13)
(communicated_rock_data waypoint15)
(communicated_rock_data waypoint38)
(communicated_rock_data waypoint29)
(communicated_rock_data waypoint4)
(communicated_rock_data waypoint0)
(communicated_rock_data waypoint25)
(communicated_rock_data waypoint35)
(communicated_image_data objective0 high_res)
(communicated_image_data objective4 high_res)
(communicated_image_data objective1 low_res)
(communicated_image_data objective0 low_res)
(communicated_image_data objective2 low_res)
(communicated_image_data objective3 high_res)
	)
)
)
