(define (problem roverprob6) (:domain Rover)
(:objects
	general - Lander
	colour high_res low_res - Mode
	rover0 rover1 rover2 rover3 - Rover
	rover0store rover1store rover2store rover3store - Store
	waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 waypoint7 waypoint8 waypoint9 waypoint10 waypoint11 waypoint12 waypoint13 waypoint14 waypoint15 waypoint16 waypoint17 waypoint18 waypoint19 waypoint20 waypoint21 waypoint22 waypoint23 waypoint24 waypoint25 waypoint26 waypoint27 waypoint28 waypoint29 waypoint30 waypoint31 waypoint32 waypoint33 waypoint34 waypoint35 waypoint36 waypoint37 waypoint38 waypoint39 waypoint40 waypoint41 waypoint42 waypoint43 waypoint44 waypoint45 waypoint46 waypoint47 waypoint48 waypoint49 waypoint50 waypoint51 waypoint52 waypoint53 waypoint54 waypoint55 waypoint56 waypoint57 waypoint58 waypoint59 - Waypoint
	camera0 camera1 camera2 camera3 camera4 camera5 camera6 - Camera
	objective0 objective1 objective2 objective3 objective4 objective5 objective6 objective7 - Objective
	)
(:init
	(visible waypoint0 waypoint28)
	(visible waypoint28 waypoint0)
	(visible waypoint0 waypoint39)
	(visible waypoint39 waypoint0)
	(visible waypoint0 waypoint44)
	(visible waypoint44 waypoint0)
	(visible waypoint0 waypoint46)
	(visible waypoint46 waypoint0)
	(visible waypoint0 waypoint52)
	(visible waypoint52 waypoint0)
	(visible waypoint1 waypoint22)
	(visible waypoint22 waypoint1)
	(visible waypoint1 waypoint32)
	(visible waypoint32 waypoint1)
	(visible waypoint1 waypoint38)
	(visible waypoint38 waypoint1)
	(visible waypoint1 waypoint44)
	(visible waypoint44 waypoint1)
	(visible waypoint2 waypoint6)
	(visible waypoint6 waypoint2)
	(visible waypoint2 waypoint34)
	(visible waypoint34 waypoint2)
	(visible waypoint2 waypoint41)
	(visible waypoint41 waypoint2)
	(visible waypoint2 waypoint44)
	(visible waypoint44 waypoint2)
	(visible waypoint3 waypoint6)
	(visible waypoint6 waypoint3)
	(visible waypoint3 waypoint19)
	(visible waypoint19 waypoint3)
	(visible waypoint3 waypoint38)
	(visible waypoint38 waypoint3)
	(visible waypoint4 waypoint13)
	(visible waypoint13 waypoint4)
	(visible waypoint4 waypoint41)
	(visible waypoint41 waypoint4)
	(visible waypoint4 waypoint56)
	(visible waypoint56 waypoint4)
	(visible waypoint4 waypoint57)
	(visible waypoint57 waypoint4)
	(visible waypoint5 waypoint30)
	(visible waypoint30 waypoint5)
	(visible waypoint5 waypoint31)
	(visible waypoint31 waypoint5)
	(visible waypoint5 waypoint48)
	(visible waypoint48 waypoint5)
	(visible waypoint5 waypoint57)
	(visible waypoint57 waypoint5)
	(visible waypoint6 waypoint12)
	(visible waypoint12 waypoint6)
	(visible waypoint6 waypoint17)
	(visible waypoint17 waypoint6)
	(visible waypoint6 waypoint55)
	(visible waypoint55 waypoint6)
	(visible waypoint6 waypoint56)
	(visible waypoint56 waypoint6)
	(visible waypoint6 waypoint57)
	(visible waypoint57 waypoint6)
	(visible waypoint7 waypoint3)
	(visible waypoint3 waypoint7)
	(visible waypoint7 waypoint11)
	(visible waypoint11 waypoint7)
	(visible waypoint7 waypoint20)
	(visible waypoint20 waypoint7)
	(visible waypoint7 waypoint41)
	(visible waypoint41 waypoint7)
	(visible waypoint7 waypoint44)
	(visible waypoint44 waypoint7)
	(visible waypoint7 waypoint57)
	(visible waypoint57 waypoint7)
	(visible waypoint8 waypoint15)
	(visible waypoint15 waypoint8)
	(visible waypoint8 waypoint29)
	(visible waypoint29 waypoint8)
	(visible waypoint8 waypoint35)
	(visible waypoint35 waypoint8)
	(visible waypoint8 waypoint37)
	(visible waypoint37 waypoint8)
	(visible waypoint8 waypoint45)
	(visible waypoint45 waypoint8)
	(visible waypoint8 waypoint46)
	(visible waypoint46 waypoint8)
	(visible waypoint8 waypoint50)
	(visible waypoint50 waypoint8)
	(visible waypoint8 waypoint57)
	(visible waypoint57 waypoint8)
	(visible waypoint9 waypoint41)
	(visible waypoint41 waypoint9)
	(visible waypoint9 waypoint58)
	(visible waypoint58 waypoint9)
	(visible waypoint10 waypoint20)
	(visible waypoint20 waypoint10)
	(visible waypoint10 waypoint23)
	(visible waypoint23 waypoint10)
	(visible waypoint10 waypoint24)
	(visible waypoint24 waypoint10)
	(visible waypoint10 waypoint33)
	(visible waypoint33 waypoint10)
	(visible waypoint10 waypoint43)
	(visible waypoint43 waypoint10)
	(visible waypoint11 waypoint26)
	(visible waypoint26 waypoint11)
	(visible waypoint11 waypoint32)
	(visible waypoint32 waypoint11)
	(visible waypoint12 waypoint5)
	(visible waypoint5 waypoint12)
	(visible waypoint12 waypoint7)
	(visible waypoint7 waypoint12)
	(visible waypoint12 waypoint24)
	(visible waypoint24 waypoint12)
	(visible waypoint12 waypoint28)
	(visible waypoint28 waypoint12)
	(visible waypoint13 waypoint7)
	(visible waypoint7 waypoint13)
	(visible waypoint13 waypoint9)
	(visible waypoint9 waypoint13)
	(visible waypoint13 waypoint21)
	(visible waypoint21 waypoint13)
	(visible waypoint13 waypoint22)
	(visible waypoint22 waypoint13)
	(visible waypoint13 waypoint28)
	(visible waypoint28 waypoint13)
	(visible waypoint13 waypoint32)
	(visible waypoint32 waypoint13)
	(visible waypoint13 waypoint59)
	(visible waypoint59 waypoint13)
	(visible waypoint14 waypoint4)
	(visible waypoint4 waypoint14)
	(visible waypoint14 waypoint11)
	(visible waypoint11 waypoint14)
	(visible waypoint14 waypoint15)
	(visible waypoint15 waypoint14)
	(visible waypoint14 waypoint18)
	(visible waypoint18 waypoint14)
	(visible waypoint14 waypoint31)
	(visible waypoint31 waypoint14)
	(visible waypoint14 waypoint52)
	(visible waypoint52 waypoint14)
	(visible waypoint14 waypoint57)
	(visible waypoint57 waypoint14)
	(visible waypoint15 waypoint4)
	(visible waypoint4 waypoint15)
	(visible waypoint15 waypoint5)
	(visible waypoint5 waypoint15)
	(visible waypoint15 waypoint9)
	(visible waypoint9 waypoint15)
	(visible waypoint15 waypoint40)
	(visible waypoint40 waypoint15)
	(visible waypoint15 waypoint56)
	(visible waypoint56 waypoint15)
	(visible waypoint16 waypoint0)
	(visible waypoint0 waypoint16)
	(visible waypoint16 waypoint5)
	(visible waypoint5 waypoint16)
	(visible waypoint16 waypoint23)
	(visible waypoint23 waypoint16)
	(visible waypoint16 waypoint24)
	(visible waypoint24 waypoint16)
	(visible waypoint16 waypoint32)
	(visible waypoint32 waypoint16)
	(visible waypoint16 waypoint47)
	(visible waypoint47 waypoint16)
	(visible waypoint16 waypoint53)
	(visible waypoint53 waypoint16)
	(visible waypoint16 waypoint58)
	(visible waypoint58 waypoint16)
	(visible waypoint17 waypoint28)
	(visible waypoint28 waypoint17)
	(visible waypoint17 waypoint42)
	(visible waypoint42 waypoint17)
	(visible waypoint17 waypoint43)
	(visible waypoint43 waypoint17)
	(visible waypoint18 waypoint12)
	(visible waypoint12 waypoint18)
	(visible waypoint18 waypoint22)
	(visible waypoint22 waypoint18)
	(visible waypoint18 waypoint41)
	(visible waypoint41 waypoint18)
	(visible waypoint18 waypoint50)
	(visible waypoint50 waypoint18)
	(visible waypoint18 waypoint58)
	(visible waypoint58 waypoint18)
	(visible waypoint19 waypoint18)
	(visible waypoint18 waypoint19)
	(visible waypoint19 waypoint38)
	(visible waypoint38 waypoint19)
	(visible waypoint20 waypoint4)
	(visible waypoint4 waypoint20)
	(visible waypoint20 waypoint23)
	(visible waypoint23 waypoint20)
	(visible waypoint20 waypoint28)
	(visible waypoint28 waypoint20)
	(visible waypoint20 waypoint36)
	(visible waypoint36 waypoint20)
	(visible waypoint20 waypoint40)
	(visible waypoint40 waypoint20)
	(visible waypoint20 waypoint44)
	(visible waypoint44 waypoint20)
	(visible waypoint21 waypoint0)
	(visible waypoint0 waypoint21)
	(visible waypoint21 waypoint8)
	(visible waypoint8 waypoint21)
	(visible waypoint21 waypoint11)
	(visible waypoint11 waypoint21)
	(visible waypoint21 waypoint14)
	(visible waypoint14 waypoint21)
	(visible waypoint21 waypoint46)
	(visible waypoint46 waypoint21)
	(visible waypoint21 waypoint47)
	(visible waypoint47 waypoint21)
	(visible waypoint22 waypoint8)
	(visible waypoint8 waypoint22)
	(visible waypoint22 waypoint19)
	(visible waypoint19 waypoint22)
	(visible waypoint22 waypoint27)
	(visible waypoint27 waypoint22)
	(visible waypoint22 waypoint41)
	(visible waypoint41 waypoint22)
	(visible waypoint22 waypoint50)
	(visible waypoint50 waypoint22)
	(visible waypoint22 waypoint56)
	(visible waypoint56 waypoint22)
	(visible waypoint23 waypoint9)
	(visible waypoint9 waypoint23)
	(visible waypoint23 waypoint37)
	(visible waypoint37 waypoint23)
	(visible waypoint23 waypoint46)
	(visible waypoint46 waypoint23)
	(visible waypoint23 waypoint52)
	(visible waypoint52 waypoint23)
	(visible waypoint23 waypoint53)
	(visible waypoint53 waypoint23)
	(visible waypoint24 waypoint4)
	(visible waypoint4 waypoint24)
	(visible waypoint24 waypoint20)
	(visible waypoint20 waypoint24)
	(visible waypoint24 waypoint52)
	(visible waypoint52 waypoint24)
	(visible waypoint24 waypoint53)
	(visible waypoint53 waypoint24)
	(visible waypoint24 waypoint56)
	(visible waypoint56 waypoint24)
	(visible waypoint25 waypoint0)
	(visible waypoint0 waypoint25)
	(visible waypoint25 waypoint2)
	(visible waypoint2 waypoint25)
	(visible waypoint25 waypoint11)
	(visible waypoint11 waypoint25)
	(visible waypoint25 waypoint13)
	(visible waypoint13 waypoint25)
	(visible waypoint25 waypoint54)
	(visible waypoint54 waypoint25)
	(visible waypoint26 waypoint4)
	(visible waypoint4 waypoint26)
	(visible waypoint26 waypoint17)
	(visible waypoint17 waypoint26)
	(visible waypoint26 waypoint19)
	(visible waypoint19 waypoint26)
	(visible waypoint26 waypoint22)
	(visible waypoint22 waypoint26)
	(visible waypoint26 waypoint31)
	(visible waypoint31 waypoint26)
	(visible waypoint26 waypoint45)
	(visible waypoint45 waypoint26)
	(visible waypoint26 waypoint58)
	(visible waypoint58 waypoint26)
	(visible waypoint27 waypoint2)
	(visible waypoint2 waypoint27)
	(visible waypoint27 waypoint26)
	(visible waypoint26 waypoint27)
	(visible waypoint27 waypoint29)
	(visible waypoint29 waypoint27)
	(visible waypoint27 waypoint41)
	(visible waypoint41 waypoint27)
	(visible waypoint28 waypoint1)
	(visible waypoint1 waypoint28)
	(visible waypoint28 waypoint37)
	(visible waypoint37 waypoint28)
	(visible waypoint28 waypoint46)
	(visible waypoint46 waypoint28)
	(visible waypoint28 waypoint54)
	(visible waypoint54 waypoint28)
	(visible waypoint29 waypoint1)
	(visible waypoint1 waypoint29)
	(visible waypoint29 waypoint32)
	(visible waypoint32 waypoint29)
	(visible waypoint29 waypoint35)
	(visible waypoint35 waypoint29)
	(visible waypoint29 waypoint48)
	(visible waypoint48 waypoint29)
	(visible waypoint29 waypoint54)
	(visible waypoint54 waypoint29)
	(visible waypoint29 waypoint57)
	(visible waypoint57 waypoint29)
	(visible waypoint30 waypoint10)
	(visible waypoint10 waypoint30)
	(visible waypoint30 waypoint44)
	(visible waypoint44 waypoint30)
	(visible waypoint30 waypoint45)
	(visible waypoint45 waypoint30)
	(visible waypoint30 waypoint48)
	(visible waypoint48 waypoint30)
	(visible waypoint30 waypoint50)
	(visible waypoint50 waypoint30)
	(visible waypoint31 waypoint1)
	(visible waypoint1 waypoint31)
	(visible waypoint31 waypoint15)
	(visible waypoint15 waypoint31)
	(visible waypoint31 waypoint30)
	(visible waypoint30 waypoint31)
	(visible waypoint31 waypoint56)
	(visible waypoint56 waypoint31)
	(visible waypoint32 waypoint5)
	(visible waypoint5 waypoint32)
	(visible waypoint32 waypoint6)
	(visible waypoint6 waypoint32)
	(visible waypoint32 waypoint12)
	(visible waypoint12 waypoint32)
	(visible waypoint32 waypoint45)
	(visible waypoint45 waypoint32)
	(visible waypoint33 waypoint2)
	(visible waypoint2 waypoint33)
	(visible waypoint33 waypoint8)
	(visible waypoint8 waypoint33)
	(visible waypoint33 waypoint26)
	(visible waypoint26 waypoint33)
	(visible waypoint33 waypoint30)
	(visible waypoint30 waypoint33)
	(visible waypoint33 waypoint40)
	(visible waypoint40 waypoint33)
	(visible waypoint33 waypoint42)
	(visible waypoint42 waypoint33)
	(visible waypoint34 waypoint8)
	(visible waypoint8 waypoint34)
	(visible waypoint34 waypoint15)
	(visible waypoint15 waypoint34)
	(visible waypoint34 waypoint52)
	(visible waypoint52 waypoint34)
	(visible waypoint35 waypoint2)
	(visible waypoint2 waypoint35)
	(visible waypoint35 waypoint5)
	(visible waypoint5 waypoint35)
	(visible waypoint35 waypoint7)
	(visible waypoint7 waypoint35)
	(visible waypoint35 waypoint21)
	(visible waypoint21 waypoint35)
	(visible waypoint35 waypoint37)
	(visible waypoint37 waypoint35)
	(visible waypoint35 waypoint44)
	(visible waypoint44 waypoint35)
	(visible waypoint36 waypoint6)
	(visible waypoint6 waypoint36)
	(visible waypoint36 waypoint18)
	(visible waypoint18 waypoint36)
	(visible waypoint36 waypoint22)
	(visible waypoint22 waypoint36)
	(visible waypoint36 waypoint29)
	(visible waypoint29 waypoint36)
	(visible waypoint36 waypoint34)
	(visible waypoint34 waypoint36)
	(visible waypoint36 waypoint48)
	(visible waypoint48 waypoint36)
	(visible waypoint36 waypoint50)
	(visible waypoint50 waypoint36)
	(visible waypoint37 waypoint5)
	(visible waypoint5 waypoint37)
	(visible waypoint37 waypoint25)
	(visible waypoint25 waypoint37)
	(visible waypoint37 waypoint27)
	(visible waypoint27 waypoint37)
	(visible waypoint37 waypoint36)
	(visible waypoint36 waypoint37)
	(visible waypoint38 waypoint2)
	(visible waypoint2 waypoint38)
	(visible waypoint38 waypoint9)
	(visible waypoint9 waypoint38)
	(visible waypoint38 waypoint12)
	(visible waypoint12 waypoint38)
	(visible waypoint38 waypoint14)
	(visible waypoint14 waypoint38)
	(visible waypoint38 waypoint15)
	(visible waypoint15 waypoint38)
	(visible waypoint38 waypoint27)
	(visible waypoint27 waypoint38)
	(visible waypoint38 waypoint30)
	(visible waypoint30 waypoint38)
	(visible waypoint38 waypoint53)
	(visible waypoint53 waypoint38)
	(visible waypoint39 waypoint10)
	(visible waypoint10 waypoint39)
	(visible waypoint39 waypoint22)
	(visible waypoint22 waypoint39)
	(visible waypoint39 waypoint33)
	(visible waypoint33 waypoint39)
	(visible waypoint39 waypoint54)
	(visible waypoint54 waypoint39)
	(visible waypoint39 waypoint58)
	(visible waypoint58 waypoint39)
	(visible waypoint40 waypoint18)
	(visible waypoint18 waypoint40)
	(visible waypoint40 waypoint21)
	(visible waypoint21 waypoint40)
	(visible waypoint40 waypoint48)
	(visible waypoint48 waypoint40)
	(visible waypoint40 waypoint54)
	(visible waypoint54 waypoint40)
	(visible waypoint41 waypoint6)
	(visible waypoint6 waypoint41)
	(visible waypoint41 waypoint10)
	(visible waypoint10 waypoint41)
	(visible waypoint41 waypoint12)
	(visible waypoint12 waypoint41)
	(visible waypoint41 waypoint32)
	(visible waypoint32 waypoint41)
	(visible waypoint41 waypoint54)
	(visible waypoint54 waypoint41)
	(visible waypoint42 waypoint39)
	(visible waypoint39 waypoint42)
	(visible waypoint43 waypoint4)
	(visible waypoint4 waypoint43)
	(visible waypoint43 waypoint11)
	(visible waypoint11 waypoint43)
	(visible waypoint43 waypoint58)
	(visible waypoint58 waypoint43)
	(visible waypoint44 waypoint5)
	(visible waypoint5 waypoint44)
	(visible waypoint44 waypoint14)
	(visible waypoint14 waypoint44)
	(visible waypoint44 waypoint26)
	(visible waypoint26 waypoint44)
	(visible waypoint44 waypoint38)
	(visible waypoint38 waypoint44)
	(visible waypoint45 waypoint24)
	(visible waypoint24 waypoint45)
	(visible waypoint45 waypoint33)
	(visible waypoint33 waypoint45)
	(visible waypoint45 waypoint38)
	(visible waypoint38 waypoint45)
	(visible waypoint45 waypoint49)
	(visible waypoint49 waypoint45)
	(visible waypoint46 waypoint4)
	(visible waypoint4 waypoint46)
	(visible waypoint46 waypoint16)
	(visible waypoint16 waypoint46)
	(visible waypoint46 waypoint30)
	(visible waypoint30 waypoint46)
	(visible waypoint47 waypoint6)
	(visible waypoint6 waypoint47)
	(visible waypoint47 waypoint24)
	(visible waypoint24 waypoint47)
	(visible waypoint47 waypoint50)
	(visible waypoint50 waypoint47)
	(visible waypoint48 waypoint1)
	(visible waypoint1 waypoint48)
	(visible waypoint48 waypoint2)
	(visible waypoint2 waypoint48)
	(visible waypoint48 waypoint14)
	(visible waypoint14 waypoint48)
	(visible waypoint48 waypoint18)
	(visible waypoint18 waypoint48)
	(visible waypoint49 waypoint14)
	(visible waypoint14 waypoint49)
	(visible waypoint49 waypoint29)
	(visible waypoint29 waypoint49)
	(visible waypoint49 waypoint46)
	(visible waypoint46 waypoint49)
	(visible waypoint50 waypoint6)
	(visible waypoint6 waypoint50)
	(visible waypoint50 waypoint16)
	(visible waypoint16 waypoint50)
	(visible waypoint50 waypoint17)
	(visible waypoint17 waypoint50)
	(visible waypoint50 waypoint48)
	(visible waypoint48 waypoint50)
	(visible waypoint50 waypoint59)
	(visible waypoint59 waypoint50)
	(visible waypoint51 waypoint16)
	(visible waypoint16 waypoint51)
	(visible waypoint51 waypoint20)
	(visible waypoint20 waypoint51)
	(visible waypoint51 waypoint34)
	(visible waypoint34 waypoint51)
	(visible waypoint51 waypoint38)
	(visible waypoint38 waypoint51)
	(visible waypoint52 waypoint5)
	(visible waypoint5 waypoint52)
	(visible waypoint52 waypoint40)
	(visible waypoint40 waypoint52)
	(visible waypoint52 waypoint46)
	(visible waypoint46 waypoint52)
	(visible waypoint52 waypoint49)
	(visible waypoint49 waypoint52)
	(visible waypoint53 waypoint12)
	(visible waypoint12 waypoint53)
	(visible waypoint53 waypoint29)
	(visible waypoint29 waypoint53)
	(visible waypoint53 waypoint51)
	(visible waypoint51 waypoint53)
	(visible waypoint54 waypoint11)
	(visible waypoint11 waypoint54)
	(visible waypoint54 waypoint20)
	(visible waypoint20 waypoint54)
	(visible waypoint55 waypoint25)
	(visible waypoint25 waypoint55)
	(visible waypoint55 waypoint31)
	(visible waypoint31 waypoint55)
	(visible waypoint55 waypoint36)
	(visible waypoint36 waypoint55)
	(visible waypoint55 waypoint47)
	(visible waypoint47 waypoint55)
	(visible waypoint55 waypoint53)
	(visible waypoint53 waypoint55)
	(visible waypoint56 waypoint12)
	(visible waypoint12 waypoint56)
	(visible waypoint56 waypoint21)
	(visible waypoint21 waypoint56)
	(visible waypoint56 waypoint33)
	(visible waypoint33 waypoint56)
	(visible waypoint56 waypoint39)
	(visible waypoint39 waypoint56)
	(visible waypoint56 waypoint42)
	(visible waypoint42 waypoint56)
	(visible waypoint56 waypoint46)
	(visible waypoint46 waypoint56)
	(visible waypoint56 waypoint51)
	(visible waypoint51 waypoint56)
	(visible waypoint57 waypoint47)
	(visible waypoint47 waypoint57)
	(visible waypoint58 waypoint1)
	(visible waypoint1 waypoint58)
	(visible waypoint58 waypoint3)
	(visible waypoint3 waypoint58)
	(visible waypoint58 waypoint22)
	(visible waypoint22 waypoint58)
	(visible waypoint58 waypoint44)
	(visible waypoint44 waypoint58)
	(visible waypoint58 waypoint48)
	(visible waypoint48 waypoint58)
	(visible waypoint58 waypoint56)
	(visible waypoint56 waypoint58)
	(visible waypoint59 waypoint28)
	(visible waypoint28 waypoint59)
	(visible waypoint59 waypoint31)
	(visible waypoint31 waypoint59)
	(visible waypoint59 waypoint40)
	(visible waypoint40 waypoint59)
	(visible waypoint59 waypoint51)
	(visible waypoint51 waypoint59)
	(visible waypoint59 waypoint57)
	(visible waypoint57 waypoint59)
	(at_soil_sample waypoint0)
	(at_rock_sample waypoint0)
	(at_soil_sample waypoint2)
	(at_rock_sample waypoint3)
	(at_rock_sample waypoint5)
	(at_soil_sample waypoint6)
	(at_soil_sample waypoint7)
	(at_rock_sample waypoint7)
	(at_rock_sample waypoint8)
	(at_rock_sample waypoint9)
	(at_rock_sample waypoint10)
	(at_rock_sample waypoint11)
	(at_soil_sample waypoint13)
	(at_rock_sample waypoint14)
	(at_soil_sample waypoint15)
	(at_soil_sample waypoint16)
	(at_rock_sample waypoint16)
	(at_soil_sample waypoint17)
	(at_rock_sample waypoint17)
	(at_soil_sample waypoint18)
	(at_rock_sample waypoint20)
	(at_soil_sample waypoint21)
	(at_rock_sample waypoint21)
	(at_soil_sample waypoint22)
	(at_soil_sample waypoint24)
	(at_rock_sample waypoint27)
	(at_soil_sample waypoint29)
	(at_rock_sample waypoint29)
	(at_soil_sample waypoint30)
	(at_rock_sample waypoint30)
	(at_soil_sample waypoint31)
	(at_rock_sample waypoint31)
	(at_rock_sample waypoint33)
	(at_soil_sample waypoint34)
	(at_soil_sample waypoint35)
	(at_soil_sample waypoint36)
	(at_rock_sample waypoint37)
	(at_soil_sample waypoint38)
	(at_rock_sample waypoint38)
	(at_soil_sample waypoint39)
	(at_soil_sample waypoint40)
	(at_rock_sample waypoint40)
	(at_soil_sample waypoint41)
	(at_rock_sample waypoint41)
	(at_soil_sample waypoint42)
	(at_rock_sample waypoint42)
	(at_soil_sample waypoint43)
	(at_rock_sample waypoint45)
	(at_soil_sample waypoint46)
	(at_rock_sample waypoint46)
	(at_soil_sample waypoint47)
	(at_rock_sample waypoint47)
	(at_rock_sample waypoint48)
	(at_soil_sample waypoint49)
	(at_soil_sample waypoint50)
	(at_rock_sample waypoint51)
	(at_soil_sample waypoint52)
	(at_rock_sample waypoint52)
	(at_soil_sample waypoint53)
	(at_rock_sample waypoint53)
	(at_soil_sample waypoint54)
	(at_rock_sample waypoint54)
	(at_soil_sample waypoint55)
	(at_rock_sample waypoint56)
	(at_rock_sample waypoint57)
	(at_soil_sample waypoint58)
	(at_rock_sample waypoint58)
	(at_rock_sample waypoint59)
	(at_lander general waypoint30)
	(channel_free general)
	(at rover0 waypoint5)
	(available rover0)
	(store_of rover0store rover0)
	(empty rover0store)
	(equipped_for_soil_analysis rover0)
	(equipped_for_imaging rover0)
	(can_traverse rover0 waypoint5 waypoint12)
	(can_traverse rover0 waypoint12 waypoint5)
	(can_traverse rover0 waypoint5 waypoint30)
	(can_traverse rover0 waypoint30 waypoint5)
	(can_traverse rover0 waypoint5 waypoint31)
	(can_traverse rover0 waypoint31 waypoint5)
	(can_traverse rover0 waypoint5 waypoint32)
	(can_traverse rover0 waypoint32 waypoint5)
	(can_traverse rover0 waypoint5 waypoint44)
	(can_traverse rover0 waypoint44 waypoint5)
	(can_traverse rover0 waypoint5 waypoint52)
	(can_traverse rover0 waypoint52 waypoint5)
	(can_traverse rover0 waypoint12 waypoint6)
	(can_traverse rover0 waypoint6 waypoint12)
	(can_traverse rover0 waypoint12 waypoint18)
	(can_traverse rover0 waypoint18 waypoint12)
	(can_traverse rover0 waypoint12 waypoint24)
	(can_traverse rover0 waypoint24 waypoint12)
	(can_traverse rover0 waypoint12 waypoint28)
	(can_traverse rover0 waypoint28 waypoint12)
	(can_traverse rover0 waypoint12 waypoint41)
	(can_traverse rover0 waypoint41 waypoint12)
	(can_traverse rover0 waypoint12 waypoint56)
	(can_traverse rover0 waypoint56 waypoint12)
	(can_traverse rover0 waypoint30 waypoint33)
	(can_traverse rover0 waypoint33 waypoint30)
	(can_traverse rover0 waypoint30 waypoint45)
	(can_traverse rover0 waypoint45 waypoint30)
	(can_traverse rover0 waypoint30 waypoint46)
	(can_traverse rover0 waypoint46 waypoint30)
	(can_traverse rover0 waypoint30 waypoint48)
	(can_traverse rover0 waypoint48 waypoint30)
	(can_traverse rover0 waypoint30 waypoint50)
	(can_traverse rover0 waypoint50 waypoint30)
	(can_traverse rover0 waypoint31 waypoint1)
	(can_traverse rover0 waypoint1 waypoint31)
	(can_traverse rover0 waypoint31 waypoint14)
	(can_traverse rover0 waypoint14 waypoint31)
	(can_traverse rover0 waypoint31 waypoint15)
	(can_traverse rover0 waypoint15 waypoint31)
	(can_traverse rover0 waypoint31 waypoint55)
	(can_traverse rover0 waypoint55 waypoint31)
	(can_traverse rover0 waypoint31 waypoint59)
	(can_traverse rover0 waypoint59 waypoint31)
	(can_traverse rover0 waypoint32 waypoint11)
	(can_traverse rover0 waypoint11 waypoint32)
	(can_traverse rover0 waypoint32 waypoint16)
	(can_traverse rover0 waypoint16 waypoint32)
	(can_traverse rover0 waypoint32 waypoint29)
	(can_traverse rover0 waypoint29 waypoint32)
	(can_traverse rover0 waypoint44 waypoint2)
	(can_traverse rover0 waypoint2 waypoint44)
	(can_traverse rover0 waypoint44 waypoint26)
	(can_traverse rover0 waypoint26 waypoint44)
	(can_traverse rover0 waypoint44 waypoint35)
	(can_traverse rover0 waypoint35 waypoint44)
	(can_traverse rover0 waypoint52 waypoint23)
	(can_traverse rover0 waypoint23 waypoint52)
	(can_traverse rover0 waypoint52 waypoint34)
	(can_traverse rover0 waypoint34 waypoint52)
	(can_traverse rover0 waypoint52 waypoint49)
	(can_traverse rover0 waypoint49 waypoint52)
	(can_traverse rover0 waypoint6 waypoint17)
	(can_traverse rover0 waypoint17 waypoint6)
	(can_traverse rover0 waypoint6 waypoint36)
	(can_traverse rover0 waypoint36 waypoint6)
	(can_traverse rover0 waypoint6 waypoint57)
	(can_traverse rover0 waypoint57 waypoint6)
	(can_traverse rover0 waypoint18 waypoint22)
	(can_traverse rover0 waypoint22 waypoint18)
	(can_traverse rover0 waypoint18 waypoint40)
	(can_traverse rover0 waypoint40 waypoint18)
	(can_traverse rover0 waypoint18 waypoint58)
	(can_traverse rover0 waypoint58 waypoint18)
	(can_traverse rover0 waypoint24 waypoint10)
	(can_traverse rover0 waypoint10 waypoint24)
	(can_traverse rover0 waypoint24 waypoint20)
	(can_traverse rover0 waypoint20 waypoint24)
	(can_traverse rover0 waypoint24 waypoint47)
	(can_traverse rover0 waypoint47 waypoint24)
	(can_traverse rover0 waypoint24 waypoint53)
	(can_traverse rover0 waypoint53 waypoint24)
	(can_traverse rover0 waypoint28 waypoint0)
	(can_traverse rover0 waypoint0 waypoint28)
	(can_traverse rover0 waypoint28 waypoint13)
	(can_traverse rover0 waypoint13 waypoint28)
	(can_traverse rover0 waypoint28 waypoint37)
	(can_traverse rover0 waypoint37 waypoint28)
	(can_traverse rover0 waypoint28 waypoint54)
	(can_traverse rover0 waypoint54 waypoint28)
	(can_traverse rover0 waypoint41 waypoint4)
	(can_traverse rover0 waypoint4 waypoint41)
	(can_traverse rover0 waypoint41 waypoint7)
	(can_traverse rover0 waypoint7 waypoint41)
	(can_traverse rover0 waypoint41 waypoint9)
	(can_traverse rover0 waypoint9 waypoint41)
	(can_traverse rover0 waypoint56 waypoint21)
	(can_traverse rover0 waypoint21 waypoint56)
	(can_traverse rover0 waypoint56 waypoint51)
	(can_traverse rover0 waypoint51 waypoint56)
	(can_traverse rover0 waypoint33 waypoint8)
	(can_traverse rover0 waypoint8 waypoint33)
	(can_traverse rover0 waypoint45 waypoint38)
	(can_traverse rover0 waypoint38 waypoint45)
	(can_traverse rover0 waypoint29 waypoint27)
	(can_traverse rover0 waypoint27 waypoint29)
	(can_traverse rover0 waypoint2 waypoint25)
	(can_traverse rover0 waypoint25 waypoint2)
	(can_traverse rover0 waypoint26 waypoint19)
	(can_traverse rover0 waypoint19 waypoint26)
	(can_traverse rover0 waypoint17 waypoint42)
	(can_traverse rover0 waypoint42 waypoint17)
	(can_traverse rover0 waypoint22 waypoint39)
	(can_traverse rover0 waypoint39 waypoint22)
	(can_traverse rover0 waypoint58 waypoint3)
	(can_traverse rover0 waypoint3 waypoint58)
	(can_traverse rover0 waypoint10 waypoint43)
	(can_traverse rover0 waypoint43 waypoint10)
	(at rover1 waypoint13)
	(available rover1)
	(store_of rover1store rover1)
	(empty rover1store)
	(equipped_for_rock_analysis rover1)
	(equipped_for_imaging rover1)
	(can_traverse rover1 waypoint13 waypoint4)
	(can_traverse rover1 waypoint4 waypoint13)
	(can_traverse rover1 waypoint13 waypoint7)
	(can_traverse rover1 waypoint7 waypoint13)
	(can_traverse rover1 waypoint13 waypoint9)
	(can_traverse rover1 waypoint9 waypoint13)
	(can_traverse rover1 waypoint13 waypoint21)
	(can_traverse rover1 waypoint21 waypoint13)
	(can_traverse rover1 waypoint13 waypoint22)
	(can_traverse rover1 waypoint22 waypoint13)
	(can_traverse rover1 waypoint13 waypoint25)
	(can_traverse rover1 waypoint25 waypoint13)
	(can_traverse rover1 waypoint13 waypoint28)
	(can_traverse rover1 waypoint28 waypoint13)
	(can_traverse rover1 waypoint13 waypoint32)
	(can_traverse rover1 waypoint32 waypoint13)
	(can_traverse rover1 waypoint13 waypoint59)
	(can_traverse rover1 waypoint59 waypoint13)
	(can_traverse rover1 waypoint4 waypoint14)
	(can_traverse rover1 waypoint14 waypoint4)
	(can_traverse rover1 waypoint4 waypoint15)
	(can_traverse rover1 waypoint15 waypoint4)
	(can_traverse rover1 waypoint4 waypoint20)
	(can_traverse rover1 waypoint20 waypoint4)
	(can_traverse rover1 waypoint4 waypoint24)
	(can_traverse rover1 waypoint24 waypoint4)
	(can_traverse rover1 waypoint4 waypoint26)
	(can_traverse rover1 waypoint26 waypoint4)
	(can_traverse rover1 waypoint4 waypoint41)
	(can_traverse rover1 waypoint41 waypoint4)
	(can_traverse rover1 waypoint4 waypoint56)
	(can_traverse rover1 waypoint56 waypoint4)
	(can_traverse rover1 waypoint4 waypoint57)
	(can_traverse rover1 waypoint57 waypoint4)
	(can_traverse rover1 waypoint7 waypoint3)
	(can_traverse rover1 waypoint3 waypoint7)
	(can_traverse rover1 waypoint7 waypoint11)
	(can_traverse rover1 waypoint11 waypoint7)
	(can_traverse rover1 waypoint7 waypoint12)
	(can_traverse rover1 waypoint12 waypoint7)
	(can_traverse rover1 waypoint7 waypoint35)
	(can_traverse rover1 waypoint35 waypoint7)
	(can_traverse rover1 waypoint9 waypoint23)
	(can_traverse rover1 waypoint23 waypoint9)
	(can_traverse rover1 waypoint9 waypoint38)
	(can_traverse rover1 waypoint38 waypoint9)
	(can_traverse rover1 waypoint9 waypoint58)
	(can_traverse rover1 waypoint58 waypoint9)
	(can_traverse rover1 waypoint21 waypoint8)
	(can_traverse rover1 waypoint8 waypoint21)
	(can_traverse rover1 waypoint21 waypoint46)
	(can_traverse rover1 waypoint46 waypoint21)
	(can_traverse rover1 waypoint21 waypoint47)
	(can_traverse rover1 waypoint47 waypoint21)
	(can_traverse rover1 waypoint22 waypoint1)
	(can_traverse rover1 waypoint1 waypoint22)
	(can_traverse rover1 waypoint22 waypoint39)
	(can_traverse rover1 waypoint39 waypoint22)
	(can_traverse rover1 waypoint25 waypoint37)
	(can_traverse rover1 waypoint37 waypoint25)
	(can_traverse rover1 waypoint25 waypoint54)
	(can_traverse rover1 waypoint54 waypoint25)
	(can_traverse rover1 waypoint25 waypoint55)
	(can_traverse rover1 waypoint55 waypoint25)
	(can_traverse rover1 waypoint28 waypoint0)
	(can_traverse rover1 waypoint0 waypoint28)
	(can_traverse rover1 waypoint28 waypoint17)
	(can_traverse rover1 waypoint17 waypoint28)
	(can_traverse rover1 waypoint32 waypoint5)
	(can_traverse rover1 waypoint5 waypoint32)
	(can_traverse rover1 waypoint32 waypoint6)
	(can_traverse rover1 waypoint6 waypoint32)
	(can_traverse rover1 waypoint32 waypoint16)
	(can_traverse rover1 waypoint16 waypoint32)
	(can_traverse rover1 waypoint32 waypoint29)
	(can_traverse rover1 waypoint29 waypoint32)
	(can_traverse rover1 waypoint59 waypoint31)
	(can_traverse rover1 waypoint31 waypoint59)
	(can_traverse rover1 waypoint59 waypoint40)
	(can_traverse rover1 waypoint40 waypoint59)
	(can_traverse rover1 waypoint59 waypoint50)
	(can_traverse rover1 waypoint50 waypoint59)
	(can_traverse rover1 waypoint59 waypoint51)
	(can_traverse rover1 waypoint51 waypoint59)
	(can_traverse rover1 waypoint14 waypoint18)
	(can_traverse rover1 waypoint18 waypoint14)
	(can_traverse rover1 waypoint14 waypoint48)
	(can_traverse rover1 waypoint48 waypoint14)
	(can_traverse rover1 waypoint14 waypoint49)
	(can_traverse rover1 waypoint49 waypoint14)
	(can_traverse rover1 waypoint14 waypoint52)
	(can_traverse rover1 waypoint52 waypoint14)
	(can_traverse rover1 waypoint15 waypoint34)
	(can_traverse rover1 waypoint34 waypoint15)
	(can_traverse rover1 waypoint20 waypoint10)
	(can_traverse rover1 waypoint10 waypoint20)
	(can_traverse rover1 waypoint20 waypoint36)
	(can_traverse rover1 waypoint36 waypoint20)
	(can_traverse rover1 waypoint24 waypoint53)
	(can_traverse rover1 waypoint53 waypoint24)
	(can_traverse rover1 waypoint26 waypoint19)
	(can_traverse rover1 waypoint19 waypoint26)
	(can_traverse rover1 waypoint26 waypoint33)
	(can_traverse rover1 waypoint33 waypoint26)
	(can_traverse rover1 waypoint26 waypoint44)
	(can_traverse rover1 waypoint44 waypoint26)
	(can_traverse rover1 waypoint26 waypoint45)
	(can_traverse rover1 waypoint45 waypoint26)
	(can_traverse rover1 waypoint41 waypoint2)
	(can_traverse rover1 waypoint2 waypoint41)
	(can_traverse rover1 waypoint41 waypoint27)
	(can_traverse rover1 waypoint27 waypoint41)
	(can_traverse rover1 waypoint56 waypoint42)
	(can_traverse rover1 waypoint42 waypoint56)
	(can_traverse rover1 waypoint11 waypoint43)
	(can_traverse rover1 waypoint43 waypoint11)
	(can_traverse rover1 waypoint38 waypoint30)
	(can_traverse rover1 waypoint30 waypoint38)
	(at rover2 waypoint16)
	(available rover2)
	(store_of rover2store rover2)
	(empty rover2store)
	(equipped_for_imaging rover2)
	(can_traverse rover2 waypoint16 waypoint0)
	(can_traverse rover2 waypoint0 waypoint16)
	(can_traverse rover2 waypoint16 waypoint5)
	(can_traverse rover2 waypoint5 waypoint16)
	(can_traverse rover2 waypoint16 waypoint46)
	(can_traverse rover2 waypoint46 waypoint16)
	(can_traverse rover2 waypoint16 waypoint47)
	(can_traverse rover2 waypoint47 waypoint16)
	(can_traverse rover2 waypoint16 waypoint50)
	(can_traverse rover2 waypoint50 waypoint16)
	(can_traverse rover2 waypoint16 waypoint51)
	(can_traverse rover2 waypoint51 waypoint16)
	(can_traverse rover2 waypoint16 waypoint53)
	(can_traverse rover2 waypoint53 waypoint16)
	(can_traverse rover2 waypoint16 waypoint58)
	(can_traverse rover2 waypoint58 waypoint16)
	(can_traverse rover2 waypoint0 waypoint25)
	(can_traverse rover2 waypoint25 waypoint0)
	(can_traverse rover2 waypoint0 waypoint39)
	(can_traverse rover2 waypoint39 waypoint0)
	(can_traverse rover2 waypoint0 waypoint44)
	(can_traverse rover2 waypoint44 waypoint0)
	(can_traverse rover2 waypoint0 waypoint52)
	(can_traverse rover2 waypoint52 waypoint0)
	(can_traverse rover2 waypoint5 waypoint12)
	(can_traverse rover2 waypoint12 waypoint5)
	(can_traverse rover2 waypoint5 waypoint30)
	(can_traverse rover2 waypoint30 waypoint5)
	(can_traverse rover2 waypoint5 waypoint31)
	(can_traverse rover2 waypoint31 waypoint5)
	(can_traverse rover2 waypoint5 waypoint32)
	(can_traverse rover2 waypoint32 waypoint5)
	(can_traverse rover2 waypoint5 waypoint35)
	(can_traverse rover2 waypoint35 waypoint5)
	(can_traverse rover2 waypoint5 waypoint37)
	(can_traverse rover2 waypoint37 waypoint5)
	(can_traverse rover2 waypoint5 waypoint48)
	(can_traverse rover2 waypoint48 waypoint5)
	(can_traverse rover2 waypoint46 waypoint4)
	(can_traverse rover2 waypoint4 waypoint46)
	(can_traverse rover2 waypoint46 waypoint8)
	(can_traverse rover2 waypoint8 waypoint46)
	(can_traverse rover2 waypoint46 waypoint21)
	(can_traverse rover2 waypoint21 waypoint46)
	(can_traverse rover2 waypoint46 waypoint28)
	(can_traverse rover2 waypoint28 waypoint46)
	(can_traverse rover2 waypoint46 waypoint49)
	(can_traverse rover2 waypoint49 waypoint46)
	(can_traverse rover2 waypoint46 waypoint56)
	(can_traverse rover2 waypoint56 waypoint46)
	(can_traverse rover2 waypoint47 waypoint6)
	(can_traverse rover2 waypoint6 waypoint47)
	(can_traverse rover2 waypoint47 waypoint24)
	(can_traverse rover2 waypoint24 waypoint47)
	(can_traverse rover2 waypoint47 waypoint55)
	(can_traverse rover2 waypoint55 waypoint47)
	(can_traverse rover2 waypoint47 waypoint57)
	(can_traverse rover2 waypoint57 waypoint47)
	(can_traverse rover2 waypoint50 waypoint17)
	(can_traverse rover2 waypoint17 waypoint50)
	(can_traverse rover2 waypoint50 waypoint18)
	(can_traverse rover2 waypoint18 waypoint50)
	(can_traverse rover2 waypoint50 waypoint36)
	(can_traverse rover2 waypoint36 waypoint50)
	(can_traverse rover2 waypoint51 waypoint20)
	(can_traverse rover2 waypoint20 waypoint51)
	(can_traverse rover2 waypoint51 waypoint34)
	(can_traverse rover2 waypoint34 waypoint51)
	(can_traverse rover2 waypoint51 waypoint38)
	(can_traverse rover2 waypoint38 waypoint51)
	(can_traverse rover2 waypoint51 waypoint59)
	(can_traverse rover2 waypoint59 waypoint51)
	(can_traverse rover2 waypoint53 waypoint29)
	(can_traverse rover2 waypoint29 waypoint53)
	(can_traverse rover2 waypoint58 waypoint1)
	(can_traverse rover2 waypoint1 waypoint58)
	(can_traverse rover2 waypoint58 waypoint3)
	(can_traverse rover2 waypoint3 waypoint58)
	(can_traverse rover2 waypoint58 waypoint9)
	(can_traverse rover2 waypoint9 waypoint58)
	(can_traverse rover2 waypoint58 waypoint43)
	(can_traverse rover2 waypoint43 waypoint58)
	(can_traverse rover2 waypoint25 waypoint2)
	(can_traverse rover2 waypoint2 waypoint25)
	(can_traverse rover2 waypoint25 waypoint11)
	(can_traverse rover2 waypoint11 waypoint25)
	(can_traverse rover2 waypoint25 waypoint13)
	(can_traverse rover2 waypoint13 waypoint25)
	(can_traverse rover2 waypoint25 waypoint54)
	(can_traverse rover2 waypoint54 waypoint25)
	(can_traverse rover2 waypoint39 waypoint10)
	(can_traverse rover2 waypoint10 waypoint39)
	(can_traverse rover2 waypoint39 waypoint22)
	(can_traverse rover2 waypoint22 waypoint39)
	(can_traverse rover2 waypoint39 waypoint33)
	(can_traverse rover2 waypoint33 waypoint39)
	(can_traverse rover2 waypoint39 waypoint42)
	(can_traverse rover2 waypoint42 waypoint39)
	(can_traverse rover2 waypoint44 waypoint7)
	(can_traverse rover2 waypoint7 waypoint44)
	(can_traverse rover2 waypoint44 waypoint14)
	(can_traverse rover2 waypoint14 waypoint44)
	(can_traverse rover2 waypoint44 waypoint26)
	(can_traverse rover2 waypoint26 waypoint44)
	(can_traverse rover2 waypoint52 waypoint23)
	(can_traverse rover2 waypoint23 waypoint52)
	(can_traverse rover2 waypoint52 waypoint40)
	(can_traverse rover2 waypoint40 waypoint52)
	(can_traverse rover2 waypoint31 waypoint15)
	(can_traverse rover2 waypoint15 waypoint31)
	(can_traverse rover2 waypoint32 waypoint41)
	(can_traverse rover2 waypoint41 waypoint32)
	(can_traverse rover2 waypoint32 waypoint45)
	(can_traverse rover2 waypoint45 waypoint32)
	(can_traverse rover2 waypoint18 waypoint19)
	(can_traverse rover2 waypoint19 waypoint18)
	(can_traverse rover2 waypoint29 waypoint27)
	(can_traverse rover2 waypoint27 waypoint29)
	(at rover3 waypoint26)
	(available rover3)
	(store_of rover3store rover3)
	(empty rover3store)
	(equipped_for_soil_analysis rover3)
	(equipped_for_imaging rover3)
	(can_traverse rover3 waypoint26 waypoint4)
	(can_traverse rover3 waypoint4 waypoint26)
	(can_traverse rover3 waypoint26 waypoint11)
	(can_traverse rover3 waypoint11 waypoint26)
	(can_traverse rover3 waypoint26 waypoint19)
	(can_traverse rover3 waypoint19 waypoint26)
	(can_traverse rover3 waypoint26 waypoint22)
	(can_traverse rover3 waypoint22 waypoint26)
	(can_traverse rover3 waypoint26 waypoint27)
	(can_traverse rover3 waypoint27 waypoint26)
	(can_traverse rover3 waypoint26 waypoint31)
	(can_traverse rover3 waypoint31 waypoint26)
	(can_traverse rover3 waypoint26 waypoint33)
	(can_traverse rover3 waypoint33 waypoint26)
	(can_traverse rover3 waypoint26 waypoint44)
	(can_traverse rover3 waypoint44 waypoint26)
	(can_traverse rover3 waypoint4 waypoint14)
	(can_traverse rover3 waypoint14 waypoint4)
	(can_traverse rover3 waypoint4 waypoint15)
	(can_traverse rover3 waypoint15 waypoint4)
	(can_traverse rover3 waypoint4 waypoint20)
	(can_traverse rover3 waypoint20 waypoint4)
	(can_traverse rover3 waypoint4 waypoint24)
	(can_traverse rover3 waypoint24 waypoint4)
	(can_traverse rover3 waypoint4 waypoint43)
	(can_traverse rover3 waypoint43 waypoint4)
	(can_traverse rover3 waypoint4 waypoint46)
	(can_traverse rover3 waypoint46 waypoint4)
	(can_traverse rover3 waypoint4 waypoint57)
	(can_traverse rover3 waypoint57 waypoint4)
	(can_traverse rover3 waypoint11 waypoint25)
	(can_traverse rover3 waypoint25 waypoint11)
	(can_traverse rover3 waypoint11 waypoint32)
	(can_traverse rover3 waypoint32 waypoint11)
	(can_traverse rover3 waypoint19 waypoint3)
	(can_traverse rover3 waypoint3 waypoint19)
	(can_traverse rover3 waypoint19 waypoint18)
	(can_traverse rover3 waypoint18 waypoint19)
	(can_traverse rover3 waypoint19 waypoint38)
	(can_traverse rover3 waypoint38 waypoint19)
	(can_traverse rover3 waypoint22 waypoint8)
	(can_traverse rover3 waypoint8 waypoint22)
	(can_traverse rover3 waypoint22 waypoint13)
	(can_traverse rover3 waypoint13 waypoint22)
	(can_traverse rover3 waypoint22 waypoint39)
	(can_traverse rover3 waypoint39 waypoint22)
	(can_traverse rover3 waypoint22 waypoint41)
	(can_traverse rover3 waypoint41 waypoint22)
	(can_traverse rover3 waypoint22 waypoint50)
	(can_traverse rover3 waypoint50 waypoint22)
	(can_traverse rover3 waypoint27 waypoint2)
	(can_traverse rover3 waypoint2 waypoint27)
	(can_traverse rover3 waypoint27 waypoint29)
	(can_traverse rover3 waypoint29 waypoint27)
	(can_traverse rover3 waypoint31 waypoint1)
	(can_traverse rover3 waypoint1 waypoint31)
	(can_traverse rover3 waypoint31 waypoint5)
	(can_traverse rover3 waypoint5 waypoint31)
	(can_traverse rover3 waypoint31 waypoint55)
	(can_traverse rover3 waypoint55 waypoint31)
	(can_traverse rover3 waypoint31 waypoint56)
	(can_traverse rover3 waypoint56 waypoint31)
	(can_traverse rover3 waypoint31 waypoint59)
	(can_traverse rover3 waypoint59 waypoint31)
	(can_traverse rover3 waypoint33 waypoint10)
	(can_traverse rover3 waypoint10 waypoint33)
	(can_traverse rover3 waypoint33 waypoint40)
	(can_traverse rover3 waypoint40 waypoint33)
	(can_traverse rover3 waypoint33 waypoint42)
	(can_traverse rover3 waypoint42 waypoint33)
	(can_traverse rover3 waypoint33 waypoint45)
	(can_traverse rover3 waypoint45 waypoint33)
	(can_traverse rover3 waypoint44 waypoint0)
	(can_traverse rover3 waypoint0 waypoint44)
	(can_traverse rover3 waypoint44 waypoint7)
	(can_traverse rover3 waypoint7 waypoint44)
	(can_traverse rover3 waypoint44 waypoint30)
	(can_traverse rover3 waypoint30 waypoint44)
	(can_traverse rover3 waypoint44 waypoint35)
	(can_traverse rover3 waypoint35 waypoint44)
	(can_traverse rover3 waypoint14 waypoint21)
	(can_traverse rover3 waypoint21 waypoint14)
	(can_traverse rover3 waypoint14 waypoint48)
	(can_traverse rover3 waypoint48 waypoint14)
	(can_traverse rover3 waypoint14 waypoint49)
	(can_traverse rover3 waypoint49 waypoint14)
	(can_traverse rover3 waypoint20 waypoint28)
	(can_traverse rover3 waypoint28 waypoint20)
	(can_traverse rover3 waypoint20 waypoint36)
	(can_traverse rover3 waypoint36 waypoint20)
	(can_traverse rover3 waypoint20 waypoint51)
	(can_traverse rover3 waypoint51 waypoint20)
	(can_traverse rover3 waypoint20 waypoint54)
	(can_traverse rover3 waypoint54 waypoint20)
	(can_traverse rover3 waypoint24 waypoint12)
	(can_traverse rover3 waypoint12 waypoint24)
	(can_traverse rover3 waypoint24 waypoint47)
	(can_traverse rover3 waypoint47 waypoint24)
	(can_traverse rover3 waypoint24 waypoint53)
	(can_traverse rover3 waypoint53 waypoint24)
	(can_traverse rover3 waypoint43 waypoint17)
	(can_traverse rover3 waypoint17 waypoint43)
	(can_traverse rover3 waypoint43 waypoint58)
	(can_traverse rover3 waypoint58 waypoint43)
	(can_traverse rover3 waypoint57 waypoint6)
	(can_traverse rover3 waypoint6 waypoint57)
	(can_traverse rover3 waypoint25 waypoint37)
	(can_traverse rover3 waypoint37 waypoint25)
	(can_traverse rover3 waypoint32 waypoint16)
	(can_traverse rover3 waypoint16 waypoint32)
	(can_traverse rover3 waypoint38 waypoint9)
	(can_traverse rover3 waypoint9 waypoint38)
	(can_traverse rover3 waypoint8 waypoint34)
	(can_traverse rover3 waypoint34 waypoint8)
	(can_traverse rover3 waypoint5 waypoint52)
	(can_traverse rover3 waypoint52 waypoint5)
	(can_traverse rover3 waypoint53 waypoint23)
	(can_traverse rover3 waypoint23 waypoint53)
	(on_board camera0 rover0)
	(calibration_target camera0 objective7)
	(supports camera0 colour)
	(supports camera0 low_res)
	(on_board camera1 rover3)
	(calibration_target camera1 objective6)
	(supports camera1 colour)
	(supports camera1 low_res)
	(on_board camera2 rover0)
	(calibration_target camera2 objective0)
	(supports camera2 low_res)
	(on_board camera3 rover3)
	(calibration_target camera3 objective6)
	(supports camera3 colour)
	(supports camera3 low_res)
	(on_board camera4 rover2)
	(calibration_target camera4 objective5)
	(supports camera4 colour)
	(supports camera4 high_res)
	(on_board camera5 rover3)
	(calibration_target camera5 objective2)
	(supports camera5 colour)
	(supports camera5 low_res)
	(on_board camera6 rover1)
	(calibration_target camera6 objective6)
	(supports camera6 high_res)
	(supports camera6 low_res)
	(visible_from objective0 waypoint2)
	(visible_from objective0 waypoint3)
	(visible_from objective0 waypoint4)
	(visible_from objective0 waypoint5)
	(visible_from objective0 waypoint11)
	(visible_from objective0 waypoint15)
	(visible_from objective0 waypoint19)
	(visible_from objective0 waypoint20)
	(visible_from objective0 waypoint23)
	(visible_from objective0 waypoint25)
	(visible_from objective0 waypoint28)
	(visible_from objective0 waypoint30)
	(visible_from objective0 waypoint40)
	(visible_from objective0 waypoint41)
	(visible_from objective0 waypoint43)
	(visible_from objective0 waypoint44)
	(visible_from objective0 waypoint48)
	(visible_from objective0 waypoint53)
	(visible_from objective0 waypoint55)
	(visible_from objective0 waypoint56)
	(visible_from objective0 waypoint59)
	(visible_from objective1 waypoint1)
	(visible_from objective1 waypoint15)
	(visible_from objective1 waypoint21)
	(visible_from objective1 waypoint28)
	(visible_from objective1 waypoint29)
	(visible_from objective1 waypoint30)
	(visible_from objective1 waypoint31)
	(visible_from objective1 waypoint37)
	(visible_from objective1 waypoint41)
	(visible_from objective1 waypoint42)
	(visible_from objective1 waypoint47)
	(visible_from objective1 waypoint52)
	(visible_from objective2 waypoint0)
	(visible_from objective2 waypoint1)
	(visible_from objective2 waypoint3)
	(visible_from objective2 waypoint11)
	(visible_from objective2 waypoint12)
	(visible_from objective2 waypoint14)
	(visible_from objective2 waypoint15)
	(visible_from objective2 waypoint20)
	(visible_from objective2 waypoint21)
	(visible_from objective2 waypoint22)
	(visible_from objective2 waypoint24)
	(visible_from objective2 waypoint25)
	(visible_from objective2 waypoint29)
	(visible_from objective2 waypoint30)
	(visible_from objective2 waypoint33)
	(visible_from objective2 waypoint34)
	(visible_from objective2 waypoint37)
	(visible_from objective2 waypoint41)
	(visible_from objective2 waypoint42)
	(visible_from objective2 waypoint43)
	(visible_from objective2 waypoint44)
	(visible_from objective2 waypoint45)
	(visible_from objective2 waypoint47)
	(visible_from objective2 waypoint48)
	(visible_from objective2 waypoint53)
	(visible_from objective2 waypoint54)
	(visible_from objective2 waypoint55)
	(visible_from objective2 waypoint56)
	(visible_from objective2 waypoint58)
	(visible_from objective2 waypoint59)
	(visible_from objective3 waypoint2)
	(visible_from objective3 waypoint4)
	(visible_from objective3 waypoint10)
	(visible_from objective3 waypoint11)
	(visible_from objective3 waypoint13)
	(visible_from objective3 waypoint16)
	(visible_from objective3 waypoint17)
	(visible_from objective3 waypoint21)
	(visible_from objective3 waypoint25)
	(visible_from objective3 waypoint26)
	(visible_from objective3 waypoint28)
	(visible_from objective3 waypoint32)
	(visible_from objective3 waypoint33)
	(visible_from objective3 waypoint35)
	(visible_from objective3 waypoint36)
	(visible_from objective3 waypoint37)
	(visible_from objective3 waypoint39)
	(visible_from objective3 waypoint44)
	(visible_from objective3 waypoint45)
	(visible_from objective3 waypoint46)
	(visible_from objective3 waypoint47)
	(visible_from objective3 waypoint48)
	(visible_from objective3 waypoint49)
	(visible_from objective3 waypoint50)
	(visible_from objective3 waypoint51)
	(visible_from objective3 waypoint52)
	(visible_from objective3 waypoint53)
	(visible_from objective3 waypoint56)
	(visible_from objective3 waypoint58)
	(visible_from objective4 waypoint0)
	(visible_from objective4 waypoint2)
	(visible_from objective4 waypoint3)
	(visible_from objective4 waypoint5)
	(visible_from objective4 waypoint6)
	(visible_from objective4 waypoint8)
	(visible_from objective4 waypoint10)
	(visible_from objective4 waypoint11)
	(visible_from objective4 waypoint13)
	(visible_from objective4 waypoint15)
	(visible_from objective4 waypoint17)
	(visible_from objective4 waypoint18)
	(visible_from objective4 waypoint20)
	(visible_from objective4 waypoint21)
	(visible_from objective4 waypoint23)
	(visible_from objective4 waypoint25)
	(visible_from objective4 waypoint26)
	(visible_from objective4 waypoint27)
	(visible_from objective4 waypoint28)
	(visible_from objective4 waypoint29)
	(visible_from objective4 waypoint31)
	(visible_from objective4 waypoint32)
	(visible_from objective4 waypoint33)
	(visible_from objective4 waypoint34)
	(visible_from objective4 waypoint35)
	(visible_from objective4 waypoint37)
	(visible_from objective4 waypoint38)
	(visible_from objective4 waypoint39)
	(visible_from objective4 waypoint40)
	(visible_from objective4 waypoint41)
	(visible_from objective4 waypoint43)
	(visible_from objective4 waypoint45)
	(visible_from objective4 waypoint46)
	(visible_from objective4 waypoint48)
	(visible_from objective4 waypoint49)
	(visible_from objective4 waypoint50)
	(visible_from objective4 waypoint51)
	(visible_from objective4 waypoint54)
	(visible_from objective4 waypoint55)
	(visible_from objective4 waypoint56)
	(visible_from objective4 waypoint58)
	(visible_from objective5 waypoint0)
	(visible_from objective5 waypoint1)
	(visible_from objective5 waypoint4)
	(visible_from objective5 waypoint6)
	(visible_from objective5 waypoint7)
	(visible_from objective5 waypoint8)
	(visible_from objective5 waypoint9)
	(visible_from objective5 waypoint10)
	(visible_from objective5 waypoint12)
	(visible_from objective5 waypoint19)
	(visible_from objective5 waypoint20)
	(visible_from objective5 waypoint21)
	(visible_from objective5 waypoint23)
	(visible_from objective5 waypoint27)
	(visible_from objective5 waypoint28)
	(visible_from objective5 waypoint29)
	(visible_from objective5 waypoint30)
	(visible_from objective5 waypoint32)
	(visible_from objective5 waypoint33)
	(visible_from objective5 waypoint34)
	(visible_from objective5 waypoint35)
	(visible_from objective5 waypoint36)
	(visible_from objective5 waypoint37)
	(visible_from objective5 waypoint38)
	(visible_from objective5 waypoint43)
	(visible_from objective5 waypoint49)
	(visible_from objective5 waypoint50)
	(visible_from objective5 waypoint51)
	(visible_from objective5 waypoint53)
	(visible_from objective5 waypoint54)
	(visible_from objective5 waypoint57)
	(visible_from objective5 waypoint58)
	(visible_from objective5 waypoint59)
	(visible_from objective6 waypoint4)
	(visible_from objective6 waypoint6)
	(visible_from objective6 waypoint7)
	(visible_from objective6 waypoint12)
	(visible_from objective6 waypoint17)
	(visible_from objective6 waypoint19)
	(visible_from objective6 waypoint20)
	(visible_from objective6 waypoint24)
	(visible_from objective6 waypoint26)
	(visible_from objective6 waypoint27)
	(visible_from objective6 waypoint30)
	(visible_from objective6 waypoint33)
	(visible_from objective6 waypoint38)
	(visible_from objective6 waypoint43)
	(visible_from objective6 waypoint46)
	(visible_from objective6 waypoint53)
	(visible_from objective6 waypoint56)
	(visible_from objective6 waypoint57)
	(visible_from objective7 waypoint3)
	(visible_from objective7 waypoint4)
	(visible_from objective7 waypoint5)
	(visible_from objective7 waypoint7)
	(visible_from objective7 waypoint10)
	(visible_from objective7 waypoint13)
	(visible_from objective7 waypoint15)
	(visible_from objective7 waypoint18)
	(visible_from objective7 waypoint23)
	(visible_from objective7 waypoint28)
	(visible_from objective7 waypoint30)
	(visible_from objective7 waypoint31)
	(visible_from objective7 waypoint33)
	(visible_from objective7 waypoint34)
	(visible_from objective7 waypoint35)
	(visible_from objective7 waypoint36)
	(visible_from objective7 waypoint38)
	(visible_from objective7 waypoint40)
	(visible_from objective7 waypoint41)
	(visible_from objective7 waypoint44)
	(visible_from objective7 waypoint45)
	(visible_from objective7 waypoint46)
	(visible_from objective7 waypoint47)
	(visible_from objective7 waypoint48)
	(visible_from objective7 waypoint49)
	(visible_from objective7 waypoint50)
	(visible_from objective7 waypoint51)
	(visible_from objective7 waypoint52)
	(visible_from objective7 waypoint53)
	(visible_from objective7 waypoint55)
	(visible_from objective7 waypoint57)
	(visible_from objective7 waypoint59)
)

(:goal (and
(communicated_soil_data waypoint47)
(communicated_soil_data waypoint15)
(communicated_soil_data waypoint21)
(communicated_soil_data waypoint52)
(communicated_soil_data waypoint41)
(communicated_soil_data waypoint7)
(communicated_soil_data waypoint39)
(communicated_soil_data waypoint29)
(communicated_soil_data waypoint58)
(communicated_soil_data waypoint18)
(communicated_soil_data waypoint16)
(communicated_soil_data waypoint0)
(communicated_soil_data waypoint6)
(communicated_soil_data waypoint31)
(communicated_soil_data waypoint2)
(communicated_soil_data waypoint40)
(communicated_soil_data waypoint46)
(communicated_soil_data waypoint17)
(communicated_rock_data waypoint33)
(communicated_rock_data waypoint14)
(communicated_rock_data waypoint46)
(communicated_rock_data waypoint42)
(communicated_rock_data waypoint10)
(communicated_rock_data waypoint37)
(communicated_rock_data waypoint52)
(communicated_rock_data waypoint40)
(communicated_rock_data waypoint5)
(communicated_rock_data waypoint45)
(communicated_rock_data waypoint7)
(communicated_rock_data waypoint58)
(communicated_rock_data waypoint16)
(communicated_rock_data waypoint3)
(communicated_rock_data waypoint51)
(communicated_image_data objective6 low_res)
(communicated_image_data objective3 low_res)
(communicated_image_data objective7 low_res)
(communicated_image_data objective2 low_res)
(communicated_image_data objective2 colour)
(communicated_image_data objective5 colour)
(communicated_image_data objective3 colour)
(communicated_image_data objective4 colour)
(communicated_image_data objective5 high_res)
(communicated_image_data objective0 high_res)
(communicated_image_data objective3 high_res)
	)
)
)
