(define (problem roverprob10) (:domain Rover)
(:objects
	general - Lander
	colour high_res low_res - Mode
	rover0 rover1 rover2 rover3 - Rover
	rover0store rover1store rover2store rover3store - Store
	waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 waypoint7 waypoint8 waypoint9 waypoint10 waypoint11 waypoint12 waypoint13 waypoint14 waypoint15 waypoint16 waypoint17 waypoint18 waypoint19 waypoint20 waypoint21 waypoint22 waypoint23 waypoint24 waypoint25 waypoint26 waypoint27 waypoint28 waypoint29 waypoint30 waypoint31 waypoint32 waypoint33 waypoint34 waypoint35 waypoint36 waypoint37 waypoint38 waypoint39 waypoint40 waypoint41 waypoint42 waypoint43 waypoint44 waypoint45 waypoint46 waypoint47 waypoint48 waypoint49 waypoint50 waypoint51 waypoint52 waypoint53 waypoint54 waypoint55 waypoint56 waypoint57 waypoint58 waypoint59 - Waypoint
	camera0 camera1 camera2 camera3 camera4 camera5 camera6 - Camera
	objective0 objective1 objective2 objective3 objective4 objective5 objective6 objective7 - Objective
	)
(:init
	(visible waypoint0 waypoint11)
	(visible waypoint11 waypoint0)
	(visible waypoint0 waypoint41)
	(visible waypoint41 waypoint0)
	(visible waypoint0 waypoint52)
	(visible waypoint52 waypoint0)
	(visible waypoint1 waypoint18)
	(visible waypoint18 waypoint1)
	(visible waypoint1 waypoint20)
	(visible waypoint20 waypoint1)
	(visible waypoint1 waypoint21)
	(visible waypoint21 waypoint1)
	(visible waypoint1 waypoint23)
	(visible waypoint23 waypoint1)
	(visible waypoint1 waypoint27)
	(visible waypoint27 waypoint1)
	(visible waypoint1 waypoint31)
	(visible waypoint31 waypoint1)
	(visible waypoint1 waypoint45)
	(visible waypoint45 waypoint1)
	(visible waypoint1 waypoint52)
	(visible waypoint52 waypoint1)
	(visible waypoint2 waypoint13)
	(visible waypoint13 waypoint2)
	(visible waypoint2 waypoint16)
	(visible waypoint16 waypoint2)
	(visible waypoint2 waypoint21)
	(visible waypoint21 waypoint2)
	(visible waypoint2 waypoint31)
	(visible waypoint31 waypoint2)
	(visible waypoint2 waypoint56)
	(visible waypoint56 waypoint2)
	(visible waypoint3 waypoint2)
	(visible waypoint2 waypoint3)
	(visible waypoint3 waypoint5)
	(visible waypoint5 waypoint3)
	(visible waypoint3 waypoint9)
	(visible waypoint9 waypoint3)
	(visible waypoint3 waypoint38)
	(visible waypoint38 waypoint3)
	(visible waypoint4 waypoint18)
	(visible waypoint18 waypoint4)
	(visible waypoint4 waypoint48)
	(visible waypoint48 waypoint4)
	(visible waypoint4 waypoint54)
	(visible waypoint54 waypoint4)
	(visible waypoint4 waypoint57)
	(visible waypoint57 waypoint4)
	(visible waypoint5 waypoint2)
	(visible waypoint2 waypoint5)
	(visible waypoint5 waypoint12)
	(visible waypoint12 waypoint5)
	(visible waypoint5 waypoint22)
	(visible waypoint22 waypoint5)
	(visible waypoint5 waypoint26)
	(visible waypoint26 waypoint5)
	(visible waypoint5 waypoint31)
	(visible waypoint31 waypoint5)
	(visible waypoint6 waypoint11)
	(visible waypoint11 waypoint6)
	(visible waypoint6 waypoint23)
	(visible waypoint23 waypoint6)
	(visible waypoint6 waypoint39)
	(visible waypoint39 waypoint6)
	(visible waypoint7 waypoint5)
	(visible waypoint5 waypoint7)
	(visible waypoint7 waypoint11)
	(visible waypoint11 waypoint7)
	(visible waypoint7 waypoint13)
	(visible waypoint13 waypoint7)
	(visible waypoint7 waypoint33)
	(visible waypoint33 waypoint7)
	(visible waypoint7 waypoint53)
	(visible waypoint53 waypoint7)
	(visible waypoint8 waypoint0)
	(visible waypoint0 waypoint8)
	(visible waypoint8 waypoint3)
	(visible waypoint3 waypoint8)
	(visible waypoint8 waypoint7)
	(visible waypoint7 waypoint8)
	(visible waypoint8 waypoint11)
	(visible waypoint11 waypoint8)
	(visible waypoint8 waypoint42)
	(visible waypoint42 waypoint8)
	(visible waypoint8 waypoint45)
	(visible waypoint45 waypoint8)
	(visible waypoint8 waypoint50)
	(visible waypoint50 waypoint8)
	(visible waypoint9 waypoint0)
	(visible waypoint0 waypoint9)
	(visible waypoint9 waypoint1)
	(visible waypoint1 waypoint9)
	(visible waypoint9 waypoint25)
	(visible waypoint25 waypoint9)
	(visible waypoint10 waypoint26)
	(visible waypoint26 waypoint10)
	(visible waypoint10 waypoint36)
	(visible waypoint36 waypoint10)
	(visible waypoint10 waypoint40)
	(visible waypoint40 waypoint10)
	(visible waypoint10 waypoint59)
	(visible waypoint59 waypoint10)
	(visible waypoint11 waypoint38)
	(visible waypoint38 waypoint11)
	(visible waypoint11 waypoint54)
	(visible waypoint54 waypoint11)
	(visible waypoint12 waypoint0)
	(visible waypoint0 waypoint12)
	(visible waypoint12 waypoint2)
	(visible waypoint2 waypoint12)
	(visible waypoint12 waypoint6)
	(visible waypoint6 waypoint12)
	(visible waypoint12 waypoint10)
	(visible waypoint10 waypoint12)
	(visible waypoint12 waypoint11)
	(visible waypoint11 waypoint12)
	(visible waypoint12 waypoint31)
	(visible waypoint31 waypoint12)
	(visible waypoint13 waypoint12)
	(visible waypoint12 waypoint13)
	(visible waypoint13 waypoint16)
	(visible waypoint16 waypoint13)
	(visible waypoint13 waypoint41)
	(visible waypoint41 waypoint13)
	(visible waypoint13 waypoint59)
	(visible waypoint59 waypoint13)
	(visible waypoint14 waypoint9)
	(visible waypoint9 waypoint14)
	(visible waypoint14 waypoint25)
	(visible waypoint25 waypoint14)
	(visible waypoint14 waypoint31)
	(visible waypoint31 waypoint14)
	(visible waypoint14 waypoint39)
	(visible waypoint39 waypoint14)
	(visible waypoint15 waypoint0)
	(visible waypoint0 waypoint15)
	(visible waypoint15 waypoint18)
	(visible waypoint18 waypoint15)
	(visible waypoint15 waypoint29)
	(visible waypoint29 waypoint15)
	(visible waypoint15 waypoint47)
	(visible waypoint47 waypoint15)
	(visible waypoint15 waypoint51)
	(visible waypoint51 waypoint15)
	(visible waypoint15 waypoint59)
	(visible waypoint59 waypoint15)
	(visible waypoint16 waypoint3)
	(visible waypoint3 waypoint16)
	(visible waypoint16 waypoint4)
	(visible waypoint4 waypoint16)
	(visible waypoint16 waypoint5)
	(visible waypoint5 waypoint16)
	(visible waypoint16 waypoint26)
	(visible waypoint26 waypoint16)
	(visible waypoint16 waypoint43)
	(visible waypoint43 waypoint16)
	(visible waypoint16 waypoint49)
	(visible waypoint49 waypoint16)
	(visible waypoint17 waypoint9)
	(visible waypoint9 waypoint17)
	(visible waypoint17 waypoint24)
	(visible waypoint24 waypoint17)
	(visible waypoint17 waypoint35)
	(visible waypoint35 waypoint17)
	(visible waypoint17 waypoint55)
	(visible waypoint55 waypoint17)
	(visible waypoint17 waypoint56)
	(visible waypoint56 waypoint17)
	(visible waypoint18 waypoint7)
	(visible waypoint7 waypoint18)
	(visible waypoint18 waypoint12)
	(visible waypoint12 waypoint18)
	(visible waypoint19 waypoint3)
	(visible waypoint3 waypoint19)
	(visible waypoint19 waypoint30)
	(visible waypoint30 waypoint19)
	(visible waypoint19 waypoint32)
	(visible waypoint32 waypoint19)
	(visible waypoint19 waypoint39)
	(visible waypoint39 waypoint19)
	(visible waypoint19 waypoint53)
	(visible waypoint53 waypoint19)
	(visible waypoint20 waypoint2)
	(visible waypoint2 waypoint20)
	(visible waypoint20 waypoint15)
	(visible waypoint15 waypoint20)
	(visible waypoint20 waypoint19)
	(visible waypoint19 waypoint20)
	(visible waypoint20 waypoint28)
	(visible waypoint28 waypoint20)
	(visible waypoint20 waypoint34)
	(visible waypoint34 waypoint20)
	(visible waypoint21 waypoint56)
	(visible waypoint56 waypoint21)
	(visible waypoint21 waypoint57)
	(visible waypoint57 waypoint21)
	(visible waypoint22 waypoint12)
	(visible waypoint12 waypoint22)
	(visible waypoint22 waypoint29)
	(visible waypoint29 waypoint22)
	(visible waypoint22 waypoint49)
	(visible waypoint49 waypoint22)
	(visible waypoint23 waypoint2)
	(visible waypoint2 waypoint23)
	(visible waypoint23 waypoint10)
	(visible waypoint10 waypoint23)
	(visible waypoint23 waypoint16)
	(visible waypoint16 waypoint23)
	(visible waypoint23 waypoint41)
	(visible waypoint41 waypoint23)
	(visible waypoint23 waypoint44)
	(visible waypoint44 waypoint23)
	(visible waypoint23 waypoint49)
	(visible waypoint49 waypoint23)
	(visible waypoint24 waypoint6)
	(visible waypoint6 waypoint24)
	(visible waypoint24 waypoint10)
	(visible waypoint10 waypoint24)
	(visible waypoint24 waypoint19)
	(visible waypoint19 waypoint24)
	(visible waypoint24 waypoint55)
	(visible waypoint55 waypoint24)
	(visible waypoint25 waypoint8)
	(visible waypoint8 waypoint25)
	(visible waypoint25 waypoint13)
	(visible waypoint13 waypoint25)
	(visible waypoint25 waypoint20)
	(visible waypoint20 waypoint25)
	(visible waypoint25 waypoint29)
	(visible waypoint29 waypoint25)
	(visible waypoint25 waypoint47)
	(visible waypoint47 waypoint25)
	(visible waypoint26 waypoint13)
	(visible waypoint13 waypoint26)
	(visible waypoint26 waypoint32)
	(visible waypoint32 waypoint26)
	(visible waypoint26 waypoint33)
	(visible waypoint33 waypoint26)
	(visible waypoint26 waypoint39)
	(visible waypoint39 waypoint26)
	(visible waypoint26 waypoint53)
	(visible waypoint53 waypoint26)
	(visible waypoint27 waypoint11)
	(visible waypoint11 waypoint27)
	(visible waypoint27 waypoint17)
	(visible waypoint17 waypoint27)
	(visible waypoint27 waypoint30)
	(visible waypoint30 waypoint27)
	(visible waypoint27 waypoint41)
	(visible waypoint41 waypoint27)
	(visible waypoint27 waypoint45)
	(visible waypoint45 waypoint27)
	(visible waypoint28 waypoint4)
	(visible waypoint4 waypoint28)
	(visible waypoint28 waypoint17)
	(visible waypoint17 waypoint28)
	(visible waypoint28 waypoint33)
	(visible waypoint33 waypoint28)
	(visible waypoint29 waypoint33)
	(visible waypoint33 waypoint29)
	(visible waypoint29 waypoint43)
	(visible waypoint43 waypoint29)
	(visible waypoint29 waypoint54)
	(visible waypoint54 waypoint29)
	(visible waypoint30 waypoint1)
	(visible waypoint1 waypoint30)
	(visible waypoint30 waypoint10)
	(visible waypoint10 waypoint30)
	(visible waypoint30 waypoint36)
	(visible waypoint36 waypoint30)
	(visible waypoint31 waypoint22)
	(visible waypoint22 waypoint31)
	(visible waypoint31 waypoint37)
	(visible waypoint37 waypoint31)
	(visible waypoint31 waypoint59)
	(visible waypoint59 waypoint31)
	(visible waypoint32 waypoint9)
	(visible waypoint9 waypoint32)
	(visible waypoint32 waypoint10)
	(visible waypoint10 waypoint32)
	(visible waypoint32 waypoint15)
	(visible waypoint15 waypoint32)
	(visible waypoint32 waypoint35)
	(visible waypoint35 waypoint32)
	(visible waypoint32 waypoint58)
	(visible waypoint58 waypoint32)
	(visible waypoint33 waypoint20)
	(visible waypoint20 waypoint33)
	(visible waypoint33 waypoint36)
	(visible waypoint36 waypoint33)
	(visible waypoint33 waypoint53)
	(visible waypoint53 waypoint33)
	(visible waypoint33 waypoint56)
	(visible waypoint56 waypoint33)
	(visible waypoint34 waypoint13)
	(visible waypoint13 waypoint34)
	(visible waypoint34 waypoint17)
	(visible waypoint17 waypoint34)
	(visible waypoint34 waypoint28)
	(visible waypoint28 waypoint34)
	(visible waypoint34 waypoint30)
	(visible waypoint30 waypoint34)
	(visible waypoint34 waypoint44)
	(visible waypoint44 waypoint34)
	(visible waypoint35 waypoint18)
	(visible waypoint18 waypoint35)
	(visible waypoint35 waypoint23)
	(visible waypoint23 waypoint35)
	(visible waypoint35 waypoint25)
	(visible waypoint25 waypoint35)
	(visible waypoint35 waypoint36)
	(visible waypoint36 waypoint35)
	(visible waypoint35 waypoint38)
	(visible waypoint38 waypoint35)
	(visible waypoint35 waypoint40)
	(visible waypoint40 waypoint35)
	(visible waypoint35 waypoint58)
	(visible waypoint58 waypoint35)
	(visible waypoint36 waypoint14)
	(visible waypoint14 waypoint36)
	(visible waypoint36 waypoint17)
	(visible waypoint17 waypoint36)
	(visible waypoint36 waypoint27)
	(visible waypoint27 waypoint36)
	(visible waypoint36 waypoint47)
	(visible waypoint47 waypoint36)
	(visible waypoint36 waypoint57)
	(visible waypoint57 waypoint36)
	(visible waypoint36 waypoint59)
	(visible waypoint59 waypoint36)
	(visible waypoint37 waypoint3)
	(visible waypoint3 waypoint37)
	(visible waypoint37 waypoint5)
	(visible waypoint5 waypoint37)
	(visible waypoint37 waypoint18)
	(visible waypoint18 waypoint37)
	(visible waypoint37 waypoint24)
	(visible waypoint24 waypoint37)
	(visible waypoint38 waypoint10)
	(visible waypoint10 waypoint38)
	(visible waypoint38 waypoint18)
	(visible waypoint18 waypoint38)
	(visible waypoint38 waypoint22)
	(visible waypoint22 waypoint38)
	(visible waypoint38 waypoint55)
	(visible waypoint55 waypoint38)
	(visible waypoint38 waypoint58)
	(visible waypoint58 waypoint38)
	(visible waypoint39 waypoint13)
	(visible waypoint13 waypoint39)
	(visible waypoint39 waypoint45)
	(visible waypoint45 waypoint39)
	(visible waypoint39 waypoint49)
	(visible waypoint49 waypoint39)
	(visible waypoint39 waypoint55)
	(visible waypoint55 waypoint39)
	(visible waypoint39 waypoint58)
	(visible waypoint58 waypoint39)
	(visible waypoint40 waypoint4)
	(visible waypoint4 waypoint40)
	(visible waypoint40 waypoint15)
	(visible waypoint15 waypoint40)
	(visible waypoint40 waypoint20)
	(visible waypoint20 waypoint40)
	(visible waypoint40 waypoint27)
	(visible waypoint27 waypoint40)
	(visible waypoint40 waypoint31)
	(visible waypoint31 waypoint40)
	(visible waypoint41 waypoint2)
	(visible waypoint2 waypoint41)
	(visible waypoint41 waypoint11)
	(visible waypoint11 waypoint41)
	(visible waypoint41 waypoint24)
	(visible waypoint24 waypoint41)
	(visible waypoint41 waypoint43)
	(visible waypoint43 waypoint41)
	(visible waypoint42 waypoint2)
	(visible waypoint2 waypoint42)
	(visible waypoint42 waypoint13)
	(visible waypoint13 waypoint42)
	(visible waypoint42 waypoint45)
	(visible waypoint45 waypoint42)
	(visible waypoint42 waypoint46)
	(visible waypoint46 waypoint42)
	(visible waypoint42 waypoint55)
	(visible waypoint55 waypoint42)
	(visible waypoint43 waypoint9)
	(visible waypoint9 waypoint43)
	(visible waypoint43 waypoint18)
	(visible waypoint18 waypoint43)
	(visible waypoint43 waypoint20)
	(visible waypoint20 waypoint43)
	(visible waypoint44 waypoint0)
	(visible waypoint0 waypoint44)
	(visible waypoint44 waypoint2)
	(visible waypoint2 waypoint44)
	(visible waypoint44 waypoint4)
	(visible waypoint4 waypoint44)
	(visible waypoint44 waypoint7)
	(visible waypoint7 waypoint44)
	(visible waypoint44 waypoint15)
	(visible waypoint15 waypoint44)
	(visible waypoint44 waypoint19)
	(visible waypoint19 waypoint44)
	(visible waypoint44 waypoint36)
	(visible waypoint36 waypoint44)
	(visible waypoint45 waypoint13)
	(visible waypoint13 waypoint45)
	(visible waypoint45 waypoint16)
	(visible waypoint16 waypoint45)
	(visible waypoint45 waypoint41)
	(visible waypoint41 waypoint45)
	(visible waypoint46 waypoint7)
	(visible waypoint7 waypoint46)
	(visible waypoint46 waypoint36)
	(visible waypoint36 waypoint46)
	(visible waypoint46 waypoint44)
	(visible waypoint44 waypoint46)
	(visible waypoint46 waypoint49)
	(visible waypoint49 waypoint46)
	(visible waypoint46 waypoint50)
	(visible waypoint50 waypoint46)
	(visible waypoint47 waypoint45)
	(visible waypoint45 waypoint47)
	(visible waypoint47 waypoint51)
	(visible waypoint51 waypoint47)
	(visible waypoint47 waypoint57)
	(visible waypoint57 waypoint47)
	(visible waypoint48 waypoint1)
	(visible waypoint1 waypoint48)
	(visible waypoint48 waypoint13)
	(visible waypoint13 waypoint48)
	(visible waypoint48 waypoint17)
	(visible waypoint17 waypoint48)
	(visible waypoint48 waypoint31)
	(visible waypoint31 waypoint48)
	(visible waypoint48 waypoint54)
	(visible waypoint54 waypoint48)
	(visible waypoint49 waypoint3)
	(visible waypoint3 waypoint49)
	(visible waypoint49 waypoint11)
	(visible waypoint11 waypoint49)
	(visible waypoint49 waypoint12)
	(visible waypoint12 waypoint49)
	(visible waypoint49 waypoint51)
	(visible waypoint51 waypoint49)
	(visible waypoint50 waypoint5)
	(visible waypoint5 waypoint50)
	(visible waypoint50 waypoint24)
	(visible waypoint24 waypoint50)
	(visible waypoint50 waypoint27)
	(visible waypoint27 waypoint50)
	(visible waypoint50 waypoint47)
	(visible waypoint47 waypoint50)
	(visible waypoint50 waypoint51)
	(visible waypoint51 waypoint50)
	(visible waypoint50 waypoint58)
	(visible waypoint58 waypoint50)
	(visible waypoint50 waypoint59)
	(visible waypoint59 waypoint50)
	(visible waypoint51 waypoint23)
	(visible waypoint23 waypoint51)
	(visible waypoint51 waypoint39)
	(visible waypoint39 waypoint51)
	(visible waypoint51 waypoint45)
	(visible waypoint45 waypoint51)
	(visible waypoint52 waypoint3)
	(visible waypoint3 waypoint52)
	(visible waypoint52 waypoint13)
	(visible waypoint13 waypoint52)
	(visible waypoint52 waypoint17)
	(visible waypoint17 waypoint52)
	(visible waypoint52 waypoint20)
	(visible waypoint20 waypoint52)
	(visible waypoint52 waypoint28)
	(visible waypoint28 waypoint52)
	(visible waypoint52 waypoint33)
	(visible waypoint33 waypoint52)
	(visible waypoint52 waypoint35)
	(visible waypoint35 waypoint52)
	(visible waypoint52 waypoint44)
	(visible waypoint44 waypoint52)
	(visible waypoint52 waypoint49)
	(visible waypoint49 waypoint52)
	(visible waypoint53 waypoint13)
	(visible waypoint13 waypoint53)
	(visible waypoint53 waypoint30)
	(visible waypoint30 waypoint53)
	(visible waypoint53 waypoint32)
	(visible waypoint32 waypoint53)
	(visible waypoint53 waypoint43)
	(visible waypoint43 waypoint53)
	(visible waypoint54 waypoint15)
	(visible waypoint15 waypoint54)
	(visible waypoint54 waypoint25)
	(visible waypoint25 waypoint54)
	(visible waypoint54 waypoint41)
	(visible waypoint41 waypoint54)
	(visible waypoint54 waypoint47)
	(visible waypoint47 waypoint54)
	(visible waypoint54 waypoint55)
	(visible waypoint55 waypoint54)
	(visible waypoint55 waypoint3)
	(visible waypoint3 waypoint55)
	(visible waypoint55 waypoint26)
	(visible waypoint26 waypoint55)
	(visible waypoint55 waypoint29)
	(visible waypoint29 waypoint55)
	(visible waypoint55 waypoint30)
	(visible waypoint30 waypoint55)
	(visible waypoint55 waypoint40)
	(visible waypoint40 waypoint55)
	(visible waypoint55 waypoint51)
	(visible waypoint51 waypoint55)
	(visible waypoint56 waypoint14)
	(visible waypoint14 waypoint56)
	(visible waypoint56 waypoint46)
	(visible waypoint46 waypoint56)
	(visible waypoint57 waypoint8)
	(visible waypoint8 waypoint57)
	(visible waypoint57 waypoint11)
	(visible waypoint11 waypoint57)
	(visible waypoint57 waypoint20)
	(visible waypoint20 waypoint57)
	(visible waypoint57 waypoint43)
	(visible waypoint43 waypoint57)
	(visible waypoint57 waypoint45)
	(visible waypoint45 waypoint57)
	(visible waypoint58 waypoint13)
	(visible waypoint13 waypoint58)
	(visible waypoint58 waypoint22)
	(visible waypoint22 waypoint58)
	(visible waypoint58 waypoint26)
	(visible waypoint26 waypoint58)
	(visible waypoint59 waypoint6)
	(visible waypoint6 waypoint59)
	(visible waypoint59 waypoint7)
	(visible waypoint7 waypoint59)
	(visible waypoint59 waypoint44)
	(visible waypoint44 waypoint59)
	(visible waypoint59 waypoint48)
	(visible waypoint48 waypoint59)
	(visible waypoint59 waypoint49)
	(visible waypoint49 waypoint59)
	(visible waypoint59 waypoint51)
	(visible waypoint51 waypoint59)
	(visible waypoint59 waypoint52)
	(visible waypoint52 waypoint59)
	(visible waypoint59 waypoint58)
	(visible waypoint58 waypoint59)
	(at_rock_sample waypoint0)
	(at_soil_sample waypoint1)
	(at_rock_sample waypoint1)
	(at_soil_sample waypoint2)
	(at_soil_sample waypoint3)
	(at_rock_sample waypoint3)
	(at_soil_sample waypoint5)
	(at_rock_sample waypoint6)
	(at_soil_sample waypoint7)
	(at_rock_sample waypoint7)
	(at_rock_sample waypoint8)
	(at_soil_sample waypoint9)
	(at_rock_sample waypoint9)
	(at_rock_sample waypoint11)
	(at_rock_sample waypoint12)
	(at_soil_sample waypoint13)
	(at_soil_sample waypoint16)
	(at_soil_sample waypoint17)
	(at_rock_sample waypoint18)
	(at_soil_sample waypoint20)
	(at_rock_sample waypoint21)
	(at_soil_sample waypoint22)
	(at_rock_sample waypoint22)
	(at_rock_sample waypoint24)
	(at_soil_sample waypoint25)
	(at_rock_sample waypoint25)
	(at_soil_sample waypoint26)
	(at_rock_sample waypoint26)
	(at_soil_sample waypoint27)
	(at_soil_sample waypoint28)
	(at_rock_sample waypoint28)
	(at_soil_sample waypoint30)
	(at_rock_sample waypoint30)
	(at_soil_sample waypoint31)
	(at_soil_sample waypoint32)
	(at_soil_sample waypoint33)
	(at_rock_sample waypoint33)
	(at_rock_sample waypoint34)
	(at_soil_sample waypoint37)
	(at_rock_sample waypoint38)
	(at_rock_sample waypoint41)
	(at_soil_sample waypoint44)
	(at_rock_sample waypoint44)
	(at_soil_sample waypoint45)
	(at_rock_sample waypoint45)
	(at_rock_sample waypoint46)
	(at_soil_sample waypoint47)
	(at_rock_sample waypoint47)
	(at_soil_sample waypoint48)
	(at_rock_sample waypoint48)
	(at_soil_sample waypoint49)
	(at_rock_sample waypoint50)
	(at_soil_sample waypoint51)
	(at_rock_sample waypoint51)
	(at_soil_sample waypoint53)
	(at_rock_sample waypoint53)
	(at_soil_sample waypoint54)
	(at_soil_sample waypoint55)
	(at_soil_sample waypoint57)
	(at_soil_sample waypoint59)
	(at_lander general waypoint37)
	(channel_free general)
	(at rover0 waypoint11)
	(available rover0)
	(store_of rover0store rover0)
	(empty rover0store)
	(equipped_for_soil_analysis rover0)
	(equipped_for_rock_analysis rover0)
	(equipped_for_imaging rover0)
	(can_traverse rover0 waypoint11 waypoint0)
	(can_traverse rover0 waypoint0 waypoint11)
	(can_traverse rover0 waypoint11 waypoint7)
	(can_traverse rover0 waypoint7 waypoint11)
	(can_traverse rover0 waypoint11 waypoint8)
	(can_traverse rover0 waypoint8 waypoint11)
	(can_traverse rover0 waypoint11 waypoint27)
	(can_traverse rover0 waypoint27 waypoint11)
	(can_traverse rover0 waypoint11 waypoint49)
	(can_traverse rover0 waypoint49 waypoint11)
	(can_traverse rover0 waypoint11 waypoint57)
	(can_traverse rover0 waypoint57 waypoint11)
	(can_traverse rover0 waypoint0 waypoint9)
	(can_traverse rover0 waypoint9 waypoint0)
	(can_traverse rover0 waypoint0 waypoint12)
	(can_traverse rover0 waypoint12 waypoint0)
	(can_traverse rover0 waypoint0 waypoint15)
	(can_traverse rover0 waypoint15 waypoint0)
	(can_traverse rover0 waypoint0 waypoint41)
	(can_traverse rover0 waypoint41 waypoint0)
	(can_traverse rover0 waypoint0 waypoint44)
	(can_traverse rover0 waypoint44 waypoint0)
	(can_traverse rover0 waypoint0 waypoint52)
	(can_traverse rover0 waypoint52 waypoint0)
	(can_traverse rover0 waypoint7 waypoint5)
	(can_traverse rover0 waypoint5 waypoint7)
	(can_traverse rover0 waypoint7 waypoint13)
	(can_traverse rover0 waypoint13 waypoint7)
	(can_traverse rover0 waypoint7 waypoint18)
	(can_traverse rover0 waypoint18 waypoint7)
	(can_traverse rover0 waypoint7 waypoint33)
	(can_traverse rover0 waypoint33 waypoint7)
	(can_traverse rover0 waypoint7 waypoint53)
	(can_traverse rover0 waypoint53 waypoint7)
	(can_traverse rover0 waypoint7 waypoint59)
	(can_traverse rover0 waypoint59 waypoint7)
	(can_traverse rover0 waypoint8 waypoint3)
	(can_traverse rover0 waypoint3 waypoint8)
	(can_traverse rover0 waypoint8 waypoint42)
	(can_traverse rover0 waypoint42 waypoint8)
	(can_traverse rover0 waypoint27 waypoint1)
	(can_traverse rover0 waypoint1 waypoint27)
	(can_traverse rover0 waypoint27 waypoint17)
	(can_traverse rover0 waypoint17 waypoint27)
	(can_traverse rover0 waypoint27 waypoint30)
	(can_traverse rover0 waypoint30 waypoint27)
	(can_traverse rover0 waypoint27 waypoint36)
	(can_traverse rover0 waypoint36 waypoint27)
	(can_traverse rover0 waypoint27 waypoint40)
	(can_traverse rover0 waypoint40 waypoint27)
	(can_traverse rover0 waypoint27 waypoint45)
	(can_traverse rover0 waypoint45 waypoint27)
	(can_traverse rover0 waypoint27 waypoint50)
	(can_traverse rover0 waypoint50 waypoint27)
	(can_traverse rover0 waypoint49 waypoint16)
	(can_traverse rover0 waypoint16 waypoint49)
	(can_traverse rover0 waypoint49 waypoint22)
	(can_traverse rover0 waypoint22 waypoint49)
	(can_traverse rover0 waypoint49 waypoint39)
	(can_traverse rover0 waypoint39 waypoint49)
	(can_traverse rover0 waypoint49 waypoint46)
	(can_traverse rover0 waypoint46 waypoint49)
	(can_traverse rover0 waypoint49 waypoint51)
	(can_traverse rover0 waypoint51 waypoint49)
	(can_traverse rover0 waypoint57 waypoint4)
	(can_traverse rover0 waypoint4 waypoint57)
	(can_traverse rover0 waypoint57 waypoint20)
	(can_traverse rover0 waypoint20 waypoint57)
	(can_traverse rover0 waypoint57 waypoint21)
	(can_traverse rover0 waypoint21 waypoint57)
	(can_traverse rover0 waypoint57 waypoint43)
	(can_traverse rover0 waypoint43 waypoint57)
	(can_traverse rover0 waypoint57 waypoint47)
	(can_traverse rover0 waypoint47 waypoint57)
	(can_traverse rover0 waypoint9 waypoint14)
	(can_traverse rover0 waypoint14 waypoint9)
	(can_traverse rover0 waypoint9 waypoint25)
	(can_traverse rover0 waypoint25 waypoint9)
	(can_traverse rover0 waypoint9 waypoint32)
	(can_traverse rover0 waypoint32 waypoint9)
	(can_traverse rover0 waypoint12 waypoint2)
	(can_traverse rover0 waypoint2 waypoint12)
	(can_traverse rover0 waypoint12 waypoint10)
	(can_traverse rover0 waypoint10 waypoint12)
	(can_traverse rover0 waypoint12 waypoint31)
	(can_traverse rover0 waypoint31 waypoint12)
	(can_traverse rover0 waypoint15 waypoint54)
	(can_traverse rover0 waypoint54 waypoint15)
	(can_traverse rover0 waypoint41 waypoint23)
	(can_traverse rover0 waypoint23 waypoint41)
	(can_traverse rover0 waypoint41 waypoint24)
	(can_traverse rover0 waypoint24 waypoint41)
	(can_traverse rover0 waypoint44 waypoint19)
	(can_traverse rover0 waypoint19 waypoint44)
	(can_traverse rover0 waypoint52 waypoint28)
	(can_traverse rover0 waypoint28 waypoint52)
	(can_traverse rover0 waypoint52 waypoint35)
	(can_traverse rover0 waypoint35 waypoint52)
	(can_traverse rover0 waypoint5 waypoint26)
	(can_traverse rover0 waypoint26 waypoint5)
	(can_traverse rover0 waypoint5 waypoint37)
	(can_traverse rover0 waypoint37 waypoint5)
	(can_traverse rover0 waypoint13 waypoint34)
	(can_traverse rover0 waypoint34 waypoint13)
	(can_traverse rover0 waypoint13 waypoint58)
	(can_traverse rover0 waypoint58 waypoint13)
	(can_traverse rover0 waypoint18 waypoint38)
	(can_traverse rover0 waypoint38 waypoint18)
	(can_traverse rover0 waypoint33 waypoint29)
	(can_traverse rover0 waypoint29 waypoint33)
	(can_traverse rover0 waypoint33 waypoint56)
	(can_traverse rover0 waypoint56 waypoint33)
	(can_traverse rover0 waypoint59 waypoint6)
	(can_traverse rover0 waypoint6 waypoint59)
	(can_traverse rover0 waypoint59 waypoint48)
	(can_traverse rover0 waypoint48 waypoint59)
	(can_traverse rover0 waypoint3 waypoint55)
	(can_traverse rover0 waypoint55 waypoint3)
	(at rover1 waypoint56)
	(available rover1)
	(store_of rover1store rover1)
	(empty rover1store)
	(equipped_for_imaging rover1)
	(can_traverse rover1 waypoint56 waypoint2)
	(can_traverse rover1 waypoint2 waypoint56)
	(can_traverse rover1 waypoint56 waypoint14)
	(can_traverse rover1 waypoint14 waypoint56)
	(can_traverse rover1 waypoint56 waypoint17)
	(can_traverse rover1 waypoint17 waypoint56)
	(can_traverse rover1 waypoint56 waypoint33)
	(can_traverse rover1 waypoint33 waypoint56)
	(can_traverse rover1 waypoint2 waypoint3)
	(can_traverse rover1 waypoint3 waypoint2)
	(can_traverse rover1 waypoint2 waypoint20)
	(can_traverse rover1 waypoint20 waypoint2)
	(can_traverse rover1 waypoint2 waypoint21)
	(can_traverse rover1 waypoint21 waypoint2)
	(can_traverse rover1 waypoint2 waypoint31)
	(can_traverse rover1 waypoint31 waypoint2)
	(can_traverse rover1 waypoint2 waypoint41)
	(can_traverse rover1 waypoint41 waypoint2)
	(can_traverse rover1 waypoint2 waypoint42)
	(can_traverse rover1 waypoint42 waypoint2)
	(can_traverse rover1 waypoint14 waypoint9)
	(can_traverse rover1 waypoint9 waypoint14)
	(can_traverse rover1 waypoint14 waypoint36)
	(can_traverse rover1 waypoint36 waypoint14)
	(can_traverse rover1 waypoint17 waypoint24)
	(can_traverse rover1 waypoint24 waypoint17)
	(can_traverse rover1 waypoint17 waypoint34)
	(can_traverse rover1 waypoint34 waypoint17)
	(can_traverse rover1 waypoint17 waypoint35)
	(can_traverse rover1 waypoint35 waypoint17)
	(can_traverse rover1 waypoint17 waypoint55)
	(can_traverse rover1 waypoint55 waypoint17)
	(can_traverse rover1 waypoint33 waypoint7)
	(can_traverse rover1 waypoint7 waypoint33)
	(can_traverse rover1 waypoint33 waypoint26)
	(can_traverse rover1 waypoint26 waypoint33)
	(can_traverse rover1 waypoint33 waypoint29)
	(can_traverse rover1 waypoint29 waypoint33)
	(can_traverse rover1 waypoint33 waypoint53)
	(can_traverse rover1 waypoint53 waypoint33)
	(can_traverse rover1 waypoint3 waypoint5)
	(can_traverse rover1 waypoint5 waypoint3)
	(can_traverse rover1 waypoint3 waypoint8)
	(can_traverse rover1 waypoint8 waypoint3)
	(can_traverse rover1 waypoint3 waypoint16)
	(can_traverse rover1 waypoint16 waypoint3)
	(can_traverse rover1 waypoint3 waypoint19)
	(can_traverse rover1 waypoint19 waypoint3)
	(can_traverse rover1 waypoint3 waypoint37)
	(can_traverse rover1 waypoint37 waypoint3)
	(can_traverse rover1 waypoint3 waypoint38)
	(can_traverse rover1 waypoint38 waypoint3)
	(can_traverse rover1 waypoint3 waypoint49)
	(can_traverse rover1 waypoint49 waypoint3)
	(can_traverse rover1 waypoint3 waypoint52)
	(can_traverse rover1 waypoint52 waypoint3)
	(can_traverse rover1 waypoint20 waypoint1)
	(can_traverse rover1 waypoint1 waypoint20)
	(can_traverse rover1 waypoint20 waypoint15)
	(can_traverse rover1 waypoint15 waypoint20)
	(can_traverse rover1 waypoint20 waypoint25)
	(can_traverse rover1 waypoint25 waypoint20)
	(can_traverse rover1 waypoint20 waypoint28)
	(can_traverse rover1 waypoint28 waypoint20)
	(can_traverse rover1 waypoint20 waypoint43)
	(can_traverse rover1 waypoint43 waypoint20)
	(can_traverse rover1 waypoint20 waypoint57)
	(can_traverse rover1 waypoint57 waypoint20)
	(can_traverse rover1 waypoint31 waypoint12)
	(can_traverse rover1 waypoint12 waypoint31)
	(can_traverse rover1 waypoint31 waypoint22)
	(can_traverse rover1 waypoint22 waypoint31)
	(can_traverse rover1 waypoint31 waypoint40)
	(can_traverse rover1 waypoint40 waypoint31)
	(can_traverse rover1 waypoint31 waypoint48)
	(can_traverse rover1 waypoint48 waypoint31)
	(can_traverse rover1 waypoint31 waypoint59)
	(can_traverse rover1 waypoint59 waypoint31)
	(can_traverse rover1 waypoint41 waypoint0)
	(can_traverse rover1 waypoint0 waypoint41)
	(can_traverse rover1 waypoint41 waypoint11)
	(can_traverse rover1 waypoint11 waypoint41)
	(can_traverse rover1 waypoint41 waypoint13)
	(can_traverse rover1 waypoint13 waypoint41)
	(can_traverse rover1 waypoint41 waypoint23)
	(can_traverse rover1 waypoint23 waypoint41)
	(can_traverse rover1 waypoint41 waypoint54)
	(can_traverse rover1 waypoint54 waypoint41)
	(can_traverse rover1 waypoint42 waypoint46)
	(can_traverse rover1 waypoint46 waypoint42)
	(can_traverse rover1 waypoint9 waypoint32)
	(can_traverse rover1 waypoint32 waypoint9)
	(can_traverse rover1 waypoint36 waypoint10)
	(can_traverse rover1 waypoint10 waypoint36)
	(can_traverse rover1 waypoint36 waypoint30)
	(can_traverse rover1 waypoint30 waypoint36)
	(can_traverse rover1 waypoint36 waypoint44)
	(can_traverse rover1 waypoint44 waypoint36)
	(can_traverse rover1 waypoint36 waypoint47)
	(can_traverse rover1 waypoint47 waypoint36)
	(can_traverse rover1 waypoint24 waypoint6)
	(can_traverse rover1 waypoint6 waypoint24)
	(can_traverse rover1 waypoint24 waypoint50)
	(can_traverse rover1 waypoint50 waypoint24)
	(can_traverse rover1 waypoint35 waypoint18)
	(can_traverse rover1 waypoint18 waypoint35)
	(can_traverse rover1 waypoint35 waypoint58)
	(can_traverse rover1 waypoint58 waypoint35)
	(can_traverse rover1 waypoint55 waypoint51)
	(can_traverse rover1 waypoint51 waypoint55)
	(can_traverse rover1 waypoint26 waypoint39)
	(can_traverse rover1 waypoint39 waypoint26)
	(can_traverse rover1 waypoint16 waypoint4)
	(can_traverse rover1 waypoint4 waypoint16)
	(can_traverse rover1 waypoint1 waypoint27)
	(can_traverse rover1 waypoint27 waypoint1)
	(can_traverse rover1 waypoint57 waypoint45)
	(can_traverse rover1 waypoint45 waypoint57)
	(at rover2 waypoint52)
	(available rover2)
	(store_of rover2store rover2)
	(empty rover2store)
	(equipped_for_rock_analysis rover2)
	(equipped_for_imaging rover2)
	(can_traverse rover2 waypoint52 waypoint0)
	(can_traverse rover2 waypoint0 waypoint52)
	(can_traverse rover2 waypoint52 waypoint1)
	(can_traverse rover2 waypoint1 waypoint52)
	(can_traverse rover2 waypoint52 waypoint17)
	(can_traverse rover2 waypoint17 waypoint52)
	(can_traverse rover2 waypoint52 waypoint20)
	(can_traverse rover2 waypoint20 waypoint52)
	(can_traverse rover2 waypoint52 waypoint28)
	(can_traverse rover2 waypoint28 waypoint52)
	(can_traverse rover2 waypoint52 waypoint33)
	(can_traverse rover2 waypoint33 waypoint52)
	(can_traverse rover2 waypoint52 waypoint35)
	(can_traverse rover2 waypoint35 waypoint52)
	(can_traverse rover2 waypoint52 waypoint44)
	(can_traverse rover2 waypoint44 waypoint52)
	(can_traverse rover2 waypoint52 waypoint49)
	(can_traverse rover2 waypoint49 waypoint52)
	(can_traverse rover2 waypoint52 waypoint59)
	(can_traverse rover2 waypoint59 waypoint52)
	(can_traverse rover2 waypoint0 waypoint8)
	(can_traverse rover2 waypoint8 waypoint0)
	(can_traverse rover2 waypoint0 waypoint9)
	(can_traverse rover2 waypoint9 waypoint0)
	(can_traverse rover2 waypoint0 waypoint15)
	(can_traverse rover2 waypoint15 waypoint0)
	(can_traverse rover2 waypoint0 waypoint41)
	(can_traverse rover2 waypoint41 waypoint0)
	(can_traverse rover2 waypoint1 waypoint18)
	(can_traverse rover2 waypoint18 waypoint1)
	(can_traverse rover2 waypoint1 waypoint23)
	(can_traverse rover2 waypoint23 waypoint1)
	(can_traverse rover2 waypoint1 waypoint27)
	(can_traverse rover2 waypoint27 waypoint1)
	(can_traverse rover2 waypoint1 waypoint30)
	(can_traverse rover2 waypoint30 waypoint1)
	(can_traverse rover2 waypoint1 waypoint31)
	(can_traverse rover2 waypoint31 waypoint1)
	(can_traverse rover2 waypoint1 waypoint45)
	(can_traverse rover2 waypoint45 waypoint1)
	(can_traverse rover2 waypoint1 waypoint48)
	(can_traverse rover2 waypoint48 waypoint1)
	(can_traverse rover2 waypoint17 waypoint34)
	(can_traverse rover2 waypoint34 waypoint17)
	(can_traverse rover2 waypoint17 waypoint36)
	(can_traverse rover2 waypoint36 waypoint17)
	(can_traverse rover2 waypoint17 waypoint56)
	(can_traverse rover2 waypoint56 waypoint17)
	(can_traverse rover2 waypoint20 waypoint2)
	(can_traverse rover2 waypoint2 waypoint20)
	(can_traverse rover2 waypoint20 waypoint25)
	(can_traverse rover2 waypoint25 waypoint20)
	(can_traverse rover2 waypoint20 waypoint40)
	(can_traverse rover2 waypoint40 waypoint20)
	(can_traverse rover2 waypoint20 waypoint43)
	(can_traverse rover2 waypoint43 waypoint20)
	(can_traverse rover2 waypoint20 waypoint57)
	(can_traverse rover2 waypoint57 waypoint20)
	(can_traverse rover2 waypoint28 waypoint4)
	(can_traverse rover2 waypoint4 waypoint28)
	(can_traverse rover2 waypoint33 waypoint26)
	(can_traverse rover2 waypoint26 waypoint33)
	(can_traverse rover2 waypoint33 waypoint29)
	(can_traverse rover2 waypoint29 waypoint33)
	(can_traverse rover2 waypoint33 waypoint53)
	(can_traverse rover2 waypoint53 waypoint33)
	(can_traverse rover2 waypoint35 waypoint32)
	(can_traverse rover2 waypoint32 waypoint35)
	(can_traverse rover2 waypoint35 waypoint38)
	(can_traverse rover2 waypoint38 waypoint35)
	(can_traverse rover2 waypoint44 waypoint7)
	(can_traverse rover2 waypoint7 waypoint44)
	(can_traverse rover2 waypoint44 waypoint19)
	(can_traverse rover2 waypoint19 waypoint44)
	(can_traverse rover2 waypoint44 waypoint46)
	(can_traverse rover2 waypoint46 waypoint44)
	(can_traverse rover2 waypoint49 waypoint3)
	(can_traverse rover2 waypoint3 waypoint49)
	(can_traverse rover2 waypoint49 waypoint11)
	(can_traverse rover2 waypoint11 waypoint49)
	(can_traverse rover2 waypoint49 waypoint16)
	(can_traverse rover2 waypoint16 waypoint49)
	(can_traverse rover2 waypoint49 waypoint22)
	(can_traverse rover2 waypoint22 waypoint49)
	(can_traverse rover2 waypoint49 waypoint39)
	(can_traverse rover2 waypoint39 waypoint49)
	(can_traverse rover2 waypoint49 waypoint51)
	(can_traverse rover2 waypoint51 waypoint49)
	(can_traverse rover2 waypoint59 waypoint6)
	(can_traverse rover2 waypoint6 waypoint59)
	(can_traverse rover2 waypoint59 waypoint13)
	(can_traverse rover2 waypoint13 waypoint59)
	(can_traverse rover2 waypoint59 waypoint50)
	(can_traverse rover2 waypoint50 waypoint59)
	(can_traverse rover2 waypoint9 waypoint14)
	(can_traverse rover2 waypoint14 waypoint9)
	(can_traverse rover2 waypoint15 waypoint47)
	(can_traverse rover2 waypoint47 waypoint15)
	(can_traverse rover2 waypoint41 waypoint24)
	(can_traverse rover2 waypoint24 waypoint41)
	(can_traverse rover2 waypoint41 waypoint54)
	(can_traverse rover2 waypoint54 waypoint41)
	(can_traverse rover2 waypoint30 waypoint10)
	(can_traverse rover2 waypoint10 waypoint30)
	(can_traverse rover2 waypoint30 waypoint55)
	(can_traverse rover2 waypoint55 waypoint30)
	(can_traverse rover2 waypoint31 waypoint37)
	(can_traverse rover2 waypoint37 waypoint31)
	(can_traverse rover2 waypoint45 waypoint42)
	(can_traverse rover2 waypoint42 waypoint45)
	(can_traverse rover2 waypoint2 waypoint5)
	(can_traverse rover2 waypoint5 waypoint2)
	(can_traverse rover2 waypoint2 waypoint12)
	(can_traverse rover2 waypoint12 waypoint2)
	(can_traverse rover2 waypoint57 waypoint21)
	(can_traverse rover2 waypoint21 waypoint57)
	(can_traverse rover2 waypoint26 waypoint58)
	(can_traverse rover2 waypoint58 waypoint26)
	(at rover3 waypoint11)
	(available rover3)
	(store_of rover3store rover3)
	(empty rover3store)
	(equipped_for_soil_analysis rover3)
	(equipped_for_rock_analysis rover3)
	(can_traverse rover3 waypoint11 waypoint0)
	(can_traverse rover3 waypoint0 waypoint11)
	(can_traverse rover3 waypoint11 waypoint6)
	(can_traverse rover3 waypoint6 waypoint11)
	(can_traverse rover3 waypoint11 waypoint8)
	(can_traverse rover3 waypoint8 waypoint11)
	(can_traverse rover3 waypoint11 waypoint12)
	(can_traverse rover3 waypoint12 waypoint11)
	(can_traverse rover3 waypoint11 waypoint38)
	(can_traverse rover3 waypoint38 waypoint11)
	(can_traverse rover3 waypoint11 waypoint49)
	(can_traverse rover3 waypoint49 waypoint11)
	(can_traverse rover3 waypoint11 waypoint57)
	(can_traverse rover3 waypoint57 waypoint11)
	(can_traverse rover3 waypoint0 waypoint9)
	(can_traverse rover3 waypoint9 waypoint0)
	(can_traverse rover3 waypoint0 waypoint15)
	(can_traverse rover3 waypoint15 waypoint0)
	(can_traverse rover3 waypoint0 waypoint41)
	(can_traverse rover3 waypoint41 waypoint0)
	(can_traverse rover3 waypoint0 waypoint52)
	(can_traverse rover3 waypoint52 waypoint0)
	(can_traverse rover3 waypoint6 waypoint23)
	(can_traverse rover3 waypoint23 waypoint6)
	(can_traverse rover3 waypoint6 waypoint39)
	(can_traverse rover3 waypoint39 waypoint6)
	(can_traverse rover3 waypoint8 waypoint3)
	(can_traverse rover3 waypoint3 waypoint8)
	(can_traverse rover3 waypoint8 waypoint25)
	(can_traverse rover3 waypoint25 waypoint8)
	(can_traverse rover3 waypoint8 waypoint50)
	(can_traverse rover3 waypoint50 waypoint8)
	(can_traverse rover3 waypoint12 waypoint5)
	(can_traverse rover3 waypoint5 waypoint12)
	(can_traverse rover3 waypoint12 waypoint13)
	(can_traverse rover3 waypoint13 waypoint12)
	(can_traverse rover3 waypoint12 waypoint22)
	(can_traverse rover3 waypoint22 waypoint12)
	(can_traverse rover3 waypoint12 waypoint31)
	(can_traverse rover3 waypoint31 waypoint12)
	(can_traverse rover3 waypoint38 waypoint18)
	(can_traverse rover3 waypoint18 waypoint38)
	(can_traverse rover3 waypoint38 waypoint35)
	(can_traverse rover3 waypoint35 waypoint38)
	(can_traverse rover3 waypoint38 waypoint55)
	(can_traverse rover3 waypoint55 waypoint38)
	(can_traverse rover3 waypoint38 waypoint58)
	(can_traverse rover3 waypoint58 waypoint38)
	(can_traverse rover3 waypoint49 waypoint16)
	(can_traverse rover3 waypoint16 waypoint49)
	(can_traverse rover3 waypoint49 waypoint51)
	(can_traverse rover3 waypoint51 waypoint49)
	(can_traverse rover3 waypoint57 waypoint4)
	(can_traverse rover3 waypoint4 waypoint57)
	(can_traverse rover3 waypoint57 waypoint21)
	(can_traverse rover3 waypoint21 waypoint57)
	(can_traverse rover3 waypoint57 waypoint36)
	(can_traverse rover3 waypoint36 waypoint57)
	(can_traverse rover3 waypoint57 waypoint43)
	(can_traverse rover3 waypoint43 waypoint57)
	(can_traverse rover3 waypoint9 waypoint1)
	(can_traverse rover3 waypoint1 waypoint9)
	(can_traverse rover3 waypoint9 waypoint14)
	(can_traverse rover3 waypoint14 waypoint9)
	(can_traverse rover3 waypoint9 waypoint17)
	(can_traverse rover3 waypoint17 waypoint9)
	(can_traverse rover3 waypoint9 waypoint32)
	(can_traverse rover3 waypoint32 waypoint9)
	(can_traverse rover3 waypoint15 waypoint20)
	(can_traverse rover3 waypoint20 waypoint15)
	(can_traverse rover3 waypoint15 waypoint40)
	(can_traverse rover3 waypoint40 waypoint15)
	(can_traverse rover3 waypoint15 waypoint44)
	(can_traverse rover3 waypoint44 waypoint15)
	(can_traverse rover3 waypoint41 waypoint24)
	(can_traverse rover3 waypoint24 waypoint41)
	(can_traverse rover3 waypoint41 waypoint45)
	(can_traverse rover3 waypoint45 waypoint41)
	(can_traverse rover3 waypoint41 waypoint54)
	(can_traverse rover3 waypoint54 waypoint41)
	(can_traverse rover3 waypoint52 waypoint28)
	(can_traverse rover3 waypoint28 waypoint52)
	(can_traverse rover3 waypoint52 waypoint33)
	(can_traverse rover3 waypoint33 waypoint52)
	(can_traverse rover3 waypoint23 waypoint2)
	(can_traverse rover3 waypoint2 waypoint23)
	(can_traverse rover3 waypoint23 waypoint10)
	(can_traverse rover3 waypoint10 waypoint23)
	(can_traverse rover3 waypoint25 waypoint47)
	(can_traverse rover3 waypoint47 waypoint25)
	(can_traverse rover3 waypoint50 waypoint46)
	(can_traverse rover3 waypoint46 waypoint50)
	(can_traverse rover3 waypoint50 waypoint59)
	(can_traverse rover3 waypoint59 waypoint50)
	(can_traverse rover3 waypoint5 waypoint7)
	(can_traverse rover3 waypoint7 waypoint5)
	(can_traverse rover3 waypoint5 waypoint26)
	(can_traverse rover3 waypoint26 waypoint5)
	(can_traverse rover3 waypoint5 waypoint37)
	(can_traverse rover3 waypoint37 waypoint5)
	(can_traverse rover3 waypoint13 waypoint42)
	(can_traverse rover3 waypoint42 waypoint13)
	(can_traverse rover3 waypoint13 waypoint48)
	(can_traverse rover3 waypoint48 waypoint13)
	(can_traverse rover3 waypoint22 waypoint29)
	(can_traverse rover3 waypoint29 waypoint22)
	(can_traverse rover3 waypoint55 waypoint30)
	(can_traverse rover3 waypoint30 waypoint55)
	(can_traverse rover3 waypoint21 waypoint56)
	(can_traverse rover3 waypoint56 waypoint21)
	(can_traverse rover3 waypoint1 waypoint27)
	(can_traverse rover3 waypoint27 waypoint1)
	(can_traverse rover3 waypoint17 waypoint34)
	(can_traverse rover3 waypoint34 waypoint17)
	(can_traverse rover3 waypoint44 waypoint19)
	(can_traverse rover3 waypoint19 waypoint44)
	(can_traverse rover3 waypoint33 waypoint53)
	(can_traverse rover3 waypoint53 waypoint33)
	(on_board camera0 rover0)
	(calibration_target camera0 objective2)
	(supports camera0 colour)
	(supports camera0 high_res)
	(on_board camera1 rover1)
	(calibration_target camera1 objective4)
	(supports camera1 colour)
	(supports camera1 high_res)
	(on_board camera2 rover1)
	(calibration_target camera2 objective7)
	(supports camera2 colour)
	(supports camera2 low_res)
	(on_board camera3 rover0)
	(calibration_target camera3 objective1)
	(supports camera3 colour)
	(supports camera3 low_res)
	(on_board camera4 rover1)
	(calibration_target camera4 objective3)
	(supports camera4 high_res)
	(on_board camera5 rover1)
	(calibration_target camera5 objective4)
	(supports camera5 colour)
	(supports camera5 high_res)
	(on_board camera6 rover2)
	(calibration_target camera6 objective5)
	(supports camera6 colour)
	(supports camera6 high_res)
	(supports camera6 low_res)
	(visible_from objective0 waypoint0)
	(visible_from objective0 waypoint9)
	(visible_from objective0 waypoint14)
	(visible_from objective0 waypoint15)
	(visible_from objective0 waypoint16)
	(visible_from objective0 waypoint17)
	(visible_from objective0 waypoint20)
	(visible_from objective0 waypoint23)
	(visible_from objective0 waypoint24)
	(visible_from objective0 waypoint28)
	(visible_from objective0 waypoint30)
	(visible_from objective0 waypoint31)
	(visible_from objective0 waypoint33)
	(visible_from objective0 waypoint37)
	(visible_from objective0 waypoint38)
	(visible_from objective0 waypoint39)
	(visible_from objective0 waypoint42)
	(visible_from objective0 waypoint47)
	(visible_from objective0 waypoint51)
	(visible_from objective0 waypoint54)
	(visible_from objective0 waypoint56)
	(visible_from objective0 waypoint57)
	(visible_from objective0 waypoint58)
	(visible_from objective1 waypoint1)
	(visible_from objective1 waypoint3)
	(visible_from objective1 waypoint10)
	(visible_from objective1 waypoint11)
	(visible_from objective1 waypoint24)
	(visible_from objective1 waypoint29)
	(visible_from objective1 waypoint37)
	(visible_from objective1 waypoint39)
	(visible_from objective1 waypoint41)
	(visible_from objective1 waypoint56)
	(visible_from objective2 waypoint5)
	(visible_from objective2 waypoint7)
	(visible_from objective2 waypoint9)
	(visible_from objective2 waypoint10)
	(visible_from objective2 waypoint11)
	(visible_from objective2 waypoint12)
	(visible_from objective2 waypoint16)
	(visible_from objective2 waypoint18)
	(visible_from objective2 waypoint20)
	(visible_from objective2 waypoint22)
	(visible_from objective2 waypoint23)
	(visible_from objective2 waypoint25)
	(visible_from objective2 waypoint26)
	(visible_from objective2 waypoint27)
	(visible_from objective2 waypoint29)
	(visible_from objective2 waypoint32)
	(visible_from objective2 waypoint33)
	(visible_from objective2 waypoint35)
	(visible_from objective2 waypoint41)
	(visible_from objective2 waypoint45)
	(visible_from objective2 waypoint46)
	(visible_from objective2 waypoint47)
	(visible_from objective2 waypoint57)
	(visible_from objective2 waypoint58)
	(visible_from objective3 waypoint1)
	(visible_from objective3 waypoint6)
	(visible_from objective3 waypoint7)
	(visible_from objective3 waypoint9)
	(visible_from objective3 waypoint14)
	(visible_from objective3 waypoint15)
	(visible_from objective3 waypoint21)
	(visible_from objective3 waypoint23)
	(visible_from objective3 waypoint24)
	(visible_from objective3 waypoint27)
	(visible_from objective3 waypoint30)
	(visible_from objective3 waypoint34)
	(visible_from objective3 waypoint35)
	(visible_from objective3 waypoint36)
	(visible_from objective3 waypoint40)
	(visible_from objective3 waypoint41)
	(visible_from objective3 waypoint42)
	(visible_from objective3 waypoint44)
	(visible_from objective3 waypoint51)
	(visible_from objective3 waypoint59)
	(visible_from objective4 waypoint1)
	(visible_from objective4 waypoint3)
	(visible_from objective4 waypoint4)
	(visible_from objective4 waypoint5)
	(visible_from objective4 waypoint6)
	(visible_from objective4 waypoint8)
	(visible_from objective4 waypoint10)
	(visible_from objective4 waypoint11)
	(visible_from objective4 waypoint13)
	(visible_from objective4 waypoint14)
	(visible_from objective4 waypoint15)
	(visible_from objective4 waypoint19)
	(visible_from objective4 waypoint20)
	(visible_from objective4 waypoint22)
	(visible_from objective4 waypoint24)
	(visible_from objective4 waypoint26)
	(visible_from objective4 waypoint27)
	(visible_from objective4 waypoint28)
	(visible_from objective4 waypoint29)
	(visible_from objective4 waypoint30)
	(visible_from objective4 waypoint31)
	(visible_from objective4 waypoint32)
	(visible_from objective4 waypoint33)
	(visible_from objective4 waypoint35)
	(visible_from objective4 waypoint36)
	(visible_from objective4 waypoint38)
	(visible_from objective4 waypoint39)
	(visible_from objective4 waypoint41)
	(visible_from objective4 waypoint44)
	(visible_from objective4 waypoint45)
	(visible_from objective4 waypoint47)
	(visible_from objective4 waypoint48)
	(visible_from objective4 waypoint51)
	(visible_from objective4 waypoint53)
	(visible_from objective4 waypoint54)
	(visible_from objective4 waypoint56)
	(visible_from objective4 waypoint57)
	(visible_from objective4 waypoint58)
	(visible_from objective4 waypoint59)
	(visible_from objective5 waypoint2)
	(visible_from objective5 waypoint4)
	(visible_from objective5 waypoint5)
	(visible_from objective5 waypoint10)
	(visible_from objective5 waypoint12)
	(visible_from objective5 waypoint14)
	(visible_from objective5 waypoint16)
	(visible_from objective5 waypoint18)
	(visible_from objective5 waypoint19)
	(visible_from objective5 waypoint20)
	(visible_from objective5 waypoint23)
	(visible_from objective5 waypoint30)
	(visible_from objective5 waypoint31)
	(visible_from objective5 waypoint45)
	(visible_from objective6 waypoint0)
	(visible_from objective6 waypoint2)
	(visible_from objective6 waypoint4)
	(visible_from objective6 waypoint6)
	(visible_from objective6 waypoint8)
	(visible_from objective6 waypoint13)
	(visible_from objective6 waypoint16)
	(visible_from objective6 waypoint19)
	(visible_from objective6 waypoint22)
	(visible_from objective6 waypoint25)
	(visible_from objective6 waypoint26)
	(visible_from objective6 waypoint27)
	(visible_from objective6 waypoint28)
	(visible_from objective6 waypoint29)
	(visible_from objective6 waypoint30)
	(visible_from objective6 waypoint32)
	(visible_from objective6 waypoint33)
	(visible_from objective6 waypoint34)
	(visible_from objective6 waypoint35)
	(visible_from objective6 waypoint36)
	(visible_from objective6 waypoint39)
	(visible_from objective6 waypoint40)
	(visible_from objective6 waypoint41)
	(visible_from objective6 waypoint43)
	(visible_from objective6 waypoint45)
	(visible_from objective6 waypoint47)
	(visible_from objective6 waypoint48)
	(visible_from objective6 waypoint50)
	(visible_from objective6 waypoint51)
	(visible_from objective6 waypoint52)
	(visible_from objective6 waypoint53)
	(visible_from objective6 waypoint54)
	(visible_from objective6 waypoint55)
	(visible_from objective6 waypoint56)
	(visible_from objective6 waypoint57)
	(visible_from objective6 waypoint58)
	(visible_from objective6 waypoint59)
	(visible_from objective7 waypoint3)
	(visible_from objective7 waypoint9)
	(visible_from objective7 waypoint16)
	(visible_from objective7 waypoint18)
	(visible_from objective7 waypoint20)
	(visible_from objective7 waypoint21)
	(visible_from objective7 waypoint26)
	(visible_from objective7 waypoint29)
	(visible_from objective7 waypoint30)
	(visible_from objective7 waypoint48)
	(visible_from objective7 waypoint53)
	(visible_from objective7 waypoint54)
	(visible_from objective7 waypoint59)
)

(:goal (and
(communicated_soil_data waypoint37)
(communicated_soil_data waypoint17)
(communicated_soil_data waypoint51)
(communicated_soil_data waypoint55)
(communicated_soil_data waypoint44)
(communicated_soil_data waypoint53)
(communicated_soil_data waypoint1)
(communicated_soil_data waypoint57)
(communicated_soil_data waypoint48)
(communicated_soil_data waypoint54)
(communicated_soil_data waypoint26)
(communicated_soil_data waypoint28)
(communicated_soil_data waypoint13)
(communicated_soil_data waypoint20)
(communicated_soil_data waypoint5)
(communicated_soil_data waypoint49)
(communicated_soil_data waypoint9)
(communicated_soil_data waypoint7)
(communicated_soil_data waypoint47)
(communicated_soil_data waypoint45)
(communicated_rock_data waypoint34)
(communicated_rock_data waypoint0)
(communicated_rock_data waypoint28)
(communicated_rock_data waypoint51)
(communicated_rock_data waypoint53)
(communicated_rock_data waypoint22)
(communicated_rock_data waypoint8)
(communicated_rock_data waypoint18)
(communicated_rock_data waypoint41)
(communicated_rock_data waypoint12)
(communicated_rock_data waypoint3)
(communicated_rock_data waypoint48)
(communicated_rock_data waypoint9)
(communicated_rock_data waypoint1)
(communicated_rock_data waypoint50)
(communicated_image_data objective5 colour)
(communicated_image_data objective7 high_res)
(communicated_image_data objective6 colour)
(communicated_image_data objective4 colour)
(communicated_image_data objective6 high_res)
(communicated_image_data objective3 high_res)
(communicated_image_data objective0 colour)
(communicated_image_data objective2 low_res)
(communicated_image_data objective2 colour)
(communicated_image_data objective5 high_res)
(communicated_image_data objective4 high_res)
(communicated_image_data objective4 low_res)
	)
)
)
