(define (problem roverprob9) (:domain Rover)
(:objects
	general - Lander
	colour high_res low_res - Mode
	rover0 rover1 rover2 - Rover
	rover0store rover1store rover2store - Store
	waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 waypoint7 waypoint8 waypoint9 waypoint10 waypoint11 waypoint12 waypoint13 waypoint14 waypoint15 waypoint16 waypoint17 waypoint18 waypoint19 waypoint20 waypoint21 waypoint22 waypoint23 waypoint24 waypoint25 waypoint26 waypoint27 waypoint28 waypoint29 - Waypoint
	camera0 camera1 camera2 camera3 camera4 - Camera
	objective0 objective1 objective2 objective3 objective4 objective5 - Objective
	)
(:init
	(visible waypoint0 waypoint12)
	(visible waypoint12 waypoint0)
	(visible waypoint0 waypoint15)
	(visible waypoint15 waypoint0)
	(visible waypoint0 waypoint27)
	(visible waypoint27 waypoint0)
	(visible waypoint1 waypoint6)
	(visible waypoint6 waypoint1)
	(visible waypoint1 waypoint15)
	(visible waypoint15 waypoint1)
	(visible waypoint1 waypoint23)
	(visible waypoint23 waypoint1)
	(visible waypoint1 waypoint27)
	(visible waypoint27 waypoint1)
	(visible waypoint1 waypoint29)
	(visible waypoint29 waypoint1)
	(visible waypoint2 waypoint1)
	(visible waypoint1 waypoint2)
	(visible waypoint2 waypoint5)
	(visible waypoint5 waypoint2)
	(visible waypoint2 waypoint9)
	(visible waypoint9 waypoint2)
	(visible waypoint2 waypoint12)
	(visible waypoint12 waypoint2)
	(visible waypoint2 waypoint16)
	(visible waypoint16 waypoint2)
	(visible waypoint2 waypoint20)
	(visible waypoint20 waypoint2)
	(visible waypoint2 waypoint27)
	(visible waypoint27 waypoint2)
	(visible waypoint3 waypoint15)
	(visible waypoint15 waypoint3)
	(visible waypoint3 waypoint19)
	(visible waypoint19 waypoint3)
	(visible waypoint3 waypoint23)
	(visible waypoint23 waypoint3)
	(visible waypoint4 waypoint19)
	(visible waypoint19 waypoint4)
	(visible waypoint4 waypoint24)
	(visible waypoint24 waypoint4)
	(visible waypoint4 waypoint26)
	(visible waypoint26 waypoint4)
	(visible waypoint5 waypoint3)
	(visible waypoint3 waypoint5)
	(visible waypoint5 waypoint19)
	(visible waypoint19 waypoint5)
	(visible waypoint5 waypoint22)
	(visible waypoint22 waypoint5)
	(visible waypoint6 waypoint10)
	(visible waypoint10 waypoint6)
	(visible waypoint6 waypoint14)
	(visible waypoint14 waypoint6)
	(visible waypoint6 waypoint20)
	(visible waypoint20 waypoint6)
	(visible waypoint7 waypoint8)
	(visible waypoint8 waypoint7)
	(visible waypoint7 waypoint12)
	(visible waypoint12 waypoint7)
	(visible waypoint7 waypoint13)
	(visible waypoint13 waypoint7)
	(visible waypoint7 waypoint25)
	(visible waypoint25 waypoint7)
	(visible waypoint8 waypoint20)
	(visible waypoint20 waypoint8)
	(visible waypoint8 waypoint23)
	(visible waypoint23 waypoint8)
	(visible waypoint9 waypoint11)
	(visible waypoint11 waypoint9)
	(visible waypoint9 waypoint20)
	(visible waypoint20 waypoint9)
	(visible waypoint9 waypoint24)
	(visible waypoint24 waypoint9)
	(visible waypoint10 waypoint11)
	(visible waypoint11 waypoint10)
	(visible waypoint10 waypoint13)
	(visible waypoint13 waypoint10)
	(visible waypoint10 waypoint17)
	(visible waypoint17 waypoint10)
	(visible waypoint11 waypoint5)
	(visible waypoint5 waypoint11)
	(visible waypoint11 waypoint21)
	(visible waypoint21 waypoint11)
	(visible waypoint11 waypoint26)
	(visible waypoint26 waypoint11)
	(visible waypoint11 waypoint27)
	(visible waypoint27 waypoint11)
	(visible waypoint12 waypoint3)
	(visible waypoint3 waypoint12)
	(visible waypoint12 waypoint5)
	(visible waypoint5 waypoint12)
	(visible waypoint12 waypoint11)
	(visible waypoint11 waypoint12)
	(visible waypoint12 waypoint16)
	(visible waypoint16 waypoint12)
	(visible waypoint13 waypoint5)
	(visible waypoint5 waypoint13)
	(visible waypoint13 waypoint9)
	(visible waypoint9 waypoint13)
	(visible waypoint13 waypoint16)
	(visible waypoint16 waypoint13)
	(visible waypoint13 waypoint18)
	(visible waypoint18 waypoint13)
	(visible waypoint13 waypoint23)
	(visible waypoint23 waypoint13)
	(visible waypoint13 waypoint27)
	(visible waypoint27 waypoint13)
	(visible waypoint14 waypoint8)
	(visible waypoint8 waypoint14)
	(visible waypoint14 waypoint20)
	(visible waypoint20 waypoint14)
	(visible waypoint14 waypoint21)
	(visible waypoint21 waypoint14)
	(visible waypoint15 waypoint4)
	(visible waypoint4 waypoint15)
	(visible waypoint15 waypoint6)
	(visible waypoint6 waypoint15)
	(visible waypoint15 waypoint11)
	(visible waypoint11 waypoint15)
	(visible waypoint15 waypoint17)
	(visible waypoint17 waypoint15)
	(visible waypoint15 waypoint25)
	(visible waypoint25 waypoint15)
	(visible waypoint16 waypoint0)
	(visible waypoint0 waypoint16)
	(visible waypoint16 waypoint1)
	(visible waypoint1 waypoint16)
	(visible waypoint16 waypoint14)
	(visible waypoint14 waypoint16)
	(visible waypoint16 waypoint20)
	(visible waypoint20 waypoint16)
	(visible waypoint17 waypoint25)
	(visible waypoint25 waypoint17)
	(visible waypoint18 waypoint0)
	(visible waypoint0 waypoint18)
	(visible waypoint18 waypoint7)
	(visible waypoint7 waypoint18)
	(visible waypoint18 waypoint8)
	(visible waypoint8 waypoint18)
	(visible waypoint18 waypoint24)
	(visible waypoint24 waypoint18)
	(visible waypoint18 waypoint29)
	(visible waypoint29 waypoint18)
	(visible waypoint19 waypoint0)
	(visible waypoint0 waypoint19)
	(visible waypoint19 waypoint1)
	(visible waypoint1 waypoint19)
	(visible waypoint19 waypoint25)
	(visible waypoint25 waypoint19)
	(visible waypoint20 waypoint1)
	(visible waypoint1 waypoint20)
	(visible waypoint20 waypoint21)
	(visible waypoint21 waypoint20)
	(visible waypoint20 waypoint27)
	(visible waypoint27 waypoint20)
	(visible waypoint20 waypoint29)
	(visible waypoint29 waypoint20)
	(visible waypoint21 waypoint8)
	(visible waypoint8 waypoint21)
	(visible waypoint21 waypoint10)
	(visible waypoint10 waypoint21)
	(visible waypoint21 waypoint18)
	(visible waypoint18 waypoint21)
	(visible waypoint22 waypoint6)
	(visible waypoint6 waypoint22)
	(visible waypoint22 waypoint8)
	(visible waypoint8 waypoint22)
	(visible waypoint22 waypoint14)
	(visible waypoint14 waypoint22)
	(visible waypoint22 waypoint24)
	(visible waypoint24 waypoint22)
	(visible waypoint23 waypoint15)
	(visible waypoint15 waypoint23)
	(visible waypoint23 waypoint28)
	(visible waypoint28 waypoint23)
	(visible waypoint24 waypoint6)
	(visible waypoint6 waypoint24)
	(visible waypoint24 waypoint8)
	(visible waypoint8 waypoint24)
	(visible waypoint24 waypoint17)
	(visible waypoint17 waypoint24)
	(visible waypoint25 waypoint5)
	(visible waypoint5 waypoint25)
	(visible waypoint25 waypoint6)
	(visible waypoint6 waypoint25)
	(visible waypoint25 waypoint9)
	(visible waypoint9 waypoint25)
	(visible waypoint25 waypoint14)
	(visible waypoint14 waypoint25)
	(visible waypoint25 waypoint18)
	(visible waypoint18 waypoint25)
	(visible waypoint25 waypoint20)
	(visible waypoint20 waypoint25)
	(visible waypoint25 waypoint21)
	(visible waypoint21 waypoint25)
	(visible waypoint26 waypoint2)
	(visible waypoint2 waypoint26)
	(visible waypoint26 waypoint3)
	(visible waypoint3 waypoint26)
	(visible waypoint26 waypoint6)
	(visible waypoint6 waypoint26)
	(visible waypoint26 waypoint13)
	(visible waypoint13 waypoint26)
	(visible waypoint26 waypoint14)
	(visible waypoint14 waypoint26)
	(visible waypoint26 waypoint24)
	(visible waypoint24 waypoint26)
	(visible waypoint27 waypoint4)
	(visible waypoint4 waypoint27)
	(visible waypoint27 waypoint15)
	(visible waypoint15 waypoint27)
	(visible waypoint28 waypoint4)
	(visible waypoint4 waypoint28)
	(visible waypoint28 waypoint7)
	(visible waypoint7 waypoint28)
	(visible waypoint28 waypoint11)
	(visible waypoint11 waypoint28)
	(visible waypoint28 waypoint16)
	(visible waypoint16 waypoint28)
	(visible waypoint28 waypoint17)
	(visible waypoint17 waypoint28)
	(visible waypoint28 waypoint19)
	(visible waypoint19 waypoint28)
	(visible waypoint28 waypoint21)
	(visible waypoint21 waypoint28)
	(visible waypoint28 waypoint24)
	(visible waypoint24 waypoint28)
	(visible waypoint29 waypoint7)
	(visible waypoint7 waypoint29)
	(visible waypoint29 waypoint19)
	(visible waypoint19 waypoint29)
	(visible waypoint29 waypoint24)
	(visible waypoint24 waypoint29)
	(visible waypoint29 waypoint25)
	(visible waypoint25 waypoint29)
	(at_rock_sample waypoint0)
	(at_rock_sample waypoint1)
	(at_soil_sample waypoint2)
	(at_rock_sample waypoint2)
	(at_soil_sample waypoint3)
	(at_rock_sample waypoint3)
	(at_soil_sample waypoint4)
	(at_rock_sample waypoint5)
	(at_rock_sample waypoint6)
	(at_soil_sample waypoint7)
	(at_rock_sample waypoint8)
	(at_soil_sample waypoint9)
	(at_soil_sample waypoint11)
	(at_soil_sample waypoint12)
	(at_rock_sample waypoint13)
	(at_soil_sample waypoint14)
	(at_rock_sample waypoint14)
	(at_soil_sample waypoint15)
	(at_rock_sample waypoint15)
	(at_soil_sample waypoint16)
	(at_rock_sample waypoint16)
	(at_rock_sample waypoint17)
	(at_rock_sample waypoint19)
	(at_soil_sample waypoint20)
	(at_rock_sample waypoint20)
	(at_soil_sample waypoint21)
	(at_rock_sample waypoint21)
	(at_soil_sample waypoint22)
	(at_soil_sample waypoint23)
	(at_rock_sample waypoint25)
	(at_rock_sample waypoint26)
	(at_rock_sample waypoint27)
	(at_soil_sample waypoint28)
	(at_rock_sample waypoint28)
	(at_rock_sample waypoint29)
	(at_lander general waypoint16)
	(channel_free general)
	(at rover0 waypoint0)
	(available rover0)
	(store_of rover0store rover0)
	(empty rover0store)
	(equipped_for_soil_analysis rover0)
	(equipped_for_imaging rover0)
	(can_traverse rover0 waypoint0 waypoint12)
	(can_traverse rover0 waypoint12 waypoint0)
	(can_traverse rover0 waypoint0 waypoint15)
	(can_traverse rover0 waypoint15 waypoint0)
	(can_traverse rover0 waypoint0 waypoint16)
	(can_traverse rover0 waypoint16 waypoint0)
	(can_traverse rover0 waypoint0 waypoint18)
	(can_traverse rover0 waypoint18 waypoint0)
	(can_traverse rover0 waypoint0 waypoint19)
	(can_traverse rover0 waypoint19 waypoint0)
	(can_traverse rover0 waypoint0 waypoint27)
	(can_traverse rover0 waypoint27 waypoint0)
	(can_traverse rover0 waypoint12 waypoint2)
	(can_traverse rover0 waypoint2 waypoint12)
	(can_traverse rover0 waypoint12 waypoint3)
	(can_traverse rover0 waypoint3 waypoint12)
	(can_traverse rover0 waypoint12 waypoint7)
	(can_traverse rover0 waypoint7 waypoint12)
	(can_traverse rover0 waypoint12 waypoint11)
	(can_traverse rover0 waypoint11 waypoint12)
	(can_traverse rover0 waypoint15 waypoint17)
	(can_traverse rover0 waypoint17 waypoint15)
	(can_traverse rover0 waypoint15 waypoint23)
	(can_traverse rover0 waypoint23 waypoint15)
	(can_traverse rover0 waypoint15 waypoint25)
	(can_traverse rover0 waypoint25 waypoint15)
	(can_traverse rover0 waypoint16 waypoint1)
	(can_traverse rover0 waypoint1 waypoint16)
	(can_traverse rover0 waypoint16 waypoint13)
	(can_traverse rover0 waypoint13 waypoint16)
	(can_traverse rover0 waypoint16 waypoint14)
	(can_traverse rover0 waypoint14 waypoint16)
	(can_traverse rover0 waypoint16 waypoint20)
	(can_traverse rover0 waypoint20 waypoint16)
	(can_traverse rover0 waypoint16 waypoint28)
	(can_traverse rover0 waypoint28 waypoint16)
	(can_traverse rover0 waypoint18 waypoint8)
	(can_traverse rover0 waypoint8 waypoint18)
	(can_traverse rover0 waypoint18 waypoint21)
	(can_traverse rover0 waypoint21 waypoint18)
	(can_traverse rover0 waypoint18 waypoint24)
	(can_traverse rover0 waypoint24 waypoint18)
	(can_traverse rover0 waypoint18 waypoint29)
	(can_traverse rover0 waypoint29 waypoint18)
	(can_traverse rover0 waypoint19 waypoint5)
	(can_traverse rover0 waypoint5 waypoint19)
	(can_traverse rover0 waypoint27 waypoint4)
	(can_traverse rover0 waypoint4 waypoint27)
	(can_traverse rover0 waypoint2 waypoint9)
	(can_traverse rover0 waypoint9 waypoint2)
	(can_traverse rover0 waypoint3 waypoint26)
	(can_traverse rover0 waypoint26 waypoint3)
	(can_traverse rover0 waypoint11 waypoint10)
	(can_traverse rover0 waypoint10 waypoint11)
	(at rover1 waypoint22)
	(available rover1)
	(store_of rover1store rover1)
	(empty rover1store)
	(equipped_for_rock_analysis rover1)
	(equipped_for_imaging rover1)
	(can_traverse rover1 waypoint22 waypoint5)
	(can_traverse rover1 waypoint5 waypoint22)
	(can_traverse rover1 waypoint22 waypoint6)
	(can_traverse rover1 waypoint6 waypoint22)
	(can_traverse rover1 waypoint22 waypoint8)
	(can_traverse rover1 waypoint8 waypoint22)
	(can_traverse rover1 waypoint22 waypoint14)
	(can_traverse rover1 waypoint14 waypoint22)
	(can_traverse rover1 waypoint22 waypoint24)
	(can_traverse rover1 waypoint24 waypoint22)
	(can_traverse rover1 waypoint5 waypoint2)
	(can_traverse rover1 waypoint2 waypoint5)
	(can_traverse rover1 waypoint5 waypoint11)
	(can_traverse rover1 waypoint11 waypoint5)
	(can_traverse rover1 waypoint5 waypoint12)
	(can_traverse rover1 waypoint12 waypoint5)
	(can_traverse rover1 waypoint5 waypoint13)
	(can_traverse rover1 waypoint13 waypoint5)
	(can_traverse rover1 waypoint5 waypoint19)
	(can_traverse rover1 waypoint19 waypoint5)
	(can_traverse rover1 waypoint5 waypoint25)
	(can_traverse rover1 waypoint25 waypoint5)
	(can_traverse rover1 waypoint6 waypoint1)
	(can_traverse rover1 waypoint1 waypoint6)
	(can_traverse rover1 waypoint6 waypoint10)
	(can_traverse rover1 waypoint10 waypoint6)
	(can_traverse rover1 waypoint6 waypoint20)
	(can_traverse rover1 waypoint20 waypoint6)
	(can_traverse rover1 waypoint6 waypoint26)
	(can_traverse rover1 waypoint26 waypoint6)
	(can_traverse rover1 waypoint8 waypoint7)
	(can_traverse rover1 waypoint7 waypoint8)
	(can_traverse rover1 waypoint8 waypoint18)
	(can_traverse rover1 waypoint18 waypoint8)
	(can_traverse rover1 waypoint8 waypoint23)
	(can_traverse rover1 waypoint23 waypoint8)
	(can_traverse rover1 waypoint14 waypoint16)
	(can_traverse rover1 waypoint16 waypoint14)
	(can_traverse rover1 waypoint14 waypoint21)
	(can_traverse rover1 waypoint21 waypoint14)
	(can_traverse rover1 waypoint24 waypoint4)
	(can_traverse rover1 waypoint4 waypoint24)
	(can_traverse rover1 waypoint24 waypoint9)
	(can_traverse rover1 waypoint9 waypoint24)
	(can_traverse rover1 waypoint24 waypoint17)
	(can_traverse rover1 waypoint17 waypoint24)
	(can_traverse rover1 waypoint24 waypoint28)
	(can_traverse rover1 waypoint28 waypoint24)
	(can_traverse rover1 waypoint24 waypoint29)
	(can_traverse rover1 waypoint29 waypoint24)
	(can_traverse rover1 waypoint2 waypoint27)
	(can_traverse rover1 waypoint27 waypoint2)
	(can_traverse rover1 waypoint11 waypoint15)
	(can_traverse rover1 waypoint15 waypoint11)
	(can_traverse rover1 waypoint12 waypoint0)
	(can_traverse rover1 waypoint0 waypoint12)
	(can_traverse rover1 waypoint19 waypoint3)
	(can_traverse rover1 waypoint3 waypoint19)
	(at rover2 waypoint10)
	(available rover2)
	(store_of rover2store rover2)
	(empty rover2store)
	(equipped_for_soil_analysis rover2)
	(equipped_for_imaging rover2)
	(can_traverse rover2 waypoint10 waypoint6)
	(can_traverse rover2 waypoint6 waypoint10)
	(can_traverse rover2 waypoint10 waypoint11)
	(can_traverse rover2 waypoint11 waypoint10)
	(can_traverse rover2 waypoint10 waypoint13)
	(can_traverse rover2 waypoint13 waypoint10)
	(can_traverse rover2 waypoint10 waypoint17)
	(can_traverse rover2 waypoint17 waypoint10)
	(can_traverse rover2 waypoint6 waypoint15)
	(can_traverse rover2 waypoint15 waypoint6)
	(can_traverse rover2 waypoint6 waypoint20)
	(can_traverse rover2 waypoint20 waypoint6)
	(can_traverse rover2 waypoint6 waypoint22)
	(can_traverse rover2 waypoint22 waypoint6)
	(can_traverse rover2 waypoint6 waypoint24)
	(can_traverse rover2 waypoint24 waypoint6)
	(can_traverse rover2 waypoint6 waypoint25)
	(can_traverse rover2 waypoint25 waypoint6)
	(can_traverse rover2 waypoint6 waypoint26)
	(can_traverse rover2 waypoint26 waypoint6)
	(can_traverse rover2 waypoint11 waypoint5)
	(can_traverse rover2 waypoint5 waypoint11)
	(can_traverse rover2 waypoint11 waypoint9)
	(can_traverse rover2 waypoint9 waypoint11)
	(can_traverse rover2 waypoint11 waypoint12)
	(can_traverse rover2 waypoint12 waypoint11)
	(can_traverse rover2 waypoint11 waypoint21)
	(can_traverse rover2 waypoint21 waypoint11)
	(can_traverse rover2 waypoint11 waypoint28)
	(can_traverse rover2 waypoint28 waypoint11)
	(can_traverse rover2 waypoint13 waypoint16)
	(can_traverse rover2 waypoint16 waypoint13)
	(can_traverse rover2 waypoint13 waypoint18)
	(can_traverse rover2 waypoint18 waypoint13)
	(can_traverse rover2 waypoint15 waypoint0)
	(can_traverse rover2 waypoint0 waypoint15)
	(can_traverse rover2 waypoint15 waypoint3)
	(can_traverse rover2 waypoint3 waypoint15)
	(can_traverse rover2 waypoint15 waypoint27)
	(can_traverse rover2 waypoint27 waypoint15)
	(can_traverse rover2 waypoint20 waypoint14)
	(can_traverse rover2 waypoint14 waypoint20)
	(can_traverse rover2 waypoint20 waypoint29)
	(can_traverse rover2 waypoint29 waypoint20)
	(can_traverse rover2 waypoint22 waypoint8)
	(can_traverse rover2 waypoint8 waypoint22)
	(can_traverse rover2 waypoint25 waypoint7)
	(can_traverse rover2 waypoint7 waypoint25)
	(can_traverse rover2 waypoint25 waypoint19)
	(can_traverse rover2 waypoint19 waypoint25)
	(can_traverse rover2 waypoint26 waypoint2)
	(can_traverse rover2 waypoint2 waypoint26)
	(can_traverse rover2 waypoint26 waypoint4)
	(can_traverse rover2 waypoint4 waypoint26)
	(on_board camera0 rover1)
	(calibration_target camera0 objective4)
	(supports camera0 colour)
	(on_board camera1 rover0)
	(calibration_target camera1 objective3)
	(supports camera1 colour)
	(on_board camera2 rover1)
	(calibration_target camera2 objective5)
	(supports camera2 low_res)
	(on_board camera3 rover2)
	(calibration_target camera3 objective0)
	(supports camera3 low_res)
	(on_board camera4 rover0)
	(calibration_target camera4 objective1)
	(supports camera4 high_res)
	(supports camera4 low_res)
	(visible_from objective0 waypoint6)
	(visible_from objective0 waypoint9)
	(visible_from objective0 waypoint11)
	(visible_from objective0 waypoint14)
	(visible_from objective0 waypoint19)
	(visible_from objective0 waypoint21)
	(visible_from objective0 waypoint26)
	(visible_from objective1 waypoint0)
	(visible_from objective1 waypoint3)
	(visible_from objective1 waypoint5)
	(visible_from objective1 waypoint6)
	(visible_from objective1 waypoint11)
	(visible_from objective1 waypoint12)
	(visible_from objective1 waypoint16)
	(visible_from objective1 waypoint17)
	(visible_from objective1 waypoint18)
	(visible_from objective1 waypoint26)
	(visible_from objective1 waypoint27)
	(visible_from objective1 waypoint28)
	(visible_from objective2 waypoint0)
	(visible_from objective2 waypoint1)
	(visible_from objective2 waypoint3)
	(visible_from objective2 waypoint4)
	(visible_from objective2 waypoint6)
	(visible_from objective2 waypoint7)
	(visible_from objective2 waypoint9)
	(visible_from objective2 waypoint10)
	(visible_from objective2 waypoint12)
	(visible_from objective2 waypoint13)
	(visible_from objective2 waypoint15)
	(visible_from objective2 waypoint16)
	(visible_from objective2 waypoint18)
	(visible_from objective2 waypoint21)
	(visible_from objective2 waypoint24)
	(visible_from objective2 waypoint27)
	(visible_from objective2 waypoint29)
	(visible_from objective3 waypoint0)
	(visible_from objective3 waypoint2)
	(visible_from objective3 waypoint3)
	(visible_from objective3 waypoint7)
	(visible_from objective3 waypoint8)
	(visible_from objective3 waypoint9)
	(visible_from objective3 waypoint10)
	(visible_from objective3 waypoint12)
	(visible_from objective3 waypoint17)
	(visible_from objective3 waypoint22)
	(visible_from objective3 waypoint29)
	(visible_from objective4 waypoint10)
	(visible_from objective4 waypoint16)
	(visible_from objective4 waypoint17)
	(visible_from objective4 waypoint25)
	(visible_from objective5 waypoint1)
	(visible_from objective5 waypoint3)
	(visible_from objective5 waypoint4)
	(visible_from objective5 waypoint5)
	(visible_from objective5 waypoint7)
	(visible_from objective5 waypoint8)
	(visible_from objective5 waypoint9)
	(visible_from objective5 waypoint10)
	(visible_from objective5 waypoint16)
	(visible_from objective5 waypoint18)
	(visible_from objective5 waypoint23)
	(visible_from objective5 waypoint24)
	(visible_from objective5 waypoint25)
	(visible_from objective5 waypoint28)
	(visible_from objective5 waypoint29)
)

(:goal (and
(communicated_soil_data waypoint11)
(communicated_soil_data waypoint21)
(communicated_soil_data waypoint9)
(communicated_soil_data waypoint23)
(communicated_soil_data waypoint7)
(communicated_soil_data waypoint20)
(communicated_rock_data waypoint5)
(communicated_rock_data waypoint6)
(communicated_rock_data waypoint26)
(communicated_rock_data waypoint21)
(communicated_rock_data waypoint1)
(communicated_rock_data waypoint2)
(communicated_rock_data waypoint16)
(communicated_rock_data waypoint28)
(communicated_image_data objective5 colour)
(communicated_image_data objective2 low_res)
(communicated_image_data objective0 colour)
(communicated_image_data objective1 colour)
(communicated_image_data objective1 low_res)
(communicated_image_data objective3 low_res)
(communicated_image_data objective3 colour)
(communicated_image_data objective4 low_res)
(communicated_image_data objective1 high_res)
(communicated_image_data objective5 low_res)
	)
)
)
