(define (problem roverprob5) (:domain Rover)
(:objects
	general - Lander
	colour high_res low_res - Mode
	rover0 rover1 rover2 rover3 - Rover
	rover0store rover1store rover2store rover3store - Store
	waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 waypoint7 waypoint8 waypoint9 waypoint10 waypoint11 waypoint12 waypoint13 waypoint14 waypoint15 waypoint16 waypoint17 waypoint18 waypoint19 waypoint20 waypoint21 waypoint22 waypoint23 waypoint24 waypoint25 waypoint26 waypoint27 waypoint28 waypoint29 waypoint30 waypoint31 waypoint32 waypoint33 waypoint34 waypoint35 waypoint36 waypoint37 waypoint38 waypoint39 waypoint40 waypoint41 waypoint42 waypoint43 waypoint44 waypoint45 waypoint46 waypoint47 waypoint48 waypoint49 waypoint50 waypoint51 waypoint52 waypoint53 waypoint54 waypoint55 waypoint56 waypoint57 waypoint58 waypoint59 - Waypoint
	camera0 camera1 camera2 camera3 camera4 camera5 camera6 - Camera
	objective0 objective1 objective2 objective3 objective4 objective5 objective6 objective7 - Objective
	)
(:init
	(visible waypoint0 waypoint5)
	(visible waypoint5 waypoint0)
	(visible waypoint0 waypoint13)
	(visible waypoint13 waypoint0)
	(visible waypoint0 waypoint16)
	(visible waypoint16 waypoint0)
	(visible waypoint0 waypoint18)
	(visible waypoint18 waypoint0)
	(visible waypoint0 waypoint28)
	(visible waypoint28 waypoint0)
	(visible waypoint0 waypoint55)
	(visible waypoint55 waypoint0)
	(visible waypoint1 waypoint17)
	(visible waypoint17 waypoint1)
	(visible waypoint1 waypoint21)
	(visible waypoint21 waypoint1)
	(visible waypoint1 waypoint24)
	(visible waypoint24 waypoint1)
	(visible waypoint1 waypoint35)
	(visible waypoint35 waypoint1)
	(visible waypoint2 waypoint6)
	(visible waypoint6 waypoint2)
	(visible waypoint2 waypoint8)
	(visible waypoint8 waypoint2)
	(visible waypoint2 waypoint10)
	(visible waypoint10 waypoint2)
	(visible waypoint2 waypoint11)
	(visible waypoint11 waypoint2)
	(visible waypoint2 waypoint28)
	(visible waypoint28 waypoint2)
	(visible waypoint2 waypoint32)
	(visible waypoint32 waypoint2)
	(visible waypoint2 waypoint33)
	(visible waypoint33 waypoint2)
	(visible waypoint2 waypoint40)
	(visible waypoint40 waypoint2)
	(visible waypoint2 waypoint47)
	(visible waypoint47 waypoint2)
	(visible waypoint2 waypoint49)
	(visible waypoint49 waypoint2)
	(visible waypoint3 waypoint56)
	(visible waypoint56 waypoint3)
	(visible waypoint4 waypoint13)
	(visible waypoint13 waypoint4)
	(visible waypoint4 waypoint24)
	(visible waypoint24 waypoint4)
	(visible waypoint4 waypoint37)
	(visible waypoint37 waypoint4)
	(visible waypoint4 waypoint49)
	(visible waypoint49 waypoint4)
	(visible waypoint4 waypoint50)
	(visible waypoint50 waypoint4)
	(visible waypoint5 waypoint2)
	(visible waypoint2 waypoint5)
	(visible waypoint5 waypoint10)
	(visible waypoint10 waypoint5)
	(visible waypoint5 waypoint56)
	(visible waypoint56 waypoint5)
	(visible waypoint6 waypoint5)
	(visible waypoint5 waypoint6)
	(visible waypoint6 waypoint14)
	(visible waypoint14 waypoint6)
	(visible waypoint6 waypoint21)
	(visible waypoint21 waypoint6)
	(visible waypoint6 waypoint22)
	(visible waypoint22 waypoint6)
	(visible waypoint6 waypoint32)
	(visible waypoint32 waypoint6)
	(visible waypoint6 waypoint44)
	(visible waypoint44 waypoint6)
	(visible waypoint6 waypoint47)
	(visible waypoint47 waypoint6)
	(visible waypoint6 waypoint52)
	(visible waypoint52 waypoint6)
	(visible waypoint6 waypoint58)
	(visible waypoint58 waypoint6)
	(visible waypoint7 waypoint1)
	(visible waypoint1 waypoint7)
	(visible waypoint7 waypoint12)
	(visible waypoint12 waypoint7)
	(visible waypoint7 waypoint18)
	(visible waypoint18 waypoint7)
	(visible waypoint7 waypoint22)
	(visible waypoint22 waypoint7)
	(visible waypoint7 waypoint29)
	(visible waypoint29 waypoint7)
	(visible waypoint7 waypoint34)
	(visible waypoint34 waypoint7)
	(visible waypoint7 waypoint53)
	(visible waypoint53 waypoint7)
	(visible waypoint8 waypoint0)
	(visible waypoint0 waypoint8)
	(visible waypoint8 waypoint3)
	(visible waypoint3 waypoint8)
	(visible waypoint8 waypoint4)
	(visible waypoint4 waypoint8)
	(visible waypoint8 waypoint21)
	(visible waypoint21 waypoint8)
	(visible waypoint8 waypoint31)
	(visible waypoint31 waypoint8)
	(visible waypoint8 waypoint34)
	(visible waypoint34 waypoint8)
	(visible waypoint8 waypoint48)
	(visible waypoint48 waypoint8)
	(visible waypoint8 waypoint49)
	(visible waypoint49 waypoint8)
	(visible waypoint9 waypoint13)
	(visible waypoint13 waypoint9)
	(visible waypoint9 waypoint35)
	(visible waypoint35 waypoint9)
	(visible waypoint9 waypoint41)
	(visible waypoint41 waypoint9)
	(visible waypoint9 waypoint53)
	(visible waypoint53 waypoint9)
	(visible waypoint10 waypoint21)
	(visible waypoint21 waypoint10)
	(visible waypoint10 waypoint28)
	(visible waypoint28 waypoint10)
	(visible waypoint10 waypoint51)
	(visible waypoint51 waypoint10)
	(visible waypoint10 waypoint58)
	(visible waypoint58 waypoint10)
	(visible waypoint11 waypoint44)
	(visible waypoint44 waypoint11)
	(visible waypoint12 waypoint0)
	(visible waypoint0 waypoint12)
	(visible waypoint12 waypoint24)
	(visible waypoint24 waypoint12)
	(visible waypoint12 waypoint29)
	(visible waypoint29 waypoint12)
	(visible waypoint13 waypoint2)
	(visible waypoint2 waypoint13)
	(visible waypoint13 waypoint10)
	(visible waypoint10 waypoint13)
	(visible waypoint13 waypoint14)
	(visible waypoint14 waypoint13)
	(visible waypoint13 waypoint27)
	(visible waypoint27 waypoint13)
	(visible waypoint13 waypoint28)
	(visible waypoint28 waypoint13)
	(visible waypoint13 waypoint48)
	(visible waypoint48 waypoint13)
	(visible waypoint14 waypoint30)
	(visible waypoint30 waypoint14)
	(visible waypoint14 waypoint38)
	(visible waypoint38 waypoint14)
	(visible waypoint14 waypoint42)
	(visible waypoint42 waypoint14)
	(visible waypoint15 waypoint6)
	(visible waypoint6 waypoint15)
	(visible waypoint15 waypoint51)
	(visible waypoint51 waypoint15)
	(visible waypoint16 waypoint2)
	(visible waypoint2 waypoint16)
	(visible waypoint16 waypoint26)
	(visible waypoint26 waypoint16)
	(visible waypoint16 waypoint48)
	(visible waypoint48 waypoint16)
	(visible waypoint16 waypoint59)
	(visible waypoint59 waypoint16)
	(visible waypoint18 waypoint14)
	(visible waypoint14 waypoint18)
	(visible waypoint18 waypoint27)
	(visible waypoint27 waypoint18)
	(visible waypoint18 waypoint34)
	(visible waypoint34 waypoint18)
	(visible waypoint18 waypoint46)
	(visible waypoint46 waypoint18)
	(visible waypoint19 waypoint21)
	(visible waypoint21 waypoint19)
	(visible waypoint19 waypoint52)
	(visible waypoint52 waypoint19)
	(visible waypoint19 waypoint54)
	(visible waypoint54 waypoint19)
	(visible waypoint20 waypoint9)
	(visible waypoint9 waypoint20)
	(visible waypoint20 waypoint13)
	(visible waypoint13 waypoint20)
	(visible waypoint20 waypoint29)
	(visible waypoint29 waypoint20)
	(visible waypoint20 waypoint36)
	(visible waypoint36 waypoint20)
	(visible waypoint20 waypoint58)
	(visible waypoint58 waypoint20)
	(visible waypoint21 waypoint3)
	(visible waypoint3 waypoint21)
	(visible waypoint21 waypoint16)
	(visible waypoint16 waypoint21)
	(visible waypoint21 waypoint32)
	(visible waypoint32 waypoint21)
	(visible waypoint21 waypoint36)
	(visible waypoint36 waypoint21)
	(visible waypoint21 waypoint40)
	(visible waypoint40 waypoint21)
	(visible waypoint21 waypoint53)
	(visible waypoint53 waypoint21)
	(visible waypoint22 waypoint8)
	(visible waypoint8 waypoint22)
	(visible waypoint22 waypoint36)
	(visible waypoint36 waypoint22)
	(visible waypoint22 waypoint45)
	(visible waypoint45 waypoint22)
	(visible waypoint22 waypoint58)
	(visible waypoint58 waypoint22)
	(visible waypoint23 waypoint5)
	(visible waypoint5 waypoint23)
	(visible waypoint23 waypoint11)
	(visible waypoint11 waypoint23)
	(visible waypoint23 waypoint24)
	(visible waypoint24 waypoint23)
	(visible waypoint23 waypoint42)
	(visible waypoint42 waypoint23)
	(visible waypoint23 waypoint47)
	(visible waypoint47 waypoint23)
	(visible waypoint23 waypoint59)
	(visible waypoint59 waypoint23)
	(visible waypoint24 waypoint0)
	(visible waypoint0 waypoint24)
	(visible waypoint24 waypoint9)
	(visible waypoint9 waypoint24)
	(visible waypoint24 waypoint14)
	(visible waypoint14 waypoint24)
	(visible waypoint24 waypoint15)
	(visible waypoint15 waypoint24)
	(visible waypoint24 waypoint16)
	(visible waypoint16 waypoint24)
	(visible waypoint24 waypoint29)
	(visible waypoint29 waypoint24)
	(visible waypoint24 waypoint38)
	(visible waypoint38 waypoint24)
	(visible waypoint24 waypoint57)
	(visible waypoint57 waypoint24)
	(visible waypoint25 waypoint12)
	(visible waypoint12 waypoint25)
	(visible waypoint25 waypoint13)
	(visible waypoint13 waypoint25)
	(visible waypoint25 waypoint17)
	(visible waypoint17 waypoint25)
	(visible waypoint25 waypoint21)
	(visible waypoint21 waypoint25)
	(visible waypoint25 waypoint29)
	(visible waypoint29 waypoint25)
	(visible waypoint25 waypoint32)
	(visible waypoint32 waypoint25)
	(visible waypoint25 waypoint39)
	(visible waypoint39 waypoint25)
	(visible waypoint25 waypoint43)
	(visible waypoint43 waypoint25)
	(visible waypoint26 waypoint6)
	(visible waypoint6 waypoint26)
	(visible waypoint26 waypoint24)
	(visible waypoint24 waypoint26)
	(visible waypoint26 waypoint43)
	(visible waypoint43 waypoint26)
	(visible waypoint27 waypoint1)
	(visible waypoint1 waypoint27)
	(visible waypoint27 waypoint17)
	(visible waypoint17 waypoint27)
	(visible waypoint27 waypoint19)
	(visible waypoint19 waypoint27)
	(visible waypoint27 waypoint20)
	(visible waypoint20 waypoint27)
	(visible waypoint27 waypoint29)
	(visible waypoint29 waypoint27)
	(visible waypoint27 waypoint42)
	(visible waypoint42 waypoint27)
	(visible waypoint27 waypoint49)
	(visible waypoint49 waypoint27)
	(visible waypoint27 waypoint58)
	(visible waypoint58 waypoint27)
	(visible waypoint28 waypoint1)
	(visible waypoint1 waypoint28)
	(visible waypoint28 waypoint6)
	(visible waypoint6 waypoint28)
	(visible waypoint28 waypoint7)
	(visible waypoint7 waypoint28)
	(visible waypoint28 waypoint11)
	(visible waypoint11 waypoint28)
	(visible waypoint28 waypoint18)
	(visible waypoint18 waypoint28)
	(visible waypoint28 waypoint32)
	(visible waypoint32 waypoint28)
	(visible waypoint28 waypoint34)
	(visible waypoint34 waypoint28)
	(visible waypoint28 waypoint38)
	(visible waypoint38 waypoint28)
	(visible waypoint28 waypoint56)
	(visible waypoint56 waypoint28)
	(visible waypoint28 waypoint58)
	(visible waypoint58 waypoint28)
	(visible waypoint29 waypoint10)
	(visible waypoint10 waypoint29)
	(visible waypoint29 waypoint53)
	(visible waypoint53 waypoint29)
	(visible waypoint30 waypoint4)
	(visible waypoint4 waypoint30)
	(visible waypoint30 waypoint6)
	(visible waypoint6 waypoint30)
	(visible waypoint30 waypoint19)
	(visible waypoint19 waypoint30)
	(visible waypoint30 waypoint24)
	(visible waypoint24 waypoint30)
	(visible waypoint30 waypoint29)
	(visible waypoint29 waypoint30)
	(visible waypoint30 waypoint36)
	(visible waypoint36 waypoint30)
	(visible waypoint31 waypoint11)
	(visible waypoint11 waypoint31)
	(visible waypoint31 waypoint12)
	(visible waypoint12 waypoint31)
	(visible waypoint31 waypoint16)
	(visible waypoint16 waypoint31)
	(visible waypoint31 waypoint18)
	(visible waypoint18 waypoint31)
	(visible waypoint31 waypoint22)
	(visible waypoint22 waypoint31)
	(visible waypoint31 waypoint58)
	(visible waypoint58 waypoint31)
	(visible waypoint32 waypoint0)
	(visible waypoint0 waypoint32)
	(visible waypoint32 waypoint11)
	(visible waypoint11 waypoint32)
	(visible waypoint32 waypoint26)
	(visible waypoint26 waypoint32)
	(visible waypoint32 waypoint31)
	(visible waypoint31 waypoint32)
	(visible waypoint32 waypoint40)
	(visible waypoint40 waypoint32)
	(visible waypoint32 waypoint51)
	(visible waypoint51 waypoint32)
	(visible waypoint32 waypoint57)
	(visible waypoint57 waypoint32)
	(visible waypoint32 waypoint59)
	(visible waypoint59 waypoint32)
	(visible waypoint33 waypoint10)
	(visible waypoint10 waypoint33)
	(visible waypoint33 waypoint24)
	(visible waypoint24 waypoint33)
	(visible waypoint34 waypoint10)
	(visible waypoint10 waypoint34)
	(visible waypoint34 waypoint31)
	(visible waypoint31 waypoint34)
	(visible waypoint35 waypoint5)
	(visible waypoint5 waypoint35)
	(visible waypoint35 waypoint6)
	(visible waypoint6 waypoint35)
	(visible waypoint35 waypoint40)
	(visible waypoint40 waypoint35)
	(visible waypoint35 waypoint44)
	(visible waypoint44 waypoint35)
	(visible waypoint36 waypoint2)
	(visible waypoint2 waypoint36)
	(visible waypoint36 waypoint19)
	(visible waypoint19 waypoint36)
	(visible waypoint36 waypoint46)
	(visible waypoint46 waypoint36)
	(visible waypoint37 waypoint2)
	(visible waypoint2 waypoint37)
	(visible waypoint37 waypoint5)
	(visible waypoint5 waypoint37)
	(visible waypoint37 waypoint12)
	(visible waypoint12 waypoint37)
	(visible waypoint38 waypoint10)
	(visible waypoint10 waypoint38)
	(visible waypoint38 waypoint45)
	(visible waypoint45 waypoint38)
	(visible waypoint38 waypoint49)
	(visible waypoint49 waypoint38)
	(visible waypoint39 waypoint13)
	(visible waypoint13 waypoint39)
	(visible waypoint39 waypoint18)
	(visible waypoint18 waypoint39)
	(visible waypoint39 waypoint30)
	(visible waypoint30 waypoint39)
	(visible waypoint39 waypoint35)
	(visible waypoint35 waypoint39)
	(visible waypoint39 waypoint53)
	(visible waypoint53 waypoint39)
	(visible waypoint40 waypoint11)
	(visible waypoint11 waypoint40)
	(visible waypoint40 waypoint13)
	(visible waypoint13 waypoint40)
	(visible waypoint40 waypoint48)
	(visible waypoint48 waypoint40)
	(visible waypoint40 waypoint55)
	(visible waypoint55 waypoint40)
	(visible waypoint41 waypoint11)
	(visible waypoint11 waypoint41)
	(visible waypoint41 waypoint17)
	(visible waypoint17 waypoint41)
	(visible waypoint41 waypoint53)
	(visible waypoint53 waypoint41)
	(visible waypoint42 waypoint0)
	(visible waypoint0 waypoint42)
	(visible waypoint42 waypoint7)
	(visible waypoint7 waypoint42)
	(visible waypoint42 waypoint13)
	(visible waypoint13 waypoint42)
	(visible waypoint42 waypoint26)
	(visible waypoint26 waypoint42)
	(visible waypoint42 waypoint29)
	(visible waypoint29 waypoint42)
	(visible waypoint42 waypoint50)
	(visible waypoint50 waypoint42)
	(visible waypoint42 waypoint52)
	(visible waypoint52 waypoint42)
	(visible waypoint42 waypoint58)
	(visible waypoint58 waypoint42)
	(visible waypoint43 waypoint9)
	(visible waypoint9 waypoint43)
	(visible waypoint43 waypoint11)
	(visible waypoint11 waypoint43)
	(visible waypoint43 waypoint31)
	(visible waypoint31 waypoint43)
	(visible waypoint43 waypoint52)
	(visible waypoint52 waypoint43)
	(visible waypoint44 waypoint33)
	(visible waypoint33 waypoint44)
	(visible waypoint44 waypoint42)
	(visible waypoint42 waypoint44)
	(visible waypoint44 waypoint45)
	(visible waypoint45 waypoint44)
	(visible waypoint45 waypoint32)
	(visible waypoint32 waypoint45)
	(visible waypoint45 waypoint33)
	(visible waypoint33 waypoint45)
	(visible waypoint45 waypoint41)
	(visible waypoint41 waypoint45)
	(visible waypoint45 waypoint43)
	(visible waypoint43 waypoint45)
	(visible waypoint46 waypoint0)
	(visible waypoint0 waypoint46)
	(visible waypoint46 waypoint16)
	(visible waypoint16 waypoint46)
	(visible waypoint46 waypoint21)
	(visible waypoint21 waypoint46)
	(visible waypoint46 waypoint29)
	(visible waypoint29 waypoint46)
	(visible waypoint46 waypoint30)
	(visible waypoint30 waypoint46)
	(visible waypoint46 waypoint35)
	(visible waypoint35 waypoint46)
	(visible waypoint47 waypoint9)
	(visible waypoint9 waypoint47)
	(visible waypoint47 waypoint16)
	(visible waypoint16 waypoint47)
	(visible waypoint47 waypoint22)
	(visible waypoint22 waypoint47)
	(visible waypoint47 waypoint46)
	(visible waypoint46 waypoint47)
	(visible waypoint48 waypoint25)
	(visible waypoint25 waypoint48)
	(visible waypoint48 waypoint26)
	(visible waypoint26 waypoint48)
	(visible waypoint48 waypoint33)
	(visible waypoint33 waypoint48)
	(visible waypoint48 waypoint43)
	(visible waypoint43 waypoint48)
	(visible waypoint49 waypoint31)
	(visible waypoint31 waypoint49)
	(visible waypoint49 waypoint42)
	(visible waypoint42 waypoint49)
	(visible waypoint49 waypoint47)
	(visible waypoint47 waypoint49)
	(visible waypoint49 waypoint52)
	(visible waypoint52 waypoint49)
	(visible waypoint50 waypoint39)
	(visible waypoint39 waypoint50)
	(visible waypoint50 waypoint44)
	(visible waypoint44 waypoint50)
	(visible waypoint50 waypoint47)
	(visible waypoint47 waypoint50)
	(visible waypoint50 waypoint53)
	(visible waypoint53 waypoint50)
	(visible waypoint51 waypoint22)
	(visible waypoint22 waypoint51)
	(visible waypoint52 waypoint1)
	(visible waypoint1 waypoint52)
	(visible waypoint52 waypoint31)
	(visible waypoint31 waypoint52)
	(visible waypoint52 waypoint41)
	(visible waypoint41 waypoint52)
	(visible waypoint52 waypoint58)
	(visible waypoint58 waypoint52)
	(visible waypoint53 waypoint34)
	(visible waypoint34 waypoint53)
	(visible waypoint53 waypoint43)
	(visible waypoint43 waypoint53)
	(visible waypoint54 waypoint5)
	(visible waypoint5 waypoint54)
	(visible waypoint54 waypoint37)
	(visible waypoint37 waypoint54)
	(visible waypoint55 waypoint15)
	(visible waypoint15 waypoint55)
	(visible waypoint55 waypoint29)
	(visible waypoint29 waypoint55)
	(visible waypoint55 waypoint44)
	(visible waypoint44 waypoint55)
	(visible waypoint55 waypoint45)
	(visible waypoint45 waypoint55)
	(visible waypoint56 waypoint52)
	(visible waypoint52 waypoint56)
	(visible waypoint56 waypoint54)
	(visible waypoint54 waypoint56)
	(visible waypoint57 waypoint20)
	(visible waypoint20 waypoint57)
	(visible waypoint57 waypoint23)
	(visible waypoint23 waypoint57)
	(visible waypoint57 waypoint25)
	(visible waypoint25 waypoint57)
	(visible waypoint57 waypoint29)
	(visible waypoint29 waypoint57)
	(visible waypoint57 waypoint40)
	(visible waypoint40 waypoint57)
	(visible waypoint57 waypoint49)
	(visible waypoint49 waypoint57)
	(visible waypoint58 waypoint0)
	(visible waypoint0 waypoint58)
	(visible waypoint58 waypoint13)
	(visible waypoint13 waypoint58)
	(visible waypoint58 waypoint19)
	(visible waypoint19 waypoint58)
	(visible waypoint58 waypoint24)
	(visible waypoint24 waypoint58)
	(visible waypoint59 waypoint4)
	(visible waypoint4 waypoint59)
	(visible waypoint59 waypoint5)
	(visible waypoint5 waypoint59)
	(visible waypoint59 waypoint7)
	(visible waypoint7 waypoint59)
	(visible waypoint59 waypoint11)
	(visible waypoint11 waypoint59)
	(visible waypoint59 waypoint29)
	(visible waypoint29 waypoint59)
	(visible waypoint59 waypoint33)
	(visible waypoint33 waypoint59)
	(visible waypoint59 waypoint50)
	(visible waypoint50 waypoint59)
	(visible waypoint59 waypoint56)
	(visible waypoint56 waypoint59)
	(at_soil_sample waypoint1)
	(at_soil_sample waypoint2)
	(at_soil_sample waypoint3)
	(at_rock_sample waypoint3)
	(at_rock_sample waypoint4)
	(at_soil_sample waypoint5)
	(at_soil_sample waypoint6)
	(at_rock_sample waypoint6)
	(at_soil_sample waypoint7)
	(at_rock_sample waypoint8)
	(at_soil_sample waypoint9)
	(at_rock_sample waypoint9)
	(at_rock_sample waypoint10)
	(at_soil_sample waypoint11)
	(at_soil_sample waypoint12)
	(at_soil_sample waypoint13)
	(at_rock_sample waypoint13)
	(at_rock_sample waypoint14)
	(at_rock_sample waypoint15)
	(at_soil_sample waypoint17)
	(at_rock_sample waypoint17)
	(at_soil_sample waypoint19)
	(at_rock_sample waypoint19)
	(at_soil_sample waypoint20)
	(at_rock_sample waypoint21)
	(at_soil_sample waypoint22)
	(at_rock_sample waypoint22)
	(at_rock_sample waypoint25)
	(at_soil_sample waypoint26)
	(at_soil_sample waypoint27)
	(at_rock_sample waypoint27)
	(at_rock_sample waypoint28)
	(at_soil_sample waypoint29)
	(at_rock_sample waypoint29)
	(at_soil_sample waypoint30)
	(at_rock_sample waypoint31)
	(at_rock_sample waypoint34)
	(at_soil_sample waypoint35)
	(at_rock_sample waypoint35)
	(at_rock_sample waypoint36)
	(at_soil_sample waypoint37)
	(at_soil_sample waypoint39)
	(at_rock_sample waypoint40)
	(at_rock_sample waypoint41)
	(at_rock_sample waypoint42)
	(at_soil_sample waypoint44)
	(at_soil_sample waypoint45)
	(at_rock_sample waypoint45)
	(at_rock_sample waypoint46)
	(at_rock_sample waypoint47)
	(at_soil_sample waypoint48)
	(at_rock_sample waypoint48)
	(at_rock_sample waypoint49)
	(at_rock_sample waypoint50)
	(at_soil_sample waypoint51)
	(at_rock_sample waypoint51)
	(at_soil_sample waypoint52)
	(at_soil_sample waypoint53)
	(at_soil_sample waypoint54)
	(at_rock_sample waypoint55)
	(at_soil_sample waypoint56)
	(at_soil_sample waypoint57)
	(at_rock_sample waypoint57)
	(at_soil_sample waypoint59)
	(at_rock_sample waypoint59)
	(at_lander general waypoint38)
	(channel_free general)
	(at rover0 waypoint24)
	(available rover0)
	(store_of rover0store rover0)
	(empty rover0store)
	(equipped_for_soil_analysis rover0)
	(equipped_for_rock_analysis rover0)
	(equipped_for_imaging rover0)
	(can_traverse rover0 waypoint24 waypoint0)
	(can_traverse rover0 waypoint0 waypoint24)
	(can_traverse rover0 waypoint24 waypoint4)
	(can_traverse rover0 waypoint4 waypoint24)
	(can_traverse rover0 waypoint24 waypoint9)
	(can_traverse rover0 waypoint9 waypoint24)
	(can_traverse rover0 waypoint24 waypoint12)
	(can_traverse rover0 waypoint12 waypoint24)
	(can_traverse rover0 waypoint24 waypoint14)
	(can_traverse rover0 waypoint14 waypoint24)
	(can_traverse rover0 waypoint24 waypoint15)
	(can_traverse rover0 waypoint15 waypoint24)
	(can_traverse rover0 waypoint24 waypoint23)
	(can_traverse rover0 waypoint23 waypoint24)
	(can_traverse rover0 waypoint24 waypoint26)
	(can_traverse rover0 waypoint26 waypoint24)
	(can_traverse rover0 waypoint24 waypoint29)
	(can_traverse rover0 waypoint29 waypoint24)
	(can_traverse rover0 waypoint24 waypoint30)
	(can_traverse rover0 waypoint30 waypoint24)
	(can_traverse rover0 waypoint24 waypoint33)
	(can_traverse rover0 waypoint33 waypoint24)
	(can_traverse rover0 waypoint24 waypoint57)
	(can_traverse rover0 waypoint57 waypoint24)
	(can_traverse rover0 waypoint24 waypoint58)
	(can_traverse rover0 waypoint58 waypoint24)
	(can_traverse rover0 waypoint0 waypoint5)
	(can_traverse rover0 waypoint5 waypoint0)
	(can_traverse rover0 waypoint0 waypoint8)
	(can_traverse rover0 waypoint8 waypoint0)
	(can_traverse rover0 waypoint0 waypoint13)
	(can_traverse rover0 waypoint13 waypoint0)
	(can_traverse rover0 waypoint0 waypoint16)
	(can_traverse rover0 waypoint16 waypoint0)
	(can_traverse rover0 waypoint0 waypoint18)
	(can_traverse rover0 waypoint18 waypoint0)
	(can_traverse rover0 waypoint0 waypoint32)
	(can_traverse rover0 waypoint32 waypoint0)
	(can_traverse rover0 waypoint0 waypoint42)
	(can_traverse rover0 waypoint42 waypoint0)
	(can_traverse rover0 waypoint0 waypoint46)
	(can_traverse rover0 waypoint46 waypoint0)
	(can_traverse rover0 waypoint0 waypoint55)
	(can_traverse rover0 waypoint55 waypoint0)
	(can_traverse rover0 waypoint4 waypoint37)
	(can_traverse rover0 waypoint37 waypoint4)
	(can_traverse rover0 waypoint4 waypoint50)
	(can_traverse rover0 waypoint50 waypoint4)
	(can_traverse rover0 waypoint9 waypoint20)
	(can_traverse rover0 waypoint20 waypoint9)
	(can_traverse rover0 waypoint9 waypoint35)
	(can_traverse rover0 waypoint35 waypoint9)
	(can_traverse rover0 waypoint12 waypoint7)
	(can_traverse rover0 waypoint7 waypoint12)
	(can_traverse rover0 waypoint15 waypoint51)
	(can_traverse rover0 waypoint51 waypoint15)
	(can_traverse rover0 waypoint23 waypoint11)
	(can_traverse rover0 waypoint11 waypoint23)
	(can_traverse rover0 waypoint23 waypoint59)
	(can_traverse rover0 waypoint59 waypoint23)
	(can_traverse rover0 waypoint26 waypoint6)
	(can_traverse rover0 waypoint6 waypoint26)
	(can_traverse rover0 waypoint26 waypoint43)
	(can_traverse rover0 waypoint43 waypoint26)
	(can_traverse rover0 waypoint29 waypoint10)
	(can_traverse rover0 waypoint10 waypoint29)
	(can_traverse rover0 waypoint29 waypoint53)
	(can_traverse rover0 waypoint53 waypoint29)
	(can_traverse rover0 waypoint30 waypoint19)
	(can_traverse rover0 waypoint19 waypoint30)
	(can_traverse rover0 waypoint30 waypoint36)
	(can_traverse rover0 waypoint36 waypoint30)
	(can_traverse rover0 waypoint30 waypoint39)
	(can_traverse rover0 waypoint39 waypoint30)
	(can_traverse rover0 waypoint33 waypoint44)
	(can_traverse rover0 waypoint44 waypoint33)
	(can_traverse rover0 waypoint33 waypoint45)
	(can_traverse rover0 waypoint45 waypoint33)
	(can_traverse rover0 waypoint33 waypoint48)
	(can_traverse rover0 waypoint48 waypoint33)
	(can_traverse rover0 waypoint57 waypoint25)
	(can_traverse rover0 waypoint25 waypoint57)
	(can_traverse rover0 waypoint57 waypoint40)
	(can_traverse rover0 waypoint40 waypoint57)
	(can_traverse rover0 waypoint57 waypoint49)
	(can_traverse rover0 waypoint49 waypoint57)
	(can_traverse rover0 waypoint58 waypoint22)
	(can_traverse rover0 waypoint22 waypoint58)
	(can_traverse rover0 waypoint58 waypoint27)
	(can_traverse rover0 waypoint27 waypoint58)
	(can_traverse rover0 waypoint58 waypoint28)
	(can_traverse rover0 waypoint28 waypoint58)
	(can_traverse rover0 waypoint58 waypoint31)
	(can_traverse rover0 waypoint31 waypoint58)
	(can_traverse rover0 waypoint58 waypoint52)
	(can_traverse rover0 waypoint52 waypoint58)
	(can_traverse rover0 waypoint5 waypoint2)
	(can_traverse rover0 waypoint2 waypoint5)
	(can_traverse rover0 waypoint5 waypoint54)
	(can_traverse rover0 waypoint54 waypoint5)
	(can_traverse rover0 waypoint5 waypoint56)
	(can_traverse rover0 waypoint56 waypoint5)
	(can_traverse rover0 waypoint8 waypoint3)
	(can_traverse rover0 waypoint3 waypoint8)
	(can_traverse rover0 waypoint8 waypoint21)
	(can_traverse rover0 waypoint21 waypoint8)
	(can_traverse rover0 waypoint8 waypoint34)
	(can_traverse rover0 waypoint34 waypoint8)
	(can_traverse rover0 waypoint16 waypoint47)
	(can_traverse rover0 waypoint47 waypoint16)
	(can_traverse rover0 waypoint35 waypoint1)
	(can_traverse rover0 waypoint1 waypoint35)
	(can_traverse rover0 waypoint11 waypoint41)
	(can_traverse rover0 waypoint41 waypoint11)
	(can_traverse rover0 waypoint45 waypoint38)
	(can_traverse rover0 waypoint38 waypoint45)
	(can_traverse rover0 waypoint27 waypoint17)
	(can_traverse rover0 waypoint17 waypoint27)
	(at rover1 waypoint44)
	(available rover1)
	(store_of rover1store rover1)
	(empty rover1store)
	(equipped_for_soil_analysis rover1)
	(equipped_for_rock_analysis rover1)
	(equipped_for_imaging rover1)
	(can_traverse rover1 waypoint44 waypoint6)
	(can_traverse rover1 waypoint6 waypoint44)
	(can_traverse rover1 waypoint44 waypoint33)
	(can_traverse rover1 waypoint33 waypoint44)
	(can_traverse rover1 waypoint44 waypoint42)
	(can_traverse rover1 waypoint42 waypoint44)
	(can_traverse rover1 waypoint44 waypoint45)
	(can_traverse rover1 waypoint45 waypoint44)
	(can_traverse rover1 waypoint44 waypoint50)
	(can_traverse rover1 waypoint50 waypoint44)
	(can_traverse rover1 waypoint44 waypoint55)
	(can_traverse rover1 waypoint55 waypoint44)
	(can_traverse rover1 waypoint6 waypoint2)
	(can_traverse rover1 waypoint2 waypoint6)
	(can_traverse rover1 waypoint6 waypoint5)
	(can_traverse rover1 waypoint5 waypoint6)
	(can_traverse rover1 waypoint6 waypoint15)
	(can_traverse rover1 waypoint15 waypoint6)
	(can_traverse rover1 waypoint6 waypoint21)
	(can_traverse rover1 waypoint21 waypoint6)
	(can_traverse rover1 waypoint6 waypoint22)
	(can_traverse rover1 waypoint22 waypoint6)
	(can_traverse rover1 waypoint6 waypoint26)
	(can_traverse rover1 waypoint26 waypoint6)
	(can_traverse rover1 waypoint6 waypoint28)
	(can_traverse rover1 waypoint28 waypoint6)
	(can_traverse rover1 waypoint6 waypoint30)
	(can_traverse rover1 waypoint30 waypoint6)
	(can_traverse rover1 waypoint6 waypoint32)
	(can_traverse rover1 waypoint32 waypoint6)
	(can_traverse rover1 waypoint6 waypoint35)
	(can_traverse rover1 waypoint35 waypoint6)
	(can_traverse rover1 waypoint6 waypoint52)
	(can_traverse rover1 waypoint52 waypoint6)
	(can_traverse rover1 waypoint6 waypoint58)
	(can_traverse rover1 waypoint58 waypoint6)
	(can_traverse rover1 waypoint42 waypoint0)
	(can_traverse rover1 waypoint0 waypoint42)
	(can_traverse rover1 waypoint42 waypoint7)
	(can_traverse rover1 waypoint7 waypoint42)
	(can_traverse rover1 waypoint42 waypoint13)
	(can_traverse rover1 waypoint13 waypoint42)
	(can_traverse rover1 waypoint42 waypoint14)
	(can_traverse rover1 waypoint14 waypoint42)
	(can_traverse rover1 waypoint42 waypoint29)
	(can_traverse rover1 waypoint29 waypoint42)
	(can_traverse rover1 waypoint42 waypoint49)
	(can_traverse rover1 waypoint49 waypoint42)
	(can_traverse rover1 waypoint45 waypoint38)
	(can_traverse rover1 waypoint38 waypoint45)
	(can_traverse rover1 waypoint45 waypoint41)
	(can_traverse rover1 waypoint41 waypoint45)
	(can_traverse rover1 waypoint50 waypoint47)
	(can_traverse rover1 waypoint47 waypoint50)
	(can_traverse rover1 waypoint50 waypoint53)
	(can_traverse rover1 waypoint53 waypoint50)
	(can_traverse rover1 waypoint50 waypoint59)
	(can_traverse rover1 waypoint59 waypoint50)
	(can_traverse rover1 waypoint55 waypoint40)
	(can_traverse rover1 waypoint40 waypoint55)
	(can_traverse rover1 waypoint2 waypoint8)
	(can_traverse rover1 waypoint8 waypoint2)
	(can_traverse rover1 waypoint2 waypoint11)
	(can_traverse rover1 waypoint11 waypoint2)
	(can_traverse rover1 waypoint2 waypoint37)
	(can_traverse rover1 waypoint37 waypoint2)
	(can_traverse rover1 waypoint5 waypoint10)
	(can_traverse rover1 waypoint10 waypoint5)
	(can_traverse rover1 waypoint5 waypoint23)
	(can_traverse rover1 waypoint23 waypoint5)
	(can_traverse rover1 waypoint5 waypoint56)
	(can_traverse rover1 waypoint56 waypoint5)
	(can_traverse rover1 waypoint15 waypoint24)
	(can_traverse rover1 waypoint24 waypoint15)
	(can_traverse rover1 waypoint21 waypoint1)
	(can_traverse rover1 waypoint1 waypoint21)
	(can_traverse rover1 waypoint21 waypoint3)
	(can_traverse rover1 waypoint3 waypoint21)
	(can_traverse rover1 waypoint21 waypoint19)
	(can_traverse rover1 waypoint19 waypoint21)
	(can_traverse rover1 waypoint21 waypoint36)
	(can_traverse rover1 waypoint36 waypoint21)
	(can_traverse rover1 waypoint21 waypoint46)
	(can_traverse rover1 waypoint46 waypoint21)
	(can_traverse rover1 waypoint22 waypoint31)
	(can_traverse rover1 waypoint31 waypoint22)
	(can_traverse rover1 waypoint22 waypoint51)
	(can_traverse rover1 waypoint51 waypoint22)
	(can_traverse rover1 waypoint26 waypoint16)
	(can_traverse rover1 waypoint16 waypoint26)
	(can_traverse rover1 waypoint26 waypoint43)
	(can_traverse rover1 waypoint43 waypoint26)
	(can_traverse rover1 waypoint26 waypoint48)
	(can_traverse rover1 waypoint48 waypoint26)
	(can_traverse rover1 waypoint28 waypoint18)
	(can_traverse rover1 waypoint18 waypoint28)
	(can_traverse rover1 waypoint28 waypoint34)
	(can_traverse rover1 waypoint34 waypoint28)
	(can_traverse rover1 waypoint30 waypoint4)
	(can_traverse rover1 waypoint4 waypoint30)
	(can_traverse rover1 waypoint30 waypoint39)
	(can_traverse rover1 waypoint39 waypoint30)
	(can_traverse rover1 waypoint58 waypoint20)
	(can_traverse rover1 waypoint20 waypoint58)
	(can_traverse rover1 waypoint58 waypoint27)
	(can_traverse rover1 waypoint27 waypoint58)
	(can_traverse rover1 waypoint0 waypoint12)
	(can_traverse rover1 waypoint12 waypoint0)
	(can_traverse rover1 waypoint13 waypoint9)
	(can_traverse rover1 waypoint9 waypoint13)
	(can_traverse rover1 waypoint13 waypoint25)
	(can_traverse rover1 waypoint25 waypoint13)
	(can_traverse rover1 waypoint49 waypoint57)
	(can_traverse rover1 waypoint57 waypoint49)
	(can_traverse rover1 waypoint41 waypoint17)
	(can_traverse rover1 waypoint17 waypoint41)
	(can_traverse rover1 waypoint37 waypoint54)
	(can_traverse rover1 waypoint54 waypoint37)
	(at rover2 waypoint55)
	(available rover2)
	(store_of rover2store rover2)
	(empty rover2store)
	(equipped_for_imaging rover2)
	(can_traverse rover2 waypoint55 waypoint0)
	(can_traverse rover2 waypoint0 waypoint55)
	(can_traverse rover2 waypoint55 waypoint15)
	(can_traverse rover2 waypoint15 waypoint55)
	(can_traverse rover2 waypoint55 waypoint29)
	(can_traverse rover2 waypoint29 waypoint55)
	(can_traverse rover2 waypoint55 waypoint45)
	(can_traverse rover2 waypoint45 waypoint55)
	(can_traverse rover2 waypoint0 waypoint5)
	(can_traverse rover2 waypoint5 waypoint0)
	(can_traverse rover2 waypoint0 waypoint8)
	(can_traverse rover2 waypoint8 waypoint0)
	(can_traverse rover2 waypoint0 waypoint16)
	(can_traverse rover2 waypoint16 waypoint0)
	(can_traverse rover2 waypoint0 waypoint18)
	(can_traverse rover2 waypoint18 waypoint0)
	(can_traverse rover2 waypoint0 waypoint28)
	(can_traverse rover2 waypoint28 waypoint0)
	(can_traverse rover2 waypoint0 waypoint46)
	(can_traverse rover2 waypoint46 waypoint0)
	(can_traverse rover2 waypoint15 waypoint6)
	(can_traverse rover2 waypoint6 waypoint15)
	(can_traverse rover2 waypoint29 waypoint7)
	(can_traverse rover2 waypoint7 waypoint29)
	(can_traverse rover2 waypoint29 waypoint10)
	(can_traverse rover2 waypoint10 waypoint29)
	(can_traverse rover2 waypoint29 waypoint12)
	(can_traverse rover2 waypoint12 waypoint29)
	(can_traverse rover2 waypoint29 waypoint20)
	(can_traverse rover2 waypoint20 waypoint29)
	(can_traverse rover2 waypoint29 waypoint24)
	(can_traverse rover2 waypoint24 waypoint29)
	(can_traverse rover2 waypoint29 waypoint25)
	(can_traverse rover2 waypoint25 waypoint29)
	(can_traverse rover2 waypoint29 waypoint27)
	(can_traverse rover2 waypoint27 waypoint29)
	(can_traverse rover2 waypoint29 waypoint30)
	(can_traverse rover2 waypoint30 waypoint29)
	(can_traverse rover2 waypoint29 waypoint42)
	(can_traverse rover2 waypoint42 waypoint29)
	(can_traverse rover2 waypoint29 waypoint53)
	(can_traverse rover2 waypoint53 waypoint29)
	(can_traverse rover2 waypoint29 waypoint57)
	(can_traverse rover2 waypoint57 waypoint29)
	(can_traverse rover2 waypoint29 waypoint59)
	(can_traverse rover2 waypoint59 waypoint29)
	(can_traverse rover2 waypoint45 waypoint22)
	(can_traverse rover2 waypoint22 waypoint45)
	(can_traverse rover2 waypoint45 waypoint32)
	(can_traverse rover2 waypoint32 waypoint45)
	(can_traverse rover2 waypoint45 waypoint41)
	(can_traverse rover2 waypoint41 waypoint45)
	(can_traverse rover2 waypoint45 waypoint43)
	(can_traverse rover2 waypoint43 waypoint45)
	(can_traverse rover2 waypoint5 waypoint2)
	(can_traverse rover2 waypoint2 waypoint5)
	(can_traverse rover2 waypoint5 waypoint23)
	(can_traverse rover2 waypoint23 waypoint5)
	(can_traverse rover2 waypoint5 waypoint35)
	(can_traverse rover2 waypoint35 waypoint5)
	(can_traverse rover2 waypoint5 waypoint37)
	(can_traverse rover2 waypoint37 waypoint5)
	(can_traverse rover2 waypoint5 waypoint54)
	(can_traverse rover2 waypoint54 waypoint5)
	(can_traverse rover2 waypoint8 waypoint3)
	(can_traverse rover2 waypoint3 waypoint8)
	(can_traverse rover2 waypoint8 waypoint4)
	(can_traverse rover2 waypoint4 waypoint8)
	(can_traverse rover2 waypoint8 waypoint21)
	(can_traverse rover2 waypoint21 waypoint8)
	(can_traverse rover2 waypoint8 waypoint31)
	(can_traverse rover2 waypoint31 waypoint8)
	(can_traverse rover2 waypoint8 waypoint34)
	(can_traverse rover2 waypoint34 waypoint8)
	(can_traverse rover2 waypoint8 waypoint48)
	(can_traverse rover2 waypoint48 waypoint8)
	(can_traverse rover2 waypoint8 waypoint49)
	(can_traverse rover2 waypoint49 waypoint8)
	(can_traverse rover2 waypoint18 waypoint39)
	(can_traverse rover2 waypoint39 waypoint18)
	(can_traverse rover2 waypoint28 waypoint11)
	(can_traverse rover2 waypoint11 waypoint28)
	(can_traverse rover2 waypoint28 waypoint13)
	(can_traverse rover2 waypoint13 waypoint28)
	(can_traverse rover2 waypoint28 waypoint38)
	(can_traverse rover2 waypoint38 waypoint28)
	(can_traverse rover2 waypoint46 waypoint36)
	(can_traverse rover2 waypoint36 waypoint46)
	(can_traverse rover2 waypoint46 waypoint47)
	(can_traverse rover2 waypoint47 waypoint46)
	(can_traverse rover2 waypoint6 waypoint14)
	(can_traverse rover2 waypoint14 waypoint6)
	(can_traverse rover2 waypoint6 waypoint26)
	(can_traverse rover2 waypoint26 waypoint6)
	(can_traverse rover2 waypoint6 waypoint44)
	(can_traverse rover2 waypoint44 waypoint6)
	(can_traverse rover2 waypoint6 waypoint58)
	(can_traverse rover2 waypoint58 waypoint6)
	(can_traverse rover2 waypoint10 waypoint33)
	(can_traverse rover2 waypoint33 waypoint10)
	(can_traverse rover2 waypoint10 waypoint51)
	(can_traverse rover2 waypoint51 waypoint10)
	(can_traverse rover2 waypoint24 waypoint1)
	(can_traverse rover2 waypoint1 waypoint24)
	(can_traverse rover2 waypoint24 waypoint9)
	(can_traverse rover2 waypoint9 waypoint24)
	(can_traverse rover2 waypoint25 waypoint17)
	(can_traverse rover2 waypoint17 waypoint25)
	(can_traverse rover2 waypoint42 waypoint50)
	(can_traverse rover2 waypoint50 waypoint42)
	(can_traverse rover2 waypoint57 waypoint40)
	(can_traverse rover2 waypoint40 waypoint57)
	(can_traverse rover2 waypoint59 waypoint56)
	(can_traverse rover2 waypoint56 waypoint59)
	(can_traverse rover2 waypoint41 waypoint52)
	(can_traverse rover2 waypoint52 waypoint41)
	(can_traverse rover2 waypoint21 waypoint19)
	(can_traverse rover2 waypoint19 waypoint21)
	(at rover3 waypoint41)
	(available rover3)
	(store_of rover3store rover3)
	(empty rover3store)
	(equipped_for_soil_analysis rover3)
	(equipped_for_imaging rover3)
	(can_traverse rover3 waypoint41 waypoint9)
	(can_traverse rover3 waypoint9 waypoint41)
	(can_traverse rover3 waypoint41 waypoint52)
	(can_traverse rover3 waypoint52 waypoint41)
	(can_traverse rover3 waypoint41 waypoint53)
	(can_traverse rover3 waypoint53 waypoint41)
	(can_traverse rover3 waypoint9 waypoint13)
	(can_traverse rover3 waypoint13 waypoint9)
	(can_traverse rover3 waypoint9 waypoint24)
	(can_traverse rover3 waypoint24 waypoint9)
	(can_traverse rover3 waypoint9 waypoint43)
	(can_traverse rover3 waypoint43 waypoint9)
	(can_traverse rover3 waypoint52 waypoint1)
	(can_traverse rover3 waypoint1 waypoint52)
	(can_traverse rover3 waypoint52 waypoint6)
	(can_traverse rover3 waypoint6 waypoint52)
	(can_traverse rover3 waypoint52 waypoint49)
	(can_traverse rover3 waypoint49 waypoint52)
	(can_traverse rover3 waypoint52 waypoint56)
	(can_traverse rover3 waypoint56 waypoint52)
	(can_traverse rover3 waypoint52 waypoint58)
	(can_traverse rover3 waypoint58 waypoint52)
	(can_traverse rover3 waypoint53 waypoint7)
	(can_traverse rover3 waypoint7 waypoint53)
	(can_traverse rover3 waypoint53 waypoint21)
	(can_traverse rover3 waypoint21 waypoint53)
	(can_traverse rover3 waypoint53 waypoint34)
	(can_traverse rover3 waypoint34 waypoint53)
	(can_traverse rover3 waypoint13 waypoint2)
	(can_traverse rover3 waypoint2 waypoint13)
	(can_traverse rover3 waypoint13 waypoint4)
	(can_traverse rover3 waypoint4 waypoint13)
	(can_traverse rover3 waypoint13 waypoint14)
	(can_traverse rover3 waypoint14 waypoint13)
	(can_traverse rover3 waypoint13 waypoint20)
	(can_traverse rover3 waypoint20 waypoint13)
	(can_traverse rover3 waypoint13 waypoint25)
	(can_traverse rover3 waypoint25 waypoint13)
	(can_traverse rover3 waypoint13 waypoint27)
	(can_traverse rover3 waypoint27 waypoint13)
	(can_traverse rover3 waypoint13 waypoint28)
	(can_traverse rover3 waypoint28 waypoint13)
	(can_traverse rover3 waypoint13 waypoint39)
	(can_traverse rover3 waypoint39 waypoint13)
	(can_traverse rover3 waypoint13 waypoint40)
	(can_traverse rover3 waypoint40 waypoint13)
	(can_traverse rover3 waypoint13 waypoint42)
	(can_traverse rover3 waypoint42 waypoint13)
	(can_traverse rover3 waypoint13 waypoint48)
	(can_traverse rover3 waypoint48 waypoint13)
	(can_traverse rover3 waypoint24 waypoint0)
	(can_traverse rover3 waypoint0 waypoint24)
	(can_traverse rover3 waypoint24 waypoint12)
	(can_traverse rover3 waypoint12 waypoint24)
	(can_traverse rover3 waypoint24 waypoint15)
	(can_traverse rover3 waypoint15 waypoint24)
	(can_traverse rover3 waypoint24 waypoint16)
	(can_traverse rover3 waypoint16 waypoint24)
	(can_traverse rover3 waypoint24 waypoint23)
	(can_traverse rover3 waypoint23 waypoint24)
	(can_traverse rover3 waypoint24 waypoint26)
	(can_traverse rover3 waypoint26 waypoint24)
	(can_traverse rover3 waypoint24 waypoint30)
	(can_traverse rover3 waypoint30 waypoint24)
	(can_traverse rover3 waypoint24 waypoint38)
	(can_traverse rover3 waypoint38 waypoint24)
	(can_traverse rover3 waypoint24 waypoint57)
	(can_traverse rover3 waypoint57 waypoint24)
	(can_traverse rover3 waypoint43 waypoint11)
	(can_traverse rover3 waypoint11 waypoint43)
	(can_traverse rover3 waypoint43 waypoint31)
	(can_traverse rover3 waypoint31 waypoint43)
	(can_traverse rover3 waypoint1 waypoint17)
	(can_traverse rover3 waypoint17 waypoint1)
	(can_traverse rover3 waypoint1 waypoint35)
	(can_traverse rover3 waypoint35 waypoint1)
	(can_traverse rover3 waypoint6 waypoint22)
	(can_traverse rover3 waypoint22 waypoint6)
	(can_traverse rover3 waypoint6 waypoint32)
	(can_traverse rover3 waypoint32 waypoint6)
	(can_traverse rover3 waypoint6 waypoint47)
	(can_traverse rover3 waypoint47 waypoint6)
	(can_traverse rover3 waypoint56 waypoint3)
	(can_traverse rover3 waypoint3 waypoint56)
	(can_traverse rover3 waypoint56 waypoint54)
	(can_traverse rover3 waypoint54 waypoint56)
	(can_traverse rover3 waypoint56 waypoint59)
	(can_traverse rover3 waypoint59 waypoint56)
	(can_traverse rover3 waypoint7 waypoint18)
	(can_traverse rover3 waypoint18 waypoint7)
	(can_traverse rover3 waypoint7 waypoint29)
	(can_traverse rover3 waypoint29 waypoint7)
	(can_traverse rover3 waypoint21 waypoint10)
	(can_traverse rover3 waypoint10 waypoint21)
	(can_traverse rover3 waypoint21 waypoint19)
	(can_traverse rover3 waypoint19 waypoint21)
	(can_traverse rover3 waypoint21 waypoint36)
	(can_traverse rover3 waypoint36 waypoint21)
	(can_traverse rover3 waypoint34 waypoint8)
	(can_traverse rover3 waypoint8 waypoint34)
	(can_traverse rover3 waypoint2 waypoint5)
	(can_traverse rover3 waypoint5 waypoint2)
	(can_traverse rover3 waypoint2 waypoint33)
	(can_traverse rover3 waypoint33 waypoint2)
	(can_traverse rover3 waypoint2 waypoint37)
	(can_traverse rover3 waypoint37 waypoint2)
	(can_traverse rover3 waypoint4 waypoint50)
	(can_traverse rover3 waypoint50 waypoint4)
	(on_board camera0 rover1)
	(calibration_target camera0 objective0)
	(supports camera0 colour)
	(on_board camera1 rover2)
	(calibration_target camera1 objective4)
	(supports camera1 colour)
	(supports camera1 low_res)
	(on_board camera2 rover3)
	(calibration_target camera2 objective2)
	(supports camera2 colour)
	(on_board camera3 rover3)
	(calibration_target camera3 objective2)
	(supports camera3 colour)
	(supports camera3 low_res)
	(on_board camera4 rover2)
	(calibration_target camera4 objective2)
	(supports camera4 low_res)
	(on_board camera5 rover1)
	(calibration_target camera5 objective6)
	(supports camera5 low_res)
	(on_board camera6 rover0)
	(calibration_target camera6 objective0)
	(supports camera6 colour)
	(supports camera6 high_res)
	(supports camera6 low_res)
	(visible_from objective0 waypoint2)
	(visible_from objective0 waypoint3)
	(visible_from objective0 waypoint11)
	(visible_from objective0 waypoint17)
	(visible_from objective0 waypoint24)
	(visible_from objective0 waypoint26)
	(visible_from objective0 waypoint29)
	(visible_from objective0 waypoint36)
	(visible_from objective0 waypoint37)
	(visible_from objective0 waypoint51)
	(visible_from objective0 waypoint55)
	(visible_from objective0 waypoint56)
	(visible_from objective0 waypoint59)
	(visible_from objective1 waypoint2)
	(visible_from objective1 waypoint4)
	(visible_from objective1 waypoint5)
	(visible_from objective1 waypoint8)
	(visible_from objective1 waypoint12)
	(visible_from objective1 waypoint13)
	(visible_from objective1 waypoint14)
	(visible_from objective1 waypoint15)
	(visible_from objective1 waypoint17)
	(visible_from objective1 waypoint18)
	(visible_from objective1 waypoint19)
	(visible_from objective1 waypoint20)
	(visible_from objective1 waypoint21)
	(visible_from objective1 waypoint22)
	(visible_from objective1 waypoint25)
	(visible_from objective1 waypoint28)
	(visible_from objective1 waypoint30)
	(visible_from objective1 waypoint31)
	(visible_from objective1 waypoint33)
	(visible_from objective1 waypoint35)
	(visible_from objective1 waypoint36)
	(visible_from objective1 waypoint37)
	(visible_from objective1 waypoint38)
	(visible_from objective1 waypoint40)
	(visible_from objective1 waypoint41)
	(visible_from objective1 waypoint43)
	(visible_from objective1 waypoint44)
	(visible_from objective1 waypoint45)
	(visible_from objective1 waypoint47)
	(visible_from objective1 waypoint48)
	(visible_from objective1 waypoint50)
	(visible_from objective1 waypoint52)
	(visible_from objective1 waypoint54)
	(visible_from objective1 waypoint55)
	(visible_from objective1 waypoint57)
	(visible_from objective1 waypoint58)
	(visible_from objective2 waypoint3)
	(visible_from objective2 waypoint5)
	(visible_from objective2 waypoint14)
	(visible_from objective2 waypoint15)
	(visible_from objective2 waypoint16)
	(visible_from objective2 waypoint17)
	(visible_from objective2 waypoint18)
	(visible_from objective2 waypoint26)
	(visible_from objective2 waypoint27)
	(visible_from objective2 waypoint29)
	(visible_from objective2 waypoint30)
	(visible_from objective2 waypoint31)
	(visible_from objective2 waypoint32)
	(visible_from objective2 waypoint35)
	(visible_from objective2 waypoint42)
	(visible_from objective2 waypoint44)
	(visible_from objective2 waypoint45)
	(visible_from objective2 waypoint46)
	(visible_from objective2 waypoint47)
	(visible_from objective2 waypoint48)
	(visible_from objective2 waypoint51)
	(visible_from objective2 waypoint53)
	(visible_from objective2 waypoint57)
	(visible_from objective2 waypoint58)
	(visible_from objective2 waypoint59)
	(visible_from objective3 waypoint0)
	(visible_from objective3 waypoint1)
	(visible_from objective3 waypoint3)
	(visible_from objective3 waypoint5)
	(visible_from objective3 waypoint7)
	(visible_from objective3 waypoint8)
	(visible_from objective3 waypoint10)
	(visible_from objective3 waypoint11)
	(visible_from objective3 waypoint15)
	(visible_from objective3 waypoint16)
	(visible_from objective3 waypoint18)
	(visible_from objective3 waypoint19)
	(visible_from objective3 waypoint20)
	(visible_from objective3 waypoint22)
	(visible_from objective3 waypoint23)
	(visible_from objective3 waypoint24)
	(visible_from objective3 waypoint25)
	(visible_from objective3 waypoint26)
	(visible_from objective3 waypoint29)
	(visible_from objective3 waypoint30)
	(visible_from objective3 waypoint32)
	(visible_from objective3 waypoint35)
	(visible_from objective3 waypoint36)
	(visible_from objective3 waypoint38)
	(visible_from objective3 waypoint39)
	(visible_from objective3 waypoint41)
	(visible_from objective3 waypoint43)
	(visible_from objective3 waypoint44)
	(visible_from objective3 waypoint46)
	(visible_from objective3 waypoint49)
	(visible_from objective3 waypoint51)
	(visible_from objective3 waypoint52)
	(visible_from objective3 waypoint54)
	(visible_from objective3 waypoint55)
	(visible_from objective4 waypoint1)
	(visible_from objective4 waypoint6)
	(visible_from objective4 waypoint10)
	(visible_from objective4 waypoint11)
	(visible_from objective4 waypoint12)
	(visible_from objective4 waypoint14)
	(visible_from objective4 waypoint16)
	(visible_from objective4 waypoint17)
	(visible_from objective4 waypoint19)
	(visible_from objective4 waypoint23)
	(visible_from objective4 waypoint24)
	(visible_from objective4 waypoint25)
	(visible_from objective4 waypoint27)
	(visible_from objective4 waypoint28)
	(visible_from objective4 waypoint29)
	(visible_from objective4 waypoint30)
	(visible_from objective4 waypoint31)
	(visible_from objective4 waypoint34)
	(visible_from objective4 waypoint36)
	(visible_from objective4 waypoint38)
	(visible_from objective4 waypoint40)
	(visible_from objective4 waypoint43)
	(visible_from objective4 waypoint45)
	(visible_from objective4 waypoint46)
	(visible_from objective4 waypoint47)
	(visible_from objective4 waypoint48)
	(visible_from objective4 waypoint49)
	(visible_from objective4 waypoint50)
	(visible_from objective4 waypoint51)
	(visible_from objective4 waypoint52)
	(visible_from objective4 waypoint53)
	(visible_from objective4 waypoint54)
	(visible_from objective4 waypoint55)
	(visible_from objective4 waypoint56)
	(visible_from objective4 waypoint57)
	(visible_from objective4 waypoint59)
	(visible_from objective5 waypoint6)
	(visible_from objective5 waypoint9)
	(visible_from objective5 waypoint13)
	(visible_from objective5 waypoint20)
	(visible_from objective5 waypoint27)
	(visible_from objective5 waypoint28)
	(visible_from objective5 waypoint31)
	(visible_from objective5 waypoint50)
	(visible_from objective5 waypoint55)
	(visible_from objective5 waypoint56)
	(visible_from objective6 waypoint9)
	(visible_from objective6 waypoint13)
	(visible_from objective6 waypoint16)
	(visible_from objective6 waypoint17)
	(visible_from objective6 waypoint20)
	(visible_from objective6 waypoint22)
	(visible_from objective6 waypoint23)
	(visible_from objective6 waypoint24)
	(visible_from objective6 waypoint29)
	(visible_from objective6 waypoint34)
	(visible_from objective6 waypoint36)
	(visible_from objective6 waypoint37)
	(visible_from objective6 waypoint44)
	(visible_from objective6 waypoint46)
	(visible_from objective6 waypoint47)
	(visible_from objective6 waypoint51)
	(visible_from objective6 waypoint52)
	(visible_from objective6 waypoint59)
	(visible_from objective7 waypoint2)
	(visible_from objective7 waypoint3)
	(visible_from objective7 waypoint7)
	(visible_from objective7 waypoint12)
	(visible_from objective7 waypoint16)
	(visible_from objective7 waypoint17)
	(visible_from objective7 waypoint19)
	(visible_from objective7 waypoint20)
	(visible_from objective7 waypoint27)
	(visible_from objective7 waypoint28)
	(visible_from objective7 waypoint29)
	(visible_from objective7 waypoint35)
	(visible_from objective7 waypoint40)
	(visible_from objective7 waypoint41)
	(visible_from objective7 waypoint44)
	(visible_from objective7 waypoint47)
	(visible_from objective7 waypoint48)
	(visible_from objective7 waypoint50)
	(visible_from objective7 waypoint54)
	(visible_from objective7 waypoint57)
)

(:goal (and
(communicated_soil_data waypoint26)
(communicated_soil_data waypoint56)
(communicated_soil_data waypoint27)
(communicated_soil_data waypoint39)
(communicated_soil_data waypoint1)
(communicated_soil_data waypoint59)
(communicated_soil_data waypoint3)
(communicated_soil_data waypoint52)
(communicated_soil_data waypoint12)
(communicated_soil_data waypoint48)
(communicated_rock_data waypoint17)
(communicated_rock_data waypoint28)
(communicated_rock_data waypoint27)
(communicated_rock_data waypoint29)
(communicated_rock_data waypoint15)
(communicated_rock_data waypoint4)
(communicated_rock_data waypoint25)
(communicated_rock_data waypoint6)
(communicated_rock_data waypoint13)
(communicated_rock_data waypoint41)
(communicated_rock_data waypoint42)
(communicated_rock_data waypoint55)
(communicated_rock_data waypoint34)
(communicated_rock_data waypoint3)
(communicated_rock_data waypoint50)
(communicated_rock_data waypoint22)
(communicated_rock_data waypoint19)
(communicated_rock_data waypoint48)
(communicated_rock_data waypoint46)
(communicated_rock_data waypoint51)
(communicated_image_data objective6 low_res)
(communicated_image_data objective7 low_res)
(communicated_image_data objective4 low_res)
(communicated_image_data objective7 colour)
(communicated_image_data objective5 low_res)
(communicated_image_data objective4 colour)
(communicated_image_data objective1 low_res)
(communicated_image_data objective2 colour)
(communicated_image_data objective1 colour)
	)
)
)
