(define (problem roverprob7) (:domain Rover)
(:objects
	general - Lander
	colour high_res low_res - Mode
	rover0 rover1 rover2 rover3 - Rover
	rover0store rover1store rover2store rover3store - Store
	waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 waypoint7 waypoint8 waypoint9 waypoint10 waypoint11 waypoint12 waypoint13 waypoint14 waypoint15 waypoint16 waypoint17 waypoint18 waypoint19 waypoint20 waypoint21 waypoint22 waypoint23 waypoint24 waypoint25 waypoint26 waypoint27 waypoint28 waypoint29 waypoint30 waypoint31 waypoint32 waypoint33 waypoint34 waypoint35 waypoint36 waypoint37 waypoint38 waypoint39 waypoint40 waypoint41 waypoint42 waypoint43 waypoint44 waypoint45 waypoint46 waypoint47 waypoint48 waypoint49 waypoint50 waypoint51 waypoint52 waypoint53 waypoint54 waypoint55 waypoint56 waypoint57 waypoint58 waypoint59 - Waypoint
	camera0 camera1 camera2 camera3 camera4 camera5 camera6 - Camera
	objective0 objective1 objective2 objective3 objective4 objective5 objective6 objective7 - Objective
	)
(:init
	(visible waypoint0 waypoint8)
	(visible waypoint8 waypoint0)
	(visible waypoint0 waypoint15)
	(visible waypoint15 waypoint0)
	(visible waypoint0 waypoint23)
	(visible waypoint23 waypoint0)
	(visible waypoint0 waypoint30)
	(visible waypoint30 waypoint0)
	(visible waypoint0 waypoint56)
	(visible waypoint56 waypoint0)
	(visible waypoint1 waypoint13)
	(visible waypoint13 waypoint1)
	(visible waypoint1 waypoint34)
	(visible waypoint34 waypoint1)
	(visible waypoint1 waypoint50)
	(visible waypoint50 waypoint1)
	(visible waypoint2 waypoint4)
	(visible waypoint4 waypoint2)
	(visible waypoint2 waypoint30)
	(visible waypoint30 waypoint2)
	(visible waypoint2 waypoint31)
	(visible waypoint31 waypoint2)
	(visible waypoint2 waypoint37)
	(visible waypoint37 waypoint2)
	(visible waypoint2 waypoint46)
	(visible waypoint46 waypoint2)
	(visible waypoint2 waypoint49)
	(visible waypoint49 waypoint2)
	(visible waypoint2 waypoint59)
	(visible waypoint59 waypoint2)
	(visible waypoint3 waypoint6)
	(visible waypoint6 waypoint3)
	(visible waypoint3 waypoint21)
	(visible waypoint21 waypoint3)
	(visible waypoint3 waypoint23)
	(visible waypoint23 waypoint3)
	(visible waypoint3 waypoint34)
	(visible waypoint34 waypoint3)
	(visible waypoint4 waypoint14)
	(visible waypoint14 waypoint4)
	(visible waypoint5 waypoint13)
	(visible waypoint13 waypoint5)
	(visible waypoint5 waypoint29)
	(visible waypoint29 waypoint5)
	(visible waypoint5 waypoint37)
	(visible waypoint37 waypoint5)
	(visible waypoint5 waypoint53)
	(visible waypoint53 waypoint5)
	(visible waypoint5 waypoint58)
	(visible waypoint58 waypoint5)
	(visible waypoint6 waypoint12)
	(visible waypoint12 waypoint6)
	(visible waypoint6 waypoint40)
	(visible waypoint40 waypoint6)
	(visible waypoint6 waypoint45)
	(visible waypoint45 waypoint6)
	(visible waypoint6 waypoint59)
	(visible waypoint59 waypoint6)
	(visible waypoint7 waypoint12)
	(visible waypoint12 waypoint7)
	(visible waypoint7 waypoint19)
	(visible waypoint19 waypoint7)
	(visible waypoint7 waypoint56)
	(visible waypoint56 waypoint7)
	(visible waypoint8 waypoint1)
	(visible waypoint1 waypoint8)
	(visible waypoint8 waypoint2)
	(visible waypoint2 waypoint8)
	(visible waypoint8 waypoint10)
	(visible waypoint10 waypoint8)
	(visible waypoint8 waypoint50)
	(visible waypoint50 waypoint8)
	(visible waypoint9 waypoint15)
	(visible waypoint15 waypoint9)
	(visible waypoint9 waypoint26)
	(visible waypoint26 waypoint9)
	(visible waypoint9 waypoint42)
	(visible waypoint42 waypoint9)
	(visible waypoint9 waypoint45)
	(visible waypoint45 waypoint9)
	(visible waypoint10 waypoint26)
	(visible waypoint26 waypoint10)
	(visible waypoint10 waypoint28)
	(visible waypoint28 waypoint10)
	(visible waypoint10 waypoint31)
	(visible waypoint31 waypoint10)
	(visible waypoint10 waypoint39)
	(visible waypoint39 waypoint10)
	(visible waypoint10 waypoint57)
	(visible waypoint57 waypoint10)
	(visible waypoint11 waypoint8)
	(visible waypoint8 waypoint11)
	(visible waypoint11 waypoint23)
	(visible waypoint23 waypoint11)
	(visible waypoint11 waypoint48)
	(visible waypoint48 waypoint11)
	(visible waypoint12 waypoint13)
	(visible waypoint13 waypoint12)
	(visible waypoint12 waypoint40)
	(visible waypoint40 waypoint12)
	(visible waypoint12 waypoint47)
	(visible waypoint47 waypoint12)
	(visible waypoint12 waypoint55)
	(visible waypoint55 waypoint12)
	(visible waypoint12 waypoint57)
	(visible waypoint57 waypoint12)
	(visible waypoint13 waypoint4)
	(visible waypoint4 waypoint13)
	(visible waypoint13 waypoint22)
	(visible waypoint22 waypoint13)
	(visible waypoint13 waypoint34)
	(visible waypoint34 waypoint13)
	(visible waypoint13 waypoint35)
	(visible waypoint35 waypoint13)
	(visible waypoint13 waypoint43)
	(visible waypoint43 waypoint13)
	(visible waypoint14 waypoint23)
	(visible waypoint23 waypoint14)
	(visible waypoint14 waypoint26)
	(visible waypoint26 waypoint14)
	(visible waypoint14 waypoint27)
	(visible waypoint27 waypoint14)
	(visible waypoint14 waypoint54)
	(visible waypoint54 waypoint14)
	(visible waypoint15 waypoint21)
	(visible waypoint21 waypoint15)
	(visible waypoint15 waypoint38)
	(visible waypoint38 waypoint15)
	(visible waypoint15 waypoint51)
	(visible waypoint51 waypoint15)
	(visible waypoint15 waypoint55)
	(visible waypoint55 waypoint15)
	(visible waypoint15 waypoint58)
	(visible waypoint58 waypoint15)
	(visible waypoint16 waypoint1)
	(visible waypoint1 waypoint16)
	(visible waypoint16 waypoint3)
	(visible waypoint3 waypoint16)
	(visible waypoint16 waypoint28)
	(visible waypoint28 waypoint16)
	(visible waypoint16 waypoint31)
	(visible waypoint31 waypoint16)
	(visible waypoint16 waypoint42)
	(visible waypoint42 waypoint16)
	(visible waypoint16 waypoint57)
	(visible waypoint57 waypoint16)
	(visible waypoint16 waypoint58)
	(visible waypoint58 waypoint16)
	(visible waypoint17 waypoint5)
	(visible waypoint5 waypoint17)
	(visible waypoint17 waypoint30)
	(visible waypoint30 waypoint17)
	(visible waypoint17 waypoint39)
	(visible waypoint39 waypoint17)
	(visible waypoint17 waypoint44)
	(visible waypoint44 waypoint17)
	(visible waypoint17 waypoint55)
	(visible waypoint55 waypoint17)
	(visible waypoint18 waypoint25)
	(visible waypoint25 waypoint18)
	(visible waypoint18 waypoint41)
	(visible waypoint41 waypoint18)
	(visible waypoint18 waypoint51)
	(visible waypoint51 waypoint18)
	(visible waypoint19 waypoint1)
	(visible waypoint1 waypoint19)
	(visible waypoint19 waypoint17)
	(visible waypoint17 waypoint19)
	(visible waypoint19 waypoint27)
	(visible waypoint27 waypoint19)
	(visible waypoint19 waypoint37)
	(visible waypoint37 waypoint19)
	(visible waypoint19 waypoint52)
	(visible waypoint52 waypoint19)
	(visible waypoint19 waypoint59)
	(visible waypoint59 waypoint19)
	(visible waypoint20 waypoint14)
	(visible waypoint14 waypoint20)
	(visible waypoint20 waypoint18)
	(visible waypoint18 waypoint20)
	(visible waypoint20 waypoint30)
	(visible waypoint30 waypoint20)
	(visible waypoint20 waypoint59)
	(visible waypoint59 waypoint20)
	(visible waypoint21 waypoint9)
	(visible waypoint9 waypoint21)
	(visible waypoint21 waypoint19)
	(visible waypoint19 waypoint21)
	(visible waypoint21 waypoint28)
	(visible waypoint28 waypoint21)
	(visible waypoint21 waypoint36)
	(visible waypoint36 waypoint21)
	(visible waypoint21 waypoint45)
	(visible waypoint45 waypoint21)
	(visible waypoint22 waypoint15)
	(visible waypoint15 waypoint22)
	(visible waypoint22 waypoint26)
	(visible waypoint26 waypoint22)
	(visible waypoint22 waypoint36)
	(visible waypoint36 waypoint22)
	(visible waypoint22 waypoint51)
	(visible waypoint51 waypoint22)
	(visible waypoint22 waypoint54)
	(visible waypoint54 waypoint22)
	(visible waypoint22 waypoint59)
	(visible waypoint59 waypoint22)
	(visible waypoint23 waypoint53)
	(visible waypoint53 waypoint23)
	(visible waypoint23 waypoint58)
	(visible waypoint58 waypoint23)
	(visible waypoint24 waypoint33)
	(visible waypoint33 waypoint24)
	(visible waypoint24 waypoint46)
	(visible waypoint46 waypoint24)
	(visible waypoint24 waypoint49)
	(visible waypoint49 waypoint24)
	(visible waypoint25 waypoint3)
	(visible waypoint3 waypoint25)
	(visible waypoint25 waypoint5)
	(visible waypoint5 waypoint25)
	(visible waypoint25 waypoint21)
	(visible waypoint21 waypoint25)
	(visible waypoint25 waypoint26)
	(visible waypoint26 waypoint25)
	(visible waypoint25 waypoint48)
	(visible waypoint48 waypoint25)
	(visible waypoint26 waypoint0)
	(visible waypoint0 waypoint26)
	(visible waypoint26 waypoint2)
	(visible waypoint2 waypoint26)
	(visible waypoint26 waypoint12)
	(visible waypoint12 waypoint26)
	(visible waypoint26 waypoint18)
	(visible waypoint18 waypoint26)
	(visible waypoint26 waypoint19)
	(visible waypoint19 waypoint26)
	(visible waypoint26 waypoint38)
	(visible waypoint38 waypoint26)
	(visible waypoint26 waypoint52)
	(visible waypoint52 waypoint26)
	(visible waypoint26 waypoint56)
	(visible waypoint56 waypoint26)
	(visible waypoint27 waypoint6)
	(visible waypoint6 waypoint27)
	(visible waypoint27 waypoint26)
	(visible waypoint26 waypoint27)
	(visible waypoint27 waypoint48)
	(visible waypoint48 waypoint27)
	(visible waypoint27 waypoint49)
	(visible waypoint49 waypoint27)
	(visible waypoint27 waypoint56)
	(visible waypoint56 waypoint27)
	(visible waypoint28 waypoint1)
	(visible waypoint1 waypoint28)
	(visible waypoint28 waypoint7)
	(visible waypoint7 waypoint28)
	(visible waypoint28 waypoint34)
	(visible waypoint34 waypoint28)
	(visible waypoint28 waypoint36)
	(visible waypoint36 waypoint28)
	(visible waypoint28 waypoint39)
	(visible waypoint39 waypoint28)
	(visible waypoint28 waypoint43)
	(visible waypoint43 waypoint28)
	(visible waypoint29 waypoint3)
	(visible waypoint3 waypoint29)
	(visible waypoint29 waypoint25)
	(visible waypoint25 waypoint29)
	(visible waypoint29 waypoint52)
	(visible waypoint52 waypoint29)
	(visible waypoint30 waypoint8)
	(visible waypoint8 waypoint30)
	(visible waypoint30 waypoint11)
	(visible waypoint11 waypoint30)
	(visible waypoint30 waypoint18)
	(visible waypoint18 waypoint30)
	(visible waypoint30 waypoint19)
	(visible waypoint19 waypoint30)
	(visible waypoint30 waypoint24)
	(visible waypoint24 waypoint30)
	(visible waypoint30 waypoint25)
	(visible waypoint25 waypoint30)
	(visible waypoint30 waypoint49)
	(visible waypoint49 waypoint30)
	(visible waypoint31 waypoint5)
	(visible waypoint5 waypoint31)
	(visible waypoint31 waypoint41)
	(visible waypoint41 waypoint31)
	(visible waypoint31 waypoint48)
	(visible waypoint48 waypoint31)
	(visible waypoint31 waypoint50)
	(visible waypoint50 waypoint31)
	(visible waypoint32 waypoint20)
	(visible waypoint20 waypoint32)
	(visible waypoint32 waypoint22)
	(visible waypoint22 waypoint32)
	(visible waypoint32 waypoint29)
	(visible waypoint29 waypoint32)
	(visible waypoint32 waypoint54)
	(visible waypoint54 waypoint32)
	(visible waypoint33 waypoint2)
	(visible waypoint2 waypoint33)
	(visible waypoint33 waypoint9)
	(visible waypoint9 waypoint33)
	(visible waypoint33 waypoint11)
	(visible waypoint11 waypoint33)
	(visible waypoint33 waypoint36)
	(visible waypoint36 waypoint33)
	(visible waypoint33 waypoint56)
	(visible waypoint56 waypoint33)
	(visible waypoint34 waypoint4)
	(visible waypoint4 waypoint34)
	(visible waypoint34 waypoint24)
	(visible waypoint24 waypoint34)
	(visible waypoint34 waypoint33)
	(visible waypoint33 waypoint34)
	(visible waypoint34 waypoint38)
	(visible waypoint38 waypoint34)
	(visible waypoint34 waypoint44)
	(visible waypoint44 waypoint34)
	(visible waypoint34 waypoint53)
	(visible waypoint53 waypoint34)
	(visible waypoint35 waypoint7)
	(visible waypoint7 waypoint35)
	(visible waypoint35 waypoint12)
	(visible waypoint12 waypoint35)
	(visible waypoint35 waypoint34)
	(visible waypoint34 waypoint35)
	(visible waypoint36 waypoint3)
	(visible waypoint3 waypoint36)
	(visible waypoint36 waypoint5)
	(visible waypoint5 waypoint36)
	(visible waypoint36 waypoint20)
	(visible waypoint20 waypoint36)
	(visible waypoint36 waypoint29)
	(visible waypoint29 waypoint36)
	(visible waypoint36 waypoint49)
	(visible waypoint49 waypoint36)
	(visible waypoint36 waypoint55)
	(visible waypoint55 waypoint36)
	(visible waypoint37 waypoint7)
	(visible waypoint7 waypoint37)
	(visible waypoint37 waypoint16)
	(visible waypoint16 waypoint37)
	(visible waypoint37 waypoint30)
	(visible waypoint30 waypoint37)
	(visible waypoint37 waypoint43)
	(visible waypoint43 waypoint37)
	(visible waypoint37 waypoint53)
	(visible waypoint53 waypoint37)
	(visible waypoint38 waypoint4)
	(visible waypoint4 waypoint38)
	(visible waypoint39 waypoint4)
	(visible waypoint4 waypoint39)
	(visible waypoint39 waypoint5)
	(visible waypoint5 waypoint39)
	(visible waypoint39 waypoint7)
	(visible waypoint7 waypoint39)
	(visible waypoint39 waypoint30)
	(visible waypoint30 waypoint39)
	(visible waypoint39 waypoint47)
	(visible waypoint47 waypoint39)
	(visible waypoint39 waypoint48)
	(visible waypoint48 waypoint39)
	(visible waypoint40 waypoint0)
	(visible waypoint0 waypoint40)
	(visible waypoint40 waypoint1)
	(visible waypoint1 waypoint40)
	(visible waypoint40 waypoint11)
	(visible waypoint11 waypoint40)
	(visible waypoint40 waypoint24)
	(visible waypoint24 waypoint40)
	(visible waypoint40 waypoint29)
	(visible waypoint29 waypoint40)
	(visible waypoint41 waypoint13)
	(visible waypoint13 waypoint41)
	(visible waypoint41 waypoint16)
	(visible waypoint16 waypoint41)
	(visible waypoint41 waypoint35)
	(visible waypoint35 waypoint41)
	(visible waypoint42 waypoint15)
	(visible waypoint15 waypoint42)
	(visible waypoint42 waypoint19)
	(visible waypoint19 waypoint42)
	(visible waypoint42 waypoint21)
	(visible waypoint21 waypoint42)
	(visible waypoint42 waypoint25)
	(visible waypoint25 waypoint42)
	(visible waypoint42 waypoint54)
	(visible waypoint54 waypoint42)
	(visible waypoint43 waypoint4)
	(visible waypoint4 waypoint43)
	(visible waypoint43 waypoint32)
	(visible waypoint32 waypoint43)
	(visible waypoint43 waypoint51)
	(visible waypoint51 waypoint43)
	(visible waypoint43 waypoint58)
	(visible waypoint58 waypoint43)
	(visible waypoint44 waypoint3)
	(visible waypoint3 waypoint44)
	(visible waypoint44 waypoint54)
	(visible waypoint54 waypoint44)
	(visible waypoint44 waypoint56)
	(visible waypoint56 waypoint44)
	(visible waypoint44 waypoint57)
	(visible waypoint57 waypoint44)
	(visible waypoint45 waypoint12)
	(visible waypoint12 waypoint45)
	(visible waypoint45 waypoint14)
	(visible waypoint14 waypoint45)
	(visible waypoint45 waypoint24)
	(visible waypoint24 waypoint45)
	(visible waypoint45 waypoint43)
	(visible waypoint43 waypoint45)
	(visible waypoint45 waypoint48)
	(visible waypoint48 waypoint45)
	(visible waypoint45 waypoint56)
	(visible waypoint56 waypoint45)
	(visible waypoint46 waypoint10)
	(visible waypoint10 waypoint46)
	(visible waypoint46 waypoint51)
	(visible waypoint51 waypoint46)
	(visible waypoint46 waypoint58)
	(visible waypoint58 waypoint46)
	(visible waypoint47 waypoint3)
	(visible waypoint3 waypoint47)
	(visible waypoint47 waypoint4)
	(visible waypoint4 waypoint47)
	(visible waypoint47 waypoint5)
	(visible waypoint5 waypoint47)
	(visible waypoint47 waypoint27)
	(visible waypoint27 waypoint47)
	(visible waypoint47 waypoint30)
	(visible waypoint30 waypoint47)
	(visible waypoint47 waypoint31)
	(visible waypoint31 waypoint47)
	(visible waypoint48 waypoint12)
	(visible waypoint12 waypoint48)
	(visible waypoint48 waypoint14)
	(visible waypoint14 waypoint48)
	(visible waypoint48 waypoint19)
	(visible waypoint19 waypoint48)
	(visible waypoint48 waypoint49)
	(visible waypoint49 waypoint48)
	(visible waypoint48 waypoint53)
	(visible waypoint53 waypoint48)
	(visible waypoint48 waypoint56)
	(visible waypoint56 waypoint48)
	(visible waypoint49 waypoint13)
	(visible waypoint13 waypoint49)
	(visible waypoint49 waypoint20)
	(visible waypoint20 waypoint49)
	(visible waypoint49 waypoint53)
	(visible waypoint53 waypoint49)
	(visible waypoint50 waypoint17)
	(visible waypoint17 waypoint50)
	(visible waypoint50 waypoint34)
	(visible waypoint34 waypoint50)
	(visible waypoint50 waypoint39)
	(visible waypoint39 waypoint50)
	(visible waypoint50 waypoint56)
	(visible waypoint56 waypoint50)
	(visible waypoint51 waypoint12)
	(visible waypoint12 waypoint51)
	(visible waypoint51 waypoint40)
	(visible waypoint40 waypoint51)
	(visible waypoint51 waypoint44)
	(visible waypoint44 waypoint51)
	(visible waypoint52 waypoint6)
	(visible waypoint6 waypoint52)
	(visible waypoint52 waypoint12)
	(visible waypoint12 waypoint52)
	(visible waypoint52 waypoint30)
	(visible waypoint30 waypoint52)
	(visible waypoint52 waypoint33)
	(visible waypoint33 waypoint52)
	(visible waypoint52 waypoint34)
	(visible waypoint34 waypoint52)
	(visible waypoint52 waypoint38)
	(visible waypoint38 waypoint52)
	(visible waypoint52 waypoint41)
	(visible waypoint41 waypoint52)
	(visible waypoint52 waypoint55)
	(visible waypoint55 waypoint52)
	(visible waypoint53 waypoint9)
	(visible waypoint9 waypoint53)
	(visible waypoint53 waypoint47)
	(visible waypoint47 waypoint53)
	(visible waypoint53 waypoint52)
	(visible waypoint52 waypoint53)
	(visible waypoint54 waypoint9)
	(visible waypoint9 waypoint54)
	(visible waypoint54 waypoint25)
	(visible waypoint25 waypoint54)
	(visible waypoint54 waypoint37)
	(visible waypoint37 waypoint54)
	(visible waypoint54 waypoint43)
	(visible waypoint43 waypoint54)
	(visible waypoint54 waypoint45)
	(visible waypoint45 waypoint54)
	(visible waypoint55 waypoint10)
	(visible waypoint10 waypoint55)
	(visible waypoint55 waypoint23)
	(visible waypoint23 waypoint55)
	(visible waypoint55 waypoint34)
	(visible waypoint34 waypoint55)
	(visible waypoint55 waypoint53)
	(visible waypoint53 waypoint55)
	(visible waypoint56 waypoint2)
	(visible waypoint2 waypoint56)
	(visible waypoint56 waypoint40)
	(visible waypoint40 waypoint56)
	(visible waypoint56 waypoint46)
	(visible waypoint46 waypoint56)
	(visible waypoint56 waypoint49)
	(visible waypoint49 waypoint56)
	(visible waypoint57 waypoint2)
	(visible waypoint2 waypoint57)
	(visible waypoint57 waypoint25)
	(visible waypoint25 waypoint57)
	(visible waypoint57 waypoint26)
	(visible waypoint26 waypoint57)
	(visible waypoint57 waypoint36)
	(visible waypoint36 waypoint57)
	(visible waypoint58 waypoint33)
	(visible waypoint33 waypoint58)
	(visible waypoint58 waypoint53)
	(visible waypoint53 waypoint58)
	(visible waypoint59 waypoint1)
	(visible waypoint1 waypoint59)
	(visible waypoint59 waypoint5)
	(visible waypoint5 waypoint59)
	(visible waypoint59 waypoint12)
	(visible waypoint12 waypoint59)
	(visible waypoint59 waypoint28)
	(visible waypoint28 waypoint59)
	(at_soil_sample waypoint0)
	(at_soil_sample waypoint2)
	(at_soil_sample waypoint3)
	(at_rock_sample waypoint3)
	(at_soil_sample waypoint5)
	(at_rock_sample waypoint6)
	(at_soil_sample waypoint7)
	(at_rock_sample waypoint7)
	(at_soil_sample waypoint9)
	(at_soil_sample waypoint10)
	(at_soil_sample waypoint11)
	(at_soil_sample waypoint12)
	(at_soil_sample waypoint13)
	(at_rock_sample waypoint13)
	(at_soil_sample waypoint14)
	(at_soil_sample waypoint15)
	(at_rock_sample waypoint15)
	(at_soil_sample waypoint16)
	(at_rock_sample waypoint16)
	(at_soil_sample waypoint17)
	(at_soil_sample waypoint18)
	(at_rock_sample waypoint18)
	(at_soil_sample waypoint19)
	(at_soil_sample waypoint20)
	(at_rock_sample waypoint20)
	(at_rock_sample waypoint21)
	(at_soil_sample waypoint25)
	(at_rock_sample waypoint25)
	(at_rock_sample waypoint26)
	(at_soil_sample waypoint28)
	(at_rock_sample waypoint29)
	(at_rock_sample waypoint30)
	(at_soil_sample waypoint33)
	(at_soil_sample waypoint34)
	(at_rock_sample waypoint34)
	(at_soil_sample waypoint36)
	(at_rock_sample waypoint36)
	(at_soil_sample waypoint39)
	(at_soil_sample waypoint40)
	(at_rock_sample waypoint40)
	(at_soil_sample waypoint41)
	(at_rock_sample waypoint41)
	(at_soil_sample waypoint42)
	(at_soil_sample waypoint43)
	(at_rock_sample waypoint43)
	(at_soil_sample waypoint44)
	(at_rock_sample waypoint44)
	(at_soil_sample waypoint45)
	(at_rock_sample waypoint45)
	(at_soil_sample waypoint46)
	(at_rock_sample waypoint46)
	(at_soil_sample waypoint47)
	(at_soil_sample waypoint48)
	(at_soil_sample waypoint49)
	(at_soil_sample waypoint50)
	(at_rock_sample waypoint51)
	(at_soil_sample waypoint52)
	(at_rock_sample waypoint52)
	(at_soil_sample waypoint54)
	(at_rock_sample waypoint54)
	(at_rock_sample waypoint55)
	(at_soil_sample waypoint56)
	(at_rock_sample waypoint56)
	(at_soil_sample waypoint57)
	(at_rock_sample waypoint57)
	(at_soil_sample waypoint58)
	(at_soil_sample waypoint59)
	(at_rock_sample waypoint59)
	(at_lander general waypoint31)
	(channel_free general)
	(at rover0 waypoint11)
	(available rover0)
	(store_of rover0store rover0)
	(empty rover0store)
	(equipped_for_soil_analysis rover0)
	(equipped_for_imaging rover0)
	(can_traverse rover0 waypoint11 waypoint8)
	(can_traverse rover0 waypoint8 waypoint11)
	(can_traverse rover0 waypoint11 waypoint30)
	(can_traverse rover0 waypoint30 waypoint11)
	(can_traverse rover0 waypoint11 waypoint33)
	(can_traverse rover0 waypoint33 waypoint11)
	(can_traverse rover0 waypoint11 waypoint48)
	(can_traverse rover0 waypoint48 waypoint11)
	(can_traverse rover0 waypoint8 waypoint0)
	(can_traverse rover0 waypoint0 waypoint8)
	(can_traverse rover0 waypoint8 waypoint1)
	(can_traverse rover0 waypoint1 waypoint8)
	(can_traverse rover0 waypoint8 waypoint2)
	(can_traverse rover0 waypoint2 waypoint8)
	(can_traverse rover0 waypoint8 waypoint10)
	(can_traverse rover0 waypoint10 waypoint8)
	(can_traverse rover0 waypoint8 waypoint50)
	(can_traverse rover0 waypoint50 waypoint8)
	(can_traverse rover0 waypoint30 waypoint17)
	(can_traverse rover0 waypoint17 waypoint30)
	(can_traverse rover0 waypoint30 waypoint19)
	(can_traverse rover0 waypoint19 waypoint30)
	(can_traverse rover0 waypoint30 waypoint20)
	(can_traverse rover0 waypoint20 waypoint30)
	(can_traverse rover0 waypoint30 waypoint37)
	(can_traverse rover0 waypoint37 waypoint30)
	(can_traverse rover0 waypoint30 waypoint49)
	(can_traverse rover0 waypoint49 waypoint30)
	(can_traverse rover0 waypoint30 waypoint52)
	(can_traverse rover0 waypoint52 waypoint30)
	(can_traverse rover0 waypoint33 waypoint9)
	(can_traverse rover0 waypoint9 waypoint33)
	(can_traverse rover0 waypoint33 waypoint24)
	(can_traverse rover0 waypoint24 waypoint33)
	(can_traverse rover0 waypoint33 waypoint34)
	(can_traverse rover0 waypoint34 waypoint33)
	(can_traverse rover0 waypoint33 waypoint36)
	(can_traverse rover0 waypoint36 waypoint33)
	(can_traverse rover0 waypoint33 waypoint58)
	(can_traverse rover0 waypoint58 waypoint33)
	(can_traverse rover0 waypoint48 waypoint12)
	(can_traverse rover0 waypoint12 waypoint48)
	(can_traverse rover0 waypoint48 waypoint14)
	(can_traverse rover0 waypoint14 waypoint48)
	(can_traverse rover0 waypoint48 waypoint25)
	(can_traverse rover0 waypoint25 waypoint48)
	(can_traverse rover0 waypoint48 waypoint27)
	(can_traverse rover0 waypoint27 waypoint48)
	(can_traverse rover0 waypoint48 waypoint31)
	(can_traverse rover0 waypoint31 waypoint48)
	(can_traverse rover0 waypoint48 waypoint53)
	(can_traverse rover0 waypoint53 waypoint48)
	(can_traverse rover0 waypoint48 waypoint56)
	(can_traverse rover0 waypoint56 waypoint48)
	(can_traverse rover0 waypoint0 waypoint26)
	(can_traverse rover0 waypoint26 waypoint0)
	(can_traverse rover0 waypoint0 waypoint40)
	(can_traverse rover0 waypoint40 waypoint0)
	(can_traverse rover0 waypoint1 waypoint13)
	(can_traverse rover0 waypoint13 waypoint1)
	(can_traverse rover0 waypoint1 waypoint16)
	(can_traverse rover0 waypoint16 waypoint1)
	(can_traverse rover0 waypoint1 waypoint59)
	(can_traverse rover0 waypoint59 waypoint1)
	(can_traverse rover0 waypoint2 waypoint4)
	(can_traverse rover0 waypoint4 waypoint2)
	(can_traverse rover0 waypoint2 waypoint46)
	(can_traverse rover0 waypoint46 waypoint2)
	(can_traverse rover0 waypoint2 waypoint57)
	(can_traverse rover0 waypoint57 waypoint2)
	(can_traverse rover0 waypoint10 waypoint39)
	(can_traverse rover0 waypoint39 waypoint10)
	(can_traverse rover0 waypoint10 waypoint55)
	(can_traverse rover0 waypoint55 waypoint10)
	(can_traverse rover0 waypoint17 waypoint5)
	(can_traverse rover0 waypoint5 waypoint17)
	(can_traverse rover0 waypoint19 waypoint21)
	(can_traverse rover0 waypoint21 waypoint19)
	(can_traverse rover0 waypoint19 waypoint42)
	(can_traverse rover0 waypoint42 waypoint19)
	(can_traverse rover0 waypoint20 waypoint18)
	(can_traverse rover0 waypoint18 waypoint20)
	(can_traverse rover0 waypoint20 waypoint32)
	(can_traverse rover0 waypoint32 waypoint20)
	(can_traverse rover0 waypoint37 waypoint7)
	(can_traverse rover0 waypoint7 waypoint37)
	(can_traverse rover0 waypoint52 waypoint6)
	(can_traverse rover0 waypoint6 waypoint52)
	(can_traverse rover0 waypoint52 waypoint29)
	(can_traverse rover0 waypoint29 waypoint52)
	(can_traverse rover0 waypoint52 waypoint38)
	(can_traverse rover0 waypoint38 waypoint52)
	(can_traverse rover0 waypoint52 waypoint41)
	(can_traverse rover0 waypoint41 waypoint52)
	(can_traverse rover0 waypoint9 waypoint15)
	(can_traverse rover0 waypoint15 waypoint9)
	(can_traverse rover0 waypoint9 waypoint45)
	(can_traverse rover0 waypoint45 waypoint9)
	(can_traverse rover0 waypoint9 waypoint54)
	(can_traverse rover0 waypoint54 waypoint9)
	(can_traverse rover0 waypoint34 waypoint28)
	(can_traverse rover0 waypoint28 waypoint34)
	(can_traverse rover0 waypoint36 waypoint3)
	(can_traverse rover0 waypoint3 waypoint36)
	(can_traverse rover0 waypoint36 waypoint22)
	(can_traverse rover0 waypoint22 waypoint36)
	(can_traverse rover0 waypoint58 waypoint43)
	(can_traverse rover0 waypoint43 waypoint58)
	(can_traverse rover0 waypoint12 waypoint35)
	(can_traverse rover0 waypoint35 waypoint12)
	(can_traverse rover0 waypoint12 waypoint47)
	(can_traverse rover0 waypoint47 waypoint12)
	(can_traverse rover0 waypoint14 waypoint23)
	(can_traverse rover0 waypoint23 waypoint14)
	(can_traverse rover0 waypoint40 waypoint51)
	(can_traverse rover0 waypoint51 waypoint40)
	(can_traverse rover0 waypoint57 waypoint44)
	(can_traverse rover0 waypoint44 waypoint57)
	(at rover1 waypoint26)
	(available rover1)
	(store_of rover1store rover1)
	(empty rover1store)
	(equipped_for_soil_analysis rover1)
	(equipped_for_rock_analysis rover1)
	(equipped_for_imaging rover1)
	(can_traverse rover1 waypoint26 waypoint0)
	(can_traverse rover1 waypoint0 waypoint26)
	(can_traverse rover1 waypoint26 waypoint2)
	(can_traverse rover1 waypoint2 waypoint26)
	(can_traverse rover1 waypoint26 waypoint10)
	(can_traverse rover1 waypoint10 waypoint26)
	(can_traverse rover1 waypoint26 waypoint12)
	(can_traverse rover1 waypoint12 waypoint26)
	(can_traverse rover1 waypoint26 waypoint14)
	(can_traverse rover1 waypoint14 waypoint26)
	(can_traverse rover1 waypoint26 waypoint18)
	(can_traverse rover1 waypoint18 waypoint26)
	(can_traverse rover1 waypoint26 waypoint19)
	(can_traverse rover1 waypoint19 waypoint26)
	(can_traverse rover1 waypoint26 waypoint22)
	(can_traverse rover1 waypoint22 waypoint26)
	(can_traverse rover1 waypoint26 waypoint25)
	(can_traverse rover1 waypoint25 waypoint26)
	(can_traverse rover1 waypoint26 waypoint27)
	(can_traverse rover1 waypoint27 waypoint26)
	(can_traverse rover1 waypoint26 waypoint52)
	(can_traverse rover1 waypoint52 waypoint26)
	(can_traverse rover1 waypoint26 waypoint56)
	(can_traverse rover1 waypoint56 waypoint26)
	(can_traverse rover1 waypoint26 waypoint57)
	(can_traverse rover1 waypoint57 waypoint26)
	(can_traverse rover1 waypoint0 waypoint8)
	(can_traverse rover1 waypoint8 waypoint0)
	(can_traverse rover1 waypoint0 waypoint15)
	(can_traverse rover1 waypoint15 waypoint0)
	(can_traverse rover1 waypoint0 waypoint23)
	(can_traverse rover1 waypoint23 waypoint0)
	(can_traverse rover1 waypoint0 waypoint30)
	(can_traverse rover1 waypoint30 waypoint0)
	(can_traverse rover1 waypoint0 waypoint40)
	(can_traverse rover1 waypoint40 waypoint0)
	(can_traverse rover1 waypoint2 waypoint4)
	(can_traverse rover1 waypoint4 waypoint2)
	(can_traverse rover1 waypoint2 waypoint31)
	(can_traverse rover1 waypoint31 waypoint2)
	(can_traverse rover1 waypoint2 waypoint33)
	(can_traverse rover1 waypoint33 waypoint2)
	(can_traverse rover1 waypoint2 waypoint37)
	(can_traverse rover1 waypoint37 waypoint2)
	(can_traverse rover1 waypoint2 waypoint46)
	(can_traverse rover1 waypoint46 waypoint2)
	(can_traverse rover1 waypoint2 waypoint49)
	(can_traverse rover1 waypoint49 waypoint2)
	(can_traverse rover1 waypoint10 waypoint39)
	(can_traverse rover1 waypoint39 waypoint10)
	(can_traverse rover1 waypoint12 waypoint6)
	(can_traverse rover1 waypoint6 waypoint12)
	(can_traverse rover1 waypoint12 waypoint7)
	(can_traverse rover1 waypoint7 waypoint12)
	(can_traverse rover1 waypoint12 waypoint13)
	(can_traverse rover1 waypoint13 waypoint12)
	(can_traverse rover1 waypoint12 waypoint35)
	(can_traverse rover1 waypoint35 waypoint12)
	(can_traverse rover1 waypoint12 waypoint45)
	(can_traverse rover1 waypoint45 waypoint12)
	(can_traverse rover1 waypoint12 waypoint47)
	(can_traverse rover1 waypoint47 waypoint12)
	(can_traverse rover1 waypoint12 waypoint51)
	(can_traverse rover1 waypoint51 waypoint12)
	(can_traverse rover1 waypoint12 waypoint55)
	(can_traverse rover1 waypoint55 waypoint12)
	(can_traverse rover1 waypoint14 waypoint20)
	(can_traverse rover1 waypoint20 waypoint14)
	(can_traverse rover1 waypoint14 waypoint48)
	(can_traverse rover1 waypoint48 waypoint14)
	(can_traverse rover1 waypoint14 waypoint54)
	(can_traverse rover1 waypoint54 waypoint14)
	(can_traverse rover1 waypoint19 waypoint17)
	(can_traverse rover1 waypoint17 waypoint19)
	(can_traverse rover1 waypoint19 waypoint21)
	(can_traverse rover1 waypoint21 waypoint19)
	(can_traverse rover1 waypoint19 waypoint42)
	(can_traverse rover1 waypoint42 waypoint19)
	(can_traverse rover1 waypoint19 waypoint59)
	(can_traverse rover1 waypoint59 waypoint19)
	(can_traverse rover1 waypoint22 waypoint32)
	(can_traverse rover1 waypoint32 waypoint22)
	(can_traverse rover1 waypoint22 waypoint36)
	(can_traverse rover1 waypoint36 waypoint22)
	(can_traverse rover1 waypoint25 waypoint5)
	(can_traverse rover1 waypoint5 waypoint25)
	(can_traverse rover1 waypoint52 waypoint29)
	(can_traverse rover1 waypoint29 waypoint52)
	(can_traverse rover1 waypoint52 waypoint34)
	(can_traverse rover1 waypoint34 waypoint52)
	(can_traverse rover1 waypoint52 waypoint38)
	(can_traverse rover1 waypoint38 waypoint52)
	(can_traverse rover1 waypoint52 waypoint41)
	(can_traverse rover1 waypoint41 waypoint52)
	(can_traverse rover1 waypoint52 waypoint53)
	(can_traverse rover1 waypoint53 waypoint52)
	(can_traverse rover1 waypoint56 waypoint44)
	(can_traverse rover1 waypoint44 waypoint56)
	(can_traverse rover1 waypoint56 waypoint50)
	(can_traverse rover1 waypoint50 waypoint56)
	(can_traverse rover1 waypoint57 waypoint16)
	(can_traverse rover1 waypoint16 waypoint57)
	(can_traverse rover1 waypoint8 waypoint1)
	(can_traverse rover1 waypoint1 waypoint8)
	(can_traverse rover1 waypoint8 waypoint11)
	(can_traverse rover1 waypoint11 waypoint8)
	(can_traverse rover1 waypoint15 waypoint58)
	(can_traverse rover1 waypoint58 waypoint15)
	(can_traverse rover1 waypoint30 waypoint24)
	(can_traverse rover1 waypoint24 waypoint30)
	(can_traverse rover1 waypoint37 waypoint43)
	(can_traverse rover1 waypoint43 waypoint37)
	(can_traverse rover1 waypoint39 waypoint28)
	(can_traverse rover1 waypoint28 waypoint39)
	(can_traverse rover1 waypoint6 waypoint3)
	(can_traverse rover1 waypoint3 waypoint6)
	(can_traverse rover1 waypoint45 waypoint9)
	(can_traverse rover1 waypoint9 waypoint45)
	(at rover2 waypoint3)
	(available rover2)
	(store_of rover2store rover2)
	(empty rover2store)
	(equipped_for_imaging rover2)
	(can_traverse rover2 waypoint3 waypoint6)
	(can_traverse rover2 waypoint6 waypoint3)
	(can_traverse rover2 waypoint3 waypoint16)
	(can_traverse rover2 waypoint16 waypoint3)
	(can_traverse rover2 waypoint3 waypoint36)
	(can_traverse rover2 waypoint36 waypoint3)
	(can_traverse rover2 waypoint3 waypoint47)
	(can_traverse rover2 waypoint47 waypoint3)
	(can_traverse rover2 waypoint6 waypoint12)
	(can_traverse rover2 waypoint12 waypoint6)
	(can_traverse rover2 waypoint6 waypoint40)
	(can_traverse rover2 waypoint40 waypoint6)
	(can_traverse rover2 waypoint6 waypoint52)
	(can_traverse rover2 waypoint52 waypoint6)
	(can_traverse rover2 waypoint6 waypoint59)
	(can_traverse rover2 waypoint59 waypoint6)
	(can_traverse rover2 waypoint16 waypoint1)
	(can_traverse rover2 waypoint1 waypoint16)
	(can_traverse rover2 waypoint16 waypoint28)
	(can_traverse rover2 waypoint28 waypoint16)
	(can_traverse rover2 waypoint16 waypoint37)
	(can_traverse rover2 waypoint37 waypoint16)
	(can_traverse rover2 waypoint16 waypoint42)
	(can_traverse rover2 waypoint42 waypoint16)
	(can_traverse rover2 waypoint16 waypoint57)
	(can_traverse rover2 waypoint57 waypoint16)
	(can_traverse rover2 waypoint16 waypoint58)
	(can_traverse rover2 waypoint58 waypoint16)
	(can_traverse rover2 waypoint36 waypoint20)
	(can_traverse rover2 waypoint20 waypoint36)
	(can_traverse rover2 waypoint36 waypoint29)
	(can_traverse rover2 waypoint29 waypoint36)
	(can_traverse rover2 waypoint36 waypoint33)
	(can_traverse rover2 waypoint33 waypoint36)
	(can_traverse rover2 waypoint36 waypoint55)
	(can_traverse rover2 waypoint55 waypoint36)
	(can_traverse rover2 waypoint47 waypoint4)
	(can_traverse rover2 waypoint4 waypoint47)
	(can_traverse rover2 waypoint47 waypoint5)
	(can_traverse rover2 waypoint5 waypoint47)
	(can_traverse rover2 waypoint47 waypoint27)
	(can_traverse rover2 waypoint27 waypoint47)
	(can_traverse rover2 waypoint47 waypoint30)
	(can_traverse rover2 waypoint30 waypoint47)
	(can_traverse rover2 waypoint47 waypoint31)
	(can_traverse rover2 waypoint31 waypoint47)
	(can_traverse rover2 waypoint47 waypoint39)
	(can_traverse rover2 waypoint39 waypoint47)
	(can_traverse rover2 waypoint47 waypoint53)
	(can_traverse rover2 waypoint53 waypoint47)
	(can_traverse rover2 waypoint12 waypoint7)
	(can_traverse rover2 waypoint7 waypoint12)
	(can_traverse rover2 waypoint12 waypoint13)
	(can_traverse rover2 waypoint13 waypoint12)
	(can_traverse rover2 waypoint12 waypoint26)
	(can_traverse rover2 waypoint26 waypoint12)
	(can_traverse rover2 waypoint12 waypoint35)
	(can_traverse rover2 waypoint35 waypoint12)
	(can_traverse rover2 waypoint40 waypoint0)
	(can_traverse rover2 waypoint0 waypoint40)
	(can_traverse rover2 waypoint40 waypoint11)
	(can_traverse rover2 waypoint11 waypoint40)
	(can_traverse rover2 waypoint40 waypoint24)
	(can_traverse rover2 waypoint24 waypoint40)
	(can_traverse rover2 waypoint40 waypoint51)
	(can_traverse rover2 waypoint51 waypoint40)
	(can_traverse rover2 waypoint40 waypoint56)
	(can_traverse rover2 waypoint56 waypoint40)
	(can_traverse rover2 waypoint52 waypoint19)
	(can_traverse rover2 waypoint19 waypoint52)
	(can_traverse rover2 waypoint52 waypoint38)
	(can_traverse rover2 waypoint38 waypoint52)
	(can_traverse rover2 waypoint52 waypoint41)
	(can_traverse rover2 waypoint41 waypoint52)
	(can_traverse rover2 waypoint59 waypoint2)
	(can_traverse rover2 waypoint2 waypoint59)
	(can_traverse rover2 waypoint1 waypoint8)
	(can_traverse rover2 waypoint8 waypoint1)
	(can_traverse rover2 waypoint1 waypoint34)
	(can_traverse rover2 waypoint34 waypoint1)
	(can_traverse rover2 waypoint1 waypoint50)
	(can_traverse rover2 waypoint50 waypoint1)
	(can_traverse rover2 waypoint28 waypoint21)
	(can_traverse rover2 waypoint21 waypoint28)
	(can_traverse rover2 waypoint37 waypoint43)
	(can_traverse rover2 waypoint43 waypoint37)
	(can_traverse rover2 waypoint37 waypoint54)
	(can_traverse rover2 waypoint54 waypoint37)
	(can_traverse rover2 waypoint42 waypoint9)
	(can_traverse rover2 waypoint9 waypoint42)
	(can_traverse rover2 waypoint42 waypoint15)
	(can_traverse rover2 waypoint15 waypoint42)
	(can_traverse rover2 waypoint42 waypoint25)
	(can_traverse rover2 waypoint25 waypoint42)
	(can_traverse rover2 waypoint57 waypoint44)
	(can_traverse rover2 waypoint44 waypoint57)
	(can_traverse rover2 waypoint58 waypoint46)
	(can_traverse rover2 waypoint46 waypoint58)
	(can_traverse rover2 waypoint20 waypoint14)
	(can_traverse rover2 waypoint14 waypoint20)
	(can_traverse rover2 waypoint20 waypoint18)
	(can_traverse rover2 waypoint18 waypoint20)
	(can_traverse rover2 waypoint20 waypoint32)
	(can_traverse rover2 waypoint32 waypoint20)
	(can_traverse rover2 waypoint20 waypoint49)
	(can_traverse rover2 waypoint49 waypoint20)
	(can_traverse rover2 waypoint55 waypoint23)
	(can_traverse rover2 waypoint23 waypoint55)
	(can_traverse rover2 waypoint5 waypoint17)
	(can_traverse rover2 waypoint17 waypoint5)
	(can_traverse rover2 waypoint27 waypoint48)
	(can_traverse rover2 waypoint48 waypoint27)
	(can_traverse rover2 waypoint39 waypoint10)
	(can_traverse rover2 waypoint10 waypoint39)
	(can_traverse rover2 waypoint26 waypoint22)
	(can_traverse rover2 waypoint22 waypoint26)
	(can_traverse rover2 waypoint56 waypoint45)
	(can_traverse rover2 waypoint45 waypoint56)
	(at rover3 waypoint38)
	(available rover3)
	(store_of rover3store rover3)
	(empty rover3store)
	(equipped_for_soil_analysis rover3)
	(equipped_for_rock_analysis rover3)
	(equipped_for_imaging rover3)
	(can_traverse rover3 waypoint38 waypoint4)
	(can_traverse rover3 waypoint4 waypoint38)
	(can_traverse rover3 waypoint38 waypoint15)
	(can_traverse rover3 waypoint15 waypoint38)
	(can_traverse rover3 waypoint38 waypoint26)
	(can_traverse rover3 waypoint26 waypoint38)
	(can_traverse rover3 waypoint38 waypoint34)
	(can_traverse rover3 waypoint34 waypoint38)
	(can_traverse rover3 waypoint38 waypoint52)
	(can_traverse rover3 waypoint52 waypoint38)
	(can_traverse rover3 waypoint4 waypoint2)
	(can_traverse rover3 waypoint2 waypoint4)
	(can_traverse rover3 waypoint4 waypoint43)
	(can_traverse rover3 waypoint43 waypoint4)
	(can_traverse rover3 waypoint4 waypoint47)
	(can_traverse rover3 waypoint47 waypoint4)
	(can_traverse rover3 waypoint15 waypoint0)
	(can_traverse rover3 waypoint0 waypoint15)
	(can_traverse rover3 waypoint15 waypoint9)
	(can_traverse rover3 waypoint9 waypoint15)
	(can_traverse rover3 waypoint15 waypoint22)
	(can_traverse rover3 waypoint22 waypoint15)
	(can_traverse rover3 waypoint15 waypoint42)
	(can_traverse rover3 waypoint42 waypoint15)
	(can_traverse rover3 waypoint15 waypoint55)
	(can_traverse rover3 waypoint55 waypoint15)
	(can_traverse rover3 waypoint26 waypoint12)
	(can_traverse rover3 waypoint12 waypoint26)
	(can_traverse rover3 waypoint26 waypoint14)
	(can_traverse rover3 waypoint14 waypoint26)
	(can_traverse rover3 waypoint26 waypoint19)
	(can_traverse rover3 waypoint19 waypoint26)
	(can_traverse rover3 waypoint26 waypoint25)
	(can_traverse rover3 waypoint25 waypoint26)
	(can_traverse rover3 waypoint26 waypoint27)
	(can_traverse rover3 waypoint27 waypoint26)
	(can_traverse rover3 waypoint26 waypoint57)
	(can_traverse rover3 waypoint57 waypoint26)
	(can_traverse rover3 waypoint34 waypoint3)
	(can_traverse rover3 waypoint3 waypoint34)
	(can_traverse rover3 waypoint34 waypoint13)
	(can_traverse rover3 waypoint13 waypoint34)
	(can_traverse rover3 waypoint34 waypoint35)
	(can_traverse rover3 waypoint35 waypoint34)
	(can_traverse rover3 waypoint34 waypoint44)
	(can_traverse rover3 waypoint44 waypoint34)
	(can_traverse rover3 waypoint34 waypoint53)
	(can_traverse rover3 waypoint53 waypoint34)
	(can_traverse rover3 waypoint52 waypoint6)
	(can_traverse rover3 waypoint6 waypoint52)
	(can_traverse rover3 waypoint52 waypoint30)
	(can_traverse rover3 waypoint30 waypoint52)
	(can_traverse rover3 waypoint52 waypoint33)
	(can_traverse rover3 waypoint33 waypoint52)
	(can_traverse rover3 waypoint2 waypoint8)
	(can_traverse rover3 waypoint8 waypoint2)
	(can_traverse rover3 waypoint2 waypoint31)
	(can_traverse rover3 waypoint31 waypoint2)
	(can_traverse rover3 waypoint2 waypoint37)
	(can_traverse rover3 waypoint37 waypoint2)
	(can_traverse rover3 waypoint2 waypoint49)
	(can_traverse rover3 waypoint49 waypoint2)
	(can_traverse rover3 waypoint2 waypoint56)
	(can_traverse rover3 waypoint56 waypoint2)
	(can_traverse rover3 waypoint2 waypoint59)
	(can_traverse rover3 waypoint59 waypoint2)
	(can_traverse rover3 waypoint43 waypoint32)
	(can_traverse rover3 waypoint32 waypoint43)
	(can_traverse rover3 waypoint43 waypoint45)
	(can_traverse rover3 waypoint45 waypoint43)
	(can_traverse rover3 waypoint43 waypoint58)
	(can_traverse rover3 waypoint58 waypoint43)
	(can_traverse rover3 waypoint47 waypoint5)
	(can_traverse rover3 waypoint5 waypoint47)
	(can_traverse rover3 waypoint47 waypoint39)
	(can_traverse rover3 waypoint39 waypoint47)
	(can_traverse rover3 waypoint0 waypoint40)
	(can_traverse rover3 waypoint40 waypoint0)
	(can_traverse rover3 waypoint9 waypoint21)
	(can_traverse rover3 waypoint21 waypoint9)
	(can_traverse rover3 waypoint22 waypoint36)
	(can_traverse rover3 waypoint36 waypoint22)
	(can_traverse rover3 waypoint22 waypoint51)
	(can_traverse rover3 waypoint51 waypoint22)
	(can_traverse rover3 waypoint22 waypoint54)
	(can_traverse rover3 waypoint54 waypoint22)
	(can_traverse rover3 waypoint42 waypoint16)
	(can_traverse rover3 waypoint16 waypoint42)
	(can_traverse rover3 waypoint55 waypoint10)
	(can_traverse rover3 waypoint10 waypoint55)
	(can_traverse rover3 waypoint55 waypoint17)
	(can_traverse rover3 waypoint17 waypoint55)
	(can_traverse rover3 waypoint55 waypoint23)
	(can_traverse rover3 waypoint23 waypoint55)
	(can_traverse rover3 waypoint12 waypoint7)
	(can_traverse rover3 waypoint7 waypoint12)
	(can_traverse rover3 waypoint12 waypoint48)
	(can_traverse rover3 waypoint48 waypoint12)
	(can_traverse rover3 waypoint19 waypoint1)
	(can_traverse rover3 waypoint1 waypoint19)
	(can_traverse rover3 waypoint25 waypoint18)
	(can_traverse rover3 waypoint18 waypoint25)
	(can_traverse rover3 waypoint25 waypoint29)
	(can_traverse rover3 waypoint29 waypoint25)
	(can_traverse rover3 waypoint13 waypoint41)
	(can_traverse rover3 waypoint41 waypoint13)
	(can_traverse rover3 waypoint30 waypoint20)
	(can_traverse rover3 waypoint20 waypoint30)
	(can_traverse rover3 waypoint30 waypoint24)
	(can_traverse rover3 waypoint24 waypoint30)
	(can_traverse rover3 waypoint33 waypoint11)
	(can_traverse rover3 waypoint11 waypoint33)
	(can_traverse rover3 waypoint31 waypoint50)
	(can_traverse rover3 waypoint50 waypoint31)
	(can_traverse rover3 waypoint56 waypoint46)
	(can_traverse rover3 waypoint46 waypoint56)
	(on_board camera0 rover2)
	(calibration_target camera0 objective6)
	(supports camera0 colour)
	(supports camera0 high_res)
	(on_board camera1 rover3)
	(calibration_target camera1 objective4)
	(supports camera1 colour)
	(on_board camera2 rover2)
	(calibration_target camera2 objective2)
	(supports camera2 colour)
	(supports camera2 high_res)
	(supports camera2 low_res)
	(on_board camera3 rover1)
	(calibration_target camera3 objective1)
	(supports camera3 colour)
	(supports camera3 low_res)
	(on_board camera4 rover3)
	(calibration_target camera4 objective6)
	(supports camera4 high_res)
	(on_board camera5 rover1)
	(calibration_target camera5 objective1)
	(supports camera5 low_res)
	(on_board camera6 rover0)
	(calibration_target camera6 objective3)
	(supports camera6 colour)
	(supports camera6 low_res)
	(visible_from objective0 waypoint0)
	(visible_from objective0 waypoint6)
	(visible_from objective0 waypoint10)
	(visible_from objective0 waypoint14)
	(visible_from objective0 waypoint16)
	(visible_from objective0 waypoint17)
	(visible_from objective0 waypoint18)
	(visible_from objective0 waypoint24)
	(visible_from objective0 waypoint38)
	(visible_from objective0 waypoint50)
	(visible_from objective0 waypoint57)
	(visible_from objective0 waypoint59)
	(visible_from objective1 waypoint0)
	(visible_from objective1 waypoint3)
	(visible_from objective1 waypoint10)
	(visible_from objective1 waypoint20)
	(visible_from objective1 waypoint21)
	(visible_from objective1 waypoint27)
	(visible_from objective1 waypoint29)
	(visible_from objective1 waypoint39)
	(visible_from objective1 waypoint41)
	(visible_from objective1 waypoint44)
	(visible_from objective1 waypoint51)
	(visible_from objective1 waypoint53)
	(visible_from objective1 waypoint54)
	(visible_from objective1 waypoint56)
	(visible_from objective1 waypoint57)
	(visible_from objective1 waypoint58)
	(visible_from objective2 waypoint0)
	(visible_from objective2 waypoint2)
	(visible_from objective2 waypoint3)
	(visible_from objective2 waypoint4)
	(visible_from objective2 waypoint6)
	(visible_from objective2 waypoint8)
	(visible_from objective2 waypoint13)
	(visible_from objective2 waypoint16)
	(visible_from objective2 waypoint17)
	(visible_from objective2 waypoint20)
	(visible_from objective2 waypoint24)
	(visible_from objective2 waypoint27)
	(visible_from objective2 waypoint45)
	(visible_from objective2 waypoint56)
	(visible_from objective2 waypoint59)
	(visible_from objective3 waypoint0)
	(visible_from objective3 waypoint3)
	(visible_from objective3 waypoint4)
	(visible_from objective3 waypoint5)
	(visible_from objective3 waypoint9)
	(visible_from objective3 waypoint10)
	(visible_from objective3 waypoint11)
	(visible_from objective3 waypoint12)
	(visible_from objective3 waypoint14)
	(visible_from objective3 waypoint15)
	(visible_from objective3 waypoint17)
	(visible_from objective3 waypoint19)
	(visible_from objective3 waypoint20)
	(visible_from objective3 waypoint23)
	(visible_from objective3 waypoint28)
	(visible_from objective3 waypoint29)
	(visible_from objective3 waypoint31)
	(visible_from objective3 waypoint32)
	(visible_from objective3 waypoint36)
	(visible_from objective3 waypoint39)
	(visible_from objective3 waypoint40)
	(visible_from objective3 waypoint42)
	(visible_from objective3 waypoint44)
	(visible_from objective3 waypoint45)
	(visible_from objective3 waypoint47)
	(visible_from objective3 waypoint49)
	(visible_from objective3 waypoint53)
	(visible_from objective3 waypoint54)
	(visible_from objective3 waypoint58)
	(visible_from objective3 waypoint59)
	(visible_from objective4 waypoint1)
	(visible_from objective4 waypoint7)
	(visible_from objective4 waypoint10)
	(visible_from objective4 waypoint11)
	(visible_from objective4 waypoint12)
	(visible_from objective4 waypoint15)
	(visible_from objective4 waypoint20)
	(visible_from objective4 waypoint21)
	(visible_from objective4 waypoint25)
	(visible_from objective4 waypoint30)
	(visible_from objective4 waypoint32)
	(visible_from objective4 waypoint43)
	(visible_from objective4 waypoint51)
	(visible_from objective4 waypoint52)
	(visible_from objective4 waypoint58)
	(visible_from objective4 waypoint59)
	(visible_from objective5 waypoint3)
	(visible_from objective5 waypoint7)
	(visible_from objective5 waypoint9)
	(visible_from objective5 waypoint18)
	(visible_from objective5 waypoint21)
	(visible_from objective5 waypoint22)
	(visible_from objective5 waypoint23)
	(visible_from objective5 waypoint24)
	(visible_from objective5 waypoint29)
	(visible_from objective5 waypoint32)
	(visible_from objective5 waypoint36)
	(visible_from objective5 waypoint48)
	(visible_from objective5 waypoint50)
	(visible_from objective5 waypoint52)
	(visible_from objective5 waypoint59)
	(visible_from objective6 waypoint0)
	(visible_from objective6 waypoint1)
	(visible_from objective6 waypoint4)
	(visible_from objective6 waypoint6)
	(visible_from objective6 waypoint7)
	(visible_from objective6 waypoint8)
	(visible_from objective6 waypoint10)
	(visible_from objective6 waypoint12)
	(visible_from objective6 waypoint13)
	(visible_from objective6 waypoint14)
	(visible_from objective6 waypoint15)
	(visible_from objective6 waypoint16)
	(visible_from objective6 waypoint17)
	(visible_from objective6 waypoint19)
	(visible_from objective6 waypoint21)
	(visible_from objective6 waypoint22)
	(visible_from objective6 waypoint23)
	(visible_from objective6 waypoint24)
	(visible_from objective6 waypoint27)
	(visible_from objective6 waypoint28)
	(visible_from objective6 waypoint33)
	(visible_from objective6 waypoint34)
	(visible_from objective6 waypoint35)
	(visible_from objective6 waypoint39)
	(visible_from objective6 waypoint40)
	(visible_from objective6 waypoint41)
	(visible_from objective6 waypoint42)
	(visible_from objective6 waypoint44)
	(visible_from objective6 waypoint45)
	(visible_from objective6 waypoint47)
	(visible_from objective6 waypoint54)
	(visible_from objective6 waypoint55)
	(visible_from objective6 waypoint56)
	(visible_from objective6 waypoint57)
	(visible_from objective6 waypoint59)
	(visible_from objective7 waypoint2)
	(visible_from objective7 waypoint3)
	(visible_from objective7 waypoint4)
	(visible_from objective7 waypoint5)
	(visible_from objective7 waypoint6)
	(visible_from objective7 waypoint7)
	(visible_from objective7 waypoint11)
	(visible_from objective7 waypoint12)
	(visible_from objective7 waypoint13)
	(visible_from objective7 waypoint14)
	(visible_from objective7 waypoint18)
	(visible_from objective7 waypoint19)
	(visible_from objective7 waypoint21)
	(visible_from objective7 waypoint24)
	(visible_from objective7 waypoint25)
	(visible_from objective7 waypoint27)
	(visible_from objective7 waypoint28)
	(visible_from objective7 waypoint29)
	(visible_from objective7 waypoint30)
	(visible_from objective7 waypoint33)
	(visible_from objective7 waypoint35)
	(visible_from objective7 waypoint36)
	(visible_from objective7 waypoint37)
	(visible_from objective7 waypoint39)
	(visible_from objective7 waypoint41)
	(visible_from objective7 waypoint42)
	(visible_from objective7 waypoint44)
	(visible_from objective7 waypoint45)
	(visible_from objective7 waypoint48)
	(visible_from objective7 waypoint49)
	(visible_from objective7 waypoint50)
	(visible_from objective7 waypoint51)
	(visible_from objective7 waypoint53)
	(visible_from objective7 waypoint56)
	(visible_from objective7 waypoint58)
	(visible_from objective7 waypoint59)
)

(:goal (and
(communicated_soil_data waypoint36)
(communicated_soil_data waypoint13)
(communicated_soil_data waypoint49)
(communicated_soil_data waypoint19)
(communicated_soil_data waypoint59)
(communicated_soil_data waypoint57)
(communicated_soil_data waypoint12)
(communicated_soil_data waypoint41)
(communicated_soil_data waypoint47)
(communicated_soil_data waypoint46)
(communicated_soil_data waypoint40)
(communicated_soil_data waypoint16)
(communicated_soil_data waypoint42)
(communicated_rock_data waypoint18)
(communicated_rock_data waypoint56)
(communicated_rock_data waypoint21)
(communicated_rock_data waypoint46)
(communicated_rock_data waypoint41)
(communicated_rock_data waypoint52)
(communicated_rock_data waypoint25)
(communicated_rock_data waypoint51)
(communicated_rock_data waypoint16)
(communicated_rock_data waypoint54)
(communicated_rock_data waypoint45)
(communicated_rock_data waypoint30)
(communicated_rock_data waypoint7)
(communicated_rock_data waypoint3)
(communicated_rock_data waypoint6)
(communicated_rock_data waypoint43)
(communicated_rock_data waypoint15)
(communicated_rock_data waypoint55)
(communicated_image_data objective6 low_res)
(communicated_image_data objective2 low_res)
(communicated_image_data objective6 colour)
(communicated_image_data objective4 colour)
(communicated_image_data objective0 high_res)
(communicated_image_data objective6 high_res)
(communicated_image_data objective7 colour)
(communicated_image_data objective3 high_res)
(communicated_image_data objective7 high_res)
(communicated_image_data objective4 high_res)
(communicated_image_data objective3 colour)
(communicated_image_data objective3 low_res)
(communicated_image_data objective7 low_res)
	)
)
)
