(define (problem roverprob3) (:domain Rover)
(:objects
	general - Lander
	colour high_res low_res - Mode
	rover0 rover1 rover2 rover3 - Rover
	rover0store rover1store rover2store rover3store - Store
	waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 waypoint7 waypoint8 waypoint9 waypoint10 waypoint11 waypoint12 waypoint13 waypoint14 waypoint15 waypoint16 waypoint17 waypoint18 waypoint19 waypoint20 waypoint21 waypoint22 waypoint23 waypoint24 waypoint25 waypoint26 waypoint27 waypoint28 waypoint29 waypoint30 waypoint31 waypoint32 waypoint33 waypoint34 waypoint35 waypoint36 waypoint37 waypoint38 waypoint39 waypoint40 waypoint41 waypoint42 waypoint43 waypoint44 waypoint45 waypoint46 waypoint47 waypoint48 waypoint49 - Waypoint
	camera0 camera1 camera2 camera3 camera4 camera5 - Camera
	objective0 objective1 objective2 objective3 objective4 objective5 objective6 objective7 - Objective
	)
(:init
	(visible waypoint0 waypoint4)
	(visible waypoint4 waypoint0)
	(visible waypoint0 waypoint10)
	(visible waypoint10 waypoint0)
	(visible waypoint0 waypoint12)
	(visible waypoint12 waypoint0)
	(visible waypoint0 waypoint23)
	(visible waypoint23 waypoint0)
	(visible waypoint0 waypoint25)
	(visible waypoint25 waypoint0)
	(visible waypoint1 waypoint22)
	(visible waypoint22 waypoint1)
	(visible waypoint1 waypoint37)
	(visible waypoint37 waypoint1)
	(visible waypoint1 waypoint44)
	(visible waypoint44 waypoint1)
	(visible waypoint1 waypoint47)
	(visible waypoint47 waypoint1)
	(visible waypoint2 waypoint1)
	(visible waypoint1 waypoint2)
	(visible waypoint2 waypoint10)
	(visible waypoint10 waypoint2)
	(visible waypoint2 waypoint21)
	(visible waypoint21 waypoint2)
	(visible waypoint2 waypoint22)
	(visible waypoint22 waypoint2)
	(visible waypoint2 waypoint28)
	(visible waypoint28 waypoint2)
	(visible waypoint2 waypoint29)
	(visible waypoint29 waypoint2)
	(visible waypoint2 waypoint32)
	(visible waypoint32 waypoint2)
	(visible waypoint2 waypoint43)
	(visible waypoint43 waypoint2)
	(visible waypoint3 waypoint15)
	(visible waypoint15 waypoint3)
	(visible waypoint3 waypoint37)
	(visible waypoint37 waypoint3)
	(visible waypoint3 waypoint46)
	(visible waypoint46 waypoint3)
	(visible waypoint4 waypoint3)
	(visible waypoint3 waypoint4)
	(visible waypoint4 waypoint8)
	(visible waypoint8 waypoint4)
	(visible waypoint4 waypoint18)
	(visible waypoint18 waypoint4)
	(visible waypoint4 waypoint23)
	(visible waypoint23 waypoint4)
	(visible waypoint4 waypoint42)
	(visible waypoint42 waypoint4)
	(visible waypoint5 waypoint3)
	(visible waypoint3 waypoint5)
	(visible waypoint5 waypoint11)
	(visible waypoint11 waypoint5)
	(visible waypoint5 waypoint22)
	(visible waypoint22 waypoint5)
	(visible waypoint5 waypoint30)
	(visible waypoint30 waypoint5)
	(visible waypoint5 waypoint32)
	(visible waypoint32 waypoint5)
	(visible waypoint6 waypoint15)
	(visible waypoint15 waypoint6)
	(visible waypoint6 waypoint43)
	(visible waypoint43 waypoint6)
	(visible waypoint8 waypoint15)
	(visible waypoint15 waypoint8)
	(visible waypoint8 waypoint18)
	(visible waypoint18 waypoint8)
	(visible waypoint8 waypoint22)
	(visible waypoint22 waypoint8)
	(visible waypoint8 waypoint31)
	(visible waypoint31 waypoint8)
	(visible waypoint9 waypoint2)
	(visible waypoint2 waypoint9)
	(visible waypoint9 waypoint19)
	(visible waypoint19 waypoint9)
	(visible waypoint9 waypoint25)
	(visible waypoint25 waypoint9)
	(visible waypoint9 waypoint30)
	(visible waypoint30 waypoint9)
	(visible waypoint10 waypoint18)
	(visible waypoint18 waypoint10)
	(visible waypoint10 waypoint26)
	(visible waypoint26 waypoint10)
	(visible waypoint10 waypoint39)
	(visible waypoint39 waypoint10)
	(visible waypoint10 waypoint42)
	(visible waypoint42 waypoint10)
	(visible waypoint10 waypoint43)
	(visible waypoint43 waypoint10)
	(visible waypoint11 waypoint3)
	(visible waypoint3 waypoint11)
	(visible waypoint11 waypoint8)
	(visible waypoint8 waypoint11)
	(visible waypoint11 waypoint24)
	(visible waypoint24 waypoint11)
	(visible waypoint11 waypoint33)
	(visible waypoint33 waypoint11)
	(visible waypoint11 waypoint37)
	(visible waypoint37 waypoint11)
	(visible waypoint12 waypoint2)
	(visible waypoint2 waypoint12)
	(visible waypoint12 waypoint6)
	(visible waypoint6 waypoint12)
	(visible waypoint12 waypoint10)
	(visible waypoint10 waypoint12)
	(visible waypoint12 waypoint16)
	(visible waypoint16 waypoint12)
	(visible waypoint13 waypoint7)
	(visible waypoint7 waypoint13)
	(visible waypoint13 waypoint8)
	(visible waypoint8 waypoint13)
	(visible waypoint13 waypoint10)
	(visible waypoint10 waypoint13)
	(visible waypoint13 waypoint14)
	(visible waypoint14 waypoint13)
	(visible waypoint13 waypoint31)
	(visible waypoint31 waypoint13)
	(visible waypoint14 waypoint5)
	(visible waypoint5 waypoint14)
	(visible waypoint14 waypoint7)
	(visible waypoint7 waypoint14)
	(visible waypoint14 waypoint21)
	(visible waypoint21 waypoint14)
	(visible waypoint14 waypoint28)
	(visible waypoint28 waypoint14)
	(visible waypoint15 waypoint9)
	(visible waypoint9 waypoint15)
	(visible waypoint15 waypoint26)
	(visible waypoint26 waypoint15)
	(visible waypoint15 waypoint38)
	(visible waypoint38 waypoint15)
	(visible waypoint16 waypoint2)
	(visible waypoint2 waypoint16)
	(visible waypoint16 waypoint38)
	(visible waypoint38 waypoint16)
	(visible waypoint16 waypoint41)
	(visible waypoint41 waypoint16)
	(visible waypoint16 waypoint42)
	(visible waypoint42 waypoint16)
	(visible waypoint17 waypoint2)
	(visible waypoint2 waypoint17)
	(visible waypoint17 waypoint4)
	(visible waypoint4 waypoint17)
	(visible waypoint17 waypoint14)
	(visible waypoint14 waypoint17)
	(visible waypoint17 waypoint34)
	(visible waypoint34 waypoint17)
	(visible waypoint17 waypoint37)
	(visible waypoint37 waypoint17)
	(visible waypoint18 waypoint7)
	(visible waypoint7 waypoint18)
	(visible waypoint18 waypoint38)
	(visible waypoint38 waypoint18)
	(visible waypoint18 waypoint47)
	(visible waypoint47 waypoint18)
	(visible waypoint19 waypoint1)
	(visible waypoint1 waypoint19)
	(visible waypoint19 waypoint8)
	(visible waypoint8 waypoint19)
	(visible waypoint19 waypoint13)
	(visible waypoint13 waypoint19)
	(visible waypoint19 waypoint22)
	(visible waypoint22 waypoint19)
	(visible waypoint19 waypoint23)
	(visible waypoint23 waypoint19)
	(visible waypoint20 waypoint7)
	(visible waypoint7 waypoint20)
	(visible waypoint20 waypoint32)
	(visible waypoint32 waypoint20)
	(visible waypoint20 waypoint43)
	(visible waypoint43 waypoint20)
	(visible waypoint21 waypoint15)
	(visible waypoint15 waypoint21)
	(visible waypoint21 waypoint18)
	(visible waypoint18 waypoint21)
	(visible waypoint21 waypoint19)
	(visible waypoint19 waypoint21)
	(visible waypoint21 waypoint33)
	(visible waypoint33 waypoint21)
	(visible waypoint22 waypoint3)
	(visible waypoint3 waypoint22)
	(visible waypoint22 waypoint4)
	(visible waypoint4 waypoint22)
	(visible waypoint22 waypoint13)
	(visible waypoint13 waypoint22)
	(visible waypoint22 waypoint30)
	(visible waypoint30 waypoint22)
	(visible waypoint22 waypoint37)
	(visible waypoint37 waypoint22)
	(visible waypoint22 waypoint44)
	(visible waypoint44 waypoint22)
	(visible waypoint22 waypoint49)
	(visible waypoint49 waypoint22)
	(visible waypoint23 waypoint16)
	(visible waypoint16 waypoint23)
	(visible waypoint23 waypoint22)
	(visible waypoint22 waypoint23)
	(visible waypoint24 waypoint19)
	(visible waypoint19 waypoint24)
	(visible waypoint24 waypoint30)
	(visible waypoint30 waypoint24)
	(visible waypoint24 waypoint31)
	(visible waypoint31 waypoint24)
	(visible waypoint24 waypoint45)
	(visible waypoint45 waypoint24)
	(visible waypoint24 waypoint49)
	(visible waypoint49 waypoint24)
	(visible waypoint25 waypoint4)
	(visible waypoint4 waypoint25)
	(visible waypoint25 waypoint14)
	(visible waypoint14 waypoint25)
	(visible waypoint25 waypoint16)
	(visible waypoint16 waypoint25)
	(visible waypoint25 waypoint19)
	(visible waypoint19 waypoint25)
	(visible waypoint25 waypoint32)
	(visible waypoint32 waypoint25)
	(visible waypoint25 waypoint37)
	(visible waypoint37 waypoint25)
	(visible waypoint25 waypoint45)
	(visible waypoint45 waypoint25)
	(visible waypoint26 waypoint8)
	(visible waypoint8 waypoint26)
	(visible waypoint26 waypoint11)
	(visible waypoint11 waypoint26)
	(visible waypoint26 waypoint13)
	(visible waypoint13 waypoint26)
	(visible waypoint26 waypoint16)
	(visible waypoint16 waypoint26)
	(visible waypoint26 waypoint20)
	(visible waypoint20 waypoint26)
	(visible waypoint26 waypoint24)
	(visible waypoint24 waypoint26)
	(visible waypoint26 waypoint31)
	(visible waypoint31 waypoint26)
	(visible waypoint26 waypoint36)
	(visible waypoint36 waypoint26)
	(visible waypoint26 waypoint37)
	(visible waypoint37 waypoint26)
	(visible waypoint26 waypoint46)
	(visible waypoint46 waypoint26)
	(visible waypoint27 waypoint15)
	(visible waypoint15 waypoint27)
	(visible waypoint27 waypoint39)
	(visible waypoint39 waypoint27)
	(visible waypoint28 waypoint4)
	(visible waypoint4 waypoint28)
	(visible waypoint28 waypoint11)
	(visible waypoint11 waypoint28)
	(visible waypoint28 waypoint13)
	(visible waypoint13 waypoint28)
	(visible waypoint28 waypoint26)
	(visible waypoint26 waypoint28)
	(visible waypoint28 waypoint39)
	(visible waypoint39 waypoint28)
	(visible waypoint28 waypoint43)
	(visible waypoint43 waypoint28)
	(visible waypoint28 waypoint45)
	(visible waypoint45 waypoint28)
	(visible waypoint28 waypoint46)
	(visible waypoint46 waypoint28)
	(visible waypoint29 waypoint9)
	(visible waypoint9 waypoint29)
	(visible waypoint29 waypoint15)
	(visible waypoint15 waypoint29)
	(visible waypoint29 waypoint32)
	(visible waypoint32 waypoint29)
	(visible waypoint29 waypoint45)
	(visible waypoint45 waypoint29)
	(visible waypoint29 waypoint49)
	(visible waypoint49 waypoint29)
	(visible waypoint30 waypoint14)
	(visible waypoint14 waypoint30)
	(visible waypoint30 waypoint25)
	(visible waypoint25 waypoint30)
	(visible waypoint30 waypoint28)
	(visible waypoint28 waypoint30)
	(visible waypoint31 waypoint46)
	(visible waypoint46 waypoint31)
	(visible waypoint32 waypoint14)
	(visible waypoint14 waypoint32)
	(visible waypoint32 waypoint47)
	(visible waypoint47 waypoint32)
	(visible waypoint33 waypoint9)
	(visible waypoint9 waypoint33)
	(visible waypoint33 waypoint15)
	(visible waypoint15 waypoint33)
	(visible waypoint33 waypoint18)
	(visible waypoint18 waypoint33)
	(visible waypoint33 waypoint25)
	(visible waypoint25 waypoint33)
	(visible waypoint33 waypoint39)
	(visible waypoint39 waypoint33)
	(visible waypoint34 waypoint4)
	(visible waypoint4 waypoint34)
	(visible waypoint34 waypoint6)
	(visible waypoint6 waypoint34)
	(visible waypoint34 waypoint9)
	(visible waypoint9 waypoint34)
	(visible waypoint34 waypoint20)
	(visible waypoint20 waypoint34)
	(visible waypoint34 waypoint29)
	(visible waypoint29 waypoint34)
	(visible waypoint34 waypoint32)
	(visible waypoint32 waypoint34)
	(visible waypoint35 waypoint4)
	(visible waypoint4 waypoint35)
	(visible waypoint35 waypoint7)
	(visible waypoint7 waypoint35)
	(visible waypoint35 waypoint33)
	(visible waypoint33 waypoint35)
	(visible waypoint35 waypoint47)
	(visible waypoint47 waypoint35)
	(visible waypoint36 waypoint7)
	(visible waypoint7 waypoint36)
	(visible waypoint36 waypoint11)
	(visible waypoint11 waypoint36)
	(visible waypoint36 waypoint15)
	(visible waypoint15 waypoint36)
	(visible waypoint36 waypoint16)
	(visible waypoint16 waypoint36)
	(visible waypoint36 waypoint45)
	(visible waypoint45 waypoint36)
	(visible waypoint37 waypoint12)
	(visible waypoint12 waypoint37)
	(visible waypoint37 waypoint29)
	(visible waypoint29 waypoint37)
	(visible waypoint37 waypoint31)
	(visible waypoint31 waypoint37)
	(visible waypoint37 waypoint33)
	(visible waypoint33 waypoint37)
	(visible waypoint38 waypoint0)
	(visible waypoint0 waypoint38)
	(visible waypoint38 waypoint25)
	(visible waypoint25 waypoint38)
	(visible waypoint38 waypoint33)
	(visible waypoint33 waypoint38)
	(visible waypoint39 waypoint9)
	(visible waypoint9 waypoint39)
	(visible waypoint39 waypoint29)
	(visible waypoint29 waypoint39)
	(visible waypoint39 waypoint40)
	(visible waypoint40 waypoint39)
	(visible waypoint40 waypoint8)
	(visible waypoint8 waypoint40)
	(visible waypoint40 waypoint15)
	(visible waypoint15 waypoint40)
	(visible waypoint40 waypoint19)
	(visible waypoint19 waypoint40)
	(visible waypoint40 waypoint22)
	(visible waypoint22 waypoint40)
	(visible waypoint40 waypoint27)
	(visible waypoint27 waypoint40)
	(visible waypoint40 waypoint36)
	(visible waypoint36 waypoint40)
	(visible waypoint40 waypoint37)
	(visible waypoint37 waypoint40)
	(visible waypoint41 waypoint4)
	(visible waypoint4 waypoint41)
	(visible waypoint41 waypoint6)
	(visible waypoint6 waypoint41)
	(visible waypoint41 waypoint21)
	(visible waypoint21 waypoint41)
	(visible waypoint41 waypoint22)
	(visible waypoint22 waypoint41)
	(visible waypoint41 waypoint23)
	(visible waypoint23 waypoint41)
	(visible waypoint41 waypoint25)
	(visible waypoint25 waypoint41)
	(visible waypoint41 waypoint30)
	(visible waypoint30 waypoint41)
	(visible waypoint41 waypoint43)
	(visible waypoint43 waypoint41)
	(visible waypoint42 waypoint24)
	(visible waypoint24 waypoint42)
	(visible waypoint42 waypoint29)
	(visible waypoint29 waypoint42)
	(visible waypoint42 waypoint34)
	(visible waypoint34 waypoint42)
	(visible waypoint42 waypoint43)
	(visible waypoint43 waypoint42)
	(visible waypoint43 waypoint3)
	(visible waypoint3 waypoint43)
	(visible waypoint43 waypoint18)
	(visible waypoint18 waypoint43)
	(visible waypoint43 waypoint21)
	(visible waypoint21 waypoint43)
	(visible waypoint43 waypoint30)
	(visible waypoint30 waypoint43)
	(visible waypoint43 waypoint36)
	(visible waypoint36 waypoint43)
	(visible waypoint43 waypoint38)
	(visible waypoint38 waypoint43)
	(visible waypoint44 waypoint11)
	(visible waypoint11 waypoint44)
	(visible waypoint44 waypoint16)
	(visible waypoint16 waypoint44)
	(visible waypoint44 waypoint29)
	(visible waypoint29 waypoint44)
	(visible waypoint44 waypoint35)
	(visible waypoint35 waypoint44)
	(visible waypoint44 waypoint40)
	(visible waypoint40 waypoint44)
	(visible waypoint45 waypoint9)
	(visible waypoint9 waypoint45)
	(visible waypoint45 waypoint11)
	(visible waypoint11 waypoint45)
	(visible waypoint45 waypoint19)
	(visible waypoint19 waypoint45)
	(visible waypoint45 waypoint40)
	(visible waypoint40 waypoint45)
	(visible waypoint45 waypoint48)
	(visible waypoint48 waypoint45)
	(visible waypoint46 waypoint0)
	(visible waypoint0 waypoint46)
	(visible waypoint46 waypoint5)
	(visible waypoint5 waypoint46)
	(visible waypoint46 waypoint18)
	(visible waypoint18 waypoint46)
	(visible waypoint46 waypoint39)
	(visible waypoint39 waypoint46)
	(visible waypoint47 waypoint25)
	(visible waypoint25 waypoint47)
	(visible waypoint47 waypoint42)
	(visible waypoint42 waypoint47)
	(visible waypoint48 waypoint1)
	(visible waypoint1 waypoint48)
	(visible waypoint48 waypoint17)
	(visible waypoint17 waypoint48)
	(visible waypoint48 waypoint20)
	(visible waypoint20 waypoint48)
	(visible waypoint48 waypoint32)
	(visible waypoint32 waypoint48)
	(visible waypoint48 waypoint35)
	(visible waypoint35 waypoint48)
	(visible waypoint48 waypoint39)
	(visible waypoint39 waypoint48)
	(visible waypoint49 waypoint8)
	(visible waypoint8 waypoint49)
	(visible waypoint49 waypoint9)
	(visible waypoint9 waypoint49)
	(visible waypoint49 waypoint10)
	(visible waypoint10 waypoint49)
	(visible waypoint49 waypoint36)
	(visible waypoint36 waypoint49)
	(visible waypoint49 waypoint37)
	(visible waypoint37 waypoint49)
	(visible waypoint49 waypoint48)
	(visible waypoint48 waypoint49)
	(at_rock_sample waypoint1)
	(at_soil_sample waypoint3)
	(at_rock_sample waypoint3)
	(at_soil_sample waypoint4)
	(at_soil_sample waypoint5)
	(at_rock_sample waypoint5)
	(at_rock_sample waypoint6)
	(at_rock_sample waypoint7)
	(at_soil_sample waypoint8)
	(at_rock_sample waypoint8)
	(at_soil_sample waypoint10)
	(at_soil_sample waypoint15)
	(at_soil_sample waypoint16)
	(at_soil_sample waypoint17)
	(at_soil_sample waypoint18)
	(at_soil_sample waypoint19)
	(at_soil_sample waypoint21)
	(at_rock_sample waypoint21)
	(at_rock_sample waypoint22)
	(at_soil_sample waypoint24)
	(at_rock_sample waypoint24)
	(at_soil_sample waypoint27)
	(at_rock_sample waypoint27)
	(at_rock_sample waypoint28)
	(at_soil_sample waypoint30)
	(at_soil_sample waypoint31)
	(at_soil_sample waypoint32)
	(at_soil_sample waypoint33)
	(at_rock_sample waypoint33)
	(at_soil_sample waypoint34)
	(at_soil_sample waypoint35)
	(at_soil_sample waypoint36)
	(at_rock_sample waypoint36)
	(at_rock_sample waypoint38)
	(at_rock_sample waypoint39)
	(at_soil_sample waypoint40)
	(at_rock_sample waypoint40)
	(at_soil_sample waypoint41)
	(at_soil_sample waypoint42)
	(at_soil_sample waypoint43)
	(at_rock_sample waypoint43)
	(at_soil_sample waypoint44)
	(at_rock_sample waypoint44)
	(at_rock_sample waypoint48)
	(at_soil_sample waypoint49)
	(at_rock_sample waypoint49)
	(at_lander general waypoint16)
	(channel_free general)
	(at rover0 waypoint49)
	(available rover0)
	(store_of rover0store rover0)
	(empty rover0store)
	(equipped_for_soil_analysis rover0)
	(equipped_for_rock_analysis rover0)
	(equipped_for_imaging rover0)
	(can_traverse rover0 waypoint49 waypoint8)
	(can_traverse rover0 waypoint8 waypoint49)
	(can_traverse rover0 waypoint49 waypoint9)
	(can_traverse rover0 waypoint9 waypoint49)
	(can_traverse rover0 waypoint49 waypoint10)
	(can_traverse rover0 waypoint10 waypoint49)
	(can_traverse rover0 waypoint49 waypoint22)
	(can_traverse rover0 waypoint22 waypoint49)
	(can_traverse rover0 waypoint49 waypoint24)
	(can_traverse rover0 waypoint24 waypoint49)
	(can_traverse rover0 waypoint49 waypoint29)
	(can_traverse rover0 waypoint29 waypoint49)
	(can_traverse rover0 waypoint49 waypoint37)
	(can_traverse rover0 waypoint37 waypoint49)
	(can_traverse rover0 waypoint49 waypoint48)
	(can_traverse rover0 waypoint48 waypoint49)
	(can_traverse rover0 waypoint8 waypoint4)
	(can_traverse rover0 waypoint4 waypoint8)
	(can_traverse rover0 waypoint8 waypoint13)
	(can_traverse rover0 waypoint13 waypoint8)
	(can_traverse rover0 waypoint8 waypoint19)
	(can_traverse rover0 waypoint19 waypoint8)
	(can_traverse rover0 waypoint8 waypoint26)
	(can_traverse rover0 waypoint26 waypoint8)
	(can_traverse rover0 waypoint8 waypoint31)
	(can_traverse rover0 waypoint31 waypoint8)
	(can_traverse rover0 waypoint8 waypoint40)
	(can_traverse rover0 waypoint40 waypoint8)
	(can_traverse rover0 waypoint9 waypoint15)
	(can_traverse rover0 waypoint15 waypoint9)
	(can_traverse rover0 waypoint9 waypoint25)
	(can_traverse rover0 waypoint25 waypoint9)
	(can_traverse rover0 waypoint9 waypoint30)
	(can_traverse rover0 waypoint30 waypoint9)
	(can_traverse rover0 waypoint9 waypoint33)
	(can_traverse rover0 waypoint33 waypoint9)
	(can_traverse rover0 waypoint9 waypoint34)
	(can_traverse rover0 waypoint34 waypoint9)
	(can_traverse rover0 waypoint9 waypoint39)
	(can_traverse rover0 waypoint39 waypoint9)
	(can_traverse rover0 waypoint10 waypoint0)
	(can_traverse rover0 waypoint0 waypoint10)
	(can_traverse rover0 waypoint10 waypoint2)
	(can_traverse rover0 waypoint2 waypoint10)
	(can_traverse rover0 waypoint10 waypoint12)
	(can_traverse rover0 waypoint12 waypoint10)
	(can_traverse rover0 waypoint10 waypoint18)
	(can_traverse rover0 waypoint18 waypoint10)
	(can_traverse rover0 waypoint22 waypoint3)
	(can_traverse rover0 waypoint3 waypoint22)
	(can_traverse rover0 waypoint22 waypoint23)
	(can_traverse rover0 waypoint23 waypoint22)
	(can_traverse rover0 waypoint24 waypoint11)
	(can_traverse rover0 waypoint11 waypoint24)
	(can_traverse rover0 waypoint24 waypoint42)
	(can_traverse rover0 waypoint42 waypoint24)
	(can_traverse rover0 waypoint24 waypoint45)
	(can_traverse rover0 waypoint45 waypoint24)
	(can_traverse rover0 waypoint29 waypoint44)
	(can_traverse rover0 waypoint44 waypoint29)
	(can_traverse rover0 waypoint37 waypoint1)
	(can_traverse rover0 waypoint1 waypoint37)
	(can_traverse rover0 waypoint48 waypoint20)
	(can_traverse rover0 waypoint20 waypoint48)
	(can_traverse rover0 waypoint48 waypoint32)
	(can_traverse rover0 waypoint32 waypoint48)
	(can_traverse rover0 waypoint48 waypoint35)
	(can_traverse rover0 waypoint35 waypoint48)
	(can_traverse rover0 waypoint4 waypoint17)
	(can_traverse rover0 waypoint17 waypoint4)
	(can_traverse rover0 waypoint4 waypoint41)
	(can_traverse rover0 waypoint41 waypoint4)
	(can_traverse rover0 waypoint13 waypoint7)
	(can_traverse rover0 waypoint7 waypoint13)
	(can_traverse rover0 waypoint13 waypoint14)
	(can_traverse rover0 waypoint14 waypoint13)
	(can_traverse rover0 waypoint13 waypoint28)
	(can_traverse rover0 waypoint28 waypoint13)
	(can_traverse rover0 waypoint19 waypoint21)
	(can_traverse rover0 waypoint21 waypoint19)
	(can_traverse rover0 waypoint26 waypoint16)
	(can_traverse rover0 waypoint16 waypoint26)
	(can_traverse rover0 waypoint26 waypoint36)
	(can_traverse rover0 waypoint36 waypoint26)
	(can_traverse rover0 waypoint26 waypoint46)
	(can_traverse rover0 waypoint46 waypoint26)
	(can_traverse rover0 waypoint40 waypoint27)
	(can_traverse rover0 waypoint27 waypoint40)
	(can_traverse rover0 waypoint15 waypoint38)
	(can_traverse rover0 waypoint38 waypoint15)
	(can_traverse rover0 waypoint25 waypoint47)
	(can_traverse rover0 waypoint47 waypoint25)
	(can_traverse rover0 waypoint34 waypoint6)
	(can_traverse rover0 waypoint6 waypoint34)
	(can_traverse rover0 waypoint2 waypoint43)
	(can_traverse rover0 waypoint43 waypoint2)
	(can_traverse rover0 waypoint11 waypoint5)
	(can_traverse rover0 waypoint5 waypoint11)
	(at rover1 waypoint36)
	(available rover1)
	(store_of rover1store rover1)
	(empty rover1store)
	(equipped_for_rock_analysis rover1)
	(can_traverse rover1 waypoint36 waypoint7)
	(can_traverse rover1 waypoint7 waypoint36)
	(can_traverse rover1 waypoint36 waypoint11)
	(can_traverse rover1 waypoint11 waypoint36)
	(can_traverse rover1 waypoint36 waypoint15)
	(can_traverse rover1 waypoint15 waypoint36)
	(can_traverse rover1 waypoint36 waypoint16)
	(can_traverse rover1 waypoint16 waypoint36)
	(can_traverse rover1 waypoint36 waypoint26)
	(can_traverse rover1 waypoint26 waypoint36)
	(can_traverse rover1 waypoint36 waypoint40)
	(can_traverse rover1 waypoint40 waypoint36)
	(can_traverse rover1 waypoint36 waypoint45)
	(can_traverse rover1 waypoint45 waypoint36)
	(can_traverse rover1 waypoint36 waypoint49)
	(can_traverse rover1 waypoint49 waypoint36)
	(can_traverse rover1 waypoint7 waypoint13)
	(can_traverse rover1 waypoint13 waypoint7)
	(can_traverse rover1 waypoint7 waypoint14)
	(can_traverse rover1 waypoint14 waypoint7)
	(can_traverse rover1 waypoint7 waypoint18)
	(can_traverse rover1 waypoint18 waypoint7)
	(can_traverse rover1 waypoint7 waypoint35)
	(can_traverse rover1 waypoint35 waypoint7)
	(can_traverse rover1 waypoint11 waypoint3)
	(can_traverse rover1 waypoint3 waypoint11)
	(can_traverse rover1 waypoint11 waypoint5)
	(can_traverse rover1 waypoint5 waypoint11)
	(can_traverse rover1 waypoint11 waypoint8)
	(can_traverse rover1 waypoint8 waypoint11)
	(can_traverse rover1 waypoint11 waypoint24)
	(can_traverse rover1 waypoint24 waypoint11)
	(can_traverse rover1 waypoint11 waypoint33)
	(can_traverse rover1 waypoint33 waypoint11)
	(can_traverse rover1 waypoint15 waypoint9)
	(can_traverse rover1 waypoint9 waypoint15)
	(can_traverse rover1 waypoint15 waypoint27)
	(can_traverse rover1 waypoint27 waypoint15)
	(can_traverse rover1 waypoint15 waypoint29)
	(can_traverse rover1 waypoint29 waypoint15)
	(can_traverse rover1 waypoint15 waypoint38)
	(can_traverse rover1 waypoint38 waypoint15)
	(can_traverse rover1 waypoint16 waypoint2)
	(can_traverse rover1 waypoint2 waypoint16)
	(can_traverse rover1 waypoint16 waypoint12)
	(can_traverse rover1 waypoint12 waypoint16)
	(can_traverse rover1 waypoint16 waypoint23)
	(can_traverse rover1 waypoint23 waypoint16)
	(can_traverse rover1 waypoint16 waypoint25)
	(can_traverse rover1 waypoint25 waypoint16)
	(can_traverse rover1 waypoint16 waypoint41)
	(can_traverse rover1 waypoint41 waypoint16)
	(can_traverse rover1 waypoint16 waypoint42)
	(can_traverse rover1 waypoint42 waypoint16)
	(can_traverse rover1 waypoint26 waypoint10)
	(can_traverse rover1 waypoint10 waypoint26)
	(can_traverse rover1 waypoint26 waypoint31)
	(can_traverse rover1 waypoint31 waypoint26)
	(can_traverse rover1 waypoint26 waypoint37)
	(can_traverse rover1 waypoint37 waypoint26)
	(can_traverse rover1 waypoint26 waypoint46)
	(can_traverse rover1 waypoint46 waypoint26)
	(can_traverse rover1 waypoint40 waypoint39)
	(can_traverse rover1 waypoint39 waypoint40)
	(can_traverse rover1 waypoint40 waypoint44)
	(can_traverse rover1 waypoint44 waypoint40)
	(can_traverse rover1 waypoint45 waypoint28)
	(can_traverse rover1 waypoint28 waypoint45)
	(can_traverse rover1 waypoint45 waypoint48)
	(can_traverse rover1 waypoint48 waypoint45)
	(can_traverse rover1 waypoint49 waypoint22)
	(can_traverse rover1 waypoint22 waypoint49)
	(can_traverse rover1 waypoint13 waypoint19)
	(can_traverse rover1 waypoint19 waypoint13)
	(can_traverse rover1 waypoint14 waypoint21)
	(can_traverse rover1 waypoint21 waypoint14)
	(can_traverse rover1 waypoint14 waypoint30)
	(can_traverse rover1 waypoint30 waypoint14)
	(can_traverse rover1 waypoint18 waypoint4)
	(can_traverse rover1 waypoint4 waypoint18)
	(can_traverse rover1 waypoint18 waypoint47)
	(can_traverse rover1 waypoint47 waypoint18)
	(can_traverse rover1 waypoint5 waypoint32)
	(can_traverse rover1 waypoint32 waypoint5)
	(can_traverse rover1 waypoint29 waypoint34)
	(can_traverse rover1 waypoint34 waypoint29)
	(can_traverse rover1 waypoint38 waypoint0)
	(can_traverse rover1 waypoint0 waypoint38)
	(can_traverse rover1 waypoint38 waypoint43)
	(can_traverse rover1 waypoint43 waypoint38)
	(can_traverse rover1 waypoint2 waypoint1)
	(can_traverse rover1 waypoint1 waypoint2)
	(can_traverse rover1 waypoint2 waypoint17)
	(can_traverse rover1 waypoint17 waypoint2)
	(can_traverse rover1 waypoint12 waypoint6)
	(can_traverse rover1 waypoint6 waypoint12)
	(can_traverse rover1 waypoint32 waypoint20)
	(can_traverse rover1 waypoint20 waypoint32)
	(at rover2 waypoint1)
	(available rover2)
	(store_of rover2store rover2)
	(empty rover2store)
	(equipped_for_rock_analysis rover2)
	(equipped_for_imaging rover2)
	(can_traverse rover2 waypoint1 waypoint2)
	(can_traverse rover2 waypoint2 waypoint1)
	(can_traverse rover2 waypoint1 waypoint22)
	(can_traverse rover2 waypoint22 waypoint1)
	(can_traverse rover2 waypoint1 waypoint37)
	(can_traverse rover2 waypoint37 waypoint1)
	(can_traverse rover2 waypoint1 waypoint47)
	(can_traverse rover2 waypoint47 waypoint1)
	(can_traverse rover2 waypoint2 waypoint9)
	(can_traverse rover2 waypoint9 waypoint2)
	(can_traverse rover2 waypoint2 waypoint16)
	(can_traverse rover2 waypoint16 waypoint2)
	(can_traverse rover2 waypoint2 waypoint21)
	(can_traverse rover2 waypoint21 waypoint2)
	(can_traverse rover2 waypoint2 waypoint28)
	(can_traverse rover2 waypoint28 waypoint2)
	(can_traverse rover2 waypoint2 waypoint32)
	(can_traverse rover2 waypoint32 waypoint2)
	(can_traverse rover2 waypoint2 waypoint43)
	(can_traverse rover2 waypoint43 waypoint2)
	(can_traverse rover2 waypoint22 waypoint3)
	(can_traverse rover2 waypoint3 waypoint22)
	(can_traverse rover2 waypoint22 waypoint5)
	(can_traverse rover2 waypoint5 waypoint22)
	(can_traverse rover2 waypoint22 waypoint8)
	(can_traverse rover2 waypoint8 waypoint22)
	(can_traverse rover2 waypoint22 waypoint13)
	(can_traverse rover2 waypoint13 waypoint22)
	(can_traverse rover2 waypoint22 waypoint19)
	(can_traverse rover2 waypoint19 waypoint22)
	(can_traverse rover2 waypoint22 waypoint30)
	(can_traverse rover2 waypoint30 waypoint22)
	(can_traverse rover2 waypoint22 waypoint40)
	(can_traverse rover2 waypoint40 waypoint22)
	(can_traverse rover2 waypoint22 waypoint44)
	(can_traverse rover2 waypoint44 waypoint22)
	(can_traverse rover2 waypoint22 waypoint49)
	(can_traverse rover2 waypoint49 waypoint22)
	(can_traverse rover2 waypoint37 waypoint11)
	(can_traverse rover2 waypoint11 waypoint37)
	(can_traverse rover2 waypoint37 waypoint12)
	(can_traverse rover2 waypoint12 waypoint37)
	(can_traverse rover2 waypoint37 waypoint25)
	(can_traverse rover2 waypoint25 waypoint37)
	(can_traverse rover2 waypoint37 waypoint26)
	(can_traverse rover2 waypoint26 waypoint37)
	(can_traverse rover2 waypoint37 waypoint29)
	(can_traverse rover2 waypoint29 waypoint37)
	(can_traverse rover2 waypoint47 waypoint18)
	(can_traverse rover2 waypoint18 waypoint47)
	(can_traverse rover2 waypoint47 waypoint35)
	(can_traverse rover2 waypoint35 waypoint47)
	(can_traverse rover2 waypoint47 waypoint42)
	(can_traverse rover2 waypoint42 waypoint47)
	(can_traverse rover2 waypoint9 waypoint33)
	(can_traverse rover2 waypoint33 waypoint9)
	(can_traverse rover2 waypoint9 waypoint34)
	(can_traverse rover2 waypoint34 waypoint9)
	(can_traverse rover2 waypoint9 waypoint39)
	(can_traverse rover2 waypoint39 waypoint9)
	(can_traverse rover2 waypoint9 waypoint45)
	(can_traverse rover2 waypoint45 waypoint9)
	(can_traverse rover2 waypoint16 waypoint23)
	(can_traverse rover2 waypoint23 waypoint16)
	(can_traverse rover2 waypoint16 waypoint36)
	(can_traverse rover2 waypoint36 waypoint16)
	(can_traverse rover2 waypoint16 waypoint38)
	(can_traverse rover2 waypoint38 waypoint16)
	(can_traverse rover2 waypoint16 waypoint41)
	(can_traverse rover2 waypoint41 waypoint16)
	(can_traverse rover2 waypoint21 waypoint14)
	(can_traverse rover2 waypoint14 waypoint21)
	(can_traverse rover2 waypoint21 waypoint15)
	(can_traverse rover2 waypoint15 waypoint21)
	(can_traverse rover2 waypoint28 waypoint4)
	(can_traverse rover2 waypoint4 waypoint28)
	(can_traverse rover2 waypoint32 waypoint20)
	(can_traverse rover2 waypoint20 waypoint32)
	(can_traverse rover2 waypoint43 waypoint10)
	(can_traverse rover2 waypoint10 waypoint43)
	(can_traverse rover2 waypoint5 waypoint46)
	(can_traverse rover2 waypoint46 waypoint5)
	(can_traverse rover2 waypoint49 waypoint48)
	(can_traverse rover2 waypoint48 waypoint49)
	(can_traverse rover2 waypoint11 waypoint24)
	(can_traverse rover2 waypoint24 waypoint11)
	(can_traverse rover2 waypoint12 waypoint0)
	(can_traverse rover2 waypoint0 waypoint12)
	(can_traverse rover2 waypoint12 waypoint6)
	(can_traverse rover2 waypoint6 waypoint12)
	(can_traverse rover2 waypoint26 waypoint31)
	(can_traverse rover2 waypoint31 waypoint26)
	(can_traverse rover2 waypoint18 waypoint7)
	(can_traverse rover2 waypoint7 waypoint18)
	(can_traverse rover2 waypoint34 waypoint17)
	(can_traverse rover2 waypoint17 waypoint34)
	(at rover3 waypoint25)
	(available rover3)
	(store_of rover3store rover3)
	(empty rover3store)
	(equipped_for_soil_analysis rover3)
	(equipped_for_rock_analysis rover3)
	(equipped_for_imaging rover3)
	(can_traverse rover3 waypoint25 waypoint0)
	(can_traverse rover3 waypoint0 waypoint25)
	(can_traverse rover3 waypoint25 waypoint4)
	(can_traverse rover3 waypoint4 waypoint25)
	(can_traverse rover3 waypoint25 waypoint9)
	(can_traverse rover3 waypoint9 waypoint25)
	(can_traverse rover3 waypoint25 waypoint14)
	(can_traverse rover3 waypoint14 waypoint25)
	(can_traverse rover3 waypoint25 waypoint19)
	(can_traverse rover3 waypoint19 waypoint25)
	(can_traverse rover3 waypoint25 waypoint30)
	(can_traverse rover3 waypoint30 waypoint25)
	(can_traverse rover3 waypoint25 waypoint37)
	(can_traverse rover3 waypoint37 waypoint25)
	(can_traverse rover3 waypoint25 waypoint45)
	(can_traverse rover3 waypoint45 waypoint25)
	(can_traverse rover3 waypoint25 waypoint47)
	(can_traverse rover3 waypoint47 waypoint25)
	(can_traverse rover3 waypoint0 waypoint23)
	(can_traverse rover3 waypoint23 waypoint0)
	(can_traverse rover3 waypoint0 waypoint38)
	(can_traverse rover3 waypoint38 waypoint0)
	(can_traverse rover3 waypoint0 waypoint46)
	(can_traverse rover3 waypoint46 waypoint0)
	(can_traverse rover3 waypoint4 waypoint3)
	(can_traverse rover3 waypoint3 waypoint4)
	(can_traverse rover3 waypoint4 waypoint17)
	(can_traverse rover3 waypoint17 waypoint4)
	(can_traverse rover3 waypoint4 waypoint18)
	(can_traverse rover3 waypoint18 waypoint4)
	(can_traverse rover3 waypoint4 waypoint35)
	(can_traverse rover3 waypoint35 waypoint4)
	(can_traverse rover3 waypoint4 waypoint41)
	(can_traverse rover3 waypoint41 waypoint4)
	(can_traverse rover3 waypoint4 waypoint42)
	(can_traverse rover3 waypoint42 waypoint4)
	(can_traverse rover3 waypoint9 waypoint2)
	(can_traverse rover3 waypoint2 waypoint9)
	(can_traverse rover3 waypoint9 waypoint15)
	(can_traverse rover3 waypoint15 waypoint9)
	(can_traverse rover3 waypoint9 waypoint29)
	(can_traverse rover3 waypoint29 waypoint9)
	(can_traverse rover3 waypoint9 waypoint33)
	(can_traverse rover3 waypoint33 waypoint9)
	(can_traverse rover3 waypoint9 waypoint34)
	(can_traverse rover3 waypoint34 waypoint9)
	(can_traverse rover3 waypoint9 waypoint39)
	(can_traverse rover3 waypoint39 waypoint9)
	(can_traverse rover3 waypoint14 waypoint5)
	(can_traverse rover3 waypoint5 waypoint14)
	(can_traverse rover3 waypoint14 waypoint13)
	(can_traverse rover3 waypoint13 waypoint14)
	(can_traverse rover3 waypoint14 waypoint21)
	(can_traverse rover3 waypoint21 waypoint14)
	(can_traverse rover3 waypoint14 waypoint28)
	(can_traverse rover3 waypoint28 waypoint14)
	(can_traverse rover3 waypoint14 waypoint32)
	(can_traverse rover3 waypoint32 waypoint14)
	(can_traverse rover3 waypoint19 waypoint8)
	(can_traverse rover3 waypoint8 waypoint19)
	(can_traverse rover3 waypoint19 waypoint22)
	(can_traverse rover3 waypoint22 waypoint19)
	(can_traverse rover3 waypoint19 waypoint24)
	(can_traverse rover3 waypoint24 waypoint19)
	(can_traverse rover3 waypoint30 waypoint43)
	(can_traverse rover3 waypoint43 waypoint30)
	(can_traverse rover3 waypoint37 waypoint1)
	(can_traverse rover3 waypoint1 waypoint37)
	(can_traverse rover3 waypoint37 waypoint11)
	(can_traverse rover3 waypoint11 waypoint37)
	(can_traverse rover3 waypoint37 waypoint12)
	(can_traverse rover3 waypoint12 waypoint37)
	(can_traverse rover3 waypoint37 waypoint26)
	(can_traverse rover3 waypoint26 waypoint37)
	(can_traverse rover3 waypoint37 waypoint49)
	(can_traverse rover3 waypoint49 waypoint37)
	(can_traverse rover3 waypoint45 waypoint48)
	(can_traverse rover3 waypoint48 waypoint45)
	(can_traverse rover3 waypoint23 waypoint16)
	(can_traverse rover3 waypoint16 waypoint23)
	(can_traverse rover3 waypoint35 waypoint7)
	(can_traverse rover3 waypoint7 waypoint35)
	(can_traverse rover3 waypoint41 waypoint6)
	(can_traverse rover3 waypoint6 waypoint41)
	(can_traverse rover3 waypoint15 waypoint27)
	(can_traverse rover3 waypoint27 waypoint15)
	(can_traverse rover3 waypoint15 waypoint40)
	(can_traverse rover3 waypoint40 waypoint15)
	(can_traverse rover3 waypoint29 waypoint44)
	(can_traverse rover3 waypoint44 waypoint29)
	(can_traverse rover3 waypoint13 waypoint10)
	(can_traverse rover3 waypoint10 waypoint13)
	(can_traverse rover3 waypoint32 waypoint20)
	(can_traverse rover3 waypoint20 waypoint32)
	(can_traverse rover3 waypoint8 waypoint31)
	(can_traverse rover3 waypoint31 waypoint8)
	(can_traverse rover3 waypoint26 waypoint36)
	(can_traverse rover3 waypoint36 waypoint26)
	(on_board camera0 rover2)
	(calibration_target camera0 objective6)
	(supports camera0 low_res)
	(on_board camera1 rover3)
	(calibration_target camera1 objective7)
	(supports camera1 low_res)
	(on_board camera2 rover3)
	(calibration_target camera2 objective0)
	(supports camera2 high_res)
	(on_board camera3 rover3)
	(calibration_target camera3 objective6)
	(supports camera3 colour)
	(supports camera3 high_res)
	(supports camera3 low_res)
	(on_board camera4 rover0)
	(calibration_target camera4 objective0)
	(supports camera4 high_res)
	(supports camera4 low_res)
	(on_board camera5 rover0)
	(calibration_target camera5 objective5)
	(supports camera5 low_res)
	(visible_from objective0 waypoint0)
	(visible_from objective0 waypoint2)
	(visible_from objective0 waypoint3)
	(visible_from objective0 waypoint6)
	(visible_from objective0 waypoint14)
	(visible_from objective0 waypoint20)
	(visible_from objective0 waypoint21)
	(visible_from objective0 waypoint24)
	(visible_from objective0 waypoint26)
	(visible_from objective0 waypoint27)
	(visible_from objective0 waypoint32)
	(visible_from objective0 waypoint35)
	(visible_from objective0 waypoint43)
	(visible_from objective0 waypoint47)
	(visible_from objective1 waypoint16)
	(visible_from objective2 waypoint0)
	(visible_from objective2 waypoint2)
	(visible_from objective2 waypoint3)
	(visible_from objective2 waypoint4)
	(visible_from objective2 waypoint5)
	(visible_from objective2 waypoint7)
	(visible_from objective2 waypoint10)
	(visible_from objective2 waypoint18)
	(visible_from objective2 waypoint21)
	(visible_from objective2 waypoint22)
	(visible_from objective2 waypoint23)
	(visible_from objective2 waypoint24)
	(visible_from objective2 waypoint25)
	(visible_from objective2 waypoint28)
	(visible_from objective2 waypoint29)
	(visible_from objective2 waypoint30)
	(visible_from objective2 waypoint32)
	(visible_from objective2 waypoint33)
	(visible_from objective2 waypoint35)
	(visible_from objective2 waypoint38)
	(visible_from objective2 waypoint39)
	(visible_from objective2 waypoint40)
	(visible_from objective2 waypoint44)
	(visible_from objective2 waypoint45)
	(visible_from objective2 waypoint47)
	(visible_from objective2 waypoint48)
	(visible_from objective3 waypoint9)
	(visible_from objective3 waypoint10)
	(visible_from objective3 waypoint12)
	(visible_from objective3 waypoint17)
	(visible_from objective3 waypoint19)
	(visible_from objective3 waypoint21)
	(visible_from objective3 waypoint22)
	(visible_from objective3 waypoint32)
	(visible_from objective3 waypoint35)
	(visible_from objective4 waypoint1)
	(visible_from objective4 waypoint3)
	(visible_from objective4 waypoint6)
	(visible_from objective4 waypoint7)
	(visible_from objective4 waypoint8)
	(visible_from objective4 waypoint9)
	(visible_from objective4 waypoint10)
	(visible_from objective4 waypoint13)
	(visible_from objective4 waypoint14)
	(visible_from objective4 waypoint15)
	(visible_from objective4 waypoint16)
	(visible_from objective4 waypoint18)
	(visible_from objective4 waypoint19)
	(visible_from objective4 waypoint20)
	(visible_from objective4 waypoint22)
	(visible_from objective4 waypoint23)
	(visible_from objective4 waypoint24)
	(visible_from objective4 waypoint27)
	(visible_from objective4 waypoint31)
	(visible_from objective4 waypoint32)
	(visible_from objective4 waypoint34)
	(visible_from objective4 waypoint35)
	(visible_from objective4 waypoint36)
	(visible_from objective4 waypoint38)
	(visible_from objective4 waypoint39)
	(visible_from objective4 waypoint40)
	(visible_from objective4 waypoint41)
	(visible_from objective4 waypoint45)
	(visible_from objective4 waypoint48)
	(visible_from objective4 waypoint49)
	(visible_from objective5 waypoint5)
	(visible_from objective5 waypoint6)
	(visible_from objective5 waypoint9)
	(visible_from objective5 waypoint12)
	(visible_from objective5 waypoint14)
	(visible_from objective5 waypoint15)
	(visible_from objective5 waypoint17)
	(visible_from objective5 waypoint19)
	(visible_from objective5 waypoint21)
	(visible_from objective5 waypoint25)
	(visible_from objective5 waypoint26)
	(visible_from objective5 waypoint27)
	(visible_from objective5 waypoint29)
	(visible_from objective5 waypoint30)
	(visible_from objective5 waypoint31)
	(visible_from objective5 waypoint33)
	(visible_from objective5 waypoint35)
	(visible_from objective5 waypoint36)
	(visible_from objective5 waypoint38)
	(visible_from objective5 waypoint39)
	(visible_from objective5 waypoint42)
	(visible_from objective5 waypoint43)
	(visible_from objective5 waypoint44)
	(visible_from objective5 waypoint49)
	(visible_from objective6 waypoint20)
	(visible_from objective6 waypoint37)
	(visible_from objective6 waypoint42)
	(visible_from objective7 waypoint0)
	(visible_from objective7 waypoint1)
	(visible_from objective7 waypoint4)
	(visible_from objective7 waypoint5)
	(visible_from objective7 waypoint7)
	(visible_from objective7 waypoint9)
	(visible_from objective7 waypoint11)
	(visible_from objective7 waypoint12)
	(visible_from objective7 waypoint14)
	(visible_from objective7 waypoint16)
	(visible_from objective7 waypoint19)
	(visible_from objective7 waypoint22)
	(visible_from objective7 waypoint27)
	(visible_from objective7 waypoint29)
	(visible_from objective7 waypoint31)
	(visible_from objective7 waypoint32)
	(visible_from objective7 waypoint33)
	(visible_from objective7 waypoint35)
	(visible_from objective7 waypoint36)
	(visible_from objective7 waypoint37)
	(visible_from objective7 waypoint38)
	(visible_from objective7 waypoint39)
	(visible_from objective7 waypoint49)
)

(:goal (and
(communicated_soil_data waypoint44)
(communicated_soil_data waypoint16)
(communicated_soil_data waypoint49)
(communicated_soil_data waypoint41)
(communicated_soil_data waypoint34)
(communicated_soil_data waypoint24)
(communicated_soil_data waypoint10)
(communicated_soil_data waypoint17)
(communicated_soil_data waypoint36)
(communicated_soil_data waypoint27)
(communicated_soil_data waypoint42)
(communicated_soil_data waypoint4)
(communicated_soil_data waypoint18)
(communicated_soil_data waypoint30)
(communicated_soil_data waypoint21)
(communicated_soil_data waypoint19)
(communicated_rock_data waypoint48)
(communicated_rock_data waypoint43)
(communicated_rock_data waypoint3)
(communicated_rock_data waypoint28)
(communicated_rock_data waypoint36)
(communicated_rock_data waypoint6)
(communicated_rock_data waypoint49)
(communicated_rock_data waypoint1)
(communicated_rock_data waypoint44)
(communicated_rock_data waypoint33)
(communicated_image_data objective2 high_res)
(communicated_image_data objective5 low_res)
(communicated_image_data objective2 low_res)
(communicated_image_data objective4 high_res)
(communicated_image_data objective5 colour)
(communicated_image_data objective7 low_res)
(communicated_image_data objective4 low_res)
	)
)
)
