(define (problem roverprob1) (:domain Rover)
(:objects
	general - Lander
	colour high_res low_res - Mode
	rover0 rover1 rover2 rover3 - Rover
	rover0store rover1store rover2store rover3store - Store
	waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 waypoint7 waypoint8 waypoint9 waypoint10 waypoint11 waypoint12 waypoint13 waypoint14 waypoint15 waypoint16 waypoint17 waypoint18 waypoint19 waypoint20 waypoint21 waypoint22 waypoint23 waypoint24 waypoint25 waypoint26 waypoint27 waypoint28 waypoint29 waypoint30 waypoint31 waypoint32 waypoint33 waypoint34 waypoint35 waypoint36 waypoint37 waypoint38 waypoint39 waypoint40 waypoint41 waypoint42 waypoint43 waypoint44 waypoint45 waypoint46 waypoint47 waypoint48 waypoint49 - Waypoint
	camera0 camera1 camera2 camera3 camera4 camera5 camera6 - Camera
	objective0 objective1 objective2 objective3 objective4 objective5 objective6 objective7 - Objective
	)
(:init
	(visible waypoint0 waypoint12)
	(visible waypoint12 waypoint0)
	(visible waypoint0 waypoint46)
	(visible waypoint46 waypoint0)
	(visible waypoint1 waypoint37)
	(visible waypoint37 waypoint1)
	(visible waypoint2 waypoint7)
	(visible waypoint7 waypoint2)
	(visible waypoint2 waypoint22)
	(visible waypoint22 waypoint2)
	(visible waypoint2 waypoint26)
	(visible waypoint26 waypoint2)
	(visible waypoint3 waypoint1)
	(visible waypoint1 waypoint3)
	(visible waypoint3 waypoint4)
	(visible waypoint4 waypoint3)
	(visible waypoint3 waypoint10)
	(visible waypoint10 waypoint3)
	(visible waypoint3 waypoint31)
	(visible waypoint31 waypoint3)
	(visible waypoint3 waypoint34)
	(visible waypoint34 waypoint3)
	(visible waypoint3 waypoint47)
	(visible waypoint47 waypoint3)
	(visible waypoint4 waypoint6)
	(visible waypoint6 waypoint4)
	(visible waypoint4 waypoint19)
	(visible waypoint19 waypoint4)
	(visible waypoint5 waypoint18)
	(visible waypoint18 waypoint5)
	(visible waypoint5 waypoint29)
	(visible waypoint29 waypoint5)
	(visible waypoint5 waypoint32)
	(visible waypoint32 waypoint5)
	(visible waypoint5 waypoint33)
	(visible waypoint33 waypoint5)
	(visible waypoint6 waypoint5)
	(visible waypoint5 waypoint6)
	(visible waypoint6 waypoint18)
	(visible waypoint18 waypoint6)
	(visible waypoint6 waypoint34)
	(visible waypoint34 waypoint6)
	(visible waypoint6 waypoint39)
	(visible waypoint39 waypoint6)
	(visible waypoint6 waypoint40)
	(visible waypoint40 waypoint6)
	(visible waypoint7 waypoint1)
	(visible waypoint1 waypoint7)
	(visible waypoint7 waypoint3)
	(visible waypoint3 waypoint7)
	(visible waypoint7 waypoint20)
	(visible waypoint20 waypoint7)
	(visible waypoint7 waypoint25)
	(visible waypoint25 waypoint7)
	(visible waypoint7 waypoint30)
	(visible waypoint30 waypoint7)
	(visible waypoint7 waypoint36)
	(visible waypoint36 waypoint7)
	(visible waypoint7 waypoint44)
	(visible waypoint44 waypoint7)
	(visible waypoint8 waypoint11)
	(visible waypoint11 waypoint8)
	(visible waypoint8 waypoint12)
	(visible waypoint12 waypoint8)
	(visible waypoint8 waypoint13)
	(visible waypoint13 waypoint8)
	(visible waypoint8 waypoint19)
	(visible waypoint19 waypoint8)
	(visible waypoint8 waypoint37)
	(visible waypoint37 waypoint8)
	(visible waypoint8 waypoint41)
	(visible waypoint41 waypoint8)
	(visible waypoint8 waypoint45)
	(visible waypoint45 waypoint8)
	(visible waypoint9 waypoint13)
	(visible waypoint13 waypoint9)
	(visible waypoint9 waypoint21)
	(visible waypoint21 waypoint9)
	(visible waypoint9 waypoint30)
	(visible waypoint30 waypoint9)
	(visible waypoint9 waypoint33)
	(visible waypoint33 waypoint9)
	(visible waypoint9 waypoint34)
	(visible waypoint34 waypoint9)
	(visible waypoint10 waypoint20)
	(visible waypoint20 waypoint10)
	(visible waypoint10 waypoint23)
	(visible waypoint23 waypoint10)
	(visible waypoint11 waypoint19)
	(visible waypoint19 waypoint11)
	(visible waypoint11 waypoint32)
	(visible waypoint32 waypoint11)
	(visible waypoint11 waypoint44)
	(visible waypoint44 waypoint11)
	(visible waypoint11 waypoint48)
	(visible waypoint48 waypoint11)
	(visible waypoint12 waypoint16)
	(visible waypoint16 waypoint12)
	(visible waypoint12 waypoint38)
	(visible waypoint38 waypoint12)
	(visible waypoint13 waypoint26)
	(visible waypoint26 waypoint13)
	(visible waypoint13 waypoint27)
	(visible waypoint27 waypoint13)
	(visible waypoint13 waypoint32)
	(visible waypoint32 waypoint13)
	(visible waypoint13 waypoint43)
	(visible waypoint43 waypoint13)
	(visible waypoint14 waypoint5)
	(visible waypoint5 waypoint14)
	(visible waypoint14 waypoint11)
	(visible waypoint11 waypoint14)
	(visible waypoint14 waypoint17)
	(visible waypoint17 waypoint14)
	(visible waypoint14 waypoint27)
	(visible waypoint27 waypoint14)
	(visible waypoint14 waypoint36)
	(visible waypoint36 waypoint14)
	(visible waypoint14 waypoint38)
	(visible waypoint38 waypoint14)
	(visible waypoint14 waypoint45)
	(visible waypoint45 waypoint14)
	(visible waypoint15 waypoint11)
	(visible waypoint11 waypoint15)
	(visible waypoint15 waypoint13)
	(visible waypoint13 waypoint15)
	(visible waypoint15 waypoint21)
	(visible waypoint21 waypoint15)
	(visible waypoint15 waypoint32)
	(visible waypoint32 waypoint15)
	(visible waypoint15 waypoint36)
	(visible waypoint36 waypoint15)
	(visible waypoint15 waypoint44)
	(visible waypoint44 waypoint15)
	(visible waypoint15 waypoint49)
	(visible waypoint49 waypoint15)
	(visible waypoint16 waypoint4)
	(visible waypoint4 waypoint16)
	(visible waypoint16 waypoint9)
	(visible waypoint9 waypoint16)
	(visible waypoint16 waypoint11)
	(visible waypoint11 waypoint16)
	(visible waypoint16 waypoint38)
	(visible waypoint38 waypoint16)
	(visible waypoint16 waypoint42)
	(visible waypoint42 waypoint16)
	(visible waypoint16 waypoint46)
	(visible waypoint46 waypoint16)
	(visible waypoint17 waypoint9)
	(visible waypoint9 waypoint17)
	(visible waypoint17 waypoint27)
	(visible waypoint27 waypoint17)
	(visible waypoint17 waypoint29)
	(visible waypoint29 waypoint17)
	(visible waypoint17 waypoint34)
	(visible waypoint34 waypoint17)
	(visible waypoint17 waypoint40)
	(visible waypoint40 waypoint17)
	(visible waypoint17 waypoint43)
	(visible waypoint43 waypoint17)
	(visible waypoint18 waypoint14)
	(visible waypoint14 waypoint18)
	(visible waypoint18 waypoint25)
	(visible waypoint25 waypoint18)
	(visible waypoint18 waypoint35)
	(visible waypoint35 waypoint18)
	(visible waypoint18 waypoint38)
	(visible waypoint38 waypoint18)
	(visible waypoint19 waypoint32)
	(visible waypoint32 waypoint19)
	(visible waypoint19 waypoint38)
	(visible waypoint38 waypoint19)
	(visible waypoint19 waypoint40)
	(visible waypoint40 waypoint19)
	(visible waypoint20 waypoint0)
	(visible waypoint0 waypoint20)
	(visible waypoint20 waypoint34)
	(visible waypoint34 waypoint20)
	(visible waypoint20 waypoint44)
	(visible waypoint44 waypoint20)
	(visible waypoint21 waypoint0)
	(visible waypoint0 waypoint21)
	(visible waypoint21 waypoint46)
	(visible waypoint46 waypoint21)
	(visible waypoint22 waypoint3)
	(visible waypoint3 waypoint22)
	(visible waypoint22 waypoint11)
	(visible waypoint11 waypoint22)
	(visible waypoint22 waypoint39)
	(visible waypoint39 waypoint22)
	(visible waypoint22 waypoint44)
	(visible waypoint44 waypoint22)
	(visible waypoint23 waypoint8)
	(visible waypoint8 waypoint23)
	(visible waypoint23 waypoint29)
	(visible waypoint29 waypoint23)
	(visible waypoint23 waypoint31)
	(visible waypoint31 waypoint23)
	(visible waypoint23 waypoint40)
	(visible waypoint40 waypoint23)
	(visible waypoint23 waypoint42)
	(visible waypoint42 waypoint23)
	(visible waypoint24 waypoint6)
	(visible waypoint6 waypoint24)
	(visible waypoint24 waypoint7)
	(visible waypoint7 waypoint24)
	(visible waypoint24 waypoint10)
	(visible waypoint10 waypoint24)
	(visible waypoint24 waypoint11)
	(visible waypoint11 waypoint24)
	(visible waypoint24 waypoint14)
	(visible waypoint14 waypoint24)
	(visible waypoint24 waypoint15)
	(visible waypoint15 waypoint24)
	(visible waypoint24 waypoint16)
	(visible waypoint16 waypoint24)
	(visible waypoint24 waypoint28)
	(visible waypoint28 waypoint24)
	(visible waypoint24 waypoint38)
	(visible waypoint38 waypoint24)
	(visible waypoint24 waypoint48)
	(visible waypoint48 waypoint24)
	(visible waypoint25 waypoint10)
	(visible waypoint10 waypoint25)
	(visible waypoint25 waypoint20)
	(visible waypoint20 waypoint25)
	(visible waypoint25 waypoint33)
	(visible waypoint33 waypoint25)
	(visible waypoint25 waypoint41)
	(visible waypoint41 waypoint25)
	(visible waypoint25 waypoint48)
	(visible waypoint48 waypoint25)
	(visible waypoint26 waypoint1)
	(visible waypoint1 waypoint26)
	(visible waypoint26 waypoint3)
	(visible waypoint3 waypoint26)
	(visible waypoint26 waypoint4)
	(visible waypoint4 waypoint26)
	(visible waypoint26 waypoint7)
	(visible waypoint7 waypoint26)
	(visible waypoint26 waypoint37)
	(visible waypoint37 waypoint26)
	(visible waypoint26 waypoint38)
	(visible waypoint38 waypoint26)
	(visible waypoint26 waypoint42)
	(visible waypoint42 waypoint26)
	(visible waypoint27 waypoint0)
	(visible waypoint0 waypoint27)
	(visible waypoint27 waypoint20)
	(visible waypoint20 waypoint27)
	(visible waypoint27 waypoint21)
	(visible waypoint21 waypoint27)
	(visible waypoint27 waypoint45)
	(visible waypoint45 waypoint27)
	(visible waypoint28 waypoint22)
	(visible waypoint22 waypoint28)
	(visible waypoint28 waypoint26)
	(visible waypoint26 waypoint28)
	(visible waypoint28 waypoint29)
	(visible waypoint29 waypoint28)
	(visible waypoint28 waypoint37)
	(visible waypoint37 waypoint28)
	(visible waypoint28 waypoint43)
	(visible waypoint43 waypoint28)
	(visible waypoint29 waypoint9)
	(visible waypoint9 waypoint29)
	(visible waypoint29 waypoint12)
	(visible waypoint12 waypoint29)
	(visible waypoint29 waypoint13)
	(visible waypoint13 waypoint29)
	(visible waypoint29 waypoint18)
	(visible waypoint18 waypoint29)
	(visible waypoint30 waypoint12)
	(visible waypoint12 waypoint30)
	(visible waypoint30 waypoint14)
	(visible waypoint14 waypoint30)
	(visible waypoint30 waypoint24)
	(visible waypoint24 waypoint30)
	(visible waypoint30 waypoint26)
	(visible waypoint26 waypoint30)
	(visible waypoint30 waypoint29)
	(visible waypoint29 waypoint30)
	(visible waypoint30 waypoint31)
	(visible waypoint31 waypoint30)
	(visible waypoint30 waypoint32)
	(visible waypoint32 waypoint30)
	(visible waypoint31 waypoint2)
	(visible waypoint2 waypoint31)
	(visible waypoint31 waypoint11)
	(visible waypoint11 waypoint31)
	(visible waypoint31 waypoint17)
	(visible waypoint17 waypoint31)
	(visible waypoint31 waypoint26)
	(visible waypoint26 waypoint31)
	(visible waypoint31 waypoint35)
	(visible waypoint35 waypoint31)
	(visible waypoint31 waypoint37)
	(visible waypoint37 waypoint31)
	(visible waypoint31 waypoint41)
	(visible waypoint41 waypoint31)
	(visible waypoint32 waypoint0)
	(visible waypoint0 waypoint32)
	(visible waypoint32 waypoint1)
	(visible waypoint1 waypoint32)
	(visible waypoint32 waypoint12)
	(visible waypoint12 waypoint32)
	(visible waypoint32 waypoint21)
	(visible waypoint21 waypoint32)
	(visible waypoint32 waypoint38)
	(visible waypoint38 waypoint32)
	(visible waypoint32 waypoint42)
	(visible waypoint42 waypoint32)
	(visible waypoint32 waypoint48)
	(visible waypoint48 waypoint32)
	(visible waypoint33 waypoint14)
	(visible waypoint14 waypoint33)
	(visible waypoint33 waypoint24)
	(visible waypoint24 waypoint33)
	(visible waypoint33 waypoint31)
	(visible waypoint31 waypoint33)
	(visible waypoint33 waypoint43)
	(visible waypoint43 waypoint33)
	(visible waypoint34 waypoint4)
	(visible waypoint4 waypoint34)
	(visible waypoint34 waypoint8)
	(visible waypoint8 waypoint34)
	(visible waypoint34 waypoint15)
	(visible waypoint15 waypoint34)
	(visible waypoint34 waypoint19)
	(visible waypoint19 waypoint34)
	(visible waypoint34 waypoint22)
	(visible waypoint22 waypoint34)
	(visible waypoint34 waypoint40)
	(visible waypoint40 waypoint34)
	(visible waypoint34 waypoint45)
	(visible waypoint45 waypoint34)
	(visible waypoint35 waypoint5)
	(visible waypoint5 waypoint35)
	(visible waypoint35 waypoint9)
	(visible waypoint9 waypoint35)
	(visible waypoint35 waypoint15)
	(visible waypoint15 waypoint35)
	(visible waypoint35 waypoint28)
	(visible waypoint28 waypoint35)
	(visible waypoint36 waypoint6)
	(visible waypoint6 waypoint36)
	(visible waypoint36 waypoint16)
	(visible waypoint16 waypoint36)
	(visible waypoint36 waypoint31)
	(visible waypoint31 waypoint36)
	(visible waypoint37 waypoint10)
	(visible waypoint10 waypoint37)
	(visible waypoint37 waypoint18)
	(visible waypoint18 waypoint37)
	(visible waypoint38 waypoint34)
	(visible waypoint34 waypoint38)
	(visible waypoint39 waypoint15)
	(visible waypoint15 waypoint39)
	(visible waypoint39 waypoint27)
	(visible waypoint27 waypoint39)
	(visible waypoint39 waypoint35)
	(visible waypoint35 waypoint39)
	(visible waypoint39 waypoint36)
	(visible waypoint36 waypoint39)
	(visible waypoint39 waypoint38)
	(visible waypoint38 waypoint39)
	(visible waypoint40 waypoint33)
	(visible waypoint33 waypoint40)
	(visible waypoint40 waypoint45)
	(visible waypoint45 waypoint40)
	(visible waypoint41 waypoint11)
	(visible waypoint11 waypoint41)
	(visible waypoint41 waypoint14)
	(visible waypoint14 waypoint41)
	(visible waypoint41 waypoint16)
	(visible waypoint16 waypoint41)
	(visible waypoint41 waypoint19)
	(visible waypoint19 waypoint41)
	(visible waypoint41 waypoint36)
	(visible waypoint36 waypoint41)
	(visible waypoint41 waypoint40)
	(visible waypoint40 waypoint41)
	(visible waypoint41 waypoint46)
	(visible waypoint46 waypoint41)
	(visible waypoint42 waypoint19)
	(visible waypoint19 waypoint42)
	(visible waypoint43 waypoint3)
	(visible waypoint3 waypoint43)
	(visible waypoint43 waypoint4)
	(visible waypoint4 waypoint43)
	(visible waypoint43 waypoint10)
	(visible waypoint10 waypoint43)
	(visible waypoint43 waypoint24)
	(visible waypoint24 waypoint43)
	(visible waypoint43 waypoint36)
	(visible waypoint36 waypoint43)
	(visible waypoint43 waypoint41)
	(visible waypoint41 waypoint43)
	(visible waypoint44 waypoint3)
	(visible waypoint3 waypoint44)
	(visible waypoint44 waypoint6)
	(visible waypoint6 waypoint44)
	(visible waypoint44 waypoint9)
	(visible waypoint9 waypoint44)
	(visible waypoint44 waypoint17)
	(visible waypoint17 waypoint44)
	(visible waypoint44 waypoint31)
	(visible waypoint31 waypoint44)
	(visible waypoint45 waypoint9)
	(visible waypoint9 waypoint45)
	(visible waypoint45 waypoint31)
	(visible waypoint31 waypoint45)
	(visible waypoint45 waypoint42)
	(visible waypoint42 waypoint45)
	(visible waypoint45 waypoint43)
	(visible waypoint43 waypoint45)
	(visible waypoint45 waypoint49)
	(visible waypoint49 waypoint45)
	(visible waypoint46 waypoint8)
	(visible waypoint8 waypoint46)
	(visible waypoint46 waypoint34)
	(visible waypoint34 waypoint46)
	(visible waypoint46 waypoint36)
	(visible waypoint36 waypoint46)
	(visible waypoint47 waypoint22)
	(visible waypoint22 waypoint47)
	(visible waypoint47 waypoint29)
	(visible waypoint29 waypoint47)
	(visible waypoint47 waypoint45)
	(visible waypoint45 waypoint47)
	(visible waypoint47 waypoint46)
	(visible waypoint46 waypoint47)
	(visible waypoint48 waypoint37)
	(visible waypoint37 waypoint48)
	(visible waypoint49 waypoint0)
	(visible waypoint0 waypoint49)
	(visible waypoint49 waypoint2)
	(visible waypoint2 waypoint49)
	(visible waypoint49 waypoint10)
	(visible waypoint10 waypoint49)
	(visible waypoint49 waypoint16)
	(visible waypoint16 waypoint49)
	(visible waypoint49 waypoint35)
	(visible waypoint35 waypoint49)
	(visible waypoint49 waypoint46)
	(visible waypoint46 waypoint49)
	(at_soil_sample waypoint1)
	(at_soil_sample waypoint2)
	(at_rock_sample waypoint2)
	(at_soil_sample waypoint3)
	(at_rock_sample waypoint4)
	(at_soil_sample waypoint5)
	(at_rock_sample waypoint6)
	(at_soil_sample waypoint8)
	(at_rock_sample waypoint8)
	(at_rock_sample waypoint9)
	(at_soil_sample waypoint10)
	(at_soil_sample waypoint11)
	(at_rock_sample waypoint12)
	(at_rock_sample waypoint14)
	(at_soil_sample waypoint15)
	(at_rock_sample waypoint16)
	(at_soil_sample waypoint17)
	(at_soil_sample waypoint22)
	(at_soil_sample waypoint23)
	(at_rock_sample waypoint23)
	(at_soil_sample waypoint24)
	(at_rock_sample waypoint24)
	(at_soil_sample waypoint25)
	(at_soil_sample waypoint26)
	(at_rock_sample waypoint26)
	(at_soil_sample waypoint27)
	(at_rock_sample waypoint27)
	(at_rock_sample waypoint28)
	(at_rock_sample waypoint31)
	(at_soil_sample waypoint34)
	(at_soil_sample waypoint35)
	(at_soil_sample waypoint36)
	(at_rock_sample waypoint36)
	(at_soil_sample waypoint37)
	(at_soil_sample waypoint38)
	(at_rock_sample waypoint38)
	(at_soil_sample waypoint39)
	(at_rock_sample waypoint39)
	(at_soil_sample waypoint40)
	(at_soil_sample waypoint42)
	(at_rock_sample waypoint42)
	(at_rock_sample waypoint43)
	(at_soil_sample waypoint44)
	(at_rock_sample waypoint44)
	(at_rock_sample waypoint45)
	(at_soil_sample waypoint46)
	(at_soil_sample waypoint47)
	(at_rock_sample waypoint47)
	(at_soil_sample waypoint49)
	(at_lander general waypoint33)
	(channel_free general)
	(at rover0 waypoint45)
	(available rover0)
	(store_of rover0store rover0)
	(empty rover0store)
	(equipped_for_soil_analysis rover0)
	(equipped_for_imaging rover0)
	(can_traverse rover0 waypoint45 waypoint8)
	(can_traverse rover0 waypoint8 waypoint45)
	(can_traverse rover0 waypoint45 waypoint9)
	(can_traverse rover0 waypoint9 waypoint45)
	(can_traverse rover0 waypoint45 waypoint14)
	(can_traverse rover0 waypoint14 waypoint45)
	(can_traverse rover0 waypoint45 waypoint27)
	(can_traverse rover0 waypoint27 waypoint45)
	(can_traverse rover0 waypoint45 waypoint34)
	(can_traverse rover0 waypoint34 waypoint45)
	(can_traverse rover0 waypoint45 waypoint40)
	(can_traverse rover0 waypoint40 waypoint45)
	(can_traverse rover0 waypoint45 waypoint42)
	(can_traverse rover0 waypoint42 waypoint45)
	(can_traverse rover0 waypoint45 waypoint43)
	(can_traverse rover0 waypoint43 waypoint45)
	(can_traverse rover0 waypoint45 waypoint47)
	(can_traverse rover0 waypoint47 waypoint45)
	(can_traverse rover0 waypoint45 waypoint49)
	(can_traverse rover0 waypoint49 waypoint45)
	(can_traverse rover0 waypoint8 waypoint11)
	(can_traverse rover0 waypoint11 waypoint8)
	(can_traverse rover0 waypoint8 waypoint12)
	(can_traverse rover0 waypoint12 waypoint8)
	(can_traverse rover0 waypoint8 waypoint13)
	(can_traverse rover0 waypoint13 waypoint8)
	(can_traverse rover0 waypoint8 waypoint19)
	(can_traverse rover0 waypoint19 waypoint8)
	(can_traverse rover0 waypoint8 waypoint23)
	(can_traverse rover0 waypoint23 waypoint8)
	(can_traverse rover0 waypoint8 waypoint37)
	(can_traverse rover0 waypoint37 waypoint8)
	(can_traverse rover0 waypoint8 waypoint41)
	(can_traverse rover0 waypoint41 waypoint8)
	(can_traverse rover0 waypoint8 waypoint46)
	(can_traverse rover0 waypoint46 waypoint8)
	(can_traverse rover0 waypoint9 waypoint16)
	(can_traverse rover0 waypoint16 waypoint9)
	(can_traverse rover0 waypoint9 waypoint17)
	(can_traverse rover0 waypoint17 waypoint9)
	(can_traverse rover0 waypoint9 waypoint21)
	(can_traverse rover0 waypoint21 waypoint9)
	(can_traverse rover0 waypoint9 waypoint29)
	(can_traverse rover0 waypoint29 waypoint9)
	(can_traverse rover0 waypoint9 waypoint30)
	(can_traverse rover0 waypoint30 waypoint9)
	(can_traverse rover0 waypoint9 waypoint35)
	(can_traverse rover0 waypoint35 waypoint9)
	(can_traverse rover0 waypoint9 waypoint44)
	(can_traverse rover0 waypoint44 waypoint9)
	(can_traverse rover0 waypoint14 waypoint18)
	(can_traverse rover0 waypoint18 waypoint14)
	(can_traverse rover0 waypoint14 waypoint24)
	(can_traverse rover0 waypoint24 waypoint14)
	(can_traverse rover0 waypoint14 waypoint33)
	(can_traverse rover0 waypoint33 waypoint14)
	(can_traverse rover0 waypoint14 waypoint36)
	(can_traverse rover0 waypoint36 waypoint14)
	(can_traverse rover0 waypoint14 waypoint38)
	(can_traverse rover0 waypoint38 waypoint14)
	(can_traverse rover0 waypoint27 waypoint0)
	(can_traverse rover0 waypoint0 waypoint27)
	(can_traverse rover0 waypoint27 waypoint20)
	(can_traverse rover0 waypoint20 waypoint27)
	(can_traverse rover0 waypoint27 waypoint39)
	(can_traverse rover0 waypoint39 waypoint27)
	(can_traverse rover0 waypoint34 waypoint3)
	(can_traverse rover0 waypoint3 waypoint34)
	(can_traverse rover0 waypoint34 waypoint6)
	(can_traverse rover0 waypoint6 waypoint34)
	(can_traverse rover0 waypoint34 waypoint22)
	(can_traverse rover0 waypoint22 waypoint34)
	(can_traverse rover0 waypoint42 waypoint26)
	(can_traverse rover0 waypoint26 waypoint42)
	(can_traverse rover0 waypoint42 waypoint32)
	(can_traverse rover0 waypoint32 waypoint42)
	(can_traverse rover0 waypoint43 waypoint4)
	(can_traverse rover0 waypoint4 waypoint43)
	(can_traverse rover0 waypoint43 waypoint28)
	(can_traverse rover0 waypoint28 waypoint43)
	(can_traverse rover0 waypoint49 waypoint2)
	(can_traverse rover0 waypoint2 waypoint49)
	(can_traverse rover0 waypoint49 waypoint15)
	(can_traverse rover0 waypoint15 waypoint49)
	(can_traverse rover0 waypoint11 waypoint31)
	(can_traverse rover0 waypoint31 waypoint11)
	(can_traverse rover0 waypoint11 waypoint48)
	(can_traverse rover0 waypoint48 waypoint11)
	(can_traverse rover0 waypoint23 waypoint10)
	(can_traverse rover0 waypoint10 waypoint23)
	(can_traverse rover0 waypoint41 waypoint25)
	(can_traverse rover0 waypoint25 waypoint41)
	(can_traverse rover0 waypoint30 waypoint7)
	(can_traverse rover0 waypoint7 waypoint30)
	(can_traverse rover0 waypoint18 waypoint5)
	(can_traverse rover0 waypoint5 waypoint18)
	(can_traverse rover0 waypoint3 waypoint1)
	(can_traverse rover0 waypoint1 waypoint3)
	(at rover1 waypoint40)
	(available rover1)
	(store_of rover1store rover1)
	(empty rover1store)
	(equipped_for_imaging rover1)
	(can_traverse rover1 waypoint40 waypoint6)
	(can_traverse rover1 waypoint6 waypoint40)
	(can_traverse rover1 waypoint40 waypoint23)
	(can_traverse rover1 waypoint23 waypoint40)
	(can_traverse rover1 waypoint40 waypoint33)
	(can_traverse rover1 waypoint33 waypoint40)
	(can_traverse rover1 waypoint40 waypoint45)
	(can_traverse rover1 waypoint45 waypoint40)
	(can_traverse rover1 waypoint6 waypoint4)
	(can_traverse rover1 waypoint4 waypoint6)
	(can_traverse rover1 waypoint6 waypoint5)
	(can_traverse rover1 waypoint5 waypoint6)
	(can_traverse rover1 waypoint6 waypoint18)
	(can_traverse rover1 waypoint18 waypoint6)
	(can_traverse rover1 waypoint6 waypoint24)
	(can_traverse rover1 waypoint24 waypoint6)
	(can_traverse rover1 waypoint6 waypoint34)
	(can_traverse rover1 waypoint34 waypoint6)
	(can_traverse rover1 waypoint6 waypoint36)
	(can_traverse rover1 waypoint36 waypoint6)
	(can_traverse rover1 waypoint6 waypoint39)
	(can_traverse rover1 waypoint39 waypoint6)
	(can_traverse rover1 waypoint6 waypoint44)
	(can_traverse rover1 waypoint44 waypoint6)
	(can_traverse rover1 waypoint23 waypoint8)
	(can_traverse rover1 waypoint8 waypoint23)
	(can_traverse rover1 waypoint23 waypoint10)
	(can_traverse rover1 waypoint10 waypoint23)
	(can_traverse rover1 waypoint23 waypoint29)
	(can_traverse rover1 waypoint29 waypoint23)
	(can_traverse rover1 waypoint23 waypoint42)
	(can_traverse rover1 waypoint42 waypoint23)
	(can_traverse rover1 waypoint33 waypoint9)
	(can_traverse rover1 waypoint9 waypoint33)
	(can_traverse rover1 waypoint33 waypoint14)
	(can_traverse rover1 waypoint14 waypoint33)
	(can_traverse rover1 waypoint33 waypoint25)
	(can_traverse rover1 waypoint25 waypoint33)
	(can_traverse rover1 waypoint33 waypoint31)
	(can_traverse rover1 waypoint31 waypoint33)
	(can_traverse rover1 waypoint45 waypoint27)
	(can_traverse rover1 waypoint27 waypoint45)
	(can_traverse rover1 waypoint45 waypoint43)
	(can_traverse rover1 waypoint43 waypoint45)
	(can_traverse rover1 waypoint45 waypoint47)
	(can_traverse rover1 waypoint47 waypoint45)
	(can_traverse rover1 waypoint45 waypoint49)
	(can_traverse rover1 waypoint49 waypoint45)
	(can_traverse rover1 waypoint4 waypoint16)
	(can_traverse rover1 waypoint16 waypoint4)
	(can_traverse rover1 waypoint4 waypoint19)
	(can_traverse rover1 waypoint19 waypoint4)
	(can_traverse rover1 waypoint4 waypoint26)
	(can_traverse rover1 waypoint26 waypoint4)
	(can_traverse rover1 waypoint5 waypoint32)
	(can_traverse rover1 waypoint32 waypoint5)
	(can_traverse rover1 waypoint5 waypoint35)
	(can_traverse rover1 waypoint35 waypoint5)
	(can_traverse rover1 waypoint18 waypoint37)
	(can_traverse rover1 waypoint37 waypoint18)
	(can_traverse rover1 waypoint18 waypoint38)
	(can_traverse rover1 waypoint38 waypoint18)
	(can_traverse rover1 waypoint24 waypoint11)
	(can_traverse rover1 waypoint11 waypoint24)
	(can_traverse rover1 waypoint24 waypoint15)
	(can_traverse rover1 waypoint15 waypoint24)
	(can_traverse rover1 waypoint24 waypoint28)
	(can_traverse rover1 waypoint28 waypoint24)
	(can_traverse rover1 waypoint24 waypoint30)
	(can_traverse rover1 waypoint30 waypoint24)
	(can_traverse rover1 waypoint34 waypoint3)
	(can_traverse rover1 waypoint3 waypoint34)
	(can_traverse rover1 waypoint34 waypoint17)
	(can_traverse rover1 waypoint17 waypoint34)
	(can_traverse rover1 waypoint34 waypoint22)
	(can_traverse rover1 waypoint22 waypoint34)
	(can_traverse rover1 waypoint36 waypoint7)
	(can_traverse rover1 waypoint7 waypoint36)
	(can_traverse rover1 waypoint36 waypoint41)
	(can_traverse rover1 waypoint41 waypoint36)
	(can_traverse rover1 waypoint36 waypoint46)
	(can_traverse rover1 waypoint46 waypoint36)
	(can_traverse rover1 waypoint44 waypoint20)
	(can_traverse rover1 waypoint20 waypoint44)
	(can_traverse rover1 waypoint8 waypoint13)
	(can_traverse rover1 waypoint13 waypoint8)
	(can_traverse rover1 waypoint29 waypoint12)
	(can_traverse rover1 waypoint12 waypoint29)
	(can_traverse rover1 waypoint31 waypoint2)
	(can_traverse rover1 waypoint2 waypoint31)
	(can_traverse rover1 waypoint27 waypoint21)
	(can_traverse rover1 waypoint21 waypoint27)
	(can_traverse rover1 waypoint49 waypoint0)
	(can_traverse rover1 waypoint0 waypoint49)
	(can_traverse rover1 waypoint26 waypoint1)
	(can_traverse rover1 waypoint1 waypoint26)
	(can_traverse rover1 waypoint32 waypoint48)
	(can_traverse rover1 waypoint48 waypoint32)
	(at rover2 waypoint46)
	(available rover2)
	(store_of rover2store rover2)
	(empty rover2store)
	(equipped_for_imaging rover2)
	(can_traverse rover2 waypoint46 waypoint0)
	(can_traverse rover2 waypoint0 waypoint46)
	(can_traverse rover2 waypoint46 waypoint8)
	(can_traverse rover2 waypoint8 waypoint46)
	(can_traverse rover2 waypoint46 waypoint16)
	(can_traverse rover2 waypoint16 waypoint46)
	(can_traverse rover2 waypoint46 waypoint36)
	(can_traverse rover2 waypoint36 waypoint46)
	(can_traverse rover2 waypoint46 waypoint41)
	(can_traverse rover2 waypoint41 waypoint46)
	(can_traverse rover2 waypoint46 waypoint47)
	(can_traverse rover2 waypoint47 waypoint46)
	(can_traverse rover2 waypoint46 waypoint49)
	(can_traverse rover2 waypoint49 waypoint46)
	(can_traverse rover2 waypoint0 waypoint12)
	(can_traverse rover2 waypoint12 waypoint0)
	(can_traverse rover2 waypoint0 waypoint21)
	(can_traverse rover2 waypoint21 waypoint0)
	(can_traverse rover2 waypoint0 waypoint32)
	(can_traverse rover2 waypoint32 waypoint0)
	(can_traverse rover2 waypoint8 waypoint11)
	(can_traverse rover2 waypoint11 waypoint8)
	(can_traverse rover2 waypoint8 waypoint13)
	(can_traverse rover2 waypoint13 waypoint8)
	(can_traverse rover2 waypoint8 waypoint19)
	(can_traverse rover2 waypoint19 waypoint8)
	(can_traverse rover2 waypoint16 waypoint4)
	(can_traverse rover2 waypoint4 waypoint16)
	(can_traverse rover2 waypoint16 waypoint42)
	(can_traverse rover2 waypoint42 waypoint16)
	(can_traverse rover2 waypoint36 waypoint15)
	(can_traverse rover2 waypoint15 waypoint36)
	(can_traverse rover2 waypoint36 waypoint31)
	(can_traverse rover2 waypoint31 waypoint36)
	(can_traverse rover2 waypoint36 waypoint39)
	(can_traverse rover2 waypoint39 waypoint36)
	(can_traverse rover2 waypoint41 waypoint14)
	(can_traverse rover2 waypoint14 waypoint41)
	(can_traverse rover2 waypoint41 waypoint40)
	(can_traverse rover2 waypoint40 waypoint41)
	(can_traverse rover2 waypoint41 waypoint43)
	(can_traverse rover2 waypoint43 waypoint41)
	(can_traverse rover2 waypoint47 waypoint3)
	(can_traverse rover2 waypoint3 waypoint47)
	(can_traverse rover2 waypoint47 waypoint45)
	(can_traverse rover2 waypoint45 waypoint47)
	(can_traverse rover2 waypoint49 waypoint2)
	(can_traverse rover2 waypoint2 waypoint49)
	(can_traverse rover2 waypoint12 waypoint29)
	(can_traverse rover2 waypoint29 waypoint12)
	(can_traverse rover2 waypoint12 waypoint30)
	(can_traverse rover2 waypoint30 waypoint12)
	(can_traverse rover2 waypoint12 waypoint38)
	(can_traverse rover2 waypoint38 waypoint12)
	(can_traverse rover2 waypoint21 waypoint9)
	(can_traverse rover2 waypoint9 waypoint21)
	(can_traverse rover2 waypoint21 waypoint27)
	(can_traverse rover2 waypoint27 waypoint21)
	(can_traverse rover2 waypoint32 waypoint5)
	(can_traverse rover2 waypoint5 waypoint32)
	(can_traverse rover2 waypoint11 waypoint22)
	(can_traverse rover2 waypoint22 waypoint11)
	(can_traverse rover2 waypoint11 waypoint24)
	(can_traverse rover2 waypoint24 waypoint11)
	(can_traverse rover2 waypoint11 waypoint44)
	(can_traverse rover2 waypoint44 waypoint11)
	(can_traverse rover2 waypoint11 waypoint48)
	(can_traverse rover2 waypoint48 waypoint11)
	(can_traverse rover2 waypoint13 waypoint26)
	(can_traverse rover2 waypoint26 waypoint13)
	(can_traverse rover2 waypoint19 waypoint34)
	(can_traverse rover2 waypoint34 waypoint19)
	(can_traverse rover2 waypoint42 waypoint23)
	(can_traverse rover2 waypoint23 waypoint42)
	(can_traverse rover2 waypoint15 waypoint35)
	(can_traverse rover2 waypoint35 waypoint15)
	(can_traverse rover2 waypoint31 waypoint17)
	(can_traverse rover2 waypoint17 waypoint31)
	(can_traverse rover2 waypoint31 waypoint33)
	(can_traverse rover2 waypoint33 waypoint31)
	(can_traverse rover2 waypoint31 waypoint37)
	(can_traverse rover2 waypoint37 waypoint31)
	(can_traverse rover2 waypoint39 waypoint6)
	(can_traverse rover2 waypoint6 waypoint39)
	(can_traverse rover2 waypoint14 waypoint18)
	(can_traverse rover2 waypoint18 waypoint14)
	(can_traverse rover2 waypoint43 waypoint28)
	(can_traverse rover2 waypoint28 waypoint43)
	(can_traverse rover2 waypoint3 waypoint7)
	(can_traverse rover2 waypoint7 waypoint3)
	(can_traverse rover2 waypoint26 waypoint1)
	(can_traverse rover2 waypoint1 waypoint26)
	(can_traverse rover2 waypoint23 waypoint10)
	(can_traverse rover2 waypoint10 waypoint23)
	(at rover3 waypoint47)
	(available rover3)
	(store_of rover3store rover3)
	(empty rover3store)
	(equipped_for_soil_analysis rover3)
	(equipped_for_imaging rover3)
	(can_traverse rover3 waypoint47 waypoint3)
	(can_traverse rover3 waypoint3 waypoint47)
	(can_traverse rover3 waypoint47 waypoint22)
	(can_traverse rover3 waypoint22 waypoint47)
	(can_traverse rover3 waypoint47 waypoint45)
	(can_traverse rover3 waypoint45 waypoint47)
	(can_traverse rover3 waypoint47 waypoint46)
	(can_traverse rover3 waypoint46 waypoint47)
	(can_traverse rover3 waypoint3 waypoint1)
	(can_traverse rover3 waypoint1 waypoint3)
	(can_traverse rover3 waypoint3 waypoint4)
	(can_traverse rover3 waypoint4 waypoint3)
	(can_traverse rover3 waypoint3 waypoint7)
	(can_traverse rover3 waypoint7 waypoint3)
	(can_traverse rover3 waypoint3 waypoint10)
	(can_traverse rover3 waypoint10 waypoint3)
	(can_traverse rover3 waypoint3 waypoint26)
	(can_traverse rover3 waypoint26 waypoint3)
	(can_traverse rover3 waypoint3 waypoint43)
	(can_traverse rover3 waypoint43 waypoint3)
	(can_traverse rover3 waypoint3 waypoint44)
	(can_traverse rover3 waypoint44 waypoint3)
	(can_traverse rover3 waypoint22 waypoint11)
	(can_traverse rover3 waypoint11 waypoint22)
	(can_traverse rover3 waypoint22 waypoint28)
	(can_traverse rover3 waypoint28 waypoint22)
	(can_traverse rover3 waypoint22 waypoint39)
	(can_traverse rover3 waypoint39 waypoint22)
	(can_traverse rover3 waypoint45 waypoint8)
	(can_traverse rover3 waypoint8 waypoint45)
	(can_traverse rover3 waypoint45 waypoint9)
	(can_traverse rover3 waypoint9 waypoint45)
	(can_traverse rover3 waypoint45 waypoint14)
	(can_traverse rover3 waypoint14 waypoint45)
	(can_traverse rover3 waypoint45 waypoint27)
	(can_traverse rover3 waypoint27 waypoint45)
	(can_traverse rover3 waypoint45 waypoint31)
	(can_traverse rover3 waypoint31 waypoint45)
	(can_traverse rover3 waypoint45 waypoint40)
	(can_traverse rover3 waypoint40 waypoint45)
	(can_traverse rover3 waypoint45 waypoint42)
	(can_traverse rover3 waypoint42 waypoint45)
	(can_traverse rover3 waypoint46 waypoint0)
	(can_traverse rover3 waypoint0 waypoint46)
	(can_traverse rover3 waypoint46 waypoint21)
	(can_traverse rover3 waypoint21 waypoint46)
	(can_traverse rover3 waypoint46 waypoint36)
	(can_traverse rover3 waypoint36 waypoint46)
	(can_traverse rover3 waypoint46 waypoint41)
	(can_traverse rover3 waypoint41 waypoint46)
	(can_traverse rover3 waypoint46 waypoint49)
	(can_traverse rover3 waypoint49 waypoint46)
	(can_traverse rover3 waypoint1 waypoint32)
	(can_traverse rover3 waypoint32 waypoint1)
	(can_traverse rover3 waypoint1 waypoint37)
	(can_traverse rover3 waypoint37 waypoint1)
	(can_traverse rover3 waypoint4 waypoint6)
	(can_traverse rover3 waypoint6 waypoint4)
	(can_traverse rover3 waypoint4 waypoint16)
	(can_traverse rover3 waypoint16 waypoint4)
	(can_traverse rover3 waypoint7 waypoint20)
	(can_traverse rover3 waypoint20 waypoint7)
	(can_traverse rover3 waypoint7 waypoint24)
	(can_traverse rover3 waypoint24 waypoint7)
	(can_traverse rover3 waypoint7 waypoint25)
	(can_traverse rover3 waypoint25 waypoint7)
	(can_traverse rover3 waypoint7 waypoint30)
	(can_traverse rover3 waypoint30 waypoint7)
	(can_traverse rover3 waypoint10 waypoint23)
	(can_traverse rover3 waypoint23 waypoint10)
	(can_traverse rover3 waypoint26 waypoint2)
	(can_traverse rover3 waypoint2 waypoint26)
	(can_traverse rover3 waypoint26 waypoint13)
	(can_traverse rover3 waypoint13 waypoint26)
	(can_traverse rover3 waypoint26 waypoint38)
	(can_traverse rover3 waypoint38 waypoint26)
	(can_traverse rover3 waypoint43 waypoint17)
	(can_traverse rover3 waypoint17 waypoint43)
	(can_traverse rover3 waypoint11 waypoint19)
	(can_traverse rover3 waypoint19 waypoint11)
	(can_traverse rover3 waypoint28 waypoint29)
	(can_traverse rover3 waypoint29 waypoint28)
	(can_traverse rover3 waypoint28 waypoint35)
	(can_traverse rover3 waypoint35 waypoint28)
	(can_traverse rover3 waypoint39 waypoint15)
	(can_traverse rover3 waypoint15 waypoint39)
	(can_traverse rover3 waypoint8 waypoint12)
	(can_traverse rover3 waypoint12 waypoint8)
	(can_traverse rover3 waypoint9 waypoint34)
	(can_traverse rover3 waypoint34 waypoint9)
	(can_traverse rover3 waypoint14 waypoint5)
	(can_traverse rover3 waypoint5 waypoint14)
	(can_traverse rover3 waypoint40 waypoint33)
	(can_traverse rover3 waypoint33 waypoint40)
	(can_traverse rover3 waypoint32 waypoint48)
	(can_traverse rover3 waypoint48 waypoint32)
	(can_traverse rover3 waypoint6 waypoint18)
	(can_traverse rover3 waypoint18 waypoint6)
	(on_board camera0 rover0)
	(calibration_target camera0 objective6)
	(supports camera0 low_res)
	(on_board camera1 rover3)
	(calibration_target camera1 objective6)
	(supports camera1 colour)
	(supports camera1 high_res)
	(supports camera1 low_res)
	(on_board camera2 rover2)
	(calibration_target camera2 objective4)
	(supports camera2 high_res)
	(on_board camera3 rover0)
	(calibration_target camera3 objective7)
	(supports camera3 high_res)
	(on_board camera4 rover0)
	(calibration_target camera4 objective7)
	(supports camera4 high_res)
	(supports camera4 low_res)
	(on_board camera5 rover3)
	(calibration_target camera5 objective1)
	(supports camera5 colour)
	(supports camera5 high_res)
	(supports camera5 low_res)
	(on_board camera6 rover1)
	(calibration_target camera6 objective5)
	(supports camera6 high_res)
	(supports camera6 low_res)
	(visible_from objective0 waypoint4)
	(visible_from objective0 waypoint17)
	(visible_from objective0 waypoint21)
	(visible_from objective0 waypoint22)
	(visible_from objective0 waypoint34)
	(visible_from objective0 waypoint38)
	(visible_from objective0 waypoint42)
	(visible_from objective0 waypoint46)
	(visible_from objective0 waypoint49)
	(visible_from objective1 waypoint0)
	(visible_from objective1 waypoint1)
	(visible_from objective1 waypoint4)
	(visible_from objective1 waypoint5)
	(visible_from objective1 waypoint6)
	(visible_from objective1 waypoint8)
	(visible_from objective1 waypoint10)
	(visible_from objective1 waypoint15)
	(visible_from objective1 waypoint16)
	(visible_from objective1 waypoint18)
	(visible_from objective1 waypoint19)
	(visible_from objective1 waypoint21)
	(visible_from objective1 waypoint22)
	(visible_from objective1 waypoint23)
	(visible_from objective1 waypoint25)
	(visible_from objective1 waypoint26)
	(visible_from objective1 waypoint29)
	(visible_from objective1 waypoint30)
	(visible_from objective1 waypoint32)
	(visible_from objective1 waypoint33)
	(visible_from objective1 waypoint34)
	(visible_from objective1 waypoint38)
	(visible_from objective1 waypoint39)
	(visible_from objective1 waypoint44)
	(visible_from objective1 waypoint47)
	(visible_from objective2 waypoint1)
	(visible_from objective2 waypoint2)
	(visible_from objective2 waypoint3)
	(visible_from objective2 waypoint4)
	(visible_from objective2 waypoint5)
	(visible_from objective2 waypoint6)
	(visible_from objective2 waypoint7)
	(visible_from objective2 waypoint8)
	(visible_from objective2 waypoint9)
	(visible_from objective2 waypoint11)
	(visible_from objective2 waypoint15)
	(visible_from objective2 waypoint18)
	(visible_from objective2 waypoint19)
	(visible_from objective2 waypoint20)
	(visible_from objective2 waypoint25)
	(visible_from objective2 waypoint26)
	(visible_from objective2 waypoint28)
	(visible_from objective2 waypoint29)
	(visible_from objective2 waypoint31)
	(visible_from objective2 waypoint33)
	(visible_from objective2 waypoint35)
	(visible_from objective2 waypoint36)
	(visible_from objective2 waypoint37)
	(visible_from objective2 waypoint38)
	(visible_from objective2 waypoint39)
	(visible_from objective2 waypoint40)
	(visible_from objective2 waypoint41)
	(visible_from objective2 waypoint42)
	(visible_from objective2 waypoint43)
	(visible_from objective2 waypoint46)
	(visible_from objective3 waypoint5)
	(visible_from objective3 waypoint9)
	(visible_from objective3 waypoint13)
	(visible_from objective3 waypoint14)
	(visible_from objective3 waypoint23)
	(visible_from objective3 waypoint44)
	(visible_from objective4 waypoint1)
	(visible_from objective4 waypoint3)
	(visible_from objective4 waypoint5)
	(visible_from objective4 waypoint7)
	(visible_from objective4 waypoint8)
	(visible_from objective4 waypoint11)
	(visible_from objective4 waypoint14)
	(visible_from objective4 waypoint16)
	(visible_from objective4 waypoint17)
	(visible_from objective4 waypoint18)
	(visible_from objective4 waypoint22)
	(visible_from objective4 waypoint25)
	(visible_from objective4 waypoint28)
	(visible_from objective4 waypoint29)
	(visible_from objective4 waypoint30)
	(visible_from objective4 waypoint31)
	(visible_from objective4 waypoint32)
	(visible_from objective4 waypoint33)
	(visible_from objective4 waypoint38)
	(visible_from objective4 waypoint40)
	(visible_from objective4 waypoint41)
	(visible_from objective4 waypoint43)
	(visible_from objective4 waypoint44)
	(visible_from objective4 waypoint46)
	(visible_from objective4 waypoint47)
	(visible_from objective5 waypoint0)
	(visible_from objective5 waypoint3)
	(visible_from objective5 waypoint5)
	(visible_from objective5 waypoint6)
	(visible_from objective5 waypoint9)
	(visible_from objective5 waypoint11)
	(visible_from objective5 waypoint12)
	(visible_from objective5 waypoint13)
	(visible_from objective5 waypoint14)
	(visible_from objective5 waypoint15)
	(visible_from objective5 waypoint18)
	(visible_from objective5 waypoint19)
	(visible_from objective5 waypoint21)
	(visible_from objective5 waypoint23)
	(visible_from objective5 waypoint24)
	(visible_from objective5 waypoint28)
	(visible_from objective5 waypoint29)
	(visible_from objective5 waypoint33)
	(visible_from objective5 waypoint37)
	(visible_from objective5 waypoint40)
	(visible_from objective5 waypoint42)
	(visible_from objective5 waypoint44)
	(visible_from objective5 waypoint45)
	(visible_from objective6 waypoint2)
	(visible_from objective6 waypoint5)
	(visible_from objective6 waypoint8)
	(visible_from objective6 waypoint10)
	(visible_from objective6 waypoint23)
	(visible_from objective6 waypoint26)
	(visible_from objective6 waypoint32)
	(visible_from objective6 waypoint33)
	(visible_from objective6 waypoint34)
	(visible_from objective6 waypoint38)
	(visible_from objective6 waypoint40)
	(visible_from objective6 waypoint41)
	(visible_from objective6 waypoint43)
	(visible_from objective6 waypoint47)
	(visible_from objective6 waypoint49)
	(visible_from objective7 waypoint0)
	(visible_from objective7 waypoint2)
	(visible_from objective7 waypoint4)
	(visible_from objective7 waypoint5)
	(visible_from objective7 waypoint7)
	(visible_from objective7 waypoint9)
	(visible_from objective7 waypoint10)
	(visible_from objective7 waypoint11)
	(visible_from objective7 waypoint13)
	(visible_from objective7 waypoint14)
	(visible_from objective7 waypoint16)
	(visible_from objective7 waypoint17)
	(visible_from objective7 waypoint19)
	(visible_from objective7 waypoint20)
	(visible_from objective7 waypoint21)
	(visible_from objective7 waypoint22)
	(visible_from objective7 waypoint23)
	(visible_from objective7 waypoint25)
	(visible_from objective7 waypoint26)
	(visible_from objective7 waypoint27)
	(visible_from objective7 waypoint30)
	(visible_from objective7 waypoint32)
	(visible_from objective7 waypoint33)
	(visible_from objective7 waypoint34)
	(visible_from objective7 waypoint35)
	(visible_from objective7 waypoint39)
	(visible_from objective7 waypoint40)
	(visible_from objective7 waypoint41)
	(visible_from objective7 waypoint42)
	(visible_from objective7 waypoint43)
	(visible_from objective7 waypoint48)
	(visible_from objective7 waypoint49)
)

(:goal (and
(communicated_soil_data waypoint47)
(communicated_soil_data waypoint44)
(communicated_soil_data waypoint39)
(communicated_soil_data waypoint15)
(communicated_soil_data waypoint27)
(communicated_soil_data waypoint24)
(communicated_soil_data waypoint34)
(communicated_soil_data waypoint46)
(communicated_soil_data waypoint35)
(communicated_soil_data waypoint8)
(communicated_soil_data waypoint1)
(communicated_soil_data waypoint17)
(communicated_soil_data waypoint49)
(communicated_soil_data waypoint40)
(communicated_soil_data waypoint36)
(communicated_image_data objective4 high_res)
(communicated_image_data objective1 high_res)
(communicated_image_data objective6 high_res)
(communicated_image_data objective1 low_res)
(communicated_image_data objective5 low_res)
(communicated_image_data objective5 high_res)
	)
)
)
