(define (problem roverprob8) (:domain Rover)
(:objects
	general - Lander
	colour high_res low_res - Mode
	rover0 rover1 rover2 rover3 - Rover
	rover0store rover1store rover2store rover3store - Store
	waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 waypoint7 waypoint8 waypoint9 waypoint10 waypoint11 waypoint12 waypoint13 waypoint14 waypoint15 waypoint16 waypoint17 waypoint18 waypoint19 waypoint20 waypoint21 waypoint22 waypoint23 waypoint24 waypoint25 waypoint26 waypoint27 waypoint28 waypoint29 waypoint30 waypoint31 waypoint32 waypoint33 waypoint34 waypoint35 waypoint36 waypoint37 waypoint38 waypoint39 waypoint40 waypoint41 waypoint42 waypoint43 waypoint44 waypoint45 waypoint46 waypoint47 waypoint48 waypoint49 - Waypoint
	camera0 camera1 camera2 camera3 camera4 camera5 - Camera
	objective0 objective1 objective2 objective3 objective4 objective5 objective6 objective7 - Objective
	)
(:init
	(visible waypoint0 waypoint4)
	(visible waypoint4 waypoint0)
	(visible waypoint0 waypoint6)
	(visible waypoint6 waypoint0)
	(visible waypoint0 waypoint17)
	(visible waypoint17 waypoint0)
	(visible waypoint0 waypoint18)
	(visible waypoint18 waypoint0)
	(visible waypoint0 waypoint21)
	(visible waypoint21 waypoint0)
	(visible waypoint0 waypoint30)
	(visible waypoint30 waypoint0)
	(visible waypoint0 waypoint37)
	(visible waypoint37 waypoint0)
	(visible waypoint0 waypoint41)
	(visible waypoint41 waypoint0)
	(visible waypoint0 waypoint47)
	(visible waypoint47 waypoint0)
	(visible waypoint1 waypoint5)
	(visible waypoint5 waypoint1)
	(visible waypoint1 waypoint13)
	(visible waypoint13 waypoint1)
	(visible waypoint1 waypoint27)
	(visible waypoint27 waypoint1)
	(visible waypoint1 waypoint30)
	(visible waypoint30 waypoint1)
	(visible waypoint1 waypoint38)
	(visible waypoint38 waypoint1)
	(visible waypoint2 waypoint29)
	(visible waypoint29 waypoint2)
	(visible waypoint3 waypoint9)
	(visible waypoint9 waypoint3)
	(visible waypoint3 waypoint24)
	(visible waypoint24 waypoint3)
	(visible waypoint3 waypoint40)
	(visible waypoint40 waypoint3)
	(visible waypoint3 waypoint42)
	(visible waypoint42 waypoint3)
	(visible waypoint4 waypoint3)
	(visible waypoint3 waypoint4)
	(visible waypoint4 waypoint20)
	(visible waypoint20 waypoint4)
	(visible waypoint5 waypoint3)
	(visible waypoint3 waypoint5)
	(visible waypoint5 waypoint10)
	(visible waypoint10 waypoint5)
	(visible waypoint5 waypoint12)
	(visible waypoint12 waypoint5)
	(visible waypoint5 waypoint14)
	(visible waypoint14 waypoint5)
	(visible waypoint5 waypoint33)
	(visible waypoint33 waypoint5)
	(visible waypoint5 waypoint36)
	(visible waypoint36 waypoint5)
	(visible waypoint5 waypoint41)
	(visible waypoint41 waypoint5)
	(visible waypoint6 waypoint3)
	(visible waypoint3 waypoint6)
	(visible waypoint6 waypoint11)
	(visible waypoint11 waypoint6)
	(visible waypoint6 waypoint29)
	(visible waypoint29 waypoint6)
	(visible waypoint6 waypoint33)
	(visible waypoint33 waypoint6)
	(visible waypoint6 waypoint37)
	(visible waypoint37 waypoint6)
	(visible waypoint6 waypoint44)
	(visible waypoint44 waypoint6)
	(visible waypoint6 waypoint45)
	(visible waypoint45 waypoint6)
	(visible waypoint7 waypoint5)
	(visible waypoint5 waypoint7)
	(visible waypoint7 waypoint12)
	(visible waypoint12 waypoint7)
	(visible waypoint7 waypoint39)
	(visible waypoint39 waypoint7)
	(visible waypoint7 waypoint45)
	(visible waypoint45 waypoint7)
	(visible waypoint8 waypoint28)
	(visible waypoint28 waypoint8)
	(visible waypoint8 waypoint46)
	(visible waypoint46 waypoint8)
	(visible waypoint9 waypoint10)
	(visible waypoint10 waypoint9)
	(visible waypoint9 waypoint33)
	(visible waypoint33 waypoint9)
	(visible waypoint9 waypoint38)
	(visible waypoint38 waypoint9)
	(visible waypoint9 waypoint46)
	(visible waypoint46 waypoint9)
	(visible waypoint9 waypoint49)
	(visible waypoint49 waypoint9)
	(visible waypoint10 waypoint8)
	(visible waypoint8 waypoint10)
	(visible waypoint10 waypoint12)
	(visible waypoint12 waypoint10)
	(visible waypoint10 waypoint20)
	(visible waypoint20 waypoint10)
	(visible waypoint10 waypoint21)
	(visible waypoint21 waypoint10)
	(visible waypoint10 waypoint22)
	(visible waypoint22 waypoint10)
	(visible waypoint10 waypoint26)
	(visible waypoint26 waypoint10)
	(visible waypoint10 waypoint35)
	(visible waypoint35 waypoint10)
	(visible waypoint11 waypoint1)
	(visible waypoint1 waypoint11)
	(visible waypoint11 waypoint7)
	(visible waypoint7 waypoint11)
	(visible waypoint11 waypoint8)
	(visible waypoint8 waypoint11)
	(visible waypoint11 waypoint14)
	(visible waypoint14 waypoint11)
	(visible waypoint11 waypoint35)
	(visible waypoint35 waypoint11)
	(visible waypoint11 waypoint49)
	(visible waypoint49 waypoint11)
	(visible waypoint12 waypoint42)
	(visible waypoint42 waypoint12)
	(visible waypoint13 waypoint9)
	(visible waypoint9 waypoint13)
	(visible waypoint13 waypoint17)
	(visible waypoint17 waypoint13)
	(visible waypoint13 waypoint22)
	(visible waypoint22 waypoint13)
	(visible waypoint13 waypoint28)
	(visible waypoint28 waypoint13)
	(visible waypoint13 waypoint33)
	(visible waypoint33 waypoint13)
	(visible waypoint13 waypoint35)
	(visible waypoint35 waypoint13)
	(visible waypoint14 waypoint13)
	(visible waypoint13 waypoint14)
	(visible waypoint14 waypoint17)
	(visible waypoint17 waypoint14)
	(visible waypoint14 waypoint20)
	(visible waypoint20 waypoint14)
	(visible waypoint14 waypoint31)
	(visible waypoint31 waypoint14)
	(visible waypoint14 waypoint44)
	(visible waypoint44 waypoint14)
	(visible waypoint15 waypoint8)
	(visible waypoint8 waypoint15)
	(visible waypoint15 waypoint18)
	(visible waypoint18 waypoint15)
	(visible waypoint15 waypoint23)
	(visible waypoint23 waypoint15)
	(visible waypoint15 waypoint34)
	(visible waypoint34 waypoint15)
	(visible waypoint15 waypoint42)
	(visible waypoint42 waypoint15)
	(visible waypoint16 waypoint21)
	(visible waypoint21 waypoint16)
	(visible waypoint16 waypoint23)
	(visible waypoint23 waypoint16)
	(visible waypoint16 waypoint26)
	(visible waypoint26 waypoint16)
	(visible waypoint16 waypoint29)
	(visible waypoint29 waypoint16)
	(visible waypoint16 waypoint40)
	(visible waypoint40 waypoint16)
	(visible waypoint17 waypoint3)
	(visible waypoint3 waypoint17)
	(visible waypoint17 waypoint5)
	(visible waypoint5 waypoint17)
	(visible waypoint17 waypoint37)
	(visible waypoint37 waypoint17)
	(visible waypoint17 waypoint39)
	(visible waypoint39 waypoint17)
	(visible waypoint17 waypoint40)
	(visible waypoint40 waypoint17)
	(visible waypoint17 waypoint41)
	(visible waypoint41 waypoint17)
	(visible waypoint18 waypoint12)
	(visible waypoint12 waypoint18)
	(visible waypoint18 waypoint26)
	(visible waypoint26 waypoint18)
	(visible waypoint18 waypoint41)
	(visible waypoint41 waypoint18)
	(visible waypoint18 waypoint49)
	(visible waypoint49 waypoint18)
	(visible waypoint19 waypoint31)
	(visible waypoint31 waypoint19)
	(visible waypoint20 waypoint8)
	(visible waypoint8 waypoint20)
	(visible waypoint20 waypoint18)
	(visible waypoint18 waypoint20)
	(visible waypoint20 waypoint22)
	(visible waypoint22 waypoint20)
	(visible waypoint20 waypoint45)
	(visible waypoint45 waypoint20)
	(visible waypoint21 waypoint3)
	(visible waypoint3 waypoint21)
	(visible waypoint21 waypoint23)
	(visible waypoint23 waypoint21)
	(visible waypoint21 waypoint25)
	(visible waypoint25 waypoint21)
	(visible waypoint21 waypoint35)
	(visible waypoint35 waypoint21)
	(visible waypoint21 waypoint36)
	(visible waypoint36 waypoint21)
	(visible waypoint21 waypoint44)
	(visible waypoint44 waypoint21)
	(visible waypoint22 waypoint4)
	(visible waypoint4 waypoint22)
	(visible waypoint23 waypoint3)
	(visible waypoint3 waypoint23)
	(visible waypoint23 waypoint30)
	(visible waypoint30 waypoint23)
	(visible waypoint23 waypoint41)
	(visible waypoint41 waypoint23)
	(visible waypoint23 waypoint46)
	(visible waypoint46 waypoint23)
	(visible waypoint24 waypoint0)
	(visible waypoint0 waypoint24)
	(visible waypoint24 waypoint5)
	(visible waypoint5 waypoint24)
	(visible waypoint24 waypoint14)
	(visible waypoint14 waypoint24)
	(visible waypoint24 waypoint22)
	(visible waypoint22 waypoint24)
	(visible waypoint25 waypoint5)
	(visible waypoint5 waypoint25)
	(visible waypoint25 waypoint16)
	(visible waypoint16 waypoint25)
	(visible waypoint25 waypoint17)
	(visible waypoint17 waypoint25)
	(visible waypoint25 waypoint39)
	(visible waypoint39 waypoint25)
	(visible waypoint25 waypoint46)
	(visible waypoint46 waypoint25)
	(visible waypoint26 waypoint28)
	(visible waypoint28 waypoint26)
	(visible waypoint26 waypoint32)
	(visible waypoint32 waypoint26)
	(visible waypoint26 waypoint44)
	(visible waypoint44 waypoint26)
	(visible waypoint27 waypoint7)
	(visible waypoint7 waypoint27)
	(visible waypoint27 waypoint13)
	(visible waypoint13 waypoint27)
	(visible waypoint27 waypoint21)
	(visible waypoint21 waypoint27)
	(visible waypoint27 waypoint24)
	(visible waypoint24 waypoint27)
	(visible waypoint27 waypoint34)
	(visible waypoint34 waypoint27)
	(visible waypoint27 waypoint43)
	(visible waypoint43 waypoint27)
	(visible waypoint28 waypoint23)
	(visible waypoint23 waypoint28)
	(visible waypoint28 waypoint33)
	(visible waypoint33 waypoint28)
	(visible waypoint28 waypoint37)
	(visible waypoint37 waypoint28)
	(visible waypoint28 waypoint43)
	(visible waypoint43 waypoint28)
	(visible waypoint29 waypoint25)
	(visible waypoint25 waypoint29)
	(visible waypoint29 waypoint44)
	(visible waypoint44 waypoint29)
	(visible waypoint29 waypoint45)
	(visible waypoint45 waypoint29)
	(visible waypoint30 waypoint16)
	(visible waypoint16 waypoint30)
	(visible waypoint30 waypoint18)
	(visible waypoint18 waypoint30)
	(visible waypoint30 waypoint27)
	(visible waypoint27 waypoint30)
	(visible waypoint30 waypoint49)
	(visible waypoint49 waypoint30)
	(visible waypoint31 waypoint15)
	(visible waypoint15 waypoint31)
	(visible waypoint31 waypoint30)
	(visible waypoint30 waypoint31)
	(visible waypoint31 waypoint40)
	(visible waypoint40 waypoint31)
	(visible waypoint31 waypoint42)
	(visible waypoint42 waypoint31)
	(visible waypoint32 waypoint6)
	(visible waypoint6 waypoint32)
	(visible waypoint32 waypoint16)
	(visible waypoint16 waypoint32)
	(visible waypoint32 waypoint19)
	(visible waypoint19 waypoint32)
	(visible waypoint32 waypoint29)
	(visible waypoint29 waypoint32)
	(visible waypoint32 waypoint38)
	(visible waypoint38 waypoint32)
	(visible waypoint32 waypoint39)
	(visible waypoint39 waypoint32)
	(visible waypoint33 waypoint14)
	(visible waypoint14 waypoint33)
	(visible waypoint33 waypoint15)
	(visible waypoint15 waypoint33)
	(visible waypoint33 waypoint19)
	(visible waypoint19 waypoint33)
	(visible waypoint33 waypoint20)
	(visible waypoint20 waypoint33)
	(visible waypoint33 waypoint21)
	(visible waypoint21 waypoint33)
	(visible waypoint33 waypoint22)
	(visible waypoint22 waypoint33)
	(visible waypoint33 waypoint45)
	(visible waypoint45 waypoint33)
	(visible waypoint34 waypoint4)
	(visible waypoint4 waypoint34)
	(visible waypoint34 waypoint9)
	(visible waypoint9 waypoint34)
	(visible waypoint34 waypoint19)
	(visible waypoint19 waypoint34)
	(visible waypoint34 waypoint24)
	(visible waypoint24 waypoint34)
	(visible waypoint34 waypoint42)
	(visible waypoint42 waypoint34)
	(visible waypoint34 waypoint43)
	(visible waypoint43 waypoint34)
	(visible waypoint34 waypoint44)
	(visible waypoint44 waypoint34)
	(visible waypoint35 waypoint3)
	(visible waypoint3 waypoint35)
	(visible waypoint35 waypoint5)
	(visible waypoint5 waypoint35)
	(visible waypoint36 waypoint9)
	(visible waypoint9 waypoint36)
	(visible waypoint36 waypoint18)
	(visible waypoint18 waypoint36)
	(visible waypoint36 waypoint27)
	(visible waypoint27 waypoint36)
	(visible waypoint36 waypoint37)
	(visible waypoint37 waypoint36)
	(visible waypoint36 waypoint39)
	(visible waypoint39 waypoint36)
	(visible waypoint37 waypoint21)
	(visible waypoint21 waypoint37)
	(visible waypoint37 waypoint38)
	(visible waypoint38 waypoint37)
	(visible waypoint38 waypoint8)
	(visible waypoint8 waypoint38)
	(visible waypoint38 waypoint20)
	(visible waypoint20 waypoint38)
	(visible waypoint38 waypoint33)
	(visible waypoint33 waypoint38)
	(visible waypoint38 waypoint34)
	(visible waypoint34 waypoint38)
	(visible waypoint39 waypoint28)
	(visible waypoint28 waypoint39)
	(visible waypoint39 waypoint29)
	(visible waypoint29 waypoint39)
	(visible waypoint40 waypoint12)
	(visible waypoint12 waypoint40)
	(visible waypoint40 waypoint15)
	(visible waypoint15 waypoint40)
	(visible waypoint40 waypoint24)
	(visible waypoint24 waypoint40)
	(visible waypoint41 waypoint2)
	(visible waypoint2 waypoint41)
	(visible waypoint41 waypoint4)
	(visible waypoint4 waypoint41)
	(visible waypoint41 waypoint12)
	(visible waypoint12 waypoint41)
	(visible waypoint41 waypoint13)
	(visible waypoint13 waypoint41)
	(visible waypoint41 waypoint15)
	(visible waypoint15 waypoint41)
	(visible waypoint42 waypoint14)
	(visible waypoint14 waypoint42)
	(visible waypoint42 waypoint25)
	(visible waypoint25 waypoint42)
	(visible waypoint42 waypoint33)
	(visible waypoint33 waypoint42)
	(visible waypoint42 waypoint38)
	(visible waypoint38 waypoint42)
	(visible waypoint43 waypoint14)
	(visible waypoint14 waypoint43)
	(visible waypoint43 waypoint41)
	(visible waypoint41 waypoint43)
	(visible waypoint43 waypoint44)
	(visible waypoint44 waypoint43)
	(visible waypoint43 waypoint49)
	(visible waypoint49 waypoint43)
	(visible waypoint44 waypoint12)
	(visible waypoint12 waypoint44)
	(visible waypoint44 waypoint20)
	(visible waypoint20 waypoint44)
	(visible waypoint44 waypoint33)
	(visible waypoint33 waypoint44)
	(visible waypoint44 waypoint35)
	(visible waypoint35 waypoint44)
	(visible waypoint45 waypoint2)
	(visible waypoint2 waypoint45)
	(visible waypoint45 waypoint5)
	(visible waypoint5 waypoint45)
	(visible waypoint45 waypoint27)
	(visible waypoint27 waypoint45)
	(visible waypoint45 waypoint28)
	(visible waypoint28 waypoint45)
	(visible waypoint45 waypoint32)
	(visible waypoint32 waypoint45)
	(visible waypoint45 waypoint40)
	(visible waypoint40 waypoint45)
	(visible waypoint46 waypoint7)
	(visible waypoint7 waypoint46)
	(visible waypoint46 waypoint14)
	(visible waypoint14 waypoint46)
	(visible waypoint46 waypoint21)
	(visible waypoint21 waypoint46)
	(visible waypoint46 waypoint32)
	(visible waypoint32 waypoint46)
	(visible waypoint46 waypoint42)
	(visible waypoint42 waypoint46)
	(visible waypoint47 waypoint1)
	(visible waypoint1 waypoint47)
	(visible waypoint47 waypoint12)
	(visible waypoint12 waypoint47)
	(visible waypoint47 waypoint13)
	(visible waypoint13 waypoint47)
	(visible waypoint47 waypoint22)
	(visible waypoint22 waypoint47)
	(visible waypoint47 waypoint32)
	(visible waypoint32 waypoint47)
	(visible waypoint47 waypoint42)
	(visible waypoint42 waypoint47)
	(visible waypoint47 waypoint46)
	(visible waypoint46 waypoint47)
	(visible waypoint47 waypoint48)
	(visible waypoint48 waypoint47)
	(visible waypoint48 waypoint11)
	(visible waypoint11 waypoint48)
	(visible waypoint48 waypoint23)
	(visible waypoint23 waypoint48)
	(visible waypoint48 waypoint33)
	(visible waypoint33 waypoint48)
	(visible waypoint48 waypoint36)
	(visible waypoint36 waypoint48)
	(visible waypoint49 waypoint6)
	(visible waypoint6 waypoint49)
	(visible waypoint49 waypoint41)
	(visible waypoint41 waypoint49)
	(visible waypoint49 waypoint42)
	(visible waypoint42 waypoint49)
	(at_rock_sample waypoint0)
	(at_soil_sample waypoint1)
	(at_soil_sample waypoint3)
	(at_rock_sample waypoint3)
	(at_rock_sample waypoint4)
	(at_rock_sample waypoint5)
	(at_rock_sample waypoint6)
	(at_soil_sample waypoint8)
	(at_rock_sample waypoint10)
	(at_soil_sample waypoint11)
	(at_soil_sample waypoint12)
	(at_soil_sample waypoint13)
	(at_soil_sample waypoint15)
	(at_rock_sample waypoint15)
	(at_soil_sample waypoint16)
	(at_rock_sample waypoint16)
	(at_soil_sample waypoint17)
	(at_soil_sample waypoint18)
	(at_rock_sample waypoint18)
	(at_rock_sample waypoint19)
	(at_rock_sample waypoint21)
	(at_soil_sample waypoint22)
	(at_rock_sample waypoint25)
	(at_soil_sample waypoint26)
	(at_soil_sample waypoint29)
	(at_rock_sample waypoint30)
	(at_soil_sample waypoint31)
	(at_soil_sample waypoint32)
	(at_rock_sample waypoint32)
	(at_rock_sample waypoint33)
	(at_soil_sample waypoint35)
	(at_soil_sample waypoint36)
	(at_soil_sample waypoint37)
	(at_rock_sample waypoint40)
	(at_rock_sample waypoint41)
	(at_soil_sample waypoint42)
	(at_rock_sample waypoint42)
	(at_soil_sample waypoint43)
	(at_soil_sample waypoint44)
	(at_soil_sample waypoint45)
	(at_rock_sample waypoint45)
	(at_soil_sample waypoint46)
	(at_rock_sample waypoint46)
	(at_rock_sample waypoint48)
	(at_rock_sample waypoint49)
	(at_lander general waypoint38)
	(channel_free general)
	(at rover0 waypoint14)
	(available rover0)
	(store_of rover0store rover0)
	(empty rover0store)
	(equipped_for_rock_analysis rover0)
	(equipped_for_imaging rover0)
	(can_traverse rover0 waypoint14 waypoint5)
	(can_traverse rover0 waypoint5 waypoint14)
	(can_traverse rover0 waypoint14 waypoint11)
	(can_traverse rover0 waypoint11 waypoint14)
	(can_traverse rover0 waypoint14 waypoint13)
	(can_traverse rover0 waypoint13 waypoint14)
	(can_traverse rover0 waypoint14 waypoint20)
	(can_traverse rover0 waypoint20 waypoint14)
	(can_traverse rover0 waypoint14 waypoint24)
	(can_traverse rover0 waypoint24 waypoint14)
	(can_traverse rover0 waypoint14 waypoint33)
	(can_traverse rover0 waypoint33 waypoint14)
	(can_traverse rover0 waypoint14 waypoint42)
	(can_traverse rover0 waypoint42 waypoint14)
	(can_traverse rover0 waypoint14 waypoint43)
	(can_traverse rover0 waypoint43 waypoint14)
	(can_traverse rover0 waypoint14 waypoint46)
	(can_traverse rover0 waypoint46 waypoint14)
	(can_traverse rover0 waypoint5 waypoint1)
	(can_traverse rover0 waypoint1 waypoint5)
	(can_traverse rover0 waypoint5 waypoint3)
	(can_traverse rover0 waypoint3 waypoint5)
	(can_traverse rover0 waypoint5 waypoint10)
	(can_traverse rover0 waypoint10 waypoint5)
	(can_traverse rover0 waypoint5 waypoint17)
	(can_traverse rover0 waypoint17 waypoint5)
	(can_traverse rover0 waypoint5 waypoint25)
	(can_traverse rover0 waypoint25 waypoint5)
	(can_traverse rover0 waypoint5 waypoint36)
	(can_traverse rover0 waypoint36 waypoint5)
	(can_traverse rover0 waypoint5 waypoint41)
	(can_traverse rover0 waypoint41 waypoint5)
	(can_traverse rover0 waypoint11 waypoint6)
	(can_traverse rover0 waypoint6 waypoint11)
	(can_traverse rover0 waypoint11 waypoint7)
	(can_traverse rover0 waypoint7 waypoint11)
	(can_traverse rover0 waypoint11 waypoint8)
	(can_traverse rover0 waypoint8 waypoint11)
	(can_traverse rover0 waypoint11 waypoint35)
	(can_traverse rover0 waypoint35 waypoint11)
	(can_traverse rover0 waypoint11 waypoint49)
	(can_traverse rover0 waypoint49 waypoint11)
	(can_traverse rover0 waypoint13 waypoint9)
	(can_traverse rover0 waypoint9 waypoint13)
	(can_traverse rover0 waypoint13 waypoint22)
	(can_traverse rover0 waypoint22 waypoint13)
	(can_traverse rover0 waypoint13 waypoint28)
	(can_traverse rover0 waypoint28 waypoint13)
	(can_traverse rover0 waypoint20 waypoint4)
	(can_traverse rover0 waypoint4 waypoint20)
	(can_traverse rover0 waypoint20 waypoint18)
	(can_traverse rover0 waypoint18 waypoint20)
	(can_traverse rover0 waypoint20 waypoint38)
	(can_traverse rover0 waypoint38 waypoint20)
	(can_traverse rover0 waypoint20 waypoint44)
	(can_traverse rover0 waypoint44 waypoint20)
	(can_traverse rover0 waypoint20 waypoint45)
	(can_traverse rover0 waypoint45 waypoint20)
	(can_traverse rover0 waypoint24 waypoint0)
	(can_traverse rover0 waypoint0 waypoint24)
	(can_traverse rover0 waypoint24 waypoint27)
	(can_traverse rover0 waypoint27 waypoint24)
	(can_traverse rover0 waypoint24 waypoint34)
	(can_traverse rover0 waypoint34 waypoint24)
	(can_traverse rover0 waypoint24 waypoint40)
	(can_traverse rover0 waypoint40 waypoint24)
	(can_traverse rover0 waypoint33 waypoint15)
	(can_traverse rover0 waypoint15 waypoint33)
	(can_traverse rover0 waypoint33 waypoint19)
	(can_traverse rover0 waypoint19 waypoint33)
	(can_traverse rover0 waypoint33 waypoint21)
	(can_traverse rover0 waypoint21 waypoint33)
	(can_traverse rover0 waypoint33 waypoint48)
	(can_traverse rover0 waypoint48 waypoint33)
	(can_traverse rover0 waypoint46 waypoint23)
	(can_traverse rover0 waypoint23 waypoint46)
	(can_traverse rover0 waypoint46 waypoint32)
	(can_traverse rover0 waypoint32 waypoint46)
	(can_traverse rover0 waypoint46 waypoint47)
	(can_traverse rover0 waypoint47 waypoint46)
	(can_traverse rover0 waypoint1 waypoint30)
	(can_traverse rover0 waypoint30 waypoint1)
	(can_traverse rover0 waypoint10 waypoint12)
	(can_traverse rover0 waypoint12 waypoint10)
	(can_traverse rover0 waypoint10 waypoint26)
	(can_traverse rover0 waypoint26 waypoint10)
	(can_traverse rover0 waypoint25 waypoint16)
	(can_traverse rover0 waypoint16 waypoint25)
	(can_traverse rover0 waypoint25 waypoint29)
	(can_traverse rover0 waypoint29 waypoint25)
	(can_traverse rover0 waypoint25 waypoint39)
	(can_traverse rover0 waypoint39 waypoint25)
	(can_traverse rover0 waypoint36 waypoint37)
	(can_traverse rover0 waypoint37 waypoint36)
	(can_traverse rover0 waypoint41 waypoint2)
	(can_traverse rover0 waypoint2 waypoint41)
	(at rover1 waypoint39)
	(available rover1)
	(store_of rover1store rover1)
	(empty rover1store)
	(equipped_for_soil_analysis rover1)
	(equipped_for_imaging rover1)
	(can_traverse rover1 waypoint39 waypoint7)
	(can_traverse rover1 waypoint7 waypoint39)
	(can_traverse rover1 waypoint39 waypoint17)
	(can_traverse rover1 waypoint17 waypoint39)
	(can_traverse rover1 waypoint39 waypoint25)
	(can_traverse rover1 waypoint25 waypoint39)
	(can_traverse rover1 waypoint39 waypoint28)
	(can_traverse rover1 waypoint28 waypoint39)
	(can_traverse rover1 waypoint39 waypoint32)
	(can_traverse rover1 waypoint32 waypoint39)
	(can_traverse rover1 waypoint7 waypoint5)
	(can_traverse rover1 waypoint5 waypoint7)
	(can_traverse rover1 waypoint7 waypoint12)
	(can_traverse rover1 waypoint12 waypoint7)
	(can_traverse rover1 waypoint7 waypoint45)
	(can_traverse rover1 waypoint45 waypoint7)
	(can_traverse rover1 waypoint7 waypoint46)
	(can_traverse rover1 waypoint46 waypoint7)
	(can_traverse rover1 waypoint17 waypoint0)
	(can_traverse rover1 waypoint0 waypoint17)
	(can_traverse rover1 waypoint17 waypoint3)
	(can_traverse rover1 waypoint3 waypoint17)
	(can_traverse rover1 waypoint17 waypoint13)
	(can_traverse rover1 waypoint13 waypoint17)
	(can_traverse rover1 waypoint17 waypoint14)
	(can_traverse rover1 waypoint14 waypoint17)
	(can_traverse rover1 waypoint17 waypoint40)
	(can_traverse rover1 waypoint40 waypoint17)
	(can_traverse rover1 waypoint25 waypoint29)
	(can_traverse rover1 waypoint29 waypoint25)
	(can_traverse rover1 waypoint25 waypoint42)
	(can_traverse rover1 waypoint42 waypoint25)
	(can_traverse rover1 waypoint28 waypoint23)
	(can_traverse rover1 waypoint23 waypoint28)
	(can_traverse rover1 waypoint28 waypoint26)
	(can_traverse rover1 waypoint26 waypoint28)
	(can_traverse rover1 waypoint28 waypoint33)
	(can_traverse rover1 waypoint33 waypoint28)
	(can_traverse rover1 waypoint28 waypoint37)
	(can_traverse rover1 waypoint37 waypoint28)
	(can_traverse rover1 waypoint32 waypoint6)
	(can_traverse rover1 waypoint6 waypoint32)
	(can_traverse rover1 waypoint32 waypoint19)
	(can_traverse rover1 waypoint19 waypoint32)
	(can_traverse rover1 waypoint32 waypoint47)
	(can_traverse rover1 waypoint47 waypoint32)
	(can_traverse rover1 waypoint5 waypoint1)
	(can_traverse rover1 waypoint1 waypoint5)
	(can_traverse rover1 waypoint5 waypoint10)
	(can_traverse rover1 waypoint10 waypoint5)
	(can_traverse rover1 waypoint5 waypoint24)
	(can_traverse rover1 waypoint24 waypoint5)
	(can_traverse rover1 waypoint5 waypoint35)
	(can_traverse rover1 waypoint35 waypoint5)
	(can_traverse rover1 waypoint5 waypoint36)
	(can_traverse rover1 waypoint36 waypoint5)
	(can_traverse rover1 waypoint5 waypoint41)
	(can_traverse rover1 waypoint41 waypoint5)
	(can_traverse rover1 waypoint12 waypoint18)
	(can_traverse rover1 waypoint18 waypoint12)
	(can_traverse rover1 waypoint45 waypoint2)
	(can_traverse rover1 waypoint2 waypoint45)
	(can_traverse rover1 waypoint45 waypoint27)
	(can_traverse rover1 waypoint27 waypoint45)
	(can_traverse rover1 waypoint46 waypoint8)
	(can_traverse rover1 waypoint8 waypoint46)
	(can_traverse rover1 waypoint46 waypoint9)
	(can_traverse rover1 waypoint9 waypoint46)
	(can_traverse rover1 waypoint46 waypoint21)
	(can_traverse rover1 waypoint21 waypoint46)
	(can_traverse rover1 waypoint0 waypoint4)
	(can_traverse rover1 waypoint4 waypoint0)
	(can_traverse rover1 waypoint14 waypoint20)
	(can_traverse rover1 waypoint20 waypoint14)
	(can_traverse rover1 waypoint14 waypoint31)
	(can_traverse rover1 waypoint31 waypoint14)
	(can_traverse rover1 waypoint14 waypoint44)
	(can_traverse rover1 waypoint44 waypoint14)
	(can_traverse rover1 waypoint40 waypoint15)
	(can_traverse rover1 waypoint15 waypoint40)
	(can_traverse rover1 waypoint42 waypoint34)
	(can_traverse rover1 waypoint34 waypoint42)
	(can_traverse rover1 waypoint42 waypoint38)
	(can_traverse rover1 waypoint38 waypoint42)
	(can_traverse rover1 waypoint23 waypoint16)
	(can_traverse rover1 waypoint16 waypoint23)
	(can_traverse rover1 waypoint23 waypoint30)
	(can_traverse rover1 waypoint30 waypoint23)
	(can_traverse rover1 waypoint23 waypoint48)
	(can_traverse rover1 waypoint48 waypoint23)
	(can_traverse rover1 waypoint33 waypoint22)
	(can_traverse rover1 waypoint22 waypoint33)
	(can_traverse rover1 waypoint6 waypoint11)
	(can_traverse rover1 waypoint11 waypoint6)
	(can_traverse rover1 waypoint6 waypoint49)
	(can_traverse rover1 waypoint49 waypoint6)
	(can_traverse rover1 waypoint41 waypoint43)
	(can_traverse rover1 waypoint43 waypoint41)
	(at rover2 waypoint29)
	(available rover2)
	(store_of rover2store rover2)
	(empty rover2store)
	(equipped_for_imaging rover2)
	(can_traverse rover2 waypoint29 waypoint2)
	(can_traverse rover2 waypoint2 waypoint29)
	(can_traverse rover2 waypoint29 waypoint6)
	(can_traverse rover2 waypoint6 waypoint29)
	(can_traverse rover2 waypoint29 waypoint16)
	(can_traverse rover2 waypoint16 waypoint29)
	(can_traverse rover2 waypoint29 waypoint32)
	(can_traverse rover2 waypoint32 waypoint29)
	(can_traverse rover2 waypoint29 waypoint39)
	(can_traverse rover2 waypoint39 waypoint29)
	(can_traverse rover2 waypoint29 waypoint44)
	(can_traverse rover2 waypoint44 waypoint29)
	(can_traverse rover2 waypoint29 waypoint45)
	(can_traverse rover2 waypoint45 waypoint29)
	(can_traverse rover2 waypoint2 waypoint41)
	(can_traverse rover2 waypoint41 waypoint2)
	(can_traverse rover2 waypoint6 waypoint3)
	(can_traverse rover2 waypoint3 waypoint6)
	(can_traverse rover2 waypoint6 waypoint11)
	(can_traverse rover2 waypoint11 waypoint6)
	(can_traverse rover2 waypoint16 waypoint21)
	(can_traverse rover2 waypoint21 waypoint16)
	(can_traverse rover2 waypoint16 waypoint23)
	(can_traverse rover2 waypoint23 waypoint16)
	(can_traverse rover2 waypoint16 waypoint25)
	(can_traverse rover2 waypoint25 waypoint16)
	(can_traverse rover2 waypoint16 waypoint26)
	(can_traverse rover2 waypoint26 waypoint16)
	(can_traverse rover2 waypoint16 waypoint30)
	(can_traverse rover2 waypoint30 waypoint16)
	(can_traverse rover2 waypoint16 waypoint40)
	(can_traverse rover2 waypoint40 waypoint16)
	(can_traverse rover2 waypoint32 waypoint38)
	(can_traverse rover2 waypoint38 waypoint32)
	(can_traverse rover2 waypoint32 waypoint46)
	(can_traverse rover2 waypoint46 waypoint32)
	(can_traverse rover2 waypoint39 waypoint7)
	(can_traverse rover2 waypoint7 waypoint39)
	(can_traverse rover2 waypoint39 waypoint17)
	(can_traverse rover2 waypoint17 waypoint39)
	(can_traverse rover2 waypoint39 waypoint28)
	(can_traverse rover2 waypoint28 waypoint39)
	(can_traverse rover2 waypoint44 waypoint12)
	(can_traverse rover2 waypoint12 waypoint44)
	(can_traverse rover2 waypoint44 waypoint14)
	(can_traverse rover2 waypoint14 waypoint44)
	(can_traverse rover2 waypoint44 waypoint33)
	(can_traverse rover2 waypoint33 waypoint44)
	(can_traverse rover2 waypoint44 waypoint34)
	(can_traverse rover2 waypoint34 waypoint44)
	(can_traverse rover2 waypoint44 waypoint43)
	(can_traverse rover2 waypoint43 waypoint44)
	(can_traverse rover2 waypoint41 waypoint0)
	(can_traverse rover2 waypoint0 waypoint41)
	(can_traverse rover2 waypoint41 waypoint5)
	(can_traverse rover2 waypoint5 waypoint41)
	(can_traverse rover2 waypoint41 waypoint15)
	(can_traverse rover2 waypoint15 waypoint41)
	(can_traverse rover2 waypoint41 waypoint49)
	(can_traverse rover2 waypoint49 waypoint41)
	(can_traverse rover2 waypoint3 waypoint4)
	(can_traverse rover2 waypoint4 waypoint3)
	(can_traverse rover2 waypoint3 waypoint9)
	(can_traverse rover2 waypoint9 waypoint3)
	(can_traverse rover2 waypoint3 waypoint24)
	(can_traverse rover2 waypoint24 waypoint3)
	(can_traverse rover2 waypoint3 waypoint35)
	(can_traverse rover2 waypoint35 waypoint3)
	(can_traverse rover2 waypoint11 waypoint1)
	(can_traverse rover2 waypoint1 waypoint11)
	(can_traverse rover2 waypoint11 waypoint8)
	(can_traverse rover2 waypoint8 waypoint11)
	(can_traverse rover2 waypoint11 waypoint48)
	(can_traverse rover2 waypoint48 waypoint11)
	(can_traverse rover2 waypoint21 waypoint10)
	(can_traverse rover2 waypoint10 waypoint21)
	(can_traverse rover2 waypoint21 waypoint27)
	(can_traverse rover2 waypoint27 waypoint21)
	(can_traverse rover2 waypoint21 waypoint36)
	(can_traverse rover2 waypoint36 waypoint21)
	(can_traverse rover2 waypoint21 waypoint37)
	(can_traverse rover2 waypoint37 waypoint21)
	(can_traverse rover2 waypoint25 waypoint42)
	(can_traverse rover2 waypoint42 waypoint25)
	(can_traverse rover2 waypoint26 waypoint18)
	(can_traverse rover2 waypoint18 waypoint26)
	(can_traverse rover2 waypoint40 waypoint31)
	(can_traverse rover2 waypoint31 waypoint40)
	(can_traverse rover2 waypoint38 waypoint20)
	(can_traverse rover2 waypoint20 waypoint38)
	(can_traverse rover2 waypoint46 waypoint47)
	(can_traverse rover2 waypoint47 waypoint46)
	(can_traverse rover2 waypoint17 waypoint13)
	(can_traverse rover2 waypoint13 waypoint17)
	(can_traverse rover2 waypoint33 waypoint19)
	(can_traverse rover2 waypoint19 waypoint33)
	(can_traverse rover2 waypoint4 waypoint22)
	(can_traverse rover2 waypoint22 waypoint4)
	(at rover3 waypoint39)
	(available rover3)
	(store_of rover3store rover3)
	(empty rover3store)
	(equipped_for_soil_analysis rover3)
	(equipped_for_rock_analysis rover3)
	(equipped_for_imaging rover3)
	(can_traverse rover3 waypoint39 waypoint7)
	(can_traverse rover3 waypoint7 waypoint39)
	(can_traverse rover3 waypoint39 waypoint17)
	(can_traverse rover3 waypoint17 waypoint39)
	(can_traverse rover3 waypoint39 waypoint25)
	(can_traverse rover3 waypoint25 waypoint39)
	(can_traverse rover3 waypoint39 waypoint28)
	(can_traverse rover3 waypoint28 waypoint39)
	(can_traverse rover3 waypoint39 waypoint36)
	(can_traverse rover3 waypoint36 waypoint39)
	(can_traverse rover3 waypoint7 waypoint5)
	(can_traverse rover3 waypoint5 waypoint7)
	(can_traverse rover3 waypoint7 waypoint11)
	(can_traverse rover3 waypoint11 waypoint7)
	(can_traverse rover3 waypoint7 waypoint27)
	(can_traverse rover3 waypoint27 waypoint7)
	(can_traverse rover3 waypoint7 waypoint45)
	(can_traverse rover3 waypoint45 waypoint7)
	(can_traverse rover3 waypoint7 waypoint46)
	(can_traverse rover3 waypoint46 waypoint7)
	(can_traverse rover3 waypoint17 waypoint14)
	(can_traverse rover3 waypoint14 waypoint17)
	(can_traverse rover3 waypoint17 waypoint37)
	(can_traverse rover3 waypoint37 waypoint17)
	(can_traverse rover3 waypoint17 waypoint40)
	(can_traverse rover3 waypoint40 waypoint17)
	(can_traverse rover3 waypoint17 waypoint41)
	(can_traverse rover3 waypoint41 waypoint17)
	(can_traverse rover3 waypoint25 waypoint16)
	(can_traverse rover3 waypoint16 waypoint25)
	(can_traverse rover3 waypoint25 waypoint29)
	(can_traverse rover3 waypoint29 waypoint25)
	(can_traverse rover3 waypoint25 waypoint42)
	(can_traverse rover3 waypoint42 waypoint25)
	(can_traverse rover3 waypoint28 waypoint8)
	(can_traverse rover3 waypoint8 waypoint28)
	(can_traverse rover3 waypoint28 waypoint23)
	(can_traverse rover3 waypoint23 waypoint28)
	(can_traverse rover3 waypoint28 waypoint26)
	(can_traverse rover3 waypoint26 waypoint28)
	(can_traverse rover3 waypoint28 waypoint33)
	(can_traverse rover3 waypoint33 waypoint28)
	(can_traverse rover3 waypoint28 waypoint43)
	(can_traverse rover3 waypoint43 waypoint28)
	(can_traverse rover3 waypoint36 waypoint9)
	(can_traverse rover3 waypoint9 waypoint36)
	(can_traverse rover3 waypoint36 waypoint18)
	(can_traverse rover3 waypoint18 waypoint36)
	(can_traverse rover3 waypoint36 waypoint21)
	(can_traverse rover3 waypoint21 waypoint36)
	(can_traverse rover3 waypoint36 waypoint48)
	(can_traverse rover3 waypoint48 waypoint36)
	(can_traverse rover3 waypoint5 waypoint1)
	(can_traverse rover3 waypoint1 waypoint5)
	(can_traverse rover3 waypoint5 waypoint3)
	(can_traverse rover3 waypoint3 waypoint5)
	(can_traverse rover3 waypoint5 waypoint35)
	(can_traverse rover3 waypoint35 waypoint5)
	(can_traverse rover3 waypoint11 waypoint49)
	(can_traverse rover3 waypoint49 waypoint11)
	(can_traverse rover3 waypoint27 waypoint13)
	(can_traverse rover3 waypoint13 waypoint27)
	(can_traverse rover3 waypoint27 waypoint30)
	(can_traverse rover3 waypoint30 waypoint27)
	(can_traverse rover3 waypoint27 waypoint34)
	(can_traverse rover3 waypoint34 waypoint27)
	(can_traverse rover3 waypoint45 waypoint2)
	(can_traverse rover3 waypoint2 waypoint45)
	(can_traverse rover3 waypoint45 waypoint6)
	(can_traverse rover3 waypoint6 waypoint45)
	(can_traverse rover3 waypoint45 waypoint20)
	(can_traverse rover3 waypoint20 waypoint45)
	(can_traverse rover3 waypoint46 waypoint32)
	(can_traverse rover3 waypoint32 waypoint46)
	(can_traverse rover3 waypoint14 waypoint31)
	(can_traverse rover3 waypoint31 waypoint14)
	(can_traverse rover3 waypoint14 waypoint44)
	(can_traverse rover3 waypoint44 waypoint14)
	(can_traverse rover3 waypoint37 waypoint0)
	(can_traverse rover3 waypoint0 waypoint37)
	(can_traverse rover3 waypoint37 waypoint38)
	(can_traverse rover3 waypoint38 waypoint37)
	(can_traverse rover3 waypoint40 waypoint12)
	(can_traverse rover3 waypoint12 waypoint40)
	(can_traverse rover3 waypoint40 waypoint15)
	(can_traverse rover3 waypoint15 waypoint40)
	(can_traverse rover3 waypoint40 waypoint24)
	(can_traverse rover3 waypoint24 waypoint40)
	(can_traverse rover3 waypoint41 waypoint4)
	(can_traverse rover3 waypoint4 waypoint41)
	(can_traverse rover3 waypoint8 waypoint10)
	(can_traverse rover3 waypoint10 waypoint8)
	(can_traverse rover3 waypoint33 waypoint19)
	(can_traverse rover3 waypoint19 waypoint33)
	(can_traverse rover3 waypoint48 waypoint47)
	(can_traverse rover3 waypoint47 waypoint48)
	(can_traverse rover3 waypoint24 waypoint22)
	(can_traverse rover3 waypoint22 waypoint24)
	(on_board camera0 rover0)
	(calibration_target camera0 objective3)
	(supports camera0 high_res)
	(supports camera0 low_res)
	(on_board camera1 rover2)
	(calibration_target camera1 objective1)
	(supports camera1 colour)
	(supports camera1 low_res)
	(on_board camera2 rover0)
	(calibration_target camera2 objective1)
	(supports camera2 high_res)
	(on_board camera3 rover2)
	(calibration_target camera3 objective0)
	(supports camera3 high_res)
	(on_board camera4 rover3)
	(calibration_target camera4 objective0)
	(supports camera4 colour)
	(on_board camera5 rover1)
	(calibration_target camera5 objective6)
	(supports camera5 colour)
	(visible_from objective0 waypoint0)
	(visible_from objective0 waypoint1)
	(visible_from objective0 waypoint6)
	(visible_from objective0 waypoint10)
	(visible_from objective0 waypoint11)
	(visible_from objective0 waypoint12)
	(visible_from objective0 waypoint13)
	(visible_from objective0 waypoint15)
	(visible_from objective0 waypoint16)
	(visible_from objective0 waypoint19)
	(visible_from objective0 waypoint21)
	(visible_from objective0 waypoint24)
	(visible_from objective0 waypoint25)
	(visible_from objective0 waypoint28)
	(visible_from objective0 waypoint29)
	(visible_from objective0 waypoint31)
	(visible_from objective0 waypoint32)
	(visible_from objective0 waypoint36)
	(visible_from objective0 waypoint37)
	(visible_from objective0 waypoint38)
	(visible_from objective0 waypoint40)
	(visible_from objective0 waypoint44)
	(visible_from objective0 waypoint46)
	(visible_from objective0 waypoint49)
	(visible_from objective1 waypoint11)
	(visible_from objective1 waypoint12)
	(visible_from objective1 waypoint16)
	(visible_from objective1 waypoint19)
	(visible_from objective1 waypoint21)
	(visible_from objective1 waypoint32)
	(visible_from objective1 waypoint33)
	(visible_from objective1 waypoint41)
	(visible_from objective1 waypoint47)
	(visible_from objective2 waypoint0)
	(visible_from objective2 waypoint1)
	(visible_from objective2 waypoint9)
	(visible_from objective2 waypoint12)
	(visible_from objective2 waypoint13)
	(visible_from objective2 waypoint28)
	(visible_from objective2 waypoint33)
	(visible_from objective2 waypoint34)
	(visible_from objective2 waypoint35)
	(visible_from objective2 waypoint37)
	(visible_from objective2 waypoint38)
	(visible_from objective3 waypoint16)
	(visible_from objective3 waypoint38)
	(visible_from objective4 waypoint13)
	(visible_from objective4 waypoint20)
	(visible_from objective4 waypoint29)
	(visible_from objective4 waypoint40)
	(visible_from objective5 waypoint2)
	(visible_from objective5 waypoint11)
	(visible_from objective5 waypoint13)
	(visible_from objective5 waypoint24)
	(visible_from objective5 waypoint44)
	(visible_from objective6 waypoint9)
	(visible_from objective6 waypoint13)
	(visible_from objective6 waypoint15)
	(visible_from objective6 waypoint21)
	(visible_from objective6 waypoint27)
	(visible_from objective6 waypoint33)
	(visible_from objective6 waypoint36)
	(visible_from objective6 waypoint38)
	(visible_from objective6 waypoint43)
	(visible_from objective6 waypoint44)
	(visible_from objective6 waypoint45)
	(visible_from objective6 waypoint48)
	(visible_from objective6 waypoint49)
	(visible_from objective7 waypoint9)
	(visible_from objective7 waypoint14)
	(visible_from objective7 waypoint15)
	(visible_from objective7 waypoint20)
	(visible_from objective7 waypoint22)
	(visible_from objective7 waypoint28)
	(visible_from objective7 waypoint29)
	(visible_from objective7 waypoint32)
	(visible_from objective7 waypoint33)
)

(:goal (and
(communicated_soil_data waypoint35)
(communicated_soil_data waypoint12)
(communicated_soil_data waypoint42)
(communicated_soil_data waypoint29)
(communicated_soil_data waypoint46)
(communicated_soil_data waypoint36)
(communicated_soil_data waypoint37)
(communicated_soil_data waypoint31)
(communicated_soil_data waypoint32)
(communicated_soil_data waypoint22)
(communicated_rock_data waypoint41)
(communicated_rock_data waypoint30)
(communicated_rock_data waypoint25)
(communicated_rock_data waypoint45)
(communicated_rock_data waypoint15)
(communicated_rock_data waypoint4)
(communicated_rock_data waypoint18)
(communicated_rock_data waypoint0)
(communicated_rock_data waypoint10)
(communicated_rock_data waypoint5)
(communicated_rock_data waypoint3)
(communicated_rock_data waypoint46)
(communicated_rock_data waypoint49)
(communicated_image_data objective7 high_res)
(communicated_image_data objective6 colour)
(communicated_image_data objective0 colour)
(communicated_image_data objective6 high_res)
(communicated_image_data objective0 low_res)
(communicated_image_data objective2 colour)
	)
)
)
