(define (problem prb-034_d21_p-VAL3-n53-r1w30o8c9-5) (:domain Rover)
(:objects
	general - Lander
	colour high_res low_res - Mode
	rover0 - Rover
	rover0store - Store
	waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 waypoint7 waypoint8 waypoint9 waypoint10 waypoint11 waypoint12 waypoint13 waypoint14 waypoint15 waypoint16 waypoint17 waypoint18 waypoint19 waypoint20 waypoint21 waypoint22 waypoint23 waypoint24 waypoint25 waypoint26 waypoint27 waypoint28 waypoint29 - Waypoint
	camera0 camera1 camera2 camera3 camera4 camera5 camera6 camera7 camera8 - Camera
	objective0 objective1 objective2 objective3 objective4 objective5 objective6 objective7 - Objective
	)
(:init
(visible waypoint0 waypoint2)
(visible waypoint2 waypoint0)
(visible waypoint0 waypoint8)
(visible waypoint8 waypoint0)
(visible waypoint0 waypoint9)
(visible waypoint9 waypoint0)
(visible waypoint0 waypoint10)
(visible waypoint10 waypoint0)
(visible waypoint0 waypoint12)
(visible waypoint12 waypoint0)
(visible waypoint0 waypoint14)
(visible waypoint14 waypoint0)
(visible waypoint0 waypoint27)
(visible waypoint27 waypoint0)
(visible waypoint1 waypoint4)
(visible waypoint4 waypoint1)
(visible waypoint1 waypoint5)
(visible waypoint5 waypoint1)
(visible waypoint1 waypoint14)
(visible waypoint14 waypoint1)
(visible waypoint1 waypoint23)
(visible waypoint23 waypoint1)
(visible waypoint2 waypoint5)
(visible waypoint5 waypoint2)
(visible waypoint2 waypoint12)
(visible waypoint12 waypoint2)
(visible waypoint2 waypoint24)
(visible waypoint24 waypoint2)
(visible waypoint3 waypoint6)
(visible waypoint6 waypoint3)
(visible waypoint3 waypoint11)
(visible waypoint11 waypoint3)
(visible waypoint4 waypoint2)
(visible waypoint2 waypoint4)
(visible waypoint4 waypoint20)
(visible waypoint20 waypoint4)
(visible waypoint4 waypoint26)
(visible waypoint26 waypoint4)
(visible waypoint6 waypoint0)
(visible waypoint0 waypoint6)
(visible waypoint6 waypoint1)
(visible waypoint1 waypoint6)
(visible waypoint6 waypoint7)
(visible waypoint7 waypoint6)
(visible waypoint6 waypoint13)
(visible waypoint13 waypoint6)
(visible waypoint7 waypoint3)
(visible waypoint3 waypoint7)
(visible waypoint7 waypoint21)
(visible waypoint21 waypoint7)
(visible waypoint7 waypoint25)
(visible waypoint25 waypoint7)
(visible waypoint8 waypoint1)
(visible waypoint1 waypoint8)
(visible waypoint8 waypoint13)
(visible waypoint13 waypoint8)
(visible waypoint8 waypoint24)
(visible waypoint24 waypoint8)
(visible waypoint8 waypoint29)
(visible waypoint29 waypoint8)
(visible waypoint9 waypoint13)
(visible waypoint13 waypoint9)
(visible waypoint9 waypoint17)
(visible waypoint17 waypoint9)
(visible waypoint9 waypoint26)
(visible waypoint26 waypoint9)
(visible waypoint9 waypoint27)
(visible waypoint27 waypoint9)
(visible waypoint10 waypoint1)
(visible waypoint1 waypoint10)
(visible waypoint10 waypoint6)
(visible waypoint6 waypoint10)
(visible waypoint10 waypoint8)
(visible waypoint8 waypoint10)
(visible waypoint10 waypoint14)
(visible waypoint14 waypoint10)
(visible waypoint10 waypoint26)
(visible waypoint26 waypoint10)
(visible waypoint11 waypoint5)
(visible waypoint5 waypoint11)
(visible waypoint11 waypoint12)
(visible waypoint12 waypoint11)
(visible waypoint11 waypoint21)
(visible waypoint21 waypoint11)
(visible waypoint11 waypoint22)
(visible waypoint22 waypoint11)
(visible waypoint11 waypoint29)
(visible waypoint29 waypoint11)
(visible waypoint12 waypoint6)
(visible waypoint6 waypoint12)
(visible waypoint12 waypoint7)
(visible waypoint7 waypoint12)
(visible waypoint12 waypoint8)
(visible waypoint8 waypoint12)
(visible waypoint12 waypoint14)
(visible waypoint14 waypoint12)
(visible waypoint12 waypoint19)
(visible waypoint19 waypoint12)
(visible waypoint12 waypoint21)
(visible waypoint21 waypoint12)
(visible waypoint12 waypoint28)
(visible waypoint28 waypoint12)
(visible waypoint13 waypoint10)
(visible waypoint10 waypoint13)
(visible waypoint13 waypoint12)
(visible waypoint12 waypoint13)
(visible waypoint14 waypoint3)
(visible waypoint3 waypoint14)
(visible waypoint14 waypoint5)
(visible waypoint5 waypoint14)
(visible waypoint14 waypoint9)
(visible waypoint9 waypoint14)
(visible waypoint14 waypoint19)
(visible waypoint19 waypoint14)
(visible waypoint14 waypoint26)
(visible waypoint26 waypoint14)
(visible waypoint14 waypoint29)
(visible waypoint29 waypoint14)
(visible waypoint15 waypoint2)
(visible waypoint2 waypoint15)
(visible waypoint15 waypoint3)
(visible waypoint3 waypoint15)
(visible waypoint15 waypoint9)
(visible waypoint9 waypoint15)
(visible waypoint15 waypoint11)
(visible waypoint11 waypoint15)
(visible waypoint15 waypoint12)
(visible waypoint12 waypoint15)
(visible waypoint15 waypoint29)
(visible waypoint29 waypoint15)
(visible waypoint16 waypoint0)
(visible waypoint0 waypoint16)
(visible waypoint16 waypoint13)
(visible waypoint13 waypoint16)
(visible waypoint16 waypoint20)
(visible waypoint20 waypoint16)
(visible waypoint16 waypoint25)
(visible waypoint25 waypoint16)
(visible waypoint16 waypoint28)
(visible waypoint28 waypoint16)
(visible waypoint17 waypoint2)
(visible waypoint2 waypoint17)
(visible waypoint17 waypoint5)
(visible waypoint5 waypoint17)
(visible waypoint17 waypoint15)
(visible waypoint15 waypoint17)
(visible waypoint18 waypoint1)
(visible waypoint1 waypoint18)
(visible waypoint18 waypoint2)
(visible waypoint2 waypoint18)
(visible waypoint18 waypoint6)
(visible waypoint6 waypoint18)
(visible waypoint18 waypoint23)
(visible waypoint23 waypoint18)
(visible waypoint19 waypoint9)
(visible waypoint9 waypoint19)
(visible waypoint19 waypoint22)
(visible waypoint22 waypoint19)
(visible waypoint19 waypoint26)
(visible waypoint26 waypoint19)
(visible waypoint20 waypoint5)
(visible waypoint5 waypoint20)
(visible waypoint20 waypoint6)
(visible waypoint6 waypoint20)
(visible waypoint20 waypoint26)
(visible waypoint26 waypoint20)
(visible waypoint20 waypoint27)
(visible waypoint27 waypoint20)
(visible waypoint21 waypoint3)
(visible waypoint3 waypoint21)
(visible waypoint21 waypoint4)
(visible waypoint4 waypoint21)
(visible waypoint21 waypoint13)
(visible waypoint13 waypoint21)
(visible waypoint21 waypoint15)
(visible waypoint15 waypoint21)
(visible waypoint21 waypoint29)
(visible waypoint29 waypoint21)
(visible waypoint22 waypoint16)
(visible waypoint16 waypoint22)
(visible waypoint22 waypoint20)
(visible waypoint20 waypoint22)
(visible waypoint23 waypoint4)
(visible waypoint4 waypoint23)
(visible waypoint23 waypoint10)
(visible waypoint10 waypoint23)
(visible waypoint23 waypoint14)
(visible waypoint14 waypoint23)
(visible waypoint23 waypoint17)
(visible waypoint17 waypoint23)
(visible waypoint24 waypoint21)
(visible waypoint21 waypoint24)
(visible waypoint24 waypoint26)
(visible waypoint26 waypoint24)
(visible waypoint25 waypoint19)
(visible waypoint19 waypoint25)
(visible waypoint25 waypoint22)
(visible waypoint22 waypoint25)
(visible waypoint25 waypoint23)
(visible waypoint23 waypoint25)
(visible waypoint25 waypoint26)
(visible waypoint26 waypoint25)
(visible waypoint26 waypoint0)
(visible waypoint0 waypoint26)
(visible waypoint26 waypoint15)
(visible waypoint15 waypoint26)
(visible waypoint26 waypoint21)
(visible waypoint21 waypoint26)
(visible waypoint26 waypoint29)
(visible waypoint29 waypoint26)
(visible waypoint27 waypoint2)
(visible waypoint2 waypoint27)
(visible waypoint27 waypoint7)
(visible waypoint7 waypoint27)
(visible waypoint27 waypoint14)
(visible waypoint14 waypoint27)
(visible waypoint27 waypoint18)
(visible waypoint18 waypoint27)
(visible waypoint27 waypoint22)
(visible waypoint22 waypoint27)
(visible waypoint28 waypoint10)
(visible waypoint10 waypoint28)
(visible waypoint28 waypoint11)
(visible waypoint11 waypoint28)
(visible waypoint28 waypoint14)
(visible waypoint14 waypoint28)
(visible waypoint28 waypoint24)
(visible waypoint24 waypoint28)
(visible waypoint28 waypoint27)
(visible waypoint27 waypoint28)
(visible waypoint29 waypoint0)
(visible waypoint0 waypoint29)
(visible waypoint29 waypoint2)
(visible waypoint2 waypoint29)
(visible waypoint29 waypoint3)
(visible waypoint3 waypoint29)
(visible waypoint29 waypoint6)
(visible waypoint6 waypoint29)
(visible waypoint29 waypoint9)
(visible waypoint9 waypoint29)
(visible waypoint29 waypoint16)
(visible waypoint16 waypoint29)
(visible waypoint29 waypoint28)
(visible waypoint28 waypoint29)
(at_lander general waypoint17)
(store_of rover0store rover0)
(equipped_for_rock_analysis rover0)
(equipped_for_imaging rover0)
(can_traverse rover0 waypoint5 waypoint1)
(can_traverse rover0 waypoint1 waypoint5)
(can_traverse rover0 waypoint5 waypoint2)
(can_traverse rover0 waypoint2 waypoint5)
(can_traverse rover0 waypoint5 waypoint11)
(can_traverse rover0 waypoint11 waypoint5)
(can_traverse rover0 waypoint5 waypoint14)
(can_traverse rover0 waypoint14 waypoint5)
(can_traverse rover0 waypoint1 waypoint10)
(can_traverse rover0 waypoint10 waypoint1)
(can_traverse rover0 waypoint1 waypoint18)
(can_traverse rover0 waypoint18 waypoint1)
(can_traverse rover0 waypoint2 waypoint0)
(can_traverse rover0 waypoint0 waypoint2)
(can_traverse rover0 waypoint2 waypoint4)
(can_traverse rover0 waypoint4 waypoint2)
(can_traverse rover0 waypoint2 waypoint15)
(can_traverse rover0 waypoint15 waypoint2)
(can_traverse rover0 waypoint2 waypoint17)
(can_traverse rover0 waypoint17 waypoint2)
(can_traverse rover0 waypoint2 waypoint24)
(can_traverse rover0 waypoint24 waypoint2)
(can_traverse rover0 waypoint2 waypoint27)
(can_traverse rover0 waypoint27 waypoint2)
(can_traverse rover0 waypoint2 waypoint29)
(can_traverse rover0 waypoint29 waypoint2)
(can_traverse rover0 waypoint11 waypoint3)
(can_traverse rover0 waypoint3 waypoint11)
(can_traverse rover0 waypoint11 waypoint21)
(can_traverse rover0 waypoint21 waypoint11)
(can_traverse rover0 waypoint11 waypoint22)
(can_traverse rover0 waypoint22 waypoint11)
(can_traverse rover0 waypoint14 waypoint9)
(can_traverse rover0 waypoint9 waypoint14)
(can_traverse rover0 waypoint14 waypoint12)
(can_traverse rover0 waypoint12 waypoint14)
(can_traverse rover0 waypoint14 waypoint19)
(can_traverse rover0 waypoint19 waypoint14)
(can_traverse rover0 waypoint14 waypoint23)
(can_traverse rover0 waypoint23 waypoint14)
(can_traverse rover0 waypoint14 waypoint26)
(can_traverse rover0 waypoint26 waypoint14)
(can_traverse rover0 waypoint14 waypoint28)
(can_traverse rover0 waypoint28 waypoint14)
(can_traverse rover0 waypoint10 waypoint6)
(can_traverse rover0 waypoint6 waypoint10)
(can_traverse rover0 waypoint10 waypoint13)
(can_traverse rover0 waypoint13 waypoint10)
(can_traverse rover0 waypoint0 waypoint8)
(can_traverse rover0 waypoint8 waypoint0)
(can_traverse rover0 waypoint0 waypoint16)
(can_traverse rover0 waypoint16 waypoint0)
(can_traverse rover0 waypoint4 waypoint20)
(can_traverse rover0 waypoint20 waypoint4)
(can_traverse rover0 waypoint3 waypoint7)
(can_traverse rover0 waypoint7 waypoint3)
(can_traverse rover0 waypoint22 waypoint25)
(can_traverse rover0 waypoint25 waypoint22)
(on_board camera0 rover0)
(calibration_target camera0 objective3)
(supports camera0 colour)
(on_board camera1 rover0)
(calibration_target camera1 objective7)
(supports camera1 colour)
(supports camera1 high_res)
(supports camera1 low_res)
(on_board camera2 rover0)
(calibration_target camera2 objective5)
(supports camera2 colour)
(supports camera2 high_res)
(supports camera2 low_res)
(on_board camera3 rover0)
(calibration_target camera3 objective0)
(supports camera3 high_res)
(on_board camera4 rover0)
(calibration_target camera4 objective2)
(supports camera4 colour)
(supports camera4 high_res)
(on_board camera5 rover0)
(calibration_target camera5 objective4)
(supports camera5 colour)
(supports camera5 high_res)
(supports camera5 low_res)
(on_board camera6 rover0)
(calibration_target camera6 objective6)
(supports camera6 high_res)
(on_board camera7 rover0)
(calibration_target camera7 objective5)
(supports camera7 colour)
(on_board camera8 rover0)
(calibration_target camera8 objective0)
(supports camera8 colour)
(supports camera8 low_res)
(visible_from objective0 waypoint0)
(visible_from objective0 waypoint3)
(visible_from objective0 waypoint4)
(visible_from objective0 waypoint7)
(visible_from objective0 waypoint8)
(visible_from objective0 waypoint10)
(visible_from objective0 waypoint11)
(visible_from objective0 waypoint12)
(visible_from objective0 waypoint15)
(visible_from objective0 waypoint18)
(visible_from objective0 waypoint23)
(visible_from objective0 waypoint24)
(visible_from objective1 waypoint0)
(visible_from objective1 waypoint1)
(visible_from objective1 waypoint2)
(visible_from objective1 waypoint3)
(visible_from objective1 waypoint5)
(visible_from objective1 waypoint9)
(visible_from objective1 waypoint10)
(visible_from objective1 waypoint12)
(visible_from objective1 waypoint13)
(visible_from objective1 waypoint14)
(visible_from objective1 waypoint16)
(visible_from objective1 waypoint21)
(visible_from objective1 waypoint23)
(visible_from objective1 waypoint24)
(visible_from objective1 waypoint25)
(visible_from objective1 waypoint26)
(visible_from objective1 waypoint28)
(visible_from objective1 waypoint29)
(visible_from objective2 waypoint0)
(visible_from objective2 waypoint5)
(visible_from objective2 waypoint6)
(visible_from objective2 waypoint7)
(visible_from objective2 waypoint9)
(visible_from objective2 waypoint10)
(visible_from objective2 waypoint12)
(visible_from objective2 waypoint14)
(visible_from objective2 waypoint16)
(visible_from objective2 waypoint19)
(visible_from objective3 waypoint0)
(visible_from objective3 waypoint1)
(visible_from objective3 waypoint2)
(visible_from objective3 waypoint6)
(visible_from objective3 waypoint10)
(visible_from objective3 waypoint11)
(visible_from objective3 waypoint15)
(visible_from objective4 waypoint1)
(visible_from objective4 waypoint3)
(visible_from objective4 waypoint4)
(visible_from objective4 waypoint9)
(visible_from objective4 waypoint13)
(visible_from objective4 waypoint14)
(visible_from objective4 waypoint16)
(visible_from objective4 waypoint17)
(visible_from objective4 waypoint24)
(visible_from objective4 waypoint26)
(visible_from objective4 waypoint28)
(visible_from objective5 waypoint3)
(visible_from objective5 waypoint4)
(visible_from objective5 waypoint7)
(visible_from objective5 waypoint10)
(visible_from objective5 waypoint17)
(visible_from objective5 waypoint20)
(visible_from objective5 waypoint21)
(visible_from objective5 waypoint22)
(visible_from objective5 waypoint28)
(visible_from objective6 waypoint1)
(visible_from objective6 waypoint3)
(visible_from objective6 waypoint4)
(visible_from objective6 waypoint5)
(visible_from objective6 waypoint11)
(visible_from objective6 waypoint12)
(visible_from objective6 waypoint16)
(visible_from objective6 waypoint17)
(visible_from objective6 waypoint20)
(visible_from objective6 waypoint21)
(visible_from objective6 waypoint22)
(visible_from objective6 waypoint23)
(visible_from objective6 waypoint29)
(visible_from objective7 waypoint0)
(visible_from objective7 waypoint5)
(visible_from objective7 waypoint6)
(visible_from objective7 waypoint13)
(visible_from objective7 waypoint15)
(visible_from objective7 waypoint19)
(visible_from objective7 waypoint20)
(visible_from objective7 waypoint24)
(visible_from objective7 waypoint25)
(visible_from objective7 waypoint27)
(at_rock_sample waypoint0)
(at_rock_sample waypoint1)
(at_soil_sample waypoint2)
(at_rock_sample waypoint2)
(at_rock_sample waypoint3)
(at_soil_sample waypoint4)
(at_soil_sample waypoint5)
(at_rock_sample waypoint5)
(at_rock_sample waypoint6)
(at_rock_sample waypoint11)
(at_rock_sample waypoint13)
(at_soil_sample waypoint14)
(at_soil_sample waypoint15)
(at_soil_sample waypoint17)
(at_rock_sample waypoint17)
(at_rock_sample waypoint18)
(at_soil_sample waypoint19)
(at_rock_sample waypoint19)
(at_rock_sample waypoint21)
(at_soil_sample waypoint22)
(at_rock_sample waypoint22)
(at_rock_sample waypoint24)
(at_soil_sample waypoint26)
(at_rock_sample waypoint26)
(at_rock_sample waypoint28)
(channel_free general)
(at rover0 waypoint5)
(available rover0)
(empty rover0store)
(calibrated camera5 rover0)
(have_image rover0 objective3 high_res)
)

(:goal (and
(communicated_rock_data waypoint2)
(communicated_rock_data waypoint1)
(communicated_image_data objective3 low_res)
(communicated_image_data objective3 colour)
(communicated_image_data objective1 low_res)
(communicated_image_data objective3 high_res)
	)
)
)
