(define (problem prb-086_d15_p-VAL3-n57-r2w30o10c9-6) (:domain Rover)
(:objects
	general - Lander
	colour high_res low_res - Mode
	rover0 rover1 - Rover
	rover0store rover1store - Store
	waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 waypoint7 waypoint8 waypoint9 waypoint10 waypoint11 waypoint12 waypoint13 waypoint14 waypoint15 waypoint16 waypoint17 waypoint18 waypoint19 waypoint20 waypoint21 waypoint22 waypoint23 waypoint24 waypoint25 waypoint26 waypoint27 waypoint28 waypoint29 - Waypoint
	camera0 camera1 camera2 camera3 camera4 camera5 camera6 camera7 camera8 - Camera
	objective0 objective1 objective2 objective3 objective4 objective5 objective6 objective7 objective8 objective9 - Objective
	)
(:init
(visible waypoint0 waypoint16)
(visible waypoint16 waypoint0)
(visible waypoint0 waypoint22)
(visible waypoint22 waypoint0)
(visible waypoint0 waypoint23)
(visible waypoint23 waypoint0)
(visible waypoint0 waypoint26)
(visible waypoint26 waypoint0)
(visible waypoint1 waypoint9)
(visible waypoint9 waypoint1)
(visible waypoint1 waypoint20)
(visible waypoint20 waypoint1)
(visible waypoint2 waypoint15)
(visible waypoint15 waypoint2)
(visible waypoint2 waypoint24)
(visible waypoint24 waypoint2)
(visible waypoint2 waypoint28)
(visible waypoint28 waypoint2)
(visible waypoint3 waypoint1)
(visible waypoint1 waypoint3)
(visible waypoint3 waypoint10)
(visible waypoint10 waypoint3)
(visible waypoint3 waypoint22)
(visible waypoint22 waypoint3)
(visible waypoint3 waypoint28)
(visible waypoint28 waypoint3)
(visible waypoint4 waypoint7)
(visible waypoint7 waypoint4)
(visible waypoint4 waypoint17)
(visible waypoint17 waypoint4)
(visible waypoint4 waypoint18)
(visible waypoint18 waypoint4)
(visible waypoint4 waypoint20)
(visible waypoint20 waypoint4)
(visible waypoint4 waypoint22)
(visible waypoint22 waypoint4)
(visible waypoint4 waypoint28)
(visible waypoint28 waypoint4)
(visible waypoint4 waypoint29)
(visible waypoint29 waypoint4)
(visible waypoint5 waypoint12)
(visible waypoint12 waypoint5)
(visible waypoint5 waypoint16)
(visible waypoint16 waypoint5)
(visible waypoint6 waypoint3)
(visible waypoint3 waypoint6)
(visible waypoint6 waypoint4)
(visible waypoint4 waypoint6)
(visible waypoint6 waypoint14)
(visible waypoint14 waypoint6)
(visible waypoint7 waypoint5)
(visible waypoint5 waypoint7)
(visible waypoint7 waypoint20)
(visible waypoint20 waypoint7)
(visible waypoint7 waypoint26)
(visible waypoint26 waypoint7)
(visible waypoint7 waypoint28)
(visible waypoint28 waypoint7)
(visible waypoint8 waypoint0)
(visible waypoint0 waypoint8)
(visible waypoint8 waypoint21)
(visible waypoint21 waypoint8)
(visible waypoint8 waypoint26)
(visible waypoint26 waypoint8)
(visible waypoint9 waypoint6)
(visible waypoint6 waypoint9)
(visible waypoint9 waypoint29)
(visible waypoint29 waypoint9)
(visible waypoint10 waypoint2)
(visible waypoint2 waypoint10)
(visible waypoint10 waypoint5)
(visible waypoint5 waypoint10)
(visible waypoint10 waypoint11)
(visible waypoint11 waypoint10)
(visible waypoint10 waypoint22)
(visible waypoint22 waypoint10)
(visible waypoint10 waypoint23)
(visible waypoint23 waypoint10)
(visible waypoint11 waypoint9)
(visible waypoint9 waypoint11)
(visible waypoint11 waypoint13)
(visible waypoint13 waypoint11)
(visible waypoint11 waypoint23)
(visible waypoint23 waypoint11)
(visible waypoint11 waypoint26)
(visible waypoint26 waypoint11)
(visible waypoint11 waypoint28)
(visible waypoint28 waypoint11)
(visible waypoint12 waypoint0)
(visible waypoint0 waypoint12)
(visible waypoint12 waypoint2)
(visible waypoint2 waypoint12)
(visible waypoint12 waypoint6)
(visible waypoint6 waypoint12)
(visible waypoint12 waypoint26)
(visible waypoint26 waypoint12)
(visible waypoint12 waypoint27)
(visible waypoint27 waypoint12)
(visible waypoint12 waypoint28)
(visible waypoint28 waypoint12)
(visible waypoint13 waypoint1)
(visible waypoint1 waypoint13)
(visible waypoint13 waypoint9)
(visible waypoint9 waypoint13)
(visible waypoint13 waypoint15)
(visible waypoint15 waypoint13)
(visible waypoint13 waypoint22)
(visible waypoint22 waypoint13)
(visible waypoint14 waypoint0)
(visible waypoint0 waypoint14)
(visible waypoint14 waypoint17)
(visible waypoint17 waypoint14)
(visible waypoint14 waypoint23)
(visible waypoint23 waypoint14)
(visible waypoint14 waypoint24)
(visible waypoint24 waypoint14)
(visible waypoint14 waypoint27)
(visible waypoint27 waypoint14)
(visible waypoint14 waypoint28)
(visible waypoint28 waypoint14)
(visible waypoint15 waypoint22)
(visible waypoint22 waypoint15)
(visible waypoint15 waypoint25)
(visible waypoint25 waypoint15)
(visible waypoint15 waypoint28)
(visible waypoint28 waypoint15)
(visible waypoint16 waypoint1)
(visible waypoint1 waypoint16)
(visible waypoint16 waypoint3)
(visible waypoint3 waypoint16)
(visible waypoint16 waypoint4)
(visible waypoint4 waypoint16)
(visible waypoint16 waypoint6)
(visible waypoint6 waypoint16)
(visible waypoint16 waypoint22)
(visible waypoint22 waypoint16)
(visible waypoint17 waypoint3)
(visible waypoint3 waypoint17)
(visible waypoint17 waypoint18)
(visible waypoint18 waypoint17)
(visible waypoint17 waypoint22)
(visible waypoint22 waypoint17)
(visible waypoint18 waypoint2)
(visible waypoint2 waypoint18)
(visible waypoint18 waypoint3)
(visible waypoint3 waypoint18)
(visible waypoint18 waypoint9)
(visible waypoint9 waypoint18)
(visible waypoint18 waypoint12)
(visible waypoint12 waypoint18)
(visible waypoint18 waypoint14)
(visible waypoint14 waypoint18)
(visible waypoint18 waypoint25)
(visible waypoint25 waypoint18)
(visible waypoint19 waypoint1)
(visible waypoint1 waypoint19)
(visible waypoint19 waypoint4)
(visible waypoint4 waypoint19)
(visible waypoint19 waypoint5)
(visible waypoint5 waypoint19)
(visible waypoint19 waypoint6)
(visible waypoint6 waypoint19)
(visible waypoint19 waypoint7)
(visible waypoint7 waypoint19)
(visible waypoint19 waypoint13)
(visible waypoint13 waypoint19)
(visible waypoint19 waypoint15)
(visible waypoint15 waypoint19)
(visible waypoint19 waypoint29)
(visible waypoint29 waypoint19)
(visible waypoint20 waypoint3)
(visible waypoint3 waypoint20)
(visible waypoint20 waypoint5)
(visible waypoint5 waypoint20)
(visible waypoint20 waypoint6)
(visible waypoint6 waypoint20)
(visible waypoint20 waypoint9)
(visible waypoint9 waypoint20)
(visible waypoint20 waypoint10)
(visible waypoint10 waypoint20)
(visible waypoint20 waypoint16)
(visible waypoint16 waypoint20)
(visible waypoint20 waypoint24)
(visible waypoint24 waypoint20)
(visible waypoint20 waypoint27)
(visible waypoint27 waypoint20)
(visible waypoint21 waypoint2)
(visible waypoint2 waypoint21)
(visible waypoint21 waypoint5)
(visible waypoint5 waypoint21)
(visible waypoint22 waypoint2)
(visible waypoint2 waypoint22)
(visible waypoint22 waypoint7)
(visible waypoint7 waypoint22)
(visible waypoint22 waypoint12)
(visible waypoint12 waypoint22)
(visible waypoint22 waypoint19)
(visible waypoint19 waypoint22)
(visible waypoint22 waypoint24)
(visible waypoint24 waypoint22)
(visible waypoint23 waypoint2)
(visible waypoint2 waypoint23)
(visible waypoint23 waypoint3)
(visible waypoint3 waypoint23)
(visible waypoint23 waypoint8)
(visible waypoint8 waypoint23)
(visible waypoint23 waypoint12)
(visible waypoint12 waypoint23)
(visible waypoint24 waypoint0)
(visible waypoint0 waypoint24)
(visible waypoint24 waypoint1)
(visible waypoint1 waypoint24)
(visible waypoint24 waypoint9)
(visible waypoint9 waypoint24)
(visible waypoint25 waypoint8)
(visible waypoint8 waypoint25)
(visible waypoint25 waypoint10)
(visible waypoint10 waypoint25)
(visible waypoint25 waypoint19)
(visible waypoint19 waypoint25)
(visible waypoint25 waypoint29)
(visible waypoint29 waypoint25)
(visible waypoint26 waypoint2)
(visible waypoint2 waypoint26)
(visible waypoint26 waypoint6)
(visible waypoint6 waypoint26)
(visible waypoint26 waypoint23)
(visible waypoint23 waypoint26)
(visible waypoint26 waypoint24)
(visible waypoint24 waypoint26)
(visible waypoint27 waypoint10)
(visible waypoint10 waypoint27)
(visible waypoint28 waypoint6)
(visible waypoint6 waypoint28)
(visible waypoint28 waypoint10)
(visible waypoint10 waypoint28)
(visible waypoint28 waypoint19)
(visible waypoint19 waypoint28)
(visible waypoint28 waypoint21)
(visible waypoint21 waypoint28)
(visible waypoint28 waypoint25)
(visible waypoint25 waypoint28)
(visible waypoint29 waypoint1)
(visible waypoint1 waypoint29)
(visible waypoint29 waypoint11)
(visible waypoint11 waypoint29)
(visible waypoint29 waypoint14)
(visible waypoint14 waypoint29)
(visible waypoint29 waypoint20)
(visible waypoint20 waypoint29)
(visible waypoint29 waypoint22)
(visible waypoint22 waypoint29)
(visible waypoint29 waypoint24)
(visible waypoint24 waypoint29)
(visible waypoint29 waypoint28)
(visible waypoint28 waypoint29)
(at_lander general waypoint12)
(store_of rover0store rover0)
(equipped_for_imaging rover0)
(can_traverse rover0 waypoint12 waypoint0)
(can_traverse rover0 waypoint0 waypoint12)
(can_traverse rover0 waypoint12 waypoint5)
(can_traverse rover0 waypoint5 waypoint12)
(can_traverse rover0 waypoint12 waypoint6)
(can_traverse rover0 waypoint6 waypoint12)
(can_traverse rover0 waypoint12 waypoint22)
(can_traverse rover0 waypoint22 waypoint12)
(can_traverse rover0 waypoint12 waypoint26)
(can_traverse rover0 waypoint26 waypoint12)
(can_traverse rover0 waypoint12 waypoint27)
(can_traverse rover0 waypoint27 waypoint12)
(can_traverse rover0 waypoint12 waypoint28)
(can_traverse rover0 waypoint28 waypoint12)
(can_traverse rover0 waypoint0 waypoint14)
(can_traverse rover0 waypoint14 waypoint0)
(can_traverse rover0 waypoint0 waypoint23)
(can_traverse rover0 waypoint23 waypoint0)
(can_traverse rover0 waypoint0 waypoint24)
(can_traverse rover0 waypoint24 waypoint0)
(can_traverse rover0 waypoint5 waypoint16)
(can_traverse rover0 waypoint16 waypoint5)
(can_traverse rover0 waypoint5 waypoint19)
(can_traverse rover0 waypoint19 waypoint5)
(can_traverse rover0 waypoint6 waypoint3)
(can_traverse rover0 waypoint3 waypoint6)
(can_traverse rover0 waypoint6 waypoint4)
(can_traverse rover0 waypoint4 waypoint6)
(can_traverse rover0 waypoint6 waypoint9)
(can_traverse rover0 waypoint9 waypoint6)
(can_traverse rover0 waypoint6 waypoint20)
(can_traverse rover0 waypoint20 waypoint6)
(can_traverse rover0 waypoint22 waypoint2)
(can_traverse rover0 waypoint2 waypoint22)
(can_traverse rover0 waypoint22 waypoint13)
(can_traverse rover0 waypoint13 waypoint22)
(can_traverse rover0 waypoint22 waypoint15)
(can_traverse rover0 waypoint15 waypoint22)
(can_traverse rover0 waypoint22 waypoint29)
(can_traverse rover0 waypoint29 waypoint22)
(can_traverse rover0 waypoint26 waypoint7)
(can_traverse rover0 waypoint7 waypoint26)
(can_traverse rover0 waypoint26 waypoint8)
(can_traverse rover0 waypoint8 waypoint26)
(can_traverse rover0 waypoint26 waypoint11)
(can_traverse rover0 waypoint11 waypoint26)
(can_traverse rover0 waypoint28 waypoint10)
(can_traverse rover0 waypoint10 waypoint28)
(can_traverse rover0 waypoint28 waypoint21)
(can_traverse rover0 waypoint21 waypoint28)
(can_traverse rover0 waypoint28 waypoint25)
(can_traverse rover0 waypoint25 waypoint28)
(can_traverse rover0 waypoint14 waypoint17)
(can_traverse rover0 waypoint17 waypoint14)
(can_traverse rover0 waypoint14 waypoint18)
(can_traverse rover0 waypoint18 waypoint14)
(can_traverse rover0 waypoint24 waypoint1)
(can_traverse rover0 waypoint1 waypoint24)
(store_of rover1store rover1)
(equipped_for_soil_analysis rover1)
(equipped_for_imaging rover1)
(can_traverse rover1 waypoint5 waypoint7)
(can_traverse rover1 waypoint7 waypoint5)
(can_traverse rover1 waypoint5 waypoint10)
(can_traverse rover1 waypoint10 waypoint5)
(can_traverse rover1 waypoint5 waypoint12)
(can_traverse rover1 waypoint12 waypoint5)
(can_traverse rover1 waypoint5 waypoint16)
(can_traverse rover1 waypoint16 waypoint5)
(can_traverse rover1 waypoint5 waypoint19)
(can_traverse rover1 waypoint19 waypoint5)
(can_traverse rover1 waypoint5 waypoint20)
(can_traverse rover1 waypoint20 waypoint5)
(can_traverse rover1 waypoint5 waypoint21)
(can_traverse rover1 waypoint21 waypoint5)
(can_traverse rover1 waypoint7 waypoint4)
(can_traverse rover1 waypoint4 waypoint7)
(can_traverse rover1 waypoint7 waypoint26)
(can_traverse rover1 waypoint26 waypoint7)
(can_traverse rover1 waypoint10 waypoint2)
(can_traverse rover1 waypoint2 waypoint10)
(can_traverse rover1 waypoint10 waypoint3)
(can_traverse rover1 waypoint3 waypoint10)
(can_traverse rover1 waypoint10 waypoint11)
(can_traverse rover1 waypoint11 waypoint10)
(can_traverse rover1 waypoint10 waypoint23)
(can_traverse rover1 waypoint23 waypoint10)
(can_traverse rover1 waypoint10 waypoint25)
(can_traverse rover1 waypoint25 waypoint10)
(can_traverse rover1 waypoint10 waypoint28)
(can_traverse rover1 waypoint28 waypoint10)
(can_traverse rover1 waypoint12 waypoint0)
(can_traverse rover1 waypoint0 waypoint12)
(can_traverse rover1 waypoint12 waypoint18)
(can_traverse rover1 waypoint18 waypoint12)
(can_traverse rover1 waypoint12 waypoint22)
(can_traverse rover1 waypoint22 waypoint12)
(can_traverse rover1 waypoint16 waypoint1)
(can_traverse rover1 waypoint1 waypoint16)
(can_traverse rover1 waypoint16 waypoint6)
(can_traverse rover1 waypoint6 waypoint16)
(can_traverse rover1 waypoint19 waypoint15)
(can_traverse rover1 waypoint15 waypoint19)
(can_traverse rover1 waypoint19 waypoint29)
(can_traverse rover1 waypoint29 waypoint19)
(can_traverse rover1 waypoint20 waypoint9)
(can_traverse rover1 waypoint9 waypoint20)
(can_traverse rover1 waypoint20 waypoint24)
(can_traverse rover1 waypoint24 waypoint20)
(can_traverse rover1 waypoint20 waypoint27)
(can_traverse rover1 waypoint27 waypoint20)
(can_traverse rover1 waypoint26 waypoint8)
(can_traverse rover1 waypoint8 waypoint26)
(can_traverse rover1 waypoint3 waypoint17)
(can_traverse rover1 waypoint17 waypoint3)
(can_traverse rover1 waypoint11 waypoint13)
(can_traverse rover1 waypoint13 waypoint11)
(can_traverse rover1 waypoint23 waypoint14)
(can_traverse rover1 waypoint14 waypoint23)
(on_board camera0 rover1)
(calibration_target camera0 objective6)
(supports camera0 high_res)
(supports camera0 low_res)
(on_board camera1 rover0)
(calibration_target camera1 objective7)
(supports camera1 high_res)
(on_board camera2 rover1)
(calibration_target camera2 objective4)
(supports camera2 colour)
(supports camera2 low_res)
(on_board camera3 rover1)
(calibration_target camera3 objective8)
(supports camera3 colour)
(on_board camera4 rover1)
(calibration_target camera4 objective6)
(supports camera4 high_res)
(supports camera4 low_res)
(on_board camera5 rover0)
(calibration_target camera5 objective0)
(supports camera5 colour)
(supports camera5 high_res)
(supports camera5 low_res)
(on_board camera6 rover0)
(calibration_target camera6 objective9)
(supports camera6 colour)
(supports camera6 high_res)
(supports camera6 low_res)
(on_board camera7 rover1)
(calibration_target camera7 objective4)
(supports camera7 colour)
(supports camera7 high_res)
(on_board camera8 rover1)
(calibration_target camera8 objective0)
(supports camera8 high_res)
(visible_from objective0 waypoint18)
(visible_from objective1 waypoint0)
(visible_from objective1 waypoint2)
(visible_from objective1 waypoint5)
(visible_from objective1 waypoint7)
(visible_from objective1 waypoint8)
(visible_from objective1 waypoint10)
(visible_from objective1 waypoint11)
(visible_from objective1 waypoint15)
(visible_from objective1 waypoint19)
(visible_from objective1 waypoint24)
(visible_from objective1 waypoint26)
(visible_from objective1 waypoint27)
(visible_from objective2 waypoint1)
(visible_from objective2 waypoint2)
(visible_from objective2 waypoint4)
(visible_from objective2 waypoint15)
(visible_from objective2 waypoint16)
(visible_from objective2 waypoint23)
(visible_from objective2 waypoint25)
(visible_from objective3 waypoint0)
(visible_from objective3 waypoint2)
(visible_from objective3 waypoint7)
(visible_from objective3 waypoint9)
(visible_from objective3 waypoint10)
(visible_from objective3 waypoint11)
(visible_from objective3 waypoint12)
(visible_from objective3 waypoint13)
(visible_from objective3 waypoint14)
(visible_from objective3 waypoint15)
(visible_from objective3 waypoint16)
(visible_from objective3 waypoint20)
(visible_from objective3 waypoint22)
(visible_from objective3 waypoint26)
(visible_from objective4 waypoint0)
(visible_from objective4 waypoint1)
(visible_from objective4 waypoint3)
(visible_from objective4 waypoint4)
(visible_from objective4 waypoint7)
(visible_from objective4 waypoint8)
(visible_from objective4 waypoint10)
(visible_from objective4 waypoint13)
(visible_from objective4 waypoint14)
(visible_from objective4 waypoint15)
(visible_from objective4 waypoint17)
(visible_from objective4 waypoint22)
(visible_from objective4 waypoint24)
(visible_from objective4 waypoint25)
(visible_from objective4 waypoint28)
(visible_from objective4 waypoint29)
(visible_from objective5 waypoint2)
(visible_from objective5 waypoint3)
(visible_from objective5 waypoint6)
(visible_from objective5 waypoint7)
(visible_from objective5 waypoint8)
(visible_from objective5 waypoint11)
(visible_from objective5 waypoint18)
(visible_from objective5 waypoint20)
(visible_from objective5 waypoint21)
(visible_from objective5 waypoint26)
(visible_from objective5 waypoint27)
(visible_from objective5 waypoint29)
(visible_from objective6 waypoint2)
(visible_from objective6 waypoint3)
(visible_from objective6 waypoint6)
(visible_from objective6 waypoint7)
(visible_from objective6 waypoint9)
(visible_from objective6 waypoint10)
(visible_from objective6 waypoint11)
(visible_from objective6 waypoint16)
(visible_from objective6 waypoint18)
(visible_from objective6 waypoint19)
(visible_from objective6 waypoint20)
(visible_from objective6 waypoint23)
(visible_from objective6 waypoint24)
(visible_from objective6 waypoint25)
(visible_from objective6 waypoint26)
(visible_from objective6 waypoint27)
(visible_from objective6 waypoint28)
(visible_from objective7 waypoint1)
(visible_from objective7 waypoint3)
(visible_from objective7 waypoint5)
(visible_from objective7 waypoint12)
(visible_from objective7 waypoint13)
(visible_from objective7 waypoint16)
(visible_from objective7 waypoint18)
(visible_from objective7 waypoint20)
(visible_from objective7 waypoint21)
(visible_from objective7 waypoint22)
(visible_from objective7 waypoint24)
(visible_from objective7 waypoint25)
(visible_from objective7 waypoint26)
(visible_from objective7 waypoint28)
(visible_from objective7 waypoint29)
(visible_from objective8 waypoint12)
(visible_from objective8 waypoint19)
(visible_from objective9 waypoint2)
(visible_from objective9 waypoint4)
(visible_from objective9 waypoint8)
(visible_from objective9 waypoint16)
(visible_from objective9 waypoint17)
(visible_from objective9 waypoint19)
(visible_from objective9 waypoint22)
(visible_from objective9 waypoint27)
(at_soil_sample waypoint0)
(at_rock_sample waypoint0)
(at_soil_sample waypoint1)
(at_rock_sample waypoint1)
(at_soil_sample waypoint4)
(at_rock_sample waypoint4)
(at_soil_sample waypoint5)
(at_rock_sample waypoint5)
(at_soil_sample waypoint6)
(at_rock_sample waypoint6)
(at_soil_sample waypoint7)
(at_soil_sample waypoint8)
(at_rock_sample waypoint10)
(at_soil_sample waypoint11)
(at_soil_sample waypoint12)
(at_rock_sample waypoint12)
(at_soil_sample waypoint14)
(at_rock_sample waypoint14)
(at_soil_sample waypoint15)
(at_rock_sample waypoint15)
(at_soil_sample waypoint17)
(at_rock_sample waypoint17)
(at_rock_sample waypoint18)
(at_rock_sample waypoint19)
(at_rock_sample waypoint20)
(at_soil_sample waypoint21)
(at_rock_sample waypoint21)
(at_rock_sample waypoint22)
(at_rock_sample waypoint24)
(at_soil_sample waypoint25)
(at_rock_sample waypoint26)
(at_soil_sample waypoint27)
(at_rock_sample waypoint28)
(at_soil_sample waypoint29)
(at_rock_sample waypoint29)
(channel_free general)
(at rover0 waypoint12)
(available rover0)
(empty rover0store)
(at rover1 waypoint5)
(available rover1)
(empty rover1store)
(communicated_image_data objective4 high_res)
(communicated_image_data objective3 low_res)
(calibrated camera7 rover1)
(have_image rover1 objective4 high_res)
(have_image rover1 objective3 low_res)
)

(:goal (and
(communicated_soil_data waypoint1)
(communicated_soil_data waypoint7)
(communicated_image_data objective4 high_res)
(communicated_image_data objective3 low_res)
(communicated_image_data objective6 high_res)
	)
)
)
