(define (problem prb-449_d49_p-TST3-n77-r1w45o12c14-1) (:domain Rover)
(:objects
	general - Lander
	colour high_res low_res - Mode
	rover0 - Rover
	rover0store - Store
	waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 waypoint7 waypoint8 waypoint9 waypoint10 waypoint11 waypoint12 waypoint13 waypoint14 waypoint15 waypoint16 waypoint17 waypoint18 waypoint19 waypoint20 waypoint21 waypoint22 waypoint23 waypoint24 waypoint25 waypoint26 waypoint27 waypoint28 waypoint29 waypoint30 waypoint31 waypoint32 waypoint33 waypoint34 waypoint35 waypoint36 waypoint37 waypoint38 waypoint39 waypoint40 waypoint41 waypoint42 waypoint43 waypoint44 - Waypoint
	camera0 camera1 camera2 camera3 camera4 camera5 camera6 camera7 camera8 camera9 camera10 camera11 camera12 camera13 - Camera
	objective0 objective1 objective2 objective3 objective4 objective5 objective6 objective7 objective8 objective9 objective10 objective11 - Objective
	)
(:init
(visible waypoint0 waypoint10)
(visible waypoint10 waypoint0)
(visible waypoint0 waypoint41)
(visible waypoint41 waypoint0)
(visible waypoint1 waypoint33)
(visible waypoint33 waypoint1)
(visible waypoint2 waypoint0)
(visible waypoint0 waypoint2)
(visible waypoint2 waypoint7)
(visible waypoint7 waypoint2)
(visible waypoint2 waypoint23)
(visible waypoint23 waypoint2)
(visible waypoint3 waypoint4)
(visible waypoint4 waypoint3)
(visible waypoint3 waypoint9)
(visible waypoint9 waypoint3)
(visible waypoint3 waypoint28)
(visible waypoint28 waypoint3)
(visible waypoint3 waypoint42)
(visible waypoint42 waypoint3)
(visible waypoint4 waypoint6)
(visible waypoint6 waypoint4)
(visible waypoint4 waypoint17)
(visible waypoint17 waypoint4)
(visible waypoint4 waypoint29)
(visible waypoint29 waypoint4)
(visible waypoint5 waypoint4)
(visible waypoint4 waypoint5)
(visible waypoint5 waypoint16)
(visible waypoint16 waypoint5)
(visible waypoint5 waypoint26)
(visible waypoint26 waypoint5)
(visible waypoint5 waypoint30)
(visible waypoint30 waypoint5)
(visible waypoint5 waypoint35)
(visible waypoint35 waypoint5)
(visible waypoint6 waypoint3)
(visible waypoint3 waypoint6)
(visible waypoint6 waypoint16)
(visible waypoint16 waypoint6)
(visible waypoint6 waypoint27)
(visible waypoint27 waypoint6)
(visible waypoint6 waypoint32)
(visible waypoint32 waypoint6)
(visible waypoint6 waypoint36)
(visible waypoint36 waypoint6)
(visible waypoint6 waypoint39)
(visible waypoint39 waypoint6)
(visible waypoint7 waypoint10)
(visible waypoint10 waypoint7)
(visible waypoint7 waypoint12)
(visible waypoint12 waypoint7)
(visible waypoint7 waypoint17)
(visible waypoint17 waypoint7)
(visible waypoint7 waypoint18)
(visible waypoint18 waypoint7)
(visible waypoint7 waypoint33)
(visible waypoint33 waypoint7)
(visible waypoint7 waypoint37)
(visible waypoint37 waypoint7)
(visible waypoint7 waypoint40)
(visible waypoint40 waypoint7)
(visible waypoint8 waypoint9)
(visible waypoint9 waypoint8)
(visible waypoint8 waypoint12)
(visible waypoint12 waypoint8)
(visible waypoint8 waypoint19)
(visible waypoint19 waypoint8)
(visible waypoint8 waypoint27)
(visible waypoint27 waypoint8)
(visible waypoint8 waypoint29)
(visible waypoint29 waypoint8)
(visible waypoint8 waypoint30)
(visible waypoint30 waypoint8)
(visible waypoint9 waypoint18)
(visible waypoint18 waypoint9)
(visible waypoint10 waypoint17)
(visible waypoint17 waypoint10)
(visible waypoint10 waypoint29)
(visible waypoint29 waypoint10)
(visible waypoint10 waypoint40)
(visible waypoint40 waypoint10)
(visible waypoint10 waypoint43)
(visible waypoint43 waypoint10)
(visible waypoint11 waypoint24)
(visible waypoint24 waypoint11)
(visible waypoint11 waypoint35)
(visible waypoint35 waypoint11)
(visible waypoint11 waypoint39)
(visible waypoint39 waypoint11)
(visible waypoint12 waypoint15)
(visible waypoint15 waypoint12)
(visible waypoint12 waypoint24)
(visible waypoint24 waypoint12)
(visible waypoint12 waypoint33)
(visible waypoint33 waypoint12)
(visible waypoint13 waypoint5)
(visible waypoint5 waypoint13)
(visible waypoint13 waypoint9)
(visible waypoint9 waypoint13)
(visible waypoint13 waypoint10)
(visible waypoint10 waypoint13)
(visible waypoint13 waypoint29)
(visible waypoint29 waypoint13)
(visible waypoint13 waypoint34)
(visible waypoint34 waypoint13)
(visible waypoint13 waypoint39)
(visible waypoint39 waypoint13)
(visible waypoint13 waypoint40)
(visible waypoint40 waypoint13)
(visible waypoint13 waypoint44)
(visible waypoint44 waypoint13)
(visible waypoint14 waypoint4)
(visible waypoint4 waypoint14)
(visible waypoint14 waypoint8)
(visible waypoint8 waypoint14)
(visible waypoint14 waypoint10)
(visible waypoint10 waypoint14)
(visible waypoint14 waypoint19)
(visible waypoint19 waypoint14)
(visible waypoint14 waypoint41)
(visible waypoint41 waypoint14)
(visible waypoint15 waypoint8)
(visible waypoint8 waypoint15)
(visible waypoint15 waypoint26)
(visible waypoint26 waypoint15)
(visible waypoint15 waypoint30)
(visible waypoint30 waypoint15)
(visible waypoint15 waypoint34)
(visible waypoint34 waypoint15)
(visible waypoint15 waypoint36)
(visible waypoint36 waypoint15)
(visible waypoint15 waypoint38)
(visible waypoint38 waypoint15)
(visible waypoint16 waypoint12)
(visible waypoint12 waypoint16)
(visible waypoint16 waypoint23)
(visible waypoint23 waypoint16)
(visible waypoint16 waypoint24)
(visible waypoint24 waypoint16)
(visible waypoint16 waypoint34)
(visible waypoint34 waypoint16)
(visible waypoint16 waypoint39)
(visible waypoint39 waypoint16)
(visible waypoint17 waypoint29)
(visible waypoint29 waypoint17)
(visible waypoint17 waypoint34)
(visible waypoint34 waypoint17)
(visible waypoint17 waypoint36)
(visible waypoint36 waypoint17)
(visible waypoint18 waypoint0)
(visible waypoint0 waypoint18)
(visible waypoint18 waypoint31)
(visible waypoint31 waypoint18)
(visible waypoint18 waypoint40)
(visible waypoint40 waypoint18)
(visible waypoint19 waypoint0)
(visible waypoint0 waypoint19)
(visible waypoint19 waypoint39)
(visible waypoint39 waypoint19)
(visible waypoint19 waypoint41)
(visible waypoint41 waypoint19)
(visible waypoint19 waypoint42)
(visible waypoint42 waypoint19)
(visible waypoint20 waypoint2)
(visible waypoint2 waypoint20)
(visible waypoint20 waypoint10)
(visible waypoint10 waypoint20)
(visible waypoint20 waypoint35)
(visible waypoint35 waypoint20)
(visible waypoint20 waypoint36)
(visible waypoint36 waypoint20)
(visible waypoint20 waypoint38)
(visible waypoint38 waypoint20)
(visible waypoint21 waypoint7)
(visible waypoint7 waypoint21)
(visible waypoint21 waypoint9)
(visible waypoint9 waypoint21)
(visible waypoint21 waypoint10)
(visible waypoint10 waypoint21)
(visible waypoint21 waypoint13)
(visible waypoint13 waypoint21)
(visible waypoint21 waypoint26)
(visible waypoint26 waypoint21)
(visible waypoint21 waypoint28)
(visible waypoint28 waypoint21)
(visible waypoint22 waypoint5)
(visible waypoint5 waypoint22)
(visible waypoint22 waypoint13)
(visible waypoint13 waypoint22)
(visible waypoint22 waypoint15)
(visible waypoint15 waypoint22)
(visible waypoint22 waypoint25)
(visible waypoint25 waypoint22)
(visible waypoint22 waypoint34)
(visible waypoint34 waypoint22)
(visible waypoint22 waypoint43)
(visible waypoint43 waypoint22)
(visible waypoint23 waypoint1)
(visible waypoint1 waypoint23)
(visible waypoint23 waypoint3)
(visible waypoint3 waypoint23)
(visible waypoint23 waypoint6)
(visible waypoint6 waypoint23)
(visible waypoint23 waypoint9)
(visible waypoint9 waypoint23)
(visible waypoint23 waypoint30)
(visible waypoint30 waypoint23)
(visible waypoint23 waypoint34)
(visible waypoint34 waypoint23)
(visible waypoint23 waypoint37)
(visible waypoint37 waypoint23)
(visible waypoint24 waypoint0)
(visible waypoint0 waypoint24)
(visible waypoint25 waypoint18)
(visible waypoint18 waypoint25)
(visible waypoint25 waypoint19)
(visible waypoint19 waypoint25)
(visible waypoint25 waypoint26)
(visible waypoint26 waypoint25)
(visible waypoint25 waypoint34)
(visible waypoint34 waypoint25)
(visible waypoint25 waypoint39)
(visible waypoint39 waypoint25)
(visible waypoint26 waypoint8)
(visible waypoint8 waypoint26)
(visible waypoint26 waypoint10)
(visible waypoint10 waypoint26)
(visible waypoint26 waypoint11)
(visible waypoint11 waypoint26)
(visible waypoint26 waypoint16)
(visible waypoint16 waypoint26)
(visible waypoint26 waypoint20)
(visible waypoint20 waypoint26)
(visible waypoint26 waypoint23)
(visible waypoint23 waypoint26)
(visible waypoint27 waypoint1)
(visible waypoint1 waypoint27)
(visible waypoint27 waypoint11)
(visible waypoint11 waypoint27)
(visible waypoint27 waypoint12)
(visible waypoint12 waypoint27)
(visible waypoint27 waypoint13)
(visible waypoint13 waypoint27)
(visible waypoint27 waypoint22)
(visible waypoint22 waypoint27)
(visible waypoint27 waypoint23)
(visible waypoint23 waypoint27)
(visible waypoint27 waypoint26)
(visible waypoint26 waypoint27)
(visible waypoint27 waypoint28)
(visible waypoint28 waypoint27)
(visible waypoint28 waypoint10)
(visible waypoint10 waypoint28)
(visible waypoint28 waypoint15)
(visible waypoint15 waypoint28)
(visible waypoint28 waypoint19)
(visible waypoint19 waypoint28)
(visible waypoint28 waypoint23)
(visible waypoint23 waypoint28)
(visible waypoint28 waypoint32)
(visible waypoint32 waypoint28)
(visible waypoint28 waypoint34)
(visible waypoint34 waypoint28)
(visible waypoint28 waypoint37)
(visible waypoint37 waypoint28)
(visible waypoint29 waypoint1)
(visible waypoint1 waypoint29)
(visible waypoint29 waypoint11)
(visible waypoint11 waypoint29)
(visible waypoint29 waypoint12)
(visible waypoint12 waypoint29)
(visible waypoint29 waypoint34)
(visible waypoint34 waypoint29)
(visible waypoint29 waypoint38)
(visible waypoint38 waypoint29)
(visible waypoint29 waypoint43)
(visible waypoint43 waypoint29)
(visible waypoint30 waypoint4)
(visible waypoint4 waypoint30)
(visible waypoint30 waypoint7)
(visible waypoint7 waypoint30)
(visible waypoint30 waypoint17)
(visible waypoint17 waypoint30)
(visible waypoint30 waypoint21)
(visible waypoint21 waypoint30)
(visible waypoint30 waypoint22)
(visible waypoint22 waypoint30)
(visible waypoint30 waypoint28)
(visible waypoint28 waypoint30)
(visible waypoint30 waypoint40)
(visible waypoint40 waypoint30)
(visible waypoint31 waypoint14)
(visible waypoint14 waypoint31)
(visible waypoint31 waypoint19)
(visible waypoint19 waypoint31)
(visible waypoint32 waypoint5)
(visible waypoint5 waypoint32)
(visible waypoint32 waypoint8)
(visible waypoint8 waypoint32)
(visible waypoint32 waypoint14)
(visible waypoint14 waypoint32)
(visible waypoint33 waypoint9)
(visible waypoint9 waypoint33)
(visible waypoint33 waypoint16)
(visible waypoint16 waypoint33)
(visible waypoint33 waypoint28)
(visible waypoint28 waypoint33)
(visible waypoint34 waypoint12)
(visible waypoint12 waypoint34)
(visible waypoint34 waypoint31)
(visible waypoint31 waypoint34)
(visible waypoint35 waypoint13)
(visible waypoint13 waypoint35)
(visible waypoint35 waypoint24)
(visible waypoint24 waypoint35)
(visible waypoint35 waypoint32)
(visible waypoint32 waypoint35)
(visible waypoint35 waypoint34)
(visible waypoint34 waypoint35)
(visible waypoint36 waypoint5)
(visible waypoint5 waypoint36)
(visible waypoint36 waypoint41)
(visible waypoint41 waypoint36)
(visible waypoint37 waypoint10)
(visible waypoint10 waypoint37)
(visible waypoint37 waypoint13)
(visible waypoint13 waypoint37)
(visible waypoint37 waypoint14)
(visible waypoint14 waypoint37)
(visible waypoint37 waypoint17)
(visible waypoint17 waypoint37)
(visible waypoint37 waypoint32)
(visible waypoint32 waypoint37)
(visible waypoint37 waypoint36)
(visible waypoint36 waypoint37)
(visible waypoint37 waypoint41)
(visible waypoint41 waypoint37)
(visible waypoint38 waypoint4)
(visible waypoint4 waypoint38)
(visible waypoint38 waypoint9)
(visible waypoint9 waypoint38)
(visible waypoint38 waypoint22)
(visible waypoint22 waypoint38)
(visible waypoint38 waypoint32)
(visible waypoint32 waypoint38)
(visible waypoint39 waypoint3)
(visible waypoint3 waypoint39)
(visible waypoint39 waypoint28)
(visible waypoint28 waypoint39)
(visible waypoint39 waypoint37)
(visible waypoint37 waypoint39)
(visible waypoint40 waypoint3)
(visible waypoint3 waypoint40)
(visible waypoint40 waypoint5)
(visible waypoint5 waypoint40)
(visible waypoint40 waypoint6)
(visible waypoint6 waypoint40)
(visible waypoint40 waypoint15)
(visible waypoint15 waypoint40)
(visible waypoint40 waypoint27)
(visible waypoint27 waypoint40)
(visible waypoint40 waypoint38)
(visible waypoint38 waypoint40)
(visible waypoint40 waypoint39)
(visible waypoint39 waypoint40)
(visible waypoint40 waypoint44)
(visible waypoint44 waypoint40)
(visible waypoint41 waypoint7)
(visible waypoint7 waypoint41)
(visible waypoint41 waypoint8)
(visible waypoint8 waypoint41)
(visible waypoint41 waypoint30)
(visible waypoint30 waypoint41)
(visible waypoint41 waypoint32)
(visible waypoint32 waypoint41)
(visible waypoint42 waypoint20)
(visible waypoint20 waypoint42)
(visible waypoint42 waypoint41)
(visible waypoint41 waypoint42)
(visible waypoint43 waypoint26)
(visible waypoint26 waypoint43)
(visible waypoint43 waypoint41)
(visible waypoint41 waypoint43)
(visible waypoint44 waypoint0)
(visible waypoint0 waypoint44)
(visible waypoint44 waypoint2)
(visible waypoint2 waypoint44)
(visible waypoint44 waypoint9)
(visible waypoint9 waypoint44)
(visible waypoint44 waypoint15)
(visible waypoint15 waypoint44)
(visible waypoint44 waypoint31)
(visible waypoint31 waypoint44)
(visible waypoint44 waypoint33)
(visible waypoint33 waypoint44)
(visible waypoint44 waypoint42)
(visible waypoint42 waypoint44)
(at_lander general waypoint0)
(store_of rover0store rover0)
(equipped_for_soil_analysis rover0)
(equipped_for_imaging rover0)
(can_traverse rover0 waypoint17 waypoint4)
(can_traverse rover0 waypoint4 waypoint17)
(can_traverse rover0 waypoint17 waypoint7)
(can_traverse rover0 waypoint7 waypoint17)
(can_traverse rover0 waypoint17 waypoint10)
(can_traverse rover0 waypoint10 waypoint17)
(can_traverse rover0 waypoint17 waypoint29)
(can_traverse rover0 waypoint29 waypoint17)
(can_traverse rover0 waypoint17 waypoint30)
(can_traverse rover0 waypoint30 waypoint17)
(can_traverse rover0 waypoint17 waypoint34)
(can_traverse rover0 waypoint34 waypoint17)
(can_traverse rover0 waypoint17 waypoint36)
(can_traverse rover0 waypoint36 waypoint17)
(can_traverse rover0 waypoint17 waypoint37)
(can_traverse rover0 waypoint37 waypoint17)
(can_traverse rover0 waypoint4 waypoint3)
(can_traverse rover0 waypoint3 waypoint4)
(can_traverse rover0 waypoint4 waypoint6)
(can_traverse rover0 waypoint6 waypoint4)
(can_traverse rover0 waypoint4 waypoint14)
(can_traverse rover0 waypoint14 waypoint4)
(can_traverse rover0 waypoint4 waypoint38)
(can_traverse rover0 waypoint38 waypoint4)
(can_traverse rover0 waypoint7 waypoint2)
(can_traverse rover0 waypoint2 waypoint7)
(can_traverse rover0 waypoint7 waypoint12)
(can_traverse rover0 waypoint12 waypoint7)
(can_traverse rover0 waypoint7 waypoint18)
(can_traverse rover0 waypoint18 waypoint7)
(can_traverse rover0 waypoint7 waypoint21)
(can_traverse rover0 waypoint21 waypoint7)
(can_traverse rover0 waypoint7 waypoint33)
(can_traverse rover0 waypoint33 waypoint7)
(can_traverse rover0 waypoint7 waypoint40)
(can_traverse rover0 waypoint40 waypoint7)
(can_traverse rover0 waypoint7 waypoint41)
(can_traverse rover0 waypoint41 waypoint7)
(can_traverse rover0 waypoint10 waypoint26)
(can_traverse rover0 waypoint26 waypoint10)
(can_traverse rover0 waypoint10 waypoint43)
(can_traverse rover0 waypoint43 waypoint10)
(can_traverse rover0 waypoint29 waypoint1)
(can_traverse rover0 waypoint1 waypoint29)
(can_traverse rover0 waypoint29 waypoint8)
(can_traverse rover0 waypoint8 waypoint29)
(can_traverse rover0 waypoint30 waypoint5)
(can_traverse rover0 waypoint5 waypoint30)
(can_traverse rover0 waypoint30 waypoint22)
(can_traverse rover0 waypoint22 waypoint30)
(can_traverse rover0 waypoint30 waypoint23)
(can_traverse rover0 waypoint23 waypoint30)
(can_traverse rover0 waypoint34 waypoint13)
(can_traverse rover0 waypoint13 waypoint34)
(can_traverse rover0 waypoint34 waypoint15)
(can_traverse rover0 waypoint15 waypoint34)
(can_traverse rover0 waypoint34 waypoint16)
(can_traverse rover0 waypoint16 waypoint34)
(can_traverse rover0 waypoint34 waypoint25)
(can_traverse rover0 waypoint25 waypoint34)
(can_traverse rover0 waypoint34 waypoint28)
(can_traverse rover0 waypoint28 waypoint34)
(can_traverse rover0 waypoint34 waypoint31)
(can_traverse rover0 waypoint31 waypoint34)
(can_traverse rover0 waypoint37 waypoint32)
(can_traverse rover0 waypoint32 waypoint37)
(can_traverse rover0 waypoint37 waypoint39)
(can_traverse rover0 waypoint39 waypoint37)
(can_traverse rover0 waypoint3 waypoint9)
(can_traverse rover0 waypoint9 waypoint3)
(can_traverse rover0 waypoint3 waypoint42)
(can_traverse rover0 waypoint42 waypoint3)
(can_traverse rover0 waypoint14 waypoint19)
(can_traverse rover0 waypoint19 waypoint14)
(can_traverse rover0 waypoint38 waypoint20)
(can_traverse rover0 waypoint20 waypoint38)
(can_traverse rover0 waypoint2 waypoint0)
(can_traverse rover0 waypoint0 waypoint2)
(can_traverse rover0 waypoint2 waypoint44)
(can_traverse rover0 waypoint44 waypoint2)
(can_traverse rover0 waypoint12 waypoint24)
(can_traverse rover0 waypoint24 waypoint12)
(can_traverse rover0 waypoint12 waypoint27)
(can_traverse rover0 waypoint27 waypoint12)
(can_traverse rover0 waypoint5 waypoint35)
(can_traverse rover0 waypoint35 waypoint5)
(can_traverse rover0 waypoint39 waypoint11)
(can_traverse rover0 waypoint11 waypoint39)
(on_board camera0 rover0)
(calibration_target camera0 objective11)
(supports camera0 low_res)
(on_board camera1 rover0)
(calibration_target camera1 objective11)
(supports camera1 high_res)
(on_board camera2 rover0)
(calibration_target camera2 objective7)
(supports camera2 colour)
(on_board camera3 rover0)
(calibration_target camera3 objective11)
(supports camera3 colour)
(on_board camera4 rover0)
(calibration_target camera4 objective7)
(supports camera4 high_res)
(on_board camera5 rover0)
(calibration_target camera5 objective9)
(supports camera5 high_res)
(supports camera5 low_res)
(on_board camera6 rover0)
(calibration_target camera6 objective7)
(supports camera6 high_res)
(supports camera6 low_res)
(on_board camera7 rover0)
(calibration_target camera7 objective9)
(supports camera7 colour)
(on_board camera8 rover0)
(calibration_target camera8 objective7)
(supports camera8 colour)
(supports camera8 high_res)
(on_board camera9 rover0)
(calibration_target camera9 objective7)
(supports camera9 low_res)
(on_board camera10 rover0)
(calibration_target camera10 objective1)
(supports camera10 colour)
(supports camera10 high_res)
(supports camera10 low_res)
(on_board camera11 rover0)
(calibration_target camera11 objective8)
(supports camera11 high_res)
(on_board camera12 rover0)
(calibration_target camera12 objective6)
(supports camera12 low_res)
(on_board camera13 rover0)
(calibration_target camera13 objective6)
(supports camera13 high_res)
(visible_from objective0 waypoint0)
(visible_from objective0 waypoint2)
(visible_from objective0 waypoint3)
(visible_from objective0 waypoint6)
(visible_from objective0 waypoint11)
(visible_from objective0 waypoint18)
(visible_from objective0 waypoint20)
(visible_from objective0 waypoint21)
(visible_from objective0 waypoint25)
(visible_from objective0 waypoint26)
(visible_from objective0 waypoint28)
(visible_from objective0 waypoint32)
(visible_from objective0 waypoint36)
(visible_from objective0 waypoint44)
(visible_from objective1 waypoint9)
(visible_from objective1 waypoint19)
(visible_from objective1 waypoint20)
(visible_from objective1 waypoint28)
(visible_from objective1 waypoint33)
(visible_from objective1 waypoint34)
(visible_from objective1 waypoint38)
(visible_from objective1 waypoint40)
(visible_from objective1 waypoint41)
(visible_from objective1 waypoint42)
(visible_from objective2 waypoint8)
(visible_from objective2 waypoint9)
(visible_from objective2 waypoint11)
(visible_from objective2 waypoint14)
(visible_from objective2 waypoint20)
(visible_from objective2 waypoint21)
(visible_from objective2 waypoint24)
(visible_from objective2 waypoint34)
(visible_from objective2 waypoint35)
(visible_from objective2 waypoint39)
(visible_from objective2 waypoint40)
(visible_from objective2 waypoint42)
(visible_from objective2 waypoint43)
(visible_from objective3 waypoint2)
(visible_from objective3 waypoint4)
(visible_from objective3 waypoint8)
(visible_from objective3 waypoint9)
(visible_from objective3 waypoint16)
(visible_from objective3 waypoint21)
(visible_from objective3 waypoint24)
(visible_from objective3 waypoint25)
(visible_from objective3 waypoint26)
(visible_from objective3 waypoint27)
(visible_from objective3 waypoint29)
(visible_from objective3 waypoint30)
(visible_from objective3 waypoint38)
(visible_from objective3 waypoint41)
(visible_from objective4 waypoint0)
(visible_from objective4 waypoint5)
(visible_from objective4 waypoint6)
(visible_from objective4 waypoint7)
(visible_from objective4 waypoint10)
(visible_from objective4 waypoint12)
(visible_from objective4 waypoint13)
(visible_from objective4 waypoint15)
(visible_from objective4 waypoint16)
(visible_from objective4 waypoint20)
(visible_from objective4 waypoint21)
(visible_from objective4 waypoint25)
(visible_from objective4 waypoint27)
(visible_from objective4 waypoint28)
(visible_from objective4 waypoint33)
(visible_from objective4 waypoint34)
(visible_from objective4 waypoint35)
(visible_from objective4 waypoint39)
(visible_from objective4 waypoint40)
(visible_from objective4 waypoint41)
(visible_from objective4 waypoint42)
(visible_from objective4 waypoint43)
(visible_from objective5 waypoint0)
(visible_from objective5 waypoint1)
(visible_from objective5 waypoint3)
(visible_from objective5 waypoint4)
(visible_from objective5 waypoint5)
(visible_from objective5 waypoint7)
(visible_from objective5 waypoint8)
(visible_from objective5 waypoint9)
(visible_from objective5 waypoint10)
(visible_from objective5 waypoint12)
(visible_from objective5 waypoint13)
(visible_from objective5 waypoint16)
(visible_from objective5 waypoint17)
(visible_from objective5 waypoint19)
(visible_from objective5 waypoint20)
(visible_from objective5 waypoint22)
(visible_from objective5 waypoint23)
(visible_from objective5 waypoint25)
(visible_from objective5 waypoint27)
(visible_from objective5 waypoint28)
(visible_from objective5 waypoint29)
(visible_from objective5 waypoint32)
(visible_from objective5 waypoint33)
(visible_from objective5 waypoint36)
(visible_from objective5 waypoint41)
(visible_from objective5 waypoint42)
(visible_from objective5 waypoint44)
(visible_from objective6 waypoint2)
(visible_from objective6 waypoint4)
(visible_from objective6 waypoint6)
(visible_from objective6 waypoint7)
(visible_from objective6 waypoint8)
(visible_from objective6 waypoint10)
(visible_from objective6 waypoint11)
(visible_from objective6 waypoint13)
(visible_from objective6 waypoint14)
(visible_from objective6 waypoint15)
(visible_from objective6 waypoint21)
(visible_from objective6 waypoint26)
(visible_from objective6 waypoint29)
(visible_from objective6 waypoint30)
(visible_from objective6 waypoint31)
(visible_from objective6 waypoint33)
(visible_from objective6 waypoint34)
(visible_from objective6 waypoint36)
(visible_from objective6 waypoint40)
(visible_from objective6 waypoint41)
(visible_from objective6 waypoint42)
(visible_from objective7 waypoint0)
(visible_from objective7 waypoint9)
(visible_from objective7 waypoint10)
(visible_from objective7 waypoint11)
(visible_from objective7 waypoint12)
(visible_from objective7 waypoint13)
(visible_from objective7 waypoint14)
(visible_from objective7 waypoint15)
(visible_from objective7 waypoint18)
(visible_from objective7 waypoint19)
(visible_from objective7 waypoint23)
(visible_from objective7 waypoint24)
(visible_from objective7 waypoint26)
(visible_from objective7 waypoint28)
(visible_from objective7 waypoint29)
(visible_from objective7 waypoint30)
(visible_from objective7 waypoint31)
(visible_from objective7 waypoint32)
(visible_from objective7 waypoint36)
(visible_from objective7 waypoint41)
(visible_from objective8 waypoint0)
(visible_from objective8 waypoint11)
(visible_from objective8 waypoint14)
(visible_from objective8 waypoint23)
(visible_from objective8 waypoint27)
(visible_from objective8 waypoint30)
(visible_from objective8 waypoint34)
(visible_from objective8 waypoint38)
(visible_from objective9 waypoint0)
(visible_from objective9 waypoint1)
(visible_from objective9 waypoint3)
(visible_from objective9 waypoint4)
(visible_from objective9 waypoint7)
(visible_from objective9 waypoint8)
(visible_from objective9 waypoint11)
(visible_from objective9 waypoint13)
(visible_from objective9 waypoint15)
(visible_from objective9 waypoint16)
(visible_from objective9 waypoint21)
(visible_from objective9 waypoint22)
(visible_from objective9 waypoint23)
(visible_from objective9 waypoint26)
(visible_from objective9 waypoint27)
(visible_from objective9 waypoint31)
(visible_from objective9 waypoint32)
(visible_from objective9 waypoint33)
(visible_from objective9 waypoint34)
(visible_from objective9 waypoint36)
(visible_from objective9 waypoint39)
(visible_from objective9 waypoint40)
(visible_from objective9 waypoint41)
(visible_from objective9 waypoint43)
(visible_from objective10 waypoint3)
(visible_from objective10 waypoint4)
(visible_from objective10 waypoint5)
(visible_from objective10 waypoint6)
(visible_from objective10 waypoint7)
(visible_from objective10 waypoint9)
(visible_from objective10 waypoint10)
(visible_from objective10 waypoint12)
(visible_from objective10 waypoint14)
(visible_from objective10 waypoint15)
(visible_from objective10 waypoint17)
(visible_from objective10 waypoint19)
(visible_from objective10 waypoint20)
(visible_from objective10 waypoint26)
(visible_from objective10 waypoint27)
(visible_from objective10 waypoint29)
(visible_from objective10 waypoint31)
(visible_from objective10 waypoint33)
(visible_from objective10 waypoint34)
(visible_from objective10 waypoint35)
(visible_from objective10 waypoint36)
(visible_from objective10 waypoint38)
(visible_from objective10 waypoint39)
(visible_from objective10 waypoint41)
(visible_from objective10 waypoint42)
(visible_from objective10 waypoint44)
(visible_from objective11 waypoint0)
(visible_from objective11 waypoint1)
(visible_from objective11 waypoint2)
(visible_from objective11 waypoint3)
(visible_from objective11 waypoint4)
(visible_from objective11 waypoint5)
(visible_from objective11 waypoint7)
(visible_from objective11 waypoint9)
(visible_from objective11 waypoint13)
(visible_from objective11 waypoint14)
(visible_from objective11 waypoint17)
(visible_from objective11 waypoint19)
(visible_from objective11 waypoint20)
(visible_from objective11 waypoint23)
(visible_from objective11 waypoint26)
(visible_from objective11 waypoint29)
(visible_from objective11 waypoint30)
(visible_from objective11 waypoint34)
(visible_from objective11 waypoint35)
(visible_from objective11 waypoint39)
(visible_from objective11 waypoint40)
(visible_from objective11 waypoint41)
(visible_from objective11 waypoint42)
(at_soil_sample waypoint0)
(at_soil_sample waypoint1)
(at_soil_sample waypoint3)
(at_soil_sample waypoint4)
(at_soil_sample waypoint5)
(at_rock_sample waypoint5)
(at_soil_sample waypoint6)
(at_rock_sample waypoint6)
(at_soil_sample waypoint7)
(at_rock_sample waypoint7)
(at_soil_sample waypoint8)
(at_soil_sample waypoint9)
(at_rock_sample waypoint9)
(at_soil_sample waypoint10)
(at_rock_sample waypoint10)
(at_rock_sample waypoint11)
(at_soil_sample waypoint12)
(at_rock_sample waypoint12)
(at_soil_sample waypoint13)
(at_soil_sample waypoint14)
(at_rock_sample waypoint14)
(at_soil_sample waypoint15)
(at_rock_sample waypoint16)
(at_rock_sample waypoint18)
(at_soil_sample waypoint19)
(at_soil_sample waypoint20)
(at_rock_sample waypoint21)
(at_soil_sample waypoint22)
(at_rock_sample waypoint23)
(at_soil_sample waypoint25)
(at_rock_sample waypoint25)
(at_rock_sample waypoint26)
(at_rock_sample waypoint28)
(at_rock_sample waypoint29)
(at_rock_sample waypoint30)
(at_rock_sample waypoint34)
(at_soil_sample waypoint35)
(at_soil_sample waypoint36)
(at_rock_sample waypoint36)
(at_soil_sample waypoint37)
(at_rock_sample waypoint38)
(at_soil_sample waypoint39)
(at_rock_sample waypoint40)
(at_soil_sample waypoint41)
(at_rock_sample waypoint41)
(at_soil_sample waypoint42)
(at_rock_sample waypoint42)
(at_soil_sample waypoint43)
(at_soil_sample waypoint44)
(at_rock_sample waypoint44)
(channel_free general)
(at rover0 waypoint17)
(available rover0)
(empty rover0store)
(calibrated camera1 rover0)
)

(:goal (and
(communicated_soil_data waypoint35)
(communicated_soil_data waypoint13)
(communicated_soil_data waypoint19)
(communicated_soil_data waypoint0)
(communicated_image_data objective4 colour)
(communicated_image_data objective6 colour)
(communicated_image_data objective4 high_res)
(communicated_image_data objective6 high_res)
	)
)
)
