(define (problem prb-578_d91_p-TST3-n89-r3w50o14c15-4) (:domain Rover)
(:objects
	general - Lander
	colour high_res low_res - Mode
	rover0 rover1 rover2 - Rover
	rover0store rover1store rover2store - Store
	waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 waypoint7 waypoint8 waypoint9 waypoint10 waypoint11 waypoint12 waypoint13 waypoint14 waypoint15 waypoint16 waypoint17 waypoint18 waypoint19 waypoint20 waypoint21 waypoint22 waypoint23 waypoint24 waypoint25 waypoint26 waypoint27 waypoint28 waypoint29 waypoint30 waypoint31 waypoint32 waypoint33 waypoint34 waypoint35 waypoint36 waypoint37 waypoint38 waypoint39 waypoint40 waypoint41 waypoint42 waypoint43 waypoint44 waypoint45 waypoint46 waypoint47 waypoint48 waypoint49 - Waypoint
	camera0 camera1 camera2 camera3 camera4 camera5 camera6 camera7 camera8 camera9 camera10 camera11 camera12 camera13 camera14 - Camera
	objective0 objective1 objective2 objective3 objective4 objective5 objective6 objective7 objective8 objective9 objective10 objective11 objective12 objective13 - Objective
	)
(:init
(visible waypoint0 waypoint24)
(visible waypoint24 waypoint0)
(visible waypoint1 waypoint10)
(visible waypoint10 waypoint1)
(visible waypoint1 waypoint13)
(visible waypoint13 waypoint1)
(visible waypoint1 waypoint15)
(visible waypoint15 waypoint1)
(visible waypoint1 waypoint16)
(visible waypoint16 waypoint1)
(visible waypoint1 waypoint20)
(visible waypoint20 waypoint1)
(visible waypoint1 waypoint22)
(visible waypoint22 waypoint1)
(visible waypoint1 waypoint24)
(visible waypoint24 waypoint1)
(visible waypoint1 waypoint29)
(visible waypoint29 waypoint1)
(visible waypoint2 waypoint1)
(visible waypoint1 waypoint2)
(visible waypoint2 waypoint3)
(visible waypoint3 waypoint2)
(visible waypoint2 waypoint6)
(visible waypoint6 waypoint2)
(visible waypoint2 waypoint18)
(visible waypoint18 waypoint2)
(visible waypoint2 waypoint21)
(visible waypoint21 waypoint2)
(visible waypoint2 waypoint26)
(visible waypoint26 waypoint2)
(visible waypoint2 waypoint29)
(visible waypoint29 waypoint2)
(visible waypoint2 waypoint48)
(visible waypoint48 waypoint2)
(visible waypoint3 waypoint4)
(visible waypoint4 waypoint3)
(visible waypoint3 waypoint12)
(visible waypoint12 waypoint3)
(visible waypoint4 waypoint1)
(visible waypoint1 waypoint4)
(visible waypoint4 waypoint6)
(visible waypoint6 waypoint4)
(visible waypoint4 waypoint10)
(visible waypoint10 waypoint4)
(visible waypoint4 waypoint14)
(visible waypoint14 waypoint4)
(visible waypoint4 waypoint44)
(visible waypoint44 waypoint4)
(visible waypoint4 waypoint46)
(visible waypoint46 waypoint4)
(visible waypoint5 waypoint14)
(visible waypoint14 waypoint5)
(visible waypoint5 waypoint16)
(visible waypoint16 waypoint5)
(visible waypoint5 waypoint21)
(visible waypoint21 waypoint5)
(visible waypoint5 waypoint22)
(visible waypoint22 waypoint5)
(visible waypoint5 waypoint23)
(visible waypoint23 waypoint5)
(visible waypoint5 waypoint26)
(visible waypoint26 waypoint5)
(visible waypoint5 waypoint30)
(visible waypoint30 waypoint5)
(visible waypoint5 waypoint37)
(visible waypoint37 waypoint5)
(visible waypoint5 waypoint48)
(visible waypoint48 waypoint5)
(visible waypoint7 waypoint32)
(visible waypoint32 waypoint7)
(visible waypoint8 waypoint3)
(visible waypoint3 waypoint8)
(visible waypoint8 waypoint5)
(visible waypoint5 waypoint8)
(visible waypoint8 waypoint15)
(visible waypoint15 waypoint8)
(visible waypoint8 waypoint17)
(visible waypoint17 waypoint8)
(visible waypoint8 waypoint18)
(visible waypoint18 waypoint8)
(visible waypoint8 waypoint32)
(visible waypoint32 waypoint8)
(visible waypoint8 waypoint34)
(visible waypoint34 waypoint8)
(visible waypoint9 waypoint8)
(visible waypoint8 waypoint9)
(visible waypoint9 waypoint13)
(visible waypoint13 waypoint9)
(visible waypoint9 waypoint15)
(visible waypoint15 waypoint9)
(visible waypoint9 waypoint26)
(visible waypoint26 waypoint9)
(visible waypoint9 waypoint40)
(visible waypoint40 waypoint9)
(visible waypoint9 waypoint48)
(visible waypoint48 waypoint9)
(visible waypoint10 waypoint12)
(visible waypoint12 waypoint10)
(visible waypoint10 waypoint18)
(visible waypoint18 waypoint10)
(visible waypoint10 waypoint35)
(visible waypoint35 waypoint10)
(visible waypoint11 waypoint3)
(visible waypoint3 waypoint11)
(visible waypoint11 waypoint7)
(visible waypoint7 waypoint11)
(visible waypoint11 waypoint10)
(visible waypoint10 waypoint11)
(visible waypoint12 waypoint9)
(visible waypoint9 waypoint12)
(visible waypoint12 waypoint27)
(visible waypoint27 waypoint12)
(visible waypoint12 waypoint34)
(visible waypoint34 waypoint12)
(visible waypoint12 waypoint48)
(visible waypoint48 waypoint12)
(visible waypoint13 waypoint4)
(visible waypoint4 waypoint13)
(visible waypoint13 waypoint24)
(visible waypoint24 waypoint13)
(visible waypoint13 waypoint49)
(visible waypoint49 waypoint13)
(visible waypoint14 waypoint1)
(visible waypoint1 waypoint14)
(visible waypoint14 waypoint23)
(visible waypoint23 waypoint14)
(visible waypoint14 waypoint33)
(visible waypoint33 waypoint14)
(visible waypoint14 waypoint39)
(visible waypoint39 waypoint14)
(visible waypoint14 waypoint41)
(visible waypoint41 waypoint14)
(visible waypoint15 waypoint13)
(visible waypoint13 waypoint15)
(visible waypoint15 waypoint16)
(visible waypoint16 waypoint15)
(visible waypoint15 waypoint17)
(visible waypoint17 waypoint15)
(visible waypoint15 waypoint20)
(visible waypoint20 waypoint15)
(visible waypoint15 waypoint26)
(visible waypoint26 waypoint15)
(visible waypoint16 waypoint0)
(visible waypoint0 waypoint16)
(visible waypoint16 waypoint25)
(visible waypoint25 waypoint16)
(visible waypoint16 waypoint29)
(visible waypoint29 waypoint16)
(visible waypoint17 waypoint1)
(visible waypoint1 waypoint17)
(visible waypoint18 waypoint27)
(visible waypoint27 waypoint18)
(visible waypoint18 waypoint29)
(visible waypoint29 waypoint18)
(visible waypoint18 waypoint30)
(visible waypoint30 waypoint18)
(visible waypoint18 waypoint32)
(visible waypoint32 waypoint18)
(visible waypoint18 waypoint33)
(visible waypoint33 waypoint18)
(visible waypoint18 waypoint39)
(visible waypoint39 waypoint18)
(visible waypoint19 waypoint6)
(visible waypoint6 waypoint19)
(visible waypoint19 waypoint33)
(visible waypoint33 waypoint19)
(visible waypoint19 waypoint45)
(visible waypoint45 waypoint19)
(visible waypoint20 waypoint17)
(visible waypoint17 waypoint20)
(visible waypoint20 waypoint18)
(visible waypoint18 waypoint20)
(visible waypoint20 waypoint22)
(visible waypoint22 waypoint20)
(visible waypoint20 waypoint24)
(visible waypoint24 waypoint20)
(visible waypoint20 waypoint32)
(visible waypoint32 waypoint20)
(visible waypoint20 waypoint41)
(visible waypoint41 waypoint20)
(visible waypoint20 waypoint43)
(visible waypoint43 waypoint20)
(visible waypoint21 waypoint18)
(visible waypoint18 waypoint21)
(visible waypoint21 waypoint20)
(visible waypoint20 waypoint21)
(visible waypoint21 waypoint40)
(visible waypoint40 waypoint21)
(visible waypoint22 waypoint0)
(visible waypoint0 waypoint22)
(visible waypoint22 waypoint3)
(visible waypoint3 waypoint22)
(visible waypoint22 waypoint27)
(visible waypoint27 waypoint22)
(visible waypoint22 waypoint28)
(visible waypoint28 waypoint22)
(visible waypoint22 waypoint47)
(visible waypoint47 waypoint22)
(visible waypoint23 waypoint10)
(visible waypoint10 waypoint23)
(visible waypoint23 waypoint24)
(visible waypoint24 waypoint23)
(visible waypoint24 waypoint3)
(visible waypoint3 waypoint24)
(visible waypoint24 waypoint5)
(visible waypoint5 waypoint24)
(visible waypoint24 waypoint6)
(visible waypoint6 waypoint24)
(visible waypoint24 waypoint11)
(visible waypoint11 waypoint24)
(visible waypoint24 waypoint17)
(visible waypoint17 waypoint24)
(visible waypoint24 waypoint22)
(visible waypoint22 waypoint24)
(visible waypoint24 waypoint30)
(visible waypoint30 waypoint24)
(visible waypoint24 waypoint40)
(visible waypoint40 waypoint24)
(visible waypoint25 waypoint5)
(visible waypoint5 waypoint25)
(visible waypoint25 waypoint10)
(visible waypoint10 waypoint25)
(visible waypoint25 waypoint24)
(visible waypoint24 waypoint25)
(visible waypoint25 waypoint34)
(visible waypoint34 waypoint25)
(visible waypoint26 waypoint7)
(visible waypoint7 waypoint26)
(visible waypoint26 waypoint10)
(visible waypoint10 waypoint26)
(visible waypoint26 waypoint16)
(visible waypoint16 waypoint26)
(visible waypoint26 waypoint20)
(visible waypoint20 waypoint26)
(visible waypoint26 waypoint21)
(visible waypoint21 waypoint26)
(visible waypoint26 waypoint28)
(visible waypoint28 waypoint26)
(visible waypoint26 waypoint39)
(visible waypoint39 waypoint26)
(visible waypoint27 waypoint28)
(visible waypoint28 waypoint27)
(visible waypoint27 waypoint39)
(visible waypoint39 waypoint27)
(visible waypoint27 waypoint45)
(visible waypoint45 waypoint27)
(visible waypoint28 waypoint1)
(visible waypoint1 waypoint28)
(visible waypoint28 waypoint33)
(visible waypoint33 waypoint28)
(visible waypoint28 waypoint40)
(visible waypoint40 waypoint28)
(visible waypoint28 waypoint41)
(visible waypoint41 waypoint28)
(visible waypoint28 waypoint46)
(visible waypoint46 waypoint28)
(visible waypoint29 waypoint3)
(visible waypoint3 waypoint29)
(visible waypoint29 waypoint7)
(visible waypoint7 waypoint29)
(visible waypoint29 waypoint15)
(visible waypoint15 waypoint29)
(visible waypoint29 waypoint23)
(visible waypoint23 waypoint29)
(visible waypoint29 waypoint25)
(visible waypoint25 waypoint29)
(visible waypoint29 waypoint28)
(visible waypoint28 waypoint29)
(visible waypoint30 waypoint31)
(visible waypoint31 waypoint30)
(visible waypoint30 waypoint38)
(visible waypoint38 waypoint30)
(visible waypoint30 waypoint44)
(visible waypoint44 waypoint30)
(visible waypoint31 waypoint6)
(visible waypoint6 waypoint31)
(visible waypoint31 waypoint15)
(visible waypoint15 waypoint31)
(visible waypoint31 waypoint23)
(visible waypoint23 waypoint31)
(visible waypoint31 waypoint40)
(visible waypoint40 waypoint31)
(visible waypoint31 waypoint45)
(visible waypoint45 waypoint31)
(visible waypoint32 waypoint23)
(visible waypoint23 waypoint32)
(visible waypoint32 waypoint27)
(visible waypoint27 waypoint32)
(visible waypoint32 waypoint28)
(visible waypoint28 waypoint32)
(visible waypoint32 waypoint46)
(visible waypoint46 waypoint32)
(visible waypoint33 waypoint30)
(visible waypoint30 waypoint33)
(visible waypoint33 waypoint32)
(visible waypoint32 waypoint33)
(visible waypoint33 waypoint37)
(visible waypoint37 waypoint33)
(visible waypoint33 waypoint38)
(visible waypoint38 waypoint33)
(visible waypoint34 waypoint0)
(visible waypoint0 waypoint34)
(visible waypoint35 waypoint3)
(visible waypoint3 waypoint35)
(visible waypoint35 waypoint11)
(visible waypoint11 waypoint35)
(visible waypoint35 waypoint22)
(visible waypoint22 waypoint35)
(visible waypoint35 waypoint34)
(visible waypoint34 waypoint35)
(visible waypoint36 waypoint4)
(visible waypoint4 waypoint36)
(visible waypoint36 waypoint23)
(visible waypoint23 waypoint36)
(visible waypoint36 waypoint29)
(visible waypoint29 waypoint36)
(visible waypoint36 waypoint37)
(visible waypoint37 waypoint36)
(visible waypoint36 waypoint42)
(visible waypoint42 waypoint36)
(visible waypoint36 waypoint48)
(visible waypoint48 waypoint36)
(visible waypoint37 waypoint4)
(visible waypoint4 waypoint37)
(visible waypoint37 waypoint25)
(visible waypoint25 waypoint37)
(visible waypoint37 waypoint26)
(visible waypoint26 waypoint37)
(visible waypoint37 waypoint30)
(visible waypoint30 waypoint37)
(visible waypoint37 waypoint41)
(visible waypoint41 waypoint37)
(visible waypoint37 waypoint42)
(visible waypoint42 waypoint37)
(visible waypoint37 waypoint45)
(visible waypoint45 waypoint37)
(visible waypoint37 waypoint46)
(visible waypoint46 waypoint37)
(visible waypoint38 waypoint18)
(visible waypoint18 waypoint38)
(visible waypoint38 waypoint20)
(visible waypoint20 waypoint38)
(visible waypoint38 waypoint41)
(visible waypoint41 waypoint38)
(visible waypoint38 waypoint44)
(visible waypoint44 waypoint38)
(visible waypoint39 waypoint2)
(visible waypoint2 waypoint39)
(visible waypoint39 waypoint7)
(visible waypoint7 waypoint39)
(visible waypoint39 waypoint9)
(visible waypoint9 waypoint39)
(visible waypoint39 waypoint16)
(visible waypoint16 waypoint39)
(visible waypoint39 waypoint21)
(visible waypoint21 waypoint39)
(visible waypoint39 waypoint37)
(visible waypoint37 waypoint39)
(visible waypoint39 waypoint38)
(visible waypoint38 waypoint39)
(visible waypoint40 waypoint14)
(visible waypoint14 waypoint40)
(visible waypoint40 waypoint45)
(visible waypoint45 waypoint40)
(visible waypoint41 waypoint1)
(visible waypoint1 waypoint41)
(visible waypoint41 waypoint9)
(visible waypoint9 waypoint41)
(visible waypoint41 waypoint12)
(visible waypoint12 waypoint41)
(visible waypoint41 waypoint32)
(visible waypoint32 waypoint41)
(visible waypoint41 waypoint35)
(visible waypoint35 waypoint41)
(visible waypoint42 waypoint6)
(visible waypoint6 waypoint42)
(visible waypoint42 waypoint18)
(visible waypoint18 waypoint42)
(visible waypoint42 waypoint44)
(visible waypoint44 waypoint42)
(visible waypoint43 waypoint5)
(visible waypoint5 waypoint43)
(visible waypoint43 waypoint6)
(visible waypoint6 waypoint43)
(visible waypoint43 waypoint9)
(visible waypoint9 waypoint43)
(visible waypoint43 waypoint12)
(visible waypoint12 waypoint43)
(visible waypoint43 waypoint15)
(visible waypoint15 waypoint43)
(visible waypoint43 waypoint17)
(visible waypoint17 waypoint43)
(visible waypoint44 waypoint5)
(visible waypoint5 waypoint44)
(visible waypoint44 waypoint17)
(visible waypoint17 waypoint44)
(visible waypoint44 waypoint41)
(visible waypoint41 waypoint44)
(visible waypoint44 waypoint48)
(visible waypoint48 waypoint44)
(visible waypoint45 waypoint6)
(visible waypoint6 waypoint45)
(visible waypoint45 waypoint9)
(visible waypoint9 waypoint45)
(visible waypoint45 waypoint12)
(visible waypoint12 waypoint45)
(visible waypoint45 waypoint32)
(visible waypoint32 waypoint45)
(visible waypoint46 waypoint14)
(visible waypoint14 waypoint46)
(visible waypoint46 waypoint18)
(visible waypoint18 waypoint46)
(visible waypoint46 waypoint19)
(visible waypoint19 waypoint46)
(visible waypoint46 waypoint21)
(visible waypoint21 waypoint46)
(visible waypoint46 waypoint35)
(visible waypoint35 waypoint46)
(visible waypoint47 waypoint23)
(visible waypoint23 waypoint47)
(visible waypoint47 waypoint31)
(visible waypoint31 waypoint47)
(visible waypoint47 waypoint48)
(visible waypoint48 waypoint47)
(visible waypoint48 waypoint1)
(visible waypoint1 waypoint48)
(visible waypoint48 waypoint13)
(visible waypoint13 waypoint48)
(visible waypoint48 waypoint20)
(visible waypoint20 waypoint48)
(visible waypoint48 waypoint21)
(visible waypoint21 waypoint48)
(visible waypoint48 waypoint33)
(visible waypoint33 waypoint48)
(visible waypoint49 waypoint1)
(visible waypoint1 waypoint49)
(visible waypoint49 waypoint14)
(visible waypoint14 waypoint49)
(visible waypoint49 waypoint23)
(visible waypoint23 waypoint49)
(visible waypoint49 waypoint25)
(visible waypoint25 waypoint49)
(visible waypoint49 waypoint36)
(visible waypoint36 waypoint49)
(visible waypoint49 waypoint40)
(visible waypoint40 waypoint49)
(visible waypoint49 waypoint47)
(visible waypoint47 waypoint49)
(at_lander general waypoint11)
(store_of rover0store rover0)
(equipped_for_soil_analysis rover0)
(equipped_for_imaging rover0)
(can_traverse rover0 waypoint20 waypoint1)
(can_traverse rover0 waypoint1 waypoint20)
(can_traverse rover0 waypoint20 waypoint15)
(can_traverse rover0 waypoint15 waypoint20)
(can_traverse rover0 waypoint20 waypoint17)
(can_traverse rover0 waypoint17 waypoint20)
(can_traverse rover0 waypoint20 waypoint21)
(can_traverse rover0 waypoint21 waypoint20)
(can_traverse rover0 waypoint20 waypoint22)
(can_traverse rover0 waypoint22 waypoint20)
(can_traverse rover0 waypoint20 waypoint24)
(can_traverse rover0 waypoint24 waypoint20)
(can_traverse rover0 waypoint20 waypoint26)
(can_traverse rover0 waypoint26 waypoint20)
(can_traverse rover0 waypoint20 waypoint32)
(can_traverse rover0 waypoint32 waypoint20)
(can_traverse rover0 waypoint20 waypoint38)
(can_traverse rover0 waypoint38 waypoint20)
(can_traverse rover0 waypoint20 waypoint41)
(can_traverse rover0 waypoint41 waypoint20)
(can_traverse rover0 waypoint1 waypoint2)
(can_traverse rover0 waypoint2 waypoint1)
(can_traverse rover0 waypoint1 waypoint4)
(can_traverse rover0 waypoint4 waypoint1)
(can_traverse rover0 waypoint1 waypoint10)
(can_traverse rover0 waypoint10 waypoint1)
(can_traverse rover0 waypoint1 waypoint14)
(can_traverse rover0 waypoint14 waypoint1)
(can_traverse rover0 waypoint1 waypoint28)
(can_traverse rover0 waypoint28 waypoint1)
(can_traverse rover0 waypoint1 waypoint48)
(can_traverse rover0 waypoint48 waypoint1)
(can_traverse rover0 waypoint15 waypoint8)
(can_traverse rover0 waypoint8 waypoint15)
(can_traverse rover0 waypoint15 waypoint9)
(can_traverse rover0 waypoint9 waypoint15)
(can_traverse rover0 waypoint15 waypoint13)
(can_traverse rover0 waypoint13 waypoint15)
(can_traverse rover0 waypoint15 waypoint16)
(can_traverse rover0 waypoint16 waypoint15)
(can_traverse rover0 waypoint15 waypoint43)
(can_traverse rover0 waypoint43 waypoint15)
(can_traverse rover0 waypoint17 waypoint44)
(can_traverse rover0 waypoint44 waypoint17)
(can_traverse rover0 waypoint21 waypoint5)
(can_traverse rover0 waypoint5 waypoint21)
(can_traverse rover0 waypoint21 waypoint18)
(can_traverse rover0 waypoint18 waypoint21)
(can_traverse rover0 waypoint21 waypoint39)
(can_traverse rover0 waypoint39 waypoint21)
(can_traverse rover0 waypoint21 waypoint40)
(can_traverse rover0 waypoint40 waypoint21)
(can_traverse rover0 waypoint21 waypoint46)
(can_traverse rover0 waypoint46 waypoint21)
(can_traverse rover0 waypoint22 waypoint0)
(can_traverse rover0 waypoint0 waypoint22)
(can_traverse rover0 waypoint22 waypoint3)
(can_traverse rover0 waypoint3 waypoint22)
(can_traverse rover0 waypoint22 waypoint35)
(can_traverse rover0 waypoint35 waypoint22)
(can_traverse rover0 waypoint24 waypoint6)
(can_traverse rover0 waypoint6 waypoint24)
(can_traverse rover0 waypoint24 waypoint11)
(can_traverse rover0 waypoint11 waypoint24)
(can_traverse rover0 waypoint24 waypoint23)
(can_traverse rover0 waypoint23 waypoint24)
(can_traverse rover0 waypoint26 waypoint37)
(can_traverse rover0 waypoint37 waypoint26)
(can_traverse rover0 waypoint32 waypoint7)
(can_traverse rover0 waypoint7 waypoint32)
(can_traverse rover0 waypoint32 waypoint27)
(can_traverse rover0 waypoint27 waypoint32)
(can_traverse rover0 waypoint32 waypoint33)
(can_traverse rover0 waypoint33 waypoint32)
(can_traverse rover0 waypoint32 waypoint45)
(can_traverse rover0 waypoint45 waypoint32)
(can_traverse rover0 waypoint38 waypoint30)
(can_traverse rover0 waypoint30 waypoint38)
(can_traverse rover0 waypoint4 waypoint36)
(can_traverse rover0 waypoint36 waypoint4)
(can_traverse rover0 waypoint10 waypoint12)
(can_traverse rover0 waypoint12 waypoint10)
(can_traverse rover0 waypoint10 waypoint25)
(can_traverse rover0 waypoint25 waypoint10)
(can_traverse rover0 waypoint48 waypoint47)
(can_traverse rover0 waypoint47 waypoint48)
(can_traverse rover0 waypoint8 waypoint34)
(can_traverse rover0 waypoint34 waypoint8)
(can_traverse rover0 waypoint13 waypoint49)
(can_traverse rover0 waypoint49 waypoint13)
(can_traverse rover0 waypoint44 waypoint42)
(can_traverse rover0 waypoint42 waypoint44)
(can_traverse rover0 waypoint18 waypoint29)
(can_traverse rover0 waypoint29 waypoint18)
(can_traverse rover0 waypoint40 waypoint31)
(can_traverse rover0 waypoint31 waypoint40)
(store_of rover1store rover1)
(equipped_for_imaging rover1)
(can_traverse rover1 waypoint28 waypoint1)
(can_traverse rover1 waypoint1 waypoint28)
(can_traverse rover1 waypoint28 waypoint27)
(can_traverse rover1 waypoint27 waypoint28)
(can_traverse rover1 waypoint28 waypoint29)
(can_traverse rover1 waypoint29 waypoint28)
(can_traverse rover1 waypoint28 waypoint32)
(can_traverse rover1 waypoint32 waypoint28)
(can_traverse rover1 waypoint28 waypoint33)
(can_traverse rover1 waypoint33 waypoint28)
(can_traverse rover1 waypoint28 waypoint40)
(can_traverse rover1 waypoint40 waypoint28)
(can_traverse rover1 waypoint28 waypoint41)
(can_traverse rover1 waypoint41 waypoint28)
(can_traverse rover1 waypoint1 waypoint2)
(can_traverse rover1 waypoint2 waypoint1)
(can_traverse rover1 waypoint1 waypoint4)
(can_traverse rover1 waypoint4 waypoint1)
(can_traverse rover1 waypoint1 waypoint10)
(can_traverse rover1 waypoint10 waypoint1)
(can_traverse rover1 waypoint1 waypoint13)
(can_traverse rover1 waypoint13 waypoint1)
(can_traverse rover1 waypoint1 waypoint14)
(can_traverse rover1 waypoint14 waypoint1)
(can_traverse rover1 waypoint1 waypoint15)
(can_traverse rover1 waypoint15 waypoint1)
(can_traverse rover1 waypoint1 waypoint16)
(can_traverse rover1 waypoint16 waypoint1)
(can_traverse rover1 waypoint1 waypoint17)
(can_traverse rover1 waypoint17 waypoint1)
(can_traverse rover1 waypoint1 waypoint20)
(can_traverse rover1 waypoint20 waypoint1)
(can_traverse rover1 waypoint1 waypoint22)
(can_traverse rover1 waypoint22 waypoint1)
(can_traverse rover1 waypoint1 waypoint24)
(can_traverse rover1 waypoint24 waypoint1)
(can_traverse rover1 waypoint1 waypoint48)
(can_traverse rover1 waypoint48 waypoint1)
(can_traverse rover1 waypoint27 waypoint12)
(can_traverse rover1 waypoint12 waypoint27)
(can_traverse rover1 waypoint27 waypoint39)
(can_traverse rover1 waypoint39 waypoint27)
(can_traverse rover1 waypoint27 waypoint45)
(can_traverse rover1 waypoint45 waypoint27)
(can_traverse rover1 waypoint29 waypoint3)
(can_traverse rover1 waypoint3 waypoint29)
(can_traverse rover1 waypoint29 waypoint7)
(can_traverse rover1 waypoint7 waypoint29)
(can_traverse rover1 waypoint29 waypoint23)
(can_traverse rover1 waypoint23 waypoint29)
(can_traverse rover1 waypoint29 waypoint25)
(can_traverse rover1 waypoint25 waypoint29)
(can_traverse rover1 waypoint32 waypoint8)
(can_traverse rover1 waypoint8 waypoint32)
(can_traverse rover1 waypoint32 waypoint18)
(can_traverse rover1 waypoint18 waypoint32)
(can_traverse rover1 waypoint32 waypoint46)
(can_traverse rover1 waypoint46 waypoint32)
(can_traverse rover1 waypoint33 waypoint30)
(can_traverse rover1 waypoint30 waypoint33)
(can_traverse rover1 waypoint33 waypoint37)
(can_traverse rover1 waypoint37 waypoint33)
(can_traverse rover1 waypoint40 waypoint31)
(can_traverse rover1 waypoint31 waypoint40)
(can_traverse rover1 waypoint40 waypoint49)
(can_traverse rover1 waypoint49 waypoint40)
(can_traverse rover1 waypoint41 waypoint9)
(can_traverse rover1 waypoint9 waypoint41)
(can_traverse rover1 waypoint41 waypoint38)
(can_traverse rover1 waypoint38 waypoint41)
(can_traverse rover1 waypoint41 waypoint44)
(can_traverse rover1 waypoint44 waypoint41)
(can_traverse rover1 waypoint2 waypoint6)
(can_traverse rover1 waypoint6 waypoint2)
(can_traverse rover1 waypoint2 waypoint26)
(can_traverse rover1 waypoint26 waypoint2)
(can_traverse rover1 waypoint4 waypoint36)
(can_traverse rover1 waypoint36 waypoint4)
(can_traverse rover1 waypoint10 waypoint11)
(can_traverse rover1 waypoint11 waypoint10)
(can_traverse rover1 waypoint10 waypoint35)
(can_traverse rover1 waypoint35 waypoint10)
(can_traverse rover1 waypoint14 waypoint5)
(can_traverse rover1 waypoint5 waypoint14)
(can_traverse rover1 waypoint15 waypoint43)
(can_traverse rover1 waypoint43 waypoint15)
(can_traverse rover1 waypoint16 waypoint0)
(can_traverse rover1 waypoint0 waypoint16)
(can_traverse rover1 waypoint22 waypoint47)
(can_traverse rover1 waypoint47 waypoint22)
(can_traverse rover1 waypoint48 waypoint21)
(can_traverse rover1 waypoint21 waypoint48)
(can_traverse rover1 waypoint25 waypoint34)
(can_traverse rover1 waypoint34 waypoint25)
(can_traverse rover1 waypoint18 waypoint42)
(can_traverse rover1 waypoint42 waypoint18)
(can_traverse rover1 waypoint6 waypoint19)
(can_traverse rover1 waypoint19 waypoint6)
(store_of rover2store rover2)
(equipped_for_rock_analysis rover2)
(equipped_for_imaging rover2)
(can_traverse rover2 waypoint5 waypoint8)
(can_traverse rover2 waypoint8 waypoint5)
(can_traverse rover2 waypoint5 waypoint16)
(can_traverse rover2 waypoint16 waypoint5)
(can_traverse rover2 waypoint5 waypoint22)
(can_traverse rover2 waypoint22 waypoint5)
(can_traverse rover2 waypoint5 waypoint23)
(can_traverse rover2 waypoint23 waypoint5)
(can_traverse rover2 waypoint5 waypoint26)
(can_traverse rover2 waypoint26 waypoint5)
(can_traverse rover2 waypoint5 waypoint30)
(can_traverse rover2 waypoint30 waypoint5)
(can_traverse rover2 waypoint5 waypoint37)
(can_traverse rover2 waypoint37 waypoint5)
(can_traverse rover2 waypoint8 waypoint3)
(can_traverse rover2 waypoint3 waypoint8)
(can_traverse rover2 waypoint8 waypoint9)
(can_traverse rover2 waypoint9 waypoint8)
(can_traverse rover2 waypoint8 waypoint32)
(can_traverse rover2 waypoint32 waypoint8)
(can_traverse rover2 waypoint8 waypoint34)
(can_traverse rover2 waypoint34 waypoint8)
(can_traverse rover2 waypoint16 waypoint0)
(can_traverse rover2 waypoint0 waypoint16)
(can_traverse rover2 waypoint16 waypoint15)
(can_traverse rover2 waypoint15 waypoint16)
(can_traverse rover2 waypoint22 waypoint20)
(can_traverse rover2 waypoint20 waypoint22)
(can_traverse rover2 waypoint22 waypoint27)
(can_traverse rover2 waypoint27 waypoint22)
(can_traverse rover2 waypoint22 waypoint28)
(can_traverse rover2 waypoint28 waypoint22)
(can_traverse rover2 waypoint22 waypoint35)
(can_traverse rover2 waypoint35 waypoint22)
(can_traverse rover2 waypoint22 waypoint47)
(can_traverse rover2 waypoint47 waypoint22)
(can_traverse rover2 waypoint23 waypoint10)
(can_traverse rover2 waypoint10 waypoint23)
(can_traverse rover2 waypoint23 waypoint24)
(can_traverse rover2 waypoint24 waypoint23)
(can_traverse rover2 waypoint23 waypoint29)
(can_traverse rover2 waypoint29 waypoint23)
(can_traverse rover2 waypoint23 waypoint31)
(can_traverse rover2 waypoint31 waypoint23)
(can_traverse rover2 waypoint23 waypoint36)
(can_traverse rover2 waypoint36 waypoint23)
(can_traverse rover2 waypoint23 waypoint49)
(can_traverse rover2 waypoint49 waypoint23)
(can_traverse rover2 waypoint26 waypoint2)
(can_traverse rover2 waypoint2 waypoint26)
(can_traverse rover2 waypoint26 waypoint7)
(can_traverse rover2 waypoint7 waypoint26)
(can_traverse rover2 waypoint26 waypoint21)
(can_traverse rover2 waypoint21 waypoint26)
(can_traverse rover2 waypoint26 waypoint39)
(can_traverse rover2 waypoint39 waypoint26)
(can_traverse rover2 waypoint30 waypoint18)
(can_traverse rover2 waypoint18 waypoint30)
(can_traverse rover2 waypoint30 waypoint33)
(can_traverse rover2 waypoint33 waypoint30)
(can_traverse rover2 waypoint30 waypoint38)
(can_traverse rover2 waypoint38 waypoint30)
(can_traverse rover2 waypoint30 waypoint44)
(can_traverse rover2 waypoint44 waypoint30)
(can_traverse rover2 waypoint37 waypoint4)
(can_traverse rover2 waypoint4 waypoint37)
(can_traverse rover2 waypoint37 waypoint25)
(can_traverse rover2 waypoint25 waypoint37)
(can_traverse rover2 waypoint37 waypoint41)
(can_traverse rover2 waypoint41 waypoint37)
(can_traverse rover2 waypoint37 waypoint42)
(can_traverse rover2 waypoint42 waypoint37)
(can_traverse rover2 waypoint37 waypoint45)
(can_traverse rover2 waypoint45 waypoint37)
(can_traverse rover2 waypoint37 waypoint46)
(can_traverse rover2 waypoint46 waypoint37)
(can_traverse rover2 waypoint3 waypoint11)
(can_traverse rover2 waypoint11 waypoint3)
(can_traverse rover2 waypoint3 waypoint12)
(can_traverse rover2 waypoint12 waypoint3)
(can_traverse rover2 waypoint9 waypoint13)
(can_traverse rover2 waypoint13 waypoint9)
(can_traverse rover2 waypoint9 waypoint40)
(can_traverse rover2 waypoint40 waypoint9)
(can_traverse rover2 waypoint15 waypoint1)
(can_traverse rover2 waypoint1 waypoint15)
(can_traverse rover2 waypoint15 waypoint43)
(can_traverse rover2 waypoint43 waypoint15)
(can_traverse rover2 waypoint20 waypoint17)
(can_traverse rover2 waypoint17 waypoint20)
(can_traverse rover2 waypoint20 waypoint48)
(can_traverse rover2 waypoint48 waypoint20)
(can_traverse rover2 waypoint24 waypoint6)
(can_traverse rover2 waypoint6 waypoint24)
(can_traverse rover2 waypoint49 waypoint14)
(can_traverse rover2 waypoint14 waypoint49)
(can_traverse rover2 waypoint33 waypoint19)
(can_traverse rover2 waypoint19 waypoint33)
(on_board camera0 rover0)
(calibration_target camera0 objective0)
(supports camera0 low_res)
(on_board camera1 rover0)
(calibration_target camera1 objective11)
(supports camera1 high_res)
(supports camera1 low_res)
(on_board camera2 rover1)
(calibration_target camera2 objective10)
(supports camera2 colour)
(on_board camera3 rover1)
(calibration_target camera3 objective10)
(supports camera3 high_res)
(on_board camera4 rover2)
(calibration_target camera4 objective6)
(supports camera4 high_res)
(supports camera4 low_res)
(on_board camera5 rover2)
(calibration_target camera5 objective1)
(supports camera5 high_res)
(on_board camera6 rover2)
(calibration_target camera6 objective13)
(supports camera6 colour)
(supports camera6 low_res)
(on_board camera7 rover2)
(calibration_target camera7 objective3)
(supports camera7 high_res)
(on_board camera8 rover1)
(calibration_target camera8 objective4)
(supports camera8 low_res)
(on_board camera9 rover0)
(calibration_target camera9 objective4)
(supports camera9 colour)
(supports camera9 high_res)
(supports camera9 low_res)
(on_board camera10 rover0)
(calibration_target camera10 objective2)
(supports camera10 colour)
(supports camera10 low_res)
(on_board camera11 rover0)
(calibration_target camera11 objective9)
(supports camera11 low_res)
(on_board camera12 rover2)
(calibration_target camera12 objective13)
(supports camera12 colour)
(supports camera12 high_res)
(supports camera12 low_res)
(on_board camera13 rover2)
(calibration_target camera13 objective11)
(supports camera13 low_res)
(on_board camera14 rover0)
(calibration_target camera14 objective9)
(supports camera14 colour)
(supports camera14 low_res)
(visible_from objective0 waypoint0)
(visible_from objective0 waypoint3)
(visible_from objective0 waypoint5)
(visible_from objective0 waypoint7)
(visible_from objective0 waypoint9)
(visible_from objective0 waypoint11)
(visible_from objective0 waypoint12)
(visible_from objective0 waypoint13)
(visible_from objective0 waypoint14)
(visible_from objective0 waypoint15)
(visible_from objective0 waypoint17)
(visible_from objective0 waypoint18)
(visible_from objective0 waypoint19)
(visible_from objective0 waypoint21)
(visible_from objective0 waypoint22)
(visible_from objective0 waypoint23)
(visible_from objective0 waypoint25)
(visible_from objective0 waypoint26)
(visible_from objective0 waypoint27)
(visible_from objective0 waypoint28)
(visible_from objective0 waypoint32)
(visible_from objective0 waypoint33)
(visible_from objective0 waypoint35)
(visible_from objective0 waypoint37)
(visible_from objective0 waypoint38)
(visible_from objective0 waypoint41)
(visible_from objective0 waypoint42)
(visible_from objective0 waypoint43)
(visible_from objective0 waypoint45)
(visible_from objective0 waypoint46)
(visible_from objective0 waypoint47)
(visible_from objective0 waypoint48)
(visible_from objective0 waypoint49)
(visible_from objective1 waypoint0)
(visible_from objective1 waypoint2)
(visible_from objective1 waypoint8)
(visible_from objective1 waypoint10)
(visible_from objective1 waypoint12)
(visible_from objective1 waypoint13)
(visible_from objective1 waypoint14)
(visible_from objective1 waypoint20)
(visible_from objective1 waypoint25)
(visible_from objective1 waypoint26)
(visible_from objective1 waypoint27)
(visible_from objective1 waypoint29)
(visible_from objective1 waypoint31)
(visible_from objective1 waypoint32)
(visible_from objective1 waypoint33)
(visible_from objective1 waypoint35)
(visible_from objective1 waypoint37)
(visible_from objective1 waypoint38)
(visible_from objective1 waypoint41)
(visible_from objective1 waypoint42)
(visible_from objective1 waypoint44)
(visible_from objective1 waypoint45)
(visible_from objective1 waypoint46)
(visible_from objective2 waypoint1)
(visible_from objective2 waypoint5)
(visible_from objective2 waypoint7)
(visible_from objective2 waypoint8)
(visible_from objective2 waypoint11)
(visible_from objective2 waypoint12)
(visible_from objective2 waypoint13)
(visible_from objective2 waypoint15)
(visible_from objective2 waypoint18)
(visible_from objective2 waypoint19)
(visible_from objective2 waypoint20)
(visible_from objective2 waypoint25)
(visible_from objective2 waypoint30)
(visible_from objective2 waypoint32)
(visible_from objective2 waypoint33)
(visible_from objective2 waypoint34)
(visible_from objective2 waypoint36)
(visible_from objective2 waypoint38)
(visible_from objective2 waypoint41)
(visible_from objective2 waypoint42)
(visible_from objective2 waypoint44)
(visible_from objective2 waypoint46)
(visible_from objective2 waypoint47)
(visible_from objective2 waypoint49)
(visible_from objective3 waypoint0)
(visible_from objective3 waypoint1)
(visible_from objective3 waypoint3)
(visible_from objective3 waypoint5)
(visible_from objective3 waypoint9)
(visible_from objective3 waypoint11)
(visible_from objective3 waypoint14)
(visible_from objective3 waypoint16)
(visible_from objective3 waypoint17)
(visible_from objective3 waypoint20)
(visible_from objective3 waypoint21)
(visible_from objective3 waypoint22)
(visible_from objective3 waypoint23)
(visible_from objective3 waypoint25)
(visible_from objective3 waypoint26)
(visible_from objective3 waypoint27)
(visible_from objective3 waypoint29)
(visible_from objective3 waypoint30)
(visible_from objective3 waypoint39)
(visible_from objective3 waypoint44)
(visible_from objective3 waypoint45)
(visible_from objective3 waypoint46)
(visible_from objective3 waypoint47)
(visible_from objective3 waypoint49)
(visible_from objective4 waypoint0)
(visible_from objective4 waypoint1)
(visible_from objective4 waypoint7)
(visible_from objective4 waypoint8)
(visible_from objective4 waypoint9)
(visible_from objective4 waypoint12)
(visible_from objective4 waypoint17)
(visible_from objective4 waypoint18)
(visible_from objective4 waypoint20)
(visible_from objective4 waypoint22)
(visible_from objective4 waypoint24)
(visible_from objective4 waypoint25)
(visible_from objective4 waypoint28)
(visible_from objective4 waypoint30)
(visible_from objective4 waypoint35)
(visible_from objective4 waypoint36)
(visible_from objective4 waypoint39)
(visible_from objective4 waypoint42)
(visible_from objective4 waypoint45)
(visible_from objective4 waypoint47)
(visible_from objective5 waypoint2)
(visible_from objective5 waypoint11)
(visible_from objective5 waypoint35)
(visible_from objective5 waypoint40)
(visible_from objective6 waypoint6)
(visible_from objective7 waypoint0)
(visible_from objective7 waypoint1)
(visible_from objective7 waypoint5)
(visible_from objective7 waypoint8)
(visible_from objective7 waypoint9)
(visible_from objective7 waypoint13)
(visible_from objective7 waypoint15)
(visible_from objective7 waypoint16)
(visible_from objective7 waypoint19)
(visible_from objective7 waypoint20)
(visible_from objective7 waypoint21)
(visible_from objective7 waypoint23)
(visible_from objective7 waypoint24)
(visible_from objective7 waypoint27)
(visible_from objective7 waypoint30)
(visible_from objective7 waypoint31)
(visible_from objective7 waypoint37)
(visible_from objective7 waypoint38)
(visible_from objective7 waypoint40)
(visible_from objective7 waypoint42)
(visible_from objective7 waypoint46)
(visible_from objective7 waypoint49)
(visible_from objective8 waypoint1)
(visible_from objective8 waypoint3)
(visible_from objective8 waypoint4)
(visible_from objective8 waypoint5)
(visible_from objective8 waypoint14)
(visible_from objective8 waypoint17)
(visible_from objective8 waypoint18)
(visible_from objective8 waypoint20)
(visible_from objective8 waypoint21)
(visible_from objective8 waypoint22)
(visible_from objective8 waypoint24)
(visible_from objective8 waypoint25)
(visible_from objective8 waypoint26)
(visible_from objective8 waypoint27)
(visible_from objective8 waypoint28)
(visible_from objective8 waypoint38)
(visible_from objective8 waypoint40)
(visible_from objective8 waypoint42)
(visible_from objective8 waypoint43)
(visible_from objective8 waypoint48)
(visible_from objective9 waypoint0)
(visible_from objective9 waypoint4)
(visible_from objective9 waypoint5)
(visible_from objective9 waypoint6)
(visible_from objective9 waypoint12)
(visible_from objective9 waypoint13)
(visible_from objective9 waypoint18)
(visible_from objective9 waypoint24)
(visible_from objective9 waypoint25)
(visible_from objective9 waypoint30)
(visible_from objective9 waypoint42)
(visible_from objective9 waypoint43)
(visible_from objective9 waypoint46)
(visible_from objective9 waypoint47)
(visible_from objective9 waypoint49)
(visible_from objective10 waypoint1)
(visible_from objective10 waypoint2)
(visible_from objective10 waypoint3)
(visible_from objective10 waypoint5)
(visible_from objective10 waypoint6)
(visible_from objective10 waypoint10)
(visible_from objective10 waypoint12)
(visible_from objective10 waypoint13)
(visible_from objective10 waypoint16)
(visible_from objective10 waypoint17)
(visible_from objective10 waypoint18)
(visible_from objective10 waypoint21)
(visible_from objective10 waypoint23)
(visible_from objective10 waypoint28)
(visible_from objective10 waypoint30)
(visible_from objective10 waypoint31)
(visible_from objective10 waypoint33)
(visible_from objective10 waypoint35)
(visible_from objective10 waypoint36)
(visible_from objective10 waypoint37)
(visible_from objective10 waypoint38)
(visible_from objective10 waypoint40)
(visible_from objective10 waypoint42)
(visible_from objective10 waypoint43)
(visible_from objective10 waypoint45)
(visible_from objective10 waypoint47)
(visible_from objective10 waypoint48)
(visible_from objective10 waypoint49)
(visible_from objective11 waypoint1)
(visible_from objective11 waypoint2)
(visible_from objective11 waypoint3)
(visible_from objective11 waypoint12)
(visible_from objective11 waypoint17)
(visible_from objective11 waypoint18)
(visible_from objective11 waypoint26)
(visible_from objective11 waypoint39)
(visible_from objective11 waypoint46)
(visible_from objective12 waypoint1)
(visible_from objective12 waypoint2)
(visible_from objective12 waypoint3)
(visible_from objective12 waypoint4)
(visible_from objective12 waypoint6)
(visible_from objective12 waypoint7)
(visible_from objective12 waypoint8)
(visible_from objective12 waypoint11)
(visible_from objective12 waypoint15)
(visible_from objective12 waypoint16)
(visible_from objective12 waypoint18)
(visible_from objective12 waypoint20)
(visible_from objective12 waypoint22)
(visible_from objective12 waypoint23)
(visible_from objective12 waypoint24)
(visible_from objective12 waypoint26)
(visible_from objective12 waypoint27)
(visible_from objective12 waypoint28)
(visible_from objective12 waypoint30)
(visible_from objective12 waypoint32)
(visible_from objective12 waypoint33)
(visible_from objective12 waypoint34)
(visible_from objective12 waypoint35)
(visible_from objective12 waypoint37)
(visible_from objective12 waypoint38)
(visible_from objective12 waypoint39)
(visible_from objective12 waypoint40)
(visible_from objective12 waypoint43)
(visible_from objective12 waypoint44)
(visible_from objective12 waypoint46)
(visible_from objective13 waypoint4)
(visible_from objective13 waypoint7)
(visible_from objective13 waypoint9)
(visible_from objective13 waypoint10)
(visible_from objective13 waypoint11)
(visible_from objective13 waypoint12)
(visible_from objective13 waypoint13)
(visible_from objective13 waypoint14)
(visible_from objective13 waypoint15)
(visible_from objective13 waypoint17)
(visible_from objective13 waypoint20)
(visible_from objective13 waypoint21)
(visible_from objective13 waypoint23)
(visible_from objective13 waypoint25)
(visible_from objective13 waypoint27)
(visible_from objective13 waypoint28)
(visible_from objective13 waypoint30)
(visible_from objective13 waypoint33)
(visible_from objective13 waypoint35)
(visible_from objective13 waypoint38)
(visible_from objective13 waypoint39)
(visible_from objective13 waypoint41)
(visible_from objective13 waypoint42)
(visible_from objective13 waypoint43)
(visible_from objective13 waypoint44)
(visible_from objective13 waypoint46)
(visible_from objective13 waypoint49)
(at_soil_sample waypoint1)
(at_rock_sample waypoint1)
(at_rock_sample waypoint3)
(at_rock_sample waypoint5)
(at_soil_sample waypoint7)
(at_rock_sample waypoint7)
(at_soil_sample waypoint8)
(at_rock_sample waypoint8)
(at_soil_sample waypoint9)
(at_rock_sample waypoint10)
(at_soil_sample waypoint11)
(at_soil_sample waypoint13)
(at_rock_sample waypoint13)
(at_rock_sample waypoint14)
(at_soil_sample waypoint15)
(at_rock_sample waypoint15)
(at_rock_sample waypoint17)
(at_soil_sample waypoint18)
(at_soil_sample waypoint19)
(at_soil_sample waypoint21)
(at_soil_sample waypoint23)
(at_rock_sample waypoint23)
(at_soil_sample waypoint25)
(at_soil_sample waypoint27)
(at_soil_sample waypoint29)
(at_rock_sample waypoint29)
(at_rock_sample waypoint30)
(at_rock_sample waypoint31)
(at_soil_sample waypoint32)
(at_rock_sample waypoint32)
(at_rock_sample waypoint33)
(at_rock_sample waypoint34)
(at_rock_sample waypoint35)
(at_soil_sample waypoint36)
(at_rock_sample waypoint36)
(at_soil_sample waypoint37)
(at_rock_sample waypoint37)
(at_rock_sample waypoint38)
(at_rock_sample waypoint39)
(at_soil_sample waypoint40)
(at_rock_sample waypoint40)
(at_soil_sample waypoint42)
(at_rock_sample waypoint42)
(at_soil_sample waypoint43)
(at_rock_sample waypoint43)
(at_soil_sample waypoint45)
(at_soil_sample waypoint46)
(at_rock_sample waypoint46)
(at_soil_sample waypoint47)
(at_rock_sample waypoint47)
(at_rock_sample waypoint48)
(channel_free general)
(available rover0)
(empty rover0store)
(at rover1 waypoint28)
(available rover1)
(empty rover1store)
(available rover2)
(empty rover2store)
(at rover0 waypoint1)
(at rover2 waypoint10)
(calibrated camera6 rover2)
(have_image rover2 objective1 colour)
)

(:goal (and
(communicated_soil_data waypoint47)
(communicated_soil_data waypoint25)
(communicated_soil_data waypoint7)
(communicated_soil_data waypoint29)
(communicated_rock_data waypoint29)
(communicated_rock_data waypoint17)
(communicated_rock_data waypoint39)
(communicated_rock_data waypoint14)
(communicated_rock_data waypoint13)
(communicated_image_data objective1 colour)
(communicated_image_data objective0 low_res)
(communicated_image_data objective1 low_res)
	)
)
)
