(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	satellite1 - satellite
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	satellite2 - satellite
	instrument4 - instrument
	instrument5 - instrument
	satellite3 - satellite
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	satellite4 - satellite
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	satellite5 - satellite
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	satellite6 - satellite
	instrument16 - instrument
	satellite7 - satellite
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	spectrograph2 - mode
	infrared3 - mode
	thermograph4 - mode
	spectrograph1 - mode
	spectrograph0 - mode
	GroundStation68 - direction
	GroundStation65 - direction
	Star81 - direction
	GroundStation46 - direction
	Star52 - direction
	Star11 - direction
	Star6 - direction
	GroundStation16 - direction
	GroundStation37 - direction
	GroundStation3 - direction
	GroundStation27 - direction
	GroundStation26 - direction
	GroundStation94 - direction
	GroundStation62 - direction
	Star19 - direction
	Star59 - direction
	GroundStation42 - direction
	Star73 - direction
	Star58 - direction
	GroundStation12 - direction
	Star39 - direction
	GroundStation14 - direction
	Star43 - direction
	Star60 - direction
	Star40 - direction
	Star92 - direction
	Star54 - direction
	GroundStation87 - direction
	Star10 - direction
	Star20 - direction
	Star97 - direction
	Star74 - direction
	GroundStation95 - direction
	GroundStation24 - direction
	GroundStation90 - direction
	GroundStation18 - direction
	Star1 - direction
	Star75 - direction
	Star29 - direction
	GroundStation93 - direction
	GroundStation17 - direction
	Star41 - direction
	Star91 - direction
	GroundStation76 - direction
	Star8 - direction
	Star86 - direction
	GroundStation51 - direction
	Star79 - direction
	Star47 - direction
	GroundStation88 - direction
	Star89 - direction
	Star30 - direction
	Star50 - direction
	GroundStation33 - direction
	Star45 - direction
	Star13 - direction
	GroundStation57 - direction
	Star7 - direction
	GroundStation67 - direction
	GroundStation44 - direction
	Star32 - direction
	GroundStation34 - direction
	GroundStation9 - direction
	GroundStation36 - direction
	GroundStation61 - direction
	GroundStation78 - direction
	Star53 - direction
	Star80 - direction
	GroundStation69 - direction
	Star72 - direction
	GroundStation64 - direction
	Star15 - direction
	GroundStation5 - direction
	Star82 - direction
	Star38 - direction
	Star85 - direction
	GroundStation22 - direction
	Star96 - direction
	Star71 - direction
	Star63 - direction
	GroundStation48 - direction
	Star77 - direction
	GroundStation21 - direction
	Star99 - direction
	GroundStation4 - direction
	Star25 - direction
	GroundStation49 - direction
	GroundStation2 - direction
	GroundStation83 - direction
	Star23 - direction
	Star70 - direction
	GroundStation84 - direction
	Star35 - direction
	Star56 - direction
	Star0 - direction
	GroundStation31 - direction
	Star98 - direction
	Star66 - direction
	GroundStation28 - direction
	Star55 - direction
	Planet100 - direction
	Planet101 - direction
	Star102 - direction
	Planet103 - direction
	Star104 - direction
	Phenomenon105 - direction
	Star106 - direction
	Planet107 - direction
	Planet108 - direction
	Phenomenon109 - direction
	Planet110 - direction
	Planet111 - direction
	Star112 - direction
	Phenomenon113 - direction
	Planet114 - direction
	Planet115 - direction
	Phenomenon116 - direction
	Star117 - direction
	Phenomenon118 - direction
	Planet119 - direction
	Phenomenon120 - direction
	Planet121 - direction
	Star122 - direction
	Planet123 - direction
	Phenomenon124 - direction
	Phenomenon125 - direction
	Star126 - direction
	Star127 - direction
	Planet128 - direction
	Planet129 - direction
	Phenomenon130 - direction
	Phenomenon131 - direction
	Planet132 - direction
	Phenomenon133 - direction
	Phenomenon134 - direction
	Phenomenon135 - direction
	Phenomenon136 - direction
	Planet137 - direction
	Star138 - direction
	Phenomenon139 - direction
	Planet140 - direction
	Phenomenon141 - direction
	Star142 - direction
	Phenomenon143 - direction
	Star144 - direction
	Star145 - direction
	Star146 - direction
	Star147 - direction
	Star148 - direction
	Planet149 - direction
	Phenomenon150 - direction
	Planet151 - direction
	Star152 - direction
	Star153 - direction
	Star154 - direction
	Star155 - direction
	Phenomenon156 - direction
	Star157 - direction
	Phenomenon158 - direction
	Phenomenon159 - direction
	Star160 - direction
	Phenomenon161 - direction
	Phenomenon162 - direction
	Planet163 - direction
	Planet164 - direction
	Phenomenon165 - direction
	Planet166 - direction
	Planet167 - direction
	Phenomenon168 - direction
	Star169 - direction
)
(:init
	(supports instrument0 spectrograph1)
	(calibration_target instrument0 Star98)
	(calibration_target instrument0 Star63)
	(calibration_target instrument0 Star75)
	(calibration_target instrument0 GroundStation51)
	(calibration_target instrument0 GroundStation21)
	(calibration_target instrument0 Star82)
	(calibration_target instrument0 GroundStation68)
	(calibration_target instrument0 Star71)
	(calibration_target instrument0 GroundStation31)
	(calibration_target instrument0 GroundStation18)
	(calibration_target instrument0 Star74)
	(calibration_target instrument0 GroundStation42)
	(calibration_target instrument0 GroundStation90)
	(calibration_target instrument0 GroundStation88)
	(calibration_target instrument0 GroundStation37)
	(calibration_target instrument0 GroundStation4)
	(calibration_target instrument0 Star39)
	(calibration_target instrument0 Star6)
	(calibration_target instrument0 Star45)
	(calibration_target instrument0 Star0)
	(on_board instrument0 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation44)
	(supports instrument1 spectrograph1)
	(supports instrument1 infrared3)
	(supports instrument1 spectrograph2)
	(calibration_target instrument1 Star59)
	(calibration_target instrument1 Star35)
	(calibration_target instrument1 Star39)
	(calibration_target instrument1 GroundStation42)
	(calibration_target instrument1 Star38)
	(calibration_target instrument1 Star55)
	(calibration_target instrument1 Star56)
	(calibration_target instrument1 Star54)
	(calibration_target instrument1 GroundStation83)
	(calibration_target instrument1 Star77)
	(calibration_target instrument1 GroundStation67)
	(calibration_target instrument1 GroundStation61)
	(calibration_target instrument1 GroundStation65)
	(calibration_target instrument1 Star20)
	(calibration_target instrument1 Star73)
	(calibration_target instrument1 Star29)
	(calibration_target instrument1 Star66)
	(calibration_target instrument1 GroundStation44)
	(calibration_target instrument1 Star40)
	(calibration_target instrument1 Star8)
	(supports instrument2 infrared3)
	(supports instrument2 spectrograph1)
	(calibration_target instrument2 Star73)
	(calibration_target instrument2 GroundStation64)
	(calibration_target instrument2 GroundStation26)
	(calibration_target instrument2 Star60)
	(calibration_target instrument2 Star63)
	(calibration_target instrument2 Star92)
	(calibration_target instrument2 GroundStation78)
	(calibration_target instrument2 GroundStation31)
	(calibration_target instrument2 Star70)
	(calibration_target instrument2 Star39)
	(calibration_target instrument2 Star11)
	(calibration_target instrument2 Star30)
	(calibration_target instrument2 Star35)
	(calibration_target instrument2 Star43)
	(calibration_target instrument2 GroundStation3)
	(calibration_target instrument2 Star56)
	(calibration_target instrument2 Star52)
	(calibration_target instrument2 GroundStation76)
	(calibration_target instrument2 GroundStation69)
	(calibration_target instrument2 GroundStation18)
	(calibration_target instrument2 Star6)
	(calibration_target instrument2 Star82)
	(calibration_target instrument2 GroundStation57)
	(calibration_target instrument2 GroundStation46)
	(calibration_target instrument2 Star91)
	(calibration_target instrument2 GroundStation87)
	(calibration_target instrument2 GroundStation4)
	(calibration_target instrument2 GroundStation83)
	(calibration_target instrument2 GroundStation22)
	(calibration_target instrument2 Star81)
	(calibration_target instrument2 Star29)
	(supports instrument3 spectrograph1)
	(supports instrument3 spectrograph0)
	(supports instrument3 spectrograph2)
	(calibration_target instrument3 Star39)
	(calibration_target instrument3 Star53)
	(calibration_target instrument3 Star59)
	(calibration_target instrument3 GroundStation78)
	(calibration_target instrument3 Star19)
	(calibration_target instrument3 GroundStation24)
	(calibration_target instrument3 GroundStation34)
	(calibration_target instrument3 Star60)
	(calibration_target instrument3 Star43)
	(calibration_target instrument3 GroundStation90)
	(calibration_target instrument3 GroundStation4)
	(on_board instrument1 satellite1)
	(on_board instrument2 satellite1)
	(on_board instrument3 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation67)
	(supports instrument4 infrared3)
	(supports instrument4 thermograph4)
	(supports instrument4 spectrograph2)
	(calibration_target instrument4 Star25)
	(calibration_target instrument4 Star99)
	(calibration_target instrument4 GroundStation16)
	(calibration_target instrument4 GroundStation93)
	(calibration_target instrument4 Star96)
	(calibration_target instrument4 Star53)
	(calibration_target instrument4 Star30)
	(calibration_target instrument4 Star15)
	(calibration_target instrument4 Star19)
	(calibration_target instrument4 Star39)
	(calibration_target instrument4 GroundStation9)
	(calibration_target instrument4 GroundStation69)
	(calibration_target instrument4 Star66)
	(calibration_target instrument4 GroundStation90)
	(calibration_target instrument4 Star6)
	(calibration_target instrument4 Star82)
	(calibration_target instrument4 Star79)
	(calibration_target instrument4 GroundStation51)
	(calibration_target instrument4 Star72)
	(calibration_target instrument4 GroundStation2)
	(calibration_target instrument4 Star23)
	(calibration_target instrument4 Star77)
	(calibration_target instrument4 Star1)
	(calibration_target instrument4 Star91)
	(calibration_target instrument4 Star20)
	(calibration_target instrument4 Star86)
	(calibration_target instrument4 GroundStation83)
	(calibration_target instrument4 Star70)
	(calibration_target instrument4 Star8)
	(calibration_target instrument4 Star43)
	(calibration_target instrument4 Star56)
	(calibration_target instrument4 GroundStation42)
	(supports instrument5 spectrograph2)
	(supports instrument5 spectrograph0)
	(supports instrument5 infrared3)
	(calibration_target instrument5 Star39)
	(calibration_target instrument5 Star73)
	(calibration_target instrument5 Star99)
	(calibration_target instrument5 Star59)
	(calibration_target instrument5 Star85)
	(calibration_target instrument5 GroundStation37)
	(calibration_target instrument5 GroundStation67)
	(calibration_target instrument5 GroundStation31)
	(on_board instrument4 satellite2)
	(on_board instrument5 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star144)
	(supports instrument6 spectrograph1)
	(calibration_target instrument6 Star50)
	(supports instrument7 spectrograph1)
	(calibration_target instrument7 GroundStation17)
	(calibration_target instrument7 Star60)
	(calibration_target instrument7 Star77)
	(calibration_target instrument7 Star79)
	(calibration_target instrument7 Star66)
	(calibration_target instrument7 Star50)
	(calibration_target instrument7 Star58)
	(calibration_target instrument7 GroundStation61)
	(calibration_target instrument7 Star98)
	(calibration_target instrument7 GroundStation26)
	(calibration_target instrument7 Star82)
	(calibration_target instrument7 Star73)
	(calibration_target instrument7 Star59)
	(calibration_target instrument7 GroundStation33)
	(calibration_target instrument7 Star35)
	(calibration_target instrument7 Star38)
	(calibration_target instrument7 GroundStation27)
	(calibration_target instrument7 GroundStation3)
	(calibration_target instrument7 GroundStation62)
	(calibration_target instrument7 GroundStation44)
	(calibration_target instrument7 Star23)
	(calibration_target instrument7 Star72)
	(calibration_target instrument7 Star19)
	(calibration_target instrument7 Star99)
	(supports instrument8 thermograph4)
	(calibration_target instrument8 Star35)
	(calibration_target instrument8 GroundStation62)
	(calibration_target instrument8 Star79)
	(calibration_target instrument8 GroundStation44)
	(calibration_target instrument8 GroundStation69)
	(on_board instrument6 satellite3)
	(on_board instrument7 satellite3)
	(on_board instrument8 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Phenomenon168)
	(supports instrument9 thermograph4)
	(supports instrument9 spectrograph2)
	(calibration_target instrument9 GroundStation2)
	(calibration_target instrument9 Star72)
	(calibration_target instrument9 GroundStation31)
	(calibration_target instrument9 Star40)
	(calibration_target instrument9 GroundStation18)
	(calibration_target instrument9 GroundStation90)
	(calibration_target instrument9 Star32)
	(supports instrument10 thermograph4)
	(calibration_target instrument10 GroundStation94)
	(calibration_target instrument10 Star82)
	(calibration_target instrument10 Star71)
	(calibration_target instrument10 Star45)
	(calibration_target instrument10 GroundStation67)
	(calibration_target instrument10 GroundStation90)
	(supports instrument11 infrared3)
	(calibration_target instrument11 Star13)
	(calibration_target instrument11 Star40)
	(calibration_target instrument11 GroundStation67)
	(calibration_target instrument11 GroundStation42)
	(calibration_target instrument11 GroundStation51)
	(calibration_target instrument11 GroundStation12)
	(calibration_target instrument11 Star72)
	(calibration_target instrument11 GroundStation21)
	(calibration_target instrument11 Star55)
	(calibration_target instrument11 GroundStation57)
	(calibration_target instrument11 Star59)
	(calibration_target instrument11 Star56)
	(calibration_target instrument11 Star91)
	(calibration_target instrument11 Star32)
	(calibration_target instrument11 GroundStation34)
	(calibration_target instrument11 Star19)
	(calibration_target instrument11 GroundStation28)
	(calibration_target instrument11 GroundStation88)
	(calibration_target instrument11 GroundStation62)
	(calibration_target instrument11 Star54)
	(calibration_target instrument11 GroundStation17)
	(calibration_target instrument11 Star66)
	(calibration_target instrument11 Star29)
	(on_board instrument9 satellite4)
	(on_board instrument10 satellite4)
	(on_board instrument11 satellite4)
	(power_avail satellite4)
	(pointing satellite4 GroundStation26)
	(supports instrument12 infrared3)
	(calibration_target instrument12 GroundStation14)
	(calibration_target instrument12 Star97)
	(calibration_target instrument12 Star77)
	(calibration_target instrument12 Star75)
	(calibration_target instrument12 Star39)
	(calibration_target instrument12 GroundStation78)
	(calibration_target instrument12 GroundStation83)
	(calibration_target instrument12 Star66)
	(calibration_target instrument12 GroundStation12)
	(calibration_target instrument12 GroundStation21)
	(calibration_target instrument12 GroundStation33)
	(calibration_target instrument12 Star58)
	(calibration_target instrument12 GroundStation93)
	(calibration_target instrument12 Star73)
	(calibration_target instrument12 Star23)
	(calibration_target instrument12 Star63)
	(calibration_target instrument12 GroundStation4)
	(calibration_target instrument12 Star32)
	(calibration_target instrument12 Star60)
	(calibration_target instrument12 GroundStation51)
	(calibration_target instrument12 GroundStation61)
	(supports instrument13 thermograph4)
	(calibration_target instrument13 GroundStation67)
	(calibration_target instrument13 Star75)
	(calibration_target instrument13 Star80)
	(calibration_target instrument13 GroundStation17)
	(calibration_target instrument13 GroundStation90)
	(calibration_target instrument13 Star10)
	(calibration_target instrument13 GroundStation64)
	(calibration_target instrument13 GroundStation87)
	(calibration_target instrument13 GroundStation28)
	(calibration_target instrument13 GroundStation51)
	(calibration_target instrument13 Star54)
	(calibration_target instrument13 Star92)
	(calibration_target instrument13 Star0)
	(calibration_target instrument13 GroundStation61)
	(calibration_target instrument13 Star97)
	(calibration_target instrument13 Star25)
	(calibration_target instrument13 GroundStation18)
	(calibration_target instrument13 Star40)
	(calibration_target instrument13 Star60)
	(calibration_target instrument13 GroundStation83)
	(calibration_target instrument13 Star91)
	(calibration_target instrument13 GroundStation88)
	(calibration_target instrument13 Star71)
	(calibration_target instrument13 GroundStation5)
	(calibration_target instrument13 GroundStation9)
	(calibration_target instrument13 Star43)
	(supports instrument14 spectrograph0)
	(supports instrument14 thermograph4)
	(supports instrument14 spectrograph1)
	(calibration_target instrument14 GroundStation49)
	(calibration_target instrument14 GroundStation18)
	(calibration_target instrument14 GroundStation28)
	(calibration_target instrument14 GroundStation90)
	(calibration_target instrument14 GroundStation24)
	(calibration_target instrument14 Star8)
	(calibration_target instrument14 Star91)
	(calibration_target instrument14 GroundStation4)
	(calibration_target instrument14 GroundStation95)
	(calibration_target instrument14 Star30)
	(calibration_target instrument14 Star74)
	(calibration_target instrument14 Star15)
	(calibration_target instrument14 Star97)
	(calibration_target instrument14 Star20)
	(supports instrument15 spectrograph2)
	(supports instrument15 spectrograph0)
	(calibration_target instrument15 Star8)
	(calibration_target instrument15 GroundStation61)
	(calibration_target instrument15 GroundStation9)
	(calibration_target instrument15 GroundStation76)
	(calibration_target instrument15 Star91)
	(calibration_target instrument15 GroundStation57)
	(calibration_target instrument15 Star25)
	(calibration_target instrument15 Star41)
	(calibration_target instrument15 GroundStation83)
	(calibration_target instrument15 GroundStation17)
	(calibration_target instrument15 Star99)
	(calibration_target instrument15 GroundStation93)
	(calibration_target instrument15 Star47)
	(calibration_target instrument15 Star29)
	(calibration_target instrument15 GroundStation5)
	(calibration_target instrument15 GroundStation33)
	(calibration_target instrument15 Star66)
	(calibration_target instrument15 Star75)
	(calibration_target instrument15 Star56)
	(calibration_target instrument15 Star38)
	(calibration_target instrument15 Star23)
	(calibration_target instrument15 GroundStation34)
	(calibration_target instrument15 Star1)
	(calibration_target instrument15 Star80)
	(on_board instrument12 satellite5)
	(on_board instrument13 satellite5)
	(on_board instrument14 satellite5)
	(on_board instrument15 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star148)
	(supports instrument16 spectrograph0)
	(supports instrument16 spectrograph1)
	(calibration_target instrument16 GroundStation49)
	(calibration_target instrument16 Star13)
	(calibration_target instrument16 Star45)
	(calibration_target instrument16 GroundStation33)
	(calibration_target instrument16 Star50)
	(calibration_target instrument16 Star30)
	(calibration_target instrument16 Star89)
	(calibration_target instrument16 GroundStation84)
	(calibration_target instrument16 GroundStation88)
	(calibration_target instrument16 Star7)
	(calibration_target instrument16 Star47)
	(calibration_target instrument16 Star70)
	(calibration_target instrument16 Star23)
	(calibration_target instrument16 Star25)
	(calibration_target instrument16 Star79)
	(calibration_target instrument16 GroundStation51)
	(calibration_target instrument16 Star63)
	(calibration_target instrument16 Star86)
	(calibration_target instrument16 Star8)
	(calibration_target instrument16 Star71)
	(calibration_target instrument16 GroundStation34)
	(on_board instrument16 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Phenomenon161)
	(supports instrument17 spectrograph0)
	(calibration_target instrument17 GroundStation22)
	(calibration_target instrument17 GroundStation34)
	(calibration_target instrument17 GroundStation78)
	(calibration_target instrument17 Star72)
	(calibration_target instrument17 Star32)
	(calibration_target instrument17 GroundStation64)
	(calibration_target instrument17 GroundStation44)
	(calibration_target instrument17 GroundStation67)
	(calibration_target instrument17 Star7)
	(calibration_target instrument17 GroundStation57)
	(calibration_target instrument17 Star77)
	(calibration_target instrument17 GroundStation83)
	(supports instrument18 spectrograph2)
	(supports instrument18 infrared3)
	(supports instrument18 spectrograph1)
	(calibration_target instrument18 GroundStation48)
	(calibration_target instrument18 Star63)
	(calibration_target instrument18 Star71)
	(calibration_target instrument18 GroundStation84)
	(calibration_target instrument18 Star96)
	(calibration_target instrument18 GroundStation22)
	(calibration_target instrument18 Star85)
	(calibration_target instrument18 Star38)
	(calibration_target instrument18 Star82)
	(calibration_target instrument18 GroundStation5)
	(calibration_target instrument18 Star15)
	(calibration_target instrument18 GroundStation64)
	(calibration_target instrument18 Star72)
	(calibration_target instrument18 GroundStation69)
	(calibration_target instrument18 Star80)
	(calibration_target instrument18 Star53)
	(calibration_target instrument18 GroundStation78)
	(calibration_target instrument18 GroundStation61)
	(calibration_target instrument18 GroundStation36)
	(calibration_target instrument18 Star77)
	(calibration_target instrument18 GroundStation83)
	(calibration_target instrument18 GroundStation9)
	(supports instrument19 spectrograph1)
	(supports instrument19 spectrograph0)
	(calibration_target instrument19 Star55)
	(calibration_target instrument19 GroundStation28)
	(calibration_target instrument19 Star66)
	(calibration_target instrument19 Star98)
	(calibration_target instrument19 GroundStation31)
	(calibration_target instrument19 Star0)
	(calibration_target instrument19 Star56)
	(calibration_target instrument19 Star35)
	(calibration_target instrument19 GroundStation84)
	(calibration_target instrument19 Star70)
	(calibration_target instrument19 Star23)
	(calibration_target instrument19 GroundStation83)
	(calibration_target instrument19 GroundStation2)
	(calibration_target instrument19 GroundStation49)
	(calibration_target instrument19 Star25)
	(calibration_target instrument19 GroundStation4)
	(calibration_target instrument19 Star99)
	(calibration_target instrument19 GroundStation21)
	(calibration_target instrument19 Star77)
	(on_board instrument17 satellite7)
	(on_board instrument18 satellite7)
	(on_board instrument19 satellite7)
	(power_avail satellite7)
	(pointing satellite7 GroundStation24)
)
(:goal (and
	(pointing satellite3 Phenomenon118)
	(pointing satellite6 Star50)
	(pointing satellite7 Phenomenon130)
	(have_image Planet100 thermograph4)
	(have_image Planet101 spectrograph0)
	(have_image Star102 spectrograph1)
	(have_image Planet103 thermograph4)
	(have_image Star104 spectrograph0)
	(have_image Phenomenon105 infrared3)
	(have_image Star106 thermograph4)
	(have_image Planet107 thermograph4)
	(have_image Planet108 spectrograph0)
	(have_image Phenomenon109 thermograph4)
	(have_image Planet110 thermograph4)
	(have_image Planet111 spectrograph1)
	(have_image Star112 spectrograph0)
	(have_image Phenomenon113 thermograph4)
	(have_image Planet114 spectrograph2)
	(have_image Planet115 spectrograph2)
	(have_image Phenomenon116 spectrograph0)
	(have_image Star117 spectrograph0)
	(have_image Phenomenon118 spectrograph2)
	(have_image Planet119 thermograph4)
	(have_image Phenomenon120 spectrograph1)
	(have_image Planet121 spectrograph1)
	(have_image Star122 thermograph4)
	(have_image Planet123 spectrograph2)
	(have_image Phenomenon124 thermograph4)
	(have_image Phenomenon125 infrared3)
	(have_image Star126 spectrograph0)
	(have_image Star127 spectrograph2)
	(have_image Planet128 spectrograph2)
	(have_image Planet129 thermograph4)
	(have_image Phenomenon130 thermograph4)
	(have_image Phenomenon131 spectrograph0)
	(have_image Planet132 infrared3)
	(have_image Phenomenon133 thermograph4)
	(have_image Phenomenon134 spectrograph0)
	(have_image Phenomenon135 spectrograph0)
	(have_image Phenomenon136 spectrograph0)
	(have_image Planet137 infrared3)
	(have_image Star138 thermograph4)
	(have_image Phenomenon139 spectrograph0)
	(have_image Planet140 thermograph4)
	(have_image Phenomenon141 spectrograph2)
	(have_image Star142 thermograph4)
	(have_image Phenomenon143 thermograph4)
	(have_image Star144 spectrograph0)
	(have_image Star145 infrared3)
	(have_image Star146 infrared3)
	(have_image Star147 spectrograph1)
	(have_image Star148 infrared3)
	(have_image Planet149 infrared3)
	(have_image Phenomenon150 spectrograph2)
	(have_image Planet151 spectrograph1)
	(have_image Star152 thermograph4)
	(have_image Star153 spectrograph1)
	(have_image Star154 spectrograph0)
	(have_image Star155 spectrograph2)
	(have_image Phenomenon156 thermograph4)
	(have_image Star157 spectrograph2)
	(have_image Phenomenon158 spectrograph2)
	(have_image Phenomenon159 thermograph4)
	(have_image Star160 spectrograph2)
	(have_image Phenomenon161 thermograph4)
	(have_image Phenomenon162 thermograph4)
	(have_image Planet163 spectrograph1)
	(have_image Planet164 spectrograph0)
	(have_image Phenomenon165 spectrograph2)
	(have_image Planet166 spectrograph1)
	(have_image Planet167 spectrograph1)
	(have_image Phenomenon168 spectrograph2)
	(have_image Star169 infrared3)
))

)
