(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	satellite1 - satellite
	instrument3 - instrument
	instrument4 - instrument
	satellite2 - satellite
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	satellite3 - satellite
	instrument10 - instrument
	instrument11 - instrument
	satellite4 - satellite
	instrument12 - instrument
	instrument13 - instrument
	satellite5 - satellite
	instrument14 - instrument
	instrument15 - instrument
	satellite6 - satellite
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	satellite7 - satellite
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	spectrograph0 - mode
	image3 - mode
	infrared1 - mode
	image4 - mode
	image2 - mode
	Star93 - direction
	GroundStation34 - direction
	GroundStation11 - direction
	GroundStation61 - direction
	Star82 - direction
	GroundStation72 - direction
	GroundStation38 - direction
	GroundStation84 - direction
	Star99 - direction
	Star18 - direction
	GroundStation96 - direction
	GroundStation66 - direction
	GroundStation92 - direction
	GroundStation75 - direction
	GroundStation21 - direction
	GroundStation49 - direction
	GroundStation20 - direction
	Star14 - direction
	Star48 - direction
	Star8 - direction
	Star6 - direction
	Star43 - direction
	GroundStation89 - direction
	Star88 - direction
	GroundStation83 - direction
	Star70 - direction
	GroundStation62 - direction
	Star26 - direction
	Star5 - direction
	GroundStation4 - direction
	Star17 - direction
	Star51 - direction
	Star85 - direction
	GroundStation16 - direction
	Star86 - direction
	GroundStation53 - direction
	Star12 - direction
	GroundStation32 - direction
	Star73 - direction
	Star36 - direction
	Star63 - direction
	Star60 - direction
	GroundStation52 - direction
	GroundStation23 - direction
	GroundStation33 - direction
	GroundStation27 - direction
	Star55 - direction
	Star87 - direction
	GroundStation41 - direction
	GroundStation39 - direction
	Star15 - direction
	GroundStation31 - direction
	Star44 - direction
	GroundStation57 - direction
	GroundStation97 - direction
	GroundStation78 - direction
	GroundStation25 - direction
	Star3 - direction
	Star47 - direction
	Star40 - direction
	GroundStation81 - direction
	GroundStation74 - direction
	GroundStation65 - direction
	Star77 - direction
	Star56 - direction
	Star37 - direction
	Star29 - direction
	Star71 - direction
	GroundStation94 - direction
	GroundStation9 - direction
	GroundStation10 - direction
	GroundStation54 - direction
	GroundStation35 - direction
	Star24 - direction
	GroundStation64 - direction
	GroundStation2 - direction
	GroundStation1 - direction
	Star79 - direction
	Star90 - direction
	Star46 - direction
	GroundStation67 - direction
	Star42 - direction
	GroundStation22 - direction
	Star95 - direction
	Star50 - direction
	Star0 - direction
	GroundStation76 - direction
	Star69 - direction
	Star13 - direction
	Star7 - direction
	Star59 - direction
	GroundStation91 - direction
	GroundStation68 - direction
	Star98 - direction
	GroundStation80 - direction
	Star30 - direction
	Star45 - direction
	GroundStation28 - direction
	GroundStation58 - direction
	GroundStation19 - direction
	Planet100 - direction
	Star101 - direction
	Planet102 - direction
	Star103 - direction
	Star104 - direction
	Planet105 - direction
	Star106 - direction
	Star107 - direction
	Phenomenon108 - direction
	Phenomenon109 - direction
	Star110 - direction
	Phenomenon111 - direction
	Phenomenon112 - direction
	Planet113 - direction
	Planet114 - direction
	Planet115 - direction
	Phenomenon116 - direction
	Planet117 - direction
	Star118 - direction
	Planet119 - direction
	Phenomenon120 - direction
	Star121 - direction
	Star122 - direction
	Planet123 - direction
	Planet124 - direction
	Phenomenon125 - direction
	Star126 - direction
	Planet127 - direction
	Planet128 - direction
	Planet129 - direction
	Phenomenon130 - direction
	Phenomenon131 - direction
	Planet132 - direction
	Star133 - direction
	Phenomenon134 - direction
	Planet135 - direction
	Phenomenon136 - direction
	Star137 - direction
	Planet138 - direction
	Phenomenon139 - direction
	Star140 - direction
	Star141 - direction
	Phenomenon142 - direction
	Star143 - direction
	Phenomenon144 - direction
	Star145 - direction
	Star146 - direction
	Phenomenon147 - direction
	Star148 - direction
	Planet149 - direction
	Planet150 - direction
	Planet151 - direction
	Star152 - direction
	Phenomenon153 - direction
	Star154 - direction
	Star155 - direction
	Phenomenon156 - direction
	Planet157 - direction
	Star158 - direction
	Planet159 - direction
	Star160 - direction
	Phenomenon161 - direction
	Planet162 - direction
	Planet163 - direction
	Star164 - direction
	Star165 - direction
	Star166 - direction
	Phenomenon167 - direction
	Planet168 - direction
	Planet169 - direction
)
(:init
	(supports instrument0 spectrograph0)
	(calibration_target instrument0 Star44)
	(calibration_target instrument0 Star5)
	(calibration_target instrument0 Star14)
	(calibration_target instrument0 GroundStation25)
	(calibration_target instrument0 Star90)
	(calibration_target instrument0 Star29)
	(calibration_target instrument0 Star37)
	(calibration_target instrument0 GroundStation2)
	(calibration_target instrument0 Star70)
	(calibration_target instrument0 Star82)
	(calibration_target instrument0 Star95)
	(calibration_target instrument0 Star24)
	(calibration_target instrument0 GroundStation92)
	(calibration_target instrument0 Star73)
	(calibration_target instrument0 GroundStation65)
	(calibration_target instrument0 GroundStation74)
	(calibration_target instrument0 GroundStation78)
	(calibration_target instrument0 GroundStation62)
	(calibration_target instrument0 GroundStation75)
	(calibration_target instrument0 GroundStation27)
	(calibration_target instrument0 Star71)
	(calibration_target instrument0 Star40)
	(calibration_target instrument0 Star15)
	(supports instrument1 image4)
	(supports instrument1 image3)
	(calibration_target instrument1 Star44)
	(calibration_target instrument1 Star99)
	(calibration_target instrument1 Star79)
	(calibration_target instrument1 Star18)
	(calibration_target instrument1 Star45)
	(calibration_target instrument1 Star93)
	(calibration_target instrument1 Star37)
	(supports instrument2 image3)
	(calibration_target instrument2 Star7)
	(calibration_target instrument2 Star98)
	(calibration_target instrument2 Star30)
	(calibration_target instrument2 GroundStation67)
	(calibration_target instrument2 Star60)
	(calibration_target instrument2 Star51)
	(calibration_target instrument2 GroundStation32)
	(calibration_target instrument2 GroundStation21)
	(calibration_target instrument2 Star43)
	(calibration_target instrument2 Star85)
	(calibration_target instrument2 Star86)
	(calibration_target instrument2 Star3)
	(calibration_target instrument2 GroundStation91)
	(calibration_target instrument2 Star24)
	(calibration_target instrument2 GroundStation1)
	(calibration_target instrument2 Star56)
	(calibration_target instrument2 GroundStation57)
	(calibration_target instrument2 GroundStation23)
	(calibration_target instrument2 GroundStation74)
	(calibration_target instrument2 GroundStation20)
	(calibration_target instrument2 GroundStation16)
	(calibration_target instrument2 Star44)
	(calibration_target instrument2 Star77)
	(calibration_target instrument2 Star45)
	(calibration_target instrument2 Star63)
	(calibration_target instrument2 Star46)
	(calibration_target instrument2 GroundStation19)
	(calibration_target instrument2 Star36)
	(calibration_target instrument2 Star87)
	(calibration_target instrument2 Star5)
	(calibration_target instrument2 GroundStation34)
	(calibration_target instrument2 GroundStation96)
	(calibration_target instrument2 GroundStation89)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Phenomenon161)
	(supports instrument3 spectrograph0)
	(calibration_target instrument3 Star15)
	(calibration_target instrument3 Star14)
	(supports instrument4 image4)
	(supports instrument4 infrared1)
	(calibration_target instrument4 GroundStation53)
	(calibration_target instrument4 Star5)
	(calibration_target instrument4 Star73)
	(calibration_target instrument4 GroundStation83)
	(calibration_target instrument4 GroundStation52)
	(calibration_target instrument4 GroundStation9)
	(calibration_target instrument4 GroundStation28)
	(calibration_target instrument4 Star77)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star7)
	(supports instrument5 image2)
	(supports instrument5 image3)
	(supports instrument5 infrared1)
	(calibration_target instrument5 GroundStation96)
	(calibration_target instrument5 GroundStation67)
	(calibration_target instrument5 GroundStation16)
	(calibration_target instrument5 Star30)
	(calibration_target instrument5 Star90)
	(calibration_target instrument5 GroundStation49)
	(calibration_target instrument5 Star59)
	(calibration_target instrument5 Star3)
	(calibration_target instrument5 GroundStation61)
	(calibration_target instrument5 GroundStation94)
	(calibration_target instrument5 Star29)
	(calibration_target instrument5 GroundStation11)
	(calibration_target instrument5 Star98)
	(calibration_target instrument5 GroundStation97)
	(calibration_target instrument5 Star6)
	(calibration_target instrument5 Star14)
	(supports instrument6 image4)
	(supports instrument6 image3)
	(supports instrument6 spectrograph0)
	(calibration_target instrument6 Star98)
	(calibration_target instrument6 GroundStation10)
	(calibration_target instrument6 GroundStation53)
	(calibration_target instrument6 GroundStation72)
	(calibration_target instrument6 Star63)
	(calibration_target instrument6 GroundStation94)
	(calibration_target instrument6 GroundStation38)
	(calibration_target instrument6 Star90)
	(calibration_target instrument6 Star3)
	(calibration_target instrument6 Star0)
	(calibration_target instrument6 Star82)
	(calibration_target instrument6 GroundStation61)
	(calibration_target instrument6 GroundStation52)
	(calibration_target instrument6 GroundStation2)
	(calibration_target instrument6 GroundStation4)
	(calibration_target instrument6 Star87)
	(calibration_target instrument6 GroundStation92)
	(calibration_target instrument6 GroundStation25)
	(calibration_target instrument6 GroundStation91)
	(calibration_target instrument6 GroundStation62)
	(supports instrument7 spectrograph0)
	(calibration_target instrument7 Star98)
	(calibration_target instrument7 GroundStation52)
	(supports instrument8 image3)
	(calibration_target instrument8 Star73)
	(calibration_target instrument8 GroundStation54)
	(calibration_target instrument8 GroundStation31)
	(calibration_target instrument8 Star69)
	(calibration_target instrument8 Star5)
	(calibration_target instrument8 GroundStation21)
	(calibration_target instrument8 GroundStation20)
	(supports instrument9 infrared1)
	(calibration_target instrument9 Star99)
	(calibration_target instrument9 GroundStation65)
	(calibration_target instrument9 GroundStation20)
	(calibration_target instrument9 Star56)
	(calibration_target instrument9 GroundStation23)
	(calibration_target instrument9 Star79)
	(calibration_target instrument9 Star43)
	(calibration_target instrument9 GroundStation74)
	(calibration_target instrument9 GroundStation84)
	(calibration_target instrument9 Star15)
	(calibration_target instrument9 GroundStation31)
	(calibration_target instrument9 Star7)
	(calibration_target instrument9 Star13)
	(calibration_target instrument9 GroundStation64)
	(calibration_target instrument9 GroundStation81)
	(calibration_target instrument9 GroundStation66)
	(calibration_target instrument9 Star71)
	(calibration_target instrument9 GroundStation57)
	(calibration_target instrument9 GroundStation94)
	(calibration_target instrument9 Star0)
	(calibration_target instrument9 GroundStation53)
	(calibration_target instrument9 GroundStation25)
	(calibration_target instrument9 GroundStation27)
	(calibration_target instrument9 Star40)
	(calibration_target instrument9 GroundStation41)
	(calibration_target instrument9 Star55)
	(calibration_target instrument9 Star46)
	(calibration_target instrument9 Star5)
	(calibration_target instrument9 GroundStation89)
	(calibration_target instrument9 GroundStation28)
	(calibration_target instrument9 GroundStation38)
	(on_board instrument5 satellite2)
	(on_board instrument6 satellite2)
	(on_board instrument7 satellite2)
	(on_board instrument8 satellite2)
	(on_board instrument9 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star17)
	(supports instrument10 image4)
	(supports instrument10 image3)
	(calibration_target instrument10 Star85)
	(calibration_target instrument10 GroundStation53)
	(calibration_target instrument10 GroundStation76)
	(calibration_target instrument10 GroundStation91)
	(calibration_target instrument10 Star18)
	(calibration_target instrument10 GroundStation1)
	(calibration_target instrument10 Star48)
	(calibration_target instrument10 GroundStation2)
	(calibration_target instrument10 GroundStation19)
	(supports instrument11 image4)
	(calibration_target instrument11 GroundStation41)
	(calibration_target instrument11 Star55)
	(on_board instrument10 satellite3)
	(on_board instrument11 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation62)
	(supports instrument12 infrared1)
	(calibration_target instrument12 Star3)
	(calibration_target instrument12 GroundStation94)
	(calibration_target instrument12 GroundStation91)
	(calibration_target instrument12 Star26)
	(calibration_target instrument12 GroundStation76)
	(calibration_target instrument12 GroundStation10)
	(calibration_target instrument12 GroundStation89)
	(calibration_target instrument12 GroundStation16)
	(calibration_target instrument12 GroundStation2)
	(calibration_target instrument12 Star29)
	(calibration_target instrument12 Star60)
	(calibration_target instrument12 GroundStation49)
	(calibration_target instrument12 Star86)
	(calibration_target instrument12 Star48)
	(calibration_target instrument12 GroundStation21)
	(calibration_target instrument12 GroundStation75)
	(calibration_target instrument12 Star85)
	(calibration_target instrument12 Star36)
	(calibration_target instrument12 Star43)
	(calibration_target instrument12 GroundStation28)
	(calibration_target instrument12 GroundStation57)
	(calibration_target instrument12 GroundStation92)
	(calibration_target instrument12 Star98)
	(calibration_target instrument12 GroundStation66)
	(calibration_target instrument12 GroundStation96)
	(calibration_target instrument12 GroundStation35)
	(calibration_target instrument12 GroundStation41)
	(calibration_target instrument12 GroundStation31)
	(supports instrument13 image4)
	(supports instrument13 infrared1)
	(supports instrument13 spectrograph0)
	(calibration_target instrument13 GroundStation23)
	(calibration_target instrument13 Star45)
	(calibration_target instrument13 GroundStation83)
	(calibration_target instrument13 Star24)
	(calibration_target instrument13 GroundStation58)
	(calibration_target instrument13 GroundStation62)
	(on_board instrument12 satellite4)
	(on_board instrument13 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Phenomenon167)
	(supports instrument14 image3)
	(supports instrument14 image2)
	(calibration_target instrument14 GroundStation97)
	(calibration_target instrument14 Star45)
	(calibration_target instrument14 GroundStation27)
	(calibration_target instrument14 Star14)
	(calibration_target instrument14 GroundStation57)
	(calibration_target instrument14 Star40)
	(calibration_target instrument14 GroundStation20)
	(calibration_target instrument14 GroundStation76)
	(calibration_target instrument14 Star42)
	(supports instrument15 image3)
	(calibration_target instrument15 GroundStation57)
	(calibration_target instrument15 GroundStation9)
	(calibration_target instrument15 GroundStation16)
	(calibration_target instrument15 Star6)
	(calibration_target instrument15 Star30)
	(calibration_target instrument15 Star8)
	(calibration_target instrument15 Star48)
	(calibration_target instrument15 GroundStation53)
	(calibration_target instrument15 Star59)
	(calibration_target instrument15 GroundStation97)
	(calibration_target instrument15 GroundStation94)
	(calibration_target instrument15 Star77)
	(calibration_target instrument15 GroundStation64)
	(calibration_target instrument15 GroundStation80)
	(calibration_target instrument15 Star40)
	(calibration_target instrument15 GroundStation58)
	(calibration_target instrument15 Star98)
	(calibration_target instrument15 Star26)
	(calibration_target instrument15 Star14)
	(calibration_target instrument15 Star71)
	(calibration_target instrument15 Star12)
	(calibration_target instrument15 Star87)
	(calibration_target instrument15 GroundStation52)
	(calibration_target instrument15 Star15)
	(calibration_target instrument15 Star3)
	(calibration_target instrument15 GroundStation89)
	(calibration_target instrument15 Star85)
	(calibration_target instrument15 Star24)
	(calibration_target instrument15 GroundStation20)
	(calibration_target instrument15 Star55)
	(on_board instrument14 satellite5)
	(on_board instrument15 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star158)
	(supports instrument16 image3)
	(calibration_target instrument16 GroundStation16)
	(calibration_target instrument16 Star24)
	(calibration_target instrument16 GroundStation94)
	(calibration_target instrument16 GroundStation22)
	(calibration_target instrument16 Star88)
	(calibration_target instrument16 Star43)
	(calibration_target instrument16 Star17)
	(calibration_target instrument16 Star46)
	(calibration_target instrument16 Star98)
	(calibration_target instrument16 GroundStation58)
	(calibration_target instrument16 GroundStation35)
	(calibration_target instrument16 Star29)
	(supports instrument17 image3)
	(supports instrument17 infrared1)
	(calibration_target instrument17 GroundStation67)
	(calibration_target instrument17 Star51)
	(supports instrument18 image4)
	(supports instrument18 spectrograph0)
	(supports instrument18 image3)
	(calibration_target instrument18 GroundStation4)
	(calibration_target instrument18 Star5)
	(calibration_target instrument18 Star87)
	(calibration_target instrument18 GroundStation67)
	(calibration_target instrument18 Star26)
	(calibration_target instrument18 Star13)
	(calibration_target instrument18 GroundStation52)
	(calibration_target instrument18 Star85)
	(calibration_target instrument18 GroundStation94)
	(calibration_target instrument18 Star12)
	(calibration_target instrument18 GroundStation35)
	(calibration_target instrument18 GroundStation62)
	(calibration_target instrument18 Star59)
	(calibration_target instrument18 GroundStation74)
	(calibration_target instrument18 Star70)
	(calibration_target instrument18 GroundStation83)
	(calibration_target instrument18 GroundStation64)
	(calibration_target instrument18 GroundStation31)
	(calibration_target instrument18 Star88)
	(calibration_target instrument18 GroundStation80)
	(calibration_target instrument18 Star3)
	(calibration_target instrument18 GroundStation16)
	(calibration_target instrument18 GroundStation58)
	(calibration_target instrument18 Star30)
	(calibration_target instrument18 GroundStation65)
	(calibration_target instrument18 Star47)
	(calibration_target instrument18 GroundStation89)
	(calibration_target instrument18 GroundStation27)
	(supports instrument19 spectrograph0)
	(supports instrument19 image2)
	(supports instrument19 infrared1)
	(calibration_target instrument19 GroundStation53)
	(calibration_target instrument19 Star86)
	(calibration_target instrument19 GroundStation1)
	(calibration_target instrument19 GroundStation16)
	(calibration_target instrument19 GroundStation27)
	(calibration_target instrument19 Star85)
	(calibration_target instrument19 GroundStation81)
	(calibration_target instrument19 Star51)
	(calibration_target instrument19 Star69)
	(calibration_target instrument19 Star46)
	(calibration_target instrument19 Star60)
	(calibration_target instrument19 GroundStation41)
	(calibration_target instrument19 Star17)
	(calibration_target instrument19 GroundStation52)
	(on_board instrument16 satellite6)
	(on_board instrument17 satellite6)
	(on_board instrument18 satellite6)
	(on_board instrument19 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Planet169)
	(supports instrument20 spectrograph0)
	(calibration_target instrument20 GroundStation35)
	(calibration_target instrument20 GroundStation32)
	(calibration_target instrument20 Star12)
	(calibration_target instrument20 Star0)
	(supports instrument21 image3)
	(calibration_target instrument21 Star71)
	(calibration_target instrument21 Star63)
	(calibration_target instrument21 Star36)
	(calibration_target instrument21 GroundStation27)
	(calibration_target instrument21 Star73)
	(calibration_target instrument21 Star79)
	(calibration_target instrument21 Star55)
	(calibration_target instrument21 Star47)
	(calibration_target instrument21 GroundStation78)
	(calibration_target instrument21 GroundStation64)
	(supports instrument22 infrared1)
	(calibration_target instrument22 Star42)
	(calibration_target instrument22 GroundStation1)
	(calibration_target instrument22 Star45)
	(calibration_target instrument22 GroundStation57)
	(calibration_target instrument22 Star44)
	(calibration_target instrument22 Star3)
	(calibration_target instrument22 GroundStation31)
	(calibration_target instrument22 Star15)
	(calibration_target instrument22 GroundStation39)
	(calibration_target instrument22 GroundStation41)
	(calibration_target instrument22 Star87)
	(calibration_target instrument22 Star55)
	(calibration_target instrument22 GroundStation78)
	(calibration_target instrument22 GroundStation64)
	(calibration_target instrument22 GroundStation2)
	(calibration_target instrument22 Star98)
	(calibration_target instrument22 GroundStation27)
	(calibration_target instrument22 GroundStation33)
	(calibration_target instrument22 GroundStation58)
	(calibration_target instrument22 Star47)
	(calibration_target instrument22 GroundStation23)
	(calibration_target instrument22 GroundStation52)
	(calibration_target instrument22 GroundStation19)
	(calibration_target instrument22 GroundStation67)
	(calibration_target instrument22 Star60)
	(calibration_target instrument22 Star30)
	(calibration_target instrument22 Star71)
	(calibration_target instrument22 Star0)
	(calibration_target instrument22 Star13)
	(calibration_target instrument22 GroundStation91)
	(supports instrument23 image4)
	(supports instrument23 infrared1)
	(calibration_target instrument23 GroundStation10)
	(calibration_target instrument23 GroundStation9)
	(calibration_target instrument23 GroundStation1)
	(calibration_target instrument23 Star42)
	(calibration_target instrument23 GroundStation94)
	(calibration_target instrument23 Star79)
	(calibration_target instrument23 Star71)
	(calibration_target instrument23 Star29)
	(calibration_target instrument23 Star37)
	(calibration_target instrument23 Star24)
	(calibration_target instrument23 Star56)
	(calibration_target instrument23 Star77)
	(calibration_target instrument23 GroundStation65)
	(calibration_target instrument23 GroundStation74)
	(calibration_target instrument23 GroundStation81)
	(calibration_target instrument23 GroundStation80)
	(calibration_target instrument23 Star40)
	(calibration_target instrument23 GroundStation67)
	(calibration_target instrument23 Star47)
	(calibration_target instrument23 Star3)
	(calibration_target instrument23 GroundStation25)
	(calibration_target instrument23 GroundStation78)
	(calibration_target instrument23 GroundStation97)
	(supports instrument24 image4)
	(supports instrument24 spectrograph0)
	(supports instrument24 infrared1)
	(calibration_target instrument24 GroundStation19)
	(calibration_target instrument24 GroundStation58)
	(calibration_target instrument24 GroundStation28)
	(calibration_target instrument24 Star45)
	(calibration_target instrument24 Star30)
	(calibration_target instrument24 GroundStation80)
	(calibration_target instrument24 Star98)
	(calibration_target instrument24 GroundStation68)
	(calibration_target instrument24 GroundStation91)
	(calibration_target instrument24 Star59)
	(calibration_target instrument24 Star7)
	(calibration_target instrument24 Star13)
	(calibration_target instrument24 Star69)
	(calibration_target instrument24 GroundStation76)
	(calibration_target instrument24 Star0)
	(calibration_target instrument24 Star50)
	(calibration_target instrument24 Star95)
	(calibration_target instrument24 GroundStation22)
	(calibration_target instrument24 Star42)
	(calibration_target instrument24 GroundStation67)
	(calibration_target instrument24 Star46)
	(calibration_target instrument24 Star90)
	(calibration_target instrument24 Star79)
	(calibration_target instrument24 GroundStation1)
	(calibration_target instrument24 GroundStation2)
	(calibration_target instrument24 GroundStation64)
	(calibration_target instrument24 Star24)
	(calibration_target instrument24 GroundStation35)
	(calibration_target instrument24 GroundStation54)
	(on_board instrument20 satellite7)
	(on_board instrument21 satellite7)
	(on_board instrument22 satellite7)
	(on_board instrument23 satellite7)
	(on_board instrument24 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star51)
)
(:goal (and
	(pointing satellite1 Phenomenon134)
	(pointing satellite2 Star165)
	(pointing satellite5 Star26)
	(pointing satellite7 Planet105)
	(have_image Planet100 image4)
	(have_image Star101 infrared1)
	(have_image Planet102 image3)
	(have_image Star103 image3)
	(have_image Star104 infrared1)
	(have_image Planet105 image2)
	(have_image Star106 infrared1)
	(have_image Star107 infrared1)
	(have_image Phenomenon108 image4)
	(have_image Phenomenon109 spectrograph0)
	(have_image Star110 image4)
	(have_image Phenomenon111 image3)
	(have_image Phenomenon112 infrared1)
	(have_image Planet113 image2)
	(have_image Planet114 image2)
	(have_image Planet115 image3)
	(have_image Phenomenon116 image3)
	(have_image Planet117 image2)
	(have_image Star118 image4)
	(have_image Planet119 image3)
	(have_image Phenomenon120 image3)
	(have_image Star121 infrared1)
	(have_image Star122 infrared1)
	(have_image Planet123 spectrograph0)
	(have_image Planet124 image2)
	(have_image Phenomenon125 image4)
	(have_image Star126 spectrograph0)
	(have_image Planet127 image3)
	(have_image Planet128 image3)
	(have_image Planet129 image3)
	(have_image Phenomenon130 spectrograph0)
	(have_image Phenomenon131 image3)
	(have_image Planet132 image4)
	(have_image Star133 image4)
	(have_image Phenomenon134 image2)
	(have_image Planet135 image4)
	(have_image Phenomenon136 infrared1)
	(have_image Star137 infrared1)
	(have_image Planet138 image4)
	(have_image Phenomenon139 image2)
	(have_image Star140 image2)
	(have_image Star141 image4)
	(have_image Phenomenon142 spectrograph0)
	(have_image Star143 image4)
	(have_image Phenomenon144 spectrograph0)
	(have_image Star145 image3)
	(have_image Star146 infrared1)
	(have_image Phenomenon147 image2)
	(have_image Star148 image3)
	(have_image Planet149 infrared1)
	(have_image Planet150 infrared1)
	(have_image Planet151 image3)
	(have_image Star152 image3)
	(have_image Phenomenon153 image4)
	(have_image Star154 image4)
	(have_image Star155 infrared1)
	(have_image Phenomenon156 image2)
	(have_image Planet157 spectrograph0)
	(have_image Star158 image2)
	(have_image Planet159 image2)
	(have_image Star160 image3)
	(have_image Phenomenon161 spectrograph0)
	(have_image Planet162 image3)
	(have_image Planet163 spectrograph0)
	(have_image Star164 image2)
	(have_image Star165 image4)
	(have_image Star166 infrared1)
	(have_image Phenomenon167 image4)
	(have_image Planet168 image4)
	(have_image Planet169 image4)
))

)
