(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	satellite1 - satellite
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	satellite2 - satellite
	instrument8 - instrument
	satellite3 - satellite
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	satellite4 - satellite
	instrument12 - instrument
	instrument13 - instrument
	satellite5 - satellite
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	satellite6 - satellite
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	satellite7 - satellite
	instrument20 - instrument
	instrument21 - instrument
	thermograph2 - mode
	image0 - mode
	infrared3 - mode
	thermograph1 - mode
	thermograph4 - mode
	Star2 - direction
	Star30 - direction
	GroundStation49 - direction
	Star58 - direction
	GroundStation89 - direction
	Star9 - direction
	GroundStation78 - direction
	Star95 - direction
	GroundStation73 - direction
	Star84 - direction
	GroundStation53 - direction
	GroundStation83 - direction
	GroundStation94 - direction
	GroundStation1 - direction
	GroundStation63 - direction
	Star62 - direction
	Star19 - direction
	Star5 - direction
	GroundStation39 - direction
	GroundStation45 - direction
	Star28 - direction
	Star80 - direction
	Star36 - direction
	Star20 - direction
	Star71 - direction
	GroundStation18 - direction
	Star59 - direction
	GroundStation44 - direction
	GroundStation56 - direction
	GroundStation87 - direction
	Star40 - direction
	GroundStation68 - direction
	GroundStation32 - direction
	Star51 - direction
	Star42 - direction
	GroundStation79 - direction
	GroundStation65 - direction
	Star12 - direction
	GroundStation25 - direction
	GroundStation96 - direction
	GroundStation6 - direction
	GroundStation4 - direction
	Star23 - direction
	Star38 - direction
	GroundStation16 - direction
	GroundStation74 - direction
	Star54 - direction
	GroundStation17 - direction
	GroundStation93 - direction
	Star76 - direction
	Star97 - direction
	GroundStation85 - direction
	GroundStation66 - direction
	GroundStation72 - direction
	Star13 - direction
	Star31 - direction
	GroundStation3 - direction
	Star35 - direction
	Star10 - direction
	GroundStation70 - direction
	Star75 - direction
	GroundStation34 - direction
	GroundStation92 - direction
	GroundStation7 - direction
	Star91 - direction
	Star55 - direction
	GroundStation98 - direction
	Star69 - direction
	Star37 - direction
	Star67 - direction
	Star43 - direction
	Star14 - direction
	GroundStation47 - direction
	Star60 - direction
	GroundStation29 - direction
	GroundStation24 - direction
	GroundStation77 - direction
	Star0 - direction
	GroundStation86 - direction
	Star33 - direction
	Star81 - direction
	GroundStation52 - direction
	Star82 - direction
	Star64 - direction
	Star57 - direction
	Star22 - direction
	Star27 - direction
	Star8 - direction
	GroundStation88 - direction
	Star26 - direction
	Star46 - direction
	GroundStation50 - direction
	Star41 - direction
	Star15 - direction
	Star99 - direction
	Star21 - direction
	GroundStation11 - direction
	GroundStation90 - direction
	GroundStation61 - direction
	GroundStation48 - direction
	Star100 - direction
	Planet101 - direction
	Planet102 - direction
	Phenomenon103 - direction
	Planet104 - direction
	Phenomenon105 - direction
	Planet106 - direction
	Star107 - direction
	Star108 - direction
	Planet109 - direction
	Star110 - direction
	Star111 - direction
	Star112 - direction
	Star113 - direction
	Planet114 - direction
	Star115 - direction
	Phenomenon116 - direction
	Planet117 - direction
	Planet118 - direction
	Star119 - direction
	Planet120 - direction
	Planet121 - direction
	Star122 - direction
	Planet123 - direction
	Phenomenon124 - direction
	Phenomenon125 - direction
	Star126 - direction
	Planet127 - direction
	Star128 - direction
	Star129 - direction
	Star130 - direction
	Planet131 - direction
	Planet132 - direction
	Planet133 - direction
	Planet134 - direction
	Planet135 - direction
	Phenomenon136 - direction
	Phenomenon137 - direction
	Star138 - direction
	Star139 - direction
	Phenomenon140 - direction
	Star141 - direction
	Phenomenon142 - direction
	Phenomenon143 - direction
	Star144 - direction
	Star145 - direction
	Planet146 - direction
	Planet147 - direction
	Planet148 - direction
	Star149 - direction
	Phenomenon150 - direction
	Star151 - direction
	Star152 - direction
	Phenomenon153 - direction
	Planet154 - direction
	Star155 - direction
	Phenomenon156 - direction
	Star157 - direction
	Planet158 - direction
	Planet159 - direction
	Planet160 - direction
	Planet161 - direction
	Phenomenon162 - direction
	Phenomenon163 - direction
	Planet164 - direction
	Phenomenon165 - direction
	Planet166 - direction
	Planet167 - direction
	Phenomenon168 - direction
	Planet169 - direction
)
(:init
	(supports instrument0 thermograph4)
	(supports instrument0 thermograph2)
	(supports instrument0 thermograph1)
	(calibration_target instrument0 Star40)
	(calibration_target instrument0 Star76)
	(calibration_target instrument0 GroundStation79)
	(calibration_target instrument0 Star81)
	(calibration_target instrument0 GroundStation4)
	(calibration_target instrument0 GroundStation24)
	(calibration_target instrument0 GroundStation18)
	(calibration_target instrument0 Star60)
	(calibration_target instrument0 GroundStation44)
	(calibration_target instrument0 Star10)
	(calibration_target instrument0 GroundStation87)
	(calibration_target instrument0 GroundStation34)
	(calibration_target instrument0 Star21)
	(calibration_target instrument0 GroundStation29)
	(calibration_target instrument0 Star58)
	(calibration_target instrument0 Star64)
	(calibration_target instrument0 Star19)
	(calibration_target instrument0 Star20)
	(calibration_target instrument0 Star28)
	(calibration_target instrument0 Star62)
	(calibration_target instrument0 Star84)
	(calibration_target instrument0 GroundStation17)
	(calibration_target instrument0 Star5)
	(calibration_target instrument0 Star91)
	(calibration_target instrument0 Star54)
	(calibration_target instrument0 GroundStation83)
	(calibration_target instrument0 GroundStation90)
	(calibration_target instrument0 Star12)
	(calibration_target instrument0 GroundStation48)
	(calibration_target instrument0 GroundStation53)
	(calibration_target instrument0 GroundStation7)
	(calibration_target instrument0 GroundStation88)
	(supports instrument1 thermograph2)
	(supports instrument1 image0)
	(supports instrument1 thermograph4)
	(calibration_target instrument1 GroundStation52)
	(calibration_target instrument1 Star80)
	(calibration_target instrument1 GroundStation93)
	(calibration_target instrument1 Star26)
	(calibration_target instrument1 GroundStation68)
	(calibration_target instrument1 Star84)
	(calibration_target instrument1 Star38)
	(calibration_target instrument1 GroundStation18)
	(calibration_target instrument1 GroundStation89)
	(calibration_target instrument1 Star75)
	(calibration_target instrument1 GroundStation94)
	(calibration_target instrument1 GroundStation88)
	(calibration_target instrument1 GroundStation61)
	(calibration_target instrument1 Star14)
	(calibration_target instrument1 GroundStation24)
	(calibration_target instrument1 Star55)
	(calibration_target instrument1 Star71)
	(calibration_target instrument1 Star54)
	(calibration_target instrument1 Star23)
	(calibration_target instrument1 GroundStation17)
	(calibration_target instrument1 Star99)
	(calibration_target instrument1 Star51)
	(supports instrument2 thermograph4)
	(calibration_target instrument2 Star21)
	(calibration_target instrument2 Star46)
	(calibration_target instrument2 Star57)
	(calibration_target instrument2 GroundStation85)
	(calibration_target instrument2 Star38)
	(calibration_target instrument2 Star10)
	(supports instrument3 thermograph2)
	(supports instrument3 thermograph1)
	(supports instrument3 infrared3)
	(calibration_target instrument3 GroundStation52)
	(calibration_target instrument3 Star60)
	(calibration_target instrument3 GroundStation63)
	(calibration_target instrument3 Star43)
	(calibration_target instrument3 GroundStation53)
	(calibration_target instrument3 Star71)
	(calibration_target instrument3 GroundStation32)
	(calibration_target instrument3 Star75)
	(calibration_target instrument3 GroundStation94)
	(calibration_target instrument3 GroundStation17)
	(calibration_target instrument3 Star64)
	(calibration_target instrument3 GroundStation3)
	(calibration_target instrument3 GroundStation56)
	(calibration_target instrument3 GroundStation24)
	(calibration_target instrument3 Star81)
	(calibration_target instrument3 GroundStation83)
	(calibration_target instrument3 Star22)
	(calibration_target instrument3 Star31)
	(calibration_target instrument3 Star97)
	(calibration_target instrument3 GroundStation61)
	(calibration_target instrument3 Star33)
	(calibration_target instrument3 Star13)
	(calibration_target instrument3 Star0)
	(calibration_target instrument3 GroundStation88)
	(calibration_target instrument3 GroundStation47)
	(calibration_target instrument3 GroundStation96)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star62)
	(supports instrument4 thermograph1)
	(supports instrument4 thermograph4)
	(calibration_target instrument4 GroundStation6)
	(calibration_target instrument4 GroundStation90)
	(calibration_target instrument4 GroundStation77)
	(calibration_target instrument4 Star22)
	(calibration_target instrument4 Star59)
	(calibration_target instrument4 Star40)
	(calibration_target instrument4 GroundStation44)
	(calibration_target instrument4 GroundStation56)
	(supports instrument5 image0)
	(supports instrument5 infrared3)
	(calibration_target instrument5 GroundStation93)
	(calibration_target instrument5 GroundStation73)
	(calibration_target instrument5 GroundStation44)
	(calibration_target instrument5 GroundStation98)
	(calibration_target instrument5 GroundStation24)
	(calibration_target instrument5 Star9)
	(calibration_target instrument5 GroundStation90)
	(calibration_target instrument5 GroundStation66)
	(calibration_target instrument5 GroundStation61)
	(calibration_target instrument5 Star12)
	(calibration_target instrument5 GroundStation34)
	(calibration_target instrument5 GroundStation83)
	(supports instrument6 thermograph1)
	(supports instrument6 image0)
	(calibration_target instrument6 Star26)
	(calibration_target instrument6 Star42)
	(calibration_target instrument6 Star62)
	(calibration_target instrument6 GroundStation39)
	(calibration_target instrument6 GroundStation79)
	(calibration_target instrument6 GroundStation92)
	(calibration_target instrument6 Star55)
	(calibration_target instrument6 Star69)
	(calibration_target instrument6 Star91)
	(calibration_target instrument6 Star54)
	(calibration_target instrument6 Star99)
	(calibration_target instrument6 Star15)
	(calibration_target instrument6 Star60)
	(calibration_target instrument6 GroundStation6)
	(calibration_target instrument6 Star59)
	(calibration_target instrument6 Star10)
	(calibration_target instrument6 GroundStation96)
	(calibration_target instrument6 Star14)
	(calibration_target instrument6 Star23)
	(calibration_target instrument6 Star22)
	(calibration_target instrument6 Star46)
	(calibration_target instrument6 GroundStation74)
	(calibration_target instrument6 Star97)
	(calibration_target instrument6 Star51)
	(calibration_target instrument6 Star31)
	(calibration_target instrument6 Star95)
	(calibration_target instrument6 GroundStation72)
	(calibration_target instrument6 GroundStation1)
	(calibration_target instrument6 Star75)
	(calibration_target instrument6 GroundStation65)
	(calibration_target instrument6 GroundStation93)
	(calibration_target instrument6 GroundStation78)
	(calibration_target instrument6 Star19)
	(supports instrument7 image0)
	(supports instrument7 infrared3)
	(supports instrument7 thermograph1)
	(calibration_target instrument7 Star55)
	(calibration_target instrument7 GroundStation45)
	(calibration_target instrument7 GroundStation61)
	(calibration_target instrument7 Star62)
	(calibration_target instrument7 Star38)
	(calibration_target instrument7 Star21)
	(calibration_target instrument7 GroundStation63)
	(calibration_target instrument7 Star67)
	(calibration_target instrument7 Star12)
	(calibration_target instrument7 Star43)
	(calibration_target instrument7 Star97)
	(calibration_target instrument7 GroundStation85)
	(calibration_target instrument7 Star31)
	(calibration_target instrument7 GroundStation16)
	(calibration_target instrument7 GroundStation34)
	(calibration_target instrument7 GroundStation44)
	(calibration_target instrument7 GroundStation90)
	(calibration_target instrument7 Star27)
	(calibration_target instrument7 GroundStation52)
	(calibration_target instrument7 GroundStation6)
	(calibration_target instrument7 GroundStation72)
	(calibration_target instrument7 Star0)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(on_board instrument7 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star15)
	(supports instrument8 thermograph2)
	(calibration_target instrument8 Star35)
	(calibration_target instrument8 Star0)
	(calibration_target instrument8 GroundStation79)
	(calibration_target instrument8 Star46)
	(calibration_target instrument8 Star5)
	(calibration_target instrument8 Star10)
	(calibration_target instrument8 Star12)
	(calibration_target instrument8 GroundStation29)
	(calibration_target instrument8 GroundStation98)
	(calibration_target instrument8 GroundStation88)
	(calibration_target instrument8 GroundStation90)
	(calibration_target instrument8 Star13)
	(calibration_target instrument8 Star36)
	(calibration_target instrument8 Star27)
	(calibration_target instrument8 GroundStation96)
	(calibration_target instrument8 Star38)
	(calibration_target instrument8 Star71)
	(calibration_target instrument8 GroundStation24)
	(on_board instrument8 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Planet135)
	(supports instrument9 thermograph4)
	(supports instrument9 thermograph1)
	(calibration_target instrument9 Star51)
	(calibration_target instrument9 GroundStation34)
	(calibration_target instrument9 GroundStation18)
	(calibration_target instrument9 Star71)
	(calibration_target instrument9 GroundStation61)
	(calibration_target instrument9 Star23)
	(calibration_target instrument9 GroundStation52)
	(calibration_target instrument9 GroundStation48)
	(calibration_target instrument9 Star28)
	(calibration_target instrument9 GroundStation50)
	(calibration_target instrument9 Star33)
	(calibration_target instrument9 GroundStation29)
	(calibration_target instrument9 Star62)
	(calibration_target instrument9 Star60)
	(calibration_target instrument9 Star84)
	(calibration_target instrument9 Star59)
	(calibration_target instrument9 Star42)
	(calibration_target instrument9 GroundStation47)
	(calibration_target instrument9 Star12)
	(calibration_target instrument9 Star36)
	(supports instrument10 thermograph4)
	(supports instrument10 thermograph1)
	(supports instrument10 image0)
	(calibration_target instrument10 Star37)
	(calibration_target instrument10 GroundStation7)
	(calibration_target instrument10 GroundStation11)
	(calibration_target instrument10 GroundStation73)
	(calibration_target instrument10 GroundStation25)
	(calibration_target instrument10 GroundStation50)
	(calibration_target instrument10 GroundStation83)
	(calibration_target instrument10 Star64)
	(calibration_target instrument10 GroundStation3)
	(calibration_target instrument10 GroundStation39)
	(calibration_target instrument10 Star51)
	(calibration_target instrument10 GroundStation79)
	(calibration_target instrument10 Star81)
	(supports instrument11 image0)
	(supports instrument11 thermograph2)
	(supports instrument11 thermograph1)
	(calibration_target instrument11 Star75)
	(calibration_target instrument11 GroundStation90)
	(calibration_target instrument11 Star64)
	(calibration_target instrument11 GroundStation98)
	(calibration_target instrument11 GroundStation88)
	(calibration_target instrument11 GroundStation52)
	(calibration_target instrument11 GroundStation3)
	(calibration_target instrument11 GroundStation61)
	(calibration_target instrument11 Star8)
	(calibration_target instrument11 Star54)
	(calibration_target instrument11 Star23)
	(calibration_target instrument11 Star60)
	(calibration_target instrument11 Star55)
	(calibration_target instrument11 GroundStation66)
	(calibration_target instrument11 GroundStation94)
	(calibration_target instrument11 Star36)
	(calibration_target instrument11 Star12)
	(calibration_target instrument11 Star62)
	(calibration_target instrument11 Star69)
	(calibration_target instrument11 GroundStation92)
	(calibration_target instrument11 GroundStation93)
	(calibration_target instrument11 GroundStation63)
	(calibration_target instrument11 GroundStation50)
	(calibration_target instrument11 GroundStation85)
	(calibration_target instrument11 GroundStation53)
	(calibration_target instrument11 GroundStation1)
	(calibration_target instrument11 GroundStation16)
	(calibration_target instrument11 Star84)
	(calibration_target instrument11 Star38)
	(calibration_target instrument11 Star37)
	(on_board instrument9 satellite3)
	(on_board instrument10 satellite3)
	(on_board instrument11 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star119)
	(supports instrument12 infrared3)
	(supports instrument12 thermograph1)
	(supports instrument12 thermograph4)
	(calibration_target instrument12 Star31)
	(calibration_target instrument12 Star97)
	(calibration_target instrument12 Star10)
	(calibration_target instrument12 Star28)
	(calibration_target instrument12 GroundStation50)
	(calibration_target instrument12 GroundStation39)
	(calibration_target instrument12 Star5)
	(calibration_target instrument12 GroundStation3)
	(calibration_target instrument12 Star19)
	(calibration_target instrument12 Star12)
	(calibration_target instrument12 Star21)
	(calibration_target instrument12 Star67)
	(calibration_target instrument12 GroundStation87)
	(calibration_target instrument12 Star27)
	(calibration_target instrument12 Star62)
	(calibration_target instrument12 GroundStation16)
	(calibration_target instrument12 GroundStation88)
	(calibration_target instrument12 GroundStation90)
	(calibration_target instrument12 GroundStation98)
	(calibration_target instrument12 GroundStation45)
	(calibration_target instrument12 GroundStation63)
	(calibration_target instrument12 Star20)
	(calibration_target instrument12 Star59)
	(calibration_target instrument12 GroundStation32)
	(calibration_target instrument12 GroundStation1)
	(calibration_target instrument12 Star60)
	(calibration_target instrument12 Star64)
	(calibration_target instrument12 GroundStation66)
	(calibration_target instrument12 Star14)
	(calibration_target instrument12 GroundStation68)
	(calibration_target instrument12 GroundStation94)
	(calibration_target instrument12 GroundStation83)
	(calibration_target instrument12 Star35)
	(supports instrument13 image0)
	(supports instrument13 infrared3)
	(calibration_target instrument13 Star36)
	(calibration_target instrument13 GroundStation11)
	(calibration_target instrument13 GroundStation24)
	(calibration_target instrument13 Star22)
	(calibration_target instrument13 Star40)
	(calibration_target instrument13 GroundStation18)
	(calibration_target instrument13 GroundStation68)
	(calibration_target instrument13 Star69)
	(calibration_target instrument13 GroundStation79)
	(calibration_target instrument13 Star80)
	(calibration_target instrument13 GroundStation50)
	(calibration_target instrument13 GroundStation3)
	(calibration_target instrument13 GroundStation47)
	(calibration_target instrument13 Star71)
	(calibration_target instrument13 Star28)
	(calibration_target instrument13 GroundStation98)
	(calibration_target instrument13 Star75)
	(calibration_target instrument13 GroundStation87)
	(calibration_target instrument13 Star15)
	(calibration_target instrument13 Star20)
	(calibration_target instrument13 Star57)
	(calibration_target instrument13 GroundStation16)
	(calibration_target instrument13 GroundStation45)
	(on_board instrument12 satellite4)
	(on_board instrument13 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star62)
	(supports instrument14 thermograph4)
	(calibration_target instrument14 GroundStation34)
	(calibration_target instrument14 Star59)
	(calibration_target instrument14 GroundStation18)
	(calibration_target instrument14 GroundStation79)
	(calibration_target instrument14 Star71)
	(calibration_target instrument14 Star82)
	(calibration_target instrument14 Star76)
	(calibration_target instrument14 GroundStation32)
	(calibration_target instrument14 Star55)
	(calibration_target instrument14 Star54)
	(calibration_target instrument14 Star35)
	(calibration_target instrument14 GroundStation29)
	(calibration_target instrument14 Star64)
	(calibration_target instrument14 Star41)
	(calibration_target instrument14 GroundStation88)
	(calibration_target instrument14 Star20)
	(calibration_target instrument14 GroundStation85)
	(supports instrument15 thermograph2)
	(supports instrument15 infrared3)
	(calibration_target instrument15 GroundStation47)
	(calibration_target instrument15 GroundStation79)
	(calibration_target instrument15 GroundStation74)
	(calibration_target instrument15 Star42)
	(calibration_target instrument15 Star81)
	(calibration_target instrument15 GroundStation50)
	(calibration_target instrument15 Star51)
	(calibration_target instrument15 GroundStation32)
	(calibration_target instrument15 Star27)
	(calibration_target instrument15 GroundStation68)
	(calibration_target instrument15 Star40)
	(calibration_target instrument15 Star76)
	(calibration_target instrument15 GroundStation17)
	(calibration_target instrument15 GroundStation11)
	(calibration_target instrument15 GroundStation87)
	(calibration_target instrument15 Star82)
	(calibration_target instrument15 Star35)
	(calibration_target instrument15 Star99)
	(calibration_target instrument15 GroundStation56)
	(calibration_target instrument15 GroundStation44)
	(calibration_target instrument15 GroundStation65)
	(calibration_target instrument15 GroundStation92)
	(supports instrument16 image0)
	(calibration_target instrument16 GroundStation25)
	(calibration_target instrument16 GroundStation16)
	(calibration_target instrument16 GroundStation66)
	(calibration_target instrument16 Star12)
	(calibration_target instrument16 Star41)
	(calibration_target instrument16 GroundStation65)
	(calibration_target instrument16 Star38)
	(calibration_target instrument16 GroundStation93)
	(calibration_target instrument16 Star35)
	(calibration_target instrument16 GroundStation61)
	(on_board instrument14 satellite5)
	(on_board instrument15 satellite5)
	(on_board instrument16 satellite5)
	(power_avail satellite5)
	(pointing satellite5 GroundStation61)
	(supports instrument17 thermograph2)
	(supports instrument17 image0)
	(calibration_target instrument17 Star81)
	(calibration_target instrument17 Star31)
	(calibration_target instrument17 Star13)
	(calibration_target instrument17 GroundStation52)
	(calibration_target instrument17 GroundStation72)
	(calibration_target instrument17 GroundStation66)
	(calibration_target instrument17 GroundStation85)
	(calibration_target instrument17 Star97)
	(calibration_target instrument17 Star76)
	(calibration_target instrument17 GroundStation93)
	(calibration_target instrument17 GroundStation17)
	(calibration_target instrument17 Star0)
	(calibration_target instrument17 Star21)
	(calibration_target instrument17 Star54)
	(calibration_target instrument17 GroundStation74)
	(calibration_target instrument17 GroundStation11)
	(calibration_target instrument17 GroundStation16)
	(calibration_target instrument17 Star38)
	(calibration_target instrument17 Star23)
	(calibration_target instrument17 GroundStation4)
	(calibration_target instrument17 GroundStation6)
	(calibration_target instrument17 Star8)
	(calibration_target instrument17 GroundStation50)
	(calibration_target instrument17 GroundStation77)
	(calibration_target instrument17 Star75)
	(calibration_target instrument17 GroundStation96)
	(calibration_target instrument17 GroundStation29)
	(supports instrument18 image0)
	(calibration_target instrument18 Star75)
	(calibration_target instrument18 GroundStation11)
	(calibration_target instrument18 GroundStation70)
	(calibration_target instrument18 Star10)
	(calibration_target instrument18 Star35)
	(calibration_target instrument18 GroundStation47)
	(calibration_target instrument18 GroundStation3)
	(calibration_target instrument18 GroundStation29)
	(supports instrument19 infrared3)
	(supports instrument19 image0)
	(calibration_target instrument19 Star60)
	(calibration_target instrument19 GroundStation47)
	(calibration_target instrument19 GroundStation90)
	(calibration_target instrument19 Star14)
	(calibration_target instrument19 Star43)
	(calibration_target instrument19 Star67)
	(calibration_target instrument19 Star82)
	(calibration_target instrument19 Star37)
	(calibration_target instrument19 Star69)
	(calibration_target instrument19 GroundStation98)
	(calibration_target instrument19 Star55)
	(calibration_target instrument19 Star91)
	(calibration_target instrument19 GroundStation7)
	(calibration_target instrument19 GroundStation92)
	(calibration_target instrument19 GroundStation34)
	(on_board instrument17 satellite6)
	(on_board instrument18 satellite6)
	(on_board instrument19 satellite6)
	(power_avail satellite6)
	(pointing satellite6 GroundStation16)
	(supports instrument20 thermograph2)
	(calibration_target instrument20 GroundStation61)
	(calibration_target instrument20 GroundStation90)
	(calibration_target instrument20 GroundStation11)
	(calibration_target instrument20 Star21)
	(calibration_target instrument20 Star99)
	(calibration_target instrument20 Star15)
	(calibration_target instrument20 Star41)
	(calibration_target instrument20 GroundStation50)
	(calibration_target instrument20 Star46)
	(calibration_target instrument20 Star26)
	(calibration_target instrument20 GroundStation88)
	(calibration_target instrument20 Star8)
	(calibration_target instrument20 Star27)
	(calibration_target instrument20 Star22)
	(calibration_target instrument20 Star57)
	(calibration_target instrument20 Star64)
	(calibration_target instrument20 Star82)
	(calibration_target instrument20 GroundStation52)
	(calibration_target instrument20 Star81)
	(calibration_target instrument20 Star33)
	(calibration_target instrument20 GroundStation86)
	(calibration_target instrument20 Star0)
	(calibration_target instrument20 GroundStation77)
	(calibration_target instrument20 GroundStation24)
	(calibration_target instrument20 GroundStation29)
	(supports instrument21 infrared3)
	(supports instrument21 thermograph4)
	(supports instrument21 image0)
	(calibration_target instrument21 GroundStation48)
	(on_board instrument20 satellite7)
	(on_board instrument21 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star129)
)
(:goal (and
	(pointing satellite0 Planet131)
	(pointing satellite4 GroundStation4)
	(pointing satellite5 GroundStation88)
	(pointing satellite6 Planet164)
	(have_image Star100 image0)
	(have_image Planet101 thermograph1)
	(have_image Planet102 image0)
	(have_image Phenomenon103 thermograph4)
	(have_image Planet104 thermograph2)
	(have_image Phenomenon105 thermograph1)
	(have_image Planet106 infrared3)
	(have_image Star107 thermograph4)
	(have_image Star108 infrared3)
	(have_image Planet109 thermograph4)
	(have_image Star110 thermograph2)
	(have_image Star111 thermograph4)
	(have_image Star112 image0)
	(have_image Star113 thermograph2)
	(have_image Planet114 image0)
	(have_image Star115 thermograph4)
	(have_image Phenomenon116 thermograph1)
	(have_image Planet117 image0)
	(have_image Planet118 image0)
	(have_image Star119 infrared3)
	(have_image Planet120 thermograph2)
	(have_image Planet121 image0)
	(have_image Star122 thermograph1)
	(have_image Planet123 thermograph2)
	(have_image Phenomenon124 infrared3)
	(have_image Phenomenon125 infrared3)
	(have_image Star126 thermograph4)
	(have_image Planet127 infrared3)
	(have_image Star128 thermograph1)
	(have_image Star129 image0)
	(have_image Star130 thermograph4)
	(have_image Planet131 image0)
	(have_image Planet132 infrared3)
	(have_image Planet133 thermograph2)
	(have_image Planet134 infrared3)
	(have_image Planet135 thermograph1)
	(have_image Phenomenon136 infrared3)
	(have_image Phenomenon137 infrared3)
	(have_image Star138 infrared3)
	(have_image Star139 image0)
	(have_image Phenomenon140 thermograph2)
	(have_image Star141 thermograph2)
	(have_image Phenomenon142 thermograph4)
	(have_image Phenomenon143 infrared3)
	(have_image Star144 thermograph1)
	(have_image Star145 thermograph4)
	(have_image Planet146 thermograph2)
	(have_image Planet147 thermograph2)
	(have_image Planet148 thermograph4)
	(have_image Star149 thermograph1)
	(have_image Phenomenon150 image0)
	(have_image Star151 thermograph4)
	(have_image Star152 thermograph4)
	(have_image Phenomenon153 image0)
	(have_image Planet154 image0)
	(have_image Star155 image0)
	(have_image Phenomenon156 thermograph1)
	(have_image Star157 image0)
	(have_image Planet158 thermograph2)
	(have_image Planet159 thermograph2)
	(have_image Planet160 infrared3)
	(have_image Planet161 thermograph2)
	(have_image Phenomenon162 thermograph1)
	(have_image Phenomenon163 thermograph4)
	(have_image Planet164 thermograph1)
	(have_image Phenomenon165 thermograph2)
	(have_image Planet166 image0)
	(have_image Planet167 thermograph4)
	(have_image Phenomenon168 thermograph2)
	(have_image Planet169 image0)
))

)
