(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	satellite1 - satellite
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	satellite2 - satellite
	instrument5 - instrument
	instrument6 - instrument
	satellite3 - satellite
	instrument7 - instrument
	infrared2 - mode
	thermograph0 - mode
	infrared4 - mode
	image3 - mode
	infrared1 - mode
	Star0 - direction
	Star6 - direction
	Star10 - direction
	Star12 - direction
	Star15 - direction
	GroundStation18 - direction
	Star19 - direction
	Star25 - direction
	Star29 - direction
	Star30 - direction
	Star33 - direction
	Star37 - direction
	GroundStation20 - direction
	GroundStation35 - direction
	GroundStation34 - direction
	GroundStation27 - direction
	Star9 - direction
	Star3 - direction
	GroundStation2 - direction
	GroundStation13 - direction
	Star21 - direction
	GroundStation4 - direction
	Star1 - direction
	Star16 - direction
	Star23 - direction
	Star22 - direction
	GroundStation11 - direction
	Star24 - direction
	Star36 - direction
	Star38 - direction
	GroundStation8 - direction
	GroundStation31 - direction
	GroundStation32 - direction
	Star14 - direction
	GroundStation39 - direction
	Star28 - direction
	Star5 - direction
	GroundStation7 - direction
	GroundStation17 - direction
	GroundStation26 - direction
	Star40 - direction
	Phenomenon41 - direction
	Planet42 - direction
	Planet43 - direction
	Star44 - direction
	Planet45 - direction
	Star46 - direction
	Star47 - direction
	Star48 - direction
	Planet49 - direction
	Star50 - direction
	Phenomenon51 - direction
	Planet52 - direction
	Star53 - direction
	Phenomenon54 - direction
	Phenomenon55 - direction
	Phenomenon56 - direction
	Phenomenon57 - direction
	Planet58 - direction
	Star59 - direction
	Planet60 - direction
	Planet61 - direction
	Star62 - direction
	Phenomenon63 - direction
	Star64 - direction
)
(:init
	(supports instrument0 thermograph0)
	(supports instrument0 image3)
	(supports instrument0 infrared2)
	(calibration_target instrument0 Star38)
	(calibration_target instrument0 GroundStation20)
	(supports instrument1 image3)
	(supports instrument1 infrared4)
	(supports instrument1 infrared2)
	(calibration_target instrument1 Star21)
	(calibration_target instrument1 GroundStation34)
	(calibration_target instrument1 GroundStation27)
	(calibration_target instrument1 GroundStation39)
	(calibration_target instrument1 Star1)
	(calibration_target instrument1 GroundStation11)
	(calibration_target instrument1 GroundStation35)
	(calibration_target instrument1 Star36)
	(calibration_target instrument1 GroundStation17)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Phenomenon63)
	(supports instrument2 infrared4)
	(supports instrument2 thermograph0)
	(calibration_target instrument2 GroundStation7)
	(calibration_target instrument2 GroundStation4)
	(calibration_target instrument2 Star16)
	(calibration_target instrument2 Star21)
	(calibration_target instrument2 Star38)
	(calibration_target instrument2 GroundStation13)
	(calibration_target instrument2 GroundStation2)
	(calibration_target instrument2 Star3)
	(calibration_target instrument2 Star9)
	(calibration_target instrument2 GroundStation27)
	(calibration_target instrument2 Star28)
	(supports instrument3 infrared2)
	(supports instrument3 image3)
	(supports instrument3 infrared4)
	(calibration_target instrument3 Star28)
	(calibration_target instrument3 GroundStation31)
	(calibration_target instrument3 Star1)
	(supports instrument4 image3)
	(supports instrument4 infrared4)
	(supports instrument4 infrared1)
	(calibration_target instrument4 Star36)
	(calibration_target instrument4 Star24)
	(calibration_target instrument4 GroundStation11)
	(calibration_target instrument4 GroundStation8)
	(calibration_target instrument4 Star22)
	(calibration_target instrument4 GroundStation32)
	(calibration_target instrument4 Star5)
	(calibration_target instrument4 Star23)
	(calibration_target instrument4 Star16)
	(on_board instrument2 satellite1)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Phenomenon51)
	(supports instrument5 infrared4)
	(supports instrument5 image3)
	(calibration_target instrument5 GroundStation8)
	(calibration_target instrument5 Star38)
	(supports instrument6 image3)
	(calibration_target instrument6 GroundStation7)
	(calibration_target instrument6 Star5)
	(calibration_target instrument6 Star28)
	(calibration_target instrument6 GroundStation39)
	(calibration_target instrument6 Star14)
	(calibration_target instrument6 GroundStation32)
	(calibration_target instrument6 GroundStation31)
	(on_board instrument5 satellite2)
	(on_board instrument6 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star19)
	(supports instrument7 infrared4)
	(calibration_target instrument7 GroundStation26)
	(calibration_target instrument7 GroundStation17)
	(on_board instrument7 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation11)
)
(:goal (and
	(have_image Star40 image3)
	(have_image Phenomenon41 thermograph0)
	(have_image Planet42 infrared4)
	(have_image Planet43 thermograph0)
	(have_image Star44 infrared2)
	(have_image Planet45 infrared2)
	(have_image Star46 thermograph0)
	(have_image Star47 infrared4)
	(have_image Star48 infrared1)
	(have_image Planet49 thermograph0)
	(have_image Star50 infrared2)
	(have_image Phenomenon51 thermograph0)
	(have_image Planet52 infrared4)
	(have_image Star53 image3)
	(have_image Phenomenon54 thermograph0)
	(have_image Phenomenon55 infrared4)
	(have_image Phenomenon56 infrared4)
	(have_image Phenomenon57 infrared4)
	(have_image Planet58 infrared2)
	(have_image Star59 image3)
	(have_image Planet60 infrared2)
	(have_image Planet61 infrared2)
	(have_image Star62 infrared4)
	(have_image Phenomenon63 infrared4)
	(have_image Star64 thermograph0)
))

)
