(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	satellite1 - satellite
	instrument3 - instrument
	satellite2 - satellite
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	infrared3 - mode
	infrared2 - mode
	spectrograph0 - mode
	thermograph1 - mode
	Star1 - direction
	GroundStation7 - direction
	Star20 - direction
	GroundStation21 - direction
	Star23 - direction
	GroundStation14 - direction
	Star6 - direction
	Star0 - direction
	GroundStation15 - direction
	Star2 - direction
	Star3 - direction
	Star19 - direction
	Star18 - direction
	GroundStation11 - direction
	Star13 - direction
	Star12 - direction
	Star22 - direction
	Star10 - direction
	GroundStation17 - direction
	GroundStation5 - direction
	Star4 - direction
	GroundStation24 - direction
	GroundStation8 - direction
	GroundStation16 - direction
	Star9 - direction
	Planet25 - direction
	Star26 - direction
	Phenomenon27 - direction
	Planet28 - direction
	Star29 - direction
	Star30 - direction
	Phenomenon31 - direction
	Phenomenon32 - direction
	Phenomenon33 - direction
	Planet34 - direction
	Planet35 - direction
	Star36 - direction
	Star37 - direction
	Phenomenon38 - direction
	Planet39 - direction
)
(:init
	(supports instrument0 infrared2)
	(supports instrument0 infrared3)
	(calibration_target instrument0 Star4)
	(calibration_target instrument0 Star9)
	(calibration_target instrument0 GroundStation14)
	(supports instrument1 infrared3)
	(supports instrument1 infrared2)
	(supports instrument1 spectrograph0)
	(calibration_target instrument1 Star18)
	(calibration_target instrument1 Star6)
	(calibration_target instrument1 GroundStation8)
	(supports instrument2 spectrograph0)
	(supports instrument2 infrared3)
	(calibration_target instrument2 GroundStation5)
	(calibration_target instrument2 Star3)
	(calibration_target instrument2 Star13)
	(calibration_target instrument2 Star2)
	(calibration_target instrument2 GroundStation15)
	(calibration_target instrument2 Star0)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star19)
	(supports instrument3 thermograph1)
	(supports instrument3 spectrograph0)
	(calibration_target instrument3 GroundStation24)
	(calibration_target instrument3 Star12)
	(calibration_target instrument3 Star13)
	(calibration_target instrument3 GroundStation11)
	(calibration_target instrument3 Star18)
	(calibration_target instrument3 Star19)
	(on_board instrument3 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation11)
	(supports instrument4 thermograph1)
	(calibration_target instrument4 Star22)
	(supports instrument5 infrared2)
	(supports instrument5 spectrograph0)
	(supports instrument5 infrared3)
	(calibration_target instrument5 GroundStation17)
	(calibration_target instrument5 Star10)
	(calibration_target instrument5 Star22)
	(calibration_target instrument5 Star4)
	(supports instrument6 infrared3)
	(calibration_target instrument6 Star9)
	(calibration_target instrument6 GroundStation16)
	(calibration_target instrument6 GroundStation8)
	(calibration_target instrument6 GroundStation24)
	(calibration_target instrument6 Star4)
	(calibration_target instrument6 GroundStation5)
	(on_board instrument4 satellite2)
	(on_board instrument5 satellite2)
	(on_board instrument6 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star3)
)
(:goal (and
	(pointing satellite2 Star0)
	(have_image Planet25 thermograph1)
	(have_image Star26 spectrograph0)
	(have_image Phenomenon27 spectrograph0)
	(have_image Planet28 infrared3)
	(have_image Star29 infrared3)
	(have_image Star30 thermograph1)
	(have_image Phenomenon31 spectrograph0)
	(have_image Phenomenon32 infrared3)
	(have_image Phenomenon33 infrared3)
	(have_image Planet34 spectrograph0)
	(have_image Planet35 infrared2)
	(have_image Star36 spectrograph0)
	(have_image Star37 infrared2)
	(have_image Phenomenon38 infrared2)
	(have_image Planet39 infrared2)
))

)
