(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	satellite1 - satellite
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	satellite2 - satellite
	instrument7 - instrument
	satellite3 - satellite
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	satellite4 - satellite
	instrument11 - instrument
	instrument12 - instrument
	image3 - mode
	spectrograph1 - mode
	thermograph4 - mode
	infrared0 - mode
	infrared2 - mode
	Star21 - direction
	GroundStation25 - direction
	Star35 - direction
	Star50 - direction
	GroundStation39 - direction
	GroundStation19 - direction
	GroundStation51 - direction
	Star54 - direction
	GroundStation7 - direction
	GroundStation27 - direction
	GroundStation29 - direction
	GroundStation28 - direction
	GroundStation15 - direction
	GroundStation26 - direction
	Star24 - direction
	GroundStation44 - direction
	Star40 - direction
	GroundStation49 - direction
	GroundStation37 - direction
	Star38 - direction
	Star42 - direction
	Star45 - direction
	GroundStation18 - direction
	GroundStation33 - direction
	GroundStation12 - direction
	Star43 - direction
	Star8 - direction
	Star3 - direction
	Star48 - direction
	GroundStation56 - direction
	GroundStation22 - direction
	GroundStation31 - direction
	GroundStation59 - direction
	GroundStation23 - direction
	GroundStation46 - direction
	GroundStation2 - direction
	Star16 - direction
	GroundStation58 - direction
	GroundStation6 - direction
	Star55 - direction
	Star52 - direction
	GroundStation1 - direction
	GroundStation53 - direction
	GroundStation47 - direction
	Star34 - direction
	GroundStation57 - direction
	Star11 - direction
	GroundStation14 - direction
	GroundStation36 - direction
	GroundStation20 - direction
	Star32 - direction
	Star9 - direction
	Star4 - direction
	GroundStation5 - direction
	GroundStation30 - direction
	GroundStation17 - direction
	Star0 - direction
	GroundStation13 - direction
	Star41 - direction
	Star10 - direction
	Phenomenon60 - direction
	Phenomenon61 - direction
	Star62 - direction
	Phenomenon63 - direction
	Star64 - direction
	Phenomenon65 - direction
	Star66 - direction
	Star67 - direction
	Planet68 - direction
	Planet69 - direction
	Planet70 - direction
	Planet71 - direction
	Planet72 - direction
	Star73 - direction
	Star74 - direction
	Planet75 - direction
	Planet76 - direction
	Planet77 - direction
	Phenomenon78 - direction
	Planet79 - direction
	Star80 - direction
	Phenomenon81 - direction
	Planet82 - direction
	Phenomenon83 - direction
	Phenomenon84 - direction
	Phenomenon85 - direction
	Star86 - direction
	Phenomenon87 - direction
	Phenomenon88 - direction
	Planet89 - direction
	Phenomenon90 - direction
	Phenomenon91 - direction
	Star92 - direction
	Phenomenon93 - direction
	Planet94 - direction
	Planet95 - direction
	Phenomenon96 - direction
	Star97 - direction
	Star98 - direction
	Star99 - direction
)
(:init
	(supports instrument0 infrared0)
	(calibration_target instrument0 GroundStation22)
	(calibration_target instrument0 GroundStation33)
	(calibration_target instrument0 Star8)
	(calibration_target instrument0 GroundStation18)
	(calibration_target instrument0 GroundStation19)
	(calibration_target instrument0 GroundStation51)
	(calibration_target instrument0 GroundStation57)
	(calibration_target instrument0 GroundStation39)
	(calibration_target instrument0 Star10)
	(calibration_target instrument0 Star9)
	(calibration_target instrument0 GroundStation7)
	(calibration_target instrument0 GroundStation36)
	(calibration_target instrument0 GroundStation26)
	(supports instrument1 spectrograph1)
	(supports instrument1 infrared0)
	(calibration_target instrument1 GroundStation51)
	(calibration_target instrument1 GroundStation13)
	(calibration_target instrument1 GroundStation59)
	(calibration_target instrument1 Star3)
	(calibration_target instrument1 GroundStation37)
	(supports instrument2 spectrograph1)
	(supports instrument2 infrared2)
	(calibration_target instrument2 GroundStation27)
	(calibration_target instrument2 GroundStation6)
	(calibration_target instrument2 GroundStation37)
	(calibration_target instrument2 Star48)
	(calibration_target instrument2 Star42)
	(calibration_target instrument2 Star4)
	(calibration_target instrument2 Star9)
	(calibration_target instrument2 Star11)
	(calibration_target instrument2 GroundStation57)
	(calibration_target instrument2 GroundStation14)
	(calibration_target instrument2 GroundStation56)
	(calibration_target instrument2 GroundStation31)
	(calibration_target instrument2 GroundStation58)
	(calibration_target instrument2 GroundStation30)
	(calibration_target instrument2 GroundStation53)
	(calibration_target instrument2 Star43)
	(calibration_target instrument2 GroundStation47)
	(calibration_target instrument2 GroundStation46)
	(calibration_target instrument2 Star54)
	(calibration_target instrument2 GroundStation29)
	(supports instrument3 infrared0)
	(supports instrument3 image3)
	(supports instrument3 infrared2)
	(calibration_target instrument3 GroundStation57)
	(calibration_target instrument3 GroundStation37)
	(calibration_target instrument3 GroundStation26)
	(calibration_target instrument3 GroundStation49)
	(calibration_target instrument3 GroundStation22)
	(calibration_target instrument3 GroundStation30)
	(calibration_target instrument3 GroundStation27)
	(calibration_target instrument3 GroundStation29)
	(calibration_target instrument3 Star24)
	(calibration_target instrument3 GroundStation36)
	(calibration_target instrument3 GroundStation23)
	(calibration_target instrument3 Star45)
	(calibration_target instrument3 GroundStation2)
	(calibration_target instrument3 Star38)
	(calibration_target instrument3 GroundStation7)
	(calibration_target instrument3 Star34)
	(calibration_target instrument3 Star52)
	(calibration_target instrument3 GroundStation31)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star9)
	(supports instrument4 infrared2)
	(supports instrument4 thermograph4)
	(calibration_target instrument4 Star24)
	(calibration_target instrument4 GroundStation36)
	(calibration_target instrument4 Star55)
	(calibration_target instrument4 Star41)
	(calibration_target instrument4 GroundStation56)
	(calibration_target instrument4 GroundStation6)
	(calibration_target instrument4 Star52)
	(calibration_target instrument4 GroundStation57)
	(calibration_target instrument4 GroundStation26)
	(calibration_target instrument4 GroundStation15)
	(calibration_target instrument4 GroundStation28)
	(calibration_target instrument4 Star38)
	(calibration_target instrument4 Star11)
	(calibration_target instrument4 GroundStation29)
	(supports instrument5 infrared0)
	(supports instrument5 spectrograph1)
	(calibration_target instrument5 Star3)
	(calibration_target instrument5 Star9)
	(calibration_target instrument5 GroundStation58)
	(calibration_target instrument5 Star41)
	(calibration_target instrument5 GroundStation44)
	(supports instrument6 infrared0)
	(supports instrument6 image3)
	(supports instrument6 infrared2)
	(calibration_target instrument6 Star34)
	(calibration_target instrument6 Star40)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Phenomenon93)
	(supports instrument7 spectrograph1)
	(supports instrument7 image3)
	(calibration_target instrument7 GroundStation30)
	(calibration_target instrument7 Star34)
	(calibration_target instrument7 GroundStation18)
	(calibration_target instrument7 GroundStation17)
	(calibration_target instrument7 Star41)
	(calibration_target instrument7 Star42)
	(calibration_target instrument7 GroundStation13)
	(calibration_target instrument7 GroundStation56)
	(calibration_target instrument7 GroundStation37)
	(calibration_target instrument7 GroundStation22)
	(calibration_target instrument7 Star3)
	(calibration_target instrument7 GroundStation49)
	(calibration_target instrument7 GroundStation2)
	(calibration_target instrument7 Star40)
	(calibration_target instrument7 Star32)
	(on_board instrument7 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Planet94)
	(supports instrument8 infrared0)
	(calibration_target instrument8 GroundStation18)
	(calibration_target instrument8 Star45)
	(calibration_target instrument8 Star42)
	(calibration_target instrument8 Star38)
	(calibration_target instrument8 GroundStation31)
	(calibration_target instrument8 GroundStation20)
	(supports instrument9 infrared0)
	(supports instrument9 image3)
	(calibration_target instrument9 Star3)
	(calibration_target instrument9 GroundStation22)
	(calibration_target instrument9 GroundStation33)
	(supports instrument10 infrared2)
	(supports instrument10 thermograph4)
	(supports instrument10 infrared0)
	(calibration_target instrument10 Star41)
	(calibration_target instrument10 GroundStation46)
	(calibration_target instrument10 GroundStation23)
	(calibration_target instrument10 GroundStation5)
	(calibration_target instrument10 GroundStation59)
	(calibration_target instrument10 GroundStation31)
	(calibration_target instrument10 GroundStation22)
	(calibration_target instrument10 GroundStation56)
	(calibration_target instrument10 GroundStation14)
	(calibration_target instrument10 Star16)
	(calibration_target instrument10 GroundStation1)
	(calibration_target instrument10 Star48)
	(calibration_target instrument10 Star55)
	(calibration_target instrument10 Star3)
	(calibration_target instrument10 Star8)
	(calibration_target instrument10 Star43)
	(calibration_target instrument10 GroundStation6)
	(calibration_target instrument10 GroundStation12)
	(on_board instrument8 satellite3)
	(on_board instrument9 satellite3)
	(on_board instrument10 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Planet95)
	(supports instrument11 spectrograph1)
	(supports instrument11 thermograph4)
	(calibration_target instrument11 GroundStation20)
	(calibration_target instrument11 GroundStation13)
	(calibration_target instrument11 GroundStation14)
	(calibration_target instrument11 Star11)
	(calibration_target instrument11 GroundStation57)
	(calibration_target instrument11 Star34)
	(calibration_target instrument11 GroundStation47)
	(calibration_target instrument11 GroundStation53)
	(calibration_target instrument11 GroundStation1)
	(calibration_target instrument11 Star4)
	(calibration_target instrument11 Star0)
	(calibration_target instrument11 Star52)
	(calibration_target instrument11 Star9)
	(calibration_target instrument11 Star55)
	(calibration_target instrument11 GroundStation6)
	(calibration_target instrument11 GroundStation58)
	(calibration_target instrument11 Star16)
	(calibration_target instrument11 GroundStation2)
	(calibration_target instrument11 Star32)
	(supports instrument12 infrared0)
	(calibration_target instrument12 Star10)
	(calibration_target instrument12 Star41)
	(calibration_target instrument12 GroundStation13)
	(calibration_target instrument12 Star0)
	(calibration_target instrument12 GroundStation17)
	(calibration_target instrument12 GroundStation30)
	(calibration_target instrument12 GroundStation5)
	(calibration_target instrument12 Star4)
	(calibration_target instrument12 Star9)
	(calibration_target instrument12 Star32)
	(calibration_target instrument12 GroundStation20)
	(calibration_target instrument12 GroundStation36)
	(on_board instrument11 satellite4)
	(on_board instrument12 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Phenomenon60)
)
(:goal (and
	(pointing satellite0 Phenomenon91)
	(pointing satellite1 Star67)
	(pointing satellite4 Star41)
	(have_image Phenomenon60 thermograph4)
	(have_image Phenomenon61 thermograph4)
	(have_image Star62 spectrograph1)
	(have_image Phenomenon63 infrared2)
	(have_image Star64 infrared0)
	(have_image Phenomenon65 thermograph4)
	(have_image Star66 image3)
	(have_image Star67 infrared0)
	(have_image Planet68 thermograph4)
	(have_image Planet69 spectrograph1)
	(have_image Planet70 infrared0)
	(have_image Planet71 thermograph4)
	(have_image Planet72 spectrograph1)
	(have_image Star73 thermograph4)
	(have_image Star74 infrared2)
	(have_image Planet75 spectrograph1)
	(have_image Planet76 infrared2)
	(have_image Planet77 infrared2)
	(have_image Phenomenon78 thermograph4)
	(have_image Planet79 spectrograph1)
	(have_image Star80 image3)
	(have_image Phenomenon81 thermograph4)
	(have_image Planet82 infrared0)
	(have_image Phenomenon83 infrared2)
	(have_image Phenomenon84 spectrograph1)
	(have_image Phenomenon85 infrared2)
	(have_image Star86 infrared2)
	(have_image Phenomenon87 infrared2)
	(have_image Phenomenon88 infrared0)
	(have_image Planet89 spectrograph1)
	(have_image Phenomenon90 infrared2)
	(have_image Phenomenon91 infrared2)
	(have_image Star92 infrared0)
	(have_image Phenomenon93 infrared2)
	(have_image Planet94 thermograph4)
	(have_image Planet95 infrared0)
	(have_image Phenomenon96 infrared0)
	(have_image Star97 thermograph4)
	(have_image Star98 thermograph4)
	(have_image Star99 infrared2)
))

)
