(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	satellite1 - satellite
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	satellite2 - satellite
	instrument7 - instrument
	instrument8 - instrument
	image3 - mode
	infrared2 - mode
	infrared1 - mode
	thermograph0 - mode
	Star16 - direction
	Star17 - direction
	Star26 - direction
	Star23 - direction
	GroundStation6 - direction
	GroundStation15 - direction
	Star0 - direction
	GroundStation21 - direction
	Star3 - direction
	Star9 - direction
	Star4 - direction
	Star19 - direction
	GroundStation29 - direction
	GroundStation5 - direction
	GroundStation27 - direction
	Star7 - direction
	Star12 - direction
	GroundStation20 - direction
	Star14 - direction
	Star13 - direction
	GroundStation8 - direction
	GroundStation2 - direction
	GroundStation1 - direction
	GroundStation28 - direction
	GroundStation25 - direction
	GroundStation10 - direction
	GroundStation18 - direction
	GroundStation22 - direction
	Star11 - direction
	Star24 - direction
	Phenomenon30 - direction
	Star31 - direction
	Star32 - direction
	Phenomenon33 - direction
	Planet34 - direction
	Phenomenon35 - direction
	Planet36 - direction
	Star37 - direction
	Planet38 - direction
	Star39 - direction
	Planet40 - direction
	Planet41 - direction
	Phenomenon42 - direction
	Star43 - direction
	Phenomenon44 - direction
	Planet45 - direction
	Planet46 - direction
	Planet47 - direction
	Star48 - direction
	Phenomenon49 - direction
)
(:init
	(supports instrument0 image3)
	(calibration_target instrument0 Star9)
	(calibration_target instrument0 GroundStation5)
	(calibration_target instrument0 GroundStation22)
	(calibration_target instrument0 GroundStation27)
	(calibration_target instrument0 GroundStation21)
	(supports instrument1 infrared2)
	(calibration_target instrument1 Star12)
	(calibration_target instrument1 GroundStation6)
	(calibration_target instrument1 GroundStation8)
	(calibration_target instrument1 Star9)
	(calibration_target instrument1 GroundStation29)
	(calibration_target instrument1 Star0)
	(calibration_target instrument1 Star23)
	(calibration_target instrument1 GroundStation18)
	(calibration_target instrument1 Star4)
	(supports instrument2 image3)
	(calibration_target instrument2 GroundStation10)
	(supports instrument3 thermograph0)
	(calibration_target instrument3 Star4)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star12)
	(supports instrument4 infrared2)
	(calibration_target instrument4 Star0)
	(calibration_target instrument4 GroundStation22)
	(calibration_target instrument4 GroundStation15)
	(supports instrument5 thermograph0)
	(calibration_target instrument5 GroundStation29)
	(calibration_target instrument5 GroundStation10)
	(calibration_target instrument5 GroundStation2)
	(calibration_target instrument5 Star19)
	(calibration_target instrument5 Star4)
	(calibration_target instrument5 Star13)
	(calibration_target instrument5 Star9)
	(calibration_target instrument5 Star3)
	(calibration_target instrument5 GroundStation21)
	(supports instrument6 infrared2)
	(supports instrument6 infrared1)
	(calibration_target instrument6 GroundStation27)
	(calibration_target instrument6 GroundStation5)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star14)
	(supports instrument7 image3)
	(supports instrument7 infrared2)
	(supports instrument7 thermograph0)
	(calibration_target instrument7 GroundStation8)
	(calibration_target instrument7 Star13)
	(calibration_target instrument7 Star14)
	(calibration_target instrument7 GroundStation20)
	(calibration_target instrument7 Star12)
	(calibration_target instrument7 Star7)
	(calibration_target instrument7 Star24)
	(supports instrument8 thermograph0)
	(calibration_target instrument8 Star24)
	(calibration_target instrument8 Star11)
	(calibration_target instrument8 GroundStation22)
	(calibration_target instrument8 GroundStation18)
	(calibration_target instrument8 GroundStation10)
	(calibration_target instrument8 GroundStation25)
	(calibration_target instrument8 GroundStation28)
	(calibration_target instrument8 GroundStation1)
	(calibration_target instrument8 GroundStation2)
	(on_board instrument7 satellite2)
	(on_board instrument8 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star23)
)
(:goal (and
	(have_image Phenomenon30 image3)
	(have_image Star31 infrared2)
	(have_image Star32 thermograph0)
	(have_image Phenomenon33 image3)
	(have_image Planet34 infrared2)
	(have_image Phenomenon35 thermograph0)
	(have_image Planet36 thermograph0)
	(have_image Star37 image3)
	(have_image Planet38 thermograph0)
	(have_image Star39 infrared2)
	(have_image Planet40 infrared1)
	(have_image Planet41 infrared1)
	(have_image Phenomenon42 image3)
	(have_image Star43 image3)
	(have_image Phenomenon44 image3)
	(have_image Planet45 thermograph0)
	(have_image Planet46 infrared2)
	(have_image Planet47 thermograph0)
	(have_image Star48 thermograph0)
	(have_image Phenomenon49 infrared2)
))

)
