(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	satellite1 - satellite
	instrument1 - instrument
	satellite2 - satellite
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	satellite3 - satellite
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	satellite4 - satellite
	instrument9 - instrument
	instrument10 - instrument
	infrared4 - mode
	thermograph1 - mode
	image3 - mode
	infrared0 - mode
	thermograph2 - mode
	Star16 - direction
	Star19 - direction
	Star24 - direction
	Star35 - direction
	GroundStation38 - direction
	Star40 - direction
	GroundStation54 - direction
	Star59 - direction
	Star14 - direction
	Star36 - direction
	GroundStation37 - direction
	GroundStation44 - direction
	Star23 - direction
	GroundStation47 - direction
	Star3 - direction
	Star12 - direction
	GroundStation29 - direction
	Star51 - direction
	GroundStation34 - direction
	GroundStation8 - direction
	Star5 - direction
	GroundStation22 - direction
	GroundStation46 - direction
	GroundStation56 - direction
	GroundStation26 - direction
	GroundStation0 - direction
	Star15 - direction
	GroundStation4 - direction
	GroundStation17 - direction
	GroundStation43 - direction
	GroundStation50 - direction
	Star25 - direction
	GroundStation2 - direction
	GroundStation27 - direction
	GroundStation13 - direction
	Star7 - direction
	Star57 - direction
	Star58 - direction
	Star32 - direction
	Star41 - direction
	GroundStation11 - direction
	Star48 - direction
	GroundStation30 - direction
	Star33 - direction
	GroundStation45 - direction
	GroundStation20 - direction
	GroundStation52 - direction
	Star9 - direction
	GroundStation28 - direction
	GroundStation55 - direction
	Star1 - direction
	Star6 - direction
	Star21 - direction
	GroundStation31 - direction
	Star49 - direction
	Star42 - direction
	GroundStation39 - direction
	Star53 - direction
	Star10 - direction
	GroundStation18 - direction
	Star60 - direction
	Planet61 - direction
	Planet62 - direction
	Phenomenon63 - direction
	Star64 - direction
	Planet65 - direction
	Phenomenon66 - direction
	Star67 - direction
	Phenomenon68 - direction
	Planet69 - direction
	Star70 - direction
	Planet71 - direction
	Star72 - direction
	Phenomenon73 - direction
	Star74 - direction
	Star75 - direction
	Planet76 - direction
	Planet77 - direction
	Planet78 - direction
	Planet79 - direction
	Phenomenon80 - direction
	Phenomenon81 - direction
	Planet82 - direction
	Phenomenon83 - direction
	Planet84 - direction
	Star85 - direction
	Phenomenon86 - direction
	Planet87 - direction
	Phenomenon88 - direction
	Planet89 - direction
	Planet90 - direction
	Phenomenon91 - direction
	Planet92 - direction
	Star93 - direction
	Star94 - direction
	Planet95 - direction
	Planet96 - direction
	Planet97 - direction
	Phenomenon98 - direction
	Phenomenon99 - direction
)
(:init
	(supports instrument0 infrared4)
	(supports instrument0 thermograph2)
	(calibration_target instrument0 Star15)
	(on_board instrument0 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star42)
	(supports instrument1 image3)
	(supports instrument1 thermograph2)
	(calibration_target instrument1 Star5)
	(calibration_target instrument1 GroundStation37)
	(on_board instrument1 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation20)
	(supports instrument2 thermograph1)
	(calibration_target instrument2 GroundStation43)
	(calibration_target instrument2 GroundStation13)
	(calibration_target instrument2 Star5)
	(calibration_target instrument2 GroundStation45)
	(calibration_target instrument2 GroundStation29)
	(calibration_target instrument2 Star36)
	(calibration_target instrument2 Star9)
	(calibration_target instrument2 Star51)
	(calibration_target instrument2 GroundStation18)
	(calibration_target instrument2 Star48)
	(calibration_target instrument2 Star49)
	(calibration_target instrument2 Star6)
	(calibration_target instrument2 GroundStation50)
	(calibration_target instrument2 Star23)
	(calibration_target instrument2 Star14)
	(supports instrument3 image3)
	(supports instrument3 infrared0)
	(calibration_target instrument3 Star32)
	(calibration_target instrument3 GroundStation52)
	(calibration_target instrument3 GroundStation13)
	(calibration_target instrument3 GroundStation44)
	(calibration_target instrument3 GroundStation30)
	(calibration_target instrument3 GroundStation20)
	(calibration_target instrument3 Star25)
	(calibration_target instrument3 GroundStation11)
	(supports instrument4 infrared0)
	(calibration_target instrument4 Star6)
	(calibration_target instrument4 GroundStation34)
	(calibration_target instrument4 Star49)
	(calibration_target instrument4 Star23)
	(calibration_target instrument4 Star1)
	(calibration_target instrument4 GroundStation31)
	(calibration_target instrument4 Star48)
	(calibration_target instrument4 GroundStation44)
	(calibration_target instrument4 GroundStation50)
	(calibration_target instrument4 GroundStation39)
	(calibration_target instrument4 GroundStation4)
	(calibration_target instrument4 Star7)
	(calibration_target instrument4 GroundStation45)
	(calibration_target instrument4 GroundStation37)
	(calibration_target instrument4 Star3)
	(on_board instrument2 satellite2)
	(on_board instrument3 satellite2)
	(on_board instrument4 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star85)
	(supports instrument5 infrared4)
	(supports instrument5 image3)
	(supports instrument5 thermograph2)
	(calibration_target instrument5 GroundStation43)
	(calibration_target instrument5 GroundStation0)
	(calibration_target instrument5 GroundStation31)
	(calibration_target instrument5 GroundStation20)
	(calibration_target instrument5 GroundStation47)
	(supports instrument6 infrared4)
	(supports instrument6 image3)
	(supports instrument6 thermograph1)
	(calibration_target instrument6 GroundStation2)
	(calibration_target instrument6 Star42)
	(calibration_target instrument6 Star57)
	(calibration_target instrument6 Star49)
	(calibration_target instrument6 GroundStation22)
	(calibration_target instrument6 Star48)
	(calibration_target instrument6 GroundStation17)
	(calibration_target instrument6 GroundStation52)
	(calibration_target instrument6 GroundStation20)
	(calibration_target instrument6 Star53)
	(calibration_target instrument6 Star9)
	(calibration_target instrument6 Star7)
	(calibration_target instrument6 GroundStation18)
	(supports instrument7 image3)
	(calibration_target instrument7 Star58)
	(calibration_target instrument7 GroundStation56)
	(calibration_target instrument7 GroundStation18)
	(calibration_target instrument7 GroundStation50)
	(calibration_target instrument7 GroundStation34)
	(calibration_target instrument7 Star1)
	(calibration_target instrument7 GroundStation0)
	(calibration_target instrument7 GroundStation30)
	(calibration_target instrument7 GroundStation31)
	(calibration_target instrument7 Star51)
	(calibration_target instrument7 GroundStation29)
	(calibration_target instrument7 Star12)
	(calibration_target instrument7 Star49)
	(calibration_target instrument7 GroundStation28)
	(calibration_target instrument7 Star3)
	(calibration_target instrument7 GroundStation8)
	(supports instrument8 image3)
	(calibration_target instrument8 GroundStation50)
	(calibration_target instrument8 GroundStation43)
	(calibration_target instrument8 GroundStation17)
	(calibration_target instrument8 GroundStation4)
	(calibration_target instrument8 Star15)
	(calibration_target instrument8 Star21)
	(calibration_target instrument8 GroundStation0)
	(calibration_target instrument8 GroundStation11)
	(calibration_target instrument8 Star58)
	(calibration_target instrument8 GroundStation26)
	(calibration_target instrument8 GroundStation30)
	(calibration_target instrument8 GroundStation56)
	(calibration_target instrument8 GroundStation46)
	(calibration_target instrument8 Star41)
	(calibration_target instrument8 GroundStation22)
	(calibration_target instrument8 Star5)
	(calibration_target instrument8 Star33)
	(calibration_target instrument8 GroundStation8)
	(on_board instrument5 satellite3)
	(on_board instrument6 satellite3)
	(on_board instrument7 satellite3)
	(on_board instrument8 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Planet77)
	(supports instrument9 infrared4)
	(supports instrument9 image3)
	(supports instrument9 infrared0)
	(calibration_target instrument9 Star33)
	(calibration_target instrument9 GroundStation30)
	(calibration_target instrument9 Star48)
	(calibration_target instrument9 GroundStation11)
	(calibration_target instrument9 GroundStation39)
	(calibration_target instrument9 Star9)
	(calibration_target instrument9 GroundStation45)
	(calibration_target instrument9 Star41)
	(calibration_target instrument9 Star32)
	(calibration_target instrument9 Star58)
	(calibration_target instrument9 Star57)
	(calibration_target instrument9 Star7)
	(calibration_target instrument9 GroundStation13)
	(calibration_target instrument9 GroundStation27)
	(calibration_target instrument9 GroundStation2)
	(calibration_target instrument9 Star25)
	(calibration_target instrument9 Star6)
	(supports instrument10 infrared4)
	(supports instrument10 thermograph2)
	(supports instrument10 thermograph1)
	(calibration_target instrument10 GroundStation18)
	(calibration_target instrument10 Star10)
	(calibration_target instrument10 Star53)
	(calibration_target instrument10 GroundStation39)
	(calibration_target instrument10 Star42)
	(calibration_target instrument10 Star49)
	(calibration_target instrument10 GroundStation31)
	(calibration_target instrument10 Star21)
	(calibration_target instrument10 Star6)
	(calibration_target instrument10 Star1)
	(calibration_target instrument10 GroundStation55)
	(calibration_target instrument10 GroundStation28)
	(calibration_target instrument10 Star9)
	(calibration_target instrument10 GroundStation52)
	(calibration_target instrument10 GroundStation20)
	(calibration_target instrument10 GroundStation45)
	(on_board instrument9 satellite4)
	(on_board instrument10 satellite4)
	(power_avail satellite4)
	(pointing satellite4 GroundStation20)
)
(:goal (and
	(pointing satellite2 Phenomenon99)
	(pointing satellite3 GroundStation18)
	(have_image Star60 image3)
	(have_image Planet61 thermograph1)
	(have_image Planet62 thermograph2)
	(have_image Phenomenon63 infrared0)
	(have_image Star64 image3)
	(have_image Planet65 thermograph2)
	(have_image Phenomenon66 infrared0)
	(have_image Star67 thermograph1)
	(have_image Phenomenon68 thermograph2)
	(have_image Planet69 infrared4)
	(have_image Star70 infrared4)
	(have_image Planet71 infrared0)
	(have_image Star72 image3)
	(have_image Phenomenon73 thermograph1)
	(have_image Star74 image3)
	(have_image Star75 thermograph1)
	(have_image Planet76 thermograph2)
	(have_image Planet77 thermograph2)
	(have_image Planet78 thermograph1)
	(have_image Planet79 infrared0)
	(have_image Phenomenon80 thermograph1)
	(have_image Phenomenon81 thermograph2)
	(have_image Planet82 thermograph1)
	(have_image Phenomenon83 thermograph1)
	(have_image Planet84 image3)
	(have_image Star85 image3)
	(have_image Phenomenon86 image3)
	(have_image Planet87 thermograph1)
	(have_image Phenomenon88 thermograph2)
	(have_image Planet89 image3)
	(have_image Planet90 thermograph2)
	(have_image Phenomenon91 thermograph2)
	(have_image Planet92 thermograph1)
	(have_image Star93 thermograph2)
	(have_image Star94 thermograph1)
	(have_image Planet95 image3)
	(have_image Planet96 infrared0)
	(have_image Planet97 thermograph1)
	(have_image Phenomenon98 infrared4)
	(have_image Phenomenon99 infrared4)
))

)
