(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	satellite1 - satellite
	instrument2 - instrument
	satellite2 - satellite
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	satellite3 - satellite
	instrument7 - instrument
	instrument8 - instrument
	satellite4 - satellite
	instrument9 - instrument
	infrared1 - mode
	image0 - mode
	infrared4 - mode
	infrared3 - mode
	thermograph2 - mode
	GroundStation5 - direction
	Star9 - direction
	Star12 - direction
	GroundStation15 - direction
	GroundStation21 - direction
	Star23 - direction
	GroundStation27 - direction
	Star42 - direction
	Star43 - direction
	Star45 - direction
	GroundStation47 - direction
	Star49 - direction
	GroundStation50 - direction
	GroundStation53 - direction
	GroundStation51 - direction
	Star8 - direction
	Star24 - direction
	GroundStation18 - direction
	Star54 - direction
	GroundStation11 - direction
	GroundStation7 - direction
	Star40 - direction
	GroundStation48 - direction
	Star2 - direction
	Star16 - direction
	Star59 - direction
	Star58 - direction
	GroundStation34 - direction
	Star46 - direction
	Star35 - direction
	Star39 - direction
	GroundStation4 - direction
	GroundStation36 - direction
	GroundStation22 - direction
	GroundStation28 - direction
	Star26 - direction
	GroundStation6 - direction
	GroundStation29 - direction
	GroundStation33 - direction
	Star20 - direction
	Star19 - direction
	Star3 - direction
	Star30 - direction
	Star41 - direction
	Star13 - direction
	Star37 - direction
	Star38 - direction
	GroundStation32 - direction
	Star31 - direction
	Star56 - direction
	GroundStation44 - direction
	GroundStation57 - direction
	Star0 - direction
	Star25 - direction
	Star14 - direction
	Star1 - direction
	GroundStation17 - direction
	GroundStation52 - direction
	Star10 - direction
	Star55 - direction
	Phenomenon60 - direction
	Star61 - direction
	Star62 - direction
	Phenomenon63 - direction
	Planet64 - direction
	Star65 - direction
	Planet66 - direction
	Phenomenon67 - direction
	Phenomenon68 - direction
	Phenomenon69 - direction
	Phenomenon70 - direction
	Star71 - direction
	Star72 - direction
	Star73 - direction
	Star74 - direction
	Phenomenon75 - direction
	Planet76 - direction
	Star77 - direction
	Star78 - direction
	Phenomenon79 - direction
	Planet80 - direction
	Planet81 - direction
	Phenomenon82 - direction
	Planet83 - direction
	Planet84 - direction
	Planet85 - direction
	Star86 - direction
	Phenomenon87 - direction
	Star88 - direction
	Star89 - direction
	Phenomenon90 - direction
	Planet91 - direction
	Planet92 - direction
	Star93 - direction
	Star94 - direction
	Star95 - direction
	Planet96 - direction
	Star97 - direction
	Phenomenon98 - direction
	Phenomenon99 - direction
)
(:init
	(supports instrument0 image0)
	(supports instrument0 infrared4)
	(calibration_target instrument0 GroundStation44)
	(calibration_target instrument0 Star26)
	(calibration_target instrument0 GroundStation51)
	(supports instrument1 infrared3)
	(supports instrument1 image0)
	(calibration_target instrument1 Star35)
	(calibration_target instrument1 GroundStation28)
	(calibration_target instrument1 GroundStation18)
	(calibration_target instrument1 GroundStation7)
	(calibration_target instrument1 Star24)
	(calibration_target instrument1 Star25)
	(calibration_target instrument1 Star30)
	(calibration_target instrument1 Star8)
	(calibration_target instrument1 GroundStation22)
	(calibration_target instrument1 GroundStation33)
	(calibration_target instrument1 GroundStation29)
	(calibration_target instrument1 GroundStation52)
	(calibration_target instrument1 Star54)
	(calibration_target instrument1 GroundStation32)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star24)
	(supports instrument2 thermograph2)
	(calibration_target instrument2 Star10)
	(calibration_target instrument2 GroundStation57)
	(calibration_target instrument2 GroundStation6)
	(calibration_target instrument2 GroundStation48)
	(calibration_target instrument2 Star40)
	(calibration_target instrument2 GroundStation7)
	(calibration_target instrument2 Star2)
	(calibration_target instrument2 Star19)
	(calibration_target instrument2 GroundStation11)
	(calibration_target instrument2 GroundStation33)
	(calibration_target instrument2 Star55)
	(calibration_target instrument2 Star54)
	(calibration_target instrument2 Star26)
	(on_board instrument2 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star10)
	(supports instrument3 infrared4)
	(supports instrument3 image0)
	(calibration_target instrument3 GroundStation36)
	(calibration_target instrument3 Star58)
	(calibration_target instrument3 Star59)
	(calibration_target instrument3 Star13)
	(calibration_target instrument3 Star16)
	(calibration_target instrument3 Star39)
	(calibration_target instrument3 Star2)
	(calibration_target instrument3 Star37)
	(calibration_target instrument3 Star56)
	(supports instrument4 infrared1)
	(calibration_target instrument4 Star37)
	(calibration_target instrument4 Star25)
	(calibration_target instrument4 Star46)
	(calibration_target instrument4 Star31)
	(calibration_target instrument4 GroundStation34)
	(supports instrument5 infrared3)
	(supports instrument5 infrared4)
	(supports instrument5 infrared1)
	(calibration_target instrument5 GroundStation4)
	(calibration_target instrument5 Star39)
	(calibration_target instrument5 Star30)
	(calibration_target instrument5 Star35)
	(supports instrument6 infrared3)
	(supports instrument6 image0)
	(supports instrument6 infrared1)
	(calibration_target instrument6 Star26)
	(calibration_target instrument6 GroundStation28)
	(calibration_target instrument6 GroundStation22)
	(calibration_target instrument6 GroundStation44)
	(calibration_target instrument6 Star14)
	(calibration_target instrument6 GroundStation36)
	(on_board instrument3 satellite2)
	(on_board instrument4 satellite2)
	(on_board instrument5 satellite2)
	(on_board instrument6 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star89)
	(supports instrument7 infrared4)
	(supports instrument7 infrared3)
	(calibration_target instrument7 Star19)
	(calibration_target instrument7 Star55)
	(calibration_target instrument7 Star20)
	(calibration_target instrument7 GroundStation33)
	(calibration_target instrument7 GroundStation29)
	(calibration_target instrument7 GroundStation6)
	(supports instrument8 thermograph2)
	(supports instrument8 infrared1)
	(calibration_target instrument8 Star3)
	(on_board instrument7 satellite3)
	(on_board instrument8 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star16)
	(supports instrument9 thermograph2)
	(supports instrument9 infrared4)
	(supports instrument9 infrared1)
	(calibration_target instrument9 Star55)
	(calibration_target instrument9 Star10)
	(calibration_target instrument9 GroundStation52)
	(calibration_target instrument9 GroundStation17)
	(calibration_target instrument9 Star1)
	(calibration_target instrument9 Star14)
	(calibration_target instrument9 Star25)
	(calibration_target instrument9 Star0)
	(calibration_target instrument9 GroundStation57)
	(calibration_target instrument9 GroundStation44)
	(calibration_target instrument9 Star56)
	(calibration_target instrument9 Star31)
	(calibration_target instrument9 GroundStation32)
	(calibration_target instrument9 Star38)
	(calibration_target instrument9 Star37)
	(calibration_target instrument9 Star13)
	(calibration_target instrument9 Star41)
	(calibration_target instrument9 Star30)
	(on_board instrument9 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Phenomenon82)
)
(:goal (and
	(pointing satellite0 Star2)
	(pointing satellite2 GroundStation15)
	(pointing satellite4 Star16)
	(have_image Phenomenon60 infrared4)
	(have_image Star61 infrared4)
	(have_image Star62 thermograph2)
	(have_image Phenomenon63 infrared3)
	(have_image Planet64 thermograph2)
	(have_image Star65 thermograph2)
	(have_image Planet66 thermograph2)
	(have_image Phenomenon67 thermograph2)
	(have_image Phenomenon68 infrared3)
	(have_image Phenomenon69 infrared4)
	(have_image Phenomenon70 infrared1)
	(have_image Star71 infrared4)
	(have_image Star72 infrared4)
	(have_image Star73 infrared1)
	(have_image Star74 thermograph2)
	(have_image Phenomenon75 image0)
	(have_image Planet76 infrared1)
	(have_image Star77 image0)
	(have_image Star78 infrared3)
	(have_image Phenomenon79 infrared1)
	(have_image Planet80 infrared3)
	(have_image Planet81 infrared4)
	(have_image Phenomenon82 thermograph2)
	(have_image Planet83 infrared1)
	(have_image Planet84 image0)
	(have_image Planet85 image0)
	(have_image Star86 infrared3)
	(have_image Phenomenon87 infrared1)
	(have_image Star88 thermograph2)
	(have_image Star89 image0)
	(have_image Phenomenon90 infrared3)
	(have_image Planet91 infrared3)
	(have_image Planet92 thermograph2)
	(have_image Star93 image0)
	(have_image Star94 thermograph2)
	(have_image Star95 thermograph2)
	(have_image Planet96 thermograph2)
	(have_image Star97 infrared3)
	(have_image Phenomenon98 infrared3)
	(have_image Phenomenon99 infrared3)
))

)
