(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	satellite1 - satellite
	instrument4 - instrument
	instrument5 - instrument
	satellite2 - satellite
	instrument6 - instrument
	satellite3 - satellite
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	satellite4 - satellite
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	thermograph1 - mode
	image4 - mode
	infrared2 - mode
	infrared3 - mode
	spectrograph0 - mode
	GroundStation52 - direction
	GroundStation32 - direction
	GroundStation27 - direction
	GroundStation50 - direction
	Star7 - direction
	GroundStation46 - direction
	GroundStation13 - direction
	Star26 - direction
	GroundStation53 - direction
	GroundStation39 - direction
	Star16 - direction
	GroundStation37 - direction
	GroundStation14 - direction
	Star9 - direction
	GroundStation25 - direction
	Star20 - direction
	GroundStation15 - direction
	Star58 - direction
	GroundStation6 - direction
	Star31 - direction
	GroundStation47 - direction
	GroundStation55 - direction
	Star35 - direction
	Star23 - direction
	GroundStation19 - direction
	Star28 - direction
	Star30 - direction
	Star34 - direction
	GroundStation51 - direction
	Star4 - direction
	GroundStation22 - direction
	Star11 - direction
	Star48 - direction
	Star41 - direction
	GroundStation17 - direction
	GroundStation1 - direction
	Star54 - direction
	Star24 - direction
	GroundStation42 - direction
	Star12 - direction
	Star36 - direction
	GroundStation38 - direction
	GroundStation8 - direction
	Star49 - direction
	GroundStation57 - direction
	GroundStation40 - direction
	Star21 - direction
	Star2 - direction
	Star59 - direction
	Star5 - direction
	GroundStation10 - direction
	GroundStation45 - direction
	GroundStation3 - direction
	Star0 - direction
	GroundStation56 - direction
	GroundStation33 - direction
	Star43 - direction
	GroundStation44 - direction
	Star18 - direction
	GroundStation29 - direction
	Phenomenon60 - direction
	Planet61 - direction
	Phenomenon62 - direction
	Planet63 - direction
	Planet64 - direction
	Planet65 - direction
	Planet66 - direction
	Phenomenon67 - direction
	Phenomenon68 - direction
	Star69 - direction
	Planet70 - direction
	Phenomenon71 - direction
	Phenomenon72 - direction
	Star73 - direction
	Star74 - direction
	Star75 - direction
	Star76 - direction
	Planet77 - direction
	Star78 - direction
	Star79 - direction
	Star80 - direction
	Star81 - direction
	Planet82 - direction
	Planet83 - direction
	Phenomenon84 - direction
	Star85 - direction
	Planet86 - direction
	Phenomenon87 - direction
	Planet88 - direction
	Phenomenon89 - direction
	Phenomenon90 - direction
	Star91 - direction
	Planet92 - direction
	Planet93 - direction
	Planet94 - direction
	Phenomenon95 - direction
	Star96 - direction
	Star97 - direction
	Phenomenon98 - direction
	Star99 - direction
)
(:init
	(supports instrument0 infrared3)
	(supports instrument0 image4)
	(supports instrument0 infrared2)
	(calibration_target instrument0 Star49)
	(calibration_target instrument0 GroundStation40)
	(calibration_target instrument0 GroundStation57)
	(calibration_target instrument0 GroundStation46)
	(calibration_target instrument0 GroundStation1)
	(calibration_target instrument0 Star9)
	(calibration_target instrument0 Star36)
	(supports instrument1 infrared2)
	(supports instrument1 spectrograph0)
	(calibration_target instrument1 Star41)
	(calibration_target instrument1 GroundStation17)
	(calibration_target instrument1 GroundStation10)
	(calibration_target instrument1 Star36)
	(calibration_target instrument1 GroundStation32)
	(calibration_target instrument1 Star11)
	(supports instrument2 infrared2)
	(supports instrument2 thermograph1)
	(supports instrument2 spectrograph0)
	(calibration_target instrument2 GroundStation19)
	(calibration_target instrument2 Star5)
	(calibration_target instrument2 GroundStation29)
	(calibration_target instrument2 GroundStation8)
	(calibration_target instrument2 GroundStation51)
	(calibration_target instrument2 GroundStation45)
	(calibration_target instrument2 GroundStation50)
	(calibration_target instrument2 GroundStation27)
	(calibration_target instrument2 Star16)
	(calibration_target instrument2 Star36)
	(calibration_target instrument2 GroundStation32)
	(calibration_target instrument2 Star59)
	(calibration_target instrument2 Star30)
	(calibration_target instrument2 Star18)
	(calibration_target instrument2 GroundStation33)
	(supports instrument3 spectrograph0)
	(supports instrument3 infrared3)
	(calibration_target instrument3 GroundStation55)
	(calibration_target instrument3 GroundStation13)
	(calibration_target instrument3 GroundStation47)
	(calibration_target instrument3 Star20)
	(calibration_target instrument3 GroundStation53)
	(calibration_target instrument3 Star11)
	(calibration_target instrument3 Star7)
	(calibration_target instrument3 Star43)
	(calibration_target instrument3 Star48)
	(calibration_target instrument3 GroundStation56)
	(calibration_target instrument3 GroundStation17)
	(calibration_target instrument3 GroundStation45)
	(calibration_target instrument3 Star21)
	(calibration_target instrument3 Star2)
	(calibration_target instrument3 Star23)
	(calibration_target instrument3 GroundStation37)
	(calibration_target instrument3 GroundStation46)
	(calibration_target instrument3 GroundStation19)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Planet93)
	(supports instrument4 infrared2)
	(calibration_target instrument4 GroundStation1)
	(calibration_target instrument4 Star4)
	(calibration_target instrument4 GroundStation33)
	(calibration_target instrument4 GroundStation57)
	(calibration_target instrument4 GroundStation6)
	(calibration_target instrument4 GroundStation53)
	(calibration_target instrument4 Star31)
	(calibration_target instrument4 Star0)
	(calibration_target instrument4 GroundStation17)
	(calibration_target instrument4 GroundStation46)
	(supports instrument5 infrared2)
	(calibration_target instrument5 GroundStation46)
	(calibration_target instrument5 Star58)
	(calibration_target instrument5 GroundStation40)
	(calibration_target instrument5 Star54)
	(calibration_target instrument5 Star2)
	(calibration_target instrument5 Star41)
	(calibration_target instrument5 GroundStation47)
	(calibration_target instrument5 GroundStation25)
	(calibration_target instrument5 Star7)
	(calibration_target instrument5 GroundStation17)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star74)
	(supports instrument6 image4)
	(supports instrument6 thermograph1)
	(supports instrument6 infrared3)
	(calibration_target instrument6 Star30)
	(calibration_target instrument6 GroundStation29)
	(calibration_target instrument6 GroundStation39)
	(calibration_target instrument6 GroundStation40)
	(calibration_target instrument6 Star4)
	(calibration_target instrument6 Star58)
	(calibration_target instrument6 GroundStation22)
	(calibration_target instrument6 Star21)
	(calibration_target instrument6 GroundStation57)
	(calibration_target instrument6 Star20)
	(calibration_target instrument6 GroundStation13)
	(calibration_target instrument6 Star11)
	(calibration_target instrument6 GroundStation38)
	(calibration_target instrument6 GroundStation3)
	(calibration_target instrument6 Star23)
	(calibration_target instrument6 GroundStation37)
	(calibration_target instrument6 GroundStation15)
	(calibration_target instrument6 Star43)
	(on_board instrument6 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star91)
	(supports instrument7 infrared3)
	(supports instrument7 infrared2)
	(calibration_target instrument7 Star31)
	(calibration_target instrument7 Star26)
	(supports instrument8 thermograph1)
	(supports instrument8 image4)
	(calibration_target instrument8 Star41)
	(calibration_target instrument8 GroundStation47)
	(calibration_target instrument8 Star16)
	(calibration_target instrument8 GroundStation39)
	(calibration_target instrument8 Star58)
	(calibration_target instrument8 Star9)
	(calibration_target instrument8 GroundStation42)
	(calibration_target instrument8 GroundStation53)
	(calibration_target instrument8 GroundStation17)
	(calibration_target instrument8 GroundStation6)
	(calibration_target instrument8 GroundStation14)
	(supports instrument9 image4)
	(supports instrument9 infrared2)
	(calibration_target instrument9 Star34)
	(calibration_target instrument9 GroundStation6)
	(calibration_target instrument9 Star58)
	(calibration_target instrument9 GroundStation33)
	(calibration_target instrument9 Star48)
	(calibration_target instrument9 GroundStation15)
	(calibration_target instrument9 Star24)
	(calibration_target instrument9 Star20)
	(calibration_target instrument9 GroundStation25)
	(calibration_target instrument9 Star9)
	(calibration_target instrument9 GroundStation14)
	(calibration_target instrument9 GroundStation37)
	(supports instrument10 infrared2)
	(supports instrument10 spectrograph0)
	(calibration_target instrument10 Star11)
	(calibration_target instrument10 Star2)
	(calibration_target instrument10 GroundStation22)
	(calibration_target instrument10 Star4)
	(calibration_target instrument10 GroundStation51)
	(calibration_target instrument10 GroundStation3)
	(calibration_target instrument10 Star34)
	(calibration_target instrument10 Star30)
	(calibration_target instrument10 Star12)
	(calibration_target instrument10 Star28)
	(calibration_target instrument10 GroundStation19)
	(calibration_target instrument10 Star23)
	(calibration_target instrument10 Star48)
	(calibration_target instrument10 Star18)
	(calibration_target instrument10 Star35)
	(calibration_target instrument10 GroundStation55)
	(calibration_target instrument10 Star21)
	(calibration_target instrument10 GroundStation10)
	(calibration_target instrument10 GroundStation47)
	(calibration_target instrument10 Star31)
	(on_board instrument7 satellite3)
	(on_board instrument8 satellite3)
	(on_board instrument9 satellite3)
	(on_board instrument10 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation47)
	(supports instrument11 spectrograph0)
	(supports instrument11 thermograph1)
	(supports instrument11 image4)
	(calibration_target instrument11 Star36)
	(calibration_target instrument11 Star21)
	(calibration_target instrument11 GroundStation10)
	(calibration_target instrument11 Star12)
	(calibration_target instrument11 Star43)
	(calibration_target instrument11 GroundStation42)
	(calibration_target instrument11 Star59)
	(calibration_target instrument11 Star24)
	(calibration_target instrument11 Star54)
	(calibration_target instrument11 GroundStation1)
	(calibration_target instrument11 GroundStation17)
	(calibration_target instrument11 Star41)
	(calibration_target instrument11 Star2)
	(calibration_target instrument11 Star48)
	(calibration_target instrument11 GroundStation3)
	(calibration_target instrument11 Star5)
	(supports instrument12 infrared3)
	(supports instrument12 thermograph1)
	(supports instrument12 infrared2)
	(calibration_target instrument12 Star5)
	(calibration_target instrument12 Star59)
	(calibration_target instrument12 Star2)
	(calibration_target instrument12 Star21)
	(calibration_target instrument12 GroundStation40)
	(calibration_target instrument12 GroundStation57)
	(calibration_target instrument12 Star43)
	(calibration_target instrument12 Star49)
	(calibration_target instrument12 Star0)
	(calibration_target instrument12 GroundStation8)
	(calibration_target instrument12 GroundStation38)
	(calibration_target instrument12 GroundStation56)
	(supports instrument13 infrared2)
	(supports instrument13 image4)
	(calibration_target instrument13 GroundStation29)
	(calibration_target instrument13 Star18)
	(calibration_target instrument13 GroundStation44)
	(calibration_target instrument13 Star43)
	(calibration_target instrument13 GroundStation33)
	(calibration_target instrument13 GroundStation56)
	(calibration_target instrument13 Star0)
	(calibration_target instrument13 GroundStation3)
	(calibration_target instrument13 GroundStation45)
	(calibration_target instrument13 GroundStation10)
	(on_board instrument11 satellite4)
	(on_board instrument12 satellite4)
	(on_board instrument13 satellite4)
	(power_avail satellite4)
	(pointing satellite4 GroundStation57)
)
(:goal (and
	(pointing satellite0 GroundStation14)
	(pointing satellite3 Planet66)
	(have_image Phenomenon60 thermograph1)
	(have_image Planet61 infrared3)
	(have_image Phenomenon62 infrared3)
	(have_image Planet63 spectrograph0)
	(have_image Planet64 infrared2)
	(have_image Planet65 spectrograph0)
	(have_image Planet66 infrared3)
	(have_image Phenomenon67 infrared2)
	(have_image Phenomenon68 infrared2)
	(have_image Star69 infrared2)
	(have_image Planet70 spectrograph0)
	(have_image Phenomenon71 spectrograph0)
	(have_image Phenomenon72 spectrograph0)
	(have_image Star73 infrared3)
	(have_image Star74 image4)
	(have_image Star75 infrared2)
	(have_image Star76 thermograph1)
	(have_image Planet77 thermograph1)
	(have_image Star78 image4)
	(have_image Star79 spectrograph0)
	(have_image Star80 thermograph1)
	(have_image Star81 thermograph1)
	(have_image Planet82 thermograph1)
	(have_image Planet83 thermograph1)
	(have_image Phenomenon84 image4)
	(have_image Star85 infrared2)
	(have_image Planet86 infrared2)
	(have_image Phenomenon87 infrared3)
	(have_image Planet88 spectrograph0)
	(have_image Phenomenon89 thermograph1)
	(have_image Phenomenon90 thermograph1)
	(have_image Star91 thermograph1)
	(have_image Planet92 image4)
	(have_image Planet93 infrared3)
	(have_image Planet94 thermograph1)
	(have_image Phenomenon95 spectrograph0)
	(have_image Star96 infrared2)
	(have_image Star97 spectrograph0)
	(have_image Phenomenon98 image4)
	(have_image Star99 spectrograph0)
))

)
