(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	satellite1 - satellite
	instrument2 - instrument
	satellite2 - satellite
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	thermograph1 - mode
	infrared3 - mode
	image0 - mode
	spectrograph2 - mode
	Star0 - direction
	GroundStation7 - direction
	GroundStation8 - direction
	GroundStation14 - direction
	GroundStation5 - direction
	GroundStation15 - direction
	Star24 - direction
	Star10 - direction
	GroundStation22 - direction
	Star4 - direction
	Star16 - direction
	Star18 - direction
	Star21 - direction
	Star29 - direction
	GroundStation9 - direction
	Star17 - direction
	Star13 - direction
	GroundStation12 - direction
	Star26 - direction
	Star3 - direction
	GroundStation2 - direction
	GroundStation6 - direction
	GroundStation11 - direction
	GroundStation27 - direction
	Star1 - direction
	Star23 - direction
	GroundStation25 - direction
	GroundStation19 - direction
	Star20 - direction
	GroundStation28 - direction
	Phenomenon30 - direction
	Phenomenon31 - direction
	Phenomenon32 - direction
	Phenomenon33 - direction
	Planet34 - direction
	Planet35 - direction
	Star36 - direction
	Phenomenon37 - direction
	Planet38 - direction
	Phenomenon39 - direction
	Star40 - direction
	Phenomenon41 - direction
	Planet42 - direction
	Star43 - direction
	Planet44 - direction
	Planet45 - direction
	Phenomenon46 - direction
	Phenomenon47 - direction
	Planet48 - direction
	Phenomenon49 - direction
)
(:init
	(supports instrument0 thermograph1)
	(supports instrument0 image0)
	(supports instrument0 spectrograph2)
	(calibration_target instrument0 GroundStation9)
	(calibration_target instrument0 GroundStation6)
	(calibration_target instrument0 Star17)
	(calibration_target instrument0 Star16)
	(calibration_target instrument0 Star24)
	(calibration_target instrument0 GroundStation15)
	(calibration_target instrument0 GroundStation5)
	(calibration_target instrument0 GroundStation2)
	(calibration_target instrument0 Star3)
	(supports instrument1 infrared3)
	(supports instrument1 thermograph1)
	(supports instrument1 spectrograph2)
	(calibration_target instrument1 Star17)
	(calibration_target instrument1 Star18)
	(calibration_target instrument1 GroundStation9)
	(calibration_target instrument1 Star26)
	(calibration_target instrument1 GroundStation27)
	(calibration_target instrument1 GroundStation19)
	(calibration_target instrument1 GroundStation22)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star24)
	(supports instrument2 infrared3)
	(calibration_target instrument2 Star4)
	(calibration_target instrument2 GroundStation22)
	(calibration_target instrument2 Star3)
	(calibration_target instrument2 Star10)
	(calibration_target instrument2 GroundStation28)
	(calibration_target instrument2 GroundStation19)
	(calibration_target instrument2 GroundStation27)
	(on_board instrument2 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation5)
	(supports instrument3 spectrograph2)
	(supports instrument3 thermograph1)
	(supports instrument3 image0)
	(calibration_target instrument3 Star17)
	(calibration_target instrument3 GroundStation2)
	(calibration_target instrument3 GroundStation6)
	(calibration_target instrument3 Star16)
	(supports instrument4 spectrograph2)
	(supports instrument4 image0)
	(supports instrument4 thermograph1)
	(calibration_target instrument4 Star18)
	(calibration_target instrument4 Star29)
	(calibration_target instrument4 Star20)
	(supports instrument5 image0)
	(supports instrument5 infrared3)
	(calibration_target instrument5 GroundStation6)
	(calibration_target instrument5 GroundStation2)
	(calibration_target instrument5 Star3)
	(calibration_target instrument5 Star26)
	(calibration_target instrument5 GroundStation12)
	(calibration_target instrument5 Star13)
	(calibration_target instrument5 Star17)
	(calibration_target instrument5 GroundStation9)
	(calibration_target instrument5 Star29)
	(calibration_target instrument5 Star21)
	(supports instrument6 thermograph1)
	(calibration_target instrument6 GroundStation28)
	(calibration_target instrument6 Star20)
	(calibration_target instrument6 GroundStation19)
	(calibration_target instrument6 GroundStation25)
	(calibration_target instrument6 Star23)
	(calibration_target instrument6 Star1)
	(calibration_target instrument6 GroundStation27)
	(calibration_target instrument6 GroundStation11)
	(on_board instrument3 satellite2)
	(on_board instrument4 satellite2)
	(on_board instrument5 satellite2)
	(on_board instrument6 satellite2)
	(power_avail satellite2)
	(pointing satellite2 GroundStation22)
)
(:goal (and
	(pointing satellite0 Star16)
	(pointing satellite2 Star20)
	(have_image Phenomenon30 image0)
	(have_image Phenomenon31 image0)
	(have_image Phenomenon32 image0)
	(have_image Phenomenon33 thermograph1)
	(have_image Planet34 infrared3)
	(have_image Planet35 thermograph1)
	(have_image Star36 thermograph1)
	(have_image Phenomenon37 infrared3)
	(have_image Planet38 infrared3)
	(have_image Phenomenon39 spectrograph2)
	(have_image Star40 thermograph1)
	(have_image Phenomenon41 thermograph1)
	(have_image Planet42 image0)
	(have_image Star43 image0)
	(have_image Planet44 spectrograph2)
	(have_image Planet45 image0)
	(have_image Phenomenon46 spectrograph2)
	(have_image Phenomenon47 spectrograph2)
	(have_image Planet48 spectrograph2)
	(have_image Phenomenon49 spectrograph2)
))

)
