(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	satellite1 - satellite
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	satellite2 - satellite
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	satellite3 - satellite
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	satellite4 - satellite
	instrument13 - instrument
	spectrograph0 - mode
	image4 - mode
	image3 - mode
	image2 - mode
	infrared1 - mode
	Star3 - direction
	Star6 - direction
	Star15 - direction
	GroundStation33 - direction
	Star26 - direction
	GroundStation27 - direction
	GroundStation10 - direction
	Star59 - direction
	GroundStation54 - direction
	GroundStation35 - direction
	Star44 - direction
	GroundStation23 - direction
	GroundStation53 - direction
	Star42 - direction
	Star37 - direction
	Star45 - direction
	Star24 - direction
	Star36 - direction
	GroundStation22 - direction
	GroundStation39 - direction
	Star56 - direction
	GroundStation58 - direction
	Star55 - direction
	GroundStation1 - direction
	GroundStation38 - direction
	GroundStation32 - direction
	Star12 - direction
	Star8 - direction
	Star40 - direction
	Star7 - direction
	Star47 - direction
	Star14 - direction
	GroundStation11 - direction
	GroundStation49 - direction
	GroundStation31 - direction
	GroundStation9 - direction
	Star50 - direction
	GroundStation20 - direction
	GroundStation52 - direction
	GroundStation4 - direction
	GroundStation25 - direction
	Star48 - direction
	GroundStation21 - direction
	Star30 - direction
	Star5 - direction
	GroundStation57 - direction
	Star29 - direction
	Star18 - direction
	GroundStation34 - direction
	Star46 - direction
	GroundStation2 - direction
	Star43 - direction
	GroundStation41 - direction
	Star51 - direction
	GroundStation28 - direction
	GroundStation19 - direction
	Star0 - direction
	GroundStation16 - direction
	Star13 - direction
	Star17 - direction
	Star60 - direction
	Star61 - direction
	Planet62 - direction
	Phenomenon63 - direction
	Planet64 - direction
	Star65 - direction
	Star66 - direction
	Star67 - direction
	Star68 - direction
	Planet69 - direction
	Planet70 - direction
	Planet71 - direction
	Star72 - direction
	Phenomenon73 - direction
	Phenomenon74 - direction
	Phenomenon75 - direction
	Phenomenon76 - direction
	Phenomenon77 - direction
	Star78 - direction
	Phenomenon79 - direction
	Star80 - direction
	Star81 - direction
	Star82 - direction
	Planet83 - direction
	Star84 - direction
	Planet85 - direction
	Phenomenon86 - direction
	Phenomenon87 - direction
	Planet88 - direction
	Star89 - direction
	Star90 - direction
	Star91 - direction
	Planet92 - direction
	Phenomenon93 - direction
	Planet94 - direction
	Phenomenon95 - direction
	Phenomenon96 - direction
	Planet97 - direction
	Planet98 - direction
	Planet99 - direction
)
(:init
	(supports instrument0 image2)
	(supports instrument0 image4)
	(supports instrument0 spectrograph0)
	(calibration_target instrument0 GroundStation10)
	(calibration_target instrument0 GroundStation23)
	(calibration_target instrument0 GroundStation27)
	(calibration_target instrument0 Star59)
	(calibration_target instrument0 Star29)
	(calibration_target instrument0 GroundStation22)
	(calibration_target instrument0 GroundStation19)
	(calibration_target instrument0 Star56)
	(calibration_target instrument0 GroundStation4)
	(calibration_target instrument0 Star26)
	(calibration_target instrument0 GroundStation2)
	(calibration_target instrument0 GroundStation49)
	(calibration_target instrument0 Star18)
	(calibration_target instrument0 Star24)
	(calibration_target instrument0 Star47)
	(on_board instrument0 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star14)
	(supports instrument1 image4)
	(supports instrument1 image2)
	(calibration_target instrument1 Star18)
	(calibration_target instrument1 GroundStation58)
	(calibration_target instrument1 Star14)
	(calibration_target instrument1 Star12)
	(calibration_target instrument1 Star43)
	(calibration_target instrument1 GroundStation28)
	(calibration_target instrument1 GroundStation10)
	(calibration_target instrument1 GroundStation54)
	(calibration_target instrument1 GroundStation35)
	(calibration_target instrument1 GroundStation19)
	(calibration_target instrument1 Star7)
	(calibration_target instrument1 Star55)
	(calibration_target instrument1 GroundStation34)
	(calibration_target instrument1 GroundStation39)
	(calibration_target instrument1 Star0)
	(calibration_target instrument1 Star13)
	(calibration_target instrument1 GroundStation52)
	(calibration_target instrument1 Star30)
	(supports instrument2 image3)
	(calibration_target instrument2 GroundStation22)
	(calibration_target instrument2 Star36)
	(calibration_target instrument2 GroundStation52)
	(calibration_target instrument2 GroundStation41)
	(calibration_target instrument2 GroundStation23)
	(calibration_target instrument2 GroundStation20)
	(calibration_target instrument2 Star44)
	(calibration_target instrument2 GroundStation35)
	(calibration_target instrument2 GroundStation54)
	(calibration_target instrument2 Star59)
	(calibration_target instrument2 GroundStation58)
	(calibration_target instrument2 Star50)
	(calibration_target instrument2 GroundStation1)
	(supports instrument3 spectrograph0)
	(calibration_target instrument3 Star56)
	(calibration_target instrument3 GroundStation20)
	(calibration_target instrument3 GroundStation23)
	(calibration_target instrument3 Star14)
	(calibration_target instrument3 Star0)
	(calibration_target instrument3 Star37)
	(supports instrument4 infrared1)
	(calibration_target instrument4 Star30)
	(calibration_target instrument4 GroundStation4)
	(calibration_target instrument4 Star17)
	(calibration_target instrument4 GroundStation16)
	(calibration_target instrument4 GroundStation34)
	(calibration_target instrument4 GroundStation28)
	(calibration_target instrument4 GroundStation19)
	(on_board instrument1 satellite1)
	(on_board instrument2 satellite1)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation9)
	(supports instrument5 spectrograph0)
	(supports instrument5 image3)
	(calibration_target instrument5 GroundStation4)
	(calibration_target instrument5 Star24)
	(calibration_target instrument5 Star46)
	(calibration_target instrument5 Star45)
	(calibration_target instrument5 Star7)
	(calibration_target instrument5 GroundStation58)
	(calibration_target instrument5 Star37)
	(calibration_target instrument5 Star30)
	(calibration_target instrument5 Star36)
	(calibration_target instrument5 GroundStation28)
	(calibration_target instrument5 GroundStation39)
	(calibration_target instrument5 Star47)
	(calibration_target instrument5 Star55)
	(calibration_target instrument5 Star12)
	(calibration_target instrument5 Star8)
	(calibration_target instrument5 Star42)
	(calibration_target instrument5 GroundStation53)
	(calibration_target instrument5 GroundStation25)
	(calibration_target instrument5 GroundStation21)
	(calibration_target instrument5 Star40)
	(supports instrument6 spectrograph0)
	(supports instrument6 image3)
	(calibration_target instrument6 GroundStation22)
	(calibration_target instrument6 Star36)
	(supports instrument7 infrared1)
	(calibration_target instrument7 GroundStation19)
	(calibration_target instrument7 GroundStation28)
	(calibration_target instrument7 GroundStation39)
	(supports instrument8 infrared1)
	(calibration_target instrument8 Star55)
	(calibration_target instrument8 Star17)
	(calibration_target instrument8 GroundStation58)
	(calibration_target instrument8 GroundStation21)
	(calibration_target instrument8 Star56)
	(calibration_target instrument8 GroundStation34)
	(on_board instrument5 satellite2)
	(on_board instrument6 satellite2)
	(on_board instrument7 satellite2)
	(on_board instrument8 satellite2)
	(power_avail satellite2)
	(pointing satellite2 GroundStation31)
	(supports instrument9 spectrograph0)
	(calibration_target instrument9 GroundStation34)
	(calibration_target instrument9 Star14)
	(calibration_target instrument9 Star47)
	(calibration_target instrument9 Star43)
	(calibration_target instrument9 Star7)
	(calibration_target instrument9 Star50)
	(calibration_target instrument9 Star40)
	(calibration_target instrument9 Star8)
	(calibration_target instrument9 Star12)
	(calibration_target instrument9 Star13)
	(calibration_target instrument9 GroundStation2)
	(calibration_target instrument9 GroundStation41)
	(calibration_target instrument9 Star5)
	(calibration_target instrument9 GroundStation21)
	(calibration_target instrument9 GroundStation31)
	(calibration_target instrument9 GroundStation32)
	(calibration_target instrument9 GroundStation38)
	(calibration_target instrument9 GroundStation1)
	(supports instrument10 infrared1)
	(supports instrument10 spectrograph0)
	(supports instrument10 image4)
	(calibration_target instrument10 GroundStation11)
	(supports instrument11 infrared1)
	(calibration_target instrument11 Star29)
	(calibration_target instrument11 GroundStation57)
	(calibration_target instrument11 Star0)
	(calibration_target instrument11 Star5)
	(calibration_target instrument11 Star43)
	(calibration_target instrument11 Star30)
	(calibration_target instrument11 GroundStation21)
	(calibration_target instrument11 Star48)
	(calibration_target instrument11 GroundStation25)
	(calibration_target instrument11 Star17)
	(calibration_target instrument11 GroundStation28)
	(calibration_target instrument11 GroundStation4)
	(calibration_target instrument11 GroundStation52)
	(calibration_target instrument11 GroundStation16)
	(calibration_target instrument11 GroundStation20)
	(calibration_target instrument11 Star50)
	(calibration_target instrument11 GroundStation9)
	(calibration_target instrument11 GroundStation31)
	(calibration_target instrument11 GroundStation49)
	(calibration_target instrument11 Star51)
	(supports instrument12 image3)
	(calibration_target instrument12 Star13)
	(calibration_target instrument12 GroundStation16)
	(calibration_target instrument12 Star0)
	(calibration_target instrument12 GroundStation19)
	(calibration_target instrument12 GroundStation28)
	(calibration_target instrument12 Star51)
	(calibration_target instrument12 GroundStation41)
	(calibration_target instrument12 Star43)
	(calibration_target instrument12 GroundStation2)
	(calibration_target instrument12 Star46)
	(calibration_target instrument12 GroundStation34)
	(calibration_target instrument12 Star18)
	(on_board instrument9 satellite3)
	(on_board instrument10 satellite3)
	(on_board instrument11 satellite3)
	(on_board instrument12 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star59)
	(supports instrument13 image3)
	(calibration_target instrument13 Star17)
	(on_board instrument13 satellite4)
	(power_avail satellite4)
	(pointing satellite4 GroundStation49)
)
(:goal (and
	(pointing satellite1 GroundStation38)
	(pointing satellite2 Star51)
	(pointing satellite3 Phenomenon96)
	(have_image Star60 image4)
	(have_image Star61 image3)
	(have_image Planet62 image4)
	(have_image Phenomenon63 image4)
	(have_image Planet64 infrared1)
	(have_image Star65 image2)
	(have_image Star66 image4)
	(have_image Star67 spectrograph0)
	(have_image Star68 image3)
	(have_image Planet69 image2)
	(have_image Planet70 image3)
	(have_image Planet71 image2)
	(have_image Star72 image3)
	(have_image Phenomenon73 image4)
	(have_image Phenomenon74 spectrograph0)
	(have_image Phenomenon75 spectrograph0)
	(have_image Phenomenon76 infrared1)
	(have_image Phenomenon77 image2)
	(have_image Star78 image4)
	(have_image Phenomenon79 image3)
	(have_image Star80 spectrograph0)
	(have_image Star81 infrared1)
	(have_image Star82 spectrograph0)
	(have_image Planet83 image2)
	(have_image Star84 spectrograph0)
	(have_image Planet85 spectrograph0)
	(have_image Phenomenon86 image4)
	(have_image Phenomenon87 infrared1)
	(have_image Planet88 infrared1)
	(have_image Star89 image3)
	(have_image Star90 infrared1)
	(have_image Star91 image3)
	(have_image Planet92 image4)
	(have_image Phenomenon93 image2)
	(have_image Planet94 spectrograph0)
	(have_image Phenomenon95 image4)
	(have_image Phenomenon96 infrared1)
	(have_image Planet97 infrared1)
	(have_image Planet98 image3)
	(have_image Planet99 spectrograph0)
))

)
