(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	satellite1 - satellite
	instrument4 - instrument
	satellite2 - satellite
	instrument5 - instrument
	instrument6 - instrument
	satellite3 - satellite
	instrument7 - instrument
	satellite4 - satellite
	instrument8 - instrument
	image0 - mode
	thermograph2 - mode
	thermograph4 - mode
	thermograph1 - mode
	infrared3 - mode
	GroundStation4 - direction
	Star5 - direction
	GroundStation7 - direction
	GroundStation17 - direction
	GroundStation18 - direction
	Star19 - direction
	Star30 - direction
	Star31 - direction
	Star37 - direction
	Star40 - direction
	Star43 - direction
	GroundStation49 - direction
	Star51 - direction
	GroundStation53 - direction
	GroundStation50 - direction
	Star12 - direction
	GroundStation32 - direction
	GroundStation52 - direction
	Star54 - direction
	GroundStation45 - direction
	Star14 - direction
	Star36 - direction
	GroundStation25 - direction
	Star20 - direction
	Star27 - direction
	GroundStation3 - direction
	Star21 - direction
	Star38 - direction
	GroundStation1 - direction
	GroundStation56 - direction
	Star13 - direction
	Star0 - direction
	Star10 - direction
	Star33 - direction
	GroundStation44 - direction
	Star23 - direction
	Star26 - direction
	Star42 - direction
	Star15 - direction
	Star46 - direction
	Star22 - direction
	GroundStation47 - direction
	Star9 - direction
	GroundStation16 - direction
	Star2 - direction
	Star55 - direction
	Star35 - direction
	Star41 - direction
	GroundStation29 - direction
	Star57 - direction
	Star59 - direction
	GroundStation11 - direction
	GroundStation24 - direction
	GroundStation6 - direction
	GroundStation34 - direction
	Star28 - direction
	GroundStation48 - direction
	Star8 - direction
	GroundStation39 - direction
	Star58 - direction
	Phenomenon60 - direction
	Phenomenon61 - direction
	Phenomenon62 - direction
	Phenomenon63 - direction
	Phenomenon64 - direction
	Planet65 - direction
	Star66 - direction
	Star67 - direction
	Star68 - direction
	Star69 - direction
	Phenomenon70 - direction
	Planet71 - direction
	Planet72 - direction
	Star73 - direction
	Phenomenon74 - direction
	Planet75 - direction
	Planet76 - direction
	Planet77 - direction
	Phenomenon78 - direction
	Phenomenon79 - direction
	Planet80 - direction
	Star81 - direction
	Planet82 - direction
	Star83 - direction
	Phenomenon84 - direction
	Planet85 - direction
	Phenomenon86 - direction
	Star87 - direction
	Star88 - direction
	Star89 - direction
	Planet90 - direction
	Star91 - direction
	Planet92 - direction
	Planet93 - direction
	Planet94 - direction
	Planet95 - direction
	Phenomenon96 - direction
	Star97 - direction
	Planet98 - direction
	Phenomenon99 - direction
)
(:init
	(supports instrument0 image0)
	(supports instrument0 infrared3)
	(calibration_target instrument0 Star38)
	(calibration_target instrument0 GroundStation25)
	(calibration_target instrument0 Star9)
	(calibration_target instrument0 GroundStation34)
	(calibration_target instrument0 Star13)
	(calibration_target instrument0 GroundStation50)
	(calibration_target instrument0 GroundStation24)
	(supports instrument1 thermograph1)
	(calibration_target instrument1 GroundStation32)
	(calibration_target instrument1 Star21)
	(calibration_target instrument1 Star57)
	(calibration_target instrument1 Star12)
	(supports instrument2 image0)
	(supports instrument2 thermograph4)
	(calibration_target instrument2 Star10)
	(calibration_target instrument2 GroundStation56)
	(calibration_target instrument2 Star14)
	(calibration_target instrument2 GroundStation45)
	(calibration_target instrument2 Star38)
	(calibration_target instrument2 Star54)
	(calibration_target instrument2 GroundStation24)
	(calibration_target instrument2 GroundStation52)
	(calibration_target instrument2 Star8)
	(calibration_target instrument2 Star20)
	(calibration_target instrument2 Star58)
	(supports instrument3 thermograph2)
	(supports instrument3 infrared3)
	(supports instrument3 thermograph4)
	(calibration_target instrument3 Star21)
	(calibration_target instrument3 Star35)
	(calibration_target instrument3 Star33)
	(calibration_target instrument3 GroundStation29)
	(calibration_target instrument3 GroundStation48)
	(calibration_target instrument3 GroundStation11)
	(calibration_target instrument3 Star46)
	(calibration_target instrument3 Star15)
	(calibration_target instrument3 GroundStation3)
	(calibration_target instrument3 Star27)
	(calibration_target instrument3 Star10)
	(calibration_target instrument3 Star20)
	(calibration_target instrument3 Star41)
	(calibration_target instrument3 Star26)
	(calibration_target instrument3 Star59)
	(calibration_target instrument3 Star55)
	(calibration_target instrument3 GroundStation25)
	(calibration_target instrument3 GroundStation44)
	(calibration_target instrument3 Star36)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Planet77)
	(supports instrument4 thermograph2)
	(supports instrument4 thermograph4)
	(supports instrument4 image0)
	(calibration_target instrument4 GroundStation56)
	(calibration_target instrument4 GroundStation1)
	(calibration_target instrument4 Star38)
	(calibration_target instrument4 GroundStation6)
	(calibration_target instrument4 Star28)
	(on_board instrument4 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Planet76)
	(supports instrument5 thermograph4)
	(supports instrument5 thermograph1)
	(calibration_target instrument5 Star13)
	(calibration_target instrument5 Star15)
	(supports instrument6 infrared3)
	(supports instrument6 thermograph2)
	(supports instrument6 thermograph1)
	(calibration_target instrument6 Star26)
	(calibration_target instrument6 Star23)
	(calibration_target instrument6 GroundStation44)
	(calibration_target instrument6 GroundStation47)
	(calibration_target instrument6 GroundStation39)
	(calibration_target instrument6 Star33)
	(calibration_target instrument6 Star10)
	(calibration_target instrument6 Star15)
	(calibration_target instrument6 Star0)
	(calibration_target instrument6 Star13)
	(calibration_target instrument6 Star8)
	(calibration_target instrument6 Star46)
	(on_board instrument5 satellite2)
	(on_board instrument6 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Phenomenon64)
	(supports instrument7 image0)
	(supports instrument7 infrared3)
	(calibration_target instrument7 GroundStation24)
	(calibration_target instrument7 GroundStation11)
	(calibration_target instrument7 Star59)
	(calibration_target instrument7 Star57)
	(calibration_target instrument7 GroundStation29)
	(calibration_target instrument7 Star41)
	(calibration_target instrument7 GroundStation39)
	(calibration_target instrument7 Star58)
	(calibration_target instrument7 Star35)
	(calibration_target instrument7 Star55)
	(calibration_target instrument7 Star2)
	(calibration_target instrument7 GroundStation16)
	(calibration_target instrument7 Star9)
	(calibration_target instrument7 GroundStation47)
	(calibration_target instrument7 Star22)
	(calibration_target instrument7 Star46)
	(calibration_target instrument7 Star15)
	(calibration_target instrument7 Star42)
	(on_board instrument7 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation52)
	(supports instrument8 thermograph4)
	(calibration_target instrument8 Star58)
	(calibration_target instrument8 GroundStation39)
	(calibration_target instrument8 Star8)
	(calibration_target instrument8 GroundStation48)
	(calibration_target instrument8 Star28)
	(calibration_target instrument8 GroundStation34)
	(calibration_target instrument8 GroundStation6)
	(on_board instrument8 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star30)
)
(:goal (and
	(pointing satellite0 Star37)
	(pointing satellite1 Star88)
	(pointing satellite2 GroundStation3)
	(have_image Phenomenon60 thermograph1)
	(have_image Phenomenon61 thermograph2)
	(have_image Phenomenon62 thermograph4)
	(have_image Phenomenon63 thermograph4)
	(have_image Phenomenon64 thermograph4)
	(have_image Planet65 image0)
	(have_image Star66 thermograph2)
	(have_image Star67 infrared3)
	(have_image Star68 thermograph2)
	(have_image Star69 thermograph4)
	(have_image Phenomenon70 thermograph2)
	(have_image Planet71 infrared3)
	(have_image Planet72 thermograph4)
	(have_image Star73 image0)
	(have_image Phenomenon74 thermograph1)
	(have_image Planet75 thermograph4)
	(have_image Planet76 thermograph2)
	(have_image Planet77 infrared3)
	(have_image Phenomenon78 infrared3)
	(have_image Phenomenon79 thermograph1)
	(have_image Planet80 infrared3)
	(have_image Star81 infrared3)
	(have_image Planet82 infrared3)
	(have_image Star83 thermograph2)
	(have_image Phenomenon84 thermograph1)
	(have_image Planet85 thermograph4)
	(have_image Phenomenon86 infrared3)
	(have_image Star87 thermograph1)
	(have_image Star88 image0)
	(have_image Star89 thermograph1)
	(have_image Planet90 thermograph1)
	(have_image Star91 thermograph2)
	(have_image Planet92 thermograph1)
	(have_image Planet93 thermograph1)
	(have_image Planet94 thermograph4)
	(have_image Planet95 thermograph1)
	(have_image Phenomenon96 infrared3)
	(have_image Star97 thermograph1)
	(have_image Planet98 thermograph4)
	(have_image Phenomenon99 image0)
))

)
