(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	satellite1 - satellite
	instrument2 - instrument
	instrument3 - instrument
	satellite2 - satellite
	instrument4 - instrument
	satellite3 - satellite
	instrument5 - instrument
	spectrograph0 - mode
	infrared3 - mode
	spectrograph2 - mode
	spectrograph1 - mode
	thermograph4 - mode
	GroundStation3 - direction
	GroundStation5 - direction
	GroundStation9 - direction
	Star10 - direction
	GroundStation12 - direction
	Star13 - direction
	Star20 - direction
	GroundStation22 - direction
	Star23 - direction
	GroundStation26 - direction
	GroundStation27 - direction
	Star29 - direction
	Star30 - direction
	GroundStation31 - direction
	Star32 - direction
	GroundStation34 - direction
	Star35 - direction
	GroundStation21 - direction
	Star15 - direction
	Star1 - direction
	Star39 - direction
	GroundStation37 - direction
	GroundStation18 - direction
	GroundStation2 - direction
	GroundStation24 - direction
	Star11 - direction
	Star19 - direction
	GroundStation16 - direction
	GroundStation28 - direction
	GroundStation36 - direction
	Star25 - direction
	Star8 - direction
	Star6 - direction
	Star0 - direction
	GroundStation4 - direction
	Star38 - direction
	Star7 - direction
	GroundStation33 - direction
	GroundStation14 - direction
	GroundStation17 - direction
	Star40 - direction
	Star41 - direction
	Phenomenon42 - direction
	Phenomenon43 - direction
	Phenomenon44 - direction
	Planet45 - direction
	Planet46 - direction
	Star47 - direction
	Star48 - direction
	Phenomenon49 - direction
	Planet50 - direction
	Star51 - direction
	Phenomenon52 - direction
	Planet53 - direction
	Planet54 - direction
	Star55 - direction
	Star56 - direction
	Planet57 - direction
	Planet58 - direction
	Planet59 - direction
	Planet60 - direction
	Star61 - direction
	Star62 - direction
	Planet63 - direction
	Phenomenon64 - direction
)
(:init
	(supports instrument0 infrared3)
	(supports instrument0 spectrograph2)
	(calibration_target instrument0 Star35)
	(calibration_target instrument0 Star8)
	(calibration_target instrument0 GroundStation2)
	(calibration_target instrument0 GroundStation21)
	(calibration_target instrument0 Star38)
	(calibration_target instrument0 GroundStation24)
	(calibration_target instrument0 GroundStation37)
	(supports instrument1 spectrograph0)
	(supports instrument1 spectrograph1)
	(supports instrument1 spectrograph2)
	(calibration_target instrument1 GroundStation14)
	(calibration_target instrument1 GroundStation21)
	(calibration_target instrument1 GroundStation24)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation28)
	(supports instrument2 spectrograph2)
	(supports instrument2 spectrograph0)
	(calibration_target instrument2 Star6)
	(calibration_target instrument2 Star38)
	(calibration_target instrument2 GroundStation37)
	(calibration_target instrument2 Star39)
	(calibration_target instrument2 Star1)
	(calibration_target instrument2 Star15)
	(calibration_target instrument2 GroundStation33)
	(supports instrument3 spectrograph2)
	(supports instrument3 spectrograph1)
	(calibration_target instrument3 GroundStation28)
	(calibration_target instrument3 GroundStation16)
	(calibration_target instrument3 Star19)
	(calibration_target instrument3 Star25)
	(calibration_target instrument3 Star11)
	(calibration_target instrument3 GroundStation14)
	(calibration_target instrument3 GroundStation24)
	(calibration_target instrument3 GroundStation2)
	(calibration_target instrument3 Star7)
	(calibration_target instrument3 GroundStation18)
	(on_board instrument2 satellite1)
	(on_board instrument3 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star35)
	(supports instrument4 spectrograph0)
	(supports instrument4 spectrograph2)
	(supports instrument4 thermograph4)
	(calibration_target instrument4 Star25)
	(calibration_target instrument4 Star0)
	(calibration_target instrument4 GroundStation36)
	(on_board instrument4 satellite2)
	(power_avail satellite2)
	(pointing satellite2 GroundStation14)
	(supports instrument5 infrared3)
	(supports instrument5 spectrograph0)
	(calibration_target instrument5 GroundStation17)
	(calibration_target instrument5 GroundStation14)
	(calibration_target instrument5 GroundStation33)
	(calibration_target instrument5 Star7)
	(calibration_target instrument5 Star38)
	(calibration_target instrument5 GroundStation4)
	(calibration_target instrument5 Star0)
	(calibration_target instrument5 Star6)
	(calibration_target instrument5 Star8)
	(on_board instrument5 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation28)
)
(:goal (and
	(pointing satellite1 Star51)
	(pointing satellite2 GroundStation17)
	(pointing satellite3 Star32)
	(have_image Star40 spectrograph1)
	(have_image Star41 spectrograph0)
	(have_image Phenomenon42 infrared3)
	(have_image Phenomenon43 spectrograph2)
	(have_image Phenomenon44 spectrograph1)
	(have_image Planet45 infrared3)
	(have_image Planet46 spectrograph0)
	(have_image Star47 thermograph4)
	(have_image Star48 thermograph4)
	(have_image Phenomenon49 infrared3)
	(have_image Planet50 spectrograph0)
	(have_image Star51 infrared3)
	(have_image Phenomenon52 spectrograph1)
	(have_image Planet53 spectrograph1)
	(have_image Planet54 spectrograph0)
	(have_image Star55 spectrograph2)
	(have_image Star56 spectrograph0)
	(have_image Planet57 spectrograph0)
	(have_image Planet58 spectrograph0)
	(have_image Planet59 spectrograph1)
	(have_image Planet60 spectrograph2)
	(have_image Star61 spectrograph1)
	(have_image Star62 thermograph4)
	(have_image Planet63 infrared3)
	(have_image Phenomenon64 infrared3)
))

)
