(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	satellite1 - satellite
	instrument4 - instrument
	instrument5 - instrument
	satellite2 - satellite
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	satellite3 - satellite
	instrument9 - instrument
	instrument10 - instrument
	image1 - mode
	thermograph0 - mode
	thermograph2 - mode
	thermograph3 - mode
	thermograph4 - mode
	Star1 - direction
	GroundStation13 - direction
	GroundStation12 - direction
	GroundStation21 - direction
	GroundStation7 - direction
	Star32 - direction
	GroundStation6 - direction
	Star20 - direction
	Star18 - direction
	GroundStation14 - direction
	GroundStation31 - direction
	Star34 - direction
	Star26 - direction
	Star0 - direction
	GroundStation11 - direction
	Star8 - direction
	Star28 - direction
	Star23 - direction
	Star22 - direction
	GroundStation5 - direction
	Star30 - direction
	GroundStation10 - direction
	GroundStation2 - direction
	Star25 - direction
	GroundStation38 - direction
	Star36 - direction
	Star3 - direction
	Star35 - direction
	GroundStation15 - direction
	Star17 - direction
	GroundStation24 - direction
	Star39 - direction
	Star9 - direction
	Star4 - direction
	Star29 - direction
	GroundStation16 - direction
	Star37 - direction
	Star27 - direction
	GroundStation19 - direction
	GroundStation33 - direction
	Star40 - direction
	Planet41 - direction
	Star42 - direction
	Star43 - direction
	Planet44 - direction
	Planet45 - direction
	Planet46 - direction
	Planet47 - direction
	Phenomenon48 - direction
	Phenomenon49 - direction
	Star50 - direction
	Star51 - direction
	Planet52 - direction
	Planet53 - direction
	Planet54 - direction
	Star55 - direction
	Star56 - direction
	Star57 - direction
	Planet58 - direction
	Star59 - direction
	Phenomenon60 - direction
	Planet61 - direction
	Phenomenon62 - direction
	Planet63 - direction
	Star64 - direction
)
(:init
	(supports instrument0 thermograph3)
	(supports instrument0 thermograph0)
	(calibration_target instrument0 Star39)
	(calibration_target instrument0 GroundStation2)
	(calibration_target instrument0 Star9)
	(calibration_target instrument0 GroundStation12)
	(calibration_target instrument0 Star32)
	(calibration_target instrument0 GroundStation24)
	(calibration_target instrument0 Star37)
	(calibration_target instrument0 Star27)
	(calibration_target instrument0 GroundStation11)
	(calibration_target instrument0 GroundStation5)
	(calibration_target instrument0 Star18)
	(calibration_target instrument0 Star35)
	(calibration_target instrument0 Star17)
	(supports instrument1 image1)
	(calibration_target instrument1 Star28)
	(calibration_target instrument1 GroundStation6)
	(calibration_target instrument1 Star32)
	(calibration_target instrument1 GroundStation31)
	(calibration_target instrument1 Star20)
	(calibration_target instrument1 Star8)
	(calibration_target instrument1 Star23)
	(calibration_target instrument1 GroundStation2)
	(calibration_target instrument1 GroundStation7)
	(calibration_target instrument1 Star4)
	(calibration_target instrument1 GroundStation16)
	(calibration_target instrument1 GroundStation21)
	(supports instrument2 thermograph3)
	(calibration_target instrument2 Star34)
	(calibration_target instrument2 Star20)
	(calibration_target instrument2 Star17)
	(calibration_target instrument2 Star25)
	(supports instrument3 thermograph4)
	(supports instrument3 thermograph0)
	(supports instrument3 thermograph3)
	(calibration_target instrument3 Star18)
	(calibration_target instrument3 GroundStation10)
	(calibration_target instrument3 Star23)
	(calibration_target instrument3 Star20)
	(calibration_target instrument3 Star26)
	(calibration_target instrument3 Star27)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation38)
	(supports instrument4 thermograph3)
	(calibration_target instrument4 Star9)
	(calibration_target instrument4 GroundStation10)
	(calibration_target instrument4 Star26)
	(calibration_target instrument4 GroundStation11)
	(calibration_target instrument4 Star34)
	(calibration_target instrument4 Star29)
	(calibration_target instrument4 GroundStation31)
	(calibration_target instrument4 Star8)
	(calibration_target instrument4 GroundStation2)
	(calibration_target instrument4 GroundStation14)
	(supports instrument5 thermograph0)
	(supports instrument5 thermograph2)
	(supports instrument5 thermograph4)
	(calibration_target instrument5 GroundStation24)
	(calibration_target instrument5 Star28)
	(calibration_target instrument5 GroundStation19)
	(calibration_target instrument5 Star4)
	(calibration_target instrument5 Star0)
	(calibration_target instrument5 GroundStation11)
	(calibration_target instrument5 GroundStation10)
	(calibration_target instrument5 Star9)
	(calibration_target instrument5 GroundStation2)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation24)
	(supports instrument6 thermograph0)
	(supports instrument6 image1)
	(supports instrument6 thermograph2)
	(calibration_target instrument6 Star9)
	(calibration_target instrument6 GroundStation38)
	(calibration_target instrument6 Star22)
	(calibration_target instrument6 Star28)
	(calibration_target instrument6 Star8)
	(calibration_target instrument6 Star30)
	(calibration_target instrument6 GroundStation11)
	(supports instrument7 thermograph2)
	(supports instrument7 thermograph4)
	(calibration_target instrument7 GroundStation2)
	(calibration_target instrument7 GroundStation10)
	(calibration_target instrument7 Star36)
	(calibration_target instrument7 GroundStation24)
	(calibration_target instrument7 Star30)
	(calibration_target instrument7 GroundStation5)
	(calibration_target instrument7 Star4)
	(calibration_target instrument7 Star25)
	(calibration_target instrument7 Star22)
	(calibration_target instrument7 Star29)
	(calibration_target instrument7 Star23)
	(supports instrument8 image1)
	(supports instrument8 thermograph0)
	(supports instrument8 thermograph4)
	(calibration_target instrument8 Star36)
	(calibration_target instrument8 Star35)
	(calibration_target instrument8 Star9)
	(calibration_target instrument8 GroundStation38)
	(calibration_target instrument8 Star25)
	(on_board instrument6 satellite2)
	(on_board instrument7 satellite2)
	(on_board instrument8 satellite2)
	(power_avail satellite2)
	(pointing satellite2 GroundStation21)
	(supports instrument9 thermograph0)
	(supports instrument9 thermograph4)
	(calibration_target instrument9 Star27)
	(calibration_target instrument9 Star37)
	(calibration_target instrument9 GroundStation16)
	(calibration_target instrument9 Star29)
	(calibration_target instrument9 Star4)
	(calibration_target instrument9 GroundStation33)
	(calibration_target instrument9 Star9)
	(calibration_target instrument9 Star39)
	(calibration_target instrument9 GroundStation24)
	(calibration_target instrument9 Star17)
	(calibration_target instrument9 GroundStation15)
	(calibration_target instrument9 Star35)
	(calibration_target instrument9 Star3)
	(supports instrument10 thermograph2)
	(calibration_target instrument10 GroundStation33)
	(calibration_target instrument10 GroundStation19)
	(on_board instrument9 satellite3)
	(on_board instrument10 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star22)
)
(:goal (and
	(pointing satellite0 GroundStation7)
	(pointing satellite1 Star43)
	(pointing satellite2 Star30)
	(pointing satellite3 Star42)
	(have_image Star40 thermograph2)
	(have_image Planet41 thermograph3)
	(have_image Star42 image1)
	(have_image Star43 image1)
	(have_image Planet44 thermograph3)
	(have_image Planet45 thermograph2)
	(have_image Planet46 image1)
	(have_image Planet47 thermograph3)
	(have_image Phenomenon48 thermograph0)
	(have_image Phenomenon49 thermograph2)
	(have_image Star50 thermograph3)
	(have_image Star51 thermograph4)
	(have_image Planet52 image1)
	(have_image Planet53 thermograph2)
	(have_image Planet54 thermograph3)
	(have_image Star55 thermograph0)
	(have_image Star56 thermograph3)
	(have_image Star57 thermograph3)
	(have_image Planet58 thermograph4)
	(have_image Star59 thermograph0)
	(have_image Phenomenon60 thermograph2)
	(have_image Planet61 thermograph2)
	(have_image Phenomenon62 thermograph3)
	(have_image Planet63 thermograph3)
	(have_image Star64 thermograph4)
))

)
