(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	satellite1 - satellite
	instrument1 - instrument
	satellite2 - satellite
	instrument2 - instrument
	satellite3 - satellite
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	satellite4 - satellite
	instrument7 - instrument
	satellite5 - satellite
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	satellite6 - satellite
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	satellite7 - satellite
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	thermograph0 - mode
	thermograph3 - mode
	image1 - mode
	thermograph2 - mode
	thermograph4 - mode
	Star35 - direction
	Star64 - direction
	GroundStation15 - direction
	GroundStation61 - direction
	Star75 - direction
	GroundStation16 - direction
	GroundStation71 - direction
	GroundStation73 - direction
	GroundStation55 - direction
	Star67 - direction
	Star36 - direction
	Star40 - direction
	Star32 - direction
	Star3 - direction
	Star91 - direction
	Star17 - direction
	Star1 - direction
	Star34 - direction
	GroundStation6 - direction
	Star93 - direction
	GroundStation43 - direction
	GroundStation52 - direction
	GroundStation33 - direction
	GroundStation38 - direction
	GroundStation19 - direction
	Star77 - direction
	Star96 - direction
	Star57 - direction
	GroundStation50 - direction
	GroundStation14 - direction
	Star29 - direction
	GroundStation81 - direction
	Star56 - direction
	Star74 - direction
	Star99 - direction
	Star90 - direction
	Star49 - direction
	GroundStation44 - direction
	GroundStation2 - direction
	Star83 - direction
	GroundStation70 - direction
	Star8 - direction
	GroundStation7 - direction
	GroundStation82 - direction
	Star63 - direction
	GroundStation41 - direction
	Star0 - direction
	Star39 - direction
	Star51 - direction
	GroundStation58 - direction
	GroundStation31 - direction
	Star53 - direction
	Star37 - direction
	Star30 - direction
	Star26 - direction
	Star4 - direction
	GroundStation12 - direction
	GroundStation5 - direction
	GroundStation48 - direction
	GroundStation69 - direction
	GroundStation97 - direction
	GroundStation92 - direction
	GroundStation47 - direction
	Star87 - direction
	Star23 - direction
	Star9 - direction
	Star78 - direction
	GroundStation88 - direction
	GroundStation21 - direction
	Star45 - direction
	Star18 - direction
	Star20 - direction
	GroundStation84 - direction
	GroundStation60 - direction
	GroundStation79 - direction
	GroundStation95 - direction
	Star28 - direction
	GroundStation86 - direction
	GroundStation80 - direction
	GroundStation62 - direction
	GroundStation89 - direction
	GroundStation98 - direction
	GroundStation68 - direction
	Star25 - direction
	GroundStation66 - direction
	Star27 - direction
	Star22 - direction
	GroundStation13 - direction
	GroundStation10 - direction
	GroundStation46 - direction
	Star72 - direction
	GroundStation11 - direction
	GroundStation85 - direction
	GroundStation24 - direction
	GroundStation76 - direction
	Star65 - direction
	Star59 - direction
	Star54 - direction
	GroundStation42 - direction
	GroundStation94 - direction
	Planet100 - direction
	Star101 - direction
	Planet102 - direction
	Planet103 - direction
	Star104 - direction
	Phenomenon105 - direction
	Planet106 - direction
	Planet107 - direction
	Star108 - direction
	Phenomenon109 - direction
	Star110 - direction
	Planet111 - direction
	Phenomenon112 - direction
	Star113 - direction
	Planet114 - direction
	Planet115 - direction
	Phenomenon116 - direction
	Star117 - direction
	Phenomenon118 - direction
	Star119 - direction
	Star120 - direction
	Phenomenon121 - direction
	Phenomenon122 - direction
	Phenomenon123 - direction
	Planet124 - direction
	Phenomenon125 - direction
	Star126 - direction
	Star127 - direction
	Planet128 - direction
	Planet129 - direction
	Star130 - direction
	Phenomenon131 - direction
	Star132 - direction
	Planet133 - direction
	Phenomenon134 - direction
	Star135 - direction
	Star136 - direction
	Planet137 - direction
	Star138 - direction
	Star139 - direction
	Planet140 - direction
	Planet141 - direction
	Phenomenon142 - direction
	Star143 - direction
	Phenomenon144 - direction
	Planet145 - direction
	Planet146 - direction
	Star147 - direction
	Planet148 - direction
	Star149 - direction
	Star150 - direction
	Planet151 - direction
	Planet152 - direction
	Star153 - direction
	Planet154 - direction
	Star155 - direction
	Phenomenon156 - direction
	Phenomenon157 - direction
	Planet158 - direction
	Planet159 - direction
	Star160 - direction
	Phenomenon161 - direction
	Star162 - direction
	Star163 - direction
	Phenomenon164 - direction
	Phenomenon165 - direction
	Phenomenon166 - direction
	Star167 - direction
	Star168 - direction
	Star169 - direction
)
(:init
	(supports instrument0 thermograph4)
	(supports instrument0 thermograph3)
	(calibration_target instrument0 Star4)
	(calibration_target instrument0 GroundStation71)
	(calibration_target instrument0 GroundStation84)
	(calibration_target instrument0 GroundStation7)
	(calibration_target instrument0 Star40)
	(calibration_target instrument0 Star1)
	(on_board instrument0 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation76)
	(supports instrument1 thermograph4)
	(supports instrument1 thermograph3)
	(calibration_target instrument1 GroundStation86)
	(calibration_target instrument1 Star3)
	(calibration_target instrument1 Star65)
	(calibration_target instrument1 GroundStation71)
	(calibration_target instrument1 GroundStation46)
	(calibration_target instrument1 GroundStation6)
	(calibration_target instrument1 GroundStation38)
	(calibration_target instrument1 Star64)
	(calibration_target instrument1 GroundStation12)
	(calibration_target instrument1 GroundStation11)
	(calibration_target instrument1 Star49)
	(calibration_target instrument1 Star20)
	(calibration_target instrument1 Star53)
	(calibration_target instrument1 GroundStation52)
	(calibration_target instrument1 GroundStation24)
	(calibration_target instrument1 Star37)
	(calibration_target instrument1 GroundStation85)
	(calibration_target instrument1 GroundStation79)
	(calibration_target instrument1 GroundStation73)
	(calibration_target instrument1 GroundStation94)
	(calibration_target instrument1 Star36)
	(calibration_target instrument1 Star51)
	(calibration_target instrument1 GroundStation15)
	(calibration_target instrument1 Star87)
	(calibration_target instrument1 GroundStation95)
	(on_board instrument1 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star155)
	(supports instrument2 thermograph4)
	(supports instrument2 thermograph0)
	(supports instrument2 image1)
	(calibration_target instrument2 GroundStation14)
	(calibration_target instrument2 GroundStation19)
	(calibration_target instrument2 GroundStation79)
	(calibration_target instrument2 GroundStation68)
	(on_board instrument2 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star35)
	(supports instrument3 thermograph4)
	(supports instrument3 image1)
	(supports instrument3 thermograph2)
	(calibration_target instrument3 GroundStation73)
	(calibration_target instrument3 GroundStation79)
	(calibration_target instrument3 GroundStation70)
	(calibration_target instrument3 GroundStation52)
	(calibration_target instrument3 GroundStation89)
	(supports instrument4 thermograph0)
	(supports instrument4 thermograph2)
	(supports instrument4 image1)
	(calibration_target instrument4 Star67)
	(calibration_target instrument4 Star17)
	(calibration_target instrument4 GroundStation79)
	(calibration_target instrument4 GroundStation47)
	(calibration_target instrument4 GroundStation80)
	(calibration_target instrument4 Star0)
	(calibration_target instrument4 GroundStation43)
	(calibration_target instrument4 GroundStation14)
	(calibration_target instrument4 GroundStation55)
	(calibration_target instrument4 GroundStation11)
	(calibration_target instrument4 Star90)
	(calibration_target instrument4 GroundStation41)
	(calibration_target instrument4 Star36)
	(calibration_target instrument4 GroundStation21)
	(calibration_target instrument4 Star77)
	(calibration_target instrument4 GroundStation71)
	(calibration_target instrument4 GroundStation6)
	(calibration_target instrument4 Star72)
	(calibration_target instrument4 GroundStation58)
	(calibration_target instrument4 GroundStation95)
	(calibration_target instrument4 GroundStation10)
	(calibration_target instrument4 GroundStation68)
	(calibration_target instrument4 GroundStation60)
	(calibration_target instrument4 Star99)
	(calibration_target instrument4 Star28)
	(calibration_target instrument4 Star83)
	(supports instrument5 thermograph3)
	(supports instrument5 image1)
	(calibration_target instrument5 GroundStation15)
	(calibration_target instrument5 GroundStation95)
	(calibration_target instrument5 GroundStation42)
	(calibration_target instrument5 GroundStation69)
	(calibration_target instrument5 Star64)
	(calibration_target instrument5 Star96)
	(calibration_target instrument5 GroundStation24)
	(calibration_target instrument5 Star87)
	(calibration_target instrument5 GroundStation86)
	(calibration_target instrument5 Star27)
	(calibration_target instrument5 GroundStation47)
	(calibration_target instrument5 Star90)
	(calibration_target instrument5 GroundStation43)
	(calibration_target instrument5 GroundStation62)
	(calibration_target instrument5 GroundStation92)
	(calibration_target instrument5 Star37)
	(calibration_target instrument5 GroundStation48)
	(calibration_target instrument5 Star54)
	(calibration_target instrument5 Star17)
	(calibration_target instrument5 Star56)
	(calibration_target instrument5 Star53)
	(calibration_target instrument5 Star45)
	(calibration_target instrument5 Star32)
	(calibration_target instrument5 GroundStation76)
	(calibration_target instrument5 GroundStation11)
	(supports instrument6 image1)
	(supports instrument6 thermograph4)
	(calibration_target instrument6 Star34)
	(calibration_target instrument6 Star18)
	(calibration_target instrument6 GroundStation38)
	(calibration_target instrument6 Star40)
	(calibration_target instrument6 GroundStation60)
	(calibration_target instrument6 Star75)
	(calibration_target instrument6 Star9)
	(calibration_target instrument6 Star54)
	(calibration_target instrument6 GroundStation58)
	(calibration_target instrument6 GroundStation73)
	(calibration_target instrument6 GroundStation82)
	(calibration_target instrument6 GroundStation81)
	(calibration_target instrument6 Star36)
	(calibration_target instrument6 GroundStation50)
	(calibration_target instrument6 Star83)
	(calibration_target instrument6 Star93)
	(calibration_target instrument6 Star56)
	(calibration_target instrument6 Star87)
	(calibration_target instrument6 Star27)
	(calibration_target instrument6 GroundStation66)
	(calibration_target instrument6 GroundStation61)
	(calibration_target instrument6 Star37)
	(on_board instrument3 satellite3)
	(on_board instrument4 satellite3)
	(on_board instrument5 satellite3)
	(on_board instrument6 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation5)
	(supports instrument7 image1)
	(supports instrument7 thermograph0)
	(calibration_target instrument7 Star40)
	(calibration_target instrument7 Star90)
	(calibration_target instrument7 GroundStation80)
	(calibration_target instrument7 GroundStation68)
	(calibration_target instrument7 GroundStation50)
	(calibration_target instrument7 Star96)
	(calibration_target instrument7 GroundStation76)
	(calibration_target instrument7 Star74)
	(calibration_target instrument7 GroundStation60)
	(calibration_target instrument7 GroundStation88)
	(calibration_target instrument7 GroundStation82)
	(calibration_target instrument7 GroundStation69)
	(calibration_target instrument7 Star25)
	(calibration_target instrument7 Star45)
	(calibration_target instrument7 GroundStation46)
	(calibration_target instrument7 GroundStation41)
	(calibration_target instrument7 GroundStation81)
	(calibration_target instrument7 GroundStation98)
	(on_board instrument7 satellite4)
	(power_avail satellite4)
	(pointing satellite4 GroundStation7)
	(supports instrument8 image1)
	(supports instrument8 thermograph2)
	(calibration_target instrument8 Star18)
	(calibration_target instrument8 Star3)
	(calibration_target instrument8 GroundStation97)
	(calibration_target instrument8 GroundStation24)
	(calibration_target instrument8 GroundStation66)
	(calibration_target instrument8 GroundStation58)
	(calibration_target instrument8 GroundStation47)
	(calibration_target instrument8 GroundStation69)
	(calibration_target instrument8 GroundStation55)
	(calibration_target instrument8 Star87)
	(calibration_target instrument8 Star59)
	(calibration_target instrument8 GroundStation62)
	(calibration_target instrument8 GroundStation73)
	(calibration_target instrument8 GroundStation38)
	(calibration_target instrument8 GroundStation84)
	(calibration_target instrument8 Star36)
	(calibration_target instrument8 Star26)
	(calibration_target instrument8 GroundStation21)
	(calibration_target instrument8 Star78)
	(calibration_target instrument8 Star51)
	(calibration_target instrument8 GroundStation71)
	(calibration_target instrument8 GroundStation85)
	(calibration_target instrument8 GroundStation42)
	(calibration_target instrument8 GroundStation70)
	(calibration_target instrument8 GroundStation48)
	(calibration_target instrument8 Star74)
	(calibration_target instrument8 GroundStation16)
	(calibration_target instrument8 GroundStation50)
	(calibration_target instrument8 GroundStation81)
	(calibration_target instrument8 GroundStation33)
	(calibration_target instrument8 GroundStation82)
	(supports instrument9 thermograph3)
	(calibration_target instrument9 GroundStation95)
	(calibration_target instrument9 Star65)
	(calibration_target instrument9 GroundStation42)
	(calibration_target instrument9 GroundStation52)
	(calibration_target instrument9 GroundStation12)
	(calibration_target instrument9 Star30)
	(calibration_target instrument9 GroundStation70)
	(calibration_target instrument9 GroundStation92)
	(calibration_target instrument9 Star3)
	(calibration_target instrument9 GroundStation2)
	(calibration_target instrument9 Star32)
	(calibration_target instrument9 Star63)
	(calibration_target instrument9 GroundStation5)
	(calibration_target instrument9 Star37)
	(calibration_target instrument9 GroundStation85)
	(calibration_target instrument9 Star49)
	(calibration_target instrument9 GroundStation50)
	(calibration_target instrument9 GroundStation38)
	(calibration_target instrument9 GroundStation68)
	(calibration_target instrument9 Star96)
	(calibration_target instrument9 Star77)
	(calibration_target instrument9 Star40)
	(calibration_target instrument9 Star93)
	(calibration_target instrument9 Star36)
	(calibration_target instrument9 GroundStation60)
	(calibration_target instrument9 GroundStation44)
	(calibration_target instrument9 Star27)
	(calibration_target instrument9 Star83)
	(calibration_target instrument9 Star67)
	(calibration_target instrument9 GroundStation46)
	(calibration_target instrument9 GroundStation43)
	(supports instrument10 thermograph3)
	(supports instrument10 thermograph4)
	(calibration_target instrument10 GroundStation52)
	(calibration_target instrument10 Star54)
	(calibration_target instrument10 GroundStation6)
	(calibration_target instrument10 GroundStation41)
	(calibration_target instrument10 Star59)
	(calibration_target instrument10 Star29)
	(calibration_target instrument10 GroundStation19)
	(calibration_target instrument10 GroundStation12)
	(calibration_target instrument10 GroundStation5)
	(calibration_target instrument10 Star34)
	(calibration_target instrument10 Star1)
	(calibration_target instrument10 GroundStation2)
	(calibration_target instrument10 Star17)
	(calibration_target instrument10 Star91)
	(supports instrument11 image1)
	(calibration_target instrument11 GroundStation89)
	(calibration_target instrument11 Star63)
	(calibration_target instrument11 GroundStation47)
	(calibration_target instrument11 Star87)
	(calibration_target instrument11 GroundStation82)
	(calibration_target instrument11 GroundStation43)
	(calibration_target instrument11 Star93)
	(calibration_target instrument11 Star25)
	(calibration_target instrument11 Star26)
	(calibration_target instrument11 GroundStation13)
	(calibration_target instrument11 Star51)
	(on_board instrument8 satellite5)
	(on_board instrument9 satellite5)
	(on_board instrument10 satellite5)
	(on_board instrument11 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star104)
	(supports instrument12 image1)
	(calibration_target instrument12 Star25)
	(calibration_target instrument12 GroundStation58)
	(calibration_target instrument12 GroundStation66)
	(calibration_target instrument12 Star45)
	(calibration_target instrument12 Star39)
	(calibration_target instrument12 Star72)
	(calibration_target instrument12 GroundStation50)
	(calibration_target instrument12 Star83)
	(calibration_target instrument12 Star0)
	(calibration_target instrument12 Star57)
	(calibration_target instrument12 GroundStation13)
	(calibration_target instrument12 GroundStation69)
	(calibration_target instrument12 Star96)
	(calibration_target instrument12 Star54)
	(calibration_target instrument12 Star77)
	(calibration_target instrument12 Star18)
	(calibration_target instrument12 GroundStation19)
	(calibration_target instrument12 GroundStation38)
	(calibration_target instrument12 Star51)
	(calibration_target instrument12 Star65)
	(calibration_target instrument12 GroundStation70)
	(calibration_target instrument12 GroundStation33)
	(calibration_target instrument12 GroundStation94)
	(calibration_target instrument12 Star74)
	(calibration_target instrument12 GroundStation31)
	(calibration_target instrument12 GroundStation12)
	(calibration_target instrument12 GroundStation89)
	(calibration_target instrument12 GroundStation52)
	(calibration_target instrument12 Star87)
	(calibration_target instrument12 Star26)
	(calibration_target instrument12 GroundStation5)
	(calibration_target instrument12 Star59)
	(calibration_target instrument12 GroundStation81)
	(supports instrument13 image1)
	(calibration_target instrument13 GroundStation14)
	(calibration_target instrument13 GroundStation42)
	(calibration_target instrument13 GroundStation66)
	(calibration_target instrument13 GroundStation58)
	(supports instrument14 thermograph2)
	(supports instrument14 thermograph3)
	(calibration_target instrument14 GroundStation81)
	(calibration_target instrument14 Star29)
	(calibration_target instrument14 GroundStation92)
	(calibration_target instrument14 Star28)
	(calibration_target instrument14 GroundStation58)
	(calibration_target instrument14 Star65)
	(calibration_target instrument14 GroundStation21)
	(calibration_target instrument14 GroundStation62)
	(calibration_target instrument14 Star45)
	(supports instrument15 image1)
	(supports instrument15 thermograph2)
	(supports instrument15 thermograph3)
	(calibration_target instrument15 GroundStation44)
	(calibration_target instrument15 Star49)
	(calibration_target instrument15 Star78)
	(calibration_target instrument15 GroundStation31)
	(calibration_target instrument15 Star0)
	(calibration_target instrument15 Star26)
	(calibration_target instrument15 Star90)
	(calibration_target instrument15 Star99)
	(calibration_target instrument15 GroundStation84)
	(calibration_target instrument15 Star72)
	(calibration_target instrument15 GroundStation47)
	(calibration_target instrument15 Star27)
	(calibration_target instrument15 GroundStation13)
	(calibration_target instrument15 GroundStation60)
	(calibration_target instrument15 Star74)
	(calibration_target instrument15 Star53)
	(calibration_target instrument15 GroundStation24)
	(calibration_target instrument15 Star56)
	(supports instrument16 image1)
	(supports instrument16 thermograph2)
	(calibration_target instrument16 GroundStation58)
	(calibration_target instrument16 Star87)
	(calibration_target instrument16 GroundStation86)
	(calibration_target instrument16 Star51)
	(calibration_target instrument16 GroundStation13)
	(calibration_target instrument16 Star65)
	(calibration_target instrument16 Star39)
	(calibration_target instrument16 GroundStation76)
	(calibration_target instrument16 Star0)
	(calibration_target instrument16 GroundStation41)
	(calibration_target instrument16 Star63)
	(calibration_target instrument16 GroundStation42)
	(calibration_target instrument16 GroundStation82)
	(calibration_target instrument16 Star9)
	(calibration_target instrument16 GroundStation95)
	(calibration_target instrument16 Star78)
	(calibration_target instrument16 GroundStation7)
	(calibration_target instrument16 Star23)
	(calibration_target instrument16 Star8)
	(calibration_target instrument16 GroundStation66)
	(calibration_target instrument16 GroundStation69)
	(calibration_target instrument16 GroundStation70)
	(calibration_target instrument16 Star45)
	(calibration_target instrument16 Star83)
	(calibration_target instrument16 GroundStation2)
	(on_board instrument12 satellite6)
	(on_board instrument13 satellite6)
	(on_board instrument14 satellite6)
	(on_board instrument15 satellite6)
	(on_board instrument16 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star74)
	(supports instrument17 thermograph0)
	(supports instrument17 image1)
	(calibration_target instrument17 Star23)
	(calibration_target instrument17 Star87)
	(calibration_target instrument17 GroundStation95)
	(calibration_target instrument17 Star28)
	(calibration_target instrument17 GroundStation60)
	(calibration_target instrument17 GroundStation47)
	(calibration_target instrument17 GroundStation98)
	(calibration_target instrument17 Star20)
	(calibration_target instrument17 GroundStation84)
	(calibration_target instrument17 GroundStation92)
	(calibration_target instrument17 Star78)
	(calibration_target instrument17 GroundStation97)
	(calibration_target instrument17 GroundStation69)
	(calibration_target instrument17 GroundStation48)
	(calibration_target instrument17 Star9)
	(calibration_target instrument17 GroundStation5)
	(calibration_target instrument17 GroundStation12)
	(calibration_target instrument17 Star25)
	(calibration_target instrument17 Star4)
	(calibration_target instrument17 Star26)
	(calibration_target instrument17 GroundStation86)
	(calibration_target instrument17 Star30)
	(calibration_target instrument17 GroundStation62)
	(calibration_target instrument17 GroundStation88)
	(calibration_target instrument17 Star37)
	(calibration_target instrument17 GroundStation42)
	(calibration_target instrument17 Star53)
	(calibration_target instrument17 GroundStation31)
	(calibration_target instrument17 GroundStation79)
	(calibration_target instrument17 Star54)
	(calibration_target instrument17 GroundStation24)
	(supports instrument18 thermograph3)
	(supports instrument18 thermograph0)
	(supports instrument18 thermograph4)
	(calibration_target instrument18 GroundStation80)
	(calibration_target instrument18 GroundStation86)
	(calibration_target instrument18 GroundStation13)
	(calibration_target instrument18 Star28)
	(calibration_target instrument18 GroundStation95)
	(calibration_target instrument18 GroundStation79)
	(calibration_target instrument18 GroundStation10)
	(calibration_target instrument18 GroundStation60)
	(calibration_target instrument18 GroundStation84)
	(calibration_target instrument18 Star20)
	(calibration_target instrument18 Star18)
	(calibration_target instrument18 Star45)
	(calibration_target instrument18 GroundStation21)
	(calibration_target instrument18 GroundStation88)
	(calibration_target instrument18 Star78)
	(calibration_target instrument18 Star9)
	(supports instrument19 thermograph3)
	(calibration_target instrument19 GroundStation94)
	(calibration_target instrument19 GroundStation42)
	(calibration_target instrument19 Star54)
	(calibration_target instrument19 Star59)
	(calibration_target instrument19 Star65)
	(calibration_target instrument19 GroundStation76)
	(calibration_target instrument19 GroundStation24)
	(calibration_target instrument19 GroundStation85)
	(calibration_target instrument19 GroundStation11)
	(calibration_target instrument19 Star72)
	(calibration_target instrument19 GroundStation46)
	(calibration_target instrument19 GroundStation10)
	(calibration_target instrument19 GroundStation13)
	(calibration_target instrument19 Star22)
	(calibration_target instrument19 Star27)
	(calibration_target instrument19 GroundStation66)
	(calibration_target instrument19 Star25)
	(calibration_target instrument19 GroundStation68)
	(calibration_target instrument19 GroundStation98)
	(calibration_target instrument19 GroundStation89)
	(calibration_target instrument19 GroundStation62)
	(on_board instrument17 satellite7)
	(on_board instrument18 satellite7)
	(on_board instrument19 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star32)
)
(:goal (and
	(pointing satellite0 Star96)
	(pointing satellite2 Phenomenon123)
	(pointing satellite3 Star130)
	(pointing satellite4 Star83)
	(pointing satellite5 Star74)
	(have_image Planet100 thermograph4)
	(have_image Star101 image1)
	(have_image Planet102 thermograph3)
	(have_image Planet103 thermograph2)
	(have_image Star104 thermograph0)
	(have_image Phenomenon105 thermograph2)
	(have_image Planet106 image1)
	(have_image Planet107 image1)
	(have_image Star108 thermograph3)
	(have_image Phenomenon109 thermograph0)
	(have_image Star110 image1)
	(have_image Planet111 thermograph3)
	(have_image Phenomenon112 thermograph0)
	(have_image Star113 image1)
	(have_image Planet114 image1)
	(have_image Planet115 thermograph0)
	(have_image Phenomenon116 image1)
	(have_image Star117 image1)
	(have_image Phenomenon118 thermograph2)
	(have_image Star119 thermograph4)
	(have_image Star120 thermograph4)
	(have_image Phenomenon121 image1)
	(have_image Phenomenon122 thermograph3)
	(have_image Phenomenon123 thermograph3)
	(have_image Planet124 thermograph3)
	(have_image Phenomenon125 thermograph2)
	(have_image Star126 thermograph0)
	(have_image Star127 thermograph0)
	(have_image Planet128 thermograph2)
	(have_image Planet129 thermograph3)
	(have_image Star130 thermograph3)
	(have_image Phenomenon131 thermograph3)
	(have_image Star132 thermograph2)
	(have_image Planet133 thermograph4)
	(have_image Phenomenon134 thermograph0)
	(have_image Star135 image1)
	(have_image Star136 thermograph2)
	(have_image Planet137 image1)
	(have_image Star138 thermograph0)
	(have_image Star139 thermograph3)
	(have_image Planet140 image1)
	(have_image Planet141 image1)
	(have_image Phenomenon142 image1)
	(have_image Star143 thermograph4)
	(have_image Phenomenon144 thermograph2)
	(have_image Planet145 thermograph4)
	(have_image Planet146 thermograph0)
	(have_image Star147 thermograph3)
	(have_image Planet148 thermograph3)
	(have_image Star149 thermograph2)
	(have_image Star150 thermograph3)
	(have_image Planet151 thermograph0)
	(have_image Planet152 thermograph2)
	(have_image Star153 image1)
	(have_image Planet154 thermograph0)
	(have_image Star155 thermograph4)
	(have_image Phenomenon156 thermograph3)
	(have_image Phenomenon157 thermograph4)
	(have_image Planet158 thermograph2)
	(have_image Planet159 image1)
	(have_image Star160 thermograph4)
	(have_image Phenomenon161 thermograph3)
	(have_image Star162 thermograph0)
	(have_image Star163 image1)
	(have_image Phenomenon164 thermograph2)
	(have_image Phenomenon165 thermograph3)
	(have_image Phenomenon166 thermograph4)
	(have_image Star167 image1)
	(have_image Star168 image1)
	(have_image Star169 thermograph0)
))

)
