(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	satellite1 - satellite
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	satellite2 - satellite
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	satellite3 - satellite
	instrument11 - instrument
	satellite4 - satellite
	instrument12 - instrument
	instrument13 - instrument
	satellite5 - satellite
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	satellite6 - satellite
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	satellite7 - satellite
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	infrared2 - mode
	spectrograph0 - mode
	image4 - mode
	infrared3 - mode
	thermograph1 - mode
	GroundStation10 - direction
	Star49 - direction
	GroundStation78 - direction
	GroundStation79 - direction
	GroundStation45 - direction
	Star20 - direction
	Star59 - direction
	GroundStation37 - direction
	Star98 - direction
	GroundStation40 - direction
	GroundStation56 - direction
	Star18 - direction
	Star0 - direction
	Star85 - direction
	Star73 - direction
	GroundStation74 - direction
	Star76 - direction
	Star7 - direction
	GroundStation19 - direction
	Star36 - direction
	Star71 - direction
	GroundStation38 - direction
	Star54 - direction
	GroundStation32 - direction
	Star5 - direction
	GroundStation50 - direction
	GroundStation82 - direction
	GroundStation91 - direction
	Star24 - direction
	GroundStation13 - direction
	Star43 - direction
	GroundStation51 - direction
	GroundStation17 - direction
	GroundStation47 - direction
	GroundStation81 - direction
	Star68 - direction
	Star11 - direction
	Star4 - direction
	Star58 - direction
	GroundStation55 - direction
	Star67 - direction
	GroundStation14 - direction
	GroundStation62 - direction
	GroundStation53 - direction
	Star60 - direction
	GroundStation57 - direction
	GroundStation89 - direction
	Star84 - direction
	Star23 - direction
	Star48 - direction
	Star12 - direction
	Star16 - direction
	GroundStation63 - direction
	Star30 - direction
	GroundStation64 - direction
	GroundStation94 - direction
	Star75 - direction
	Star9 - direction
	GroundStation39 - direction
	GroundStation33 - direction
	Star88 - direction
	Star80 - direction
	Star92 - direction
	GroundStation29 - direction
	GroundStation6 - direction
	Star99 - direction
	Star35 - direction
	GroundStation93 - direction
	Star70 - direction
	GroundStation52 - direction
	GroundStation27 - direction
	GroundStation87 - direction
	Star72 - direction
	GroundStation42 - direction
	Star41 - direction
	GroundStation8 - direction
	GroundStation3 - direction
	GroundStation46 - direction
	GroundStation86 - direction
	Star31 - direction
	Star21 - direction
	Star77 - direction
	GroundStation83 - direction
	GroundStation22 - direction
	GroundStation15 - direction
	Star2 - direction
	GroundStation1 - direction
	Star61 - direction
	GroundStation66 - direction
	GroundStation97 - direction
	GroundStation69 - direction
	Star28 - direction
	GroundStation65 - direction
	Star96 - direction
	Star34 - direction
	GroundStation25 - direction
	GroundStation44 - direction
	GroundStation95 - direction
	Star26 - direction
	GroundStation90 - direction
	Planet100 - direction
	Phenomenon101 - direction
	Planet102 - direction
	Star103 - direction
	Phenomenon104 - direction
	Phenomenon105 - direction
	Phenomenon106 - direction
	Star107 - direction
	Phenomenon108 - direction
	Phenomenon109 - direction
	Star110 - direction
	Star111 - direction
	Planet112 - direction
	Star113 - direction
	Planet114 - direction
	Planet115 - direction
	Phenomenon116 - direction
	Phenomenon117 - direction
	Phenomenon118 - direction
	Planet119 - direction
	Phenomenon120 - direction
	Phenomenon121 - direction
	Phenomenon122 - direction
	Planet123 - direction
	Star124 - direction
	Planet125 - direction
	Star126 - direction
	Star127 - direction
	Phenomenon128 - direction
	Star129 - direction
	Planet130 - direction
	Planet131 - direction
	Star132 - direction
	Planet133 - direction
	Star134 - direction
	Phenomenon135 - direction
	Phenomenon136 - direction
	Planet137 - direction
	Planet138 - direction
	Planet139 - direction
	Planet140 - direction
	Planet141 - direction
	Star142 - direction
	Star143 - direction
	Phenomenon144 - direction
	Star145 - direction
	Phenomenon146 - direction
	Star147 - direction
	Phenomenon148 - direction
	Planet149 - direction
	Phenomenon150 - direction
	Phenomenon151 - direction
	Phenomenon152 - direction
	Star153 - direction
	Star154 - direction
	Star155 - direction
	Phenomenon156 - direction
	Phenomenon157 - direction
	Phenomenon158 - direction
	Planet159 - direction
	Star160 - direction
	Phenomenon161 - direction
	Planet162 - direction
	Phenomenon163 - direction
	Phenomenon164 - direction
	Planet165 - direction
	Star166 - direction
	Planet167 - direction
	Star168 - direction
	Star169 - direction
)
(:init
	(supports instrument0 infrared3)
	(calibration_target instrument0 Star31)
	(calibration_target instrument0 GroundStation56)
	(calibration_target instrument0 Star67)
	(calibration_target instrument0 GroundStation97)
	(calibration_target instrument0 GroundStation93)
	(supports instrument1 thermograph1)
	(calibration_target instrument1 Star36)
	(calibration_target instrument1 GroundStation74)
	(calibration_target instrument1 Star16)
	(calibration_target instrument1 GroundStation38)
	(calibration_target instrument1 GroundStation65)
	(calibration_target instrument1 Star35)
	(calibration_target instrument1 GroundStation95)
	(calibration_target instrument1 Star60)
	(calibration_target instrument1 Star73)
	(calibration_target instrument1 GroundStation39)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation45)
	(supports instrument2 spectrograph0)
	(calibration_target instrument2 Star34)
	(calibration_target instrument2 GroundStation56)
	(calibration_target instrument2 Star92)
	(calibration_target instrument2 GroundStation55)
	(supports instrument3 infrared3)
	(calibration_target instrument3 Star9)
	(calibration_target instrument3 Star92)
	(calibration_target instrument3 Star71)
	(calibration_target instrument3 GroundStation44)
	(calibration_target instrument3 Star72)
	(calibration_target instrument3 GroundStation97)
	(calibration_target instrument3 Star98)
	(calibration_target instrument3 Star41)
	(calibration_target instrument3 GroundStation45)
	(calibration_target instrument3 GroundStation93)
	(calibration_target instrument3 GroundStation91)
	(calibration_target instrument3 Star35)
	(calibration_target instrument3 GroundStation87)
	(calibration_target instrument3 GroundStation19)
	(calibration_target instrument3 GroundStation74)
	(calibration_target instrument3 Star24)
	(calibration_target instrument3 GroundStation14)
	(calibration_target instrument3 GroundStation56)
	(supports instrument4 infrared3)
	(calibration_target instrument4 Star54)
	(calibration_target instrument4 GroundStation94)
	(calibration_target instrument4 GroundStation44)
	(calibration_target instrument4 GroundStation40)
	(calibration_target instrument4 Star61)
	(calibration_target instrument4 Star20)
	(supports instrument5 infrared2)
	(supports instrument5 spectrograph0)
	(calibration_target instrument5 Star54)
	(calibration_target instrument5 Star26)
	(calibration_target instrument5 GroundStation3)
	(calibration_target instrument5 Star5)
	(calibration_target instrument5 GroundStation56)
	(calibration_target instrument5 GroundStation42)
	(calibration_target instrument5 GroundStation90)
	(calibration_target instrument5 GroundStation64)
	(calibration_target instrument5 Star75)
	(calibration_target instrument5 GroundStation19)
	(calibration_target instrument5 Star68)
	(calibration_target instrument5 Star43)
	(calibration_target instrument5 GroundStation91)
	(supports instrument6 infrared3)
	(supports instrument6 spectrograph0)
	(calibration_target instrument6 GroundStation56)
	(calibration_target instrument6 Star36)
	(calibration_target instrument6 Star70)
	(calibration_target instrument6 Star54)
	(calibration_target instrument6 Star24)
	(calibration_target instrument6 GroundStation25)
	(calibration_target instrument6 GroundStation46)
	(on_board instrument2 satellite1)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star58)
	(supports instrument7 infrared2)
	(supports instrument7 infrared3)
	(calibration_target instrument7 Star60)
	(calibration_target instrument7 GroundStation82)
	(calibration_target instrument7 Star26)
	(calibration_target instrument7 Star23)
	(calibration_target instrument7 GroundStation13)
	(calibration_target instrument7 Star18)
	(calibration_target instrument7 GroundStation17)
	(calibration_target instrument7 Star61)
	(calibration_target instrument7 GroundStation39)
	(calibration_target instrument7 GroundStation15)
	(calibration_target instrument7 Star88)
	(calibration_target instrument7 Star71)
	(calibration_target instrument7 Star76)
	(calibration_target instrument7 GroundStation91)
	(supports instrument8 infrared3)
	(supports instrument8 thermograph1)
	(calibration_target instrument8 GroundStation51)
	(supports instrument9 spectrograph0)
	(calibration_target instrument9 GroundStation66)
	(calibration_target instrument9 GroundStation27)
	(calibration_target instrument9 GroundStation51)
	(calibration_target instrument9 Star96)
	(calibration_target instrument9 GroundStation97)
	(calibration_target instrument9 Star75)
	(calibration_target instrument9 Star24)
	(calibration_target instrument9 GroundStation89)
	(calibration_target instrument9 GroundStation8)
	(calibration_target instrument9 Star61)
	(calibration_target instrument9 GroundStation83)
	(calibration_target instrument9 GroundStation38)
	(calibration_target instrument9 Star7)
	(calibration_target instrument9 GroundStation69)
	(calibration_target instrument9 Star59)
	(supports instrument10 infrared2)
	(calibration_target instrument10 Star80)
	(calibration_target instrument10 GroundStation56)
	(calibration_target instrument10 GroundStation14)
	(calibration_target instrument10 Star2)
	(calibration_target instrument10 Star92)
	(calibration_target instrument10 GroundStation69)
	(calibration_target instrument10 Star28)
	(calibration_target instrument10 GroundStation74)
	(calibration_target instrument10 Star58)
	(calibration_target instrument10 GroundStation19)
	(calibration_target instrument10 Star98)
	(calibration_target instrument10 GroundStation44)
	(calibration_target instrument10 GroundStation38)
	(calibration_target instrument10 GroundStation37)
	(calibration_target instrument10 Star0)
	(calibration_target instrument10 GroundStation81)
	(calibration_target instrument10 Star99)
	(calibration_target instrument10 Star73)
	(calibration_target instrument10 GroundStation3)
	(calibration_target instrument10 Star72)
	(calibration_target instrument10 GroundStation33)
	(calibration_target instrument10 GroundStation39)
	(calibration_target instrument10 GroundStation6)
	(calibration_target instrument10 Star96)
	(calibration_target instrument10 GroundStation29)
	(calibration_target instrument10 GroundStation8)
	(calibration_target instrument10 Star75)
	(calibration_target instrument10 GroundStation13)
	(on_board instrument7 satellite2)
	(on_board instrument8 satellite2)
	(on_board instrument9 satellite2)
	(on_board instrument10 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star85)
	(supports instrument11 thermograph1)
	(calibration_target instrument11 GroundStation13)
	(calibration_target instrument11 Star85)
	(calibration_target instrument11 GroundStation57)
	(calibration_target instrument11 Star60)
	(calibration_target instrument11 GroundStation40)
	(calibration_target instrument11 Star9)
	(calibration_target instrument11 Star80)
	(calibration_target instrument11 Star30)
	(calibration_target instrument11 Star5)
	(calibration_target instrument11 Star88)
	(calibration_target instrument11 GroundStation33)
	(calibration_target instrument11 GroundStation3)
	(calibration_target instrument11 Star68)
	(calibration_target instrument11 Star0)
	(calibration_target instrument11 Star96)
	(calibration_target instrument11 GroundStation29)
	(calibration_target instrument11 Star11)
	(calibration_target instrument11 Star54)
	(on_board instrument11 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation32)
	(supports instrument12 infrared2)
	(calibration_target instrument12 GroundStation33)
	(calibration_target instrument12 GroundStation14)
	(supports instrument13 infrared2)
	(supports instrument13 spectrograph0)
	(supports instrument13 image4)
	(calibration_target instrument13 GroundStation82)
	(calibration_target instrument13 Star0)
	(calibration_target instrument13 Star80)
	(calibration_target instrument13 Star18)
	(calibration_target instrument13 GroundStation81)
	(calibration_target instrument13 GroundStation64)
	(calibration_target instrument13 GroundStation33)
	(calibration_target instrument13 GroundStation65)
	(calibration_target instrument13 GroundStation22)
	(calibration_target instrument13 Star73)
	(calibration_target instrument13 GroundStation91)
	(calibration_target instrument13 GroundStation53)
	(calibration_target instrument13 GroundStation44)
	(calibration_target instrument13 GroundStation27)
	(calibration_target instrument13 Star34)
	(calibration_target instrument13 Star84)
	(calibration_target instrument13 Star41)
	(calibration_target instrument13 Star67)
	(calibration_target instrument13 Star23)
	(calibration_target instrument13 Star71)
	(calibration_target instrument13 GroundStation14)
	(calibration_target instrument13 Star61)
	(calibration_target instrument13 GroundStation94)
	(calibration_target instrument13 GroundStation56)
	(calibration_target instrument13 GroundStation32)
	(on_board instrument12 satellite4)
	(on_board instrument13 satellite4)
	(power_avail satellite4)
	(pointing satellite4 GroundStation79)
	(supports instrument14 image4)
	(calibration_target instrument14 GroundStation25)
	(calibration_target instrument14 Star16)
	(calibration_target instrument14 GroundStation94)
	(calibration_target instrument14 Star35)
	(calibration_target instrument14 Star61)
	(calibration_target instrument14 Star9)
	(calibration_target instrument14 Star67)
	(calibration_target instrument14 Star85)
	(calibration_target instrument14 Star54)
	(calibration_target instrument14 Star88)
	(calibration_target instrument14 GroundStation32)
	(calibration_target instrument14 GroundStation87)
	(supports instrument15 infrared3)
	(supports instrument15 thermograph1)
	(supports instrument15 spectrograph0)
	(calibration_target instrument15 Star96)
	(calibration_target instrument15 GroundStation74)
	(calibration_target instrument15 Star2)
	(calibration_target instrument15 Star73)
	(calibration_target instrument15 Star76)
	(calibration_target instrument15 GroundStation91)
	(calibration_target instrument15 Star92)
	(calibration_target instrument15 GroundStation25)
	(calibration_target instrument15 GroundStation29)
	(supports instrument16 image4)
	(calibration_target instrument16 GroundStation15)
	(calibration_target instrument16 GroundStation66)
	(calibration_target instrument16 Star21)
	(calibration_target instrument16 Star35)
	(calibration_target instrument16 Star9)
	(calibration_target instrument16 Star88)
	(calibration_target instrument16 GroundStation25)
	(calibration_target instrument16 Star76)
	(calibration_target instrument16 Star4)
	(on_board instrument14 satellite5)
	(on_board instrument15 satellite5)
	(on_board instrument16 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star143)
	(supports instrument17 infrared3)
	(calibration_target instrument17 Star68)
	(calibration_target instrument17 Star48)
	(calibration_target instrument17 GroundStation1)
	(calibration_target instrument17 Star54)
	(calibration_target instrument17 GroundStation38)
	(calibration_target instrument17 GroundStation50)
	(calibration_target instrument17 GroundStation22)
	(calibration_target instrument17 GroundStation83)
	(calibration_target instrument17 Star2)
	(calibration_target instrument17 Star71)
	(calibration_target instrument17 Star36)
	(calibration_target instrument17 Star4)
	(calibration_target instrument17 GroundStation87)
	(calibration_target instrument17 GroundStation32)
	(calibration_target instrument17 GroundStation19)
	(calibration_target instrument17 Star5)
	(calibration_target instrument17 Star77)
	(calibration_target instrument17 Star7)
	(calibration_target instrument17 Star12)
	(calibration_target instrument17 Star35)
	(calibration_target instrument17 GroundStation95)
	(calibration_target instrument17 GroundStation86)
	(calibration_target instrument17 GroundStation55)
	(calibration_target instrument17 Star41)
	(calibration_target instrument17 GroundStation3)
	(supports instrument18 thermograph1)
	(supports instrument18 spectrograph0)
	(calibration_target instrument18 Star43)
	(calibration_target instrument18 GroundStation50)
	(calibration_target instrument18 Star5)
	(calibration_target instrument18 GroundStation47)
	(calibration_target instrument18 GroundStation62)
	(calibration_target instrument18 GroundStation13)
	(calibration_target instrument18 Star67)
	(calibration_target instrument18 GroundStation32)
	(calibration_target instrument18 Star23)
	(calibration_target instrument18 Star26)
	(calibration_target instrument18 GroundStation25)
	(calibration_target instrument18 GroundStation6)
	(calibration_target instrument18 Star24)
	(calibration_target instrument18 Star61)
	(calibration_target instrument18 GroundStation66)
	(calibration_target instrument18 GroundStation64)
	(calibration_target instrument18 GroundStation69)
	(supports instrument19 thermograph1)
	(calibration_target instrument19 GroundStation22)
	(calibration_target instrument19 GroundStation95)
	(calibration_target instrument19 GroundStation53)
	(calibration_target instrument19 GroundStation62)
	(calibration_target instrument19 GroundStation14)
	(calibration_target instrument19 GroundStation86)
	(calibration_target instrument19 Star70)
	(calibration_target instrument19 Star67)
	(calibration_target instrument19 GroundStation27)
	(calibration_target instrument19 GroundStation55)
	(calibration_target instrument19 Star58)
	(calibration_target instrument19 GroundStation97)
	(calibration_target instrument19 Star4)
	(calibration_target instrument19 Star11)
	(calibration_target instrument19 Star68)
	(calibration_target instrument19 GroundStation90)
	(calibration_target instrument19 GroundStation81)
	(calibration_target instrument19 Star48)
	(calibration_target instrument19 GroundStation47)
	(calibration_target instrument19 Star23)
	(calibration_target instrument19 GroundStation17)
	(calibration_target instrument19 GroundStation51)
	(calibration_target instrument19 Star43)
	(calibration_target instrument19 GroundStation13)
	(calibration_target instrument19 Star24)
	(calibration_target instrument19 GroundStation89)
	(calibration_target instrument19 Star77)
	(calibration_target instrument19 GroundStation94)
	(calibration_target instrument19 Star84)
	(calibration_target instrument19 GroundStation91)
	(calibration_target instrument19 GroundStation82)
	(calibration_target instrument19 GroundStation42)
	(calibration_target instrument19 GroundStation8)
	(supports instrument20 infrared2)
	(supports instrument20 infrared3)
	(supports instrument20 spectrograph0)
	(calibration_target instrument20 Star96)
	(calibration_target instrument20 GroundStation57)
	(calibration_target instrument20 Star60)
	(calibration_target instrument20 GroundStation95)
	(on_board instrument17 satellite6)
	(on_board instrument18 satellite6)
	(on_board instrument19 satellite6)
	(on_board instrument20 satellite6)
	(power_avail satellite6)
	(pointing satellite6 GroundStation55)
	(supports instrument21 thermograph1)
	(calibration_target instrument21 Star88)
	(calibration_target instrument21 Star16)
	(calibration_target instrument21 Star12)
	(calibration_target instrument21 Star75)
	(calibration_target instrument21 GroundStation87)
	(calibration_target instrument21 Star48)
	(calibration_target instrument21 Star23)
	(calibration_target instrument21 Star84)
	(calibration_target instrument21 GroundStation89)
	(calibration_target instrument21 GroundStation95)
	(supports instrument22 spectrograph0)
	(supports instrument22 infrared2)
	(calibration_target instrument22 Star72)
	(calibration_target instrument22 GroundStation87)
	(calibration_target instrument22 GroundStation69)
	(calibration_target instrument22 GroundStation27)
	(calibration_target instrument22 GroundStation52)
	(calibration_target instrument22 Star70)
	(calibration_target instrument22 GroundStation93)
	(calibration_target instrument22 Star35)
	(calibration_target instrument22 Star99)
	(calibration_target instrument22 GroundStation66)
	(calibration_target instrument22 GroundStation6)
	(calibration_target instrument22 GroundStation8)
	(calibration_target instrument22 GroundStation29)
	(calibration_target instrument22 Star92)
	(calibration_target instrument22 Star80)
	(calibration_target instrument22 Star88)
	(calibration_target instrument22 GroundStation33)
	(calibration_target instrument22 Star2)
	(calibration_target instrument22 GroundStation39)
	(calibration_target instrument22 Star9)
	(calibration_target instrument22 Star75)
	(calibration_target instrument22 GroundStation25)
	(calibration_target instrument22 GroundStation94)
	(calibration_target instrument22 GroundStation64)
	(calibration_target instrument22 Star30)
	(calibration_target instrument22 GroundStation63)
	(supports instrument23 infrared2)
	(supports instrument23 thermograph1)
	(supports instrument23 spectrograph0)
	(calibration_target instrument23 Star26)
	(calibration_target instrument23 GroundStation95)
	(calibration_target instrument23 GroundStation44)
	(calibration_target instrument23 GroundStation25)
	(calibration_target instrument23 Star34)
	(calibration_target instrument23 Star96)
	(calibration_target instrument23 GroundStation65)
	(calibration_target instrument23 Star28)
	(calibration_target instrument23 GroundStation69)
	(calibration_target instrument23 GroundStation97)
	(calibration_target instrument23 GroundStation66)
	(calibration_target instrument23 Star61)
	(calibration_target instrument23 GroundStation1)
	(calibration_target instrument23 Star2)
	(calibration_target instrument23 GroundStation15)
	(calibration_target instrument23 GroundStation22)
	(calibration_target instrument23 GroundStation83)
	(calibration_target instrument23 Star77)
	(calibration_target instrument23 Star21)
	(calibration_target instrument23 Star31)
	(calibration_target instrument23 GroundStation86)
	(calibration_target instrument23 GroundStation46)
	(calibration_target instrument23 GroundStation3)
	(calibration_target instrument23 GroundStation8)
	(calibration_target instrument23 Star41)
	(calibration_target instrument23 GroundStation42)
	(supports instrument24 infrared2)
	(calibration_target instrument24 GroundStation90)
	(on_board instrument21 satellite7)
	(on_board instrument22 satellite7)
	(on_board instrument23 satellite7)
	(on_board instrument24 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star129)
)
(:goal (and
	(pointing satellite1 Phenomenon128)
	(pointing satellite3 Phenomenon135)
	(pointing satellite6 GroundStation8)
	(pointing satellite7 Star48)
	(have_image Planet100 thermograph1)
	(have_image Phenomenon101 thermograph1)
	(have_image Planet102 image4)
	(have_image Star103 image4)
	(have_image Phenomenon104 infrared3)
	(have_image Phenomenon105 infrared2)
	(have_image Phenomenon106 spectrograph0)
	(have_image Star107 infrared2)
	(have_image Phenomenon108 infrared3)
	(have_image Phenomenon109 spectrograph0)
	(have_image Star110 thermograph1)
	(have_image Star111 infrared3)
	(have_image Planet112 spectrograph0)
	(have_image Star113 spectrograph0)
	(have_image Planet114 infrared3)
	(have_image Planet115 infrared2)
	(have_image Phenomenon116 infrared3)
	(have_image Phenomenon117 image4)
	(have_image Phenomenon118 image4)
	(have_image Planet119 spectrograph0)
	(have_image Phenomenon120 spectrograph0)
	(have_image Phenomenon121 infrared3)
	(have_image Phenomenon122 spectrograph0)
	(have_image Planet123 image4)
	(have_image Star124 spectrograph0)
	(have_image Planet125 spectrograph0)
	(have_image Star126 infrared2)
	(have_image Star127 thermograph1)
	(have_image Phenomenon128 thermograph1)
	(have_image Star129 image4)
	(have_image Planet130 image4)
	(have_image Planet131 infrared2)
	(have_image Star132 infrared3)
	(have_image Planet133 infrared3)
	(have_image Star134 infrared2)
	(have_image Phenomenon135 infrared2)
	(have_image Phenomenon136 image4)
	(have_image Planet137 thermograph1)
	(have_image Planet138 image4)
	(have_image Planet139 thermograph1)
	(have_image Planet140 infrared2)
	(have_image Planet141 image4)
	(have_image Star142 image4)
	(have_image Star143 thermograph1)
	(have_image Phenomenon144 infrared3)
	(have_image Star145 thermograph1)
	(have_image Phenomenon146 infrared2)
	(have_image Star147 spectrograph0)
	(have_image Phenomenon148 image4)
	(have_image Planet149 infrared2)
	(have_image Phenomenon150 spectrograph0)
	(have_image Phenomenon151 image4)
	(have_image Phenomenon152 thermograph1)
	(have_image Star153 image4)
	(have_image Star154 thermograph1)
	(have_image Star155 thermograph1)
	(have_image Phenomenon156 infrared3)
	(have_image Phenomenon157 infrared3)
	(have_image Phenomenon158 image4)
	(have_image Planet159 spectrograph0)
	(have_image Star160 infrared2)
	(have_image Phenomenon161 infrared3)
	(have_image Planet162 infrared2)
	(have_image Phenomenon163 thermograph1)
	(have_image Phenomenon164 spectrograph0)
	(have_image Planet165 infrared2)
	(have_image Star166 spectrograph0)
	(have_image Planet167 image4)
	(have_image Star168 spectrograph0)
	(have_image Star169 spectrograph0)
))

)
