(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	satellite1 - satellite
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	satellite2 - satellite
	instrument7 - instrument
	satellite3 - satellite
	instrument8 - instrument
	infrared1 - mode
	thermograph2 - mode
	infrared4 - mode
	infrared3 - mode
	image0 - mode
	Star0 - direction
	Star1 - direction
	GroundStation11 - direction
	GroundStation15 - direction
	GroundStation28 - direction
	GroundStation29 - direction
	Star3 - direction
	Star20 - direction
	Star39 - direction
	Star26 - direction
	Star8 - direction
	Star25 - direction
	Star2 - direction
	GroundStation7 - direction
	GroundStation36 - direction
	GroundStation5 - direction
	GroundStation33 - direction
	GroundStation27 - direction
	Star30 - direction
	Star24 - direction
	Star13 - direction
	GroundStation22 - direction
	Star35 - direction
	Star9 - direction
	GroundStation17 - direction
	Star12 - direction
	GroundStation32 - direction
	GroundStation18 - direction
	Star37 - direction
	GroundStation34 - direction
	GroundStation21 - direction
	Star10 - direction
	Star19 - direction
	Star14 - direction
	Star31 - direction
	GroundStation6 - direction
	Star16 - direction
	GroundStation4 - direction
	Star38 - direction
	Star23 - direction
	Phenomenon40 - direction
	Star41 - direction
	Star42 - direction
	Planet43 - direction
	Star44 - direction
	Phenomenon45 - direction
	Phenomenon46 - direction
	Planet47 - direction
	Planet48 - direction
	Phenomenon49 - direction
	Planet50 - direction
	Planet51 - direction
	Phenomenon52 - direction
	Phenomenon53 - direction
	Phenomenon54 - direction
	Planet55 - direction
	Phenomenon56 - direction
	Phenomenon57 - direction
	Phenomenon58 - direction
	Phenomenon59 - direction
	Star60 - direction
	Star61 - direction
	Star62 - direction
	Phenomenon63 - direction
	Planet64 - direction
)
(:init
	(supports instrument0 image0)
	(calibration_target instrument0 Star20)
	(calibration_target instrument0 GroundStation4)
	(calibration_target instrument0 Star3)
	(calibration_target instrument0 Star19)
	(calibration_target instrument0 Star16)
	(calibration_target instrument0 Star23)
	(calibration_target instrument0 Star37)
	(supports instrument1 thermograph2)
	(calibration_target instrument1 Star26)
	(calibration_target instrument1 GroundStation21)
	(calibration_target instrument1 Star39)
	(calibration_target instrument1 Star14)
	(calibration_target instrument1 GroundStation4)
	(calibration_target instrument1 GroundStation33)
	(calibration_target instrument1 GroundStation7)
	(calibration_target instrument1 GroundStation17)
	(calibration_target instrument1 Star19)
	(calibration_target instrument1 GroundStation34)
	(supports instrument2 infrared3)
	(supports instrument2 infrared4)
	(supports instrument2 infrared1)
	(calibration_target instrument2 GroundStation5)
	(calibration_target instrument2 Star19)
	(calibration_target instrument2 Star8)
	(supports instrument3 thermograph2)
	(supports instrument3 infrared4)
	(supports instrument3 image0)
	(calibration_target instrument3 GroundStation27)
	(calibration_target instrument3 Star25)
	(calibration_target instrument3 GroundStation7)
	(calibration_target instrument3 GroundStation18)
	(calibration_target instrument3 Star2)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation36)
	(supports instrument4 thermograph2)
	(calibration_target instrument4 Star30)
	(calibration_target instrument4 GroundStation34)
	(calibration_target instrument4 GroundStation27)
	(calibration_target instrument4 GroundStation33)
	(calibration_target instrument4 Star16)
	(calibration_target instrument4 GroundStation5)
	(calibration_target instrument4 GroundStation36)
	(calibration_target instrument4 GroundStation7)
	(calibration_target instrument4 Star38)
	(calibration_target instrument4 GroundStation17)
	(calibration_target instrument4 GroundStation22)
	(calibration_target instrument4 Star2)
	(supports instrument5 image0)
	(supports instrument5 infrared3)
	(supports instrument5 infrared4)
	(calibration_target instrument5 Star12)
	(calibration_target instrument5 GroundStation32)
	(calibration_target instrument5 Star9)
	(calibration_target instrument5 GroundStation17)
	(calibration_target instrument5 Star35)
	(calibration_target instrument5 GroundStation22)
	(calibration_target instrument5 Star31)
	(calibration_target instrument5 Star13)
	(calibration_target instrument5 Star24)
	(calibration_target instrument5 Star37)
	(supports instrument6 infrared3)
	(supports instrument6 thermograph2)
	(supports instrument6 infrared1)
	(calibration_target instrument6 GroundStation6)
	(calibration_target instrument6 GroundStation17)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation17)
	(supports instrument7 thermograph2)
	(calibration_target instrument7 GroundStation18)
	(calibration_target instrument7 GroundStation32)
	(calibration_target instrument7 Star12)
	(on_board instrument7 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star19)
	(supports instrument8 infrared3)
	(supports instrument8 image0)
	(supports instrument8 thermograph2)
	(calibration_target instrument8 Star23)
	(calibration_target instrument8 Star38)
	(calibration_target instrument8 GroundStation4)
	(calibration_target instrument8 Star16)
	(calibration_target instrument8 GroundStation6)
	(calibration_target instrument8 Star31)
	(calibration_target instrument8 Star14)
	(calibration_target instrument8 Star19)
	(calibration_target instrument8 Star10)
	(calibration_target instrument8 GroundStation21)
	(calibration_target instrument8 GroundStation34)
	(calibration_target instrument8 Star37)
	(on_board instrument8 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star20)
)
(:goal (and
	(pointing satellite0 Planet50)
	(pointing satellite1 Phenomenon54)
	(pointing satellite3 GroundStation15)
	(have_image Phenomenon40 image0)
	(have_image Star41 thermograph2)
	(have_image Star42 infrared1)
	(have_image Planet43 infrared3)
	(have_image Star44 infrared3)
	(have_image Phenomenon45 thermograph2)
	(have_image Phenomenon46 thermograph2)
	(have_image Planet47 infrared3)
	(have_image Planet48 infrared1)
	(have_image Phenomenon49 infrared1)
	(have_image Planet50 infrared1)
	(have_image Planet51 infrared4)
	(have_image Phenomenon52 image0)
	(have_image Phenomenon53 infrared1)
	(have_image Phenomenon54 infrared4)
	(have_image Planet55 thermograph2)
	(have_image Phenomenon56 infrared1)
	(have_image Phenomenon57 infrared1)
	(have_image Phenomenon58 infrared1)
	(have_image Phenomenon59 thermograph2)
	(have_image Star60 thermograph2)
	(have_image Star61 infrared4)
	(have_image Star62 infrared1)
	(have_image Phenomenon63 infrared4)
	(have_image Planet64 infrared1)
))

)
