(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	satellite1 - satellite
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	satellite2 - satellite
	instrument7 - instrument
	instrument8 - instrument
	satellite3 - satellite
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	thermograph1 - mode
	thermograph2 - mode
	infrared4 - mode
	infrared0 - mode
	image3 - mode
	Star25 - direction
	GroundStation27 - direction
	Star36 - direction
	Star12 - direction
	Star5 - direction
	GroundStation4 - direction
	Star21 - direction
	Star32 - direction
	GroundStation38 - direction
	GroundStation20 - direction
	GroundStation17 - direction
	Star35 - direction
	Star14 - direction
	Star1 - direction
	GroundStation29 - direction
	GroundStation13 - direction
	Star15 - direction
	Star7 - direction
	GroundStation39 - direction
	Star23 - direction
	Star24 - direction
	GroundStation2 - direction
	GroundStation26 - direction
	GroundStation18 - direction
	Star10 - direction
	Star6 - direction
	Star16 - direction
	GroundStation28 - direction
	GroundStation37 - direction
	GroundStation11 - direction
	GroundStation8 - direction
	Star33 - direction
	GroundStation30 - direction
	Star3 - direction
	Star9 - direction
	GroundStation0 - direction
	Star19 - direction
	GroundStation22 - direction
	GroundStation34 - direction
	GroundStation31 - direction
	Phenomenon40 - direction
	Planet41 - direction
	Phenomenon42 - direction
	Star43 - direction
	Star44 - direction
	Planet45 - direction
	Phenomenon46 - direction
	Planet47 - direction
	Planet48 - direction
	Phenomenon49 - direction
	Phenomenon50 - direction
	Planet51 - direction
	Phenomenon52 - direction
	Star53 - direction
	Phenomenon54 - direction
	Planet55 - direction
	Phenomenon56 - direction
	Planet57 - direction
	Planet58 - direction
	Star59 - direction
	Phenomenon60 - direction
	Planet61 - direction
	Planet62 - direction
	Star63 - direction
	Phenomenon64 - direction
)
(:init
	(supports instrument0 thermograph2)
	(supports instrument0 infrared4)
	(supports instrument0 image3)
	(calibration_target instrument0 Star35)
	(calibration_target instrument0 Star21)
	(calibration_target instrument0 Star16)
	(calibration_target instrument0 GroundStation17)
	(calibration_target instrument0 GroundStation37)
	(calibration_target instrument0 Star1)
	(calibration_target instrument0 Star33)
	(calibration_target instrument0 GroundStation13)
	(calibration_target instrument0 GroundStation30)
	(calibration_target instrument0 GroundStation31)
	(calibration_target instrument0 GroundStation20)
	(supports instrument1 image3)
	(calibration_target instrument1 GroundStation0)
	(calibration_target instrument1 Star24)
	(calibration_target instrument1 Star3)
	(calibration_target instrument1 Star6)
	(calibration_target instrument1 GroundStation27)
	(calibration_target instrument1 Star33)
	(calibration_target instrument1 Star35)
	(calibration_target instrument1 GroundStation4)
	(calibration_target instrument1 Star14)
	(calibration_target instrument1 Star25)
	(calibration_target instrument1 Star21)
	(calibration_target instrument1 GroundStation18)
	(calibration_target instrument1 Star15)
	(supports instrument2 thermograph1)
	(calibration_target instrument2 Star21)
	(calibration_target instrument2 Star32)
	(calibration_target instrument2 GroundStation39)
	(calibration_target instrument2 Star12)
	(calibration_target instrument2 Star36)
	(calibration_target instrument2 Star1)
	(supports instrument3 image3)
	(supports instrument3 infrared4)
	(supports instrument3 infrared0)
	(calibration_target instrument3 GroundStation30)
	(calibration_target instrument3 Star21)
	(calibration_target instrument3 Star23)
	(calibration_target instrument3 GroundStation39)
	(calibration_target instrument3 Star1)
	(calibration_target instrument3 GroundStation31)
	(calibration_target instrument3 GroundStation20)
	(calibration_target instrument3 GroundStation4)
	(calibration_target instrument3 GroundStation17)
	(calibration_target instrument3 Star5)
	(calibration_target instrument3 GroundStation0)
	(calibration_target instrument3 Star14)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star9)
	(supports instrument4 image3)
	(supports instrument4 infrared4)
	(supports instrument4 thermograph1)
	(calibration_target instrument4 GroundStation29)
	(calibration_target instrument4 Star9)
	(calibration_target instrument4 GroundStation18)
	(calibration_target instrument4 GroundStation17)
	(calibration_target instrument4 GroundStation11)
	(calibration_target instrument4 GroundStation13)
	(calibration_target instrument4 Star33)
	(calibration_target instrument4 Star3)
	(calibration_target instrument4 Star32)
	(calibration_target instrument4 GroundStation39)
	(supports instrument5 thermograph1)
	(supports instrument5 infrared0)
	(supports instrument5 image3)
	(calibration_target instrument5 GroundStation8)
	(calibration_target instrument5 GroundStation20)
	(calibration_target instrument5 GroundStation37)
	(calibration_target instrument5 GroundStation11)
	(calibration_target instrument5 GroundStation38)
	(calibration_target instrument5 Star9)
	(supports instrument6 thermograph1)
	(supports instrument6 infrared4)
	(calibration_target instrument6 Star35)
	(calibration_target instrument6 GroundStation13)
	(calibration_target instrument6 GroundStation17)
	(calibration_target instrument6 GroundStation18)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star63)
	(supports instrument7 infrared0)
	(calibration_target instrument7 GroundStation13)
	(calibration_target instrument7 GroundStation29)
	(calibration_target instrument7 GroundStation39)
	(calibration_target instrument7 GroundStation22)
	(calibration_target instrument7 Star10)
	(calibration_target instrument7 Star7)
	(calibration_target instrument7 Star19)
	(calibration_target instrument7 Star1)
	(calibration_target instrument7 Star9)
	(calibration_target instrument7 Star14)
	(supports instrument8 infrared4)
	(supports instrument8 infrared0)
	(supports instrument8 thermograph1)
	(calibration_target instrument8 Star9)
	(calibration_target instrument8 GroundStation37)
	(calibration_target instrument8 GroundStation39)
	(calibration_target instrument8 Star7)
	(calibration_target instrument8 Star15)
	(calibration_target instrument8 GroundStation11)
	(calibration_target instrument8 Star19)
	(on_board instrument7 satellite2)
	(on_board instrument8 satellite2)
	(power_avail satellite2)
	(pointing satellite2 GroundStation31)
	(supports instrument9 image3)
	(supports instrument9 thermograph1)
	(calibration_target instrument9 GroundStation18)
	(calibration_target instrument9 GroundStation26)
	(calibration_target instrument9 GroundStation2)
	(calibration_target instrument9 GroundStation30)
	(calibration_target instrument9 GroundStation22)
	(calibration_target instrument9 Star33)
	(calibration_target instrument9 Star24)
	(calibration_target instrument9 Star23)
	(supports instrument10 thermograph1)
	(supports instrument10 image3)
	(calibration_target instrument10 Star9)
	(calibration_target instrument10 Star3)
	(calibration_target instrument10 GroundStation30)
	(calibration_target instrument10 Star33)
	(calibration_target instrument10 GroundStation8)
	(calibration_target instrument10 GroundStation11)
	(calibration_target instrument10 GroundStation37)
	(calibration_target instrument10 GroundStation28)
	(calibration_target instrument10 Star16)
	(calibration_target instrument10 Star6)
	(calibration_target instrument10 Star10)
	(calibration_target instrument10 Star19)
	(supports instrument11 thermograph1)
	(calibration_target instrument11 GroundStation22)
	(calibration_target instrument11 Star19)
	(calibration_target instrument11 GroundStation0)
	(supports instrument12 infrared0)
	(supports instrument12 thermograph1)
	(calibration_target instrument12 GroundStation31)
	(calibration_target instrument12 GroundStation34)
	(on_board instrument9 satellite3)
	(on_board instrument10 satellite3)
	(on_board instrument11 satellite3)
	(on_board instrument12 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation30)
)
(:goal (and
	(pointing satellite1 Planet57)
	(pointing satellite2 Phenomenon40)
	(pointing satellite3 Star16)
	(have_image Phenomenon40 infrared0)
	(have_image Planet41 infrared0)
	(have_image Phenomenon42 infrared0)
	(have_image Star43 thermograph2)
	(have_image Star44 thermograph2)
	(have_image Planet45 infrared0)
	(have_image Phenomenon46 infrared0)
	(have_image Planet47 image3)
	(have_image Planet48 infrared0)
	(have_image Phenomenon49 infrared0)
	(have_image Phenomenon50 thermograph1)
	(have_image Planet51 image3)
	(have_image Phenomenon52 thermograph1)
	(have_image Star53 thermograph1)
	(have_image Phenomenon54 thermograph1)
	(have_image Planet55 infrared4)
	(have_image Phenomenon56 thermograph1)
	(have_image Planet57 infrared4)
	(have_image Planet58 thermograph1)
	(have_image Star59 infrared0)
	(have_image Phenomenon60 infrared0)
	(have_image Planet61 image3)
	(have_image Planet62 infrared0)
	(have_image Star63 infrared0)
	(have_image Phenomenon64 thermograph1)
))

)
