(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	satellite1 - satellite
	instrument2 - instrument
	satellite2 - satellite
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	satellite3 - satellite
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	satellite4 - satellite
	instrument10 - instrument
	instrument11 - instrument
	image0 - mode
	infrared4 - mode
	infrared1 - mode
	thermograph2 - mode
	infrared3 - mode
	Star9 - direction
	GroundStation33 - direction
	Star13 - direction
	Star16 - direction
	Star0 - direction
	Star31 - direction
	Star8 - direction
	Star2 - direction
	GroundStation21 - direction
	Star37 - direction
	Star42 - direction
	Star35 - direction
	GroundStation36 - direction
	Star12 - direction
	Star39 - direction
	GroundStation28 - direction
	Star38 - direction
	Star23 - direction
	Star20 - direction
	GroundStation44 - direction
	GroundStation34 - direction
	GroundStation11 - direction
	GroundStation4 - direction
	Star14 - direction
	GroundStation47 - direction
	GroundStation15 - direction
	Star19 - direction
	GroundStation48 - direction
	GroundStation32 - direction
	Star3 - direction
	Star25 - direction
	Star30 - direction
	GroundStation22 - direction
	Star43 - direction
	Star49 - direction
	Star10 - direction
	GroundStation18 - direction
	Star45 - direction
	Star26 - direction
	Star46 - direction
	GroundStation17 - direction
	Star1 - direction
	GroundStation27 - direction
	GroundStation6 - direction
	GroundStation7 - direction
	Star41 - direction
	GroundStation5 - direction
	Star40 - direction
	Star24 - direction
	GroundStation29 - direction
	Planet50 - direction
	Star51 - direction
	Phenomenon52 - direction
	Planet53 - direction
	Phenomenon54 - direction
	Phenomenon55 - direction
	Planet56 - direction
	Star57 - direction
	Phenomenon58 - direction
	Planet59 - direction
	Star60 - direction
	Planet61 - direction
	Star62 - direction
	Phenomenon63 - direction
	Planet64 - direction
	Planet65 - direction
	Star66 - direction
	Phenomenon67 - direction
	Phenomenon68 - direction
	Phenomenon69 - direction
	Planet70 - direction
	Phenomenon71 - direction
	Phenomenon72 - direction
	Phenomenon73 - direction
	Phenomenon74 - direction
	Star75 - direction
	Phenomenon76 - direction
	Planet77 - direction
	Planet78 - direction
	Phenomenon79 - direction
	Planet80 - direction
	Planet81 - direction
	Planet82 - direction
	Planet83 - direction
	Planet84 - direction
)
(:init
	(supports instrument0 infrared1)
	(supports instrument0 infrared4)
	(calibration_target instrument0 Star45)
	(calibration_target instrument0 Star41)
	(calibration_target instrument0 GroundStation7)
	(calibration_target instrument0 GroundStation18)
	(calibration_target instrument0 Star20)
	(calibration_target instrument0 GroundStation21)
	(calibration_target instrument0 Star43)
	(calibration_target instrument0 Star31)
	(calibration_target instrument0 Star12)
	(calibration_target instrument0 Star13)
	(calibration_target instrument0 Star37)
	(supports instrument1 infrared3)
	(supports instrument1 infrared1)
	(supports instrument1 image0)
	(calibration_target instrument1 Star8)
	(calibration_target instrument1 Star31)
	(calibration_target instrument1 Star39)
	(calibration_target instrument1 Star49)
	(calibration_target instrument1 GroundStation47)
	(calibration_target instrument1 GroundStation28)
	(calibration_target instrument1 GroundStation7)
	(calibration_target instrument1 GroundStation5)
	(calibration_target instrument1 Star43)
	(calibration_target instrument1 GroundStation22)
	(calibration_target instrument1 Star0)
	(calibration_target instrument1 GroundStation32)
	(calibration_target instrument1 GroundStation36)
	(calibration_target instrument1 Star16)
	(calibration_target instrument1 GroundStation17)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Phenomenon67)
	(supports instrument2 infrared4)
	(calibration_target instrument2 Star46)
	(calibration_target instrument2 Star26)
	(calibration_target instrument2 Star38)
	(calibration_target instrument2 Star10)
	(calibration_target instrument2 GroundStation21)
	(calibration_target instrument2 GroundStation36)
	(calibration_target instrument2 Star49)
	(calibration_target instrument2 Star39)
	(calibration_target instrument2 Star20)
	(calibration_target instrument2 Star23)
	(calibration_target instrument2 Star35)
	(calibration_target instrument2 Star2)
	(calibration_target instrument2 GroundStation7)
	(calibration_target instrument2 Star45)
	(calibration_target instrument2 Star24)
	(on_board instrument2 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Planet65)
	(supports instrument3 infrared3)
	(supports instrument3 infrared1)
	(supports instrument3 thermograph2)
	(calibration_target instrument3 GroundStation47)
	(calibration_target instrument3 Star38)
	(supports instrument4 infrared3)
	(supports instrument4 infrared4)
	(calibration_target instrument4 GroundStation44)
	(calibration_target instrument4 GroundStation48)
	(calibration_target instrument4 GroundStation29)
	(calibration_target instrument4 Star25)
	(calibration_target instrument4 Star35)
	(calibration_target instrument4 GroundStation15)
	(calibration_target instrument4 Star40)
	(calibration_target instrument4 Star42)
	(calibration_target instrument4 GroundStation6)
	(calibration_target instrument4 Star43)
	(calibration_target instrument4 Star14)
	(calibration_target instrument4 Star26)
	(calibration_target instrument4 GroundStation34)
	(calibration_target instrument4 Star37)
	(supports instrument5 infrared4)
	(supports instrument5 image0)
	(calibration_target instrument5 Star3)
	(calibration_target instrument5 Star24)
	(calibration_target instrument5 GroundStation48)
	(calibration_target instrument5 Star26)
	(calibration_target instrument5 Star49)
	(calibration_target instrument5 Star41)
	(calibration_target instrument5 GroundStation11)
	(calibration_target instrument5 Star38)
	(calibration_target instrument5 Star14)
	(calibration_target instrument5 Star12)
	(calibration_target instrument5 GroundStation36)
	(calibration_target instrument5 GroundStation4)
	(calibration_target instrument5 Star45)
	(supports instrument6 image0)
	(supports instrument6 thermograph2)
	(calibration_target instrument6 Star20)
	(calibration_target instrument6 GroundStation27)
	(calibration_target instrument6 Star1)
	(calibration_target instrument6 Star23)
	(calibration_target instrument6 Star38)
	(calibration_target instrument6 Star40)
	(calibration_target instrument6 GroundStation15)
	(calibration_target instrument6 Star26)
	(calibration_target instrument6 GroundStation28)
	(calibration_target instrument6 Star39)
	(on_board instrument3 satellite2)
	(on_board instrument4 satellite2)
	(on_board instrument5 satellite2)
	(on_board instrument6 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star75)
	(supports instrument7 thermograph2)
	(calibration_target instrument7 GroundStation48)
	(calibration_target instrument7 Star19)
	(calibration_target instrument7 GroundStation15)
	(calibration_target instrument7 Star24)
	(calibration_target instrument7 GroundStation47)
	(calibration_target instrument7 Star14)
	(calibration_target instrument7 Star10)
	(calibration_target instrument7 Star30)
	(calibration_target instrument7 GroundStation4)
	(calibration_target instrument7 GroundStation11)
	(calibration_target instrument7 GroundStation34)
	(calibration_target instrument7 Star3)
	(calibration_target instrument7 GroundStation44)
	(supports instrument8 infrared3)
	(calibration_target instrument8 Star3)
	(calibration_target instrument8 GroundStation32)
	(supports instrument9 thermograph2)
	(supports instrument9 infrared1)
	(supports instrument9 infrared3)
	(calibration_target instrument9 GroundStation7)
	(calibration_target instrument9 GroundStation6)
	(calibration_target instrument9 GroundStation27)
	(calibration_target instrument9 Star1)
	(calibration_target instrument9 GroundStation17)
	(calibration_target instrument9 Star46)
	(calibration_target instrument9 Star26)
	(calibration_target instrument9 Star45)
	(calibration_target instrument9 Star40)
	(calibration_target instrument9 GroundStation18)
	(calibration_target instrument9 Star10)
	(calibration_target instrument9 Star49)
	(calibration_target instrument9 Star43)
	(calibration_target instrument9 GroundStation22)
	(calibration_target instrument9 Star30)
	(calibration_target instrument9 Star25)
	(on_board instrument7 satellite3)
	(on_board instrument8 satellite3)
	(on_board instrument9 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star39)
	(supports instrument10 infrared1)
	(calibration_target instrument10 Star40)
	(calibration_target instrument10 GroundStation5)
	(calibration_target instrument10 Star41)
	(supports instrument11 thermograph2)
	(supports instrument11 infrared4)
	(supports instrument11 infrared1)
	(calibration_target instrument11 GroundStation29)
	(calibration_target instrument11 Star24)
	(on_board instrument10 satellite4)
	(on_board instrument11 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Planet64)
)
(:goal (and
	(pointing satellite1 GroundStation48)
	(have_image Planet50 thermograph2)
	(have_image Star51 infrared1)
	(have_image Phenomenon52 infrared1)
	(have_image Planet53 infrared3)
	(have_image Phenomenon54 thermograph2)
	(have_image Phenomenon55 thermograph2)
	(have_image Planet56 image0)
	(have_image Star57 thermograph2)
	(have_image Phenomenon58 infrared4)
	(have_image Planet59 infrared1)
	(have_image Star60 image0)
	(have_image Planet61 infrared1)
	(have_image Star62 infrared1)
	(have_image Phenomenon63 image0)
	(have_image Planet64 infrared4)
	(have_image Planet65 thermograph2)
	(have_image Star66 infrared4)
	(have_image Phenomenon67 image0)
	(have_image Phenomenon68 thermograph2)
	(have_image Phenomenon69 infrared4)
	(have_image Planet70 infrared3)
	(have_image Phenomenon71 infrared3)
	(have_image Phenomenon72 infrared4)
	(have_image Phenomenon73 infrared3)
	(have_image Phenomenon74 image0)
	(have_image Star75 infrared4)
	(have_image Phenomenon76 infrared3)
	(have_image Planet77 thermograph2)
	(have_image Planet78 infrared4)
	(have_image Phenomenon79 infrared4)
	(have_image Planet80 image0)
	(have_image Planet81 infrared1)
	(have_image Planet82 infrared1)
	(have_image Planet83 infrared3)
	(have_image Planet84 infrared4)
))

)
