(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	satellite1 - satellite
	instrument2 - instrument
	instrument3 - instrument
	satellite2 - satellite
	instrument4 - instrument
	satellite3 - satellite
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	satellite4 - satellite
	instrument8 - instrument
	image3 - mode
	infrared2 - mode
	spectrograph1 - mode
	infrared0 - mode
	thermograph4 - mode
	Star0 - direction
	GroundStation1 - direction
	GroundStation2 - direction
	Star9 - direction
	Star21 - direction
	GroundStation22 - direction
	GroundStation23 - direction
	GroundStation29 - direction
	GroundStation46 - direction
	GroundStation6 - direction
	Star41 - direction
	Star8 - direction
	Star45 - direction
	Star11 - direction
	Star10 - direction
	GroundStation39 - direction
	GroundStation36 - direction
	GroundStation13 - direction
	GroundStation18 - direction
	GroundStation20 - direction
	GroundStation25 - direction
	GroundStation7 - direction
	Star42 - direction
	GroundStation26 - direction
	Star24 - direction
	GroundStation47 - direction
	Star35 - direction
	GroundStation19 - direction
	GroundStation33 - direction
	Star43 - direction
	Star38 - direction
	GroundStation15 - direction
	GroundStation5 - direction
	Star34 - direction
	GroundStation49 - direction
	GroundStation44 - direction
	GroundStation12 - direction
	GroundStation27 - direction
	GroundStation37 - direction
	GroundStation17 - direction
	GroundStation31 - direction
	Star4 - direction
	GroundStation30 - direction
	Star16 - direction
	Star40 - direction
	Star3 - direction
	Star48 - direction
	Star32 - direction
	GroundStation14 - direction
	GroundStation28 - direction
	Phenomenon50 - direction
	Planet51 - direction
	Planet52 - direction
	Planet53 - direction
	Phenomenon54 - direction
	Planet55 - direction
	Phenomenon56 - direction
	Star57 - direction
	Planet58 - direction
	Star59 - direction
	Planet60 - direction
	Phenomenon61 - direction
	Phenomenon62 - direction
	Planet63 - direction
	Planet64 - direction
	Star65 - direction
	Star66 - direction
	Phenomenon67 - direction
	Star68 - direction
	Planet69 - direction
	Planet70 - direction
	Planet71 - direction
	Planet72 - direction
	Phenomenon73 - direction
	Planet74 - direction
	Star75 - direction
	Phenomenon76 - direction
	Planet77 - direction
	Phenomenon78 - direction
	Phenomenon79 - direction
	Planet80 - direction
	Phenomenon81 - direction
	Phenomenon82 - direction
	Star83 - direction
	Phenomenon84 - direction
)
(:init
	(supports instrument0 spectrograph1)
	(supports instrument0 image3)
	(calibration_target instrument0 Star45)
	(calibration_target instrument0 GroundStation47)
	(calibration_target instrument0 GroundStation19)
	(calibration_target instrument0 Star8)
	(calibration_target instrument0 Star16)
	(calibration_target instrument0 GroundStation14)
	(calibration_target instrument0 GroundStation18)
	(calibration_target instrument0 Star42)
	(calibration_target instrument0 GroundStation49)
	(calibration_target instrument0 Star41)
	(calibration_target instrument0 GroundStation6)
	(calibration_target instrument0 Star43)
	(calibration_target instrument0 Star24)
	(calibration_target instrument0 Star35)
	(calibration_target instrument0 GroundStation15)
	(calibration_target instrument0 Star10)
	(supports instrument1 image3)
	(supports instrument1 thermograph4)
	(supports instrument1 infrared2)
	(calibration_target instrument1 Star8)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Phenomenon73)
	(supports instrument2 spectrograph1)
	(supports instrument2 infrared0)
	(calibration_target instrument2 Star3)
	(calibration_target instrument2 Star10)
	(calibration_target instrument2 GroundStation14)
	(calibration_target instrument2 Star11)
	(calibration_target instrument2 Star45)
	(calibration_target instrument2 Star43)
	(calibration_target instrument2 GroundStation20)
	(supports instrument3 infrared0)
	(calibration_target instrument3 GroundStation28)
	(calibration_target instrument3 GroundStation15)
	(calibration_target instrument3 GroundStation30)
	(calibration_target instrument3 GroundStation31)
	(calibration_target instrument3 GroundStation36)
	(calibration_target instrument3 GroundStation39)
	(calibration_target instrument3 GroundStation26)
	(on_board instrument2 satellite1)
	(on_board instrument3 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation49)
	(supports instrument4 image3)
	(calibration_target instrument4 Star42)
	(calibration_target instrument4 GroundStation7)
	(calibration_target instrument4 GroundStation28)
	(calibration_target instrument4 GroundStation26)
	(calibration_target instrument4 GroundStation37)
	(calibration_target instrument4 GroundStation19)
	(calibration_target instrument4 GroundStation25)
	(calibration_target instrument4 GroundStation20)
	(calibration_target instrument4 GroundStation27)
	(calibration_target instrument4 GroundStation18)
	(calibration_target instrument4 GroundStation5)
	(calibration_target instrument4 Star43)
	(calibration_target instrument4 GroundStation13)
	(calibration_target instrument4 GroundStation44)
	(calibration_target instrument4 Star48)
	(on_board instrument4 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star65)
	(supports instrument5 thermograph4)
	(supports instrument5 image3)
	(calibration_target instrument5 GroundStation47)
	(calibration_target instrument5 GroundStation44)
	(calibration_target instrument5 Star24)
	(calibration_target instrument5 GroundStation26)
	(supports instrument6 thermograph4)
	(calibration_target instrument6 Star38)
	(calibration_target instrument6 GroundStation12)
	(calibration_target instrument6 Star43)
	(calibration_target instrument6 GroundStation33)
	(calibration_target instrument6 GroundStation19)
	(calibration_target instrument6 Star32)
	(calibration_target instrument6 Star16)
	(calibration_target instrument6 GroundStation31)
	(calibration_target instrument6 Star35)
	(supports instrument7 infrared2)
	(calibration_target instrument7 Star16)
	(calibration_target instrument7 GroundStation30)
	(calibration_target instrument7 Star32)
	(calibration_target instrument7 Star4)
	(calibration_target instrument7 Star3)
	(calibration_target instrument7 GroundStation31)
	(calibration_target instrument7 GroundStation17)
	(calibration_target instrument7 GroundStation37)
	(calibration_target instrument7 GroundStation28)
	(calibration_target instrument7 GroundStation27)
	(calibration_target instrument7 GroundStation12)
	(calibration_target instrument7 GroundStation44)
	(calibration_target instrument7 GroundStation49)
	(calibration_target instrument7 Star34)
	(calibration_target instrument7 GroundStation5)
	(calibration_target instrument7 GroundStation15)
	(on_board instrument5 satellite3)
	(on_board instrument6 satellite3)
	(on_board instrument7 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation6)
	(supports instrument8 image3)
	(supports instrument8 spectrograph1)
	(calibration_target instrument8 GroundStation28)
	(calibration_target instrument8 GroundStation14)
	(calibration_target instrument8 Star32)
	(calibration_target instrument8 Star48)
	(calibration_target instrument8 Star3)
	(calibration_target instrument8 Star40)
	(on_board instrument8 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Phenomenon81)
)
(:goal (and
	(pointing satellite0 Star35)
	(pointing satellite1 GroundStation47)
	(pointing satellite3 GroundStation1)
	(have_image Phenomenon50 thermograph4)
	(have_image Planet51 spectrograph1)
	(have_image Planet52 thermograph4)
	(have_image Planet53 image3)
	(have_image Phenomenon54 infrared2)
	(have_image Planet55 infrared0)
	(have_image Phenomenon56 infrared0)
	(have_image Star57 image3)
	(have_image Planet58 infrared0)
	(have_image Star59 image3)
	(have_image Planet60 spectrograph1)
	(have_image Phenomenon61 infrared0)
	(have_image Phenomenon62 infrared2)
	(have_image Planet63 thermograph4)
	(have_image Planet64 infrared2)
	(have_image Star65 spectrograph1)
	(have_image Star66 image3)
	(have_image Phenomenon67 image3)
	(have_image Star68 image3)
	(have_image Planet69 image3)
	(have_image Planet70 infrared2)
	(have_image Planet71 image3)
	(have_image Planet72 infrared2)
	(have_image Phenomenon73 infrared0)
	(have_image Planet74 spectrograph1)
	(have_image Star75 infrared0)
	(have_image Phenomenon76 thermograph4)
	(have_image Planet77 image3)
	(have_image Phenomenon78 infrared0)
	(have_image Phenomenon79 infrared0)
	(have_image Planet80 spectrograph1)
	(have_image Phenomenon81 thermograph4)
	(have_image Phenomenon82 infrared2)
	(have_image Star83 infrared0)
	(have_image Phenomenon84 thermograph4)
))

)
