(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	satellite1 - satellite
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	satellite2 - satellite
	instrument6 - instrument
	satellite3 - satellite
	instrument7 - instrument
	instrument8 - instrument
	satellite4 - satellite
	instrument9 - instrument
	image3 - mode
	infrared4 - mode
	thermograph0 - mode
	infrared2 - mode
	infrared1 - mode
	Star9 - direction
	Star10 - direction
	GroundStation13 - direction
	Star15 - direction
	Star16 - direction
	Star36 - direction
	Star42 - direction
	GroundStation45 - direction
	Star46 - direction
	GroundStation49 - direction
	Star30 - direction
	GroundStation4 - direction
	GroundStation44 - direction
	GroundStation18 - direction
	Star24 - direction
	GroundStation20 - direction
	GroundStation39 - direction
	GroundStation32 - direction
	GroundStation48 - direction
	GroundStation11 - direction
	Star23 - direction
	Star33 - direction
	Star25 - direction
	Star37 - direction
	Star12 - direction
	Star1 - direction
	Star38 - direction
	GroundStation7 - direction
	GroundStation26 - direction
	GroundStation35 - direction
	Star28 - direction
	GroundStation34 - direction
	Star40 - direction
	GroundStation8 - direction
	GroundStation47 - direction
	Star14 - direction
	Star3 - direction
	Star22 - direction
	Star0 - direction
	Star41 - direction
	GroundStation31 - direction
	GroundStation2 - direction
	Star5 - direction
	GroundStation17 - direction
	Star21 - direction
	GroundStation27 - direction
	Star43 - direction
	Star6 - direction
	Star19 - direction
	Star29 - direction
	Star50 - direction
	Phenomenon51 - direction
	Star52 - direction
	Phenomenon53 - direction
	Planet54 - direction
	Phenomenon55 - direction
	Star56 - direction
	Phenomenon57 - direction
	Star58 - direction
	Star59 - direction
	Planet60 - direction
	Star61 - direction
	Phenomenon62 - direction
	Phenomenon63 - direction
	Planet64 - direction
	Phenomenon65 - direction
	Star66 - direction
	Star67 - direction
	Star68 - direction
	Star69 - direction
	Phenomenon70 - direction
	Star71 - direction
	Planet72 - direction
	Planet73 - direction
	Phenomenon74 - direction
	Star75 - direction
	Star76 - direction
	Star77 - direction
	Phenomenon78 - direction
	Phenomenon79 - direction
	Planet80 - direction
	Planet81 - direction
	Phenomenon82 - direction
	Planet83 - direction
	Planet84 - direction
)
(:init
	(supports instrument0 infrared2)
	(supports instrument0 infrared1)
	(supports instrument0 infrared4)
	(calibration_target instrument0 Star30)
	(calibration_target instrument0 GroundStation47)
	(calibration_target instrument0 GroundStation27)
	(calibration_target instrument0 GroundStation39)
	(supports instrument1 infrared4)
	(supports instrument1 thermograph0)
	(calibration_target instrument1 GroundStation44)
	(calibration_target instrument1 GroundStation20)
	(calibration_target instrument1 GroundStation17)
	(calibration_target instrument1 Star0)
	(calibration_target instrument1 GroundStation26)
	(calibration_target instrument1 Star24)
	(calibration_target instrument1 GroundStation4)
	(supports instrument2 infrared2)
	(calibration_target instrument2 GroundStation39)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star0)
	(supports instrument3 infrared1)
	(supports instrument3 image3)
	(supports instrument3 thermograph0)
	(calibration_target instrument3 GroundStation17)
	(calibration_target instrument3 Star29)
	(calibration_target instrument3 GroundStation39)
	(calibration_target instrument3 Star0)
	(calibration_target instrument3 GroundStation20)
	(calibration_target instrument3 Star25)
	(calibration_target instrument3 GroundStation2)
	(calibration_target instrument3 Star40)
	(calibration_target instrument3 Star24)
	(calibration_target instrument3 Star1)
	(calibration_target instrument3 GroundStation18)
	(supports instrument4 infrared1)
	(supports instrument4 infrared2)
	(supports instrument4 thermograph0)
	(calibration_target instrument4 Star43)
	(calibration_target instrument4 Star37)
	(calibration_target instrument4 Star25)
	(calibration_target instrument4 Star12)
	(calibration_target instrument4 Star33)
	(calibration_target instrument4 Star23)
	(calibration_target instrument4 GroundStation11)
	(calibration_target instrument4 GroundStation31)
	(calibration_target instrument4 Star21)
	(calibration_target instrument4 GroundStation47)
	(calibration_target instrument4 GroundStation34)
	(calibration_target instrument4 Star29)
	(calibration_target instrument4 GroundStation48)
	(calibration_target instrument4 GroundStation32)
	(supports instrument5 thermograph0)
	(supports instrument5 infrared4)
	(supports instrument5 infrared2)
	(calibration_target instrument5 GroundStation8)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star75)
	(supports instrument6 image3)
	(supports instrument6 infrared4)
	(supports instrument6 infrared1)
	(calibration_target instrument6 Star12)
	(on_board instrument6 satellite2)
	(power_avail satellite2)
	(pointing satellite2 GroundStation27)
	(supports instrument7 thermograph0)
	(calibration_target instrument7 Star14)
	(calibration_target instrument7 GroundStation47)
	(calibration_target instrument7 GroundStation8)
	(calibration_target instrument7 Star40)
	(calibration_target instrument7 GroundStation34)
	(calibration_target instrument7 Star6)
	(calibration_target instrument7 Star28)
	(calibration_target instrument7 GroundStation35)
	(calibration_target instrument7 GroundStation26)
	(calibration_target instrument7 GroundStation7)
	(calibration_target instrument7 Star5)
	(calibration_target instrument7 Star38)
	(calibration_target instrument7 Star1)
	(supports instrument8 image3)
	(calibration_target instrument8 GroundStation2)
	(calibration_target instrument8 GroundStation17)
	(calibration_target instrument8 GroundStation31)
	(calibration_target instrument8 Star41)
	(calibration_target instrument8 Star0)
	(calibration_target instrument8 Star22)
	(calibration_target instrument8 Star3)
	(on_board instrument7 satellite3)
	(on_board instrument8 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Phenomenon74)
	(supports instrument9 infrared2)
	(calibration_target instrument9 Star29)
	(calibration_target instrument9 Star19)
	(calibration_target instrument9 Star6)
	(calibration_target instrument9 Star43)
	(calibration_target instrument9 GroundStation27)
	(calibration_target instrument9 Star21)
	(calibration_target instrument9 GroundStation17)
	(calibration_target instrument9 Star5)
	(on_board instrument9 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star67)
)
(:goal (and
	(pointing satellite4 Star37)
	(have_image Star50 infrared2)
	(have_image Phenomenon51 infrared4)
	(have_image Star52 infrared2)
	(have_image Phenomenon53 infrared4)
	(have_image Planet54 infrared1)
	(have_image Phenomenon55 image3)
	(have_image Star56 infrared2)
	(have_image Phenomenon57 infrared4)
	(have_image Star58 image3)
	(have_image Star59 image3)
	(have_image Planet60 infrared4)
	(have_image Star61 image3)
	(have_image Phenomenon62 infrared2)
	(have_image Phenomenon63 image3)
	(have_image Planet64 image3)
	(have_image Phenomenon65 image3)
	(have_image Star66 infrared2)
	(have_image Star67 thermograph0)
	(have_image Star68 infrared4)
	(have_image Star69 thermograph0)
	(have_image Phenomenon70 thermograph0)
	(have_image Star71 image3)
	(have_image Planet72 image3)
	(have_image Planet73 infrared2)
	(have_image Phenomenon74 image3)
	(have_image Star75 infrared2)
	(have_image Star76 thermograph0)
	(have_image Star77 image3)
	(have_image Phenomenon78 infrared4)
	(have_image Phenomenon79 infrared4)
	(have_image Planet80 infrared4)
	(have_image Planet81 infrared2)
	(have_image Phenomenon82 infrared2)
	(have_image Planet83 infrared1)
	(have_image Planet84 image3)
))

)
