(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	satellite1 - satellite
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	satellite2 - satellite
	instrument7 - instrument
	instrument8 - instrument
	satellite3 - satellite
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	satellite4 - satellite
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	image0 - mode
	thermograph4 - mode
	thermograph1 - mode
	infrared3 - mode
	thermograph2 - mode
	Star9 - direction
	Star19 - direction
	GroundStation44 - direction
	Star28 - direction
	Star0 - direction
	GroundStation3 - direction
	GroundStation34 - direction
	Star2 - direction
	GroundStation24 - direction
	Star15 - direction
	GroundStation32 - direction
	Star35 - direction
	GroundStation18 - direction
	Star5 - direction
	Star8 - direction
	Star37 - direction
	Star40 - direction
	Star14 - direction
	Star33 - direction
	GroundStation39 - direction
	GroundStation48 - direction
	Star10 - direction
	Star41 - direction
	Star43 - direction
	GroundStation16 - direction
	GroundStation6 - direction
	Star26 - direction
	Star23 - direction
	GroundStation11 - direction
	Star30 - direction
	Star31 - direction
	GroundStation4 - direction
	GroundStation1 - direction
	Star38 - direction
	Star13 - direction
	GroundStation49 - direction
	GroundStation17 - direction
	GroundStation7 - direction
	GroundStation45 - direction
	Star36 - direction
	Star46 - direction
	Star20 - direction
	Star12 - direction
	GroundStation25 - direction
	GroundStation29 - direction
	Star27 - direction
	Star42 - direction
	Star22 - direction
	GroundStation47 - direction
	Star21 - direction
	Planet50 - direction
	Star51 - direction
	Star52 - direction
	Phenomenon53 - direction
	Phenomenon54 - direction
	Planet55 - direction
	Star56 - direction
	Star57 - direction
	Planet58 - direction
	Phenomenon59 - direction
	Planet60 - direction
	Phenomenon61 - direction
	Phenomenon62 - direction
	Phenomenon63 - direction
	Phenomenon64 - direction
	Phenomenon65 - direction
	Planet66 - direction
	Planet67 - direction
	Star68 - direction
	Phenomenon69 - direction
	Planet70 - direction
	Star71 - direction
	Planet72 - direction
	Phenomenon73 - direction
	Planet74 - direction
	Star75 - direction
	Planet76 - direction
	Planet77 - direction
	Planet78 - direction
	Planet79 - direction
	Planet80 - direction
	Planet81 - direction
	Planet82 - direction
	Phenomenon83 - direction
	Phenomenon84 - direction
)
(:init
	(supports instrument0 thermograph1)
	(supports instrument0 image0)
	(supports instrument0 thermograph2)
	(calibration_target instrument0 Star26)
	(calibration_target instrument0 Star20)
	(calibration_target instrument0 Star30)
	(calibration_target instrument0 Star12)
	(calibration_target instrument0 GroundStation49)
	(calibration_target instrument0 Star5)
	(calibration_target instrument0 Star14)
	(supports instrument1 thermograph1)
	(calibration_target instrument1 GroundStation11)
	(calibration_target instrument1 Star20)
	(calibration_target instrument1 Star14)
	(calibration_target instrument1 Star40)
	(calibration_target instrument1 GroundStation32)
	(calibration_target instrument1 GroundStation29)
	(calibration_target instrument1 Star5)
	(calibration_target instrument1 Star28)
	(calibration_target instrument1 GroundStation7)
	(supports instrument2 image0)
	(calibration_target instrument2 GroundStation24)
	(calibration_target instrument2 Star2)
	(calibration_target instrument2 Star35)
	(calibration_target instrument2 GroundStation34)
	(calibration_target instrument2 Star14)
	(calibration_target instrument2 GroundStation3)
	(calibration_target instrument2 Star41)
	(calibration_target instrument2 GroundStation4)
	(calibration_target instrument2 Star0)
	(calibration_target instrument2 Star10)
	(calibration_target instrument2 Star21)
	(calibration_target instrument2 GroundStation11)
	(calibration_target instrument2 Star20)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation25)
	(supports instrument3 thermograph4)
	(calibration_target instrument3 Star31)
	(calibration_target instrument3 GroundStation32)
	(calibration_target instrument3 Star2)
	(calibration_target instrument3 Star33)
	(calibration_target instrument3 Star21)
	(calibration_target instrument3 Star22)
	(calibration_target instrument3 Star36)
	(calibration_target instrument3 Star10)
	(calibration_target instrument3 GroundStation18)
	(calibration_target instrument3 GroundStation4)
	(calibration_target instrument3 Star37)
	(calibration_target instrument3 Star8)
	(calibration_target instrument3 Star14)
	(calibration_target instrument3 GroundStation24)
	(calibration_target instrument3 GroundStation29)
	(supports instrument4 infrared3)
	(calibration_target instrument4 Star23)
	(calibration_target instrument4 GroundStation7)
	(calibration_target instrument4 GroundStation6)
	(calibration_target instrument4 GroundStation49)
	(supports instrument5 thermograph4)
	(calibration_target instrument5 GroundStation17)
	(calibration_target instrument5 Star26)
	(calibration_target instrument5 Star15)
	(calibration_target instrument5 Star40)
	(calibration_target instrument5 Star22)
	(calibration_target instrument5 Star43)
	(calibration_target instrument5 Star46)
	(calibration_target instrument5 Star38)
	(calibration_target instrument5 GroundStation24)
	(supports instrument6 thermograph2)
	(supports instrument6 infrared3)
	(supports instrument6 image0)
	(calibration_target instrument6 Star15)
	(calibration_target instrument6 GroundStation39)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation1)
	(supports instrument7 thermograph4)
	(supports instrument7 infrared3)
	(calibration_target instrument7 GroundStation4)
	(calibration_target instrument7 GroundStation45)
	(calibration_target instrument7 GroundStation16)
	(calibration_target instrument7 Star35)
	(calibration_target instrument7 GroundStation25)
	(calibration_target instrument7 Star22)
	(calibration_target instrument7 GroundStation49)
	(calibration_target instrument7 Star5)
	(calibration_target instrument7 Star36)
	(calibration_target instrument7 Star37)
	(calibration_target instrument7 GroundStation32)
	(calibration_target instrument7 GroundStation29)
	(calibration_target instrument7 Star10)
	(calibration_target instrument7 GroundStation48)
	(calibration_target instrument7 Star43)
	(supports instrument8 thermograph2)
	(calibration_target instrument8 Star8)
	(calibration_target instrument8 Star5)
	(calibration_target instrument8 GroundStation18)
	(calibration_target instrument8 GroundStation11)
	(calibration_target instrument8 Star38)
	(on_board instrument7 satellite2)
	(on_board instrument8 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star51)
	(supports instrument9 thermograph2)
	(supports instrument9 infrared3)
	(calibration_target instrument9 Star13)
	(calibration_target instrument9 Star14)
	(calibration_target instrument9 Star22)
	(calibration_target instrument9 Star40)
	(calibration_target instrument9 Star37)
	(calibration_target instrument9 Star43)
	(supports instrument10 infrared3)
	(calibration_target instrument10 Star43)
	(calibration_target instrument10 Star26)
	(calibration_target instrument10 Star46)
	(calibration_target instrument10 Star20)
	(calibration_target instrument10 GroundStation11)
	(calibration_target instrument10 GroundStation47)
	(calibration_target instrument10 GroundStation45)
	(supports instrument11 image0)
	(supports instrument11 thermograph1)
	(supports instrument11 thermograph4)
	(calibration_target instrument11 GroundStation16)
	(supports instrument12 infrared3)
	(supports instrument12 image0)
	(calibration_target instrument12 Star42)
	(calibration_target instrument12 Star31)
	(calibration_target instrument12 Star36)
	(calibration_target instrument12 GroundStation6)
	(calibration_target instrument12 GroundStation16)
	(calibration_target instrument12 Star43)
	(calibration_target instrument12 Star41)
	(calibration_target instrument12 Star10)
	(calibration_target instrument12 GroundStation48)
	(calibration_target instrument12 GroundStation39)
	(calibration_target instrument12 Star33)
	(on_board instrument9 satellite3)
	(on_board instrument10 satellite3)
	(on_board instrument11 satellite3)
	(on_board instrument12 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Phenomenon69)
	(supports instrument13 thermograph2)
	(calibration_target instrument13 Star38)
	(calibration_target instrument13 GroundStation45)
	(calibration_target instrument13 GroundStation1)
	(calibration_target instrument13 GroundStation4)
	(calibration_target instrument13 Star13)
	(calibration_target instrument13 Star21)
	(calibration_target instrument13 Star31)
	(calibration_target instrument13 Star30)
	(calibration_target instrument13 GroundStation11)
	(calibration_target instrument13 Star23)
	(calibration_target instrument13 Star26)
	(supports instrument14 infrared3)
	(supports instrument14 image0)
	(supports instrument14 thermograph4)
	(calibration_target instrument14 GroundStation7)
	(calibration_target instrument14 GroundStation17)
	(calibration_target instrument14 GroundStation49)
	(calibration_target instrument14 Star13)
	(supports instrument15 thermograph1)
	(supports instrument15 thermograph2)
	(calibration_target instrument15 Star21)
	(calibration_target instrument15 GroundStation47)
	(calibration_target instrument15 Star22)
	(calibration_target instrument15 Star42)
	(calibration_target instrument15 Star27)
	(calibration_target instrument15 GroundStation29)
	(calibration_target instrument15 GroundStation25)
	(calibration_target instrument15 Star12)
	(calibration_target instrument15 Star20)
	(calibration_target instrument15 Star46)
	(calibration_target instrument15 Star36)
	(calibration_target instrument15 GroundStation45)
	(on_board instrument13 satellite4)
	(on_board instrument14 satellite4)
	(on_board instrument15 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Phenomenon63)
)
(:goal (and
	(pointing satellite0 GroundStation32)
	(pointing satellite2 Star5)
	(pointing satellite4 Phenomenon62)
	(have_image Planet50 thermograph4)
	(have_image Star51 thermograph2)
	(have_image Star52 thermograph2)
	(have_image Phenomenon53 thermograph2)
	(have_image Phenomenon54 thermograph1)
	(have_image Planet55 image0)
	(have_image Star56 image0)
	(have_image Star57 thermograph2)
	(have_image Planet58 thermograph2)
	(have_image Phenomenon59 thermograph4)
	(have_image Planet60 thermograph2)
	(have_image Phenomenon61 thermograph1)
	(have_image Phenomenon62 thermograph4)
	(have_image Phenomenon63 thermograph1)
	(have_image Phenomenon64 infrared3)
	(have_image Phenomenon65 image0)
	(have_image Planet66 image0)
	(have_image Planet67 thermograph1)
	(have_image Star68 infrared3)
	(have_image Phenomenon69 image0)
	(have_image Planet70 infrared3)
	(have_image Star71 image0)
	(have_image Planet72 thermograph2)
	(have_image Phenomenon73 image0)
	(have_image Planet74 thermograph1)
	(have_image Star75 thermograph2)
	(have_image Planet76 image0)
	(have_image Planet77 thermograph4)
	(have_image Planet78 thermograph4)
	(have_image Planet79 thermograph1)
	(have_image Planet80 thermograph4)
	(have_image Planet81 thermograph2)
	(have_image Planet82 thermograph4)
	(have_image Phenomenon83 image0)
	(have_image Phenomenon84 infrared3)
))

)
