(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	satellite1 - satellite
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	satellite2 - satellite
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	satellite3 - satellite
	instrument11 - instrument
	satellite4 - satellite
	instrument12 - instrument
	satellite5 - satellite
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	thermograph2 - mode
	infrared4 - mode
	image0 - mode
	infrared3 - mode
	infrared1 - mode
	Star24 - direction
	Star45 - direction
	Star23 - direction
	Star37 - direction
	Star19 - direction
	GroundStation33 - direction
	Star39 - direction
	Star9 - direction
	Star30 - direction
	GroundStation17 - direction
	Star3 - direction
	Star54 - direction
	Star13 - direction
	Star49 - direction
	GroundStation18 - direction
	GroundStation7 - direction
	Star43 - direction
	GroundStation6 - direction
	GroundStation29 - direction
	Star25 - direction
	GroundStation5 - direction
	GroundStation27 - direction
	Star1 - direction
	Star40 - direction
	GroundStation44 - direction
	Star41 - direction
	Star56 - direction
	Star0 - direction
	Star55 - direction
	GroundStation34 - direction
	Star42 - direction
	GroundStation48 - direction
	Star59 - direction
	GroundStation57 - direction
	GroundStation32 - direction
	Star8 - direction
	Star26 - direction
	Star38 - direction
	GroundStation15 - direction
	Star2 - direction
	Star58 - direction
	Star14 - direction
	Star46 - direction
	Star16 - direction
	GroundStation28 - direction
	GroundStation21 - direction
	Star35 - direction
	GroundStation36 - direction
	Star31 - direction
	GroundStation51 - direction
	Star12 - direction
	Star10 - direction
	GroundStation53 - direction
	GroundStation47 - direction
	GroundStation22 - direction
	GroundStation50 - direction
	Star20 - direction
	GroundStation11 - direction
	GroundStation52 - direction
	GroundStation4 - direction
	Phenomenon60 - direction
	Star61 - direction
	Star62 - direction
	Phenomenon63 - direction
	Planet64 - direction
	Star65 - direction
	Planet66 - direction
	Phenomenon67 - direction
	Phenomenon68 - direction
	Phenomenon69 - direction
	Phenomenon70 - direction
	Star71 - direction
	Star72 - direction
	Star73 - direction
	Star74 - direction
	Phenomenon75 - direction
	Planet76 - direction
	Star77 - direction
	Star78 - direction
	Phenomenon79 - direction
	Planet80 - direction
	Planet81 - direction
	Phenomenon82 - direction
	Planet83 - direction
	Planet84 - direction
	Planet85 - direction
	Star86 - direction
	Phenomenon87 - direction
	Star88 - direction
	Star89 - direction
	Phenomenon90 - direction
	Planet91 - direction
	Planet92 - direction
	Star93 - direction
	Star94 - direction
	Star95 - direction
	Planet96 - direction
	Star97 - direction
	Phenomenon98 - direction
	Phenomenon99 - direction
	Phenomenon100 - direction
	Phenomenon101 - direction
	Phenomenon102 - direction
	Star103 - direction
	Planet104 - direction
)
(:init
	(supports instrument0 thermograph2)
	(supports instrument0 infrared3)
	(calibration_target instrument0 GroundStation6)
	(calibration_target instrument0 GroundStation34)
	(calibration_target instrument0 GroundStation15)
	(calibration_target instrument0 Star58)
	(on_board instrument0 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation34)
	(supports instrument1 infrared4)
	(calibration_target instrument1 GroundStation53)
	(calibration_target instrument1 Star13)
	(calibration_target instrument1 Star56)
	(calibration_target instrument1 Star26)
	(calibration_target instrument1 Star46)
	(calibration_target instrument1 Star31)
	(calibration_target instrument1 Star49)
	(calibration_target instrument1 GroundStation44)
	(calibration_target instrument1 GroundStation32)
	(calibration_target instrument1 Star14)
	(calibration_target instrument1 GroundStation7)
	(calibration_target instrument1 GroundStation22)
	(calibration_target instrument1 GroundStation27)
	(calibration_target instrument1 GroundStation17)
	(calibration_target instrument1 Star58)
	(calibration_target instrument1 Star42)
	(calibration_target instrument1 Star12)
	(supports instrument2 infrared3)
	(calibration_target instrument2 Star9)
	(calibration_target instrument2 Star10)
	(calibration_target instrument2 Star0)
	(calibration_target instrument2 GroundStation36)
	(calibration_target instrument2 GroundStation28)
	(calibration_target instrument2 Star38)
	(calibration_target instrument2 GroundStation22)
	(calibration_target instrument2 GroundStation50)
	(calibration_target instrument2 GroundStation29)
	(calibration_target instrument2 Star45)
	(supports instrument3 infrared3)
	(supports instrument3 infrared4)
	(calibration_target instrument3 Star2)
	(supports instrument4 infrared1)
	(supports instrument4 image0)
	(supports instrument4 thermograph2)
	(calibration_target instrument4 Star19)
	(calibration_target instrument4 Star30)
	(calibration_target instrument4 GroundStation34)
	(calibration_target instrument4 GroundStation15)
	(calibration_target instrument4 GroundStation6)
	(calibration_target instrument4 Star38)
	(calibration_target instrument4 Star37)
	(calibration_target instrument4 Star3)
	(calibration_target instrument4 Star23)
	(calibration_target instrument4 Star56)
	(supports instrument5 image0)
	(supports instrument5 infrared3)
	(calibration_target instrument5 GroundStation22)
	(calibration_target instrument5 GroundStation4)
	(calibration_target instrument5 Star43)
	(calibration_target instrument5 GroundStation28)
	(calibration_target instrument5 Star8)
	(calibration_target instrument5 GroundStation57)
	(calibration_target instrument5 Star39)
	(calibration_target instrument5 GroundStation33)
	(calibration_target instrument5 Star26)
	(calibration_target instrument5 GroundStation36)
	(calibration_target instrument5 GroundStation29)
	(calibration_target instrument5 Star20)
	(on_board instrument1 satellite1)
	(on_board instrument2 satellite1)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation48)
	(supports instrument6 image0)
	(supports instrument6 infrared4)
	(supports instrument6 infrared1)
	(calibration_target instrument6 Star49)
	(calibration_target instrument6 Star2)
	(calibration_target instrument6 Star16)
	(calibration_target instrument6 GroundStation18)
	(calibration_target instrument6 GroundStation17)
	(calibration_target instrument6 Star30)
	(calibration_target instrument6 GroundStation47)
	(calibration_target instrument6 Star43)
	(calibration_target instrument6 GroundStation6)
	(calibration_target instrument6 Star42)
	(calibration_target instrument6 GroundStation34)
	(calibration_target instrument6 GroundStation44)
	(calibration_target instrument6 Star54)
	(calibration_target instrument6 Star8)
	(calibration_target instrument6 GroundStation29)
	(calibration_target instrument6 Star58)
	(calibration_target instrument6 Star9)
	(calibration_target instrument6 Star55)
	(supports instrument7 thermograph2)
	(calibration_target instrument7 Star42)
	(calibration_target instrument7 Star56)
	(calibration_target instrument7 Star12)
	(calibration_target instrument7 GroundStation32)
	(calibration_target instrument7 Star55)
	(calibration_target instrument7 GroundStation48)
	(calibration_target instrument7 Star25)
	(calibration_target instrument7 GroundStation11)
	(calibration_target instrument7 Star54)
	(calibration_target instrument7 Star10)
	(supports instrument8 infrared3)
	(supports instrument8 infrared4)
	(calibration_target instrument8 Star0)
	(calibration_target instrument8 Star43)
	(calibration_target instrument8 Star13)
	(calibration_target instrument8 Star54)
	(calibration_target instrument8 Star2)
	(calibration_target instrument8 Star38)
	(calibration_target instrument8 Star3)
	(supports instrument9 thermograph2)
	(supports instrument9 image0)
	(calibration_target instrument9 GroundStation6)
	(calibration_target instrument9 Star20)
	(calibration_target instrument9 Star43)
	(calibration_target instrument9 Star31)
	(calibration_target instrument9 GroundStation48)
	(calibration_target instrument9 GroundStation34)
	(calibration_target instrument9 GroundStation7)
	(calibration_target instrument9 GroundStation15)
	(calibration_target instrument9 GroundStation18)
	(calibration_target instrument9 GroundStation47)
	(calibration_target instrument9 GroundStation28)
	(calibration_target instrument9 GroundStation5)
	(calibration_target instrument9 Star2)
	(calibration_target instrument9 Star55)
	(calibration_target instrument9 Star49)
	(calibration_target instrument9 Star59)
	(calibration_target instrument9 GroundStation44)
	(calibration_target instrument9 GroundStation22)
	(calibration_target instrument9 Star58)
	(supports instrument10 image0)
	(calibration_target instrument10 Star38)
	(calibration_target instrument10 GroundStation5)
	(calibration_target instrument10 Star25)
	(calibration_target instrument10 GroundStation29)
	(calibration_target instrument10 GroundStation32)
	(calibration_target instrument10 Star59)
	(calibration_target instrument10 Star40)
	(calibration_target instrument10 GroundStation51)
	(calibration_target instrument10 Star26)
	(calibration_target instrument10 Star41)
	(calibration_target instrument10 GroundStation36)
	(calibration_target instrument10 Star2)
	(calibration_target instrument10 GroundStation22)
	(on_board instrument6 satellite2)
	(on_board instrument7 satellite2)
	(on_board instrument8 satellite2)
	(on_board instrument9 satellite2)
	(on_board instrument10 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Phenomenon70)
	(supports instrument11 infrared1)
	(supports instrument11 thermograph2)
	(calibration_target instrument11 GroundStation57)
	(calibration_target instrument11 GroundStation15)
	(calibration_target instrument11 Star12)
	(on_board instrument11 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star19)
	(supports instrument12 infrared4)
	(calibration_target instrument12 Star0)
	(calibration_target instrument12 Star56)
	(calibration_target instrument12 Star41)
	(calibration_target instrument12 GroundStation44)
	(calibration_target instrument12 Star40)
	(calibration_target instrument12 Star1)
	(calibration_target instrument12 GroundStation48)
	(calibration_target instrument12 Star35)
	(calibration_target instrument12 Star59)
	(calibration_target instrument12 Star42)
	(calibration_target instrument12 GroundStation27)
	(on_board instrument12 satellite4)
	(power_avail satellite4)
	(pointing satellite4 GroundStation11)
	(supports instrument13 infrared3)
	(calibration_target instrument13 GroundStation22)
	(calibration_target instrument13 Star59)
	(calibration_target instrument13 GroundStation48)
	(calibration_target instrument13 Star58)
	(calibration_target instrument13 Star42)
	(calibration_target instrument13 GroundStation34)
	(calibration_target instrument13 Star55)
	(calibration_target instrument13 GroundStation32)
	(supports instrument14 infrared3)
	(supports instrument14 infrared1)
	(supports instrument14 infrared4)
	(calibration_target instrument14 Star16)
	(calibration_target instrument14 GroundStation57)
	(calibration_target instrument14 GroundStation51)
	(calibration_target instrument14 Star58)
	(supports instrument15 thermograph2)
	(calibration_target instrument15 Star46)
	(calibration_target instrument15 GroundStation50)
	(calibration_target instrument15 Star14)
	(calibration_target instrument15 Star58)
	(calibration_target instrument15 Star12)
	(calibration_target instrument15 Star2)
	(calibration_target instrument15 GroundStation15)
	(calibration_target instrument15 Star38)
	(calibration_target instrument15 GroundStation53)
	(calibration_target instrument15 Star26)
	(calibration_target instrument15 Star10)
	(calibration_target instrument15 Star8)
	(calibration_target instrument15 GroundStation32)
	(supports instrument16 infrared4)
	(supports instrument16 thermograph2)
	(calibration_target instrument16 GroundStation53)
	(calibration_target instrument16 Star10)
	(calibration_target instrument16 GroundStation22)
	(calibration_target instrument16 Star12)
	(calibration_target instrument16 GroundStation51)
	(calibration_target instrument16 Star31)
	(calibration_target instrument16 GroundStation36)
	(calibration_target instrument16 Star20)
	(calibration_target instrument16 GroundStation52)
	(calibration_target instrument16 Star35)
	(calibration_target instrument16 GroundStation21)
	(calibration_target instrument16 GroundStation28)
	(calibration_target instrument16 Star16)
	(supports instrument17 infrared3)
	(supports instrument17 infrared4)
	(calibration_target instrument17 GroundStation4)
	(calibration_target instrument17 GroundStation52)
	(calibration_target instrument17 GroundStation11)
	(calibration_target instrument17 Star20)
	(calibration_target instrument17 GroundStation50)
	(calibration_target instrument17 GroundStation22)
	(calibration_target instrument17 GroundStation47)
	(on_board instrument13 satellite5)
	(on_board instrument14 satellite5)
	(on_board instrument15 satellite5)
	(on_board instrument16 satellite5)
	(on_board instrument17 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Phenomenon98)
)
(:goal (and
	(pointing satellite0 GroundStation36)
	(pointing satellite4 Star65)
	(pointing satellite5 GroundStation36)
	(have_image Phenomenon60 infrared4)
	(have_image Star61 infrared4)
	(have_image Star62 thermograph2)
	(have_image Phenomenon63 infrared3)
	(have_image Planet64 thermograph2)
	(have_image Star65 thermograph2)
	(have_image Planet66 thermograph2)
	(have_image Phenomenon67 thermograph2)
	(have_image Phenomenon68 infrared3)
	(have_image Phenomenon69 infrared4)
	(have_image Phenomenon70 infrared1)
	(have_image Star71 infrared4)
	(have_image Star72 infrared4)
	(have_image Star73 infrared1)
	(have_image Star74 thermograph2)
	(have_image Phenomenon75 image0)
	(have_image Planet76 infrared1)
	(have_image Star77 image0)
	(have_image Star78 infrared3)
	(have_image Phenomenon79 infrared1)
	(have_image Planet80 infrared3)
	(have_image Planet81 infrared4)
	(have_image Phenomenon82 thermograph2)
	(have_image Planet83 infrared1)
	(have_image Planet84 image0)
	(have_image Planet85 image0)
	(have_image Star86 infrared3)
	(have_image Phenomenon87 infrared1)
	(have_image Star88 thermograph2)
	(have_image Star89 image0)
	(have_image Phenomenon90 infrared3)
	(have_image Planet91 infrared3)
	(have_image Planet92 thermograph2)
	(have_image Star93 image0)
	(have_image Star94 thermograph2)
	(have_image Star95 thermograph2)
	(have_image Planet96 thermograph2)
	(have_image Star97 infrared3)
	(have_image Phenomenon98 infrared3)
	(have_image Phenomenon99 infrared3)
	(have_image Phenomenon100 infrared4)
	(have_image Phenomenon101 thermograph2)
	(have_image Phenomenon102 thermograph2)
	(have_image Star103 image0)
	(have_image Planet104 infrared3)
))

)
