(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	satellite1 - satellite
	instrument5 - instrument
	instrument6 - instrument
	satellite2 - satellite
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	satellite3 - satellite
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	satellite4 - satellite
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	satellite5 - satellite
	instrument19 - instrument
	infrared0 - mode
	spectrograph1 - mode
	image3 - mode
	thermograph4 - mode
	infrared2 - mode
	GroundStation12 - direction
	Star11 - direction
	GroundStation36 - direction
	Star54 - direction
	Star45 - direction
	GroundStation37 - direction
	GroundStation51 - direction
	GroundStation20 - direction
	Star32 - direction
	GroundStation19 - direction
	GroundStation26 - direction
	Star48 - direction
	Star8 - direction
	Star42 - direction
	GroundStation23 - direction
	GroundStation2 - direction
	GroundStation14 - direction
	Star9 - direction
	GroundStation31 - direction
	GroundStation46 - direction
	Star24 - direction
	GroundStation15 - direction
	GroundStation49 - direction
	GroundStation13 - direction
	Star43 - direction
	GroundStation6 - direction
	GroundStation59 - direction
	GroundStation39 - direction
	GroundStation57 - direction
	Star4 - direction
	Star38 - direction
	GroundStation22 - direction
	GroundStation27 - direction
	GroundStation29 - direction
	Star35 - direction
	GroundStation44 - direction
	GroundStation17 - direction
	GroundStation5 - direction
	GroundStation58 - direction
	Star34 - direction
	Star41 - direction
	GroundStation47 - direction
	Star52 - direction
	Star16 - direction
	GroundStation7 - direction
	GroundStation56 - direction
	Star50 - direction
	Star3 - direction
	GroundStation28 - direction
	Star21 - direction
	Star10 - direction
	GroundStation18 - direction
	GroundStation53 - direction
	GroundStation25 - direction
	Star0 - direction
	Star40 - direction
	Star55 - direction
	GroundStation30 - direction
	GroundStation33 - direction
	GroundStation1 - direction
	Phenomenon60 - direction
	Phenomenon61 - direction
	Star62 - direction
	Phenomenon63 - direction
	Star64 - direction
	Phenomenon65 - direction
	Star66 - direction
	Star67 - direction
	Planet68 - direction
	Planet69 - direction
	Planet70 - direction
	Planet71 - direction
	Planet72 - direction
	Star73 - direction
	Star74 - direction
	Planet75 - direction
	Planet76 - direction
	Planet77 - direction
	Phenomenon78 - direction
	Planet79 - direction
	Star80 - direction
	Phenomenon81 - direction
	Planet82 - direction
	Phenomenon83 - direction
	Phenomenon84 - direction
	Phenomenon85 - direction
	Star86 - direction
	Phenomenon87 - direction
	Phenomenon88 - direction
	Planet89 - direction
	Phenomenon90 - direction
	Phenomenon91 - direction
	Star92 - direction
	Phenomenon93 - direction
	Planet94 - direction
	Planet95 - direction
	Phenomenon96 - direction
	Star97 - direction
	Star98 - direction
	Star99 - direction
	Planet100 - direction
	Phenomenon101 - direction
	Phenomenon102 - direction
	Star103 - direction
	Phenomenon104 - direction
)
(:init
	(supports instrument0 spectrograph1)
	(calibration_target instrument0 GroundStation26)
	(calibration_target instrument0 GroundStation18)
	(calibration_target instrument0 GroundStation31)
	(supports instrument1 infrared2)
	(supports instrument1 image3)
	(supports instrument1 infrared0)
	(calibration_target instrument1 Star38)
	(calibration_target instrument1 GroundStation14)
	(calibration_target instrument1 Star11)
	(calibration_target instrument1 GroundStation18)
	(calibration_target instrument1 GroundStation15)
	(calibration_target instrument1 Star0)
	(calibration_target instrument1 Star55)
	(calibration_target instrument1 GroundStation39)
	(calibration_target instrument1 Star9)
	(calibration_target instrument1 GroundStation53)
	(calibration_target instrument1 GroundStation7)
	(calibration_target instrument1 GroundStation31)
	(calibration_target instrument1 GroundStation22)
	(calibration_target instrument1 Star10)
	(calibration_target instrument1 GroundStation27)
	(supports instrument2 spectrograph1)
	(supports instrument2 infrared0)
	(supports instrument2 thermograph4)
	(calibration_target instrument2 GroundStation26)
	(calibration_target instrument2 GroundStation12)
	(calibration_target instrument2 GroundStation5)
	(calibration_target instrument2 GroundStation33)
	(supports instrument3 infrared0)
	(calibration_target instrument3 GroundStation2)
	(calibration_target instrument3 GroundStation57)
	(calibration_target instrument3 GroundStation28)
	(calibration_target instrument3 GroundStation13)
	(calibration_target instrument3 Star9)
	(calibration_target instrument3 Star34)
	(calibration_target instrument3 Star45)
	(calibration_target instrument3 GroundStation44)
	(calibration_target instrument3 Star32)
	(calibration_target instrument3 GroundStation26)
	(calibration_target instrument3 Star4)
	(calibration_target instrument3 Star8)
	(calibration_target instrument3 GroundStation23)
	(supports instrument4 infrared0)
	(supports instrument4 infrared2)
	(calibration_target instrument4 GroundStation22)
	(calibration_target instrument4 GroundStation49)
	(calibration_target instrument4 Star0)
	(calibration_target instrument4 GroundStation23)
	(calibration_target instrument4 GroundStation56)
	(calibration_target instrument4 Star50)
	(calibration_target instrument4 GroundStation17)
	(calibration_target instrument4 GroundStation13)
	(calibration_target instrument4 Star32)
	(calibration_target instrument4 GroundStation47)
	(calibration_target instrument4 Star34)
	(calibration_target instrument4 Star45)
	(calibration_target instrument4 Star52)
	(calibration_target instrument4 GroundStation19)
	(calibration_target instrument4 GroundStation53)
	(calibration_target instrument4 GroundStation5)
	(calibration_target instrument4 GroundStation29)
	(calibration_target instrument4 GroundStation27)
	(calibration_target instrument4 GroundStation39)
	(calibration_target instrument4 GroundStation46)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star48)
	(supports instrument5 thermograph4)
	(calibration_target instrument5 GroundStation27)
	(calibration_target instrument5 GroundStation22)
	(calibration_target instrument5 Star24)
	(calibration_target instrument5 Star11)
	(calibration_target instrument5 Star45)
	(calibration_target instrument5 GroundStation37)
	(calibration_target instrument5 Star32)
	(calibration_target instrument5 GroundStation29)
	(calibration_target instrument5 Star9)
	(calibration_target instrument5 Star35)
	(calibration_target instrument5 Star3)
	(calibration_target instrument5 GroundStation20)
	(calibration_target instrument5 GroundStation1)
	(calibration_target instrument5 GroundStation46)
	(calibration_target instrument5 Star40)
	(calibration_target instrument5 GroundStation57)
	(calibration_target instrument5 GroundStation47)
	(calibration_target instrument5 GroundStation44)
	(calibration_target instrument5 GroundStation31)
	(supports instrument6 spectrograph1)
	(calibration_target instrument6 Star21)
	(calibration_target instrument6 GroundStation14)
	(calibration_target instrument6 Star52)
	(calibration_target instrument6 GroundStation57)
	(calibration_target instrument6 GroundStation39)
	(calibration_target instrument6 Star54)
	(calibration_target instrument6 GroundStation17)
	(calibration_target instrument6 Star41)
	(calibration_target instrument6 Star50)
	(calibration_target instrument6 GroundStation53)
	(calibration_target instrument6 GroundStation36)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation22)
	(supports instrument7 image3)
	(supports instrument7 thermograph4)
	(supports instrument7 infrared2)
	(calibration_target instrument7 GroundStation5)
	(calibration_target instrument7 GroundStation22)
	(calibration_target instrument7 Star11)
	(calibration_target instrument7 Star52)
	(calibration_target instrument7 GroundStation17)
	(calibration_target instrument7 Star8)
	(calibration_target instrument7 GroundStation13)
	(calibration_target instrument7 Star21)
	(calibration_target instrument7 GroundStation26)
	(calibration_target instrument7 GroundStation36)
	(calibration_target instrument7 Star38)
	(calibration_target instrument7 Star34)
	(supports instrument8 infrared0)
	(supports instrument8 infrared2)
	(calibration_target instrument8 Star38)
	(calibration_target instrument8 GroundStation14)
	(calibration_target instrument8 GroundStation51)
	(calibration_target instrument8 GroundStation15)
	(calibration_target instrument8 Star9)
	(calibration_target instrument8 Star8)
	(calibration_target instrument8 Star10)
	(calibration_target instrument8 Star40)
	(calibration_target instrument8 GroundStation33)
	(calibration_target instrument8 Star45)
	(calibration_target instrument8 GroundStation47)
	(supports instrument9 thermograph4)
	(calibration_target instrument9 GroundStation39)
	(calibration_target instrument9 GroundStation13)
	(calibration_target instrument9 Star38)
	(calibration_target instrument9 GroundStation22)
	(calibration_target instrument9 GroundStation18)
	(calibration_target instrument9 GroundStation37)
	(calibration_target instrument9 Star54)
	(calibration_target instrument9 GroundStation6)
	(calibration_target instrument9 GroundStation36)
	(calibration_target instrument9 GroundStation33)
	(supports instrument10 thermograph4)
	(supports instrument10 infrared0)
	(calibration_target instrument10 Star10)
	(calibration_target instrument10 Star16)
	(calibration_target instrument10 GroundStation37)
	(calibration_target instrument10 GroundStation23)
	(calibration_target instrument10 GroundStation58)
	(calibration_target instrument10 Star55)
	(calibration_target instrument10 Star9)
	(calibration_target instrument10 Star45)
	(on_board instrument7 satellite2)
	(on_board instrument8 satellite2)
	(on_board instrument9 satellite2)
	(on_board instrument10 satellite2)
	(power_avail satellite2)
	(pointing satellite2 GroundStation58)
	(supports instrument11 thermograph4)
	(calibration_target instrument11 Star8)
	(calibration_target instrument11 GroundStation1)
	(calibration_target instrument11 Star38)
	(calibration_target instrument11 Star21)
	(calibration_target instrument11 GroundStation14)
	(calibration_target instrument11 GroundStation26)
	(calibration_target instrument11 GroundStation17)
	(calibration_target instrument11 GroundStation5)
	(calibration_target instrument11 GroundStation39)
	(calibration_target instrument11 Star40)
	(calibration_target instrument11 GroundStation6)
	(calibration_target instrument11 Star34)
	(calibration_target instrument11 GroundStation20)
	(calibration_target instrument11 Star52)
	(calibration_target instrument11 GroundStation44)
	(calibration_target instrument11 GroundStation58)
	(calibration_target instrument11 GroundStation51)
	(calibration_target instrument11 GroundStation47)
	(supports instrument12 image3)
	(calibration_target instrument12 GroundStation17)
	(calibration_target instrument12 Star21)
	(supports instrument13 infrared0)
	(calibration_target instrument13 GroundStation56)
	(calibration_target instrument13 GroundStation7)
	(calibration_target instrument13 GroundStation22)
	(calibration_target instrument13 Star3)
	(calibration_target instrument13 GroundStation26)
	(calibration_target instrument13 GroundStation19)
	(calibration_target instrument13 Star24)
	(calibration_target instrument13 Star32)
	(calibration_target instrument13 GroundStation57)
	(calibration_target instrument13 GroundStation15)
	(calibration_target instrument13 GroundStation13)
	(calibration_target instrument13 GroundStation17)
	(calibration_target instrument13 Star0)
	(calibration_target instrument13 GroundStation25)
	(calibration_target instrument13 GroundStation33)
	(calibration_target instrument13 GroundStation14)
	(calibration_target instrument13 GroundStation2)
	(calibration_target instrument13 Star4)
	(supports instrument14 infrared2)
	(supports instrument14 spectrograph1)
	(calibration_target instrument14 GroundStation1)
	(calibration_target instrument14 GroundStation14)
	(calibration_target instrument14 GroundStation57)
	(calibration_target instrument14 Star24)
	(calibration_target instrument14 GroundStation2)
	(calibration_target instrument14 Star50)
	(calibration_target instrument14 GroundStation25)
	(calibration_target instrument14 Star3)
	(calibration_target instrument14 GroundStation23)
	(calibration_target instrument14 Star35)
	(calibration_target instrument14 GroundStation13)
	(calibration_target instrument14 Star42)
	(calibration_target instrument14 GroundStation39)
	(calibration_target instrument14 Star43)
	(calibration_target instrument14 Star8)
	(calibration_target instrument14 Star48)
	(calibration_target instrument14 GroundStation46)
	(calibration_target instrument14 Star41)
	(on_board instrument11 satellite3)
	(on_board instrument12 satellite3)
	(on_board instrument13 satellite3)
	(on_board instrument14 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation15)
	(supports instrument15 spectrograph1)
	(supports instrument15 image3)
	(calibration_target instrument15 Star43)
	(calibration_target instrument15 GroundStation7)
	(calibration_target instrument15 Star40)
	(calibration_target instrument15 GroundStation58)
	(calibration_target instrument15 GroundStation13)
	(calibration_target instrument15 GroundStation49)
	(calibration_target instrument15 GroundStation15)
	(calibration_target instrument15 GroundStation1)
	(calibration_target instrument15 Star24)
	(calibration_target instrument15 GroundStation46)
	(calibration_target instrument15 GroundStation31)
	(calibration_target instrument15 Star9)
	(supports instrument16 image3)
	(supports instrument16 thermograph4)
	(supports instrument16 infrared0)
	(calibration_target instrument16 GroundStation39)
	(calibration_target instrument16 GroundStation1)
	(calibration_target instrument16 GroundStation59)
	(calibration_target instrument16 Star52)
	(calibration_target instrument16 GroundStation6)
	(supports instrument17 thermograph4)
	(supports instrument17 infrared2)
	(calibration_target instrument17 GroundStation7)
	(calibration_target instrument17 Star35)
	(calibration_target instrument17 GroundStation29)
	(calibration_target instrument17 GroundStation27)
	(calibration_target instrument17 GroundStation53)
	(calibration_target instrument17 GroundStation22)
	(calibration_target instrument17 Star55)
	(calibration_target instrument17 Star38)
	(calibration_target instrument17 GroundStation47)
	(calibration_target instrument17 GroundStation1)
	(calibration_target instrument17 Star4)
	(calibration_target instrument17 Star50)
	(calibration_target instrument17 GroundStation57)
	(supports instrument18 spectrograph1)
	(calibration_target instrument18 Star34)
	(calibration_target instrument18 GroundStation58)
	(calibration_target instrument18 GroundStation5)
	(calibration_target instrument18 GroundStation47)
	(calibration_target instrument18 Star52)
	(calibration_target instrument18 GroundStation17)
	(calibration_target instrument18 GroundStation53)
	(calibration_target instrument18 GroundStation44)
	(on_board instrument15 satellite4)
	(on_board instrument16 satellite4)
	(on_board instrument17 satellite4)
	(on_board instrument18 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star41)
	(supports instrument19 thermograph4)
	(calibration_target instrument19 GroundStation1)
	(calibration_target instrument19 GroundStation33)
	(calibration_target instrument19 GroundStation30)
	(calibration_target instrument19 Star55)
	(calibration_target instrument19 Star40)
	(calibration_target instrument19 Star0)
	(calibration_target instrument19 GroundStation25)
	(calibration_target instrument19 GroundStation53)
	(calibration_target instrument19 GroundStation18)
	(calibration_target instrument19 Star10)
	(calibration_target instrument19 Star21)
	(calibration_target instrument19 GroundStation28)
	(calibration_target instrument19 Star3)
	(calibration_target instrument19 Star50)
	(calibration_target instrument19 GroundStation56)
	(calibration_target instrument19 GroundStation7)
	(calibration_target instrument19 Star16)
	(calibration_target instrument19 Star52)
	(calibration_target instrument19 GroundStation47)
	(calibration_target instrument19 Star41)
	(on_board instrument19 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Phenomenon63)
)
(:goal (and
	(pointing satellite0 GroundStation2)
	(pointing satellite1 Star4)
	(have_image Phenomenon60 thermograph4)
	(have_image Phenomenon61 thermograph4)
	(have_image Star62 spectrograph1)
	(have_image Phenomenon63 infrared2)
	(have_image Star64 infrared0)
	(have_image Phenomenon65 thermograph4)
	(have_image Star66 image3)
	(have_image Star67 infrared0)
	(have_image Planet68 thermograph4)
	(have_image Planet69 spectrograph1)
	(have_image Planet70 infrared0)
	(have_image Planet71 thermograph4)
	(have_image Planet72 spectrograph1)
	(have_image Star73 thermograph4)
	(have_image Star74 infrared2)
	(have_image Planet75 spectrograph1)
	(have_image Planet76 infrared2)
	(have_image Planet77 infrared2)
	(have_image Phenomenon78 thermograph4)
	(have_image Planet79 spectrograph1)
	(have_image Star80 image3)
	(have_image Phenomenon81 thermograph4)
	(have_image Planet82 infrared0)
	(have_image Phenomenon83 infrared2)
	(have_image Phenomenon84 spectrograph1)
	(have_image Phenomenon85 infrared2)
	(have_image Star86 infrared2)
	(have_image Phenomenon87 infrared2)
	(have_image Phenomenon88 infrared0)
	(have_image Planet89 spectrograph1)
	(have_image Phenomenon90 infrared2)
	(have_image Phenomenon91 infrared2)
	(have_image Star92 infrared0)
	(have_image Phenomenon93 infrared2)
	(have_image Planet94 thermograph4)
	(have_image Planet95 infrared0)
	(have_image Phenomenon96 infrared0)
	(have_image Star97 thermograph4)
	(have_image Star98 thermograph4)
	(have_image Star99 infrared2)
	(have_image Planet100 infrared2)
	(have_image Phenomenon101 infrared0)
	(have_image Phenomenon102 infrared0)
	(have_image Star103 infrared2)
	(have_image Phenomenon104 infrared2)
))

)
