(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	satellite1 - satellite
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	satellite2 - satellite
	instrument7 - instrument
	satellite3 - satellite
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	satellite4 - satellite
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	satellite5 - satellite
	instrument17 - instrument
	thermograph4 - mode
	image0 - mode
	thermograph1 - mode
	infrared3 - mode
	thermograph2 - mode
	Star13 - direction
	Star19 - direction
	Star0 - direction
	Star33 - direction
	Star40 - direction
	GroundStation52 - direction
	Star43 - direction
	GroundStation3 - direction
	Star30 - direction
	GroundStation53 - direction
	Star58 - direction
	GroundStation6 - direction
	Star9 - direction
	GroundStation24 - direction
	GroundStation50 - direction
	Star28 - direction
	GroundStation32 - direction
	GroundStation39 - direction
	Star42 - direction
	GroundStation48 - direction
	Star31 - direction
	GroundStation11 - direction
	GroundStation25 - direction
	Star20 - direction
	GroundStation45 - direction
	GroundStation44 - direction
	Star26 - direction
	Star5 - direction
	Star59 - direction
	GroundStation56 - direction
	Star41 - direction
	GroundStation1 - direction
	Star55 - direction
	Star2 - direction
	Star10 - direction
	Star23 - direction
	Star14 - direction
	Star36 - direction
	GroundStation49 - direction
	GroundStation17 - direction
	Star22 - direction
	Star8 - direction
	GroundStation4 - direction
	GroundStation34 - direction
	Star21 - direction
	Star37 - direction
	Star54 - direction
	Star46 - direction
	Star38 - direction
	GroundStation7 - direction
	GroundStation16 - direction
	Star27 - direction
	Star15 - direction
	GroundStation47 - direction
	GroundStation29 - direction
	GroundStation18 - direction
	Star12 - direction
	Star51 - direction
	Star57 - direction
	Star35 - direction
	Phenomenon60 - direction
	Phenomenon61 - direction
	Phenomenon62 - direction
	Phenomenon63 - direction
	Phenomenon64 - direction
	Planet65 - direction
	Star66 - direction
	Star67 - direction
	Star68 - direction
	Star69 - direction
	Phenomenon70 - direction
	Planet71 - direction
	Planet72 - direction
	Star73 - direction
	Phenomenon74 - direction
	Planet75 - direction
	Planet76 - direction
	Planet77 - direction
	Phenomenon78 - direction
	Phenomenon79 - direction
	Planet80 - direction
	Star81 - direction
	Planet82 - direction
	Star83 - direction
	Phenomenon84 - direction
	Planet85 - direction
	Phenomenon86 - direction
	Star87 - direction
	Star88 - direction
	Star89 - direction
	Planet90 - direction
	Star91 - direction
	Planet92 - direction
	Planet93 - direction
	Planet94 - direction
	Planet95 - direction
	Phenomenon96 - direction
	Star97 - direction
	Planet98 - direction
	Phenomenon99 - direction
	Phenomenon100 - direction
	Phenomenon101 - direction
	Planet102 - direction
	Star103 - direction
	Planet104 - direction
)
(:init
	(supports instrument0 image0)
	(supports instrument0 infrared3)
	(calibration_target instrument0 GroundStation39)
	(calibration_target instrument0 Star59)
	(calibration_target instrument0 GroundStation52)
	(calibration_target instrument0 Star33)
	(supports instrument1 infrared3)
	(supports instrument1 thermograph4)
	(calibration_target instrument1 Star41)
	(calibration_target instrument1 Star35)
	(calibration_target instrument1 Star12)
	(calibration_target instrument1 Star59)
	(calibration_target instrument1 Star2)
	(calibration_target instrument1 GroundStation52)
	(calibration_target instrument1 Star21)
	(calibration_target instrument1 GroundStation3)
	(calibration_target instrument1 Star10)
	(calibration_target instrument1 GroundStation32)
	(calibration_target instrument1 GroundStation25)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star10)
	(supports instrument2 thermograph1)
	(calibration_target instrument2 Star33)
	(calibration_target instrument2 GroundStation47)
	(calibration_target instrument2 GroundStation44)
	(calibration_target instrument2 GroundStation32)
	(calibration_target instrument2 GroundStation45)
	(calibration_target instrument2 Star59)
	(calibration_target instrument2 Star21)
	(calibration_target instrument2 Star54)
	(calibration_target instrument2 Star31)
	(calibration_target instrument2 GroundStation18)
	(calibration_target instrument2 GroundStation24)
	(calibration_target instrument2 Star30)
	(calibration_target instrument2 Star51)
	(supports instrument3 thermograph2)
	(calibration_target instrument3 GroundStation48)
	(calibration_target instrument3 Star10)
	(calibration_target instrument3 GroundStation1)
	(calibration_target instrument3 GroundStation11)
	(calibration_target instrument3 Star22)
	(supports instrument4 image0)
	(supports instrument4 thermograph2)
	(supports instrument4 thermograph4)
	(calibration_target instrument4 Star0)
	(calibration_target instrument4 Star5)
	(calibration_target instrument4 Star57)
	(calibration_target instrument4 Star36)
	(calibration_target instrument4 GroundStation53)
	(calibration_target instrument4 Star9)
	(calibration_target instrument4 Star31)
	(calibration_target instrument4 Star42)
	(calibration_target instrument4 GroundStation4)
	(calibration_target instrument4 Star19)
	(calibration_target instrument4 Star35)
	(calibration_target instrument4 Star15)
	(calibration_target instrument4 Star26)
	(calibration_target instrument4 Star21)
	(calibration_target instrument4 Star23)
	(supports instrument5 thermograph4)
	(supports instrument5 infrared3)
	(supports instrument5 thermograph2)
	(calibration_target instrument5 GroundStation44)
	(calibration_target instrument5 Star2)
	(calibration_target instrument5 Star51)
	(calibration_target instrument5 GroundStation6)
	(calibration_target instrument5 Star12)
	(calibration_target instrument5 Star22)
	(calibration_target instrument5 GroundStation11)
	(calibration_target instrument5 Star59)
	(calibration_target instrument5 Star42)
	(calibration_target instrument5 Star58)
	(calibration_target instrument5 Star21)
	(calibration_target instrument5 Star43)
	(calibration_target instrument5 Star33)
	(calibration_target instrument5 GroundStation45)
	(calibration_target instrument5 Star26)
	(supports instrument6 thermograph4)
	(calibration_target instrument6 Star5)
	(calibration_target instrument6 Star12)
	(calibration_target instrument6 Star55)
	(calibration_target instrument6 GroundStation52)
	(calibration_target instrument6 Star15)
	(calibration_target instrument6 Star59)
	(calibration_target instrument6 Star38)
	(calibration_target instrument6 GroundStation44)
	(calibration_target instrument6 GroundStation4)
	(calibration_target instrument6 GroundStation47)
	(calibration_target instrument6 Star31)
	(calibration_target instrument6 Star40)
	(calibration_target instrument6 Star46)
	(calibration_target instrument6 Star36)
	(calibration_target instrument6 Star51)
	(calibration_target instrument6 GroundStation56)
	(calibration_target instrument6 Star43)
	(calibration_target instrument6 GroundStation7)
	(on_board instrument2 satellite1)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star35)
	(supports instrument7 thermograph1)
	(supports instrument7 image0)
	(calibration_target instrument7 Star5)
	(calibration_target instrument7 Star14)
	(calibration_target instrument7 GroundStation3)
	(calibration_target instrument7 Star26)
	(calibration_target instrument7 GroundStation17)
	(calibration_target instrument7 Star38)
	(calibration_target instrument7 GroundStation49)
	(calibration_target instrument7 GroundStation25)
	(calibration_target instrument7 GroundStation11)
	(calibration_target instrument7 GroundStation32)
	(calibration_target instrument7 GroundStation6)
	(calibration_target instrument7 Star51)
	(calibration_target instrument7 Star43)
	(calibration_target instrument7 Star8)
	(calibration_target instrument7 Star36)
	(calibration_target instrument7 GroundStation47)
	(calibration_target instrument7 GroundStation24)
	(on_board instrument7 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star43)
	(supports instrument8 thermograph2)
	(calibration_target instrument8 Star28)
	(calibration_target instrument8 GroundStation25)
	(calibration_target instrument8 Star30)
	(calibration_target instrument8 Star57)
	(calibration_target instrument8 GroundStation17)
	(calibration_target instrument8 GroundStation7)
	(calibration_target instrument8 Star22)
	(supports instrument9 image0)
	(supports instrument9 thermograph4)
	(calibration_target instrument9 GroundStation34)
	(calibration_target instrument9 Star2)
	(calibration_target instrument9 GroundStation39)
	(calibration_target instrument9 Star10)
	(calibration_target instrument9 GroundStation47)
	(calibration_target instrument9 GroundStation7)
	(supports instrument10 infrared3)
	(supports instrument10 thermograph2)
	(calibration_target instrument10 Star55)
	(calibration_target instrument10 Star23)
	(calibration_target instrument10 GroundStation1)
	(calibration_target instrument10 GroundStation16)
	(calibration_target instrument10 Star58)
	(calibration_target instrument10 Star14)
	(calibration_target instrument10 Star15)
	(calibration_target instrument10 GroundStation4)
	(calibration_target instrument10 Star51)
	(calibration_target instrument10 Star42)
	(calibration_target instrument10 GroundStation32)
	(calibration_target instrument10 GroundStation53)
	(calibration_target instrument10 Star28)
	(calibration_target instrument10 Star10)
	(supports instrument11 image0)
	(supports instrument11 infrared3)
	(calibration_target instrument11 Star28)
	(calibration_target instrument11 GroundStation50)
	(calibration_target instrument11 GroundStation16)
	(calibration_target instrument11 GroundStation18)
	(calibration_target instrument11 Star42)
	(calibration_target instrument11 GroundStation24)
	(calibration_target instrument11 Star26)
	(calibration_target instrument11 Star8)
	(calibration_target instrument11 Star10)
	(calibration_target instrument11 Star9)
	(calibration_target instrument11 GroundStation47)
	(calibration_target instrument11 Star57)
	(calibration_target instrument11 Star54)
	(calibration_target instrument11 GroundStation56)
	(calibration_target instrument11 Star22)
	(calibration_target instrument11 GroundStation6)
	(calibration_target instrument11 Star23)
	(calibration_target instrument11 GroundStation34)
	(calibration_target instrument11 Star36)
	(on_board instrument8 satellite3)
	(on_board instrument9 satellite3)
	(on_board instrument10 satellite3)
	(on_board instrument11 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation18)
	(supports instrument12 thermograph2)
	(supports instrument12 image0)
	(calibration_target instrument12 Star37)
	(calibration_target instrument12 Star38)
	(calibration_target instrument12 Star14)
	(calibration_target instrument12 Star15)
	(supports instrument13 thermograph4)
	(supports instrument13 thermograph2)
	(calibration_target instrument13 GroundStation11)
	(calibration_target instrument13 GroundStation16)
	(calibration_target instrument13 Star59)
	(calibration_target instrument13 Star31)
	(calibration_target instrument13 GroundStation48)
	(calibration_target instrument13 Star23)
	(calibration_target instrument13 GroundStation1)
	(calibration_target instrument13 Star42)
	(calibration_target instrument13 GroundStation39)
	(calibration_target instrument13 Star54)
	(calibration_target instrument13 Star26)
	(calibration_target instrument13 Star20)
	(calibration_target instrument13 GroundStation32)
	(calibration_target instrument13 Star15)
	(calibration_target instrument13 GroundStation18)
	(calibration_target instrument13 Star14)
	(supports instrument14 thermograph4)
	(calibration_target instrument14 GroundStation44)
	(calibration_target instrument14 Star8)
	(calibration_target instrument14 Star35)
	(calibration_target instrument14 Star41)
	(calibration_target instrument14 GroundStation45)
	(calibration_target instrument14 Star20)
	(calibration_target instrument14 Star23)
	(calibration_target instrument14 Star46)
	(calibration_target instrument14 GroundStation25)
	(calibration_target instrument14 Star54)
	(supports instrument15 thermograph2)
	(supports instrument15 thermograph1)
	(supports instrument15 image0)
	(calibration_target instrument15 GroundStation34)
	(calibration_target instrument15 Star51)
	(calibration_target instrument15 Star23)
	(calibration_target instrument15 Star10)
	(calibration_target instrument15 Star2)
	(calibration_target instrument15 Star55)
	(calibration_target instrument15 GroundStation1)
	(calibration_target instrument15 Star41)
	(calibration_target instrument15 GroundStation56)
	(calibration_target instrument15 Star59)
	(calibration_target instrument15 GroundStation29)
	(calibration_target instrument15 Star5)
	(calibration_target instrument15 Star26)
	(supports instrument16 thermograph2)
	(calibration_target instrument16 Star54)
	(calibration_target instrument16 Star37)
	(calibration_target instrument16 Star21)
	(calibration_target instrument16 GroundStation34)
	(calibration_target instrument16 Star57)
	(calibration_target instrument16 GroundStation16)
	(calibration_target instrument16 GroundStation4)
	(calibration_target instrument16 Star8)
	(calibration_target instrument16 Star22)
	(calibration_target instrument16 GroundStation17)
	(calibration_target instrument16 GroundStation49)
	(calibration_target instrument16 Star12)
	(calibration_target instrument16 Star36)
	(calibration_target instrument16 Star14)
	(on_board instrument12 satellite4)
	(on_board instrument13 satellite4)
	(on_board instrument14 satellite4)
	(on_board instrument15 satellite4)
	(on_board instrument16 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star66)
	(supports instrument17 thermograph4)
	(supports instrument17 image0)
	(supports instrument17 thermograph2)
	(calibration_target instrument17 Star35)
	(calibration_target instrument17 Star57)
	(calibration_target instrument17 Star51)
	(calibration_target instrument17 Star12)
	(calibration_target instrument17 GroundStation18)
	(calibration_target instrument17 GroundStation29)
	(calibration_target instrument17 GroundStation47)
	(calibration_target instrument17 Star15)
	(calibration_target instrument17 Star27)
	(calibration_target instrument17 GroundStation16)
	(calibration_target instrument17 GroundStation7)
	(calibration_target instrument17 Star38)
	(calibration_target instrument17 Star46)
	(on_board instrument17 satellite5)
	(power_avail satellite5)
	(pointing satellite5 GroundStation3)
)
(:goal (and
	(pointing satellite2 Phenomenon96)
	(have_image Phenomenon60 thermograph1)
	(have_image Phenomenon61 thermograph2)
	(have_image Phenomenon62 thermograph4)
	(have_image Phenomenon63 thermograph4)
	(have_image Phenomenon64 thermograph4)
	(have_image Planet65 image0)
	(have_image Star66 thermograph2)
	(have_image Star67 infrared3)
	(have_image Star68 thermograph2)
	(have_image Star69 thermograph4)
	(have_image Phenomenon70 thermograph2)
	(have_image Planet71 infrared3)
	(have_image Planet72 thermograph4)
	(have_image Star73 image0)
	(have_image Phenomenon74 thermograph1)
	(have_image Planet75 thermograph4)
	(have_image Planet76 thermograph2)
	(have_image Planet77 infrared3)
	(have_image Phenomenon78 infrared3)
	(have_image Phenomenon79 thermograph1)
	(have_image Planet80 infrared3)
	(have_image Star81 infrared3)
	(have_image Planet82 infrared3)
	(have_image Star83 thermograph2)
	(have_image Phenomenon84 thermograph1)
	(have_image Planet85 thermograph4)
	(have_image Phenomenon86 infrared3)
	(have_image Star87 thermograph1)
	(have_image Star88 image0)
	(have_image Star89 thermograph1)
	(have_image Planet90 thermograph1)
	(have_image Star91 thermograph2)
	(have_image Planet92 thermograph1)
	(have_image Planet93 thermograph1)
	(have_image Planet94 thermograph4)
	(have_image Planet95 thermograph1)
	(have_image Phenomenon96 infrared3)
	(have_image Star97 thermograph1)
	(have_image Planet98 thermograph4)
	(have_image Phenomenon99 image0)
	(have_image Phenomenon100 thermograph4)
	(have_image Phenomenon101 thermograph4)
	(have_image Planet102 image0)
	(have_image Star103 image0)
	(have_image Planet104 thermograph4)
))

)
