(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	satellite1 - satellite
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	satellite2 - satellite
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	satellite3 - satellite
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	satellite4 - satellite
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	satellite5 - satellite
	instrument21 - instrument
	instrument22 - instrument
	thermograph2 - mode
	thermograph0 - mode
	image1 - mode
	thermograph3 - mode
	thermograph4 - mode
	Star53 - direction
	GroundStation16 - direction
	GroundStation31 - direction
	Star17 - direction
	GroundStation46 - direction
	Star1 - direction
	GroundStation7 - direction
	Star45 - direction
	Star3 - direction
	Star0 - direction
	GroundStation33 - direction
	GroundStation6 - direction
	GroundStation12 - direction
	Star9 - direction
	GroundStation13 - direction
	Star27 - direction
	Star26 - direction
	Star40 - direction
	GroundStation41 - direction
	GroundStation14 - direction
	Star30 - direction
	Star35 - direction
	Star37 - direction
	GroundStation48 - direction
	GroundStation55 - direction
	Star49 - direction
	Star18 - direction
	Star20 - direction
	GroundStation15 - direction
	Star29 - direction
	GroundStation42 - direction
	Star36 - direction
	GroundStation43 - direction
	Star59 - direction
	Star51 - direction
	Star23 - direction
	GroundStation19 - direction
	Star32 - direction
	GroundStation38 - direction
	Star28 - direction
	GroundStation2 - direction
	GroundStation50 - direction
	Star8 - direction
	Star57 - direction
	Star25 - direction
	GroundStation52 - direction
	GroundStation11 - direction
	Star4 - direction
	GroundStation10 - direction
	Star56 - direction
	Star54 - direction
	GroundStation44 - direction
	GroundStation5 - direction
	Star22 - direction
	Star34 - direction
	Star39 - direction
	GroundStation24 - direction
	GroundStation58 - direction
	GroundStation21 - direction
	GroundStation47 - direction
	Phenomenon60 - direction
	Phenomenon61 - direction
	Phenomenon62 - direction
	Planet63 - direction
	Planet64 - direction
	Planet65 - direction
	Phenomenon66 - direction
	Phenomenon67 - direction
	Phenomenon68 - direction
	Star69 - direction
	Phenomenon70 - direction
	Phenomenon71 - direction
	Planet72 - direction
	Phenomenon73 - direction
	Star74 - direction
	Phenomenon75 - direction
	Star76 - direction
	Star77 - direction
	Phenomenon78 - direction
	Phenomenon79 - direction
	Phenomenon80 - direction
	Phenomenon81 - direction
	Planet82 - direction
	Star83 - direction
	Phenomenon84 - direction
	Star85 - direction
	Phenomenon86 - direction
	Planet87 - direction
	Star88 - direction
	Phenomenon89 - direction
	Planet90 - direction
	Phenomenon91 - direction
	Star92 - direction
	Phenomenon93 - direction
	Planet94 - direction
	Star95 - direction
	Phenomenon96 - direction
	Planet97 - direction
	Phenomenon98 - direction
	Planet99 - direction
	Star100 - direction
	Planet101 - direction
	Planet102 - direction
	Phenomenon103 - direction
	Planet104 - direction
)
(:init
	(supports instrument0 thermograph3)
	(supports instrument0 thermograph0)
	(calibration_target instrument0 Star56)
	(calibration_target instrument0 Star39)
	(calibration_target instrument0 GroundStation5)
	(calibration_target instrument0 GroundStation6)
	(calibration_target instrument0 GroundStation14)
	(calibration_target instrument0 Star40)
	(calibration_target instrument0 GroundStation58)
	(calibration_target instrument0 GroundStation38)
	(calibration_target instrument0 GroundStation21)
	(calibration_target instrument0 Star3)
	(calibration_target instrument0 Star36)
	(calibration_target instrument0 GroundStation10)
	(calibration_target instrument0 Star54)
	(calibration_target instrument0 Star35)
	(calibration_target instrument0 GroundStation50)
	(calibration_target instrument0 Star49)
	(calibration_target instrument0 GroundStation11)
	(calibration_target instrument0 GroundStation33)
	(calibration_target instrument0 Star8)
	(calibration_target instrument0 GroundStation2)
	(supports instrument1 thermograph2)
	(calibration_target instrument1 GroundStation6)
	(calibration_target instrument1 Star57)
	(calibration_target instrument1 GroundStation46)
	(calibration_target instrument1 Star54)
	(calibration_target instrument1 GroundStation10)
	(calibration_target instrument1 GroundStation16)
	(calibration_target instrument1 GroundStation14)
	(calibration_target instrument1 GroundStation21)
	(calibration_target instrument1 Star1)
	(calibration_target instrument1 Star34)
	(calibration_target instrument1 Star0)
	(calibration_target instrument1 Star40)
	(calibration_target instrument1 Star20)
	(calibration_target instrument1 GroundStation2)
	(supports instrument2 image1)
	(supports instrument2 thermograph2)
	(calibration_target instrument2 Star20)
	(calibration_target instrument2 GroundStation44)
	(calibration_target instrument2 GroundStation24)
	(calibration_target instrument2 Star49)
	(calibration_target instrument2 Star8)
	(calibration_target instrument2 Star18)
	(calibration_target instrument2 GroundStation52)
	(calibration_target instrument2 GroundStation50)
	(supports instrument3 thermograph0)
	(supports instrument3 thermograph3)
	(supports instrument3 image1)
	(calibration_target instrument3 GroundStation46)
	(calibration_target instrument3 Star35)
	(calibration_target instrument3 GroundStation58)
	(calibration_target instrument3 Star29)
	(calibration_target instrument3 GroundStation2)
	(calibration_target instrument3 Star54)
	(calibration_target instrument3 Star34)
	(calibration_target instrument3 GroundStation10)
	(calibration_target instrument3 Star56)
	(calibration_target instrument3 GroundStation15)
	(calibration_target instrument3 Star3)
	(calibration_target instrument3 Star17)
	(calibration_target instrument3 GroundStation31)
	(calibration_target instrument3 Star27)
	(calibration_target instrument3 Star0)
	(calibration_target instrument3 GroundStation47)
	(calibration_target instrument3 Star1)
	(calibration_target instrument3 Star30)
	(calibration_target instrument3 Star20)
	(supports instrument4 image1)
	(supports instrument4 thermograph2)
	(calibration_target instrument4 GroundStation52)
	(calibration_target instrument4 Star1)
	(calibration_target instrument4 Star36)
	(calibration_target instrument4 GroundStation43)
	(calibration_target instrument4 Star25)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation21)
	(supports instrument5 thermograph2)
	(supports instrument5 image1)
	(calibration_target instrument5 GroundStation46)
	(calibration_target instrument5 GroundStation10)
	(calibration_target instrument5 GroundStation16)
	(calibration_target instrument5 Star27)
	(calibration_target instrument5 Star49)
	(calibration_target instrument5 Star54)
	(calibration_target instrument5 Star53)
	(calibration_target instrument5 GroundStation13)
	(calibration_target instrument5 Star45)
	(calibration_target instrument5 GroundStation6)
	(calibration_target instrument5 GroundStation47)
	(calibration_target instrument5 GroundStation52)
	(calibration_target instrument5 GroundStation43)
	(calibration_target instrument5 Star35)
	(calibration_target instrument5 Star23)
	(calibration_target instrument5 GroundStation12)
	(calibration_target instrument5 Star40)
	(calibration_target instrument5 GroundStation48)
	(supports instrument6 thermograph4)
	(supports instrument6 thermograph2)
	(supports instrument6 image1)
	(calibration_target instrument6 GroundStation31)
	(calibration_target instrument6 GroundStation16)
	(calibration_target instrument6 Star17)
	(calibration_target instrument6 GroundStation24)
	(calibration_target instrument6 Star26)
	(calibration_target instrument6 Star29)
	(calibration_target instrument6 Star54)
	(calibration_target instrument6 GroundStation21)
	(calibration_target instrument6 Star4)
	(calibration_target instrument6 Star40)
	(calibration_target instrument6 Star20)
	(calibration_target instrument6 Star37)
	(supports instrument7 thermograph0)
	(calibration_target instrument7 GroundStation41)
	(calibration_target instrument7 GroundStation38)
	(calibration_target instrument7 GroundStation43)
	(calibration_target instrument7 GroundStation13)
	(calibration_target instrument7 Star49)
	(calibration_target instrument7 GroundStation48)
	(calibration_target instrument7 GroundStation11)
	(calibration_target instrument7 GroundStation55)
	(calibration_target instrument7 GroundStation6)
	(calibration_target instrument7 Star4)
	(calibration_target instrument7 Star22)
	(calibration_target instrument7 GroundStation7)
	(calibration_target instrument7 GroundStation21)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(on_board instrument7 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star92)
	(supports instrument8 image1)
	(calibration_target instrument8 Star26)
	(calibration_target instrument8 Star45)
	(calibration_target instrument8 Star37)
	(calibration_target instrument8 Star56)
	(calibration_target instrument8 GroundStation2)
	(calibration_target instrument8 Star17)
	(calibration_target instrument8 Star34)
	(calibration_target instrument8 Star57)
	(calibration_target instrument8 Star35)
	(calibration_target instrument8 GroundStation11)
	(supports instrument9 image1)
	(supports instrument9 thermograph0)
	(calibration_target instrument9 Star1)
	(calibration_target instrument9 GroundStation46)
	(calibration_target instrument9 GroundStation11)
	(calibration_target instrument9 GroundStation33)
	(supports instrument10 thermograph2)
	(supports instrument10 thermograph0)
	(supports instrument10 thermograph3)
	(calibration_target instrument10 GroundStation42)
	(calibration_target instrument10 Star25)
	(calibration_target instrument10 Star20)
	(calibration_target instrument10 GroundStation11)
	(calibration_target instrument10 Star54)
	(calibration_target instrument10 Star22)
	(calibration_target instrument10 GroundStation2)
	(calibration_target instrument10 Star57)
	(calibration_target instrument10 GroundStation7)
	(calibration_target instrument10 Star26)
	(calibration_target instrument10 Star1)
	(calibration_target instrument10 GroundStation43)
	(calibration_target instrument10 Star29)
	(calibration_target instrument10 Star32)
	(calibration_target instrument10 GroundStation52)
	(calibration_target instrument10 Star36)
	(calibration_target instrument10 Star28)
	(calibration_target instrument10 Star4)
	(calibration_target instrument10 GroundStation38)
	(calibration_target instrument10 Star40)
	(supports instrument11 thermograph4)
	(calibration_target instrument11 GroundStation33)
	(calibration_target instrument11 Star18)
	(calibration_target instrument11 Star45)
	(calibration_target instrument11 GroundStation19)
	(on_board instrument8 satellite2)
	(on_board instrument9 satellite2)
	(on_board instrument10 satellite2)
	(on_board instrument11 satellite2)
	(power_avail satellite2)
	(pointing satellite2 GroundStation55)
	(supports instrument12 thermograph2)
	(supports instrument12 image1)
	(supports instrument12 thermograph4)
	(calibration_target instrument12 Star25)
	(supports instrument13 thermograph3)
	(calibration_target instrument13 GroundStation48)
	(calibration_target instrument13 GroundStation15)
	(calibration_target instrument13 GroundStation14)
	(calibration_target instrument13 Star34)
	(calibration_target instrument13 GroundStation47)
	(calibration_target instrument13 Star27)
	(calibration_target instrument13 GroundStation44)
	(calibration_target instrument13 Star49)
	(calibration_target instrument13 GroundStation19)
	(calibration_target instrument13 Star0)
	(calibration_target instrument13 Star4)
	(calibration_target instrument13 Star3)
	(calibration_target instrument13 GroundStation33)
	(calibration_target instrument13 GroundStation21)
	(supports instrument14 thermograph0)
	(supports instrument14 thermograph4)
	(supports instrument14 image1)
	(calibration_target instrument14 GroundStation6)
	(calibration_target instrument14 GroundStation33)
	(calibration_target instrument14 GroundStation11)
	(calibration_target instrument14 GroundStation43)
	(calibration_target instrument14 GroundStation47)
	(calibration_target instrument14 Star39)
	(calibration_target instrument14 Star28)
	(calibration_target instrument14 GroundStation50)
	(calibration_target instrument14 Star54)
	(supports instrument15 image1)
	(supports instrument15 thermograph4)
	(supports instrument15 thermograph0)
	(calibration_target instrument15 GroundStation58)
	(calibration_target instrument15 Star51)
	(calibration_target instrument15 GroundStation21)
	(on_board instrument12 satellite3)
	(on_board instrument13 satellite3)
	(on_board instrument14 satellite3)
	(on_board instrument15 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Phenomenon91)
	(supports instrument16 thermograph2)
	(supports instrument16 thermograph3)
	(calibration_target instrument16 GroundStation15)
	(calibration_target instrument16 GroundStation12)
	(supports instrument17 thermograph4)
	(supports instrument17 thermograph0)
	(supports instrument17 thermograph3)
	(calibration_target instrument17 Star9)
	(calibration_target instrument17 Star59)
	(calibration_target instrument17 Star30)
	(calibration_target instrument17 GroundStation12)
	(calibration_target instrument17 GroundStation55)
	(calibration_target instrument17 GroundStation13)
	(calibration_target instrument17 GroundStation15)
	(calibration_target instrument17 GroundStation50)
	(calibration_target instrument17 GroundStation24)
	(calibration_target instrument17 Star37)
	(supports instrument18 thermograph3)
	(calibration_target instrument18 GroundStation42)
	(calibration_target instrument18 Star54)
	(calibration_target instrument18 GroundStation48)
	(calibration_target instrument18 Star36)
	(calibration_target instrument18 Star8)
	(calibration_target instrument18 GroundStation58)
	(supports instrument19 thermograph4)
	(supports instrument19 thermograph3)
	(supports instrument19 thermograph0)
	(calibration_target instrument19 GroundStation5)
	(calibration_target instrument19 Star57)
	(calibration_target instrument19 Star35)
	(calibration_target instrument19 Star30)
	(calibration_target instrument19 GroundStation10)
	(calibration_target instrument19 GroundStation19)
	(calibration_target instrument19 Star23)
	(calibration_target instrument19 Star4)
	(calibration_target instrument19 GroundStation24)
	(calibration_target instrument19 GroundStation14)
	(calibration_target instrument19 GroundStation48)
	(calibration_target instrument19 GroundStation41)
	(calibration_target instrument19 Star40)
	(calibration_target instrument19 Star26)
	(calibration_target instrument19 Star27)
	(calibration_target instrument19 GroundStation13)
	(supports instrument20 thermograph0)
	(calibration_target instrument20 GroundStation38)
	(calibration_target instrument20 Star23)
	(calibration_target instrument20 Star57)
	(calibration_target instrument20 Star51)
	(calibration_target instrument20 Star59)
	(calibration_target instrument20 GroundStation21)
	(calibration_target instrument20 GroundStation43)
	(calibration_target instrument20 Star36)
	(calibration_target instrument20 GroundStation58)
	(calibration_target instrument20 GroundStation42)
	(calibration_target instrument20 Star29)
	(calibration_target instrument20 Star39)
	(calibration_target instrument20 GroundStation15)
	(calibration_target instrument20 GroundStation19)
	(calibration_target instrument20 Star20)
	(calibration_target instrument20 Star18)
	(calibration_target instrument20 Star49)
	(calibration_target instrument20 GroundStation55)
	(calibration_target instrument20 GroundStation48)
	(calibration_target instrument20 Star37)
	(on_board instrument16 satellite4)
	(on_board instrument17 satellite4)
	(on_board instrument18 satellite4)
	(on_board instrument19 satellite4)
	(on_board instrument20 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star3)
	(supports instrument21 thermograph0)
	(supports instrument21 image1)
	(calibration_target instrument21 Star34)
	(calibration_target instrument21 Star22)
	(calibration_target instrument21 GroundStation5)
	(calibration_target instrument21 GroundStation44)
	(calibration_target instrument21 Star54)
	(calibration_target instrument21 Star56)
	(calibration_target instrument21 GroundStation10)
	(calibration_target instrument21 Star39)
	(calibration_target instrument21 Star4)
	(calibration_target instrument21 GroundStation11)
	(calibration_target instrument21 GroundStation52)
	(calibration_target instrument21 Star25)
	(calibration_target instrument21 Star57)
	(calibration_target instrument21 Star8)
	(calibration_target instrument21 GroundStation50)
	(calibration_target instrument21 GroundStation2)
	(calibration_target instrument21 Star28)
	(calibration_target instrument21 GroundStation38)
	(calibration_target instrument21 Star32)
	(calibration_target instrument21 GroundStation19)
	(supports instrument22 thermograph2)
	(calibration_target instrument22 GroundStation47)
	(calibration_target instrument22 GroundStation21)
	(calibration_target instrument22 GroundStation58)
	(calibration_target instrument22 GroundStation24)
	(calibration_target instrument22 Star39)
	(on_board instrument21 satellite5)
	(on_board instrument22 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star32)
)
(:goal (and
	(pointing satellite0 GroundStation2)
	(pointing satellite3 Star76)
	(pointing satellite4 Star9)
	(pointing satellite5 Phenomenon103)
	(have_image Phenomenon60 thermograph4)
	(have_image Phenomenon61 thermograph0)
	(have_image Phenomenon62 thermograph0)
	(have_image Planet63 thermograph3)
	(have_image Planet64 thermograph0)
	(have_image Planet65 thermograph2)
	(have_image Phenomenon66 thermograph2)
	(have_image Phenomenon67 thermograph4)
	(have_image Phenomenon68 image1)
	(have_image Star69 thermograph3)
	(have_image Phenomenon70 thermograph4)
	(have_image Phenomenon71 thermograph0)
	(have_image Planet72 thermograph4)
	(have_image Phenomenon73 thermograph0)
	(have_image Star74 thermograph0)
	(have_image Phenomenon75 image1)
	(have_image Star76 image1)
	(have_image Star77 thermograph4)
	(have_image Phenomenon78 image1)
	(have_image Phenomenon79 thermograph3)
	(have_image Phenomenon80 image1)
	(have_image Phenomenon81 thermograph4)
	(have_image Planet82 thermograph2)
	(have_image Star83 thermograph3)
	(have_image Phenomenon84 thermograph2)
	(have_image Star85 thermograph4)
	(have_image Phenomenon86 thermograph4)
	(have_image Planet87 thermograph4)
	(have_image Star88 thermograph4)
	(have_image Phenomenon89 thermograph3)
	(have_image Planet90 thermograph3)
	(have_image Phenomenon91 image1)
	(have_image Star92 thermograph2)
	(have_image Phenomenon93 thermograph0)
	(have_image Planet94 thermograph4)
	(have_image Star95 thermograph2)
	(have_image Phenomenon96 image1)
	(have_image Planet97 thermograph3)
	(have_image Phenomenon98 thermograph2)
	(have_image Planet99 thermograph3)
	(have_image Star100 thermograph2)
	(have_image Planet101 thermograph4)
	(have_image Planet102 image1)
	(have_image Phenomenon103 image1)
	(have_image Planet104 thermograph4)
))

)
