(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	satellite1 - satellite
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	satellite2 - satellite
	instrument6 - instrument
	instrument7 - instrument
	satellite3 - satellite
	instrument8 - instrument
	satellite4 - satellite
	instrument9 - instrument
	satellite5 - satellite
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	thermograph0 - mode
	infrared1 - mode
	infrared2 - mode
	infrared4 - mode
	image3 - mode
	Star0 - direction
	GroundStation7 - direction
	Star51 - direction
	Star5 - direction
	Star55 - direction
	GroundStation57 - direction
	GroundStation4 - direction
	Star53 - direction
	GroundStation17 - direction
	Star37 - direction
	GroundStation47 - direction
	Star52 - direction
	GroundStation13 - direction
	Star30 - direction
	GroundStation44 - direction
	Star54 - direction
	Star28 - direction
	Star33 - direction
	Star40 - direction
	GroundStation2 - direction
	Star41 - direction
	Star19 - direction
	GroundStation18 - direction
	GroundStation48 - direction
	Star43 - direction
	GroundStation11 - direction
	GroundStation8 - direction
	Star12 - direction
	Star3 - direction
	GroundStation32 - direction
	Star25 - direction
	GroundStation58 - direction
	GroundStation35 - direction
	Star29 - direction
	Star38 - direction
	Star24 - direction
	Star56 - direction
	Star22 - direction
	GroundStation31 - direction
	Star15 - direction
	Star14 - direction
	Star1 - direction
	GroundStation45 - direction
	GroundStation49 - direction
	GroundStation20 - direction
	Star9 - direction
	Star23 - direction
	Star46 - direction
	Star21 - direction
	GroundStation26 - direction
	GroundStation39 - direction
	Star36 - direction
	GroundStation34 - direction
	Star16 - direction
	Star6 - direction
	Star10 - direction
	GroundStation27 - direction
	Star59 - direction
	Star50 - direction
	Star42 - direction
	Planet60 - direction
	Phenomenon61 - direction
	Planet62 - direction
	Planet63 - direction
	Star64 - direction
	Star65 - direction
	Planet66 - direction
	Phenomenon67 - direction
	Phenomenon68 - direction
	Planet69 - direction
	Phenomenon70 - direction
	Phenomenon71 - direction
	Planet72 - direction
	Phenomenon73 - direction
	Planet74 - direction
	Star75 - direction
	Phenomenon76 - direction
	Planet77 - direction
	Phenomenon78 - direction
	Star79 - direction
	Star80 - direction
	Phenomenon81 - direction
	Phenomenon82 - direction
	Phenomenon83 - direction
	Star84 - direction
	Planet85 - direction
	Planet86 - direction
	Phenomenon87 - direction
	Planet88 - direction
	Planet89 - direction
	Planet90 - direction
	Phenomenon91 - direction
	Planet92 - direction
	Star93 - direction
	Star94 - direction
	Planet95 - direction
	Phenomenon96 - direction
	Planet97 - direction
	Phenomenon98 - direction
	Phenomenon99 - direction
	Star100 - direction
	Phenomenon101 - direction
	Phenomenon102 - direction
	Phenomenon103 - direction
	Phenomenon104 - direction
)
(:init
	(supports instrument0 image3)
	(supports instrument0 infrared2)
	(supports instrument0 infrared4)
	(calibration_target instrument0 Star55)
	(calibration_target instrument0 GroundStation57)
	(calibration_target instrument0 GroundStation4)
	(calibration_target instrument0 Star53)
	(calibration_target instrument0 GroundStation18)
	(on_board instrument0 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star79)
	(supports instrument1 thermograph0)
	(supports instrument1 infrared2)
	(supports instrument1 infrared1)
	(calibration_target instrument1 Star10)
	(calibration_target instrument1 Star54)
	(calibration_target instrument1 Star16)
	(calibration_target instrument1 Star15)
	(calibration_target instrument1 Star51)
	(calibration_target instrument1 Star14)
	(calibration_target instrument1 Star12)
	(calibration_target instrument1 GroundStation49)
	(calibration_target instrument1 Star30)
	(calibration_target instrument1 GroundStation7)
	(calibration_target instrument1 Star46)
	(calibration_target instrument1 GroundStation35)
	(calibration_target instrument1 Star1)
	(calibration_target instrument1 Star5)
	(calibration_target instrument1 Star21)
	(calibration_target instrument1 Star25)
	(calibration_target instrument1 GroundStation11)
	(supports instrument2 infrared1)
	(supports instrument2 image3)
	(calibration_target instrument2 GroundStation32)
	(calibration_target instrument2 GroundStation11)
	(calibration_target instrument2 Star5)
	(calibration_target instrument2 Star6)
	(calibration_target instrument2 Star28)
	(calibration_target instrument2 Star46)
	(calibration_target instrument2 GroundStation17)
	(calibration_target instrument2 GroundStation45)
	(calibration_target instrument2 Star19)
	(calibration_target instrument2 Star33)
	(calibration_target instrument2 Star29)
	(calibration_target instrument2 Star56)
	(calibration_target instrument2 GroundStation2)
	(calibration_target instrument2 Star16)
	(supports instrument3 infrared4)
	(supports instrument3 image3)
	(supports instrument3 infrared1)
	(calibration_target instrument3 GroundStation48)
	(calibration_target instrument3 GroundStation8)
	(calibration_target instrument3 Star24)
	(calibration_target instrument3 GroundStation34)
	(calibration_target instrument3 GroundStation31)
	(calibration_target instrument3 GroundStation49)
	(calibration_target instrument3 GroundStation44)
	(calibration_target instrument3 GroundStation4)
	(calibration_target instrument3 GroundStation17)
	(calibration_target instrument3 Star46)
	(calibration_target instrument3 GroundStation57)
	(calibration_target instrument3 Star56)
	(calibration_target instrument3 Star40)
	(calibration_target instrument3 Star37)
	(calibration_target instrument3 GroundStation2)
	(calibration_target instrument3 Star50)
	(calibration_target instrument3 Star53)
	(calibration_target instrument3 Star55)
	(supports instrument4 image3)
	(supports instrument4 infrared1)
	(supports instrument4 infrared4)
	(calibration_target instrument4 GroundStation13)
	(calibration_target instrument4 Star54)
	(calibration_target instrument4 GroundStation49)
	(calibration_target instrument4 Star52)
	(calibration_target instrument4 Star59)
	(calibration_target instrument4 GroundStation47)
	(calibration_target instrument4 Star50)
	(calibration_target instrument4 Star40)
	(calibration_target instrument4 Star6)
	(calibration_target instrument4 Star15)
	(calibration_target instrument4 Star37)
	(calibration_target instrument4 GroundStation17)
	(calibration_target instrument4 Star53)
	(supports instrument5 infrared2)
	(calibration_target instrument5 Star40)
	(calibration_target instrument5 GroundStation8)
	(calibration_target instrument5 Star21)
	(calibration_target instrument5 Star12)
	(calibration_target instrument5 Star46)
	(on_board instrument1 satellite1)
	(on_board instrument2 satellite1)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Phenomenon102)
	(supports instrument6 thermograph0)
	(supports instrument6 infrared1)
	(calibration_target instrument6 GroundStation48)
	(calibration_target instrument6 GroundStation44)
	(calibration_target instrument6 Star30)
	(calibration_target instrument6 Star1)
	(calibration_target instrument6 Star3)
	(calibration_target instrument6 Star50)
	(calibration_target instrument6 Star40)
	(supports instrument7 infrared4)
	(supports instrument7 image3)
	(calibration_target instrument7 Star28)
	(calibration_target instrument7 GroundStation34)
	(calibration_target instrument7 Star3)
	(calibration_target instrument7 GroundStation18)
	(calibration_target instrument7 Star46)
	(calibration_target instrument7 Star10)
	(calibration_target instrument7 Star54)
	(on_board instrument6 satellite2)
	(on_board instrument7 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Phenomenon96)
	(supports instrument8 infrared1)
	(supports instrument8 infrared2)
	(supports instrument8 image3)
	(calibration_target instrument8 Star15)
	(calibration_target instrument8 GroundStation48)
	(calibration_target instrument8 GroundStation18)
	(calibration_target instrument8 Star12)
	(calibration_target instrument8 Star42)
	(calibration_target instrument8 Star19)
	(calibration_target instrument8 Star29)
	(calibration_target instrument8 GroundStation27)
	(calibration_target instrument8 Star6)
	(calibration_target instrument8 Star41)
	(calibration_target instrument8 GroundStation2)
	(calibration_target instrument8 GroundStation32)
	(calibration_target instrument8 Star43)
	(calibration_target instrument8 Star38)
	(calibration_target instrument8 Star40)
	(calibration_target instrument8 Star25)
	(calibration_target instrument8 Star33)
	(on_board instrument8 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Planet60)
	(supports instrument9 image3)
	(calibration_target instrument9 Star56)
	(calibration_target instrument9 GroundStation11)
	(calibration_target instrument9 GroundStation8)
	(calibration_target instrument9 Star46)
	(calibration_target instrument9 Star25)
	(calibration_target instrument9 Star59)
	(calibration_target instrument9 Star43)
	(on_board instrument9 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Planet85)
	(supports instrument10 image3)
	(supports instrument10 thermograph0)
	(calibration_target instrument10 Star3)
	(calibration_target instrument10 Star14)
	(calibration_target instrument10 Star50)
	(calibration_target instrument10 GroundStation27)
	(calibration_target instrument10 GroundStation32)
	(calibration_target instrument10 Star12)
	(calibration_target instrument10 GroundStation20)
	(calibration_target instrument10 GroundStation8)
	(supports instrument11 thermograph0)
	(supports instrument11 infrared4)
	(calibration_target instrument11 GroundStation31)
	(calibration_target instrument11 Star9)
	(calibration_target instrument11 Star46)
	(calibration_target instrument11 Star22)
	(calibration_target instrument11 Star56)
	(calibration_target instrument11 Star16)
	(calibration_target instrument11 Star15)
	(calibration_target instrument11 Star24)
	(calibration_target instrument11 GroundStation39)
	(calibration_target instrument11 GroundStation27)
	(calibration_target instrument11 Star38)
	(calibration_target instrument11 Star29)
	(calibration_target instrument11 GroundStation35)
	(calibration_target instrument11 GroundStation58)
	(calibration_target instrument11 Star1)
	(calibration_target instrument11 Star25)
	(calibration_target instrument11 GroundStation32)
	(supports instrument12 infrared4)
	(calibration_target instrument12 GroundStation26)
	(calibration_target instrument12 Star23)
	(calibration_target instrument12 Star59)
	(calibration_target instrument12 Star9)
	(calibration_target instrument12 GroundStation20)
	(calibration_target instrument12 GroundStation49)
	(calibration_target instrument12 GroundStation45)
	(calibration_target instrument12 Star1)
	(calibration_target instrument12 Star14)
	(calibration_target instrument12 Star15)
	(supports instrument13 infrared2)
	(supports instrument13 infrared1)
	(supports instrument13 thermograph0)
	(calibration_target instrument13 Star42)
	(calibration_target instrument13 Star50)
	(calibration_target instrument13 Star59)
	(calibration_target instrument13 GroundStation27)
	(calibration_target instrument13 Star10)
	(calibration_target instrument13 Star6)
	(calibration_target instrument13 Star16)
	(calibration_target instrument13 GroundStation34)
	(calibration_target instrument13 Star36)
	(calibration_target instrument13 GroundStation39)
	(calibration_target instrument13 GroundStation26)
	(calibration_target instrument13 Star21)
	(calibration_target instrument13 Star46)
	(on_board instrument10 satellite5)
	(on_board instrument11 satellite5)
	(on_board instrument12 satellite5)
	(on_board instrument13 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Planet60)
)
(:goal (and
	(pointing satellite1 Star53)
	(have_image Planet60 infrared1)
	(have_image Phenomenon61 infrared1)
	(have_image Planet62 thermograph0)
	(have_image Planet63 infrared1)
	(have_image Star64 infrared1)
	(have_image Star65 infrared2)
	(have_image Planet66 thermograph0)
	(have_image Phenomenon67 infrared2)
	(have_image Phenomenon68 image3)
	(have_image Planet69 thermograph0)
	(have_image Phenomenon70 infrared4)
	(have_image Phenomenon71 infrared4)
	(have_image Planet72 infrared4)
	(have_image Phenomenon73 infrared2)
	(have_image Planet74 thermograph0)
	(have_image Star75 infrared2)
	(have_image Phenomenon76 thermograph0)
	(have_image Planet77 thermograph0)
	(have_image Phenomenon78 thermograph0)
	(have_image Star79 infrared2)
	(have_image Star80 infrared2)
	(have_image Phenomenon81 infrared4)
	(have_image Phenomenon82 image3)
	(have_image Phenomenon83 thermograph0)
	(have_image Star84 thermograph0)
	(have_image Planet85 thermograph0)
	(have_image Planet86 infrared2)
	(have_image Phenomenon87 thermograph0)
	(have_image Planet88 thermograph0)
	(have_image Planet89 infrared4)
	(have_image Planet90 infrared4)
	(have_image Phenomenon91 infrared4)
	(have_image Planet92 infrared4)
	(have_image Star93 infrared2)
	(have_image Star94 image3)
	(have_image Planet95 infrared2)
	(have_image Phenomenon96 infrared4)
	(have_image Planet97 thermograph0)
	(have_image Phenomenon98 thermograph0)
	(have_image Phenomenon99 image3)
	(have_image Star100 thermograph0)
	(have_image Phenomenon101 thermograph0)
	(have_image Phenomenon102 infrared4)
	(have_image Phenomenon103 infrared2)
	(have_image Phenomenon104 image3)
))

)
