(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	satellite1 - satellite
	instrument1 - instrument
	satellite2 - satellite
	instrument2 - instrument
	instrument3 - instrument
	satellite3 - satellite
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	satellite4 - satellite
	instrument9 - instrument
	instrument10 - instrument
	satellite5 - satellite
	instrument11 - instrument
	instrument12 - instrument
	spectrograph0 - mode
	spectrograph2 - mode
	infrared3 - mode
	spectrograph1 - mode
	thermograph4 - mode
	GroundStation12 - direction
	GroundStation24 - direction
	GroundStation44 - direction
	Star47 - direction
	Star35 - direction
	Star11 - direction
	Star23 - direction
	GroundStation49 - direction
	GroundStation2 - direction
	GroundStation9 - direction
	GroundStation16 - direction
	Star56 - direction
	GroundStation14 - direction
	GroundStation51 - direction
	GroundStation18 - direction
	Star53 - direction
	GroundStation5 - direction
	Star29 - direction
	GroundStation4 - direction
	Star1 - direction
	Star13 - direction
	Star8 - direction
	Star30 - direction
	Star32 - direction
	Star15 - direction
	GroundStation36 - direction
	GroundStation57 - direction
	Star45 - direction
	Star0 - direction
	Star59 - direction
	Star54 - direction
	GroundStation34 - direction
	GroundStation31 - direction
	Star50 - direction
	Star40 - direction
	Star38 - direction
	GroundStation27 - direction
	Star7 - direction
	Star43 - direction
	Star19 - direction
	GroundStation33 - direction
	GroundStation46 - direction
	Star58 - direction
	GroundStation17 - direction
	GroundStation48 - direction
	GroundStation28 - direction
	GroundStation21 - direction
	Star52 - direction
	GroundStation3 - direction
	Star20 - direction
	GroundStation22 - direction
	GroundStation26 - direction
	Star39 - direction
	Star10 - direction
	Star55 - direction
	GroundStation42 - direction
	Star41 - direction
	Star25 - direction
	Star6 - direction
	GroundStation37 - direction
	Phenomenon60 - direction
	Planet61 - direction
	Star62 - direction
	Planet63 - direction
	Phenomenon64 - direction
	Star65 - direction
	Star66 - direction
	Planet67 - direction
	Phenomenon68 - direction
	Phenomenon69 - direction
	Star70 - direction
	Planet71 - direction
	Phenomenon72 - direction
	Planet73 - direction
	Phenomenon74 - direction
	Phenomenon75 - direction
	Planet76 - direction
	Phenomenon77 - direction
	Phenomenon78 - direction
	Planet79 - direction
	Planet80 - direction
	Phenomenon81 - direction
	Star82 - direction
	Planet83 - direction
	Star84 - direction
	Phenomenon85 - direction
	Phenomenon86 - direction
	Star87 - direction
	Phenomenon88 - direction
	Planet89 - direction
	Star90 - direction
	Phenomenon91 - direction
	Planet92 - direction
	Star93 - direction
	Phenomenon94 - direction
	Star95 - direction
	Star96 - direction
	Star97 - direction
	Star98 - direction
	Planet99 - direction
	Planet100 - direction
	Planet101 - direction
	Planet102 - direction
	Star103 - direction
	Phenomenon104 - direction
)
(:init
	(supports instrument0 thermograph4)
	(supports instrument0 spectrograph0)
	(supports instrument0 infrared3)
	(calibration_target instrument0 GroundStation9)
	(calibration_target instrument0 GroundStation21)
	(on_board instrument0 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star70)
	(supports instrument1 spectrograph1)
	(calibration_target instrument1 GroundStation34)
	(calibration_target instrument1 Star39)
	(calibration_target instrument1 Star50)
	(calibration_target instrument1 GroundStation42)
	(calibration_target instrument1 Star15)
	(calibration_target instrument1 GroundStation24)
	(calibration_target instrument1 GroundStation57)
	(calibration_target instrument1 Star55)
	(calibration_target instrument1 Star40)
	(calibration_target instrument1 Star7)
	(calibration_target instrument1 GroundStation48)
	(calibration_target instrument1 Star45)
	(calibration_target instrument1 Star54)
	(calibration_target instrument1 GroundStation9)
	(calibration_target instrument1 Star1)
	(calibration_target instrument1 Star30)
	(calibration_target instrument1 GroundStation4)
	(calibration_target instrument1 GroundStation12)
	(calibration_target instrument1 Star53)
	(on_board instrument1 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation16)
	(supports instrument2 infrared3)
	(supports instrument2 spectrograph0)
	(calibration_target instrument2 Star20)
	(calibration_target instrument2 GroundStation9)
	(calibration_target instrument2 Star10)
	(calibration_target instrument2 Star19)
	(calibration_target instrument2 GroundStation36)
	(calibration_target instrument2 GroundStation27)
	(calibration_target instrument2 Star6)
	(calibration_target instrument2 GroundStation48)
	(calibration_target instrument2 Star0)
	(calibration_target instrument2 GroundStation2)
	(calibration_target instrument2 GroundStation44)
	(calibration_target instrument2 Star54)
	(calibration_target instrument2 Star55)
	(calibration_target instrument2 Star53)
	(supports instrument3 thermograph4)
	(supports instrument3 infrared3)
	(calibration_target instrument3 Star13)
	(calibration_target instrument3 GroundStation48)
	(calibration_target instrument3 GroundStation9)
	(calibration_target instrument3 Star58)
	(calibration_target instrument3 Star23)
	(calibration_target instrument3 Star11)
	(calibration_target instrument3 Star35)
	(calibration_target instrument3 GroundStation26)
	(calibration_target instrument3 GroundStation14)
	(calibration_target instrument3 GroundStation34)
	(calibration_target instrument3 Star19)
	(calibration_target instrument3 Star0)
	(calibration_target instrument3 GroundStation51)
	(calibration_target instrument3 GroundStation17)
	(calibration_target instrument3 Star47)
	(calibration_target instrument3 GroundStation3)
	(on_board instrument2 satellite2)
	(on_board instrument3 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star53)
	(supports instrument4 infrared3)
	(calibration_target instrument4 Star32)
	(calibration_target instrument4 GroundStation16)
	(calibration_target instrument4 GroundStation14)
	(calibration_target instrument4 Star50)
	(calibration_target instrument4 GroundStation22)
	(calibration_target instrument4 Star10)
	(calibration_target instrument4 Star7)
	(calibration_target instrument4 GroundStation57)
	(calibration_target instrument4 GroundStation26)
	(calibration_target instrument4 GroundStation42)
	(calibration_target instrument4 Star41)
	(calibration_target instrument4 GroundStation2)
	(calibration_target instrument4 GroundStation49)
	(calibration_target instrument4 GroundStation28)
	(calibration_target instrument4 GroundStation21)
	(calibration_target instrument4 Star29)
	(supports instrument5 spectrograph1)
	(supports instrument5 infrared3)
	(calibration_target instrument5 Star10)
	(calibration_target instrument5 Star54)
	(calibration_target instrument5 GroundStation16)
	(calibration_target instrument5 GroundStation21)
	(calibration_target instrument5 GroundStation22)
	(calibration_target instrument5 Star52)
	(calibration_target instrument5 Star53)
	(calibration_target instrument5 Star56)
	(calibration_target instrument5 Star1)
	(calibration_target instrument5 GroundStation9)
	(calibration_target instrument5 Star40)
	(supports instrument6 thermograph4)
	(supports instrument6 infrared3)
	(calibration_target instrument6 GroundStation18)
	(calibration_target instrument6 GroundStation37)
	(calibration_target instrument6 Star38)
	(calibration_target instrument6 GroundStation5)
	(calibration_target instrument6 Star29)
	(calibration_target instrument6 Star8)
	(calibration_target instrument6 GroundStation51)
	(calibration_target instrument6 GroundStation28)
	(calibration_target instrument6 Star32)
	(calibration_target instrument6 Star20)
	(calibration_target instrument6 GroundStation14)
	(calibration_target instrument6 Star30)
	(calibration_target instrument6 Star58)
	(calibration_target instrument6 GroundStation33)
	(calibration_target instrument6 GroundStation22)
	(calibration_target instrument6 Star56)
	(calibration_target instrument6 Star1)
	(calibration_target instrument6 GroundStation21)
	(supports instrument7 spectrograph2)
	(supports instrument7 thermograph4)
	(calibration_target instrument7 GroundStation34)
	(calibration_target instrument7 Star53)
	(calibration_target instrument7 Star13)
	(calibration_target instrument7 Star29)
	(calibration_target instrument7 Star54)
	(calibration_target instrument7 GroundStation17)
	(supports instrument8 infrared3)
	(supports instrument8 spectrograph1)
	(supports instrument8 thermograph4)
	(calibration_target instrument8 GroundStation3)
	(calibration_target instrument8 GroundStation4)
	(calibration_target instrument8 Star29)
	(calibration_target instrument8 GroundStation5)
	(calibration_target instrument8 GroundStation26)
	(calibration_target instrument8 Star7)
	(calibration_target instrument8 GroundStation57)
	(calibration_target instrument8 Star54)
	(calibration_target instrument8 Star59)
	(on_board instrument4 satellite3)
	(on_board instrument5 satellite3)
	(on_board instrument6 satellite3)
	(on_board instrument7 satellite3)
	(on_board instrument8 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation31)
	(supports instrument9 thermograph4)
	(calibration_target instrument9 Star58)
	(calibration_target instrument9 Star45)
	(calibration_target instrument9 Star6)
	(calibration_target instrument9 GroundStation57)
	(calibration_target instrument9 GroundStation36)
	(calibration_target instrument9 Star15)
	(calibration_target instrument9 Star38)
	(calibration_target instrument9 Star32)
	(calibration_target instrument9 Star30)
	(calibration_target instrument9 Star19)
	(calibration_target instrument9 GroundStation33)
	(calibration_target instrument9 Star8)
	(calibration_target instrument9 GroundStation3)
	(calibration_target instrument9 Star25)
	(calibration_target instrument9 Star13)
	(calibration_target instrument9 Star1)
	(supports instrument10 spectrograph2)
	(calibration_target instrument10 Star40)
	(calibration_target instrument10 Star20)
	(calibration_target instrument10 Star50)
	(calibration_target instrument10 GroundStation31)
	(calibration_target instrument10 Star55)
	(calibration_target instrument10 GroundStation34)
	(calibration_target instrument10 Star7)
	(calibration_target instrument10 GroundStation33)
	(calibration_target instrument10 GroundStation17)
	(calibration_target instrument10 Star54)
	(calibration_target instrument10 Star59)
	(calibration_target instrument10 Star0)
	(on_board instrument9 satellite4)
	(on_board instrument10 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Phenomenon78)
	(supports instrument11 spectrograph1)
	(calibration_target instrument11 GroundStation21)
	(calibration_target instrument11 GroundStation28)
	(calibration_target instrument11 Star52)
	(calibration_target instrument11 Star20)
	(calibration_target instrument11 GroundStation48)
	(calibration_target instrument11 GroundStation17)
	(calibration_target instrument11 Star25)
	(calibration_target instrument11 Star58)
	(calibration_target instrument11 GroundStation46)
	(calibration_target instrument11 GroundStation33)
	(calibration_target instrument11 Star19)
	(calibration_target instrument11 Star43)
	(calibration_target instrument11 Star7)
	(calibration_target instrument11 GroundStation27)
	(calibration_target instrument11 Star38)
	(supports instrument12 spectrograph2)
	(calibration_target instrument12 GroundStation37)
	(calibration_target instrument12 Star6)
	(calibration_target instrument12 Star25)
	(calibration_target instrument12 Star41)
	(calibration_target instrument12 GroundStation42)
	(calibration_target instrument12 Star55)
	(calibration_target instrument12 Star10)
	(calibration_target instrument12 Star39)
	(calibration_target instrument12 GroundStation26)
	(calibration_target instrument12 GroundStation22)
	(calibration_target instrument12 Star20)
	(calibration_target instrument12 GroundStation3)
	(calibration_target instrument12 Star52)
	(calibration_target instrument12 GroundStation21)
	(on_board instrument11 satellite5)
	(on_board instrument12 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star54)
)
(:goal (and
	(pointing satellite0 Phenomenon72)
	(pointing satellite3 GroundStation44)
	(have_image Phenomenon60 spectrograph2)
	(have_image Planet61 infrared3)
	(have_image Star62 spectrograph0)
	(have_image Planet63 infrared3)
	(have_image Phenomenon64 infrared3)
	(have_image Star65 thermograph4)
	(have_image Star66 spectrograph1)
	(have_image Planet67 thermograph4)
	(have_image Phenomenon68 infrared3)
	(have_image Phenomenon69 spectrograph1)
	(have_image Star70 spectrograph1)
	(have_image Planet71 thermograph4)
	(have_image Phenomenon72 infrared3)
	(have_image Planet73 infrared3)
	(have_image Phenomenon74 thermograph4)
	(have_image Phenomenon75 spectrograph2)
	(have_image Planet76 spectrograph0)
	(have_image Phenomenon77 spectrograph0)
	(have_image Phenomenon78 spectrograph1)
	(have_image Planet79 spectrograph1)
	(have_image Planet80 spectrograph0)
	(have_image Phenomenon81 spectrograph1)
	(have_image Star82 spectrograph2)
	(have_image Planet83 spectrograph0)
	(have_image Star84 infrared3)
	(have_image Phenomenon85 spectrograph0)
	(have_image Phenomenon86 thermograph4)
	(have_image Star87 spectrograph1)
	(have_image Phenomenon88 spectrograph1)
	(have_image Planet89 thermograph4)
	(have_image Star90 thermograph4)
	(have_image Phenomenon91 spectrograph1)
	(have_image Planet92 infrared3)
	(have_image Star93 spectrograph0)
	(have_image Phenomenon94 spectrograph1)
	(have_image Star95 infrared3)
	(have_image Star96 spectrograph2)
	(have_image Star97 thermograph4)
	(have_image Star98 spectrograph1)
	(have_image Planet99 thermograph4)
	(have_image Planet100 spectrograph2)
	(have_image Planet101 spectrograph0)
	(have_image Planet102 infrared3)
	(have_image Star103 spectrograph2)
	(have_image Phenomenon104 spectrograph2)
))

)
