(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	satellite1 - satellite
	instrument5 - instrument
	instrument6 - instrument
	satellite2 - satellite
	instrument7 - instrument
	satellite3 - satellite
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	satellite4 - satellite
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	satellite5 - satellite
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	satellite6 - satellite
	instrument20 - instrument
	instrument21 - instrument
	image1 - mode
	thermograph2 - mode
	thermograph4 - mode
	thermograph3 - mode
	thermograph0 - mode
	Star28 - direction
	GroundStation55 - direction
	Star51 - direction
	GroundStation68 - direction
	GroundStation76 - direction
	GroundStation11 - direction
	GroundStation38 - direction
	GroundStation5 - direction
	GroundStation24 - direction
	Star40 - direction
	GroundStation69 - direction
	Star23 - direction
	Star35 - direction
	GroundStation58 - direction
	Star74 - direction
	Star29 - direction
	Star1 - direction
	Star27 - direction
	GroundStation42 - direction
	Star8 - direction
	GroundStation44 - direction
	Star39 - direction
	Star65 - direction
	GroundStation48 - direction
	GroundStation50 - direction
	GroundStation15 - direction
	GroundStation47 - direction
	Star18 - direction
	GroundStation66 - direction
	GroundStation62 - direction
	Star45 - direction
	Star72 - direction
	Star22 - direction
	Star4 - direction
	Star54 - direction
	Star30 - direction
	Star77 - direction
	Star56 - direction
	Star36 - direction
	GroundStation73 - direction
	GroundStation60 - direction
	GroundStation79 - direction
	GroundStation70 - direction
	Star63 - direction
	Star53 - direction
	GroundStation6 - direction
	Star34 - direction
	GroundStation71 - direction
	GroundStation16 - direction
	Star17 - direction
	Star20 - direction
	GroundStation43 - direction
	Star3 - direction
	Star32 - direction
	GroundStation7 - direction
	Star0 - direction
	GroundStation31 - direction
	GroundStation61 - direction
	Star67 - direction
	Star37 - direction
	Star9 - direction
	Star25 - direction
	GroundStation33 - direction
	GroundStation13 - direction
	GroundStation41 - direction
	GroundStation12 - direction
	GroundStation14 - direction
	GroundStation10 - direction
	Star59 - direction
	Star26 - direction
	GroundStation2 - direction
	GroundStation46 - direction
	GroundStation21 - direction
	Star57 - direction
	Star64 - direction
	Star75 - direction
	GroundStation19 - direction
	Star49 - direction
	GroundStation52 - direction
	Star78 - direction
	Phenomenon80 - direction
	Star81 - direction
	Phenomenon82 - direction
	Star83 - direction
	Planet84 - direction
	Phenomenon85 - direction
	Star86 - direction
	Phenomenon87 - direction
	Planet88 - direction
	Star89 - direction
	Planet90 - direction
	Star91 - direction
	Planet92 - direction
	Star93 - direction
	Star94 - direction
	Planet95 - direction
	Star96 - direction
	Star97 - direction
	Phenomenon98 - direction
	Star99 - direction
	Phenomenon100 - direction
	Phenomenon101 - direction
	Phenomenon102 - direction
	Phenomenon103 - direction
	Planet104 - direction
	Phenomenon105 - direction
	Star106 - direction
	Star107 - direction
	Phenomenon108 - direction
	Phenomenon109 - direction
	Planet110 - direction
	Star111 - direction
	Planet112 - direction
	Planet113 - direction
	Planet114 - direction
	Planet115 - direction
	Star116 - direction
	Star117 - direction
	Star118 - direction
	Planet119 - direction
	Phenomenon120 - direction
	Phenomenon121 - direction
	Star122 - direction
	Phenomenon123 - direction
	Star124 - direction
	Phenomenon125 - direction
	Phenomenon126 - direction
	Star127 - direction
	Phenomenon128 - direction
	Phenomenon129 - direction
	Phenomenon130 - direction
	Star131 - direction
	Planet132 - direction
	Planet133 - direction
	Planet134 - direction
	Phenomenon135 - direction
	Planet136 - direction
	Star137 - direction
	Phenomenon138 - direction
	Phenomenon139 - direction
)
(:init
	(supports instrument0 thermograph4)
	(supports instrument0 image1)
	(calibration_target instrument0 GroundStation2)
	(calibration_target instrument0 GroundStation11)
	(supports instrument1 thermograph4)
	(supports instrument1 image1)
	(calibration_target instrument1 Star1)
	(calibration_target instrument1 Star35)
	(calibration_target instrument1 Star78)
	(calibration_target instrument1 Star22)
	(calibration_target instrument1 GroundStation62)
	(calibration_target instrument1 Star64)
	(supports instrument2 thermograph2)
	(supports instrument2 thermograph4)
	(calibration_target instrument2 GroundStation61)
	(calibration_target instrument2 Star65)
	(calibration_target instrument2 Star8)
	(calibration_target instrument2 GroundStation15)
	(calibration_target instrument2 Star27)
	(supports instrument3 thermograph4)
	(supports instrument3 thermograph2)
	(supports instrument3 thermograph0)
	(calibration_target instrument3 Star8)
	(calibration_target instrument3 GroundStation5)
	(calibration_target instrument3 GroundStation62)
	(calibration_target instrument3 Star23)
	(calibration_target instrument3 Star75)
	(calibration_target instrument3 GroundStation60)
	(calibration_target instrument3 Star40)
	(calibration_target instrument3 Star64)
	(calibration_target instrument3 Star51)
	(calibration_target instrument3 Star27)
	(calibration_target instrument3 Star9)
	(calibration_target instrument3 Star49)
	(calibration_target instrument3 GroundStation55)
	(calibration_target instrument3 Star25)
	(calibration_target instrument3 Star45)
	(calibration_target instrument3 Star72)
	(calibration_target instrument3 GroundStation15)
	(calibration_target instrument3 Star20)
	(calibration_target instrument3 GroundStation79)
	(calibration_target instrument3 GroundStation12)
	(calibration_target instrument3 GroundStation44)
	(calibration_target instrument3 GroundStation11)
	(calibration_target instrument3 Star30)
	(calibration_target instrument3 GroundStation71)
	(calibration_target instrument3 Star0)
	(supports instrument4 thermograph0)
	(calibration_target instrument4 Star22)
	(calibration_target instrument4 GroundStation46)
	(calibration_target instrument4 Star27)
	(calibration_target instrument4 Star64)
	(calibration_target instrument4 Star40)
	(calibration_target instrument4 Star77)
	(calibration_target instrument4 Star18)
	(calibration_target instrument4 Star17)
	(calibration_target instrument4 Star39)
	(calibration_target instrument4 GroundStation41)
	(calibration_target instrument4 GroundStation50)
	(calibration_target instrument4 Star49)
	(calibration_target instrument4 GroundStation71)
	(calibration_target instrument4 Star54)
	(calibration_target instrument4 GroundStation19)
	(calibration_target instrument4 GroundStation68)
	(calibration_target instrument4 GroundStation47)
	(calibration_target instrument4 Star75)
	(calibration_target instrument4 Star36)
	(calibration_target instrument4 GroundStation48)
	(calibration_target instrument4 Star34)
	(calibration_target instrument4 Star65)
	(calibration_target instrument4 Star35)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation76)
	(supports instrument5 thermograph0)
	(calibration_target instrument5 GroundStation7)
	(calibration_target instrument5 Star3)
	(calibration_target instrument5 Star77)
	(supports instrument6 thermograph4)
	(calibration_target instrument6 Star34)
	(calibration_target instrument6 GroundStation68)
	(calibration_target instrument6 GroundStation73)
	(calibration_target instrument6 Star20)
	(calibration_target instrument6 Star17)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation38)
	(supports instrument7 thermograph4)
	(supports instrument7 thermograph3)
	(supports instrument7 thermograph0)
	(calibration_target instrument7 Star57)
	(calibration_target instrument7 Star54)
	(calibration_target instrument7 Star27)
	(calibration_target instrument7 GroundStation44)
	(calibration_target instrument7 GroundStation11)
	(calibration_target instrument7 GroundStation12)
	(calibration_target instrument7 GroundStation15)
	(calibration_target instrument7 Star53)
	(calibration_target instrument7 Star35)
	(calibration_target instrument7 GroundStation38)
	(calibration_target instrument7 GroundStation10)
	(calibration_target instrument7 GroundStation14)
	(calibration_target instrument7 Star49)
	(calibration_target instrument7 GroundStation7)
	(calibration_target instrument7 Star3)
	(calibration_target instrument7 Star1)
	(calibration_target instrument7 Star56)
	(calibration_target instrument7 GroundStation33)
	(calibration_target instrument7 Star20)
	(calibration_target instrument7 Star30)
	(calibration_target instrument7 Star17)
	(calibration_target instrument7 GroundStation50)
	(calibration_target instrument7 GroundStation46)
	(calibration_target instrument7 Star29)
	(calibration_target instrument7 Star67)
	(on_board instrument7 satellite2)
	(power_avail satellite2)
	(pointing satellite2 GroundStation71)
	(supports instrument8 image1)
	(supports instrument8 thermograph4)
	(calibration_target instrument8 GroundStation43)
	(calibration_target instrument8 Star25)
	(calibration_target instrument8 Star1)
	(calibration_target instrument8 Star32)
	(calibration_target instrument8 GroundStation76)
	(calibration_target instrument8 GroundStation14)
	(calibration_target instrument8 Star39)
	(supports instrument9 image1)
	(supports instrument9 thermograph0)
	(supports instrument9 thermograph2)
	(calibration_target instrument9 Star78)
	(calibration_target instrument9 Star0)
	(calibration_target instrument9 Star8)
	(calibration_target instrument9 GroundStation15)
	(calibration_target instrument9 Star59)
	(calibration_target instrument9 Star49)
	(supports instrument10 thermograph4)
	(supports instrument10 thermograph3)
	(supports instrument10 thermograph2)
	(calibration_target instrument10 GroundStation24)
	(calibration_target instrument10 Star20)
	(calibration_target instrument10 GroundStation61)
	(calibration_target instrument10 Star74)
	(calibration_target instrument10 GroundStation5)
	(calibration_target instrument10 GroundStation73)
	(calibration_target instrument10 GroundStation38)
	(calibration_target instrument10 GroundStation69)
	(calibration_target instrument10 GroundStation66)
	(calibration_target instrument10 Star40)
	(calibration_target instrument10 Star37)
	(calibration_target instrument10 GroundStation7)
	(calibration_target instrument10 GroundStation11)
	(calibration_target instrument10 Star23)
	(calibration_target instrument10 Star59)
	(calibration_target instrument10 GroundStation6)
	(supports instrument11 image1)
	(supports instrument11 thermograph3)
	(supports instrument11 thermograph0)
	(calibration_target instrument11 GroundStation71)
	(calibration_target instrument11 Star56)
	(calibration_target instrument11 Star4)
	(calibration_target instrument11 Star59)
	(calibration_target instrument11 Star39)
	(calibration_target instrument11 Star32)
	(calibration_target instrument11 GroundStation10)
	(calibration_target instrument11 Star20)
	(calibration_target instrument11 GroundStation44)
	(calibration_target instrument11 Star3)
	(calibration_target instrument11 Star25)
	(calibration_target instrument11 GroundStation19)
	(calibration_target instrument11 Star0)
	(calibration_target instrument11 Star45)
	(calibration_target instrument11 Star40)
	(calibration_target instrument11 Star74)
	(calibration_target instrument11 GroundStation66)
	(calibration_target instrument11 Star63)
	(calibration_target instrument11 GroundStation42)
	(calibration_target instrument11 GroundStation16)
	(calibration_target instrument11 Star22)
	(calibration_target instrument11 GroundStation33)
	(supports instrument12 thermograph4)
	(calibration_target instrument12 GroundStation21)
	(calibration_target instrument12 GroundStation12)
	(calibration_target instrument12 Star49)
	(calibration_target instrument12 GroundStation31)
	(calibration_target instrument12 GroundStation19)
	(calibration_target instrument12 GroundStation79)
	(calibration_target instrument12 Star35)
	(calibration_target instrument12 Star23)
	(calibration_target instrument12 GroundStation33)
	(calibration_target instrument12 GroundStation48)
	(calibration_target instrument12 Star77)
	(calibration_target instrument12 GroundStation69)
	(on_board instrument8 satellite3)
	(on_board instrument9 satellite3)
	(on_board instrument10 satellite3)
	(on_board instrument11 satellite3)
	(on_board instrument12 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Planet92)
	(supports instrument13 image1)
	(supports instrument13 thermograph0)
	(calibration_target instrument13 GroundStation6)
	(calibration_target instrument13 Star53)
	(calibration_target instrument13 GroundStation71)
	(calibration_target instrument13 GroundStation70)
	(calibration_target instrument13 GroundStation2)
	(calibration_target instrument13 GroundStation52)
	(calibration_target instrument13 Star57)
	(calibration_target instrument13 Star25)
	(calibration_target instrument13 Star74)
	(calibration_target instrument13 Star3)
	(calibration_target instrument13 GroundStation58)
	(calibration_target instrument13 Star72)
	(supports instrument14 thermograph3)
	(supports instrument14 image1)
	(supports instrument14 thermograph2)
	(calibration_target instrument14 Star64)
	(calibration_target instrument14 GroundStation66)
	(calibration_target instrument14 GroundStation73)
	(calibration_target instrument14 Star63)
	(calibration_target instrument14 Star8)
	(calibration_target instrument14 GroundStation42)
	(calibration_target instrument14 Star32)
	(calibration_target instrument14 GroundStation7)
	(calibration_target instrument14 Star25)
	(calibration_target instrument14 Star27)
	(calibration_target instrument14 GroundStation60)
	(calibration_target instrument14 GroundStation10)
	(calibration_target instrument14 Star1)
	(calibration_target instrument14 GroundStation47)
	(calibration_target instrument14 Star29)
	(calibration_target instrument14 Star22)
	(calibration_target instrument14 GroundStation41)
	(calibration_target instrument14 GroundStation13)
	(calibration_target instrument14 GroundStation62)
	(calibration_target instrument14 Star54)
	(calibration_target instrument14 Star75)
	(calibration_target instrument14 Star17)
	(calibration_target instrument14 GroundStation46)
	(calibration_target instrument14 Star0)
	(calibration_target instrument14 Star78)
	(supports instrument15 thermograph2)
	(supports instrument15 thermograph4)
	(calibration_target instrument15 GroundStation7)
	(calibration_target instrument15 GroundStation48)
	(calibration_target instrument15 Star26)
	(calibration_target instrument15 Star67)
	(calibration_target instrument15 Star65)
	(calibration_target instrument15 Star20)
	(calibration_target instrument15 GroundStation79)
	(calibration_target instrument15 GroundStation71)
	(calibration_target instrument15 GroundStation47)
	(calibration_target instrument15 Star39)
	(calibration_target instrument15 Star78)
	(calibration_target instrument15 GroundStation60)
	(calibration_target instrument15 GroundStation52)
	(calibration_target instrument15 Star37)
	(calibration_target instrument15 GroundStation12)
	(calibration_target instrument15 GroundStation44)
	(supports instrument16 image1)
	(calibration_target instrument16 Star30)
	(calibration_target instrument16 Star54)
	(calibration_target instrument16 Star4)
	(calibration_target instrument16 GroundStation73)
	(calibration_target instrument16 GroundStation21)
	(calibration_target instrument16 Star22)
	(calibration_target instrument16 Star72)
	(calibration_target instrument16 Star45)
	(calibration_target instrument16 GroundStation16)
	(calibration_target instrument16 GroundStation10)
	(calibration_target instrument16 Star37)
	(calibration_target instrument16 GroundStation62)
	(calibration_target instrument16 GroundStation33)
	(calibration_target instrument16 Star59)
	(calibration_target instrument16 GroundStation66)
	(calibration_target instrument16 Star34)
	(calibration_target instrument16 Star18)
	(calibration_target instrument16 GroundStation47)
	(calibration_target instrument16 GroundStation15)
	(calibration_target instrument16 Star25)
	(calibration_target instrument16 GroundStation50)
	(calibration_target instrument16 Star0)
	(on_board instrument13 satellite4)
	(on_board instrument14 satellite4)
	(on_board instrument15 satellite4)
	(on_board instrument16 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Planet95)
	(supports instrument17 image1)
	(supports instrument17 thermograph4)
	(calibration_target instrument17 Star3)
	(calibration_target instrument17 GroundStation6)
	(calibration_target instrument17 Star56)
	(calibration_target instrument17 Star53)
	(calibration_target instrument17 Star77)
	(supports instrument18 thermograph4)
	(supports instrument18 thermograph0)
	(supports instrument18 thermograph3)
	(calibration_target instrument18 Star57)
	(calibration_target instrument18 GroundStation10)
	(calibration_target instrument18 GroundStation60)
	(calibration_target instrument18 Star56)
	(calibration_target instrument18 Star53)
	(supports instrument19 image1)
	(supports instrument19 thermograph2)
	(calibration_target instrument19 GroundStation6)
	(calibration_target instrument19 Star49)
	(calibration_target instrument19 Star53)
	(calibration_target instrument19 GroundStation2)
	(calibration_target instrument19 Star63)
	(calibration_target instrument19 GroundStation70)
	(calibration_target instrument19 Star78)
	(calibration_target instrument19 Star3)
	(calibration_target instrument19 GroundStation79)
	(calibration_target instrument19 Star25)
	(calibration_target instrument19 GroundStation31)
	(calibration_target instrument19 GroundStation60)
	(calibration_target instrument19 GroundStation71)
	(calibration_target instrument19 GroundStation73)
	(calibration_target instrument19 GroundStation61)
	(calibration_target instrument19 Star20)
	(calibration_target instrument19 Star36)
	(on_board instrument17 satellite5)
	(on_board instrument18 satellite5)
	(on_board instrument19 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Phenomenon105)
	(supports instrument20 thermograph2)
	(supports instrument20 image1)
	(calibration_target instrument20 GroundStation31)
	(calibration_target instrument20 Star0)
	(calibration_target instrument20 GroundStation7)
	(calibration_target instrument20 Star32)
	(calibration_target instrument20 Star3)
	(calibration_target instrument20 GroundStation43)
	(calibration_target instrument20 Star20)
	(calibration_target instrument20 Star17)
	(calibration_target instrument20 Star25)
	(calibration_target instrument20 GroundStation16)
	(calibration_target instrument20 GroundStation71)
	(calibration_target instrument20 Star34)
	(supports instrument21 image1)
	(calibration_target instrument21 Star78)
	(calibration_target instrument21 GroundStation52)
	(calibration_target instrument21 Star49)
	(calibration_target instrument21 GroundStation19)
	(calibration_target instrument21 Star75)
	(calibration_target instrument21 Star64)
	(calibration_target instrument21 Star57)
	(calibration_target instrument21 GroundStation21)
	(calibration_target instrument21 GroundStation46)
	(calibration_target instrument21 GroundStation2)
	(calibration_target instrument21 Star26)
	(calibration_target instrument21 Star59)
	(calibration_target instrument21 GroundStation10)
	(calibration_target instrument21 GroundStation14)
	(calibration_target instrument21 GroundStation12)
	(calibration_target instrument21 GroundStation41)
	(calibration_target instrument21 GroundStation13)
	(calibration_target instrument21 GroundStation33)
	(calibration_target instrument21 Star25)
	(calibration_target instrument21 Star9)
	(calibration_target instrument21 Star37)
	(calibration_target instrument21 Star67)
	(calibration_target instrument21 GroundStation61)
	(on_board instrument20 satellite6)
	(on_board instrument21 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star1)
)
(:goal (and
	(pointing satellite2 Star106)
	(pointing satellite3 Planet134)
	(pointing satellite4 Star97)
	(pointing satellite5 Star0)
	(pointing satellite6 Star30)
	(have_image Phenomenon80 image1)
	(have_image Star81 thermograph0)
	(have_image Phenomenon82 image1)
	(have_image Star83 thermograph3)
	(have_image Planet84 thermograph3)
	(have_image Phenomenon85 thermograph0)
	(have_image Star86 thermograph2)
	(have_image Phenomenon87 thermograph0)
	(have_image Planet88 thermograph2)
	(have_image Star89 thermograph3)
	(have_image Planet90 thermograph3)
	(have_image Star91 image1)
	(have_image Planet92 thermograph2)
	(have_image Star93 thermograph3)
	(have_image Star94 thermograph0)
	(have_image Planet95 image1)
	(have_image Star96 image1)
	(have_image Star97 thermograph2)
	(have_image Phenomenon98 thermograph3)
	(have_image Star99 thermograph2)
	(have_image Phenomenon100 thermograph0)
	(have_image Phenomenon101 thermograph4)
	(have_image Phenomenon102 image1)
	(have_image Phenomenon103 thermograph3)
	(have_image Planet104 thermograph4)
	(have_image Phenomenon105 thermograph2)
	(have_image Star106 thermograph4)
	(have_image Star107 image1)
	(have_image Phenomenon108 thermograph4)
	(have_image Phenomenon109 thermograph3)
	(have_image Planet110 thermograph4)
	(have_image Star111 thermograph4)
	(have_image Planet112 image1)
	(have_image Planet113 thermograph4)
	(have_image Planet114 thermograph3)
	(have_image Planet115 thermograph2)
	(have_image Star116 thermograph3)
	(have_image Star117 thermograph3)
	(have_image Star118 thermograph2)
	(have_image Planet119 image1)
	(have_image Phenomenon120 thermograph2)
	(have_image Phenomenon121 thermograph4)
	(have_image Star122 thermograph3)
	(have_image Phenomenon123 thermograph2)
	(have_image Star124 thermograph2)
	(have_image Phenomenon125 thermograph2)
	(have_image Phenomenon126 image1)
	(have_image Star127 thermograph0)
	(have_image Phenomenon128 thermograph3)
	(have_image Phenomenon129 thermograph3)
	(have_image Phenomenon130 thermograph0)
	(have_image Star131 thermograph3)
	(have_image Planet132 thermograph3)
	(have_image Planet133 thermograph4)
	(have_image Planet134 image1)
	(have_image Phenomenon135 thermograph0)
	(have_image Planet136 image1)
	(have_image Star137 image1)
	(have_image Phenomenon138 image1)
	(have_image Phenomenon139 image1)
))

)
