(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	satellite1 - satellite
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	satellite2 - satellite
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	satellite3 - satellite
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	satellite4 - satellite
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	satellite5 - satellite
	instrument21 - instrument
	satellite6 - satellite
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	spectrograph0 - mode
	thermograph4 - mode
	infrared3 - mode
	spectrograph1 - mode
	spectrograph2 - mode
	GroundStation36 - direction
	Star40 - direction
	GroundStation61 - direction
	Star43 - direction
	Star23 - direction
	Star58 - direction
	GroundStation57 - direction
	GroundStation26 - direction
	GroundStation51 - direction
	GroundStation9 - direction
	Star8 - direction
	GroundStation12 - direction
	GroundStation69 - direction
	GroundStation65 - direction
	Star72 - direction
	Star71 - direction
	Star19 - direction
	GroundStation48 - direction
	Star20 - direction
	Star39 - direction
	GroundStation28 - direction
	GroundStation24 - direction
	GroundStation21 - direction
	GroundStation76 - direction
	Star60 - direction
	Star7 - direction
	Star53 - direction
	GroundStation14 - direction
	Star11 - direction
	GroundStation46 - direction
	Star25 - direction
	Star56 - direction
	GroundStation49 - direction
	Star50 - direction
	Star10 - direction
	GroundStation22 - direction
	GroundStation67 - direction
	Star35 - direction
	Star70 - direction
	Star77 - direction
	Star45 - direction
	Star32 - direction
	Star41 - direction
	GroundStation44 - direction
	GroundStation17 - direction
	Star52 - direction
	Star0 - direction
	GroundStation27 - direction
	GroundStation5 - direction
	Star13 - direction
	GroundStation3 - direction
	Star74 - direction
	GroundStation42 - direction
	GroundStation78 - direction
	Star1 - direction
	Star75 - direction
	GroundStation68 - direction
	GroundStation18 - direction
	Star55 - direction
	Star38 - direction
	GroundStation64 - direction
	Star59 - direction
	GroundStation31 - direction
	GroundStation2 - direction
	GroundStation37 - direction
	Star79 - direction
	Star29 - direction
	GroundStation16 - direction
	Star63 - direction
	Star15 - direction
	Star30 - direction
	GroundStation33 - direction
	Star73 - direction
	Star66 - direction
	Star6 - direction
	Star47 - direction
	Star54 - direction
	GroundStation34 - direction
	GroundStation4 - direction
	GroundStation62 - direction
	Star80 - direction
	Phenomenon81 - direction
	Planet82 - direction
	Star83 - direction
	Phenomenon84 - direction
	Planet85 - direction
	Star86 - direction
	Phenomenon87 - direction
	Star88 - direction
	Star89 - direction
	Phenomenon90 - direction
	Star91 - direction
	Phenomenon92 - direction
	Phenomenon93 - direction
	Planet94 - direction
	Planet95 - direction
	Phenomenon96 - direction
	Planet97 - direction
	Star98 - direction
	Planet99 - direction
	Planet100 - direction
	Phenomenon101 - direction
	Phenomenon102 - direction
	Planet103 - direction
	Star104 - direction
	Star105 - direction
	Planet106 - direction
	Star107 - direction
	Star108 - direction
	Planet109 - direction
	Phenomenon110 - direction
	Phenomenon111 - direction
	Planet112 - direction
	Planet113 - direction
	Planet114 - direction
	Phenomenon115 - direction
	Planet116 - direction
	Star117 - direction
	Star118 - direction
	Planet119 - direction
	Phenomenon120 - direction
	Phenomenon121 - direction
	Star122 - direction
	Star123 - direction
	Phenomenon124 - direction
	Phenomenon125 - direction
	Planet126 - direction
	Phenomenon127 - direction
	Star128 - direction
	Planet129 - direction
	Star130 - direction
	Phenomenon131 - direction
	Star132 - direction
	Phenomenon133 - direction
	Phenomenon134 - direction
	Planet135 - direction
	Star136 - direction
	Planet137 - direction
	Star138 - direction
	Star139 - direction
)
(:init
	(supports instrument0 spectrograph0)
	(supports instrument0 spectrograph1)
	(calibration_target instrument0 Star47)
	(calibration_target instrument0 Star66)
	(calibration_target instrument0 GroundStation64)
	(calibration_target instrument0 Star23)
	(calibration_target instrument0 GroundStation21)
	(calibration_target instrument0 Star72)
	(calibration_target instrument0 GroundStation69)
	(calibration_target instrument0 GroundStation46)
	(calibration_target instrument0 Star8)
	(calibration_target instrument0 GroundStation42)
	(calibration_target instrument0 Star73)
	(calibration_target instrument0 Star1)
	(calibration_target instrument0 GroundStation44)
	(calibration_target instrument0 GroundStation2)
	(calibration_target instrument0 GroundStation18)
	(calibration_target instrument0 GroundStation36)
	(calibration_target instrument0 Star52)
	(calibration_target instrument0 Star13)
	(calibration_target instrument0 Star38)
	(calibration_target instrument0 GroundStation51)
	(calibration_target instrument0 Star74)
	(calibration_target instrument0 GroundStation17)
	(calibration_target instrument0 Star32)
	(calibration_target instrument0 GroundStation61)
	(supports instrument1 spectrograph2)
	(calibration_target instrument1 GroundStation21)
	(calibration_target instrument1 Star50)
	(calibration_target instrument1 GroundStation78)
	(calibration_target instrument1 Star32)
	(calibration_target instrument1 Star72)
	(calibration_target instrument1 Star79)
	(calibration_target instrument1 GroundStation49)
	(supports instrument2 spectrograph1)
	(calibration_target instrument2 GroundStation33)
	(calibration_target instrument2 Star55)
	(calibration_target instrument2 Star29)
	(calibration_target instrument2 GroundStation78)
	(calibration_target instrument2 GroundStation48)
	(calibration_target instrument2 Star66)
	(calibration_target instrument2 GroundStation22)
	(calibration_target instrument2 Star45)
	(calibration_target instrument2 GroundStation18)
	(calibration_target instrument2 Star79)
	(calibration_target instrument2 GroundStation4)
	(calibration_target instrument2 GroundStation44)
	(calibration_target instrument2 GroundStation14)
	(calibration_target instrument2 GroundStation31)
	(calibration_target instrument2 Star13)
	(calibration_target instrument2 Star70)
	(calibration_target instrument2 Star50)
	(calibration_target instrument2 Star56)
	(supports instrument3 thermograph4)
	(calibration_target instrument3 Star56)
	(calibration_target instrument3 Star41)
	(calibration_target instrument3 Star60)
	(calibration_target instrument3 Star38)
	(calibration_target instrument3 GroundStation68)
	(calibration_target instrument3 Star23)
	(calibration_target instrument3 Star39)
	(calibration_target instrument3 GroundStation5)
	(calibration_target instrument3 GroundStation69)
	(calibration_target instrument3 GroundStation21)
	(supports instrument4 spectrograph0)
	(supports instrument4 thermograph4)
	(supports instrument4 spectrograph1)
	(calibration_target instrument4 Star56)
	(calibration_target instrument4 GroundStation9)
	(calibration_target instrument4 GroundStation14)
	(calibration_target instrument4 Star0)
	(calibration_target instrument4 Star77)
	(calibration_target instrument4 GroundStation16)
	(calibration_target instrument4 GroundStation22)
	(calibration_target instrument4 GroundStation4)
	(calibration_target instrument4 GroundStation51)
	(calibration_target instrument4 GroundStation62)
	(calibration_target instrument4 Star30)
	(calibration_target instrument4 GroundStation27)
	(calibration_target instrument4 Star32)
	(calibration_target instrument4 Star40)
	(calibration_target instrument4 GroundStation33)
	(calibration_target instrument4 Star75)
	(calibration_target instrument4 GroundStation48)
	(calibration_target instrument4 GroundStation34)
	(calibration_target instrument4 GroundStation12)
	(calibration_target instrument4 GroundStation44)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Phenomenon124)
	(supports instrument5 infrared3)
	(calibration_target instrument5 GroundStation22)
	(calibration_target instrument5 GroundStation64)
	(calibration_target instrument5 Star52)
	(calibration_target instrument5 Star13)
	(calibration_target instrument5 Star45)
	(calibration_target instrument5 GroundStation14)
	(calibration_target instrument5 GroundStation37)
	(calibration_target instrument5 Star74)
	(calibration_target instrument5 GroundStation34)
	(calibration_target instrument5 GroundStation68)
	(calibration_target instrument5 Star7)
	(calibration_target instrument5 GroundStation17)
	(calibration_target instrument5 Star58)
	(calibration_target instrument5 GroundStation48)
	(calibration_target instrument5 GroundStation69)
	(calibration_target instrument5 GroundStation12)
	(calibration_target instrument5 GroundStation9)
	(calibration_target instrument5 Star11)
	(calibration_target instrument5 GroundStation24)
	(calibration_target instrument5 GroundStation51)
	(calibration_target instrument5 GroundStation16)
	(calibration_target instrument5 GroundStation44)
	(calibration_target instrument5 Star10)
	(supports instrument6 spectrograph1)
	(supports instrument6 infrared3)
	(supports instrument6 spectrograph2)
	(calibration_target instrument6 GroundStation68)
	(calibration_target instrument6 GroundStation34)
	(calibration_target instrument6 Star71)
	(calibration_target instrument6 Star7)
	(calibration_target instrument6 Star19)
	(supports instrument7 spectrograph1)
	(supports instrument7 spectrograph0)
	(supports instrument7 infrared3)
	(calibration_target instrument7 Star32)
	(calibration_target instrument7 GroundStation34)
	(calibration_target instrument7 Star54)
	(calibration_target instrument7 GroundStation28)
	(calibration_target instrument7 GroundStation14)
	(calibration_target instrument7 Star43)
	(calibration_target instrument7 GroundStation27)
	(calibration_target instrument7 Star53)
	(calibration_target instrument7 GroundStation49)
	(calibration_target instrument7 Star13)
	(calibration_target instrument7 GroundStation3)
	(calibration_target instrument7 Star47)
	(calibration_target instrument7 GroundStation76)
	(calibration_target instrument7 Star19)
	(calibration_target instrument7 GroundStation78)
	(calibration_target instrument7 GroundStation31)
	(calibration_target instrument7 GroundStation48)
	(calibration_target instrument7 GroundStation46)
	(calibration_target instrument7 Star40)
	(calibration_target instrument7 GroundStation16)
	(calibration_target instrument7 Star70)
	(calibration_target instrument7 GroundStation2)
	(calibration_target instrument7 Star75)
	(supports instrument8 spectrograph0)
	(supports instrument8 infrared3)
	(calibration_target instrument8 Star38)
	(calibration_target instrument8 Star35)
	(calibration_target instrument8 Star0)
	(calibration_target instrument8 GroundStation49)
	(calibration_target instrument8 Star41)
	(calibration_target instrument8 GroundStation14)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(on_board instrument7 satellite1)
	(on_board instrument8 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star88)
	(supports instrument9 spectrograph0)
	(supports instrument9 infrared3)
	(supports instrument9 spectrograph1)
	(calibration_target instrument9 Star25)
	(calibration_target instrument9 Star7)
	(calibration_target instrument9 Star23)
	(calibration_target instrument9 Star70)
	(calibration_target instrument9 Star29)
	(calibration_target instrument9 GroundStation26)
	(calibration_target instrument9 GroundStation34)
	(calibration_target instrument9 GroundStation22)
	(calibration_target instrument9 GroundStation61)
	(calibration_target instrument9 GroundStation33)
	(calibration_target instrument9 Star58)
	(calibration_target instrument9 GroundStation9)
	(calibration_target instrument9 Star55)
	(calibration_target instrument9 GroundStation28)
	(calibration_target instrument9 GroundStation14)
	(calibration_target instrument9 GroundStation17)
	(calibration_target instrument9 Star73)
	(calibration_target instrument9 Star66)
	(calibration_target instrument9 Star0)
	(calibration_target instrument9 Star38)
	(calibration_target instrument9 GroundStation12)
	(calibration_target instrument9 Star40)
	(calibration_target instrument9 Star10)
	(calibration_target instrument9 GroundStation37)
	(supports instrument10 spectrograph1)
	(supports instrument10 spectrograph2)
	(supports instrument10 thermograph4)
	(calibration_target instrument10 Star0)
	(calibration_target instrument10 Star55)
	(calibration_target instrument10 Star1)
	(calibration_target instrument10 GroundStation9)
	(calibration_target instrument10 Star56)
	(calibration_target instrument10 GroundStation28)
	(calibration_target instrument10 GroundStation49)
	(calibration_target instrument10 Star19)
	(supports instrument11 thermograph4)
	(supports instrument11 spectrograph0)
	(calibration_target instrument11 Star8)
	(calibration_target instrument11 Star43)
	(calibration_target instrument11 Star19)
	(calibration_target instrument11 GroundStation37)
	(calibration_target instrument11 GroundStation5)
	(calibration_target instrument11 GroundStation62)
	(calibration_target instrument11 GroundStation2)
	(calibration_target instrument11 GroundStation61)
	(calibration_target instrument11 Star53)
	(calibration_target instrument11 Star73)
	(calibration_target instrument11 Star59)
	(calibration_target instrument11 GroundStation69)
	(calibration_target instrument11 GroundStation27)
	(calibration_target instrument11 GroundStation18)
	(calibration_target instrument11 Star39)
	(calibration_target instrument11 Star25)
	(calibration_target instrument11 Star20)
	(calibration_target instrument11 GroundStation49)
	(calibration_target instrument11 GroundStation16)
	(supports instrument12 spectrograph2)
	(supports instrument12 thermograph4)
	(calibration_target instrument12 Star56)
	(calibration_target instrument12 Star13)
	(calibration_target instrument12 Star7)
	(calibration_target instrument12 GroundStation61)
	(calibration_target instrument12 GroundStation64)
	(calibration_target instrument12 Star1)
	(calibration_target instrument12 Star25)
	(calibration_target instrument12 Star55)
	(calibration_target instrument12 GroundStation51)
	(calibration_target instrument12 Star71)
	(calibration_target instrument12 GroundStation34)
	(calibration_target instrument12 Star30)
	(calibration_target instrument12 Star6)
	(on_board instrument9 satellite2)
	(on_board instrument10 satellite2)
	(on_board instrument11 satellite2)
	(on_board instrument12 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Planet95)
	(supports instrument13 spectrograph2)
	(supports instrument13 thermograph4)
	(supports instrument13 spectrograph0)
	(calibration_target instrument13 Star20)
	(calibration_target instrument13 GroundStation64)
	(calibration_target instrument13 Star50)
	(calibration_target instrument13 GroundStation31)
	(calibration_target instrument13 Star60)
	(calibration_target instrument13 GroundStation21)
	(calibration_target instrument13 Star66)
	(calibration_target instrument13 GroundStation69)
	(calibration_target instrument13 GroundStation33)
	(calibration_target instrument13 GroundStation26)
	(calibration_target instrument13 Star77)
	(calibration_target instrument13 GroundStation5)
	(calibration_target instrument13 GroundStation68)
	(calibration_target instrument13 GroundStation49)
	(calibration_target instrument13 Star38)
	(calibration_target instrument13 GroundStation14)
	(calibration_target instrument13 Star8)
	(calibration_target instrument13 Star43)
	(calibration_target instrument13 Star58)
	(calibration_target instrument13 GroundStation42)
	(calibration_target instrument13 GroundStation9)
	(supports instrument14 spectrograph2)
	(calibration_target instrument14 Star56)
	(calibration_target instrument14 Star23)
	(calibration_target instrument14 Star66)
	(supports instrument15 spectrograph2)
	(calibration_target instrument15 GroundStation57)
	(calibration_target instrument15 Star38)
	(calibration_target instrument15 Star45)
	(calibration_target instrument15 GroundStation69)
	(calibration_target instrument15 Star58)
	(calibration_target instrument15 GroundStation31)
	(calibration_target instrument15 Star0)
	(calibration_target instrument15 Star73)
	(on_board instrument13 satellite3)
	(on_board instrument14 satellite3)
	(on_board instrument15 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation37)
	(supports instrument16 spectrograph0)
	(calibration_target instrument16 GroundStation78)
	(calibration_target instrument16 GroundStation2)
	(calibration_target instrument16 GroundStation51)
	(calibration_target instrument16 Star63)
	(calibration_target instrument16 GroundStation26)
	(calibration_target instrument16 Star25)
	(calibration_target instrument16 Star60)
	(calibration_target instrument16 GroundStation31)
	(calibration_target instrument16 GroundStation27)
	(calibration_target instrument16 Star30)
	(calibration_target instrument16 Star20)
	(calibration_target instrument16 Star73)
	(supports instrument17 infrared3)
	(supports instrument17 thermograph4)
	(supports instrument17 spectrograph0)
	(calibration_target instrument17 Star56)
	(calibration_target instrument17 Star10)
	(calibration_target instrument17 GroundStation5)
	(calibration_target instrument17 Star54)
	(calibration_target instrument17 Star73)
	(calibration_target instrument17 GroundStation33)
	(calibration_target instrument17 GroundStation65)
	(calibration_target instrument17 GroundStation62)
	(calibration_target instrument17 Star71)
	(calibration_target instrument17 Star63)
	(calibration_target instrument17 GroundStation31)
	(calibration_target instrument17 Star79)
	(calibration_target instrument17 Star0)
	(supports instrument18 spectrograph1)
	(calibration_target instrument18 Star10)
	(calibration_target instrument18 GroundStation14)
	(calibration_target instrument18 Star70)
	(calibration_target instrument18 GroundStation12)
	(calibration_target instrument18 Star35)
	(calibration_target instrument18 GroundStation49)
	(calibration_target instrument18 Star74)
	(calibration_target instrument18 GroundStation33)
	(calibration_target instrument18 Star77)
	(calibration_target instrument18 Star8)
	(calibration_target instrument18 Star55)
	(calibration_target instrument18 GroundStation42)
	(calibration_target instrument18 Star1)
	(calibration_target instrument18 GroundStation9)
	(calibration_target instrument18 Star29)
	(supports instrument19 spectrograph2)
	(calibration_target instrument19 Star38)
	(calibration_target instrument19 Star59)
	(calibration_target instrument19 GroundStation42)
	(calibration_target instrument19 Star52)
	(calibration_target instrument19 GroundStation68)
	(calibration_target instrument19 GroundStation5)
	(calibration_target instrument19 Star0)
	(calibration_target instrument19 GroundStation14)
	(calibration_target instrument19 GroundStation17)
	(calibration_target instrument19 Star32)
	(calibration_target instrument19 GroundStation21)
	(calibration_target instrument19 GroundStation65)
	(calibration_target instrument19 GroundStation69)
	(calibration_target instrument19 Star79)
	(calibration_target instrument19 Star7)
	(calibration_target instrument19 Star56)
	(supports instrument20 spectrograph1)
	(supports instrument20 infrared3)
	(supports instrument20 spectrograph0)
	(calibration_target instrument20 Star19)
	(calibration_target instrument20 GroundStation76)
	(calibration_target instrument20 GroundStation33)
	(calibration_target instrument20 Star25)
	(calibration_target instrument20 Star71)
	(calibration_target instrument20 Star30)
	(calibration_target instrument20 GroundStation67)
	(calibration_target instrument20 GroundStation37)
	(calibration_target instrument20 GroundStation17)
	(calibration_target instrument20 Star7)
	(calibration_target instrument20 GroundStation14)
	(calibration_target instrument20 GroundStation78)
	(calibration_target instrument20 Star72)
	(on_board instrument16 satellite4)
	(on_board instrument17 satellite4)
	(on_board instrument18 satellite4)
	(on_board instrument19 satellite4)
	(on_board instrument20 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Phenomenon134)
	(supports instrument21 thermograph4)
	(supports instrument21 infrared3)
	(calibration_target instrument21 GroundStation3)
	(calibration_target instrument21 Star30)
	(calibration_target instrument21 Star59)
	(calibration_target instrument21 GroundStation67)
	(calibration_target instrument21 GroundStation68)
	(calibration_target instrument21 Star45)
	(calibration_target instrument21 GroundStation76)
	(calibration_target instrument21 Star13)
	(calibration_target instrument21 GroundStation64)
	(calibration_target instrument21 GroundStation34)
	(calibration_target instrument21 Star52)
	(calibration_target instrument21 Star1)
	(calibration_target instrument21 GroundStation21)
	(calibration_target instrument21 GroundStation24)
	(calibration_target instrument21 GroundStation28)
	(calibration_target instrument21 Star73)
	(calibration_target instrument21 Star6)
	(calibration_target instrument21 Star39)
	(calibration_target instrument21 Star75)
	(calibration_target instrument21 GroundStation33)
	(calibration_target instrument21 Star25)
	(calibration_target instrument21 Star20)
	(calibration_target instrument21 Star66)
	(calibration_target instrument21 GroundStation14)
	(calibration_target instrument21 GroundStation48)
	(on_board instrument21 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Phenomenon96)
	(supports instrument22 infrared3)
	(supports instrument22 thermograph4)
	(supports instrument22 spectrograph0)
	(calibration_target instrument22 Star53)
	(calibration_target instrument22 Star30)
	(calibration_target instrument22 Star7)
	(calibration_target instrument22 Star60)
	(calibration_target instrument22 GroundStation62)
	(calibration_target instrument22 Star55)
	(calibration_target instrument22 Star63)
	(calibration_target instrument22 GroundStation67)
	(supports instrument23 infrared3)
	(supports instrument23 spectrograph2)
	(supports instrument23 spectrograph0)
	(calibration_target instrument23 Star50)
	(calibration_target instrument23 GroundStation42)
	(calibration_target instrument23 Star1)
	(calibration_target instrument23 GroundStation49)
	(calibration_target instrument23 Star32)
	(calibration_target instrument23 Star66)
	(calibration_target instrument23 GroundStation16)
	(calibration_target instrument23 Star0)
	(calibration_target instrument23 Star47)
	(calibration_target instrument23 Star56)
	(calibration_target instrument23 Star25)
	(calibration_target instrument23 GroundStation46)
	(calibration_target instrument23 Star11)
	(calibration_target instrument23 GroundStation67)
	(calibration_target instrument23 Star70)
	(calibration_target instrument23 Star79)
	(calibration_target instrument23 GroundStation27)
	(calibration_target instrument23 Star74)
	(calibration_target instrument23 GroundStation68)
	(calibration_target instrument23 Star59)
	(calibration_target instrument23 Star52)
	(calibration_target instrument23 Star55)
	(calibration_target instrument23 GroundStation14)
	(supports instrument24 spectrograph1)
	(supports instrument24 infrared3)
	(supports instrument24 spectrograph0)
	(calibration_target instrument24 Star63)
	(calibration_target instrument24 Star75)
	(calibration_target instrument24 Star13)
	(calibration_target instrument24 GroundStation5)
	(calibration_target instrument24 Star29)
	(calibration_target instrument24 GroundStation3)
	(calibration_target instrument24 GroundStation27)
	(calibration_target instrument24 Star0)
	(calibration_target instrument24 Star52)
	(calibration_target instrument24 GroundStation62)
	(calibration_target instrument24 GroundStation17)
	(calibration_target instrument24 GroundStation44)
	(calibration_target instrument24 Star41)
	(calibration_target instrument24 Star55)
	(calibration_target instrument24 Star59)
	(calibration_target instrument24 Star32)
	(calibration_target instrument24 Star45)
	(calibration_target instrument24 Star6)
	(calibration_target instrument24 Star77)
	(calibration_target instrument24 Star30)
	(calibration_target instrument24 Star70)
	(calibration_target instrument24 Star35)
	(calibration_target instrument24 GroundStation67)
	(calibration_target instrument24 GroundStation22)
	(calibration_target instrument24 GroundStation2)
	(calibration_target instrument24 Star10)
	(supports instrument25 spectrograph2)
	(calibration_target instrument25 GroundStation64)
	(calibration_target instrument25 Star1)
	(calibration_target instrument25 GroundStation78)
	(calibration_target instrument25 Star30)
	(calibration_target instrument25 Star59)
	(calibration_target instrument25 GroundStation42)
	(calibration_target instrument25 GroundStation4)
	(calibration_target instrument25 Star66)
	(calibration_target instrument25 Star74)
	(calibration_target instrument25 GroundStation3)
	(calibration_target instrument25 Star55)
	(calibration_target instrument25 GroundStation16)
	(supports instrument26 infrared3)
	(supports instrument26 spectrograph1)
	(calibration_target instrument26 GroundStation62)
	(calibration_target instrument26 GroundStation4)
	(calibration_target instrument26 GroundStation34)
	(calibration_target instrument26 Star54)
	(calibration_target instrument26 Star47)
	(calibration_target instrument26 Star6)
	(calibration_target instrument26 Star66)
	(calibration_target instrument26 Star73)
	(calibration_target instrument26 GroundStation33)
	(calibration_target instrument26 Star30)
	(calibration_target instrument26 Star15)
	(calibration_target instrument26 Star63)
	(calibration_target instrument26 GroundStation16)
	(calibration_target instrument26 Star29)
	(calibration_target instrument26 Star79)
	(calibration_target instrument26 GroundStation37)
	(calibration_target instrument26 GroundStation2)
	(calibration_target instrument26 GroundStation31)
	(calibration_target instrument26 Star59)
	(calibration_target instrument26 GroundStation64)
	(calibration_target instrument26 Star38)
	(calibration_target instrument26 Star55)
	(calibration_target instrument26 GroundStation18)
	(calibration_target instrument26 GroundStation68)
	(calibration_target instrument26 Star75)
	(on_board instrument22 satellite6)
	(on_board instrument23 satellite6)
	(on_board instrument24 satellite6)
	(on_board instrument25 satellite6)
	(on_board instrument26 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star139)
)
(:goal (and
	(pointing satellite0 Star132)
	(pointing satellite1 Star52)
	(pointing satellite2 Planet106)
	(pointing satellite3 GroundStation4)
	(have_image Star80 spectrograph2)
	(have_image Phenomenon81 infrared3)
	(have_image Planet82 thermograph4)
	(have_image Star83 spectrograph0)
	(have_image Phenomenon84 spectrograph2)
	(have_image Planet85 spectrograph2)
	(have_image Star86 thermograph4)
	(have_image Phenomenon87 thermograph4)
	(have_image Star88 infrared3)
	(have_image Star89 infrared3)
	(have_image Phenomenon90 spectrograph1)
	(have_image Star91 spectrograph0)
	(have_image Phenomenon92 thermograph4)
	(have_image Phenomenon93 thermograph4)
	(have_image Planet94 infrared3)
	(have_image Planet95 spectrograph1)
	(have_image Phenomenon96 infrared3)
	(have_image Planet97 infrared3)
	(have_image Star98 spectrograph0)
	(have_image Planet99 spectrograph0)
	(have_image Planet100 spectrograph0)
	(have_image Phenomenon101 infrared3)
	(have_image Phenomenon102 thermograph4)
	(have_image Planet103 spectrograph0)
	(have_image Star104 infrared3)
	(have_image Star105 spectrograph1)
	(have_image Planet106 thermograph4)
	(have_image Star107 spectrograph1)
	(have_image Star108 infrared3)
	(have_image Planet109 spectrograph2)
	(have_image Phenomenon110 spectrograph0)
	(have_image Phenomenon111 thermograph4)
	(have_image Planet112 spectrograph1)
	(have_image Planet113 thermograph4)
	(have_image Planet114 spectrograph2)
	(have_image Phenomenon115 spectrograph2)
	(have_image Planet116 spectrograph0)
	(have_image Star117 spectrograph2)
	(have_image Star118 spectrograph2)
	(have_image Planet119 spectrograph2)
	(have_image Phenomenon120 spectrograph2)
	(have_image Phenomenon121 infrared3)
	(have_image Star122 infrared3)
	(have_image Star123 spectrograph0)
	(have_image Phenomenon124 thermograph4)
	(have_image Phenomenon125 infrared3)
	(have_image Planet126 spectrograph0)
	(have_image Phenomenon127 infrared3)
	(have_image Star128 thermograph4)
	(have_image Planet129 spectrograph1)
	(have_image Star130 spectrograph0)
	(have_image Phenomenon131 spectrograph2)
	(have_image Star132 spectrograph1)
	(have_image Phenomenon133 spectrograph0)
	(have_image Phenomenon134 spectrograph2)
	(have_image Planet135 spectrograph2)
	(have_image Star136 spectrograph2)
	(have_image Planet137 spectrograph2)
	(have_image Star138 spectrograph1)
	(have_image Star139 thermograph4)
))

)
