(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	satellite1 - satellite
	instrument1 - instrument
	satellite2 - satellite
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	satellite3 - satellite
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	satellite4 - satellite
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	satellite5 - satellite
	instrument14 - instrument
	instrument15 - instrument
	satellite6 - satellite
	instrument16 - instrument
	instrument17 - instrument
	image0 - mode
	infrared3 - mode
	thermograph1 - mode
	infrared4 - mode
	spectrograph2 - mode
	Star13 - direction
	Star31 - direction
	GroundStation46 - direction
	Star67 - direction
	GroundStation77 - direction
	Star64 - direction
	Star4 - direction
	GroundStation61 - direction
	Star23 - direction
	GroundStation54 - direction
	Star33 - direction
	Star47 - direction
	GroundStation66 - direction
	GroundStation40 - direction
	GroundStation70 - direction
	GroundStation2 - direction
	Star57 - direction
	Star49 - direction
	GroundStation11 - direction
	GroundStation73 - direction
	Star44 - direction
	Star38 - direction
	Star55 - direction
	Star19 - direction
	Star51 - direction
	Star35 - direction
	Star30 - direction
	GroundStation76 - direction
	GroundStation36 - direction
	Star25 - direction
	GroundStation59 - direction
	GroundStation42 - direction
	GroundStation27 - direction
	GroundStation9 - direction
	GroundStation24 - direction
	Star72 - direction
	Star21 - direction
	GroundStation18 - direction
	Star3 - direction
	Star22 - direction
	GroundStation41 - direction
	GroundStation69 - direction
	GroundStation78 - direction
	GroundStation75 - direction
	Star60 - direction
	Star14 - direction
	Star39 - direction
	GroundStation43 - direction
	GroundStation6 - direction
	GroundStation50 - direction
	Star12 - direction
	GroundStation26 - direction
	Star56 - direction
	Star7 - direction
	GroundStation68 - direction
	Star32 - direction
	GroundStation8 - direction
	Star29 - direction
	GroundStation58 - direction
	Star79 - direction
	GroundStation48 - direction
	Star15 - direction
	GroundStation45 - direction
	GroundStation53 - direction
	GroundStation71 - direction
	GroundStation63 - direction
	Star16 - direction
	GroundStation0 - direction
	Star17 - direction
	GroundStation62 - direction
	GroundStation20 - direction
	GroundStation10 - direction
	Star52 - direction
	Star65 - direction
	GroundStation5 - direction
	GroundStation28 - direction
	GroundStation1 - direction
	GroundStation34 - direction
	GroundStation37 - direction
	GroundStation74 - direction
	Planet80 - direction
	Phenomenon81 - direction
	Planet82 - direction
	Planet83 - direction
	Phenomenon84 - direction
	Planet85 - direction
	Star86 - direction
	Planet87 - direction
	Phenomenon88 - direction
	Star89 - direction
	Star90 - direction
	Star91 - direction
	Planet92 - direction
	Phenomenon93 - direction
	Star94 - direction
	Planet95 - direction
	Planet96 - direction
	Planet97 - direction
	Planet98 - direction
	Star99 - direction
	Planet100 - direction
	Phenomenon101 - direction
	Star102 - direction
	Star103 - direction
	Phenomenon104 - direction
	Planet105 - direction
	Planet106 - direction
	Planet107 - direction
	Planet108 - direction
	Star109 - direction
	Phenomenon110 - direction
	Star111 - direction
	Planet112 - direction
	Planet113 - direction
	Star114 - direction
	Planet115 - direction
	Planet116 - direction
	Phenomenon117 - direction
	Phenomenon118 - direction
	Planet119 - direction
	Star120 - direction
	Star121 - direction
	Star122 - direction
	Phenomenon123 - direction
	Phenomenon124 - direction
	Phenomenon125 - direction
	Phenomenon126 - direction
	Phenomenon127 - direction
	Planet128 - direction
	Phenomenon129 - direction
	Planet130 - direction
	Phenomenon131 - direction
	Phenomenon132 - direction
	Phenomenon133 - direction
	Planet134 - direction
	Phenomenon135 - direction
	Star136 - direction
	Star137 - direction
	Phenomenon138 - direction
	Planet139 - direction
)
(:init
	(supports instrument0 image0)
	(supports instrument0 spectrograph2)
	(calibration_target instrument0 Star56)
	(calibration_target instrument0 Star57)
	(calibration_target instrument0 GroundStation28)
	(calibration_target instrument0 GroundStation24)
	(calibration_target instrument0 GroundStation63)
	(calibration_target instrument0 Star7)
	(calibration_target instrument0 GroundStation11)
	(calibration_target instrument0 Star44)
	(calibration_target instrument0 GroundStation68)
	(calibration_target instrument0 Star60)
	(calibration_target instrument0 Star12)
	(calibration_target instrument0 Star47)
	(calibration_target instrument0 Star55)
	(calibration_target instrument0 GroundStation77)
	(calibration_target instrument0 GroundStation62)
	(calibration_target instrument0 Star64)
	(calibration_target instrument0 GroundStation73)
	(calibration_target instrument0 GroundStation45)
	(calibration_target instrument0 GroundStation8)
	(calibration_target instrument0 GroundStation18)
	(calibration_target instrument0 GroundStation43)
	(calibration_target instrument0 GroundStation40)
	(calibration_target instrument0 Star33)
	(calibration_target instrument0 Star17)
	(on_board instrument0 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Planet106)
	(supports instrument1 image0)
	(supports instrument1 infrared3)
	(calibration_target instrument1 GroundStation58)
	(calibration_target instrument1 GroundStation45)
	(calibration_target instrument1 Star30)
	(calibration_target instrument1 GroundStation63)
	(calibration_target instrument1 Star64)
	(calibration_target instrument1 Star65)
	(calibration_target instrument1 GroundStation78)
	(calibration_target instrument1 GroundStation69)
	(calibration_target instrument1 GroundStation24)
	(calibration_target instrument1 GroundStation61)
	(on_board instrument1 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star29)
	(supports instrument2 image0)
	(calibration_target instrument2 Star72)
	(calibration_target instrument2 GroundStation50)
	(calibration_target instrument2 Star4)
	(calibration_target instrument2 Star56)
	(calibration_target instrument2 GroundStation42)
	(calibration_target instrument2 Star57)
	(calibration_target instrument2 Star49)
	(calibration_target instrument2 GroundStation9)
	(supports instrument3 image0)
	(supports instrument3 infrared4)
	(calibration_target instrument3 Star38)
	(calibration_target instrument3 GroundStation10)
	(calibration_target instrument3 GroundStation20)
	(calibration_target instrument3 Star51)
	(calibration_target instrument3 GroundStation69)
	(supports instrument4 infrared4)
	(supports instrument4 image0)
	(supports instrument4 infrared3)
	(calibration_target instrument4 Star35)
	(calibration_target instrument4 Star65)
	(calibration_target instrument4 Star3)
	(calibration_target instrument4 GroundStation54)
	(calibration_target instrument4 Star32)
	(calibration_target instrument4 GroundStation75)
	(calibration_target instrument4 GroundStation2)
	(calibration_target instrument4 Star7)
	(calibration_target instrument4 GroundStation1)
	(calibration_target instrument4 Star72)
	(calibration_target instrument4 Star60)
	(calibration_target instrument4 Star55)
	(calibration_target instrument4 GroundStation66)
	(calibration_target instrument4 GroundStation62)
	(calibration_target instrument4 GroundStation9)
	(calibration_target instrument4 GroundStation43)
	(supports instrument5 thermograph1)
	(supports instrument5 image0)
	(supports instrument5 spectrograph2)
	(calibration_target instrument5 Star51)
	(calibration_target instrument5 GroundStation69)
	(calibration_target instrument5 GroundStation45)
	(calibration_target instrument5 Star49)
	(calibration_target instrument5 GroundStation76)
	(calibration_target instrument5 GroundStation41)
	(calibration_target instrument5 Star14)
	(calibration_target instrument5 Star35)
	(calibration_target instrument5 Star21)
	(calibration_target instrument5 GroundStation78)
	(calibration_target instrument5 GroundStation2)
	(calibration_target instrument5 GroundStation0)
	(calibration_target instrument5 GroundStation59)
	(calibration_target instrument5 GroundStation36)
	(calibration_target instrument5 Star56)
	(calibration_target instrument5 Star3)
	(calibration_target instrument5 GroundStation5)
	(on_board instrument2 satellite2)
	(on_board instrument3 satellite2)
	(on_board instrument4 satellite2)
	(on_board instrument5 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Phenomenon138)
	(supports instrument6 spectrograph2)
	(calibration_target instrument6 GroundStation18)
	(calibration_target instrument6 GroundStation26)
	(calibration_target instrument6 GroundStation54)
	(calibration_target instrument6 GroundStation73)
	(calibration_target instrument6 Star23)
	(calibration_target instrument6 GroundStation50)
	(calibration_target instrument6 GroundStation20)
	(calibration_target instrument6 Star52)
	(calibration_target instrument6 GroundStation41)
	(calibration_target instrument6 GroundStation0)
	(calibration_target instrument6 Star12)
	(calibration_target instrument6 GroundStation61)
	(calibration_target instrument6 GroundStation63)
	(calibration_target instrument6 Star47)
	(calibration_target instrument6 GroundStation37)
	(calibration_target instrument6 GroundStation2)
	(calibration_target instrument6 GroundStation24)
	(calibration_target instrument6 GroundStation42)
	(calibration_target instrument6 GroundStation45)
	(calibration_target instrument6 GroundStation71)
	(calibration_target instrument6 GroundStation10)
	(supports instrument7 image0)
	(supports instrument7 spectrograph2)
	(calibration_target instrument7 GroundStation68)
	(calibration_target instrument7 GroundStation11)
	(calibration_target instrument7 Star79)
	(calibration_target instrument7 GroundStation40)
	(calibration_target instrument7 GroundStation36)
	(calibration_target instrument7 GroundStation2)
	(calibration_target instrument7 GroundStation6)
	(calibration_target instrument7 Star29)
	(calibration_target instrument7 Star21)
	(calibration_target instrument7 Star56)
	(calibration_target instrument7 GroundStation37)
	(calibration_target instrument7 GroundStation41)
	(calibration_target instrument7 Star35)
	(calibration_target instrument7 GroundStation59)
	(calibration_target instrument7 Star72)
	(calibration_target instrument7 GroundStation66)
	(calibration_target instrument7 Star47)
	(calibration_target instrument7 Star33)
	(calibration_target instrument7 Star22)
	(supports instrument8 infrared4)
	(supports instrument8 infrared3)
	(calibration_target instrument8 GroundStation34)
	(calibration_target instrument8 GroundStation20)
	(calibration_target instrument8 GroundStation2)
	(calibration_target instrument8 GroundStation24)
	(calibration_target instrument8 GroundStation70)
	(calibration_target instrument8 GroundStation26)
	(calibration_target instrument8 Star21)
	(calibration_target instrument8 GroundStation28)
	(on_board instrument6 satellite3)
	(on_board instrument7 satellite3)
	(on_board instrument8 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Planet92)
	(supports instrument9 image0)
	(supports instrument9 infrared3)
	(calibration_target instrument9 GroundStation34)
	(calibration_target instrument9 GroundStation37)
	(calibration_target instrument9 GroundStation6)
	(calibration_target instrument9 Star38)
	(calibration_target instrument9 GroundStation68)
	(calibration_target instrument9 GroundStation69)
	(calibration_target instrument9 Star44)
	(calibration_target instrument9 Star51)
	(calibration_target instrument9 GroundStation73)
	(calibration_target instrument9 GroundStation24)
	(calibration_target instrument9 GroundStation75)
	(calibration_target instrument9 GroundStation11)
	(calibration_target instrument9 Star19)
	(calibration_target instrument9 Star65)
	(calibration_target instrument9 Star60)
	(calibration_target instrument9 GroundStation63)
	(calibration_target instrument9 Star12)
	(calibration_target instrument9 GroundStation53)
	(calibration_target instrument9 Star49)
	(calibration_target instrument9 Star7)
	(calibration_target instrument9 Star35)
	(calibration_target instrument9 Star57)
	(supports instrument10 infrared3)
	(supports instrument10 spectrograph2)
	(calibration_target instrument10 Star51)
	(calibration_target instrument10 Star19)
	(calibration_target instrument10 GroundStation41)
	(calibration_target instrument10 GroundStation26)
	(calibration_target instrument10 Star17)
	(calibration_target instrument10 Star55)
	(supports instrument11 image0)
	(calibration_target instrument11 Star56)
	(calibration_target instrument11 Star65)
	(calibration_target instrument11 Star39)
	(calibration_target instrument11 GroundStation75)
	(calibration_target instrument11 Star29)
	(calibration_target instrument11 GroundStation69)
	(calibration_target instrument11 GroundStation59)
	(calibration_target instrument11 Star25)
	(calibration_target instrument11 GroundStation36)
	(calibration_target instrument11 Star12)
	(calibration_target instrument11 GroundStation0)
	(calibration_target instrument11 Star14)
	(calibration_target instrument11 GroundStation76)
	(calibration_target instrument11 Star30)
	(calibration_target instrument11 Star35)
	(supports instrument12 image0)
	(calibration_target instrument12 GroundStation50)
	(calibration_target instrument12 GroundStation24)
	(calibration_target instrument12 Star56)
	(calibration_target instrument12 GroundStation9)
	(calibration_target instrument12 GroundStation1)
	(calibration_target instrument12 GroundStation27)
	(calibration_target instrument12 GroundStation41)
	(calibration_target instrument12 GroundStation75)
	(calibration_target instrument12 Star79)
	(calibration_target instrument12 GroundStation8)
	(calibration_target instrument12 GroundStation42)
	(supports instrument13 thermograph1)
	(supports instrument13 spectrograph2)
	(supports instrument13 infrared3)
	(calibration_target instrument13 GroundStation41)
	(calibration_target instrument13 Star39)
	(calibration_target instrument13 Star32)
	(calibration_target instrument13 Star22)
	(calibration_target instrument13 Star3)
	(calibration_target instrument13 GroundStation69)
	(calibration_target instrument13 GroundStation18)
	(calibration_target instrument13 Star21)
	(calibration_target instrument13 Star16)
	(calibration_target instrument13 Star72)
	(on_board instrument9 satellite4)
	(on_board instrument10 satellite4)
	(on_board instrument11 satellite4)
	(on_board instrument12 satellite4)
	(on_board instrument13 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Phenomenon127)
	(supports instrument14 thermograph1)
	(supports instrument14 spectrograph2)
	(supports instrument14 infrared4)
	(calibration_target instrument14 GroundStation8)
	(calibration_target instrument14 GroundStation28)
	(calibration_target instrument14 GroundStation62)
	(calibration_target instrument14 Star32)
	(calibration_target instrument14 GroundStation5)
	(calibration_target instrument14 GroundStation68)
	(calibration_target instrument14 Star7)
	(calibration_target instrument14 GroundStation71)
	(calibration_target instrument14 Star56)
	(calibration_target instrument14 GroundStation26)
	(calibration_target instrument14 GroundStation45)
	(calibration_target instrument14 Star12)
	(calibration_target instrument14 GroundStation50)
	(calibration_target instrument14 GroundStation6)
	(calibration_target instrument14 GroundStation43)
	(calibration_target instrument14 Star39)
	(calibration_target instrument14 Star14)
	(calibration_target instrument14 GroundStation53)
	(calibration_target instrument14 Star60)
	(calibration_target instrument14 GroundStation75)
	(calibration_target instrument14 GroundStation78)
	(calibration_target instrument14 GroundStation69)
	(supports instrument15 spectrograph2)
	(calibration_target instrument15 GroundStation5)
	(calibration_target instrument15 GroundStation58)
	(calibration_target instrument15 Star29)
	(on_board instrument14 satellite5)
	(on_board instrument15 satellite5)
	(power_avail satellite5)
	(pointing satellite5 GroundStation8)
	(supports instrument16 spectrograph2)
	(supports instrument16 infrared4)
	(supports instrument16 image0)
	(calibration_target instrument16 GroundStation62)
	(calibration_target instrument16 Star17)
	(calibration_target instrument16 GroundStation0)
	(calibration_target instrument16 Star16)
	(calibration_target instrument16 GroundStation5)
	(calibration_target instrument16 GroundStation63)
	(calibration_target instrument16 GroundStation71)
	(calibration_target instrument16 GroundStation53)
	(calibration_target instrument16 GroundStation45)
	(calibration_target instrument16 Star15)
	(calibration_target instrument16 GroundStation48)
	(calibration_target instrument16 Star79)
	(calibration_target instrument16 GroundStation10)
	(supports instrument17 spectrograph2)
	(calibration_target instrument17 GroundStation74)
	(calibration_target instrument17 GroundStation37)
	(calibration_target instrument17 GroundStation34)
	(calibration_target instrument17 GroundStation1)
	(calibration_target instrument17 GroundStation28)
	(calibration_target instrument17 GroundStation5)
	(calibration_target instrument17 Star65)
	(calibration_target instrument17 Star52)
	(calibration_target instrument17 GroundStation10)
	(calibration_target instrument17 GroundStation20)
	(on_board instrument16 satellite6)
	(on_board instrument17 satellite6)
	(power_avail satellite6)
	(pointing satellite6 GroundStation40)
)
(:goal (and
	(pointing satellite3 GroundStation59)
	(have_image Planet80 infrared4)
	(have_image Phenomenon81 spectrograph2)
	(have_image Planet82 infrared3)
	(have_image Planet83 thermograph1)
	(have_image Phenomenon84 image0)
	(have_image Planet85 thermograph1)
	(have_image Star86 spectrograph2)
	(have_image Planet87 spectrograph2)
	(have_image Phenomenon88 spectrograph2)
	(have_image Star89 thermograph1)
	(have_image Star90 infrared4)
	(have_image Star91 infrared4)
	(have_image Planet92 thermograph1)
	(have_image Phenomenon93 image0)
	(have_image Star94 infrared3)
	(have_image Planet95 spectrograph2)
	(have_image Planet96 infrared4)
	(have_image Planet97 infrared4)
	(have_image Planet98 infrared3)
	(have_image Star99 infrared4)
	(have_image Planet100 spectrograph2)
	(have_image Phenomenon101 thermograph1)
	(have_image Star102 thermograph1)
	(have_image Star103 thermograph1)
	(have_image Phenomenon104 image0)
	(have_image Planet105 thermograph1)
	(have_image Planet106 image0)
	(have_image Planet107 image0)
	(have_image Planet108 image0)
	(have_image Star109 infrared3)
	(have_image Phenomenon110 thermograph1)
	(have_image Star111 thermograph1)
	(have_image Planet112 infrared3)
	(have_image Planet113 image0)
	(have_image Star114 spectrograph2)
	(have_image Planet115 infrared4)
	(have_image Planet116 image0)
	(have_image Phenomenon117 infrared4)
	(have_image Phenomenon118 thermograph1)
	(have_image Planet119 thermograph1)
	(have_image Star120 infrared3)
	(have_image Star121 infrared3)
	(have_image Star122 spectrograph2)
	(have_image Phenomenon123 infrared3)
	(have_image Phenomenon124 spectrograph2)
	(have_image Phenomenon125 image0)
	(have_image Phenomenon126 infrared4)
	(have_image Phenomenon127 infrared3)
	(have_image Planet128 image0)
	(have_image Phenomenon129 thermograph1)
	(have_image Planet130 infrared4)
	(have_image Phenomenon131 thermograph1)
	(have_image Phenomenon132 infrared4)
	(have_image Phenomenon133 infrared4)
	(have_image Planet134 thermograph1)
	(have_image Phenomenon135 infrared3)
	(have_image Star136 thermograph1)
	(have_image Star137 spectrograph2)
	(have_image Phenomenon138 spectrograph2)
	(have_image Planet139 image0)
))

)
