(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	satellite1 - satellite
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	satellite2 - satellite
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	satellite3 - satellite
	instrument7 - instrument
	satellite4 - satellite
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	satellite5 - satellite
	instrument11 - instrument
	satellite6 - satellite
	instrument12 - instrument
	image3 - mode
	infrared0 - mode
	thermograph4 - mode
	infrared2 - mode
	spectrograph1 - mode
	Star38 - direction
	GroundStation51 - direction
	GroundStation53 - direction
	Star69 - direction
	GroundStation46 - direction
	GroundStation76 - direction
	GroundStation72 - direction
	GroundStation18 - direction
	Star70 - direction
	Star8 - direction
	GroundStation39 - direction
	Star40 - direction
	GroundStation20 - direction
	GroundStation68 - direction
	Star10 - direction
	Star54 - direction
	Star0 - direction
	GroundStation57 - direction
	Star9 - direction
	GroundStation26 - direction
	Star75 - direction
	GroundStation71 - direction
	Star32 - direction
	GroundStation58 - direction
	GroundStation37 - direction
	GroundStation60 - direction
	GroundStation17 - direction
	GroundStation56 - direction
	Star35 - direction
	Star61 - direction
	GroundStation30 - direction
	GroundStation49 - direction
	Star11 - direction
	GroundStation13 - direction
	GroundStation23 - direction
	Star16 - direction
	Star55 - direction
	GroundStation2 - direction
	Star48 - direction
	Star43 - direction
	Star45 - direction
	Star66 - direction
	Star34 - direction
	GroundStation6 - direction
	Star64 - direction
	GroundStation27 - direction
	Star3 - direction
	GroundStation28 - direction
	Star52 - direction
	GroundStation59 - direction
	Star4 - direction
	GroundStation5 - direction
	GroundStation36 - direction
	Star79 - direction
	GroundStation73 - direction
	Star50 - direction
	GroundStation67 - direction
	GroundStation22 - direction
	Star74 - direction
	GroundStation14 - direction
	GroundStation44 - direction
	Star41 - direction
	GroundStation25 - direction
	Star24 - direction
	Star77 - direction
	GroundStation31 - direction
	GroundStation33 - direction
	GroundStation12 - direction
	GroundStation29 - direction
	GroundStation1 - direction
	Star42 - direction
	GroundStation19 - direction
	GroundStation15 - direction
	Star21 - direction
	GroundStation7 - direction
	Star62 - direction
	GroundStation63 - direction
	GroundStation47 - direction
	Star78 - direction
	GroundStation65 - direction
	Star80 - direction
	Phenomenon81 - direction
	Planet82 - direction
	Phenomenon83 - direction
	Phenomenon84 - direction
	Star85 - direction
	Phenomenon86 - direction
	Planet87 - direction
	Phenomenon88 - direction
	Planet89 - direction
	Star90 - direction
	Planet91 - direction
	Phenomenon92 - direction
	Star93 - direction
	Star94 - direction
	Star95 - direction
	Planet96 - direction
	Star97 - direction
	Planet98 - direction
	Phenomenon99 - direction
	Planet100 - direction
	Planet101 - direction
	Star102 - direction
	Planet103 - direction
	Phenomenon104 - direction
	Star105 - direction
	Planet106 - direction
	Phenomenon107 - direction
	Phenomenon108 - direction
	Phenomenon109 - direction
	Phenomenon110 - direction
	Star111 - direction
	Phenomenon112 - direction
	Phenomenon113 - direction
	Phenomenon114 - direction
	Star115 - direction
	Star116 - direction
	Star117 - direction
	Star118 - direction
	Star119 - direction
	Phenomenon120 - direction
	Planet121 - direction
	Planet122 - direction
	Planet123 - direction
	Planet124 - direction
	Phenomenon125 - direction
	Phenomenon126 - direction
	Planet127 - direction
	Planet128 - direction
	Planet129 - direction
	Phenomenon130 - direction
	Planet131 - direction
	Star132 - direction
	Phenomenon133 - direction
	Planet134 - direction
	Star135 - direction
	Star136 - direction
	Phenomenon137 - direction
	Star138 - direction
	Star139 - direction
)
(:init
	(supports instrument0 spectrograph1)
	(supports instrument0 thermograph4)
	(calibration_target instrument0 GroundStation20)
	(calibration_target instrument0 GroundStation30)
	(calibration_target instrument0 Star66)
	(calibration_target instrument0 GroundStation12)
	(calibration_target instrument0 GroundStation13)
	(calibration_target instrument0 Star74)
	(calibration_target instrument0 GroundStation14)
	(calibration_target instrument0 GroundStation37)
	(calibration_target instrument0 GroundStation67)
	(calibration_target instrument0 Star75)
	(calibration_target instrument0 GroundStation25)
	(calibration_target instrument0 Star48)
	(calibration_target instrument0 GroundStation7)
	(calibration_target instrument0 Star43)
	(calibration_target instrument0 GroundStation58)
	(calibration_target instrument0 GroundStation73)
	(calibration_target instrument0 GroundStation5)
	(calibration_target instrument0 GroundStation23)
	(calibration_target instrument0 GroundStation46)
	(calibration_target instrument0 Star24)
	(calibration_target instrument0 Star50)
	(calibration_target instrument0 GroundStation15)
	(on_board instrument0 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star48)
	(supports instrument1 thermograph4)
	(supports instrument1 infrared2)
	(supports instrument1 infrared0)
	(calibration_target instrument1 GroundStation31)
	(calibration_target instrument1 Star11)
	(calibration_target instrument1 GroundStation56)
	(calibration_target instrument1 GroundStation76)
	(calibration_target instrument1 Star45)
	(calibration_target instrument1 GroundStation44)
	(calibration_target instrument1 GroundStation39)
	(calibration_target instrument1 GroundStation6)
	(calibration_target instrument1 GroundStation17)
	(calibration_target instrument1 GroundStation26)
	(calibration_target instrument1 GroundStation14)
	(supports instrument2 spectrograph1)
	(calibration_target instrument2 GroundStation72)
	(calibration_target instrument2 GroundStation2)
	(calibration_target instrument2 Star77)
	(calibration_target instrument2 Star21)
	(calibration_target instrument2 Star54)
	(calibration_target instrument2 Star11)
	(calibration_target instrument2 Star55)
	(calibration_target instrument2 GroundStation65)
	(calibration_target instrument2 GroundStation63)
	(calibration_target instrument2 Star8)
	(calibration_target instrument2 GroundStation17)
	(calibration_target instrument2 GroundStation20)
	(calibration_target instrument2 GroundStation57)
	(calibration_target instrument2 GroundStation56)
	(calibration_target instrument2 GroundStation31)
	(calibration_target instrument2 GroundStation15)
	(calibration_target instrument2 GroundStation30)
	(calibration_target instrument2 Star75)
	(calibration_target instrument2 GroundStation67)
	(calibration_target instrument2 Star3)
	(calibration_target instrument2 Star9)
	(supports instrument3 infrared0)
	(calibration_target instrument3 Star16)
	(calibration_target instrument3 GroundStation17)
	(calibration_target instrument3 GroundStation13)
	(calibration_target instrument3 GroundStation56)
	(calibration_target instrument3 GroundStation14)
	(calibration_target instrument3 GroundStation26)
	(calibration_target instrument3 Star55)
	(calibration_target instrument3 GroundStation25)
	(calibration_target instrument3 Star79)
	(calibration_target instrument3 GroundStation60)
	(calibration_target instrument3 GroundStation30)
	(calibration_target instrument3 GroundStation29)
	(calibration_target instrument3 Star4)
	(calibration_target instrument3 Star40)
	(calibration_target instrument3 Star8)
	(calibration_target instrument3 GroundStation1)
	(calibration_target instrument3 Star70)
	(calibration_target instrument3 Star34)
	(calibration_target instrument3 GroundStation18)
	(calibration_target instrument3 Star41)
	(on_board instrument1 satellite1)
	(on_board instrument2 satellite1)
	(on_board instrument3 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star43)
	(supports instrument4 spectrograph1)
	(calibration_target instrument4 Star78)
	(calibration_target instrument4 Star24)
	(calibration_target instrument4 Star79)
	(calibration_target instrument4 GroundStation59)
	(calibration_target instrument4 Star21)
	(calibration_target instrument4 Star52)
	(calibration_target instrument4 GroundStation58)
	(calibration_target instrument4 GroundStation56)
	(calibration_target instrument4 GroundStation71)
	(calibration_target instrument4 GroundStation67)
	(calibration_target instrument4 GroundStation6)
	(calibration_target instrument4 GroundStation36)
	(calibration_target instrument4 Star40)
	(supports instrument5 image3)
	(supports instrument5 spectrograph1)
	(supports instrument5 thermograph4)
	(calibration_target instrument5 GroundStation68)
	(calibration_target instrument5 Star55)
	(calibration_target instrument5 GroundStation20)
	(calibration_target instrument5 Star9)
	(calibration_target instrument5 Star3)
	(calibration_target instrument5 GroundStation60)
	(calibration_target instrument5 Star40)
	(calibration_target instrument5 GroundStation39)
	(calibration_target instrument5 GroundStation19)
	(calibration_target instrument5 GroundStation12)
	(calibration_target instrument5 GroundStation58)
	(calibration_target instrument5 GroundStation49)
	(calibration_target instrument5 Star64)
	(calibration_target instrument5 GroundStation26)
	(calibration_target instrument5 GroundStation25)
	(calibration_target instrument5 GroundStation47)
	(calibration_target instrument5 GroundStation1)
	(supports instrument6 infrared0)
	(supports instrument6 infrared2)
	(supports instrument6 spectrograph1)
	(calibration_target instrument6 Star48)
	(calibration_target instrument6 GroundStation27)
	(calibration_target instrument6 GroundStation14)
	(calibration_target instrument6 Star77)
	(calibration_target instrument6 GroundStation37)
	(calibration_target instrument6 GroundStation15)
	(calibration_target instrument6 GroundStation23)
	(calibration_target instrument6 GroundStation2)
	(calibration_target instrument6 Star32)
	(calibration_target instrument6 GroundStation59)
	(calibration_target instrument6 GroundStation30)
	(calibration_target instrument6 GroundStation57)
	(calibration_target instrument6 Star4)
	(calibration_target instrument6 Star0)
	(calibration_target instrument6 GroundStation26)
	(calibration_target instrument6 Star54)
	(calibration_target instrument6 Star50)
	(calibration_target instrument6 Star10)
	(on_board instrument4 satellite2)
	(on_board instrument5 satellite2)
	(on_board instrument6 satellite2)
	(power_avail satellite2)
	(pointing satellite2 GroundStation6)
	(supports instrument7 image3)
	(supports instrument7 infrared0)
	(calibration_target instrument7 Star52)
	(calibration_target instrument7 GroundStation27)
	(calibration_target instrument7 Star48)
	(calibration_target instrument7 Star42)
	(calibration_target instrument7 Star62)
	(calibration_target instrument7 Star35)
	(calibration_target instrument7 GroundStation25)
	(calibration_target instrument7 GroundStation49)
	(calibration_target instrument7 GroundStation30)
	(calibration_target instrument7 GroundStation58)
	(calibration_target instrument7 GroundStation15)
	(calibration_target instrument7 Star77)
	(calibration_target instrument7 Star32)
	(calibration_target instrument7 GroundStation59)
	(calibration_target instrument7 Star3)
	(calibration_target instrument7 GroundStation36)
	(calibration_target instrument7 GroundStation23)
	(calibration_target instrument7 GroundStation5)
	(calibration_target instrument7 GroundStation71)
	(calibration_target instrument7 Star75)
	(calibration_target instrument7 GroundStation26)
	(calibration_target instrument7 Star55)
	(calibration_target instrument7 GroundStation33)
	(calibration_target instrument7 GroundStation12)
	(calibration_target instrument7 Star9)
	(calibration_target instrument7 Star11)
	(on_board instrument7 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star95)
	(supports instrument8 infrared2)
	(supports instrument8 infrared0)
	(supports instrument8 image3)
	(calibration_target instrument8 GroundStation22)
	(calibration_target instrument8 Star41)
	(calibration_target instrument8 Star34)
	(calibration_target instrument8 GroundStation17)
	(calibration_target instrument8 GroundStation7)
	(calibration_target instrument8 Star77)
	(calibration_target instrument8 GroundStation60)
	(calibration_target instrument8 GroundStation37)
	(supports instrument9 thermograph4)
	(supports instrument9 infrared0)
	(calibration_target instrument9 GroundStation15)
	(calibration_target instrument9 Star78)
	(calibration_target instrument9 Star43)
	(calibration_target instrument9 Star48)
	(calibration_target instrument9 Star34)
	(calibration_target instrument9 GroundStation2)
	(calibration_target instrument9 Star55)
	(calibration_target instrument9 GroundStation47)
	(calibration_target instrument9 Star16)
	(calibration_target instrument9 GroundStation12)
	(calibration_target instrument9 GroundStation23)
	(calibration_target instrument9 GroundStation13)
	(calibration_target instrument9 GroundStation27)
	(calibration_target instrument9 Star41)
	(calibration_target instrument9 Star11)
	(calibration_target instrument9 GroundStation28)
	(calibration_target instrument9 GroundStation49)
	(calibration_target instrument9 Star66)
	(calibration_target instrument9 GroundStation33)
	(calibration_target instrument9 GroundStation63)
	(calibration_target instrument9 GroundStation30)
	(calibration_target instrument9 Star3)
	(calibration_target instrument9 Star61)
	(calibration_target instrument9 Star64)
	(calibration_target instrument9 Star35)
	(calibration_target instrument9 GroundStation56)
	(supports instrument10 image3)
	(supports instrument10 thermograph4)
	(calibration_target instrument10 Star3)
	(calibration_target instrument10 GroundStation47)
	(calibration_target instrument10 GroundStation27)
	(calibration_target instrument10 GroundStation44)
	(calibration_target instrument10 Star64)
	(calibration_target instrument10 Star24)
	(calibration_target instrument10 GroundStation6)
	(calibration_target instrument10 Star34)
	(calibration_target instrument10 Star66)
	(calibration_target instrument10 GroundStation29)
	(calibration_target instrument10 Star45)
	(on_board instrument8 satellite4)
	(on_board instrument9 satellite4)
	(on_board instrument10 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star75)
	(supports instrument11 infrared2)
	(calibration_target instrument11 GroundStation44)
	(calibration_target instrument11 GroundStation31)
	(calibration_target instrument11 Star78)
	(calibration_target instrument11 GroundStation63)
	(calibration_target instrument11 GroundStation14)
	(calibration_target instrument11 Star74)
	(calibration_target instrument11 GroundStation22)
	(calibration_target instrument11 GroundStation67)
	(calibration_target instrument11 Star50)
	(calibration_target instrument11 Star41)
	(calibration_target instrument11 GroundStation73)
	(calibration_target instrument11 Star79)
	(calibration_target instrument11 GroundStation36)
	(calibration_target instrument11 GroundStation5)
	(calibration_target instrument11 Star4)
	(calibration_target instrument11 GroundStation59)
	(calibration_target instrument11 Star52)
	(calibration_target instrument11 GroundStation33)
	(calibration_target instrument11 GroundStation28)
	(calibration_target instrument11 Star24)
	(on_board instrument11 satellite5)
	(power_avail satellite5)
	(pointing satellite5 GroundStation44)
	(supports instrument12 infrared2)
	(calibration_target instrument12 GroundStation65)
	(calibration_target instrument12 Star78)
	(calibration_target instrument12 GroundStation47)
	(calibration_target instrument12 GroundStation63)
	(calibration_target instrument12 Star62)
	(calibration_target instrument12 GroundStation7)
	(calibration_target instrument12 Star21)
	(calibration_target instrument12 GroundStation15)
	(calibration_target instrument12 GroundStation19)
	(calibration_target instrument12 Star42)
	(calibration_target instrument12 GroundStation1)
	(calibration_target instrument12 GroundStation29)
	(calibration_target instrument12 GroundStation12)
	(calibration_target instrument12 GroundStation33)
	(calibration_target instrument12 GroundStation31)
	(calibration_target instrument12 Star77)
	(calibration_target instrument12 Star24)
	(calibration_target instrument12 GroundStation25)
	(calibration_target instrument12 Star41)
	(on_board instrument12 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star54)
)
(:goal (and
	(pointing satellite1 Phenomenon92)
	(pointing satellite4 Phenomenon88)
	(pointing satellite5 GroundStation30)
	(have_image Star80 image3)
	(have_image Phenomenon81 infrared0)
	(have_image Planet82 infrared0)
	(have_image Phenomenon83 infrared0)
	(have_image Phenomenon84 thermograph4)
	(have_image Star85 infrared2)
	(have_image Phenomenon86 image3)
	(have_image Planet87 infrared0)
	(have_image Phenomenon88 infrared2)
	(have_image Planet89 infrared0)
	(have_image Star90 spectrograph1)
	(have_image Planet91 thermograph4)
	(have_image Phenomenon92 infrared2)
	(have_image Star93 thermograph4)
	(have_image Star94 spectrograph1)
	(have_image Star95 infrared0)
	(have_image Planet96 spectrograph1)
	(have_image Star97 infrared2)
	(have_image Planet98 image3)
	(have_image Phenomenon99 infrared2)
	(have_image Planet100 infrared2)
	(have_image Planet101 infrared0)
	(have_image Star102 infrared2)
	(have_image Planet103 infrared2)
	(have_image Phenomenon104 infrared2)
	(have_image Star105 spectrograph1)
	(have_image Planet106 infrared0)
	(have_image Phenomenon107 infrared0)
	(have_image Phenomenon108 spectrograph1)
	(have_image Phenomenon109 image3)
	(have_image Phenomenon110 infrared2)
	(have_image Star111 spectrograph1)
	(have_image Phenomenon112 infrared0)
	(have_image Phenomenon113 image3)
	(have_image Phenomenon114 infrared2)
	(have_image Star115 image3)
	(have_image Star116 infrared2)
	(have_image Star117 spectrograph1)
	(have_image Star118 spectrograph1)
	(have_image Star119 infrared0)
	(have_image Phenomenon120 image3)
	(have_image Planet121 infrared2)
	(have_image Planet122 spectrograph1)
	(have_image Planet123 image3)
	(have_image Planet124 spectrograph1)
	(have_image Phenomenon125 infrared2)
	(have_image Phenomenon126 spectrograph1)
	(have_image Planet127 image3)
	(have_image Planet128 spectrograph1)
	(have_image Planet129 infrared2)
	(have_image Phenomenon130 spectrograph1)
	(have_image Planet131 infrared2)
	(have_image Star132 image3)
	(have_image Phenomenon133 image3)
	(have_image Planet134 thermograph4)
	(have_image Star135 spectrograph1)
	(have_image Star136 infrared0)
	(have_image Phenomenon137 thermograph4)
	(have_image Star138 spectrograph1)
	(have_image Star139 infrared2)
))

)
