(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	satellite1 - satellite
	instrument3 - instrument
	instrument4 - instrument
	satellite2 - satellite
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	satellite3 - satellite
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	satellite4 - satellite
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	satellite5 - satellite
	instrument16 - instrument
	satellite6 - satellite
	instrument17 - instrument
	thermograph1 - mode
	thermograph2 - mode
	infrared0 - mode
	image3 - mode
	infrared4 - mode
	Star1 - direction
	GroundStation79 - direction
	GroundStation27 - direction
	GroundStation47 - direction
	GroundStation71 - direction
	GroundStation26 - direction
	GroundStation54 - direction
	GroundStation64 - direction
	GroundStation67 - direction
	GroundStation0 - direction
	GroundStation13 - direction
	GroundStation37 - direction
	GroundStation72 - direction
	Star21 - direction
	Star32 - direction
	GroundStation76 - direction
	Star60 - direction
	Star36 - direction
	GroundStation50 - direction
	GroundStation31 - direction
	Star58 - direction
	GroundStation17 - direction
	Star69 - direction
	GroundStation34 - direction
	Star25 - direction
	GroundStation38 - direction
	GroundStation4 - direction
	GroundStation39 - direction
	GroundStation78 - direction
	Star51 - direction
	Star61 - direction
	Star15 - direction
	Star40 - direction
	Star77 - direction
	GroundStation44 - direction
	GroundStation56 - direction
	GroundStation52 - direction
	GroundStation65 - direction
	Star5 - direction
	Star66 - direction
	Star23 - direction
	GroundStation62 - direction
	Star41 - direction
	Star59 - direction
	GroundStation68 - direction
	Star14 - direction
	GroundStation18 - direction
	Star35 - direction
	GroundStation43 - direction
	GroundStation45 - direction
	Star24 - direction
	Star53 - direction
	GroundStation63 - direction
	Star49 - direction
	GroundStation22 - direction
	Star48 - direction
	Star42 - direction
	Star16 - direction
	Star73 - direction
	Star6 - direction
	GroundStation30 - direction
	Star57 - direction
	GroundStation29 - direction
	GroundStation2 - direction
	Star74 - direction
	GroundStation28 - direction
	GroundStation8 - direction
	Star10 - direction
	GroundStation11 - direction
	Star9 - direction
	Star3 - direction
	Star19 - direction
	Star12 - direction
	GroundStation20 - direction
	GroundStation46 - direction
	Star75 - direction
	GroundStation55 - direction
	Star33 - direction
	Star70 - direction
	Star7 - direction
	Star80 - direction
	Planet81 - direction
	Star82 - direction
	Phenomenon83 - direction
	Planet84 - direction
	Star85 - direction
	Star86 - direction
	Planet87 - direction
	Planet88 - direction
	Phenomenon89 - direction
	Planet90 - direction
	Phenomenon91 - direction
	Phenomenon92 - direction
	Star93 - direction
	Phenomenon94 - direction
	Planet95 - direction
	Planet96 - direction
	Phenomenon97 - direction
	Planet98 - direction
	Star99 - direction
	Phenomenon100 - direction
	Phenomenon101 - direction
	Phenomenon102 - direction
	Planet103 - direction
	Star104 - direction
	Planet105 - direction
	Planet106 - direction
	Star107 - direction
	Planet108 - direction
	Phenomenon109 - direction
	Star110 - direction
	Phenomenon111 - direction
	Phenomenon112 - direction
	Phenomenon113 - direction
	Planet114 - direction
	Star115 - direction
	Phenomenon116 - direction
	Phenomenon117 - direction
	Planet118 - direction
	Phenomenon119 - direction
	Planet120 - direction
	Star121 - direction
	Star122 - direction
	Planet123 - direction
	Star124 - direction
	Phenomenon125 - direction
	Star126 - direction
	Star127 - direction
	Phenomenon128 - direction
	Star129 - direction
	Planet130 - direction
	Planet131 - direction
	Planet132 - direction
	Star133 - direction
	Planet134 - direction
	Phenomenon135 - direction
	Phenomenon136 - direction
	Planet137 - direction
	Planet138 - direction
	Planet139 - direction
)
(:init
	(supports instrument0 infrared4)
	(supports instrument0 thermograph2)
	(supports instrument0 image3)
	(calibration_target instrument0 Star6)
	(calibration_target instrument0 Star7)
	(calibration_target instrument0 GroundStation43)
	(calibration_target instrument0 GroundStation78)
	(calibration_target instrument0 Star69)
	(calibration_target instrument0 GroundStation56)
	(calibration_target instrument0 Star5)
	(calibration_target instrument0 GroundStation31)
	(calibration_target instrument0 Star40)
	(calibration_target instrument0 Star15)
	(calibration_target instrument0 Star66)
	(supports instrument1 thermograph2)
	(supports instrument1 infrared4)
	(calibration_target instrument1 Star49)
	(calibration_target instrument1 GroundStation43)
	(calibration_target instrument1 GroundStation17)
	(calibration_target instrument1 GroundStation39)
	(calibration_target instrument1 Star33)
	(calibration_target instrument1 Star23)
	(calibration_target instrument1 GroundStation50)
	(calibration_target instrument1 Star15)
	(calibration_target instrument1 Star21)
	(calibration_target instrument1 Star36)
	(calibration_target instrument1 Star58)
	(calibration_target instrument1 GroundStation28)
	(calibration_target instrument1 GroundStation72)
	(calibration_target instrument1 Star10)
	(calibration_target instrument1 GroundStation47)
	(calibration_target instrument1 Star59)
	(calibration_target instrument1 GroundStation44)
	(calibration_target instrument1 Star25)
	(calibration_target instrument1 GroundStation26)
	(calibration_target instrument1 GroundStation78)
	(calibration_target instrument1 GroundStation4)
	(calibration_target instrument1 GroundStation45)
	(calibration_target instrument1 GroundStation8)
	(calibration_target instrument1 Star14)
	(calibration_target instrument1 Star9)
	(calibration_target instrument1 Star19)
	(supports instrument2 infrared0)
	(supports instrument2 image3)
	(supports instrument2 thermograph2)
	(calibration_target instrument2 GroundStation27)
	(calibration_target instrument2 GroundStation79)
	(calibration_target instrument2 GroundStation22)
	(calibration_target instrument2 Star59)
	(calibration_target instrument2 Star16)
	(calibration_target instrument2 Star40)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation78)
	(supports instrument3 infrared4)
	(supports instrument3 thermograph1)
	(calibration_target instrument3 GroundStation72)
	(calibration_target instrument3 GroundStation37)
	(calibration_target instrument3 GroundStation13)
	(calibration_target instrument3 GroundStation45)
	(calibration_target instrument3 Star48)
	(calibration_target instrument3 GroundStation56)
	(calibration_target instrument3 GroundStation8)
	(calibration_target instrument3 GroundStation71)
	(calibration_target instrument3 GroundStation47)
	(calibration_target instrument3 Star41)
	(calibration_target instrument3 Star7)
	(calibration_target instrument3 Star77)
	(calibration_target instrument3 Star57)
	(calibration_target instrument3 Star32)
	(calibration_target instrument3 Star40)
	(calibration_target instrument3 GroundStation29)
	(calibration_target instrument3 Star9)
	(calibration_target instrument3 Star53)
	(calibration_target instrument3 Star16)
	(calibration_target instrument3 Star73)
	(supports instrument4 thermograph2)
	(supports instrument4 thermograph1)
	(supports instrument4 image3)
	(calibration_target instrument4 Star69)
	(calibration_target instrument4 GroundStation76)
	(calibration_target instrument4 Star41)
	(calibration_target instrument4 GroundStation22)
	(calibration_target instrument4 GroundStation64)
	(calibration_target instrument4 Star70)
	(calibration_target instrument4 GroundStation46)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation22)
	(supports instrument5 thermograph2)
	(calibration_target instrument5 Star36)
	(calibration_target instrument5 GroundStation64)
	(calibration_target instrument5 Star66)
	(calibration_target instrument5 GroundStation17)
	(calibration_target instrument5 GroundStation26)
	(calibration_target instrument5 GroundStation39)
	(calibration_target instrument5 Star48)
	(calibration_target instrument5 GroundStation37)
	(calibration_target instrument5 Star69)
	(calibration_target instrument5 Star9)
	(calibration_target instrument5 Star23)
	(calibration_target instrument5 GroundStation63)
	(supports instrument6 infrared0)
	(calibration_target instrument6 GroundStation17)
	(calibration_target instrument6 GroundStation20)
	(calibration_target instrument6 GroundStation62)
	(calibration_target instrument6 GroundStation4)
	(calibration_target instrument6 Star53)
	(calibration_target instrument6 GroundStation54)
	(calibration_target instrument6 GroundStation56)
	(calibration_target instrument6 Star60)
	(supports instrument7 infrared0)
	(supports instrument7 infrared4)
	(supports instrument7 thermograph1)
	(calibration_target instrument7 GroundStation68)
	(calibration_target instrument7 Star70)
	(calibration_target instrument7 Star60)
	(supports instrument8 thermograph1)
	(supports instrument8 infrared0)
	(calibration_target instrument8 Star49)
	(calibration_target instrument8 GroundStation18)
	(calibration_target instrument8 Star53)
	(calibration_target instrument8 Star66)
	(calibration_target instrument8 GroundStation46)
	(calibration_target instrument8 GroundStation30)
	(calibration_target instrument8 Star32)
	(calibration_target instrument8 GroundStation62)
	(calibration_target instrument8 GroundStation63)
	(calibration_target instrument8 GroundStation54)
	(calibration_target instrument8 GroundStation0)
	(calibration_target instrument8 Star19)
	(calibration_target instrument8 GroundStation67)
	(calibration_target instrument8 Star48)
	(calibration_target instrument8 GroundStation43)
	(calibration_target instrument8 GroundStation26)
	(calibration_target instrument8 Star41)
	(on_board instrument5 satellite2)
	(on_board instrument6 satellite2)
	(on_board instrument7 satellite2)
	(on_board instrument8 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star61)
	(supports instrument9 image3)
	(calibration_target instrument9 GroundStation62)
	(calibration_target instrument9 GroundStation72)
	(calibration_target instrument9 GroundStation22)
	(calibration_target instrument9 GroundStation37)
	(calibration_target instrument9 GroundStation11)
	(calibration_target instrument9 GroundStation13)
	(calibration_target instrument9 GroundStation0)
	(calibration_target instrument9 GroundStation8)
	(calibration_target instrument9 Star48)
	(calibration_target instrument9 GroundStation68)
	(calibration_target instrument9 GroundStation2)
	(calibration_target instrument9 GroundStation67)
	(calibration_target instrument9 Star49)
	(calibration_target instrument9 GroundStation50)
	(calibration_target instrument9 GroundStation31)
	(calibration_target instrument9 GroundStation64)
	(calibration_target instrument9 Star60)
	(calibration_target instrument9 Star6)
	(calibration_target instrument9 Star19)
	(calibration_target instrument9 Star5)
	(supports instrument10 infrared4)
	(supports instrument10 thermograph1)
	(supports instrument10 image3)
	(calibration_target instrument10 GroundStation50)
	(calibration_target instrument10 Star23)
	(calibration_target instrument10 Star36)
	(calibration_target instrument10 GroundStation38)
	(calibration_target instrument10 Star73)
	(calibration_target instrument10 Star60)
	(calibration_target instrument10 GroundStation28)
	(calibration_target instrument10 GroundStation44)
	(calibration_target instrument10 GroundStation78)
	(calibration_target instrument10 GroundStation76)
	(calibration_target instrument10 Star66)
	(calibration_target instrument10 GroundStation46)
	(calibration_target instrument10 GroundStation45)
	(calibration_target instrument10 Star32)
	(calibration_target instrument10 Star21)
	(calibration_target instrument10 Star70)
	(calibration_target instrument10 Star40)
	(calibration_target instrument10 Star6)
	(calibration_target instrument10 Star15)
	(calibration_target instrument10 GroundStation18)
	(supports instrument11 infrared0)
	(supports instrument11 infrared4)
	(calibration_target instrument11 Star24)
	(calibration_target instrument11 Star12)
	(on_board instrument9 satellite3)
	(on_board instrument10 satellite3)
	(on_board instrument11 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation55)
	(supports instrument12 thermograph2)
	(supports instrument12 thermograph1)
	(calibration_target instrument12 Star42)
	(calibration_target instrument12 GroundStation28)
	(calibration_target instrument12 Star48)
	(calibration_target instrument12 GroundStation45)
	(supports instrument13 thermograph2)
	(supports instrument13 image3)
	(calibration_target instrument13 GroundStation20)
	(calibration_target instrument13 GroundStation39)
	(calibration_target instrument13 Star69)
	(calibration_target instrument13 Star53)
	(calibration_target instrument13 Star41)
	(calibration_target instrument13 GroundStation17)
	(calibration_target instrument13 Star74)
	(calibration_target instrument13 GroundStation44)
	(calibration_target instrument13 Star58)
	(calibration_target instrument13 GroundStation55)
	(calibration_target instrument13 GroundStation28)
	(calibration_target instrument13 GroundStation38)
	(calibration_target instrument13 GroundStation65)
	(calibration_target instrument13 Star40)
	(calibration_target instrument13 Star19)
	(calibration_target instrument13 GroundStation31)
	(supports instrument14 thermograph1)
	(supports instrument14 infrared4)
	(calibration_target instrument14 Star42)
	(calibration_target instrument14 Star57)
	(calibration_target instrument14 Star70)
	(calibration_target instrument14 GroundStation39)
	(calibration_target instrument14 GroundStation4)
	(calibration_target instrument14 GroundStation18)
	(calibration_target instrument14 GroundStation38)
	(calibration_target instrument14 Star49)
	(calibration_target instrument14 Star9)
	(calibration_target instrument14 GroundStation43)
	(calibration_target instrument14 Star74)
	(calibration_target instrument14 Star25)
	(calibration_target instrument14 Star33)
	(calibration_target instrument14 GroundStation62)
	(calibration_target instrument14 GroundStation34)
	(calibration_target instrument14 GroundStation28)
	(calibration_target instrument14 GroundStation45)
	(calibration_target instrument14 Star12)
	(calibration_target instrument14 GroundStation11)
	(calibration_target instrument14 Star73)
	(supports instrument15 thermograph1)
	(supports instrument15 image3)
	(calibration_target instrument15 Star66)
	(calibration_target instrument15 Star5)
	(calibration_target instrument15 GroundStation65)
	(calibration_target instrument15 GroundStation63)
	(calibration_target instrument15 GroundStation52)
	(calibration_target instrument15 Star16)
	(calibration_target instrument15 Star42)
	(calibration_target instrument15 GroundStation56)
	(calibration_target instrument15 GroundStation44)
	(calibration_target instrument15 Star77)
	(calibration_target instrument15 Star40)
	(calibration_target instrument15 Star7)
	(calibration_target instrument15 Star15)
	(calibration_target instrument15 GroundStation55)
	(calibration_target instrument15 Star61)
	(calibration_target instrument15 Star51)
	(calibration_target instrument15 Star73)
	(calibration_target instrument15 GroundStation20)
	(calibration_target instrument15 GroundStation78)
	(calibration_target instrument15 Star3)
	(on_board instrument12 satellite4)
	(on_board instrument13 satellite4)
	(on_board instrument14 satellite4)
	(on_board instrument15 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Planet137)
	(supports instrument16 thermograph1)
	(supports instrument16 infrared4)
	(calibration_target instrument16 Star42)
	(calibration_target instrument16 Star48)
	(calibration_target instrument16 GroundStation22)
	(calibration_target instrument16 Star49)
	(calibration_target instrument16 Star74)
	(calibration_target instrument16 GroundStation63)
	(calibration_target instrument16 Star53)
	(calibration_target instrument16 Star24)
	(calibration_target instrument16 GroundStation45)
	(calibration_target instrument16 GroundStation43)
	(calibration_target instrument16 Star35)
	(calibration_target instrument16 GroundStation18)
	(calibration_target instrument16 Star14)
	(calibration_target instrument16 GroundStation68)
	(calibration_target instrument16 Star59)
	(calibration_target instrument16 Star41)
	(calibration_target instrument16 GroundStation62)
	(calibration_target instrument16 Star23)
	(on_board instrument16 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star6)
	(supports instrument17 thermograph2)
	(supports instrument17 infrared0)
	(supports instrument17 infrared4)
	(calibration_target instrument17 Star7)
	(calibration_target instrument17 Star70)
	(calibration_target instrument17 Star33)
	(calibration_target instrument17 GroundStation55)
	(calibration_target instrument17 Star75)
	(calibration_target instrument17 GroundStation46)
	(calibration_target instrument17 GroundStation20)
	(calibration_target instrument17 Star12)
	(calibration_target instrument17 Star19)
	(calibration_target instrument17 Star3)
	(calibration_target instrument17 Star9)
	(calibration_target instrument17 GroundStation11)
	(calibration_target instrument17 Star10)
	(calibration_target instrument17 GroundStation8)
	(calibration_target instrument17 GroundStation28)
	(calibration_target instrument17 Star74)
	(calibration_target instrument17 GroundStation2)
	(calibration_target instrument17 GroundStation29)
	(calibration_target instrument17 Star57)
	(calibration_target instrument17 GroundStation30)
	(calibration_target instrument17 Star6)
	(calibration_target instrument17 Star73)
	(calibration_target instrument17 Star16)
	(on_board instrument17 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Planet90)
)
(:goal (and
	(pointing satellite2 Star73)
	(pointing satellite3 GroundStation22)
	(pointing satellite4 GroundStation22)
	(have_image Star80 image3)
	(have_image Planet81 thermograph1)
	(have_image Star82 image3)
	(have_image Phenomenon83 infrared4)
	(have_image Planet84 infrared0)
	(have_image Star85 infrared4)
	(have_image Star86 infrared0)
	(have_image Planet87 thermograph2)
	(have_image Planet88 infrared0)
	(have_image Phenomenon89 thermograph1)
	(have_image Planet90 thermograph1)
	(have_image Phenomenon91 infrared4)
	(have_image Phenomenon92 image3)
	(have_image Star93 image3)
	(have_image Phenomenon94 infrared4)
	(have_image Planet95 thermograph1)
	(have_image Planet96 infrared4)
	(have_image Phenomenon97 infrared0)
	(have_image Planet98 infrared4)
	(have_image Star99 image3)
	(have_image Phenomenon100 image3)
	(have_image Phenomenon101 thermograph1)
	(have_image Phenomenon102 infrared4)
	(have_image Planet103 thermograph2)
	(have_image Star104 thermograph2)
	(have_image Planet105 image3)
	(have_image Planet106 infrared4)
	(have_image Star107 image3)
	(have_image Planet108 image3)
	(have_image Phenomenon109 infrared4)
	(have_image Star110 image3)
	(have_image Phenomenon111 image3)
	(have_image Phenomenon112 thermograph1)
	(have_image Phenomenon113 thermograph2)
	(have_image Planet114 thermograph2)
	(have_image Star115 infrared0)
	(have_image Phenomenon116 infrared4)
	(have_image Phenomenon117 thermograph1)
	(have_image Planet118 infrared0)
	(have_image Phenomenon119 thermograph1)
	(have_image Planet120 infrared4)
	(have_image Star121 thermograph2)
	(have_image Star122 thermograph2)
	(have_image Planet123 thermograph2)
	(have_image Star124 infrared0)
	(have_image Phenomenon125 thermograph2)
	(have_image Star126 image3)
	(have_image Star127 infrared4)
	(have_image Phenomenon128 infrared4)
	(have_image Star129 image3)
	(have_image Planet130 infrared4)
	(have_image Planet131 thermograph1)
	(have_image Planet132 thermograph2)
	(have_image Star133 image3)
	(have_image Planet134 infrared0)
	(have_image Phenomenon135 thermograph1)
	(have_image Phenomenon136 infrared4)
	(have_image Planet137 image3)
	(have_image Planet138 infrared4)
	(have_image Planet139 infrared4)
))

)
