(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	satellite1 - satellite
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	satellite2 - satellite
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	satellite3 - satellite
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	satellite4 - satellite
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	satellite5 - satellite
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	satellite6 - satellite
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	image3 - mode
	infrared2 - mode
	thermograph0 - mode
	infrared4 - mode
	infrared1 - mode
	Star42 - direction
	Star54 - direction
	GroundStation17 - direction
	GroundStation65 - direction
	Star37 - direction
	Star53 - direction
	Star71 - direction
	Star51 - direction
	Star62 - direction
	Star52 - direction
	Star59 - direction
	Star28 - direction
	GroundStation4 - direction
	Star23 - direction
	GroundStation11 - direction
	GroundStation61 - direction
	GroundStation27 - direction
	GroundStation45 - direction
	Star68 - direction
	GroundStation20 - direction
	Star46 - direction
	Star25 - direction
	Star73 - direction
	GroundStation75 - direction
	GroundStation60 - direction
	GroundStation66 - direction
	GroundStation58 - direction
	Star3 - direction
	Star24 - direction
	Star30 - direction
	Star29 - direction
	GroundStation8 - direction
	Star16 - direction
	Star55 - direction
	GroundStation57 - direction
	GroundStation44 - direction
	GroundStation76 - direction
	GroundStation79 - direction
	GroundStation49 - direction
	Star14 - direction
	Star12 - direction
	Star15 - direction
	Star69 - direction
	GroundStation7 - direction
	Star22 - direction
	Star33 - direction
	Star6 - direction
	GroundStation2 - direction
	Star77 - direction
	Star43 - direction
	Star19 - direction
	Star74 - direction
	GroundStation78 - direction
	GroundStation31 - direction
	GroundStation48 - direction
	GroundStation34 - direction
	Star56 - direction
	Star40 - direction
	GroundStation35 - direction
	Star38 - direction
	Star36 - direction
	GroundStation39 - direction
	GroundStation64 - direction
	GroundStation32 - direction
	Star10 - direction
	Star1 - direction
	GroundStation63 - direction
	Star0 - direction
	Star67 - direction
	Star9 - direction
	GroundStation18 - direction
	Star41 - direction
	Star5 - direction
	Star72 - direction
	GroundStation47 - direction
	GroundStation26 - direction
	Star21 - direction
	Star70 - direction
	Star50 - direction
	GroundStation13 - direction
	Phenomenon80 - direction
	Star81 - direction
	Planet82 - direction
	Planet83 - direction
	Planet84 - direction
	Phenomenon85 - direction
	Planet86 - direction
	Phenomenon87 - direction
	Phenomenon88 - direction
	Planet89 - direction
	Star90 - direction
	Planet91 - direction
	Star92 - direction
	Star93 - direction
	Phenomenon94 - direction
	Planet95 - direction
	Phenomenon96 - direction
	Phenomenon97 - direction
	Star98 - direction
	Planet99 - direction
	Planet100 - direction
	Planet101 - direction
	Phenomenon102 - direction
	Phenomenon103 - direction
	Planet104 - direction
	Star105 - direction
	Planet106 - direction
	Phenomenon107 - direction
	Star108 - direction
	Planet109 - direction
	Star110 - direction
	Phenomenon111 - direction
	Planet112 - direction
	Phenomenon113 - direction
	Star114 - direction
	Phenomenon115 - direction
	Planet116 - direction
	Planet117 - direction
	Star118 - direction
	Star119 - direction
	Phenomenon120 - direction
	Planet121 - direction
	Star122 - direction
	Star123 - direction
	Planet124 - direction
	Star125 - direction
	Planet126 - direction
	Planet127 - direction
	Phenomenon128 - direction
	Star129 - direction
	Phenomenon130 - direction
	Star131 - direction
	Planet132 - direction
	Star133 - direction
	Star134 - direction
	Star135 - direction
	Phenomenon136 - direction
	Planet137 - direction
	Phenomenon138 - direction
	Phenomenon139 - direction
)
(:init
	(supports instrument0 infrared1)
	(calibration_target instrument0 GroundStation60)
	(calibration_target instrument0 Star70)
	(calibration_target instrument0 Star33)
	(calibration_target instrument0 GroundStation58)
	(calibration_target instrument0 GroundStation4)
	(calibration_target instrument0 Star43)
	(calibration_target instrument0 Star72)
	(calibration_target instrument0 Star12)
	(calibration_target instrument0 Star54)
	(calibration_target instrument0 Star0)
	(calibration_target instrument0 Star19)
	(calibration_target instrument0 GroundStation45)
	(calibration_target instrument0 GroundStation49)
	(calibration_target instrument0 Star69)
	(calibration_target instrument0 Star14)
	(calibration_target instrument0 GroundStation78)
	(calibration_target instrument0 Star1)
	(calibration_target instrument0 GroundStation48)
	(calibration_target instrument0 Star36)
	(calibration_target instrument0 GroundStation31)
	(calibration_target instrument0 Star37)
	(calibration_target instrument0 GroundStation27)
	(supports instrument1 infrared1)
	(calibration_target instrument1 Star9)
	(calibration_target instrument1 Star56)
	(calibration_target instrument1 Star50)
	(calibration_target instrument1 GroundStation57)
	(calibration_target instrument1 GroundStation60)
	(calibration_target instrument1 GroundStation78)
	(calibration_target instrument1 Star62)
	(calibration_target instrument1 GroundStation18)
	(calibration_target instrument1 GroundStation7)
	(calibration_target instrument1 GroundStation35)
	(calibration_target instrument1 Star40)
	(calibration_target instrument1 Star77)
	(calibration_target instrument1 Star29)
	(calibration_target instrument1 Star24)
	(calibration_target instrument1 Star16)
	(calibration_target instrument1 Star70)
	(calibration_target instrument1 GroundStation58)
	(calibration_target instrument1 Star3)
	(calibration_target instrument1 Star52)
	(calibration_target instrument1 Star1)
	(calibration_target instrument1 Star51)
	(calibration_target instrument1 GroundStation48)
	(calibration_target instrument1 Star37)
	(calibration_target instrument1 GroundStation65)
	(calibration_target instrument1 GroundStation17)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Planet117)
	(supports instrument2 image3)
	(supports instrument2 infrared1)
	(calibration_target instrument2 GroundStation66)
	(calibration_target instrument2 Star10)
	(calibration_target instrument2 GroundStation63)
	(calibration_target instrument2 GroundStation78)
	(calibration_target instrument2 GroundStation4)
	(calibration_target instrument2 GroundStation2)
	(calibration_target instrument2 GroundStation44)
	(calibration_target instrument2 Star24)
	(calibration_target instrument2 Star16)
	(calibration_target instrument2 Star33)
	(calibration_target instrument2 Star53)
	(calibration_target instrument2 Star5)
	(calibration_target instrument2 Star52)
	(calibration_target instrument2 Star21)
	(calibration_target instrument2 Star74)
	(calibration_target instrument2 Star6)
	(calibration_target instrument2 GroundStation35)
	(calibration_target instrument2 Star29)
	(calibration_target instrument2 Star41)
	(supports instrument3 infrared1)
	(supports instrument3 image3)
	(calibration_target instrument3 GroundStation18)
	(calibration_target instrument3 GroundStation58)
	(calibration_target instrument3 Star74)
	(calibration_target instrument3 GroundStation26)
	(calibration_target instrument3 Star70)
	(calibration_target instrument3 Star62)
	(calibration_target instrument3 GroundStation4)
	(calibration_target instrument3 Star16)
	(calibration_target instrument3 Star41)
	(calibration_target instrument3 Star10)
	(calibration_target instrument3 Star21)
	(calibration_target instrument3 Star53)
	(calibration_target instrument3 GroundStation78)
	(calibration_target instrument3 GroundStation20)
	(calibration_target instrument3 GroundStation34)
	(calibration_target instrument3 Star6)
	(calibration_target instrument3 Star29)
	(calibration_target instrument3 Star77)
	(calibration_target instrument3 Star1)
	(supports instrument4 image3)
	(supports instrument4 thermograph0)
	(supports instrument4 infrared2)
	(calibration_target instrument4 GroundStation31)
	(calibration_target instrument4 GroundStation44)
	(calibration_target instrument4 Star9)
	(calibration_target instrument4 Star59)
	(calibration_target instrument4 Star3)
	(calibration_target instrument4 Star69)
	(calibration_target instrument4 Star62)
	(calibration_target instrument4 Star41)
	(calibration_target instrument4 Star25)
	(calibration_target instrument4 GroundStation48)
	(calibration_target instrument4 Star22)
	(calibration_target instrument4 Star24)
	(calibration_target instrument4 GroundStation63)
	(supports instrument5 infrared4)
	(calibration_target instrument5 Star53)
	(calibration_target instrument5 Star1)
	(calibration_target instrument5 Star10)
	(calibration_target instrument5 Star43)
	(calibration_target instrument5 GroundStation79)
	(calibration_target instrument5 Star3)
	(calibration_target instrument5 GroundStation31)
	(calibration_target instrument5 Star29)
	(calibration_target instrument5 Star24)
	(calibration_target instrument5 GroundStation48)
	(calibration_target instrument5 Star21)
	(supports instrument6 image3)
	(supports instrument6 thermograph0)
	(calibration_target instrument6 GroundStation49)
	(calibration_target instrument6 Star52)
	(calibration_target instrument6 Star59)
	(calibration_target instrument6 GroundStation7)
	(calibration_target instrument6 Star3)
	(calibration_target instrument6 Star5)
	(calibration_target instrument6 GroundStation32)
	(calibration_target instrument6 GroundStation78)
	(calibration_target instrument6 Star1)
	(calibration_target instrument6 Star12)
	(calibration_target instrument6 Star77)
	(calibration_target instrument6 Star10)
	(calibration_target instrument6 Star28)
	(calibration_target instrument6 Star51)
	(calibration_target instrument6 Star21)
	(calibration_target instrument6 Star62)
	(calibration_target instrument6 GroundStation44)
	(calibration_target instrument6 Star41)
	(calibration_target instrument6 GroundStation76)
	(calibration_target instrument6 GroundStation8)
	(on_board instrument2 satellite1)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation17)
	(supports instrument7 thermograph0)
	(calibration_target instrument7 Star36)
	(calibration_target instrument7 GroundStation4)
	(calibration_target instrument7 Star30)
	(calibration_target instrument7 Star29)
	(calibration_target instrument7 GroundStation75)
	(calibration_target instrument7 Star56)
	(calibration_target instrument7 Star67)
	(calibration_target instrument7 Star10)
	(calibration_target instrument7 GroundStation27)
	(calibration_target instrument7 GroundStation2)
	(calibration_target instrument7 GroundStation11)
	(calibration_target instrument7 GroundStation44)
	(calibration_target instrument7 GroundStation13)
	(calibration_target instrument7 GroundStation79)
	(calibration_target instrument7 Star71)
	(calibration_target instrument7 GroundStation39)
	(calibration_target instrument7 Star40)
	(calibration_target instrument7 GroundStation61)
	(calibration_target instrument7 Star19)
	(calibration_target instrument7 Star69)
	(calibration_target instrument7 Star38)
	(supports instrument8 infrared4)
	(calibration_target instrument8 GroundStation66)
	(calibration_target instrument8 Star12)
	(calibration_target instrument8 Star36)
	(calibration_target instrument8 GroundStation18)
	(calibration_target instrument8 Star71)
	(calibration_target instrument8 Star21)
	(calibration_target instrument8 Star25)
	(calibration_target instrument8 Star51)
	(calibration_target instrument8 Star46)
	(calibration_target instrument8 Star74)
	(calibration_target instrument8 Star30)
	(calibration_target instrument8 GroundStation11)
	(calibration_target instrument8 GroundStation45)
	(calibration_target instrument8 GroundStation13)
	(calibration_target instrument8 Star10)
	(calibration_target instrument8 Star53)
	(calibration_target instrument8 Star43)
	(calibration_target instrument8 GroundStation65)
	(supports instrument9 infrared4)
	(supports instrument9 infrared2)
	(supports instrument9 thermograph0)
	(calibration_target instrument9 Star77)
	(calibration_target instrument9 GroundStation79)
	(calibration_target instrument9 Star41)
	(calibration_target instrument9 GroundStation26)
	(calibration_target instrument9 Star38)
	(calibration_target instrument9 Star12)
	(calibration_target instrument9 GroundStation45)
	(calibration_target instrument9 Star43)
	(on_board instrument7 satellite2)
	(on_board instrument8 satellite2)
	(on_board instrument9 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star12)
	(supports instrument10 thermograph0)
	(calibration_target instrument10 GroundStation64)
	(calibration_target instrument10 Star28)
	(calibration_target instrument10 Star55)
	(calibration_target instrument10 GroundStation18)
	(calibration_target instrument10 Star53)
	(calibration_target instrument10 Star52)
	(calibration_target instrument10 Star59)
	(calibration_target instrument10 GroundStation60)
	(calibration_target instrument10 Star21)
	(calibration_target instrument10 Star0)
	(calibration_target instrument10 Star37)
	(calibration_target instrument10 Star29)
	(calibration_target instrument10 GroundStation45)
	(calibration_target instrument10 Star19)
	(calibration_target instrument10 GroundStation11)
	(calibration_target instrument10 GroundStation66)
	(supports instrument11 image3)
	(calibration_target instrument11 Star68)
	(calibration_target instrument11 Star29)
	(calibration_target instrument11 Star55)
	(calibration_target instrument11 Star70)
	(calibration_target instrument11 Star71)
	(calibration_target instrument11 Star14)
	(calibration_target instrument11 GroundStation32)
	(calibration_target instrument11 Star5)
	(calibration_target instrument11 Star28)
	(calibration_target instrument11 Star59)
	(calibration_target instrument11 Star33)
	(calibration_target instrument11 Star19)
	(supports instrument12 infrared2)
	(calibration_target instrument12 Star52)
	(calibration_target instrument12 GroundStation26)
	(calibration_target instrument12 GroundStation79)
	(calibration_target instrument12 Star9)
	(calibration_target instrument12 GroundStation11)
	(calibration_target instrument12 Star10)
	(calibration_target instrument12 GroundStation58)
	(calibration_target instrument12 Star55)
	(calibration_target instrument12 Star24)
	(calibration_target instrument12 GroundStation8)
	(supports instrument13 thermograph0)
	(supports instrument13 infrared2)
	(supports instrument13 infrared1)
	(calibration_target instrument13 Star30)
	(calibration_target instrument13 GroundStation13)
	(calibration_target instrument13 Star73)
	(calibration_target instrument13 GroundStation18)
	(calibration_target instrument13 Star70)
	(calibration_target instrument13 GroundStation27)
	(calibration_target instrument13 Star46)
	(calibration_target instrument13 Star25)
	(calibration_target instrument13 GroundStation57)
	(calibration_target instrument13 Star59)
	(calibration_target instrument13 Star62)
	(calibration_target instrument13 Star0)
	(calibration_target instrument13 GroundStation79)
	(calibration_target instrument13 GroundStation48)
	(calibration_target instrument13 GroundStation58)
	(calibration_target instrument13 GroundStation31)
	(calibration_target instrument13 Star12)
	(calibration_target instrument13 Star43)
	(calibration_target instrument13 GroundStation4)
	(calibration_target instrument13 Star68)
	(calibration_target instrument13 GroundStation61)
	(calibration_target instrument13 Star77)
	(calibration_target instrument13 GroundStation66)
	(calibration_target instrument13 Star51)
	(calibration_target instrument13 Star28)
	(calibration_target instrument13 GroundStation8)
	(on_board instrument10 satellite3)
	(on_board instrument11 satellite3)
	(on_board instrument12 satellite3)
	(on_board instrument13 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star77)
	(supports instrument14 thermograph0)
	(supports instrument14 infrared1)
	(calibration_target instrument14 GroundStation18)
	(calibration_target instrument14 Star72)
	(calibration_target instrument14 Star41)
	(calibration_target instrument14 GroundStation58)
	(calibration_target instrument14 Star12)
	(calibration_target instrument14 Star68)
	(calibration_target instrument14 Star1)
	(calibration_target instrument14 GroundStation11)
	(calibration_target instrument14 GroundStation57)
	(calibration_target instrument14 GroundStation79)
	(calibration_target instrument14 Star16)
	(calibration_target instrument14 Star73)
	(calibration_target instrument14 Star52)
	(calibration_target instrument14 GroundStation32)
	(calibration_target instrument14 Star69)
	(supports instrument15 infrared4)
	(calibration_target instrument15 GroundStation26)
	(calibration_target instrument15 GroundStation58)
	(calibration_target instrument15 GroundStation31)
	(calibration_target instrument15 Star74)
	(calibration_target instrument15 Star22)
	(calibration_target instrument15 Star36)
	(calibration_target instrument15 GroundStation49)
	(calibration_target instrument15 Star15)
	(calibration_target instrument15 Star24)
	(calibration_target instrument15 Star3)
	(calibration_target instrument15 Star25)
	(calibration_target instrument15 Star50)
	(calibration_target instrument15 Star14)
	(calibration_target instrument15 GroundStation57)
	(calibration_target instrument15 GroundStation4)
	(calibration_target instrument15 Star10)
	(calibration_target instrument15 Star38)
	(calibration_target instrument15 Star28)
	(calibration_target instrument15 Star23)
	(calibration_target instrument15 Star59)
	(calibration_target instrument15 Star21)
	(calibration_target instrument15 GroundStation61)
	(calibration_target instrument15 Star73)
	(supports instrument16 infrared4)
	(supports instrument16 image3)
	(supports instrument16 thermograph0)
	(calibration_target instrument16 GroundStation32)
	(calibration_target instrument16 GroundStation27)
	(calibration_target instrument16 Star46)
	(calibration_target instrument16 GroundStation44)
	(calibration_target instrument16 Star56)
	(calibration_target instrument16 Star36)
	(calibration_target instrument16 GroundStation31)
	(calibration_target instrument16 GroundStation61)
	(calibration_target instrument16 GroundStation48)
	(calibration_target instrument16 Star50)
	(calibration_target instrument16 GroundStation20)
	(calibration_target instrument16 GroundStation11)
	(calibration_target instrument16 Star73)
	(calibration_target instrument16 GroundStation39)
	(calibration_target instrument16 GroundStation34)
	(calibration_target instrument16 Star23)
	(calibration_target instrument16 Star69)
	(calibration_target instrument16 Star10)
	(on_board instrument14 satellite4)
	(on_board instrument15 satellite4)
	(on_board instrument16 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star25)
	(supports instrument17 image3)
	(supports instrument17 thermograph0)
	(supports instrument17 infrared1)
	(calibration_target instrument17 Star29)
	(calibration_target instrument17 GroundStation64)
	(calibration_target instrument17 GroundStation49)
	(calibration_target instrument17 GroundStation32)
	(calibration_target instrument17 Star69)
	(calibration_target instrument17 GroundStation45)
	(supports instrument18 image3)
	(supports instrument18 infrared1)
	(supports instrument18 infrared2)
	(calibration_target instrument18 GroundStation20)
	(calibration_target instrument18 GroundStation34)
	(calibration_target instrument18 Star14)
	(calibration_target instrument18 Star46)
	(calibration_target instrument18 Star6)
	(calibration_target instrument18 GroundStation13)
	(calibration_target instrument18 Star36)
	(calibration_target instrument18 Star68)
	(calibration_target instrument18 Star50)
	(supports instrument19 thermograph0)
	(calibration_target instrument19 GroundStation35)
	(calibration_target instrument19 Star3)
	(calibration_target instrument19 GroundStation58)
	(calibration_target instrument19 Star19)
	(calibration_target instrument19 GroundStation66)
	(calibration_target instrument19 Star41)
	(calibration_target instrument19 GroundStation60)
	(calibration_target instrument19 GroundStation34)
	(calibration_target instrument19 Star74)
	(calibration_target instrument19 Star38)
	(calibration_target instrument19 GroundStation44)
	(calibration_target instrument19 Star30)
	(calibration_target instrument19 GroundStation75)
	(calibration_target instrument19 Star73)
	(calibration_target instrument19 Star12)
	(calibration_target instrument19 Star25)
	(calibration_target instrument19 GroundStation57)
	(calibration_target instrument19 Star46)
	(on_board instrument17 satellite5)
	(on_board instrument18 satellite5)
	(on_board instrument19 satellite5)
	(power_avail satellite5)
	(pointing satellite5 GroundStation78)
	(supports instrument20 thermograph0)
	(supports instrument20 infrared2)
	(supports instrument20 infrared4)
	(calibration_target instrument20 GroundStation8)
	(calibration_target instrument20 Star36)
	(calibration_target instrument20 Star50)
	(calibration_target instrument20 Star70)
	(calibration_target instrument20 Star15)
	(calibration_target instrument20 Star74)
	(calibration_target instrument20 Star29)
	(calibration_target instrument20 Star30)
	(calibration_target instrument20 Star16)
	(calibration_target instrument20 GroundStation78)
	(calibration_target instrument20 GroundStation34)
	(calibration_target instrument20 Star38)
	(calibration_target instrument20 GroundStation64)
	(calibration_target instrument20 GroundStation48)
	(calibration_target instrument20 Star24)
	(supports instrument21 infrared4)
	(supports instrument21 infrared2)
	(supports instrument21 image3)
	(calibration_target instrument21 GroundStation7)
	(calibration_target instrument21 GroundStation18)
	(calibration_target instrument21 Star69)
	(calibration_target instrument21 Star15)
	(calibration_target instrument21 Star12)
	(calibration_target instrument21 Star14)
	(calibration_target instrument21 GroundStation48)
	(calibration_target instrument21 GroundStation49)
	(calibration_target instrument21 GroundStation79)
	(calibration_target instrument21 Star22)
	(calibration_target instrument21 GroundStation76)
	(calibration_target instrument21 Star77)
	(calibration_target instrument21 Star21)
	(calibration_target instrument21 GroundStation26)
	(calibration_target instrument21 GroundStation44)
	(calibration_target instrument21 GroundStation63)
	(calibration_target instrument21 Star41)
	(calibration_target instrument21 GroundStation57)
	(calibration_target instrument21 Star55)
	(calibration_target instrument21 GroundStation13)
	(calibration_target instrument21 Star16)
	(calibration_target instrument21 Star5)
	(supports instrument22 thermograph0)
	(supports instrument22 image3)
	(calibration_target instrument22 Star22)
	(calibration_target instrument22 GroundStation35)
	(supports instrument23 thermograph0)
	(supports instrument23 image3)
	(supports instrument23 infrared1)
	(calibration_target instrument23 Star36)
	(calibration_target instrument23 Star1)
	(calibration_target instrument23 Star38)
	(calibration_target instrument23 GroundStation35)
	(calibration_target instrument23 Star40)
	(calibration_target instrument23 Star56)
	(calibration_target instrument23 GroundStation34)
	(calibration_target instrument23 GroundStation32)
	(calibration_target instrument23 Star67)
	(calibration_target instrument23 GroundStation48)
	(calibration_target instrument23 GroundStation31)
	(calibration_target instrument23 GroundStation78)
	(calibration_target instrument23 Star41)
	(calibration_target instrument23 Star74)
	(calibration_target instrument23 Star19)
	(calibration_target instrument23 GroundStation13)
	(calibration_target instrument23 Star43)
	(calibration_target instrument23 Star77)
	(calibration_target instrument23 GroundStation2)
	(calibration_target instrument23 Star6)
	(calibration_target instrument23 Star0)
	(calibration_target instrument23 Star33)
	(calibration_target instrument23 GroundStation39)
	(calibration_target instrument23 GroundStation63)
	(supports instrument24 image3)
	(supports instrument24 infrared2)
	(calibration_target instrument24 GroundStation13)
	(calibration_target instrument24 Star50)
	(calibration_target instrument24 Star70)
	(calibration_target instrument24 Star21)
	(calibration_target instrument24 GroundStation26)
	(calibration_target instrument24 GroundStation47)
	(calibration_target instrument24 Star72)
	(calibration_target instrument24 Star5)
	(calibration_target instrument24 Star41)
	(calibration_target instrument24 GroundStation18)
	(calibration_target instrument24 Star9)
	(calibration_target instrument24 Star67)
	(calibration_target instrument24 Star0)
	(calibration_target instrument24 GroundStation63)
	(calibration_target instrument24 Star1)
	(calibration_target instrument24 Star10)
	(calibration_target instrument24 GroundStation32)
	(calibration_target instrument24 GroundStation64)
	(calibration_target instrument24 GroundStation39)
	(on_board instrument20 satellite6)
	(on_board instrument21 satellite6)
	(on_board instrument22 satellite6)
	(on_board instrument23 satellite6)
	(on_board instrument24 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Phenomenon80)
)
(:goal (and
	(pointing satellite1 GroundStation57)
	(pointing satellite2 Planet117)
	(pointing satellite3 Planet117)
	(have_image Phenomenon80 infrared2)
	(have_image Star81 infrared2)
	(have_image Planet82 thermograph0)
	(have_image Planet83 image3)
	(have_image Planet84 image3)
	(have_image Phenomenon85 image3)
	(have_image Planet86 thermograph0)
	(have_image Phenomenon87 thermograph0)
	(have_image Phenomenon88 infrared1)
	(have_image Planet89 image3)
	(have_image Star90 image3)
	(have_image Planet91 infrared4)
	(have_image Star92 thermograph0)
	(have_image Star93 thermograph0)
	(have_image Phenomenon94 image3)
	(have_image Planet95 thermograph0)
	(have_image Phenomenon96 image3)
	(have_image Phenomenon97 thermograph0)
	(have_image Star98 thermograph0)
	(have_image Planet99 infrared2)
	(have_image Planet100 image3)
	(have_image Planet101 infrared2)
	(have_image Phenomenon102 infrared2)
	(have_image Phenomenon103 infrared2)
	(have_image Planet104 image3)
	(have_image Star105 infrared4)
	(have_image Planet106 infrared2)
	(have_image Phenomenon107 infrared4)
	(have_image Star108 thermograph0)
	(have_image Planet109 thermograph0)
	(have_image Star110 image3)
	(have_image Phenomenon111 infrared4)
	(have_image Planet112 infrared4)
	(have_image Phenomenon113 infrared2)
	(have_image Star114 infrared4)
	(have_image Phenomenon115 infrared4)
	(have_image Planet116 infrared2)
	(have_image Planet117 infrared2)
	(have_image Star118 infrared4)
	(have_image Star119 thermograph0)
	(have_image Phenomenon120 infrared2)
	(have_image Planet121 infrared4)
	(have_image Star122 infrared2)
	(have_image Star123 infrared1)
	(have_image Planet124 infrared4)
	(have_image Star125 infrared2)
	(have_image Planet126 infrared1)
	(have_image Planet127 image3)
	(have_image Phenomenon128 infrared2)
	(have_image Star129 infrared1)
	(have_image Phenomenon130 image3)
	(have_image Star131 infrared4)
	(have_image Planet132 infrared4)
	(have_image Star133 infrared2)
	(have_image Star134 image3)
	(have_image Star135 thermograph0)
	(have_image Phenomenon136 image3)
	(have_image Planet137 thermograph0)
	(have_image Phenomenon138 infrared1)
	(have_image Phenomenon139 infrared2)
))

)
