(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	satellite1 - satellite
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	satellite2 - satellite
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	satellite3 - satellite
	instrument9 - instrument
	instrument10 - instrument
	satellite4 - satellite
	instrument11 - instrument
	satellite5 - satellite
	instrument12 - instrument
	satellite6 - satellite
	instrument13 - instrument
	instrument14 - instrument
	image0 - mode
	thermograph4 - mode
	thermograph1 - mode
	infrared3 - mode
	thermograph2 - mode
	GroundStation4 - direction
	Star14 - direction
	GroundStation25 - direction
	GroundStation77 - direction
	GroundStation79 - direction
	GroundStation73 - direction
	Star26 - direction
	Star62 - direction
	Star42 - direction
	Star23 - direction
	GroundStation61 - direction
	Star15 - direction
	Star28 - direction
	GroundStation53 - direction
	Star58 - direction
	Star13 - direction
	Star30 - direction
	Star38 - direction
	GroundStation72 - direction
	Star0 - direction
	GroundStation34 - direction
	GroundStation50 - direction
	Star57 - direction
	GroundStation45 - direction
	GroundStation16 - direction
	Star69 - direction
	GroundStation78 - direction
	Star31 - direction
	GroundStation17 - direction
	Star59 - direction
	GroundStation63 - direction
	GroundStation24 - direction
	Star35 - direction
	Star8 - direction
	Star67 - direction
	GroundStation1 - direction
	GroundStation74 - direction
	Star43 - direction
	Star33 - direction
	Star54 - direction
	GroundStation66 - direction
	Star20 - direction
	Star46 - direction
	GroundStation47 - direction
	Star75 - direction
	GroundStation52 - direction
	Star2 - direction
	Star19 - direction
	GroundStation68 - direction
	Star21 - direction
	GroundStation11 - direction
	GroundStation49 - direction
	Star64 - direction
	GroundStation44 - direction
	GroundStation65 - direction
	Star51 - direction
	GroundStation18 - direction
	GroundStation56 - direction
	Star9 - direction
	GroundStation6 - direction
	Star10 - direction
	Star5 - direction
	GroundStation39 - direction
	Star27 - direction
	Star76 - direction
	GroundStation3 - direction
	Star55 - direction
	GroundStation29 - direction
	GroundStation48 - direction
	GroundStation70 - direction
	Star41 - direction
	Star37 - direction
	GroundStation7 - direction
	Star60 - direction
	Star12 - direction
	Star36 - direction
	GroundStation32 - direction
	Star40 - direction
	Star71 - direction
	Star22 - direction
	Star80 - direction
	Phenomenon81 - direction
	Star82 - direction
	Planet83 - direction
	Planet84 - direction
	Planet85 - direction
	Planet86 - direction
	Star87 - direction
	Planet88 - direction
	Star89 - direction
	Planet90 - direction
	Planet91 - direction
	Phenomenon92 - direction
	Phenomenon93 - direction
	Phenomenon94 - direction
	Phenomenon95 - direction
	Phenomenon96 - direction
	Star97 - direction
	Star98 - direction
	Star99 - direction
	Phenomenon100 - direction
	Planet101 - direction
	Star102 - direction
	Star103 - direction
	Phenomenon104 - direction
	Planet105 - direction
	Star106 - direction
	Planet107 - direction
	Star108 - direction
	Star109 - direction
	Star110 - direction
	Planet111 - direction
	Phenomenon112 - direction
	Planet113 - direction
	Planet114 - direction
	Planet115 - direction
	Phenomenon116 - direction
	Phenomenon117 - direction
	Phenomenon118 - direction
	Phenomenon119 - direction
	Star120 - direction
	Phenomenon121 - direction
	Star122 - direction
	Phenomenon123 - direction
	Star124 - direction
	Phenomenon125 - direction
	Star126 - direction
	Phenomenon127 - direction
	Star128 - direction
	Star129 - direction
	Phenomenon130 - direction
	Planet131 - direction
	Planet132 - direction
	Star133 - direction
	Phenomenon134 - direction
	Star135 - direction
	Planet136 - direction
	Phenomenon137 - direction
	Planet138 - direction
	Star139 - direction
)
(:init
	(supports instrument0 infrared3)
	(calibration_target instrument0 GroundStation65)
	(calibration_target instrument0 GroundStation6)
	(calibration_target instrument0 GroundStation78)
	(calibration_target instrument0 GroundStation61)
	(calibration_target instrument0 GroundStation73)
	(calibration_target instrument0 GroundStation16)
	(calibration_target instrument0 Star8)
	(calibration_target instrument0 GroundStation3)
	(calibration_target instrument0 Star27)
	(calibration_target instrument0 Star60)
	(calibration_target instrument0 Star42)
	(calibration_target instrument0 Star62)
	(calibration_target instrument0 GroundStation66)
	(calibration_target instrument0 GroundStation56)
	(calibration_target instrument0 GroundStation24)
	(on_board instrument0 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Planet85)
	(supports instrument1 thermograph2)
	(supports instrument1 thermograph4)
	(supports instrument1 infrared3)
	(calibration_target instrument1 GroundStation11)
	(calibration_target instrument1 GroundStation49)
	(calibration_target instrument1 Star64)
	(calibration_target instrument1 GroundStation39)
	(calibration_target instrument1 Star13)
	(calibration_target instrument1 Star46)
	(calibration_target instrument1 Star54)
	(calibration_target instrument1 Star60)
	(calibration_target instrument1 GroundStation1)
	(calibration_target instrument1 Star9)
	(calibration_target instrument1 GroundStation29)
	(calibration_target instrument1 Star67)
	(calibration_target instrument1 Star19)
	(calibration_target instrument1 Star37)
	(calibration_target instrument1 GroundStation66)
	(calibration_target instrument1 GroundStation56)
	(calibration_target instrument1 Star59)
	(calibration_target instrument1 Star2)
	(calibration_target instrument1 GroundStation18)
	(calibration_target instrument1 Star43)
	(calibration_target instrument1 GroundStation7)
	(calibration_target instrument1 Star55)
	(calibration_target instrument1 Star26)
	(calibration_target instrument1 Star8)
	(supports instrument2 thermograph2)
	(supports instrument2 thermograph4)
	(supports instrument2 infrared3)
	(calibration_target instrument2 GroundStation11)
	(calibration_target instrument2 Star2)
	(calibration_target instrument2 GroundStation44)
	(calibration_target instrument2 Star33)
	(calibration_target instrument2 Star42)
	(calibration_target instrument2 Star62)
	(calibration_target instrument2 Star43)
	(calibration_target instrument2 GroundStation17)
	(calibration_target instrument2 Star59)
	(calibration_target instrument2 Star58)
	(calibration_target instrument2 Star22)
	(supports instrument3 image0)
	(calibration_target instrument3 Star8)
	(calibration_target instrument3 Star5)
	(calibration_target instrument3 GroundStation53)
	(calibration_target instrument3 Star69)
	(calibration_target instrument3 Star42)
	(calibration_target instrument3 GroundStation1)
	(calibration_target instrument3 GroundStation68)
	(calibration_target instrument3 GroundStation29)
	(calibration_target instrument3 Star15)
	(calibration_target instrument3 GroundStation6)
	(calibration_target instrument3 Star51)
	(calibration_target instrument3 GroundStation56)
	(calibration_target instrument3 GroundStation63)
	(supports instrument4 thermograph1)
	(supports instrument4 infrared3)
	(supports instrument4 image0)
	(calibration_target instrument4 Star59)
	(calibration_target instrument4 GroundStation53)
	(calibration_target instrument4 GroundStation68)
	(calibration_target instrument4 Star28)
	(calibration_target instrument4 Star15)
	(calibration_target instrument4 Star46)
	(calibration_target instrument4 GroundStation61)
	(calibration_target instrument4 Star60)
	(calibration_target instrument4 GroundStation17)
	(calibration_target instrument4 Star23)
	(calibration_target instrument4 Star0)
	(calibration_target instrument4 GroundStation24)
	(calibration_target instrument4 GroundStation16)
	(calibration_target instrument4 Star27)
	(calibration_target instrument4 Star51)
	(calibration_target instrument4 GroundStation48)
	(supports instrument5 thermograph1)
	(calibration_target instrument5 Star31)
	(calibration_target instrument5 Star33)
	(calibration_target instrument5 GroundStation78)
	(calibration_target instrument5 Star69)
	(calibration_target instrument5 GroundStation65)
	(calibration_target instrument5 Star9)
	(calibration_target instrument5 Star5)
	(calibration_target instrument5 GroundStation16)
	(calibration_target instrument5 Star59)
	(calibration_target instrument5 GroundStation45)
	(calibration_target instrument5 GroundStation56)
	(calibration_target instrument5 Star57)
	(calibration_target instrument5 GroundStation50)
	(calibration_target instrument5 GroundStation63)
	(calibration_target instrument5 GroundStation24)
	(calibration_target instrument5 GroundStation34)
	(calibration_target instrument5 Star8)
	(calibration_target instrument5 Star0)
	(calibration_target instrument5 GroundStation47)
	(calibration_target instrument5 GroundStation72)
	(calibration_target instrument5 Star38)
	(calibration_target instrument5 Star30)
	(calibration_target instrument5 Star13)
	(calibration_target instrument5 Star58)
	(on_board instrument1 satellite1)
	(on_board instrument2 satellite1)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Phenomenon81)
	(supports instrument6 thermograph2)
	(supports instrument6 thermograph4)
	(supports instrument6 infrared3)
	(calibration_target instrument6 GroundStation68)
	(calibration_target instrument6 Star64)
	(calibration_target instrument6 Star75)
	(calibration_target instrument6 Star59)
	(calibration_target instrument6 GroundStation17)
	(supports instrument7 thermograph1)
	(calibration_target instrument7 Star64)
	(calibration_target instrument7 GroundStation39)
	(calibration_target instrument7 Star10)
	(calibration_target instrument7 GroundStation63)
	(supports instrument8 infrared3)
	(supports instrument8 thermograph4)
	(calibration_target instrument8 GroundStation24)
	(calibration_target instrument8 GroundStation74)
	(calibration_target instrument8 Star43)
	(calibration_target instrument8 GroundStation65)
	(on_board instrument6 satellite2)
	(on_board instrument7 satellite2)
	(on_board instrument8 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Phenomenon104)
	(supports instrument9 image0)
	(supports instrument9 thermograph4)
	(supports instrument9 thermograph2)
	(calibration_target instrument9 Star35)
	(calibration_target instrument9 Star12)
	(calibration_target instrument9 GroundStation68)
	(supports instrument10 infrared3)
	(supports instrument10 thermograph4)
	(calibration_target instrument10 Star60)
	(calibration_target instrument10 GroundStation49)
	(calibration_target instrument10 GroundStation66)
	(on_board instrument9 satellite3)
	(on_board instrument10 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Phenomenon104)
	(supports instrument11 thermograph1)
	(calibration_target instrument11 Star43)
	(calibration_target instrument11 Star19)
	(calibration_target instrument11 Star40)
	(calibration_target instrument11 GroundStation74)
	(calibration_target instrument11 GroundStation1)
	(calibration_target instrument11 GroundStation3)
	(calibration_target instrument11 GroundStation68)
	(calibration_target instrument11 Star67)
	(calibration_target instrument11 Star75)
	(calibration_target instrument11 Star8)
	(on_board instrument11 satellite4)
	(power_avail satellite4)
	(pointing satellite4 GroundStation45)
	(supports instrument12 thermograph4)
	(calibration_target instrument12 GroundStation47)
	(calibration_target instrument12 Star46)
	(calibration_target instrument12 Star5)
	(calibration_target instrument12 Star9)
	(calibration_target instrument12 GroundStation11)
	(calibration_target instrument12 Star20)
	(calibration_target instrument12 GroundStation66)
	(calibration_target instrument12 Star54)
	(calibration_target instrument12 Star2)
	(calibration_target instrument12 Star33)
	(on_board instrument12 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star133)
	(supports instrument13 thermograph2)
	(supports instrument13 thermograph4)
	(supports instrument13 image0)
	(calibration_target instrument13 Star51)
	(calibration_target instrument13 GroundStation65)
	(calibration_target instrument13 GroundStation44)
	(calibration_target instrument13 Star64)
	(calibration_target instrument13 GroundStation49)
	(calibration_target instrument13 GroundStation70)
	(calibration_target instrument13 GroundStation11)
	(calibration_target instrument13 Star21)
	(calibration_target instrument13 GroundStation68)
	(calibration_target instrument13 Star19)
	(calibration_target instrument13 Star5)
	(calibration_target instrument13 Star2)
	(calibration_target instrument13 Star60)
	(calibration_target instrument13 GroundStation52)
	(calibration_target instrument13 GroundStation56)
	(calibration_target instrument13 GroundStation18)
	(calibration_target instrument13 Star75)
	(supports instrument14 infrared3)
	(calibration_target instrument14 Star22)
	(calibration_target instrument14 Star71)
	(calibration_target instrument14 Star40)
	(calibration_target instrument14 GroundStation32)
	(calibration_target instrument14 Star36)
	(calibration_target instrument14 Star12)
	(calibration_target instrument14 Star60)
	(calibration_target instrument14 GroundStation7)
	(calibration_target instrument14 Star37)
	(calibration_target instrument14 Star41)
	(calibration_target instrument14 GroundStation70)
	(calibration_target instrument14 GroundStation48)
	(calibration_target instrument14 GroundStation29)
	(calibration_target instrument14 Star55)
	(calibration_target instrument14 GroundStation3)
	(calibration_target instrument14 Star76)
	(calibration_target instrument14 Star27)
	(calibration_target instrument14 GroundStation39)
	(calibration_target instrument14 Star5)
	(calibration_target instrument14 Star10)
	(calibration_target instrument14 GroundStation6)
	(calibration_target instrument14 Star9)
	(calibration_target instrument14 GroundStation56)
	(calibration_target instrument14 GroundStation18)
	(on_board instrument13 satellite6)
	(on_board instrument14 satellite6)
	(power_avail satellite6)
	(pointing satellite6 GroundStation61)
)
(:goal (and
	(pointing satellite4 GroundStation7)
	(pointing satellite5 Star71)
	(have_image Star80 infrared3)
	(have_image Phenomenon81 infrared3)
	(have_image Star82 image0)
	(have_image Planet83 image0)
	(have_image Planet84 thermograph2)
	(have_image Planet85 infrared3)
	(have_image Planet86 infrared3)
	(have_image Star87 infrared3)
	(have_image Planet88 thermograph2)
	(have_image Star89 infrared3)
	(have_image Planet90 infrared3)
	(have_image Planet91 thermograph2)
	(have_image Phenomenon92 thermograph1)
	(have_image Phenomenon93 thermograph2)
	(have_image Phenomenon94 thermograph4)
	(have_image Phenomenon95 thermograph2)
	(have_image Phenomenon96 thermograph1)
	(have_image Star97 infrared3)
	(have_image Star98 thermograph4)
	(have_image Star99 thermograph4)
	(have_image Phenomenon100 infrared3)
	(have_image Planet101 thermograph2)
	(have_image Star102 image0)
	(have_image Star103 thermograph1)
	(have_image Phenomenon104 thermograph4)
	(have_image Planet105 image0)
	(have_image Star106 thermograph1)
	(have_image Planet107 thermograph4)
	(have_image Star108 thermograph4)
	(have_image Star109 thermograph1)
	(have_image Star110 infrared3)
	(have_image Planet111 image0)
	(have_image Phenomenon112 image0)
	(have_image Planet113 thermograph2)
	(have_image Planet114 thermograph4)
	(have_image Planet115 infrared3)
	(have_image Phenomenon116 image0)
	(have_image Phenomenon117 infrared3)
	(have_image Phenomenon118 infrared3)
	(have_image Phenomenon119 thermograph2)
	(have_image Star120 image0)
	(have_image Phenomenon121 infrared3)
	(have_image Star122 image0)
	(have_image Phenomenon123 thermograph2)
	(have_image Star124 thermograph4)
	(have_image Phenomenon125 thermograph4)
	(have_image Star126 thermograph2)
	(have_image Phenomenon127 thermograph4)
	(have_image Star128 infrared3)
	(have_image Star129 thermograph2)
	(have_image Phenomenon130 infrared3)
	(have_image Planet131 thermograph4)
	(have_image Planet132 thermograph2)
	(have_image Star133 thermograph1)
	(have_image Phenomenon134 infrared3)
	(have_image Star135 thermograph4)
	(have_image Planet136 thermograph4)
	(have_image Phenomenon137 thermograph1)
	(have_image Planet138 infrared3)
	(have_image Star139 thermograph1)
))

)
